### PR TITLE
Add Formatter plugin

### PR DESCRIPTION
**Pull request by bitst0rm**
Formatter is a Sublime Text 3 plugin to beautify and minify source code.

Features:
  - Support more than 20 major languages
  - Format whole file, single or multi selections
  - Config files available for each 3rd party plugins
  - Work offline

https://github.com/bitst0rm-pub/Formatter

@Thom1729 my previous commit #7421 has been accidentally updates by the pull bot, so it was auto empty. I uninstalled it now. Could you please review again, Thank you.

### CODE REVIEW

**Comment by bitst0rm** [comment]
Sorry for the repeating the same pull requests, because i got troubles with this one:
https://probot.github.io/apps/pull/
It auto deleted all my commits in my pull requests here :(
Hope its ok yet.

**Comment by Thom1729** [comment]
- You shouldn't modify `sys.path` -- it's shared by all packages. There's a [`pyyaml` dependency](https://github.com/packagecontrol/pyyaml) that should solve your problem.
- Because the package is declared to be compatible only with ST3, it isn't necessary to check the version before running.
- In `RunFormatThread.run`, you should use `with self.command_lock:` instead of manually acquiring and releasing it. This will ensure that it is released if an error is raised.
- Each item in a `Selection` is a `Region`, so in `has_selection` you can just use `sel.empty()`:

```python
    def has_selection(self):
        return any(not sel.empty() for sel in self.view.sel())
```

- Reloading modules is surprisingly subtle. I'd recommend using [AutomaticPackageReloader](https://github.com/randy3k/AutomaticPackageReloader) instead of a hand-rolled solution.
- The logic in `setup_config` looks spot-on.
- I didn't review all of the individual formatters.

**Comment by bitst0rm** [comment]
@Thom1729 Thank you for your review! :)

> * You shouldn't modify `sys.path` -- it's shared by all packages. There's a [`pyyaml` dependency](https://github.com/packagecontrol/pyyaml) that should solve your problem.

The plugin should work offline, therefore i didn't use that dependency.

> * Because the package is declared to be compatible only with ST3, it isn't necessary to check the version before running.

Done. It has been improved.

> * In `RunFormatThread.run`, you should use `with self.command_lock:` instead of manually acquiring and releasing it. This will ensure that it is released if an error is raised.

Done. It has been improved.

> * Each item in a `Selection` is a `Region`, so in `has_selection` you can just use `sel.empty()`:
> 
> ```python
>     def has_selection(self):
>         return any(not sel.empty() for sel in self.view.sel())
> ```

Done. It has been improved.

> * Reloading modules is surprisingly subtle. I'd recommend using [AutomaticPackageReloader](https://github.com/randy3k/AutomaticPackageReloader) instead of a hand-rolled solution.

I did used it, but sometimes i turn it off.

> * The logic in `setup_config` looks spot-on.
> * I didn't review all of the individual formatters.

Thank you :)

**Comment by Thom1729** [comment]
> The plugin should work offline, therefore i didn't use that dependency.

You can vendor the whole thing if you want, just use relative imports instead of modifying `sys.path`. It looks like the library already uses relative imports internally, so you won't have to rewrite them.

**Comment by bitst0rm** [comment]
I use relative imports internally instead of modifying `sys.path` in my last commit.

**Comment by Thom1729** [comment]
A couple of things I missed before:

- Ideally, you should remove the copied stuff from the User directory [when the plugin is uninstalled](https://packagecontrol.io/docs/events).
- I notice that the shared `os.environ` is modified. Can this be avoided?

**Comment by bitst0rm** [comment]
> * Ideally, you should remove the copied stuff from the User directory [when the plugin is uninstalled](https://packagecontrol.io/docs/events).

Users would lost all the config that they work hart to adjust them, therefore i did not build such function in  `plugin_unloaded()`

> * I notice that the shared `os.environ` is modified. Can this be avoided?

This cannot be avoidable, since users could install plugins local outside the default paths. If i recall, SublimeLinter uses the same approach.

**Comment by Thom1729** [comment]
> This cannot be avoidable, since users could install plugins local outside the default paths. If i recall, SublimeLinter uses the same approach.

I presume that you need the environment set up for the `Popen` call in `exec_cmd`. You can pass an `env` argument to `Popen`. This will apply those values to the environment of the child process without changing the environment of the parent.

**Comment by bitst0rm** [comment]
I will look at this tomorrow, its too late now... have thanks & see you again

**Comment by bitst0rm** [comment]
so i changed a few lines to use `Popen env`. The plugin does not touch on `sys.path` and `os.environ` anymore.

**Pull request merged**
