### PR TITLE
Add Better Logos Syntax Highlighting

### PR DESCRIPTION
**Pull request by ptcong**
Better Logos Syntax for Sublimetext (supports C,C++, Objective-C, Objective-C++)

Supports all syntax of Logos http://iphonedevwiki.net/index.php/Logos

### CODE REVIEW

**Comment by Thom1729** [comment]
You have to alphabetize your package in the channel JSON file.

**Comment by Acecool** [comment]
The current error: Expecting property enclosed in double quotes means you likely incorrectly formatting your JSON... In these files, you can't have a trailing comma... For instance a = { a = true, b = true, } would be bad because b = true has a comma... Also x, if there is nothing after the table, shouldn't have a comma after either.

**Comment by Thom1729** [comment]
It looks like you may have to add `"tags": true` to the channel entry (like other entries have). Also, it definitely needs to be alphabetized.

**Comment by Thom1729** [comment]
@Acecool ping

**Pull request closed without merging**
