### PR TITLE
rename auto dark plugin

### PR DESCRIPTION
**Pull request by smac89**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is AutoDarkLinux (Previously Auto Dark mode for Linux)

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
You also need to change its position in the list.

**Comment by smac89** [comment]
@braver Fixed!

**Comment by braver** [comment]
Sorry, forgot all about the main thing with renaming packages: you need to add the previous name, as an array, under the “previous_names” key. You can find plenty of examples of this. Doing so will ensure existing users are migrated to the new name, and keeps the index tidy.

**Comment by smac89** [comment]
@braver done

**Comment by braver** [comment]
Thanks, but please revert all the formatting changes to other entries.

**Pull request merged**
