### PR TITLE
Adding JsonSymbolsAndColorSyntax

### PR DESCRIPTION
**Pull request by Monox18**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
That's a cool concept and I like how you've implemented it. The only thing I would worry about is the name of the package. From your PR here I had no clue what to expect, and the README surprised me. That might mean that people won't be able to find your package. The functionality reminds me a little of features like Indent Rainbow and Rainbow Braces that exist for other editors, or [Rainbow Brackets](https://packagecontrol.io/packages/RainbowBrackets) for ST. May I suggest "JSON Rainbow"?

**Comment by Monox18** [comment]
Thanks for the feedback. 

Not sure that `Rainbow` is a keyword people are actually searching. Seems very specific to me. But I do agree the current name might not be the most precise. Maybe we can agree `Color` is more suitable than `Rainbow` when people are thinking about syntax coloring.

Let's see, this package has 3 main purposes with JSON files: 
1) Allow symbol navigation
2) Color nested keys. Rainbow Color targeted the braces whereas here I'm targeting the string within the quotes.
3) Display idented keys in the additional Sublime Text plugin [Sublime Outline](https://github.com/warmdev/SublimeOutline)

So with those main points I can think of `JsonSymbolsColorAndNavigation`, `JsonColorKeysAndNavigation`, `JsonColorAndNavigateKeys`, etc.. Though there's a lot of keyword sutffing in the name, it provides the best chances of being discovered as Package Control search dialog in ST only uses the name and not the description.

Let me know and I will update both name and readme accordingly. Also after like 30 mins deciding on the name `JsonColorAndNavigateKeys`  seems the most descriptive and accurate.

**Comment by braver** [comment]
> Also after like 30 mins deciding on the name JsonColorAndNavigateKeys seems the most descriptive and accurate.

Sounds good to me! I could also see JsonColorsAndNavigation or even "Json Colors and Navigation" (it's ok to have spaces).

**Comment by Monox18** [comment]
Thanks for the feedback. I have pushed the changes.

**Comment by braver** [comment]
:shipit:

**Pull request merged**
