### PR TITLE
add completions for cocos2dx

### PR DESCRIPTION
**Pull request by wshxbqq**
add code auto-complete for cocos2dx

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

By convention, your package is providing "completions" and not "auto-completions", because those would be context-aware (e.g. local variables and/or type awareness). Please adjust the label.

**Comment by wshxbqq** [comment]
set tags true and labels completions

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

You should not include `package-metadata.json` in your repo. This file is will be automatically created by Package Control on installation.

**Comment by wshxbqq** [comment]
remove package-metadata.json
Semantic versions consist of exactly three numeric parts.

**Pull request merged**
