### PR TITLE
Adding Clarity language package

### PR DESCRIPTION
**Pull request by dmitrytorba**
This is a package for supporting the smart contract programming language [Clarity](https://docs.blockstack.org/core/smart/overview.html). 

Repo: https://github.com/dmitrytorba/clarity

### CODE REVIEW

**Comment by FichteFoll** [comment]
Since this seems to be an addon for LSP, I suggest naming it `LSP-Clarity` as per the naming convention. /cc @rwols

**Comment by rwols** [comment]
Yes, it should be named LSP-Clarity because that will make the plugin load at a later point in time than the base LSP plugin. It has no significance at this point but will in the future.

Also consider making a pull request over at https://github.com/sublimehq/packages/ to add `.clar` to the file extension list of Lisp.sublime-syntax.

**Comment by rwols** [comment]
I'm also somewhat confused by the NpmClientHandler inheritance. It seems the language server is written in Rust and has pre-built binaries available on the release page: https://github.com/lgalabru/clarity-lsp/releases/tag/2020-05-27

A similar kind of language server and convenience downloader is LSP-TexLab. You might want to look at how that convenience plugin handles that server: https://github.com/sublimelsp/LSP-TexLab

**Comment by dmitrytorba** [comment]
thanks for the review, I will take a look

**Comment by rwols** [comment]
The amount of LSP-* packages is getting out of hand, so we've made our own package repository. Please submit your pull request there: https://github.com/sublimelsp/repository/

**Pull request closed without merging**
