### PR TITLE
Added Simple Import Package

### PR DESCRIPTION
**Pull request by vini175pa**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by vini175pa** [comment]
Is it ok now?

**Comment by FichteFoll** [comment]
Note that there is also a `1.0.0` tag on your repo, which would get picked up as the most recent version, although it is not the most recent commit (which is tagged as `v0.1.0`).

**Comment by vini175pa** [comment]
Oh, sorry. I deleted it. I didn't realize that, because I actually edited that release, but Github created another one.

**Pull request merged**
