### PR TITLE
YamlToJson from ryandao and Power Query syntax from Kenneth Scrubbard

### PR DESCRIPTION
**Pull request by dannysummerlin**
- [x] I'm helping the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***

My packages are two open source packages from other authors who have not updated or published in a long time.

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by dannysummerlin** [comment]
I have added a license file to the YamlToJson repo, but the Power Query repo already had one so I'm not sure what that warning is about

**Comment by braver** [comment]
I'm not against publishing forks of existing work like this, but the lack of licenses explicitly allowing that in the original work complicates it. 

> but the Power Query repo already had one so I'm not sure what that warning is about

I don't see a license in the [original repo](https://github.com/PowerQueryforAccountants/PowerQuerySublimeSyntax)? 

I'm no lawyer, but seems the cleanest way to do this is to publish the repos ad verbatim, ie. without adding a license of your own. We don't require the license, it's just a recommendation to prevent confusing situations like this. So, you don't really need to add a license if it's not your own work.

**Comment by dannysummerlin** [comment]
Ah, thanks for the suggestion! I just swapped in the original repos so that any licensing is clear from there, let me know if anything else needs tweaking!

**Comment by braver** [comment]
Oh, sorry, that’s not quite what I meant. The entries here should point to your forks. That way they can’t suddenly break if they decide to move them or whatever. But you simply fork them without adding license files, and we publish them that way.

**Comment by dannysummerlin** [comment]
Oh haha I'll get this right one day! I dropped the licenses, thanks for walking me through all this!

**Comment by braver** [comment]
No problem! I'm only seeing the YamlToJson addition now, is that correct?

**Comment by dannysummerlin** [comment]
Oh yeah, I guess so - I had missed that the Power Query bit was already in there, remembering things is overrated

**Comment by braver** [comment]
Oh, you’re right. Well good 👍🏻

**Pull request merged**
