### PR TITLE
Add Procapy package

### PR DESCRIPTION
**Pull request by thomasthorsen**
This package is an inline calculator oriented towards programmers and contains signed/unsigned bit-width truncation functions that are particularly useful when working with development of embedded software, integer algorithms, reverse engineering and binary analysis. I will update the description to clarify the functionality, just want this added so I can start using it more easily in different locations.

I've run the tests and they pass.

### CODE REVIEW

**Comment by thomasthorsen** [comment]
The key binding warnings (flagged by the packagecontrol-bot) are not actually conflicting. The particular default keybindings are only used when panels are open (search panels), and in that case they take precedence over the key bindings in this addon. The key bindings of this addon are only active (and only needed) when no panels are shown.

**Comment by FichteFoll** [comment]
Your package is significantly lacking documentation on usage and motivation (as in: what makes using the package worthwhile). I could only find out from reading the source code. Most specifically you should explain what it does and highlight the functions and variables that you provide for `eval` (in addition to the math and cmath modules).

**Comment by thomasthorsen** [comment]
You're right. I need to copy and adapt the information already at https://github.com/thomasthorsen/procapy in the README.me and add some information about what the addon does and how it works.

**Comment by FichteFoll** [comment]
@thomasthorsen ping

**Comment by thomasthorsen** [comment]
I'm here, but very busy with other stuff currently. I'll get around to fixing it soon

**Comment by thomasthorsen** [comment]
@FichteFoll I have now finally added the necessary documentation of the package along with some usage examples. Sorry about the delay, I've been extremely busy!

**Comment by thomasthorsen** [comment]
Anything else required? If not, can you please push it through?

**Comment by thomasthorsen** [comment]
@FichteFoll ping

**Pull request merged**
