### PR TITLE
Add a theme plugin package info named "Vine Theme" based on "Boxy Theme".

### PR DESCRIPTION
**Pull request by xufanchn**
Update description: Add the theme plug-in package information named "Vine Theme" based on "Boxy Theme". The original "Boxy Theme" theme was removed from the ST plug-in market because the original author deleted the code repository on github. However, my friends and I liked this theme very much, so I fork the source code and repackaged it.

### CODE REVIEW

**Comment by braver** [comment]
If this is a straight repackage, and the original license allows it (I believe it's MIT so it should be good), we can replace the existing Boxy Theme entry with this one. How's that sound to you?

**Comment by xufanchn** [comment]
> If this is a straight repackage, and the original license allows it (I believe it's MIT so it should be good), we can replace the existing Boxy Theme entry with this one. How's that sound to you?

**Comment by xufanchn** [comment]
> > If this is a straight repackage, and the original license allows it (I believe it's MIT so it should be good), we can replace the existing Boxy Theme entry with this one. How's that sound to you?

yep, I can accept it, the original intention is the same, I just want to use this theme more simply.

**Comment by braver** [comment]
Alright, for this to fly, I think the best would be to not introduce a new package, but replace the details link for the old Boxy entry. You would need to go through things like missing images in the readme, and double checking the package name in things like themes and settings. Also make sure build tools and such are excluded from the package using `.gitattributes`. 

In any case, the entry you propose doesn't pass mustard either because all the documents still talk about "Boxy" and not "Vine". So one way or the other some work to do still.

**Comment by xufanchn** [comment]
ok, thanks. I will check it and resubmit.

**Pull request closed without merging**
