### PR TITLE
Added CloseTabsLeft

### PR DESCRIPTION
**Pull request by deXterbed**
There's no support for closing tabs on the left in ST2 as of now. TBH i never use the existing "close tabs on the right" command and I was a bit shocked to find out that there wasn't an option for the opposite, so there goes my first stab at python and sublime plugins. Would love some feedback from you guys. Thanks a lot for the docs and all the help!

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by deXterbed** [comment]
@FichteFoll done!

**Comment by FichteFoll** [comment]
In your package info you define the tag prefix as `"st2-"`, but you don't use that prefix for your tags. Either you set the tag prefix to `true` (which is either none or `"v"`) or push a prefixed tag to the repo.

**Comment by deXterbed** [comment]
thanks @FichteFoll, updated PR (replaced "st2-" with true)

**Comment by deXterbed** [comment]
thank you so much :)

**Pull request merged**
