### PR TITLE
add poetry support

### PR DESCRIPTION
**Pull request by jgirardet**
frontend in sublime to work with https://github.com/sdispater/poetry

### CODE REVIEW

**Comment by Thom1729** [comment]
```python
# Let it like this wainting for toml depedency in package contrl
# https://github.com/wbond/package_control_channel/pull/7298
import sys

sys.path.append(os.path.abspath(os.path.dirname(__file__)))
import toml
```

Can this be removed now that the dependency exists?

**Comment by jgirardet** [comment]
> Can this be removed now that the dependency exists?
there is a problem with the toml dependency. I do not know why. @FichteFoll confirmed it in https://github.com/wbond/package_control_channel/pull/7343

**Comment by Thom1729** [comment]
Is that still not working?

**Comment by wbond** [comment]
It would appear @jgirardet hasn't created any semver tags yet: https://github.com/jgirardet/sublime-toml/tags. Once that is created, Package Control will include it in the channel.

**Comment by jgirardet** [comment]
my bad, tag is added and  I fixed what @Thom1729 requested in poetry

**Pull request merged**
