### PR TITLE
Unity 3D Shader: Add issues and move to tags releases

### PR DESCRIPTION
**Pull request by petereichinger**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need the issues url, it wil be detected automatically (and has been before).

**Comment by petereichinger** [comment]
I removed the line (see last commit).

Maybe I didn't look in the right place but maybe the Docs section should be updated?

**Comment by FichteFoll** [comment]
Not sure what you used, but it's mentioned [here](https://github.com/wbond/package_control/blob/d3bc04fd5c0c4bdb476a3ea798e6815508dc9bac/example-repository.json#L133-L135).

**Comment by petereichinger** [comment]
I seem to have misread that comment...

Thanks!

**Pull request merged**
