### PR TITLE
A MarkDown inspired PlainTasks theme for Sublime Text.

### PR DESCRIPTION
**Pull request by ronilaukkarinen**

### CODE REVIEW

**Comment by FichteFoll** [comment]
How about adding the scheme (it's a "color scheme") to the https://github.com/aziz/PlainTasks repo directly? cc @vovkkk

**Comment by vovkkk** [comment]
Sure, we accepted all proposed schemes so far.
On the other side, it is simpler for author to change it, keeping scheme in own repo.
Either way is okay for me.

**Comment by FichteFoll** [comment]
Same here, I can see pros and cons for either option. Your call, @ronilaukkarinen.

**Comment by ronilaukkarinen** [comment]
Hello. Yes, seems logical. This is my first package, so was not quite sure
what to do. The reason I am implementing this is that I noticed my theme
getting erased every time after updates and of course the wider audience
can be achieved this way. I am going to send this directly to PlainTasks,
so this can be closed. Thanks a bunch!

**Pull request closed without merging**
