### PR TITLE
Sass: v3 tags, prep for 4169+

### PR DESCRIPTION
**Pull request by braver**
cc @deathaxe

### CODE REVIEW

**Comment by deathaxe** [comment]
How about using least required ST build number as prefix?

LSP started to use it and it has proven useful as it clearly indicates which version is required.

**Comment by braver** [comment]
Yeah that’s smart, we’ll probably need to freeze and branch off some more for future versions

**Comment by deathaxe** [comment]
Appears bundling CSS is an easy task.

Hence I suggest creating a `4107-` prefix which points to `st4107` branch, which includes bundled CSS from ST4169 and a `4169-` prefix, which points to current master (without the CSS file).

The `v2-` and `v3-` prefixes are obsolete then and all stable ST4 releases are served with latest fixes.

**Comment by deathaxe** [comment]
With the tags and branch created in Sass Repo, we could go with this.

```json
		{
			"name": "Sass",
			"details": "https://github.com/SublimeText/Sass",
			"labels": ["language syntax", "scss", "sass", "completions", "snippets"],
			"releases": [
				{
					"sublime_text": "<4107",
					"tags": "st3-"
				},
				{
					"sublime_text": "4107 - 4168",
					"tags": "4107-"
				},
				{
					"sublime_text": ">=4169",
					"tags": "4169-"
				}
			]
		},
```

**Comment by braver** [comment]
@deathaxe looks like we're all set. Let me know if you're also ready to hit merge here.

**Comment by deathaxe** [comment]
Let's go.

**Comment by deathaxe** [comment]
We propably should merge ASAP. I wasn't aware of Package Control already picking up the 4.0.0 tag.

**Comment by deathaxe** [comment]
It might break SCSS for older ST4 releases.

**Comment by braver** [comment]
Oh, right, of course it would do that. I added a message, moved some tags around. Should be all good now 🤞🏻

**Comment by deathaxe** [comment]
Backported it to st4107 and st4134 branches and updated their tags.

4.0.0 is currently set onto st4134 branch so everyone upgrading until next crawler cycle will get it with bundled CSS to avoid failures.

**Pull request merged**
