### PR TITLE
Add FormatX

### PR DESCRIPTION
**Pull request by cj1128**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by cj1128** [comment]
Can you give some links? I don't find any formatter like FormatX in package control.

FormatX is formatter agnostic, the main usage is that the user configures the shell command, FormatX runs the command with the file as stdio and uses the stdout to replace the file. It doesn't bundle any formatters.

**Comment by braver** [comment]
That sounds a lot like Fmt:
https://packagecontrol.io/packages/Fmt

**Comment by jrappen** [comment]
Please do not override captions for "Preferences" and "Package Settings" in your menu file.

Simply targetting by id should suffice.

**Comment by cj1128** [comment]
I think `Fmt` solves my problem so there is no need for `FormatX` now.

**Pull request closed without merging**
