### PR TITLE
Added Sfortzando package

### PR DESCRIPTION
**Pull request by leesavide**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for sfcommand ###############################

### Repository checks ###


For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by leesavide** [comment]
Sorry about that: Forgot to double-check the pull-request's details URL.

**Comment by leesavide** [comment]
@FichteFoll The error's been fixed.

**Comment by math2001** [comment]
Your `messages.json` pointed to `messages/install.txt`, which doesn't exists.

**Comment by leesavide** [comment]
@FichteFoll Now **that's** been fixed :+1:

**Comment by FichteFoll** [comment]
## Report for Sfortzando ##############################

### Repository checks ###

No failures

No warnings

### Package checks ###

No failures

Reporting 3 warnings:
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: Syntaxes/PostScript.sublime-syntax
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: Syntaxes/ABC Notation.sublime-syntax
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: Syntaxes/ABC Formatting Extension.sublime-syntax

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

You might want to adjust your repo's description to be a little more specific, since that's what would be shown on https://packagecontrol.io/search/abc.

**Comment by leesavide** [comment]
@FichteFoll It's lucky that I had created the fallback `.tmLanguage` files beforehand, then transitioned them into the `.sublime-syntax` format; I've added the fallback files & also edited my repo's description like you suggested. :slightly_smiling_face: 

I wasn't aware that Sublime Text would require `.tmLanguage` files as fallbacks, since none of it's documentation even mentioned that it would default to doing so. Sorry for all the back and forth on this PR (´●▽● `)

**Comment by leesavide** [comment]
The errors should all be fixed. Try again, please?

**Comment by FichteFoll** [comment]
> I wasn't aware that Sublime Text would require .tmLanguage files as fallbacks, since none of it's documentation even mentioned that it would default to doing so.

Well, `.sublime-syntax` is a new format, so obviously older releases wouldn't be able to handle it. The options are either not supporting older releases (which is mostly ST2 at this time, because both dev and beta releases have had support for this for over a year now) or adding `.tmLanguage` fallback files that older releases understand.

**Comment by FichteFoll** [comment]
Also, please refrain from cherry-picking commits from the master branch and instead rebase (and force-push) or don't do anything at all, because it confuses Github's diff view.

**Comment by leesavide** [comment]
(´●▽● `) Ah sorry, I wasn't aware that it would cause issues. Git is still rather new to me. But thank you for the help you've given me so far! (●▽● )

**Pull request merged**
