### PR TITLE
added Padawan.sublime(Padawan.php integration) package

### PR DESCRIPTION
**Pull request by mkusher**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Due to the way Package Control downloads repositories (via zip source archives) and github not including submodules there, you can not use submodules like this. Consider using `git subtree` instead.

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by mkusher** [comment]
ok, sorry. Will fix this soon

**Comment by mkusher** [comment]
@FichteFoll fixed submodule problem and moved to semantic versioning

**Comment by FichteFoll** [comment]
You should not be using dots in the package name, this will cause major issues with loading the Python plugin files.

**Comment by mkusher** [comment]
Damn I, sorry. Fixed version and remove `.php` from package name

**Pull request merged**
