### PR TITLE
add twilight bright color scheme

### PR DESCRIPTION
**Pull request by sepisoad**
add twilight bright color scheme

### CODE REVIEW

**Comment by braver** [comment]
Please have a look at the reports from the bot (e.g. alphabetical sorting). Also maybe consider using .gitattributes to "export-ignore" the png from the final package to save on some storage and bandwidth.

**Comment by braver** [comment]
Please respond to continue the PR.

**Comment by sepisoad** [comment]
wow, I totally missed it, will handle the errors shortly

sorry

**Comment by sepisoad** [comment]
what happenes at "CI / trigger-review (pull_request)" that causes the fail?

**Comment by braver** [comment]
Sometimes it just wonks out. You haven't tagged a release yet though, have another look at our minimum requirements.

**Comment by sepisoad** [comment]
foo

**Pull request closed without merging**
