### PR TITLE
Add Ballerina language support for sublimetext 3

### PR DESCRIPTION
**Pull request by dakshika**
Please provide the following information:

 - Link to your code repository: https://github.com/ballerinalang/plugin-sublimetext3

### CODE REVIEW

**Comment by dakshika** [comment]
Is there any issue on merging this?

**Comment by wbond** [comment]
@dakshika Can you update the `sublime_text` selector, as instructed in the automated review above?

**Comment by FichteFoll** [comment]
@dakshika ping

**Comment by dakshika** [comment]
Sorry I'll update this soon

**Pull request closed without merging**
