### PR TITLE
add SelectMultiLines

### PR DESCRIPTION
**Pull request by a112121788**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

Also, please do not override default bindings.

**Comment by a112121788** [comment]
I have  changed "branch": "master" to "tags": true .

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by a112121788** [comment]
I have change the tag by  semantic version tag .

**Pull request merged**
