### PR TITLE
Added RepoSwitcher package

### PR DESCRIPTION
**Pull request by yoniamir**
Please provide the following information:

 - Link to your code repository: https://github.com/yoniamir/RepoSwitcher
 - Link to the tags page with at least one [semver](http://semver.org) tag: Didnt see other repos in the list have this tag.

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
Why is it not available on Windows?

For the tags, you must set `tags: true` instead of `branch: master`, and just push some tags:

```
$ git tag v0.1.0
$ git push origin v0.1.0
```

**Comment by yoniamir** [comment]
@math2001 
1. Added support for windows (in plugin as well). 
2. Set tags in config - Done.
3. Push tags - Done.

**Comment by yoniamir** [comment]
@math2001 Any ETA to when this can be merged?

**Comment by FichteFoll** [comment]
https://packagecontrol.io/docs/submitting_a_package#Step_4


## Report for RepoSwitcher ############################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 1 failures:
- The binding ['ctrl+o'] unconditionally overrides a default binding
    File: Default.sublime-keymap

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

By the way, Sublime Text has a nice "project switcher" that allows you to switch between your recent ST projects.

**Pull request closed without merging**
