### PR TITLE
added Hot Dog Stand

### PR DESCRIPTION
**Pull request by SomeKittens**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Did I miss a joke or something?

**Comment by SomeKittens** [comment]
For some context: http://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/

**Comment by FichteFoll** [comment]
Well ... okay, I guess ...

**Comment by wbond** [comment]
@SomeKittens You should update the github repo description and readme since this is a *color scheme*, not a *theme*.

**Comment by SomeKittens** [comment]
@wbond I'm afraid I don't know the difference...

**Comment by wbond** [comment]
Themes change the looks of the input panels and the sidebar. Color schemes change the color of the text you are editing.

Either way, this is what is known as a "Color Scheme".

Themes:
 - https://packagecontrol.io/packages/Theme%20-%20Soda
 - https://packagecontrol.io/packages/Theme%20-%20Flatland

Color Schemes:
 - https://packagecontrol.io/packages/Solarized%20Color%20Scheme
 - https://packagecontrol.io/packages/Base16%20Color%20Schemes

**Comment by SomeKittens** [comment]
@wbond Thanks for the explanation - README has been changed.

**Comment by FichteFoll** [comment]
This package is not visible on package control because you didn't push a tag.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by SomeKittens** [comment]
Tagged, thanks!

**Pull request merged**
