### PR TITLE
Add SuperElixir.

### PR DESCRIPTION
**Pull request by edelvalle**
- Repo: https://github.com/edelvalle/SuperElixir
 - Tags: https://github.com/edelvalle/SuperElixir/releases

### CODE REVIEW

**Comment by wbond** [comment]
Please review the warning in my review

**Comment by edelvalle** [comment]
@wbond how do you run this test? I just can find how to check the channel but not how to run the package reviewer.

**Comment by wbond** [comment]
If you rebase on master, it is now part of the Travis CI check.

**Comment by edelvalle** [comment]
@wbond All issues solved, release 0.0.3 of SuperElixir is ready.

**Pull request merged**
