### PR TITLE
Removed the other repos and added them to previous_names

### PR DESCRIPTION
**Pull request by rajeshvaya**
This request is in reference to previous [pull request - #3330](https://github.com/wbond/package_control_channel/pull/3330)

Added previous_names of other repos

### CODE REVIEW

**Comment by rrg** [comment]
Sorry for the delay, I just checked this after someone responded here http://stackoverflow.com/questions/19665615/sublime-text-text-list-of-open-files/19694952#19694952

I'm fine with the change, can you please get this package back to work. 

Thanks

**Comment by FichteFoll** [comment]
@rrg: @rajeshvaya appears to be rather active an the last push on https://github.com/rajeshvaya/Sublime-Extended-Tab-Switcher was 4 days ago. Please post issues there, unless he does not respond to them anymore or other issues with maintainer changes arise (or similar).

**Comment by rrg** [comment]
Sorry I do not understand what the problem is? How do I get my extension back to package manager?

**Comment by FichteFoll** [comment]
We try to keep duplicated packages at a minimum because of several reasons, mainly:

1. If the feature provided is trivial, the user is prompted with different packages all achieving practically the same thing and confused about which he should use.
2. If the difference is trivial, the user is again confused about which he should use, but the package authors or maintainers are also effectively doubling their work (of maintainance). If they worked together on the same package (either by collaborating or by proposing pull requests) the community would be.
3. If one pf the authors or maintainers can not keep maintaining his version of a package it is abandoned. With two or more authors collaborating the chance of this happening is reduced.

There are exceptions to this rule in cases where developers simply can't or don't want to work together due to certain reasons or the packages themselves are different enough in that they provide different use cases and would attract different users. However, there might also still be the option of combining these kind of packages by including functionality of one in the other.

However, there is no definitive objective criteria here.

-

In your particular case, you've been asked about 9 months ago about your stance with your package, if you'd like to continue developing on it, have @rajeshvaya's features be implemented into your package or whatever. Since your package has been merged into ExtendedTabSwitcher as a result of no answer, your package now qualifies as a new package and needs to satisfy the criteria of being a non-duplicate again.

**Comment by FichteFoll** [comment]
After looking into your package I realize that your package actually provides different functionality from the other three packages (two of which were merged into one other) in that it provides the open files in a text form, likely for copy and paste purposes. I am not sure why I thought that your package's functionality was too similar to the other ones 9 months ago, but I certainly don't see it now. The functionality of course *could* be merged into ExtendedTabSwitcher since the have somewhat similar functionality, but it's different enough to warrant being its own package.

Additionally, after a few searches I was not able to find a similar package to this currently in the list, which means you package would satisfy the non-duplicate criteria.

I sincerely apologize for my misjudgment that I did not verify due to the assumption of the merge being correct. Let's continue this in #4169.

**Comment by rrg** [comment]
Thank you, I'll take a look at the other thread, feel free to close this down.

**Pull request merged**
