### PR TITLE
Adding cfmldocplugin

### PR DESCRIPTION
**Pull request by MFernstrom**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You probably changed line endings or indentation of all lines. Please check and rebase/squash/whatever.

**Comment by MFernstrom** [comment]
Ah, so I did. Forgot to turn off a jsbeautifier plugin. Fixing.

**Comment by MFernstrom** [comment]
Fixed, committed and pushed.
As a Git newbie, is there anything I need to do now, a fresh request or so?

**Comment by FichteFoll** [comment]
Well, you should squash your commits because currently there are two commits changing almost every line and messing with git blame and similar. Refer to your favorite online tutorial I guess.

You could also start fresh, which would probably be easier if you don't know how to squash but is just avoiding the problem than solving it.

**Comment by FichteFoll** [comment]
@MFernstrom ping

**Comment by MFernstrom** [comment]
Hi FichteFoll, I believe I started over fresh after turning off the beautifier, this does remind me to find a Git tutorial though.

**Comment by FichteFoll** [comment]
Ah correct, it was #4222. Didn't notice for some reason.

**Comment by MFernstrom** [comment]
No worries, I forgot to close this one anyway.

**Pull request closed without merging**
