### PR TITLE
added SassDirector

### PR DESCRIPTION
**Pull request by Stephn-R**
See [https://github.com/Stephn-R/sass-director-sublime](https://github.com/Stephn-R/sass-director-sublime)

### CODE REVIEW

**Comment by FichteFoll** [comment]
I checked your code and it shouldn't have any issues running on ST2, so you might want to change that.

**Comment by Stephn-R** [comment]
Just ran a test with ST2, no issues. I will mark it accordingly

**Comment by FichteFoll** [comment]
What exactly should I review?

**Comment by Stephn-R** [comment]
Sorry, closing so I can update the commit to include ST2 support

**Pull request closed without merging**
