### PR TITLE
Update i.json

### PR DESCRIPTION
**Pull request by jabyrd3**
Sorry about the last pull request, I forgot my fork was so old.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can delete your `package-metadata.json` as it will be replaced on install.
You can also delete your `.no-sublime-package` file as it's not necessary and should only be included if you really need it.

I don't think it is necessary to include the requests package for just two http POST requests, that's possible with urllib as well. This wouldn't be a problem if the requests module existed as a dependency for Package Control already but we'll have to work something out about that in the future.

And in other news ... why would you do this? [`s = sublime.window`](https://github.com/jabyrd3/sublime-ixio/blob/9f8b617376d688e1bfd28f2ef886c9737f7b5411/ixio.py#L24)

**Comment by jabyrd3** [comment]
Thanks, I've deleted those two files. Tomorrow I'll rework the package to use urllib again.

The `s = sublime.window` bit is an embarrassing leftover that snuck in. Thanks for spotting it.

**Comment by jabyrd3** [comment]
Using urllib instead of requests now, removed .no-sublime-package and package-metadata.json. The newest release tag is 1.0.2.

**Comment by FichteFoll** [comment]
Well, that's ... a lot of commits.

Anyway, looking good now. I recommend you to not load the settings at the beginning though as the user might change them while ST is running and they will not get picked up this way.

**Pull request merged**
