### PR TITLE
add file header creator

### PR DESCRIPTION
**Pull request by matthewgao**
Automatically add file header while create a new file or save a empty file

### CODE REVIEW

**Comment by wbond** [comment]
A few notes:

 1. Sublime Text will only load python files in the root of a package directory
 2. We no longer accept branch-based releases for packages. You'll have to create a git tag for each release (the name should be a semantic version number, e.g. `1.0.0`) and change `"branch": "master"` to `"tags": true`.
 3. The `sublime-enhanced` label is really a construct created by @shagabutdinov to tie the collection of his packages together. I don't think it makes sense to add here.

However, in the grand scheme of things, it almost seems you are re-creating https://packagecontrol.io/packages/FileHeader. How is this different?

**Comment by FichteFoll** [comment]
Also, what are notable differences to the other "header" or "template" packages.

**Comment by FichteFoll** [comment]
@matthewgao ping

**Comment by matthewgao** [comment]
Sorry, I missed this notification.

Yes, I see there has already had a FileHeader add-on, I didn't notice that before I implement mine. And mine makes no difference with FileHeader, so just ignore me. :)

**Comment by FichteFoll** [comment]
Okay.

**Pull request closed without merging**
