### PR TITLE
Added YAML Macros package.

### PR DESCRIPTION
**Pull request by Thom1729**
Repository: https://github.com/Thom1729/YAML-Macros/tags
Tags: https://github.com/Thom1729/YAML-Macros/tags

### CODE REVIEW

**Comment by Thom1729** [comment]
The package should be compatible with older versions. The `sublime-syntax` is an example file; it doesn't need to be loaded by Sublime. The only thing that older versions can't do is run the tests for that example file.

**Comment by wbond** [comment]
Just a heads up @Thom1729, if you release it with the existing git tags, no one will even see it unless they opt in to prereleases for this package name.

**Comment by Thom1729** [comment]
It's still undergoing rapid changes today. When I release "v1.0.0", it should be generally available, right?

**Comment by wbond** [comment]
Yes, any tag with an optional leading `v` following by three dotted numbers will be available to all users.

**Comment by FichteFoll** [comment]
You rely on the `pyyaml` dependency but don't have that specified in a `dependencies.json` file.

**Comment by Thom1729** [comment]
I've fixed the dependencies.

**Pull request merged**
