### PR TITLE
update to v1.0.1

### PR DESCRIPTION
**Pull request by w3cmark**
Please provide the following information:

 - Link to your code repository: https://github.com/w3cmark/feg-sublime-snippets
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/w3cmark/feg-sublime-snippets/releases/tag/v1.0.1

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
You don't need to PR when you update your repo. Just push a new tag (as you just did), and it'll automatically get updated.

**Comment by w3cmark** [comment]
@math2001 get it! thankyou!

**Comment by math2001** [comment]
So, can you close this PR?

**Comment by Uduse** [comment]
@math2001 someone should mention this here:https://packagecontrol.io/docs/submitting_a_package 
I was confused how to update my package, so I came here to learn. Thank you very much!

**Comment by math2001** [comment]
Oh, okay. Happy I could help! I'll raise an issue on `packagecontrol.io` to let them know.

**Pull request closed without merging**
