### PR TITLE
Added HoverDocs

### PR DESCRIPTION
**Pull request by gladclef**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

My package is similar to ... However it should still be added because ...

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

Bonus points:
* Did a search for "documentation" on PackageControl.io and could not find a comparable package. The closest was OmniDocs.
* I can't put the commands from the .sublime-keybindings in the command pallette, due to the need to have all the information available in the EventListener.

### CODE REVIEW

**Comment by gladclef** [comment]
Repository link:
https://github.com/gladclef/HoverDocs

**Comment by gladclef** [comment]
My package is a way to view symbol definitions (eg function parameters) and docstrings inline.

There are no packages like it in Package Control.

**Comment by braver** [comment]
Don't we have LSP and such for that these days?

**Comment by gladclef** [comment]
I didn’t know about LSPs! Thank you so much for teaching me something new!

I would still argue that this is useful in cases where LSPs don’t work very well, such as on company controlled computers where you don’t have the ability to install nodejs or the environment setup is too complex for the LSP to understand. If you agree with this sentiment, I can add something to the readme about how this package duplicates some of the functionality of the lsp package, but is useful in certain use cases such as those listed above.

**Comment by braver** [comment]
I'm not against the idea, I certainly know of projects where LSP is overkill, unpractical, or simply doesn't work, where a "dumber" approach actually works better (for the that's a big part of what make Sublime Text awesome: it unlocks many of such features without the overhead of LSP, and you trade accuracy and richness of features). I don't think I've seen a recent attempt at something like this at least. If you look for "Doc" though we have lots of packages that do something with doc blocks. 

So, what kind of languages would your package support? Might be prudent to be up front about any limitations here.

**Comment by gladclef** [comment]
I agree that part of what I like about Sublime is that it can be “dumb” or “smart”, depending on what you need.

It should support any language that has “comment” or “parameters” in it’s syntax scope names, although it’s worth noting that I’ve only tried it with python so far.

**Comment by gladclef** [comment]
I like these suggestions. I’ll implement them and post a new message here once the updates are pushed.

**Comment by gladclef** [comment]
I implemented the following changes:
* remove comment markings for per-line markings (eg "#" for python or "//" for c)
* remove pydocs markings for python (""")
* added link to LSP in readme
* added license
* add limitation that this has only been tested with python in README
* other small fixes

**Comment by gladclef** [comment]
Ah, sorry! I didn’t update the tag! I’ll post an update with the tag tonight.

**Comment by gladclef** [comment]
Alrighty @braver! I think this is ready for re-evaluation, thanks!

**Comment by braver** [comment]
Cool, good job, let's ship it!

**Comment by gladclef** [comment]
I agree that part of what I like about Sublime is that it can be “dumb” or “smart”, depending on what you need.

It should support any language that has “comment” or “parameters” in it’s syntax scope names, although it’s worth noting that I’ve only tried it with python so far.

**Pull request merged**
