### PR TITLE
Pull request for Redlime plugin

### PR DESCRIPTION
**Pull request by tosher**
Redlime - Redmine manager plugin for Sublime Text 3

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true`.

Also, the package name is more to be though of as a unique identifier and not a description of what the package does, thus I suggest to name the package just "Redlime". Your package will still be searchable on https://packagecontrol.io/search/ via "redlime manager" since it's in your repo's description.

**Comment by tosher** [comment]
Without "redmine" in name, it will not be searchable in Sublime text via "Package control/Install package" by "redmine" substring :(
Redlime  - it's only funny name for Sublime/Redmine words, but it's [Redmine](http://redmine.org) manager :)

**Comment by FichteFoll** [comment]
I know that. It's unfortunate that SublimeText does not allow us to have the second line searchable in a quick panel (https://github.com/SublimeTextIssues/Core/issues/688), but we would rather encourage people to use [the website](https://packagecontrol.io/search/) for discovering packages instead of searching within SublimeText itself, since it has numerous advantages. You get a lot more information about a package there compared to within ST, for example the target ST versions, the latest version for each release and when it was released and the readme.

**Comment by tosher** [comment]
Ok, will waiting for quick panel upgrade :) Name was changed to "Redlime".

**Comment by FichteFoll** [comment]
Thanks.

**Comment by tosher** [comment]
Thanks!

**Pull request merged**
