### PR TITLE
Add Terrafmt

### PR DESCRIPTION
**Pull request by p3lim**

### CODE REVIEW

**Comment by Thom1729** [comment]
You should check the scope in the `on_pre_save` listener.

**Comment by p3lim** [comment]
@Thom1729 What?

**Comment by Thom1729** [comment]
In `TerrafmtListener`, in the `on_pre_save` method, before running the `terrafmt` command, you should check `view.score_selector(0, 'source.terraform') != 0`.

**Comment by p3lim** [comment]
What would be the benefit of doing that opposed to enabling the command only on the files?

**Comment by Thom1729** [comment]
I guess the `is_enabled` check will do the trick.

**Pull request merged**
