### PR TITLE
Add Fugly Syntax Highlight

### PR DESCRIPTION
**Pull request by diogomoretti**
Sublime Text (2 and 3) syntax highlight for [Fugly](https://github.com/pablo-cabrera/fugly-js).

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by diogomoretti** [comment]
Fixed branch. Waiting new review =]

**Comment by FichteFoll** [comment]
Okay, but you need to push tags to your repo.

@wbond, I think the docs need to be a bit more verbose in this regard, this has happened a lot in the past. Maybe just providing example git commands and an example tag name is sufficient.

**Comment by diogomoretti** [comment]
I added the labels ;) pls, check it.

**Comment by FichteFoll** [comment]
While this is also good, it's not what I meant either.

I meant you have to create a tag with `git tag v1.0.0` and then push it with `git push origin v1.0.0` (or alternatively `git push --tags`). It will then be listed here: https://github.com/diogomoretti/fugly.tmLanguage/tags

**Comment by diogomoretti** [comment]
Tag added! ;)

**Comment by diogomoretti** [comment]
thanks ;)

**Pull request merged**
