### PR TITLE
Add GitDiffView package

### PR DESCRIPTION
**Pull request by predragnikolic**
This package let you see all modified files and preview their changes. It is inspired by VS Code diff view.

Example
Get a quick overview of changes before commiting them.

### Features

-   Show all modified files
-   Show the diff view for a file
-   Stage/Unstage files (Staged files are marked with "✔")
-   Dismiss changes for a file
-   Go to a file

### CODE REVIEW

**Comment by predragnikolic** [comment]
I am pretty sure I change the keybinding to `alt+shift+g` for mac predragnikolic/sublime-git-diff-view@e2fe320.

**Comment by Thom1729** [comment]
You really should document the `a`/`d`/`g` keybinds, especially because they don't use modifier keys.

**Comment by predragnikolic** [comment]
Done predragnikolic/sublime-git-diff-view@fc89ebb8f.

**Comment by predragnikolic** [comment]
Thank you very much! :-)

**Pull request merged**
