### PR TITLE
Tensorflow autocompletion and shortcuts plugin.

### PR DESCRIPTION
**Pull request by baptisteArnaud**
- https://github.com/baptisteArnaud/Sublime-Tensorflow
 - https://github.com/baptisteArnaud/Sublime-Tensorflow/tags

### CODE REVIEW

**Comment by FichteFoll** [comment]
Our automated reviewer somehow chokes on this PR. Investigation pending.

In the mean time, please adjust the package name: https://packagecontrol.io/docs/submitting_a_package#Step_2

**Comment by FichteFoll** [comment]
You'll need to address both failing test runners (the key override and the package not being in the right JSON file after the rename).

**Comment by baptisteArnaud** [comment]
Can't I override a default binding ? I let the user the possibilty to change it in package settings.

**Comment by FichteFoll** [comment]
It appears your commit that changes the key bindings (https://github.com/baptisteArnaud/Sublime-Tensorflow/commit/981f68d5edddb028531247ef3c7e2b66788dfeb0) isn't included in a tag yet.

**Comment by baptisteArnaud** [comment]
All good now. Sorry for the mess! Anything else?

**Comment by baptisteArnaud** [comment]
When will the package be available?

**Comment by wbond** [comment]
Within an hour or so

**Comment by baptisteArnaud** [comment]
Thanks, whenever I push a new tag version, it will automatically update ?

**Comment by wbond** [comment]
Within about an hour, yes

**Pull request merged**
