### PR TITLE
Rename sublime-text-2-buildview to buildview, etc.

### PR DESCRIPTION
**Pull request by rctay**
As well as:

- Update git repo URL
- Use tags versioning instead of branch

### CODE REVIEW

**Comment by rctay** [comment]
Hey there, may I request that we pass on the changes requested by packagecontrol-bot, I have fixes to the messages.json file in the 'next' branch, I am holding those changes back from master in the plugin repo till this PR gets through to flip "branch" style to "tags" style versioning.

**Comment by braver** [comment]
Sure, I'll merge this right away.

**Comment by braver** [comment]
Oh, and please consider adding a LICENSE, it helps people contribute to your package.

**Comment by braver** [comment]
Wait, no, please replace both `sublime-text-2-buildview` and `sublime-text-buildview`, ie. put both names in previous_names.

**Comment by rctay** [comment]
> Wait, no, please replace both `sublime-text-2-buildview` and `sublime-text-buildview`, ie. put both names in previous_names.

Done!

**Pull request merged**
