### PR TITLE
Improving some details in my packages.

### PR DESCRIPTION
**Pull request by leoheck**

### CODE REVIEW

**Comment by leoheck** [comment]
Fixing some mistakes with syntax.

**Comment by FichteFoll** [comment]
When renaming, you need to add the previous name to a `previous_names` array in the package's metadata.

**Comment by leoheck** [comment]
@FichteFoll, do you have some instructions about how to do that? Which file should I change/create and where?

**Comment by leoheck** [comment]
Note to myself:

| Previous Name  | New Name |
| ------------- | ------------- |
| Cadence Skill  | SKILL from Cadence |
| 3D Tool Syntax Hilight | 3D Tool (Async Burst-Mode)  |
| Spice  | SPICE Simulator  |

**Comment by leoheck** [comment]
Done, @FichteFoll. The previous names arrays were added! There are other issues or we are ready to go?

**Pull request merged**
