### PR TITLE
Added MJML syntax

### PR DESCRIPTION
**Pull request by GuillaumeBadi**
Add the MJML syntax and snippets in Sublime Text for responsive Emails coding

### CODE REVIEW

**Comment by GuillaumeBadi** [comment]
Any news here @wbond ?

**Comment by arnaudbreton** [comment]
:+1: would love to see this merged officially!

**Comment by FichteFoll** [comment]
Sorry for the delay.

You don't have any tags pushed on the repo.

**Comment by GuillaumeBadi** [comment]
Hey @FichteFoll ,
You mean.. [this](https://github.com/wbond/package_control_channel/pull/5198/files#diff-a4bc313e2f8753f02db1486ed9843aceR1192) ?

**Comment by FichteFoll** [comment]
No, I mean [this](https://github.com/mjmlio/mjml-syntax/tags).

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by GuillaumeBadi** [comment]
Done :)

**Comment by FichteFoll** [comment]
I expect an upper-case `V` not to work. Please user a lower-case `v` or no prefix.

**Comment by GuillaumeBadi** [comment]
corrected! :+1:

**Pull request merged**
