### PR TITLE
add NotePad

### PR DESCRIPTION
**Pull request by va9iff**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
How does this compare to the built-in "distraction free mode", or these options?
https://packagecontrol.io/packages/DistractionFreeWindow
https://packagecontrol.io/packages/distractionless

**Comment by va9iff** [comment]
You can open a new NotePad view with 1 command and start writing here. It is window specific, so you can have separate post-it and work however you want in your current workspace.

But the biggest pro of NotePad over distractionless is that it doesn't have any listeners. I believe the packages should have as less listeners and background jobs as possible in sublime text. Cuz the speed and ligthweightness is the advantage of st for me.
I even have "copied" some packages to work by only calling 3rd party tools cuz dedicated packages were a bit bloated.

So, that's the biggest hit of NotePad to distractionless. But distraction Free Window looks very similar :) 
But in the gif It didn't toggle the gutter. But NotePad does.
Anyways, I love Sublime Text. Here's my contribution. If isn't useful, no problem :')

But NotePad is logically convenient like post-it of notepad++
I couldn't find a package to turn st to notepad. Probably someone else will too

**Comment by braver** [comment]
Alright, thanks. You skipped some stuff in the checklist like tagging a release. Please double check the requirements for submitting a package.

**Comment by va9iff** [comment]
I've done the tagging a release. If there is something else I'm missing, please let me know.

**Pull request merged**
