### PR TITLE
Add sublime devdocs packages

### PR DESCRIPTION
**Pull request by hectorqin**

### CODE REVIEW

**Comment by hectorqin** [comment]
Sublime quick search symbol in devdocs, it's a preview version, PR are welcome :)

**Comment by FichteFoll** [comment]
How is this different from https://packagecontrol.io/packages/DevDocs?

**Comment by hectorqin** [comment]
The package of devdocs is just open the browser and search the symbol, which's inconvenient, while my plugin will show the definition of symbol in popup,  that will let you focus on coding

**Comment by hectorqin** [comment]
My plugin will download the zip file from devdocs.io and provide offline search functionality

**Comment by FichteFoll** [comment]
Okay, that's fine.

However, your package name is not acceptable because it contains "Sublime". Please remove that. To separate your package from the existing one, you might want to consider "Offline DevDocs" or "DevDocs Offline".

You'll also have to push a proper semantic version tag, which consists of exactly three numeric parts.

**Comment by hectorqin** [comment]
I pulled an another request, please pass it

**Comment by hectorqin** [comment]
#6678   I pulled an another request, please review it. thinks !

**Comment by hectorqin** [comment]
@FichteFoll   I pulled an another request, please review it. thinks !  #6678

**Pull request closed without merging**
