### PR TITLE
Changes in package

### PR DESCRIPTION
**Pull request by akalongman**

### CODE REVIEW

**Comment by FichteFoll** [comment]
While I am reviewing this, please remove your `.no-sublime-package` file from the repo. It is not necessary and instead complicates things for users.

**Comment by akalongman** [comment]
```.no-sublime-package``` not supported anymore?

**Comment by FichteFoll** [comment]
It is supported, but it is not necessary in your package.

**Comment by akalongman** [comment]
Ok. I will test and after remove that file. Thank you

**Pull request merged**
