### PR TITLE
Change ScrollOffset and MouseEventListener to let them be installed on ST3

### PR DESCRIPTION
**Pull request by vihangm**
Plugin to provide vim style scroll off behavior.

### CODE REVIEW

**Comment by FichteFoll** [comment]
There is already a very similar package like this: https://github.com/SublimeText/ScrollOffset
It's currently marked as ST2-only but I didn't find anything in the source that would prevent it from working on ST3 so it could just be updated.

Would it be possible to add possibly missing functionality to that package?

cc @adzenith

**Comment by vihangm** [comment]
Yeah, I'll test it out and see if there are any egregious issues with ST3. I noticed it while sending out this PR, but didn't have the time to test it.

**Comment by adzenith** [comment]
I'm pretty certain I was using it for a long time on ST3. Not sure why it's marked ST2--I probably just forgot to update it when ST3 came out :P

**Comment by vihangm** [comment]
Depends on https://github.com/SublimeText/ScrollOffset/pull/11 and https://github.com/SublimeText/MouseEventListener/pull/1 being merged.

**Comment by vihangm** [comment]
The PRs are merged. This should be good to go now.

**Comment by FichteFoll** [comment]
Great!

**Pull request merged**
