### PR TITLE
Added urtext

### PR DESCRIPTION
**Pull request by nbeversl**

### CODE REVIEW

**Comment by nbeversl** [comment]
v0.1.0-alpha tag has been added.

**Comment by Thom1729** [comment]
Modifying `sys.path` is dangerous, and it shouldn't be necessary here. Would relative imports suffice?

**Comment by nbeversl** [comment]
By the way, I renamed the Github repo to urtext_sublime to make it a valid name for relative import paths. Will you be able to change that, or do you want me to re-pull the package control channel and resubmit?

**Comment by Thom1729** [comment]
You can just add a new commit to this PR.

**Comment by nbeversl** [comment]
Thanks. Can you clarify (was not able to get myself clear on this from the docs), does each new tag require its own PR? Or once the package is accepted, do users have access to all tags?

**Comment by Thom1729** [comment]
Only one PR is necessary for the package. Package Control will automatically notice new tags and make them available to users.

**Comment by nbeversl** [comment]
I’m not aware of the overridden default key bindings referenced here. I’m looking at  http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_win.html and http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_osx.html, am I missing anything?

**Comment by nbeversl** [comment]
Are any further modifications or actions needed from me on this?

**Comment by nbeversl** [comment]
Is this still being reviewed?

**Comment by nbeversl** [comment]
Closing due to no reply and no documentation on how to re-run the package control bot.

**Comment by FichteFoll** [comment]
Instructions on how to rerun the bot should have been available in the PR template when you created this PR. In short, you close and reopen the PR.

**Pull request closed without merging**
