### PR TITLE
Theme and color scheme inspired by autumn colors

### PR DESCRIPTION
**Pull request by DiegoAz**

### CODE REVIEW

**Comment by wbond** [comment]
You'll need to create a semantic version tag (e.g. 1.0.0) and push it to GitHub in order for users to be able to install the package.

**Comment by DiegoAz** [comment]
Hi. I've never done that. I read this, http://semver.org/ but I don´t understand. Need I to create a file with a description of the version?. It is the 1.0.0. Can you explain me? please. Thanks.

**Comment by FichteFoll** [comment]
Check out https://github.com/DiegoAz/Theme-Autumn/tags (and the referenced help page).

**Comment by DiegoAz** [comment]
Hi @FichteFoll thanks for help me. I hope I have done well.

**Pull request merged**
