### PR TITLE
add fsharp package

### PR DESCRIPTION
**Pull request by guillermooo**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The release repo doesn't contain a readme. You can either copy this from the development repo, make a custom one or just point PC to the raw readme file of the dev repo.

**Comment by guillermooo** [comment]
@FichteFoll Revised!

**Comment by rojepp** [comment]
@guillermooo The readme points to dev repo, not published repo. This means a readme for yet unreleased code could be fetched. The readme should be published in the same way as the code, and the readme link here should point to the release repos version.

**Comment by guillermooo** [comment]
@rojepp That's true. I'll change the link.

**Comment by guillermooo** [comment]
@FichteFoll we now have a readme in the repo. PTAL.

**Pull request merged**
