### PR TITLE
Add Pieces Package for Package Control

### PR DESCRIPTION
**Pull request by crispieces**
Pieces - Save code, links, text, images and more with a simple copy & paste.

Pieces - Save code, links, text, images and more with a simple copy & paste.

### CODE REVIEW

**Comment by braver** [comment]
I can't reach your bitbucket repo via that link. You can search this repo for some examples of repos hosted with bitbucket.
Your JSON uses smart quotes, which is not valid. Please use simple straight quotes and have another close look at your labels.

**Comment by crispieces** [comment]
> I can't reach your bitbucket repo via that link. You can search this repo for some examples of repos hosted with bitbucket.
> Your JSON uses smart quotes, which is not valid. Please use simple straight quotes and have another close look at your labels.

Thank you, it should be taken care of now.

**Comment by braver** [comment]
Can you maybe tell us a bit more about Pieces and how your package interacts with it?

**Comment by crispieces** [comment]
Yes,

My package was designed to be a plugin for Sublime Text Editor named
"Pieces". Pieces is supposed to highlight text in a file and send it to the
primary desktop application. Please let me know if this helps?

**Comment by crispieces** [comment]
> Can you maybe tell us a bit more about Pieces and how your package interacts with it?

Yes,

My package was designed to be a plugin for Sublime Text Editor named
"Pieces". Pieces is supposed to highlight text in a file and send it to the
primary desktop application. Please let me know if this helps?

**Comment by crispieces** [comment]
Fixed the URL issue, sorry about that.

**Comment by braver** [comment]
I guess my main problem comes from having no clue what "Pieces OS" is (and Googling doesn't really help... "pieces" isn't a great name for SEO) :) I probably also won't be able to test this package I guess?

You have some files in there that don't seem like they belong, like `Package Control.sublime-settings`, `Package Control.user-ca-bundle` and `plugin_sublime.iml`. 

It looks like you only support MacOS, so better to specify that in your package control entry.

I'll give you the standard rant with respects to key bindings: We recommend against keybindings. They tend to conflict with other packages, and for things you don't use every day they're usually impossible to remember. Instead, make sure your command is accessible via the command palette, and maybe also via the main menu. In your README you might the explain how users can set up a keybinding if they want to.

Similarly, you have an unconditional context menu entry. That takes up space in a menu that gets crowded very quickly. If it makes sense to have the command there, please consider implementing `is_visible` so that it doesn't take up space in contexts where the command won't work.

You entry here mentions features like "save snippets" but your README only mentions "Send to Pieces" which sounds like something else?

You mention "License - Mesh Intelligent Technologies, Inc.", but that isn't a license. If this is open source, please add a license file to the repo explaining the situation.

We require tags (your entry here says so too), but I don't see any tags in your repo?

**Comment by crispieces** [comment]
> I guess my main problem comes from having no clue what "Pieces OS" is (and Googling doesn't really help... "pieces" isn't a great name for SEO) :) I probably also won't be able to test this package I guess?
> 
> You have some files in there that don't seem like they belong, like `Package Control.sublime-settings`, `Package Control.user-ca-bundle` and `plugin_sublime.iml`.
> 
> It looks like you only support MacOS, so better to specify that in your package control entry.
> 
> I'll give you the standard rant with respects to key bindings: We recommend against keybindings. They tend to conflict with other packages, and for things you don't use every day they're usually impossible to remember. Instead, make sure your command is accessible via the command palette, and maybe also via the main menu. In your README you might the explain how users can set up a keybinding if they want to.
> 
> Similarly, you have an unconditional context menu entry. That takes up space in a menu that gets crowded very quickly. If it makes sense to have the command there, please consider implementing `is_visible` so that it doesn't take up space in contexts where the command won't work.
> 
> You entry here mentions features like "save snippets" but your README only mentions "Send to Pieces" which sounds like something else?
> 
> You mention "License - Mesh Intelligent Technologies, Inc.", but that isn't a license. If this is open source, please add a license file to the repo explaining the situation.
> 
> We require tags (your entry here says so too), but I don't see any tags in your repo?

Hi Braver, Pieces OS is a local helper for Pieces app. Feel free to check us out at pieces.app. The readme has been updated to reflect this information.
Some of the unnecessary files you mentioned were autogenerated from Sublime Text Editor, so I figured it was better to be safe and include them. Lastly, I added a copyright clause but will be refining licensing shortly. I hope this helps. I look forward to hearing from you.

**Comment by braver** [comment]
>  so I figured it was better to be safe and include them

Alright. I don't know how they were generated, but they definitely don't belong inside a package.

**Comment by crispieces** [comment]
> > so I figured it was better to be safe and include them
> 
> Alright. I don't know how they were generated, but they definitely don't belong inside a package.
> 
> (Please let me know when you've addressed the rest of the feedback as well)

Okay, the tag has been created for the repo. Hopefully, I've addressed your feedback. Please let me know if there is more uncertainty.

**Comment by braver** [comment]
The `Preferences.sublime-settings` seem like your own personal settings, they don't apply to this package. 

Would it be possible to implement `is_visible` for the context menu entry?

Is this the app you mean? https://apps.apple.com/nl/app/pieces/id430923245?l=en&mt=12 If you do only support MacOS, please add a `platforms` key in `releases` that specifies so.

**Comment by crispieces** [comment]
> The `Preferences.sublime-settings` seem like your own personal settings, they don't apply to this package.
> 
> Would it be possible to implement `is_visible` for the context menu entry?
> 
> Is this the app you mean? https://apps.apple.com/nl/app/pieces/id430923245?l=en&mt=12 If you do only support MacOS, please add a `platforms` key in `releases` that specifies so.

Thank you for catching the Preferences.sublime-settings, this file is deleted as it is not a part of the package. 
No, more information can be found by visiting https://pieces.app (website).
We plan to implement is_visible in version 2.

**Comment by crispieces** [comment]
@braver Commenting here to confirm my availability for any issues.

**Comment by braver** [comment]
Alright, thanks for clearing that up. Final note before we merge about your labels here. The should be thought of as tags, to allow users to find similar packages. They're not keywords or a tagline. And usually they should be lower case. In your case I would suggest:
```
['pieces', 'snippets']
```

**Comment by crispieces** [comment]
> Alright, thanks for clearing that up. Final note before we merge about your labels here. The should be thought of as tags, to allow users to find similar packages. They're not keywords or a tagline. And usually they should be lower case. In your case I would suggest:
> 
> ```
> ['pieces', 'snippets']
> ```

@braver Thank you, that should be fixed with the latest commit to my forked repo.

**Comment by crispieces** [comment]
@braver I'm a little unsure why this check failed.

**Comment by braver** [comment]
Either something over at GitHub, or something in our CI setup (maybe to do with bitbucket). I’ll have to look into it.

**Comment by tsavo-vdb-knott** [comment]
Hello all! Tsavo here from Pieces, @braver just wanted to take a minute and say THANK you for helping Cristion out with all of this. 

We are super excited to support the Sublime Text Marketplace and also would be happy to send you the download links (which will be public soon but currently are invite only) [code.pieces.app](code.pieces.app) is our site and if you want to request access I'll shoot over a download link ASAP - also you could ping us a direct request over email at [hello@pieces.app](hello@pieces.app) and just specify what OS (windows/mac) you're using and we can send you over the app - Would love feedback!

Thank you for being patient and understanding that we are early and want Sublime to be a well supported IDE. We are here to be an ecosystem player and we want our users to be able to use the tools they love! 

Cheers, 
-Tsavo

**Comment by wbond** [comment]
I've fixed the review issue - thanks for your patience.

**Comment by crispieces** [comment]
> I've fixed the review issue - thanks for your patience.

@wbond @braver Thank you for your cooperation. Please let me know if there is anything I can fix to successfully add our package to Package Control :)

**Comment by rwols** [comment]
You seem to have a command in Main.sublime-menu to a command that doesn’t exist.

**Comment by crispieces** [comment]
> You seem to have a command in Main.sublime-menu to a command that doesn’t exist.

@rwols Thank you for catching that error. We realized this yesterday and this was supposed to be a major bug fix for version 2. However, for your convenience, I have updated the Main.sublime-menu with the proper command (create_asset).

**Comment by braver** [comment]
Okidoki. I got nothing anymore, let's 🚀 😄

**Pull request merged**
