### PR TITLE
Sublpress rebirth.

### PR DESCRIPTION
**Pull request by helmutgranda**
After doing some digital forensics I was able to revive a project that has been left unattended for a little more than a year:

https://github.com/brzrkr/Sublpress/

The creation of this repo is to provide the feature to users to be able to publish/edit content to their Wordpress blog.

### CODE REVIEW

**Comment by helmutgranda** [comment]
I just noticed the thread below:

https://github.com/wbond/package_control_channel/pull/3954

Let me know if we should follow a similar route instead of using Sublpress2

**Comment by FichteFoll** [comment]
Yes, the same procedure would be preferred for sublpress as well.

Since the original package is in an awful state as well (last commit deleted many files, `.pyc` all over the place), hasn't been fixed in more than a year and is currently not even installable on package control for some reason (probably casing of the url), I won't even wait for a response here. But for fairness's sake I will mention the original author so he at least *can* see what is being done here.

cc @brzrkr

**Comment by helmutgranda** [comment]
Changes done.

**Comment by FichteFoll** [comment]
Tags must be valid semantic versions (so `0.1.0` or `v.0.1.0`).

**Comment by helmutgranda** [comment]
Tag release version updated to 0.1.0.

**Pull request merged**
