### PR TITLE
Add SublimeLinter-Dashboard package

### PR DESCRIPTION
**Pull request by philippotto**
Adds the [SublimeLinter-Dashboard](https://github.com/philippotto/SublimeLinter-Dashboard) package which provides a dashboard like UI on top of SublimeLinter.

### CODE REVIEW

**Comment by philippotto** [comment]
@FichteFoll Do you know why the @packagecontrol-bot didn't kick in? All the other PRs seem to have gotten an automatic "accept" or "request changes" by the bot.

**Comment by FichteFoll** [comment]
No idea. All I can say is that the HTTP endpoint returns a 500 error code. I ran the checks locally, however, and here are the results:


## Report for SublimeLinter-Dashboard #################

### Repository checks ###

No failures

No warnings


### Package checks ###

No failures

Reporting 6 warnings:
- The binding ['enter'] is also defined in default bindings but is masked with a 'context'
    File: Default.sublime-keymap
- The binding ['escape'] is also defined in default bindings but is masked with a 'context'
    File: Default.sublime-keymap
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default.sublime-mousemap
- Command class 'SublimeLinterDashboardWrite' does not end with 'Command'
    File: SublimeLinter-Dashboard.py
    Line: 170, Column: 1
- Command class 'SublimeLinterDashboardOpen' does not end with 'Command'
    File: SublimeLinter-Dashboard.py
    Line: 237, Column: 1
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: dashboard.sublime-syntax


For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/py_package_reviewer/wiki

**Comment by FichteFoll** [comment]
@philippotto please address (or comment) the warnings about the mousemap file and the build requirement for installation.

**Comment by philippotto** [comment]
Sorry, I'll close this PR, because I don't need the package anymore as I found the LSP plugin to be a better fit for my needs.

**Pull request closed without merging**
