### PR TITLE
master: Added NetSuite SDF package to repo

### PR DESCRIPTION
**Pull request by tjtyrrell**
Hello, this package is for the NetSuite SDF CLI tool which requires a NetSuite account (you can see the Chocolatey package here: https://chocolatey.org/packages/sdfcli, I am presently working on a Brew as well). This is a pre-release but I wanted to make it available for people to start playing with. It is limited to people who use NetSuite, so the documentation I can give you is locked behind an account.

This is needed because the only software that has a NetSuite plugin is Eclipse, and that's nasty. This provides all of the same functionality as the Eclipse plugin while resting inside the beauty and simplicity of Sublime. This is my first Sublime plugin and even my first entry into Python, so please forgive the code.

In order to use this software, you need to have the NetSuite SDF CLI tool installed. This is done either manually or using Chocolatey on Windows and soon Brew on a Mac. For a video representation of this Plugin, please see this video:
https://www.dropbox.com/s/3tkudqdnctt2s1v/Sublime%20Text%203%20Plugin.mp4?dl=0

Let me know if there is anything else I need to do.

Thank you,

TJ

### CODE REVIEW

**Comment by tjtyrrell** [comment]
Ok, let me fix this.

**Comment by tjtyrrell** [comment]
I have updated the keymap file.

**Comment by tjtyrrell** [comment]
Just checking in on this to see if there is anything I need to do.

Thank you.

TJ

**Comment by FichteFoll** [comment]
Don't worry, you'll here from me (or someone else) when there it something about your package or PR that needs fixing.

**Pull request merged**
