### PR TITLE
Add Sublime-wxapp package

### PR DESCRIPTION
**Pull request by springlong**
a plugin for mini program in wechat

### CODE REVIEW

**Comment by Thom1729** [comment]
What is this package for? I'm afraid I can't read the readme.

**Comment by Thom1729** [comment]
@springlong ping

**Comment by springlong** [comment]
I'm sorry, I'll rewrite the readme by English.

**Comment by springlong** [comment]
Hi, this plugin already edit README.md in English now!
Please check again!
Thanks!

**Pull request merged**
