### PR TITLE
Add `GreekLetters` packages

### PR DESCRIPTION
**Pull request by a-ludi**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@a-ludi ping

**Comment by a-ludi** [comment]
Sorry, I had other things to do. I will add the missing version label in the next days. Thanks for informing me! 

Am 23. März 2015 21:29:10 MEZ, schrieb FichteFoll <notifications@github.com>:

**Comment by a-ludi** [comment]
I pushed the v1.0.0 tag to my repo.

Cheers!

Am 13.03.2015 18:34 schrieb FichteFoll: 

> You have to push valid semantic version [1] tags (with optional leading v) to your repo. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] http://semver.org
[2]
https://github.com/wbond/package_control_channel/pull/4203#issuecomment-79167375

**Pull request merged**
