### PR TITLE
Add Libsass Build and Sassc dependency

### PR DESCRIPTION
**Pull request by blitzrk**

### CODE REVIEW

**Comment by blitzrk** [comment]
Just fixed some problems and squashed the intermediate commits. Now all tests are passing.

**Comment by FichteFoll** [comment]
You don't seem to have a particular need for `.no-sublime-package`, please remove it.

Also please use relative imports for ST3 and absolute imports for root-level modules for ST2 instead of modifying `sys.path`.

**Comment by blitzrk** [comment]
Removed `.no-sublime-package`.

Removed dependency from `l.json` so it is now only in `dependencies.json` in my plugin's repo.

I think I fixed the relative imports for both ST2 and 3, but I can't test it right now, because I hit Github's API's rate limit. Will test ASAP.

Good enough to merge?

**Comment by FichteFoll** [comment]
Python files in the root folder look good, but you have to use relative imports in your `libsass` package as well in order to have it work on ST3. Since this is a sub-package, relative imports will work on ST2 too.

**Comment by blitzrk** [comment]
Fixed and tested on 2221 and 3103. Thank you for your help.

I'm going to start drafting a Python 2/3 compatibility guide for packagecontrol.io's developer documentation. I'll mention what I've learned here and some other compatibility tidbits like the fact that the print function is automatically imported from __future__.

**Comment by FichteFoll** [comment]
We also have that planned for the unofficial documentation, but there just is not enough time for us.

**Pull request merged**
