### PR TITLE
Add TerminalView package

### PR DESCRIPTION
**Pull request by Wramberg**
Please provide the following information:

 - Link to your code repository:
https://github.com/Wramberg/TerminalView

 - Link to the tags page with at least one [semver](http://semver.org) tag: 
https://github.com/Wramberg/TerminalView/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
Check!
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))
Check

### CODE REVIEW

**Comment by Wramberg** [comment]
Note that it shadows a lot of ST3 keybindings on purpose (only when in the TerminalView of course).

There are a few plugins that look similar to this one but none of them uses a pseudo-terminal (that I know of) so this plugin offers a different approach that provide additional features,

**Comment by FichteFoll** [comment]
The [Term](https://github.com/percevalw/SublimeTerm) package (PR pending https://github.com/wbond/package_control_channel/pull/6293) also emulates a terminal. Yours already seems to have color support (and I generally think the keybinding overrides are a good idea).

This is kind of an odd situation because we usually try to keep packages doing the same thing at a minimum, but you were both working on your packages at the same time and both of them are also in the queue right now. Ideally we'd only have one packages, but I can see that you both put a lot of effort into it. Do you have any suggestions about this?

Also pinging @percecalw.

**Comment by FichteFoll** [comment]
(pinging @percevalw again because I made a typo earlier and had to edit it)

**Comment by percevalw** [comment]
Indeed, you did a pretty good job with this package. It looks more reactive and uses pyte to communicate with the shell, which is a good idea I think. Moreover, I won't have time to take care of mine in the near future, so go ahead !

**Comment by FichteFoll** [comment]
Thanks for understading and taking a look, @percevalw. I'll close your PR then. You'll probably want to enhance @Wramberg's package in the future, in case you find a mising feature 😉

**Comment by rwols** [comment]
@percevalw I think your runloop implementation is better than TerminalView's, so consider turning that idea into a pull request for TerminalView.

**Comment by Wramberg** [comment]
Hi gents,

After looking into the term package I see that they are indeed quite similar. I second @rwols observation that SublimeTerm probably has a better approach in terms of the run loop since it blocks while waiting for input thus using less CPU.

Moreover it seems that more research has gone into the terminfo definitions etc. in the SublimeTerm package so thats probably something I would like to look into to improve TerminalView compatibility with other shells (than bash).

I appreciate your decision to step down @percevalw - feel free to test out the TerminalView plugin and start some discussions in the gitrepo if you have any ideas. PRs are welcome too of course but some times they conflict with some of my development ideas so it's probably best to discuss first.

**Pull request merged**
