### PR TITLE
Blazing-fast out of the box search for ST3 projects of any size.

### PR DESCRIPTION
**Pull request by rokartnaz**
Please provide the following information:

 - Link to your code repository: https://github.com/rokartnaz/WhooshSearch
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/rokartnaz/WhooshSearch/tags

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for WhooshSearch ############################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 6 failures:
- The binding ['ctrl+shift+i'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap
- The binding ['ctrl+shift+w'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap
- The binding ['ctrl+shift+i'] unconditionally overrides a default binding
    File: Default (Linux).sublime-keymap
- The binding ['ctrl+shift+w'] unconditionally overrides a default binding
    File: Default (Linux).sublime-keymap
- The binding ['super+shift+i'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap
- The binding ['super+shift+w'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap

Reporting 7 warnings:
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default (Linux).sublime-mousemap
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default (Windows).sublime-mousemap
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default (OSX).sublime-mousemap
- The binding ['up'] is also defined in default bindings but is masked with a 'context'
    File: Default (Windows).sublime-keymap
- The binding ['down'] is also defined in default bindings but is masked with a 'context'
    File: Default (Windows).sublime-keymap
- The binding ['up'] is also defined in default bindings but is masked with a 'context'
    File: Default (Linux).sublime-keymap
- The binding ['down'] is also defined in default bindings but is masked with a 'context'
    File: Default (Linux).sublime-keymap

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by FichteFoll** [comment]
You should be able to make use of [these view settings](http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html#capturing-build-system-results) instead of listening to double click vents. This is also what the Find Results panel does.

**Comment by rokartnaz** [comment]
Thank you for pointing out these view settings which helped me to rid of mousemaps. Also I changed keymaps to not override default sublime functionality. The repository is ready for the review:

 - Link to code repository: https://github.com/rokartnaz/WhooshSearch
 - Link to the tags page: https://github.com/rokartnaz/WhooshSearch/tags

**Comment by FichteFoll** [comment]
Unfortunately, the 'super+alt+f' binding still overrides a default on OSX.

**Comment by rokartnaz** [comment]
Thanks @FichteFoll . I've changed key bindings and it should be alright now.

- Link to code repository: https://github.com/rokartnaz/WhooshSearch
- Link to the tags page: https://github.com/rokartnaz/WhooshSearch/tags

**Comment by rokartnaz** [comment]
Hi @FichteFoll,

Thank you for merging my plugin. I am testing now the installation process on Win7 (Package Control: Install Package) and Package Control shows that "No description provided". How can I provide a proper description for my plugin to display it instead? Actually I thought that the title of this pull request should go somehow as plugin description: "Blazing fast out of the box search for ST3 projects of any size." 

Best Regards,

**Comment by rokartnaz** [comment]
Excuse me for disturbing @FichteFoll . I found how to achieve it.

**Pull request merged**
