### PR TITLE
Added CodeDrafts Plugin

### PR DESCRIPTION
**Pull request by subeeshb**
Please provide the following information:

 - Link to your code repository: https://github.com/subeeshb/codedrafts_sublime_plugin
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/subeeshb/codedrafts_sublime_plugin/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
- could you add a description to your repo (under the title) on github, it's going to be use in Package Control's website.
- the Python's convention is to indent your code with *4* spaces. It's not a big deal, but if you could change it, it'd be great.

```python
extension == '.css' or extension == '.scss' or extension == '.less'
# is the same as
extension in ('.css', '.scss', '.less')
```

Didn't find anything else to correct

**Comment by subeeshb** [comment]
Thanks! I've updated my repo with a description, modified the if statement, and changed the indentation to 4 spaces.

**Comment by math2001** [comment]
Here's other things you could do:

- add labels to your package (in the `c.json`). Here's the [list](https://packagecontrol.io/browse/labels)
- add some messages: [Messaging](https://packagecontrol.io/docs/messaging)

**Comment by subeeshb** [comment]
Added messaging and labels.

**Comment by math2001** [comment]
Hum, the `id` keys in the `.sublime-commands` isn't needed. (sorry for not seing this earlier)

**Comment by subeeshb** [comment]
Done - removed the `id` field from `Default.sublime-commands`

**Comment by FichteFoll** [comment]
Your `Accept` HTTP headers are a lie. You actually only accept `application/json`. 😜

**Pull request merged**
