### PR TITLE
Added JSML Formatter package

### PR DESCRIPTION
**Pull request by mjkaufer**
Added a package which lets users format JSML.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by mjkaufer** [comment]
@FichteFoll I just added a release to my repo. I've never done this before, so I might've messed up. Is everything good now?

Thanks!

**Comment by FichteFoll** [comment]
Almost. Semantic versions have three numeric parts.

**Comment by mjkaufer** [comment]
@FichteFoll Sorry about that! I just fixed it. Thanks for your help!

**Comment by mjkaufer** [comment]
@FichteFoll If I've just updated my package in my package's GitHub repo (along with its latest release version), how long should it take to reflect in package control?

Thanks!

**Comment by FichteFoll** [comment]
It can take up to an hour.

**Comment by mjkaufer** [comment]
Alright. Thanks!

**Pull request merged**
