### PR TITLE
Add LazyTimeTracker

### PR DESCRIPTION
**Pull request by Bwata**
Would like to add my sublime package to Package Control. If there are any issues please let me know, this is my first publish package.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by Bwata** [comment]
FichteFoll I added the tag. Is that all I needed to do?

**Comment by FichteFoll** [comment]
You still need to do the first part.

**Comment by Bwata** [comment]
Ok, Sorry I missed that.

**Pull request merged**
