### PR TITLE
add new plugin GoDebug

### PR DESCRIPTION
**Pull request by dishmaev**

### CODE REVIEW

**Comment by dishmaev** [comment]
i want to change my setting:
current
"sublime_text": "*",
new
"sublime_text": ">=3000",

do I need to create a new pull request?

**Comment by evandrocoan** [comment]
> do I need to create a new pull request?

No, you just need to push a new commit to your `master` branch. 

You can do this by the `git` command line, by a `git` graphical client or by the GitHub website interface:

image

**Comment by dishmaev** [comment]
Thanks for the explanation, ready

**Comment by evandrocoan** [comment]
@dishmaev, can you remove `Sublime` from the package name?

It is quite annoying having packages installed on Sublime Text, which have `Sublime` on their names. For example, when I am searching for a package, I can just look for `Delve` on around the packages with name staring with `D` instead of looking there first and later on `S`.

**Comment by evandrocoan** [comment]
@dishmaev, To override the default keybings you need to:

1. State on the `README.md` which one are the default Sublime Text keys you are overriding.
1. Do it only when the user is eding `Go` files. This way he can still have the keybinds working when he is using other languages. To do this, you just need to set a context, for example:
    ```json
        {
            "command": "dlv_toggle_breakpoint",
            "keys": ["f9"]
        },
    ```
    -->
    ```json
        {
            "command": "dlv_toggle_breakpoint",
            "keys": ["f9"], 
            "context": [
                {"key": "setting.delve_enable", "operand": true},
                { "key": "selector", "operator": "equal", "operand": "source.go" },
            ]
        },
    ```

**Comment by dishmaev** [comment]
i change my Default.sublime-keymap, now only warnings when processing package "GoDebug"

**Comment by dishmaev** [comment]
?

**Pull request closed without merging**
