### PR TITLE
Add TimeNotify

### PR DESCRIPTION
**Pull request by halfmoonvic**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is view and remind time

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Your readme doesn't clearly explain how to use your package, and what that would result in. In other words, why would someone use it? What does it do?

Please use `edit_settings` also in the main menu entry, so that the settings files open in split view.

**Comment by halfmoonvic** [comment]
I have updated my readme, please check

**Comment by braver** [comment]
Thanks for the update. Please address my feedback regarding how settings are opened.

**Comment by halfmoonvic** [comment]
> Thanks for the update. Please address my earlier feedback regarding how settings are opened.

I don't understand. Are you saying to provide a screenshot of the settings file? In that case, I have updated my readme document and listed a set of settings. Is that okay?

**Comment by braver** [comment]
No, you're using open_file to open the default settings via one menu entry, and a second one for the user settings. That's the ST2 way of doing it from more than 8 years ago. You should use the edit_settings command instead, which allows you to open settings in 2 panes. There are various packages out there that you can use as [an example](https://github.com/braver/SideBarTools/blob/master/Main.sublime-menu#L17).

**Comment by halfmoonvic** [comment]
> No, you're using open_file to open the default settings via one menu entry, and a second one for the user settings. That's the ST2 way of doing it from more than 8 years ago. You should use the edit_settings command instead, which allows you to open settings in 2 panes. There are various packages out there that you can use as [an example](https://github.com/braver/SideBarTools/blob/master/Main.sublime-menu#L17).

ok, I have changed

**Pull request merged**
