### PR TITLE
Update t.json, Terminal-command

### PR DESCRIPTION
**Pull request by looking-for-a-job**

### CODE REVIEW

**Comment by Thom1729** [comment]
@looking-for-a-job 	Please address the above error. Once you've added a valid semver tag (I don't think 0.0.0 will work), close and reopen this issue and the bot will recheck it.

**Comment by Thom1729** [comment]
You should add a license.

You should probably also expand the readme at least a bit. It looks like the build system will open Terminal, open a new window, and run the command in that window. A little more explanation would go a long way.

In the Python script:

- Instead of checking `"darwin" in sys.platform.lower()`, you can check `sublime.platform() == 'osx`. Since the package is declared only for the Mac OS, the check probably isn't necessary. If you do keep the check, then when it fails you should display an error instead of silently doing nothing.
- It's not obvious from the readme that the plugin will silently change file permissions. This needs to be documented. Ideally, the user might turn this on and off with a setting.

**Comment by Thom1729** [comment]
@looking-for-a-job 	ping

**Comment by looking-for-a-job** [comment]
Thom1729, done

**Pull request merged**
