### PR TITLE
create JSON Faster Plugin

### PR DESCRIPTION
**Pull request by CourageSuo**
Please provide the following information:

 - Link to your code repository: https://github.com/CourageSuo/INTASublime.git
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
You need to type your readme in english.

Also, your command need to be more "specific". The convention is to have this kind of name `MyCommandNameCommand` (PascalCase)

**Comment by CourageSuo** [comment]
change the readme in English and Specify the command

**Comment by math2001** [comment]
I'm probably not a reference at English, but we say `faster` and not `more faster`

### Command Names

Again, you need to change your commands name: `ExampleCommand` doesn't make any sense, `tabCommand` could be used by another plugin (so, you could get overridden, or override an other's plugin's command),

What you can do is prefix your command with `JSONFaster`, or do an internal system of command: you create only one command which takes an argument `action` for example, and this command runs the appropriate function.

### Repo Name

Why isn't your repo's name `JSONFaster`?

### `Default.sublime-keymap`

If all your platform specific `.sublime-keymap` are the same, you can just create a file called `Default.sublime-keymap` and will work on every platform.

**Comment by CourageSuo** [comment]
Thanks your patient and detailed explanation and so shamed about my poor English😁😁😁
Now I rename my command name, as you suggest I add prefix ahead of my command.  of course I combined three .sublime-keymap to one Default.sublime-keymap.
The Repo name INTASbulime which is my website www.intalesson.com theme. Is that affect the pull request?
thanks

**Comment by math2001** [comment]
> The Repo name INTASbulime which is my website www.intalesson.com theme. Is that affect the pull request?

No, it doesn't. But it'll be hard(er) to find your package's repo (and there is no reason to put your websites *in* the repo's name. You can mention it in your repo description, if you want to). I don't recommend it though.

**Comment by CourageSuo** [comment]
so I change the repo name, but it still one failing check?

**Comment by math2001** [comment]
First, you don't need the `.git` at the end: `https://github.com/CourageSuo/JSONFaster`.

Second, the `details` value is the URL to the *repo*. So, if you rename it here, you have to rename your repo   accordingly (which, again I recommend).

**Comment by FichteFoll** [comment]
As @math2001 mentioned, you must remove the `.git` in your details url.

Please note that you don't have any tags pushed to your repo (they must be [semantic versions](http://semver.org) and that the `alt+-` binding is already bound by default on some platform, causing your to override it. What you want to do instead is define the key bindings in a way that they are only active on JSON files. See also the [docs](http://docs.sublimetext.info/en/latest/reference/key_bindings.html).

**Pull request closed without merging**
