### PR TITLE
Add Oceanic Next Theme

### PR DESCRIPTION
**Pull request by voronianski**
https://github.com/voronianski/oceanic-next-theme

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

I would also prefer if you used the term "Color Scheme" more deliberate instead of "Theme" because that is incorrect ST terminology.

I doubt that `punctuation.definition.tag.*.*` is actually a scope name and you intended to just write `punctuation.definition.tag` here?

For color scheme development there is also https://packagecontrol.io/packages/CSScheme (which is more suitable), but it does not convert existing schemes to the CSScheme format yet.

And finally, since 6to5 is not your plugin I would usually ask the developer before we make a change, but since your tags are resonable I will just mention instead. @zertosh

**Comment by zertosh** [comment]
hey @voronianski, I'm cool with adding more labels, but they seem to case-sensitive: [javascript](https://packagecontrol.io/browse/labels/javascript) vs [JavaScript](https://packagecontrol.io/browse/labels/JavaScript), and there are more under javascript (all-lower-case). As for `ECMAScript6`, that's just noise - besides that's not strictly true since we're adding ES7 and Flow definitions (hopefully soon).

**Comment by FichteFoll** [comment]
cc @wbond, imo labels should not be case-sensitive, or should they?

**Comment by zertosh** [comment]
I agree with @FichteFoll - I always assumed labels were case-insensitive. I only tried lowercase "javascript" because there are only 4 results for "JavaScript".

**Comment by wbond** [comment]
Labels are case sensitive, because the user interface for labels is URLs, and URLs are case sensitive unless you write code to do redirects and stuff like that.

**Comment by voronianski** [comment]
@FichteFoll 

> Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

switched to tags - https://github.com/wbond/package_control_channel/pull/4075/files#diff-36e92b7c4e2886182c4935d82f760448R97

> I would also prefer if you used the term "Color Scheme" more deliberate instead of "Theme" because that is incorrect ST terminology.

It actually uses "Color Scheme" term now - https://github.com/wbond/package_control_channel/pull/4075/files#diff-36e92b7c4e2886182c4935d82f760448R91

@zertosh, I've changed label `JavaScript` to `javascript`, hope this is OK. :smile:

**Comment by FichteFoll** [comment]
>It actually uses "Color Scheme" term now - https://github.com/wbond/package_control_channel/pull/4075/files#diff-36e92b7c4e2886182c4935d82f760448R91

It did that before, actually. I was more referring to the heading in your readme and the image.

**Comment by zertosh** [comment]
thanks @voronianski and @FichteFoll

**Comment by voronianski** [comment]
@FichteFoll thanks :+1:

**Pull request merged**
