### PR TITLE
New package added. Django-Rest-Snippets

### PR DESCRIPTION
**Pull request by Bernardoow**
Repository: https://github.com/Bernardoow/Django-Rest-Snippets
Tags page: https://github.com/Bernardoow/Django-Rest-Snippets/tags
Release page: https://github.com/Bernardoow/Django-Rest-Snippets/releases

### CODE REVIEW

**Comment by Bernardoow** [comment]
I try send two package.

Repository: https://github.com/Bernardoow/Django-Model-Converter
Tags page: https://github.com/Bernardoow/Django-Model-Converter/tags
Release page: https://github.com/Bernardoow/Django-Model-Converter/releases

**Comment by FichteFoll** [comment]
Your `messages.json` file in the first repo is empty. You should add `{"install": "messages/install.md"}`.

Also, please submit a new pull request for each package in the future.

**Comment by Bernardoow** [comment]
@FichteFoll 

I removed the message files. And remove second package infos from d.json.

I will create new pr now.

**Comment by FichteFoll** [comment]
You removed the `messages.josn` file but you didn't push a new tag with the changes, so users won't benefit from it (and package control might show an error on installation).

PS: "in the future" means "for the next time", so you didn't have to remove the other package this time. Either way, for submitting a separate pull request you would create a new branch on your fork and commit on that.

**Comment by Bernardoow** [comment]
@FichteFoll 

Sorry for my mistakes.

I changed tag to 0.0.2 . 
And added again the other package. 

And thanks for tip about the branch.

**Comment by FichteFoll** [comment]
It seems you forgot to push the commit where you added the other package though. I'll wait for that.

**Comment by Bernardoow** [comment]
@FichteFoll 

Sorry again ;x Now arrived the commit

**Pull request merged**
