### PR TITLE
Add AutoYAPF package

### PR DESCRIPTION
**Pull request by catch22**

### CODE REVIEW

**Comment by FichteFoll** [comment]
How about adding this functionality to https://packagecontrol.io/packages/PyYapf%20Python%20Formatter as an option instead?

cc @jason-kane

**Comment by jason-kane** [comment]
Happy to take a PR. It is a good addition; if I don't see anything in the
next week or two I'll add it myself.

**Comment by catch22** [comment]
It sounds like a great idea to add this feature to PyYapf.

AutoYAPF differs in a number of design and implementation decisions from PyYapf. Perhaps I'll discuss them with @jason-kane and we will take it from there!

**Comment by catch22** [comment]
Done & the changes will arrive in the next release of PyYapf.

**Comment by FichteFoll** [comment]
Nice!

**Pull request closed without merging**
