### PR TITLE
'Select Regex' package

### PR DESCRIPTION
**Pull request by mvoidex**
https://github.com/mvoidex/SublimeSelectRegex
It also replaces 'Select By Regex', which is not maintained anynore: https://github.com/tarwich/SelectByRegex/issues/5#issuecomment-167193286

### CODE REVIEW

**Comment by FichteFoll** [comment]
>Will it replace package on update (which may not be good)?

Yes, it would be replaced. Which is good imo, unless you removed significant functionality. The old package is discontinued anyway. Thus, I suggest adding the old name to a `previous_names` array if you don't wish to continue the package name.
I suggest preparing an update message for the takeover however.

I don't need extra confirmation from @tarwich btw, the referenced issue is enough.

**Comment by FichteFoll** [comment]
Also, the rename caused the package to be out of order.

**Comment by mvoidex** [comment]
> I suggest preparing an update message for the takeover however.

Ok, I'll add update message

**Comment by mvoidex** [comment]
Seems, that 'Select By Regex' used incorrect tags: 'v1.1.2' instead of '1.1.2' (or is it acceptable too?)
If I use tag '2.0.0' for my plugin, will it show update message correctly?

**Comment by mvoidex** [comment]
I've renamed repo name, added tag '2.0.0' and update message.
Please, let me know, If there's anything I have to do

**Comment by FichteFoll** [comment]
>Seems, that 'Select By Regex' used incorrect tags: 'v1.1.2' instead of '1.1.2' (or is it acceptable too?)

Package Control will automatically remove the `v` prefix from tags if it finds one. For other prefixes, one would have to specify a string with the prefix for the `tags` key.

>If I use tag '2.0.0' for my plugin, will it show update message correctly?

Yes.

**Comment by mvoidex** [comment]
Ok, thanks for help!

**Pull request merged**
