### PR TITLE
Add Tower

### PR DESCRIPTION
**Pull request by tedmiston**
Open git repos from Sublime Text in [Tower](https://www.git-tower.com/mac/).

(No other packages for Tower exist.)

### CODE REVIEW

**Comment by tedmiston** [comment]
Hey @wbond this is my first contribution to Sublime.  I know you're busy and the docs indicate that human review could take a few days or more.  I'm also considering push out minor improvements, adding tests, etc in the mean time beyond 1.0.0.  Would doing that affect / delay the human review process?

**Comment by tmelot2** [comment]
@tedmiston I'm super new here, so take what I'm saying with a grain of salt, but it seems like the review process isn't very fast atm. I think only a tiny handful of people, if even that many, are reviewing stuff, so it's understandably slow. I submitted a thing 17 days ago and haven't seen any movement yet.

Would definitely be nice if there were more people available to review and merge stuff.

**Comment by tedmiston** [comment]
Hmmph, I've been a longtime Sublime user but multiple weeks to merge something small is surely a frustrating experience.

If the number of reviewers is a bottle neck, it would be nice to broaden the tier of trusted committers like how Kubernetes has done at scale.  The process is heavily automated and really fast despite many contributors and complex codebase.

I wonder if they would consider opening it up to the community more or if there's an alternative incubator-style package channel that accepts quickly?

**Comment by wbond** [comment]
We regularly ask people to review packages, but they basically never do one or two reviews while waiting for their package to be reviewed.

Anyone can look over the submission, and follow the reviewing guidelines on the wiki. Once a user has demonstrated consistent reviews, I’d be happy to add them to have merge rights.

Are you going to volunteer?

**Comment by tedmiston** [comment]
Hmm, yeah I could see that problem.  I do some open source contrib for work so definitely starting to see some of these patterns in other projects.

I'm happy to review some — @tmelot2 's package is useful to me so I can start with that one.

Somehow, I missed that the wiki PR process doc exists.  What do you think of moving it into either the main repo like this https://github.com/apache/incubator-airflow/blob/d9bf1edd44af847aa1f9ecd9d797dfacb806cc00/CONTRIBUTING.md or the dev docs site to increase visibility?

I'll take a look at that wiki doc to start.

**Comment by tmelot2** [comment]
I'd be down to review some stuff and contribute. I want to make sure I'd do right by the channel and the community so I'll prolly start by just looking over merged PRs just to get a good feel for what yall are looking for. Outside of the reviewing guidelines in the wiki, are there any specific good examples to take a look at? This is my first open source contrib, so I want to 

@tedmiston Thanks for offering to check mine out; it's definitely pretty simple so prolly not a bad place to start...but I know there are others who have been waiting for longer than me so maybe check one of those out too!

**Comment by Thom1729** [comment]
- Is the `__init__.py` necessary for any reason?
- What happens if you invoke the command on an unsaved view with no file name?

**Comment by tmelot2** [comment]
> What happens if you invoke the command on an unsaved view with no file name?
Tested this, `sublime_tower.py` errors on [line 69](https://github.com/tedmiston/sublime_tower_plugin/blob/366f74d110829ff2add40bebcf405abfe257b445/sublime_tower.py#L69).

**Comment by Thom1729** [comment]
In that situation, it should probably either do nothing or print a clear error message.

**Comment by tedmiston** [comment]
Hey all - Thank you for reviewing this and identifying the bug(s) here.  This is great!

I'm completely overloaded at work right now and haven't touched this, but I will reply back with an updated branch as soon as I can.

**Comment by tedmiston** [comment]
@tmelot2 Thanks, and you're right, I have removed the `pass` no-op.  Other git clients would be cool.  I haven't thought about it much yet.  I'm looking for if there any git clients that support more advanced ways of opening files, such as telling it whether to open in a new tab vs new window.  I'll poke around the alternatives you found and see if there are any other features there we might be able to add here.

@Thom1729 Nope, I just removed it.

I have also patched the unsaved/new file case with a clear error message.

The new version is available at the same URL if you'd like to try it.

**Comment by tedmiston** [comment]
Hey @tmelot2 @Thom1729 - I published a new build [1.0.3](https://github.com/tedmiston/sublime_tower_plugin/releases/tag/1.0.3) handling the case where the `$ gittower` CLI is not installed.

Checking Package Control I still see the previous version.  Do know how the long delay is between publishing a release and when it shows up in PC?

By the way, I also have some other changes in the pipeline coming soon for a fallback way to open Tower in this case (WIP), and an option to launch Tower backgrounded.

**Comment by Thom1729** [comment]
It can take a couple of hours. There's a crawler script that re-checks repositories periodically.

**Comment by tedmiston** [comment]
Thanks!  Look like it has been picked up now. 👍

**Pull request merged**
