### PR TITLE
Add Laravel Latest Migrations

### PR DESCRIPTION
**Pull request by aymericauberger**
This package does the same as the Rails Latest Migration package, but for Laravel apps: it simply opens the last migration file from the migrations directory.

### CODE REVIEW

**Comment by Thom1729** [comment]
Instead of having a `WindowCommand` and getting `active_view()`, you should have a `TextCommand`.

Have you tested the recursion base case on Windows?

**Comment by Thom1729** [comment]
@aymericauberger ping

**Comment by aymericauberger** [comment]
@Thom1729 Thank you for these corrections!

I'm sorry this is my first Sublime package, I didn't really dig into the documentation but just adapted an existing one. I switched to a `TextCommand`, I hope I did it correctly.

And no I didn't test on Windows, only on OS X, should I mark it OS X only?

I also made another, almost identical package, for opening the latest Laravel log file. Do you think they should be combined into one?

**Comment by aymericauberger** [comment]
I actually found a package that does the same thing for multiple frameworks, it's probably better to keep only this one: https://packagecontrol.io/packages/Latest%20Migration
I submitted a pull request to add Laravel support: https://github.com/zaidakram/latest-migration/pull/1

**Pull request closed without merging**
