### PR TITLE
add AutoAligner package

### PR DESCRIPTION
**Pull request by generall**
Package for automatic code aligment based on BNF and Needleman–Wunsch algorith.

### CODE REVIEW

**Comment by FichteFoll** [comment]
`path = sublime.packages_path() + "/aligner"` will fail because the package will be saved as `AutoAligner` (as specified in this PR).

Your `Popen` call will also fail on ST3 because it is package into a `.sublime-package` there. Add a `.no-sublime-package` file to the repo to tell PC to unpack it.

You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

```
				req_version = (2,7)
				cur_version = (sys.version_info.major, sys.version_info.minor)
				if cur_version > req_version:
```
could also be written as `if sys.version_info > (2, 7):` (even though I think you mean `>=`.

**Comment by generall** [comment]
Thanks for review. Remarks are fixed

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) have three numeric parts.

**Comment by generall** [comment]
Fixed

**Pull request merged**
