### PR TITLE
Add CodeChampion package

### PR DESCRIPTION
**Pull request by saadeghi**
Added this sublime package: https://github.com/Atbox/CodeChampion

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Because you are invoking external commands that require actual files as parameters and ST3 by default stores installed packages in an archived `.sublime-package` file, you need to add a `.no-sublime-package` file to your repo in order to tell Package Control to unpack your package.

**Comment by saadeghi** [comment]
@FichteFoll Done. Thanks.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by saadeghi** [comment]
@FichteFoll I changed to 1.0.0 is it OK now?

**Pull request merged**
