### PR TITLE
add plugin

### PR DESCRIPTION
**Pull request by evercyan**

### CODE REVIEW

**Comment by braver** [comment]
Hi!

Can you perhaps explain what your package does, and why Tony Water is a good name for it? Not just for me, but also to help others find your package. 

It looks like a collection of string and json manipulation utilities. Perhaps you can elaborate on what your package adds to what is already out there in package control? You already have 2 abandoned packages in package control, maybe it's a good idea to replace one of them with this new one. Also, it would be nice if this one doesn't go missing after a while again...

As for the package itself. You create a context menu. We also recommend adding all commands to the command palette, via a Default.sublime-commands file. This helps users look for and discover commands, and it also enables triggering the commands without reaching for your mouse/trackpad.

**Comment by evercyan** [comment]
> Hi!
> 
> Can you perhaps explain what your package does, and why Tony Water is a good name for it? Not just for me, but also to help others find your package.
> 
> It looks like a collection of string and json manipulation utilities. Perhaps you can elaborate on what your package adds to what is already out there in package control? You already have 2 abandoned packages in package control, maybe it's a good idea to replace one of them with this new one. Also, it would be nice if this one doesn't go missing after a while again...
> 
> As for the package itself. You create a context menu. We also recommend adding all commands to the command palette, via a Default.sublime-commands file. This helps users look for and discover commands, and it also enables triggering the commands without reaching for your mouse/trackpad.

Thanks for ur reply. 
"Tony Water" means "拖泥带水" which is a chinese idiom transliteration.
It's a good name for me because this plugin is a collection of my small tools, but not for a single use sence.
About my 2 abandoned packages, I have no idea how to remove them.

**Comment by braver** [comment]
Thanks! It looks like it makes sense to replace both your existing packages with this new one via a "previous_names" key. That would reconcile the existing packages and move any existing users over to the new one.

**Comment by evercyan** [comment]
> Thanks! It looks like it makes sense to replace both your existing packages with this new one via a "previous_names" key. That would reconcile the existing packages and move any existing users over to the new one.

Thanks~ It's done.

**Pull request merged**
