### PR TITLE
Add FT Origami

### PR DESCRIPTION
**Pull request by kaelig**
screenshot 2015-07-02 11 01 03

### CODE REVIEW

**Comment by FichteFoll** [comment]
So, what is the difference to ColorHighlighter?

**Comment by kaelig** [comment]
This is for the Financial Times Origami colour scheme. Actually, maybe I should create a FT Origami package instead, since we might add stuff to it later such as autocompletion and HTML snippets.

What do you think?

**Comment by kaelig** [comment]
This is what Origami is all about: http://origami.ft.com/
And the color module's documentation is here: http://registry.origami.ft.com/components/o-colors@3.0.0

**Comment by kaelig** [comment]
@FichteFoll I've renamed the repo and made it clear what it was. We we use Sublime a lot at the Financial Times, and a lot of third party partners also do.

**Comment by FichteFoll** [comment]
Okay.

However, your repo url 404s. And you'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by kaelig** [comment]
Thank you @FichteFoll. I have updated the file and released a v1, hope everything is ok now.

**Comment by kaelig** [comment]
Thank you very much @FichteFoll.

**Pull request merged**
