### PR TITLE
Include Fuse Snippets package, handy snippets for fusetools

### PR DESCRIPTION
**Pull request by igorls**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Maybe you want to add this to the [Fuse package](https://github.com/fusetools/Fuse.SublimePlugin) directly?

cc @knatten, @Tapped

**Comment by knatten** [comment]
Thanks for the suggestion @FichteFoll! However, merging that package into ours will require us to start maintaining these snippets for the future, which we unfortunately can't prioritise.

**Comment by igorls** [comment]
@FichteFoll I also agree with that, because not every user wants/need to have a lot of snippets.. Anyway that's up to the Fuse team to decide, I'm committed to maintaining compatibility to the latest fuse version ;)

**Comment by FichteFoll** [comment]
Fine with me. You can always merge packages when you change your mind(s).

**Pull request merged**
