### PR TITLE
Master

### PR DESCRIPTION
**Pull request by alexkorovkov**
I suppose that after deleting this line read will be shown without additional html code (see https://packagecontrol.io/packages/TeXPreview)

### CODE REVIEW

**Comment by FichteFoll** [comment]
The https://packagecontrol.io/packages/LaTeXTools package also provides this feature. Do you believe your package is needed next to that and if so, why?

**Comment by FichteFoll** [comment]
@alexkorovkov ping

**Comment by alexkorovkov** [comment]
@FichteFoll I know, that LaTeXTools provides the same but there are some differences:
1. TeXPreview can show not only an equation but block of latex code, for example: tables, theorems and etc.
2. Preview can be shown in build window (as for me it's better when you write code because following lines don't "jump")
3. You can see the preview in external program

Actually I don't know if someone uses it.

**Comment by FichteFoll** [comment]
Okay, so it seems that github was playing a trick on me because their PR diff only showed you adding a package entry and not modifying one, which is why I thought this was a package addition. However, the package is already listed.

I can't see right now what you actually changed and am to lazy to check out the commit myself, so let's just see what github makes out of it when I merge.

**Comment by FichteFoll** [comment]
Well, nothing was changed ...

**Comment by alexkorovkov** [comment]
Yes. It was my fault. I wanted to delete only a "readme" line. Create a new request.

**Pull request merged**
