### PR TITLE
add complete_xml_tag

### PR DESCRIPTION
**Pull request by Neophyliam**
This package can convert non-standard close tag (</>) in an xml file to corresponding standard close tag.

### CODE REVIEW

**Comment by Thom1729** [comment]
Instead of matching the file extension, it's probably better to check `view.match_selector(0, 'text.xml')`. You might also make this extensible via settings so that users can use the package with other XML-based syntaxes that might use different scopes. Also, this check should ideally be in an `is_enabled()` method rather than in `run()`.

It's generally better to use standard built-in exceptions than to define your own. In this case, `ValueError` would be appropriate. Also, you shouldn't run `self.view.replace(edit, string_region, new_string)` if `complete_close_tag` failed.

**Comment by Neophyliam** [comment]
@Thom1729 Thanks for your review and advice! I have made some improvements to this package.

* Put the code for checking file type to `is_enabled()` method.
* Check file type using `view.match_selector(point, selector)` method.
* Add a settings file to support other XML-based syntaxes.
* Use `ValueError` instead of my custom exception.
* Handle other types of exception so that `self.view.replace(edit, string_region, new_string)` won't be run if `complete_close_tag` failed.

Thank you :)

**Comment by Thom1729** [comment]
I forgot to mention — package names are generally capitalized unless there's a strong reason not to.

Everything else looks fine.

**Comment by Neophyliam** [comment]
I have made the package name capitalized and updated related files in this package. Hope there’s no other problem this time.

**Pull request merged**
