### PR TITLE
Wild Cherry

### PR DESCRIPTION
**Pull request by mashaal**
Addition of Wild Cherry Theme

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

Since your master branch is different from what you want to release with Package Control you might want to check out the tag prefix feature as outlined in [`example-repositories.json`](https://github.com/wbond/package_control/blob/3fe18df361b67bd94276936d5707c349f8660ae6/example-repository.json#L273-L333) and use `st-` to flag the tag as sublime text-specific.

Furthermore, you should indicate in either title or labels that this package is a theme (and a color scheme as well).

**Comment by mashaal** [comment]
I've added labels to indicated theme and color scheme, removed the previous branch (and cleaned up my master branch). :package:

**Comment by FichteFoll** [comment]
You still have to push a tag though.

**Comment by mashaal** [comment]
ah- first time using tags- added 1.0.0

**Comment by FichteFoll** [comment]
Great, everything's fine now.

**Pull request merged**
