### PR TITLE
Adding PasteRepeater Plugin

### PR DESCRIPTION
**Pull request by philsinatra**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your fork is outdated, I cannot merge.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Please try not to override default key bindings.

**Comment by philsinatra** [comment]
I've updated my fork and added the version tag. I've also adjusted the Windows/Linux key bindings to hopefully avoid overriding any defaults.

**Comment by FichteFoll** [comment]
I'm not entirely sure whether this will merge well. Could you perhaps rebase and force-push instead of merging? Alternatively, start a new pull request from a fresh branch off master.

**Comment by philsinatra** [comment]
I created a fresh fork and clean request, it should be smooth on your end now.

**Pull request closed without merging**
