### PR TITLE
Added Theme Switcher plugin

### PR DESCRIPTION
**Pull request by geekpradd**
This is the plugin I asked you for help, @FicheteFoll. 
It works nicely in ST3 on both Windows and Linux although I was unable to implement a Background Task to watch for new Theme Installation. Instead I added a GUI "Refresh Theme Cache" option.

### CODE REVIEW

**Comment by FichteFoll** [comment]
There are a few theme-switching packages already out there, but they are all a bit different in their usage. It would be preferrable if you could indicate the usage pattern of your package in its name, e.g. "Theme Menu Switcher" or "Themes in Menu" or similar.

https://packagecontrol.io/packages/QuickThemes
https://packagecontrol.io/packages/Themr

**Comment by FichteFoll** [comment]
Using the `json` module for modifying the theme setting is error prone because it can't handle comments (which are allowed in `.sublime-settings` files). Use `sublime.load_settings` and `sublime.save_settings` instead.

**Comment by geekpradd** [comment]
Okay, I changed the name and I am using the Sublime API for modifying settings.

**Comment by FichteFoll** [comment]
I just noticed that you crawl the zip files manually, only search in those tha follow the `Theme - <name>` convention and don't consider the normal packages not at all.

Just use `sublime.find_resource`.

**Pull request merged**
