### PR TITLE
RDate Editor

### PR DESCRIPTION
**Pull request by Rivfadersp**
Helps to edit dates in russian language.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Ctrl+Shift+H is a default key binding. Please either choose a different binding or don't define a binding at all and instead offer a menu item and command palette entry (and suggest a binding in your readme).

**Comment by Rivfadersp** [comment]
Thank you for your remarks! I just learning to program, so hope that i did everything correctly this time.

**Comment by FichteFoll** [comment]
You will know when you successfully pushed a tag to the repository when it appears [here](https://bitbucket.org/SergeyEg/date-editor#tags) in that list. There are online resources on how to do this, for example the one I linked.

I'm pretty sure you can not trigger a key binding like `"ctrl+c+d"`- at least I can't.

**Comment by Rivfadersp** [comment]
Done.

**Pull request merged**
