### PR TITLE
Add PurpleHaze color scheme for Sublime Text

### PR DESCRIPTION
**Pull request by klomontes**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by klomontes** [comment]
@FichteFoll I have completely skipped that step. Sorry about that and thanks for help. Should be ok now.

**Comment by FichteFoll** [comment]
It appears you didn't push the tag properly, because it does not appear on this page: https://github.com/klomontes/purple-haze-color-scheme/tags

**Comment by klomontes** [comment]
@FichteFoll I didn't push the tag. :/ It is there now.

**Comment by klomontes** [comment]
@FichteFoll Thanks!

**Pull request merged**
