### PR TITLE
Add Laravel 5 Snippets

### PR DESCRIPTION
**Pull request by Lykegenes**
Hi!

There is currently another similar package in the channel, but the author deleted his Github account so it's unavailable. The missing package name is "Laravel Five Snippets" if you want to remove it.

Thanks!

### CODE REVIEW

**Comment by FichteFoll** [comment]
You are right, the other package author (and package alike) seems to be gone.

I suggest you move the old users to your new package by adding its name to a "previous_names" array in your package info.

**Comment by Lykegenes** [comment]
I made the changes, the package is ready!

**Comment by FichteFoll** [comment]
I forgot to mention that you need to remove the old package from the json as well.

**Comment by Lykegenes** [comment]
Done, Thanks!

**Pull request merged**
