### PR TITLE
SwiftSyntax - syntax highlighting for Swift 3.0 in .sublime-syntax format

### PR DESCRIPTION
**Pull request by GregoryBL**
Please provide the following information:
- Link to your code repository: [https://github.com/GregoryBL/SwiftSyntax](https://github.com/GregoryBL/SwiftSyntax)
- Link to the tags page with at least one [semver](http://semver.org) tag: [https://github.com/GregoryBL/SwiftSyntax/tags](https://github.com/GregoryBL/SwiftSyntax/tags)

Also make sure you:
1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by joshua-golub** [comment]
GregoryBL-

Would you please clarify for me what your Swift syntax provides that other similar packages (for example, [this one](https://github.com/quiqueg/Swift-Sublime-Package)) don't provide?

-Josh

**Comment by GregoryBL** [comment]
@joshua-golub ,

As far as I am aware it’s the only (more-or-less complete, c.f. https://github.com/colinta/Swift-for-f-ing-sublime) one that uses the modern sublime-syntax format as opposed to the older tmLanguage format, which is harder (at least for me) to work with. I haven’t looked at the one you linked in great detail, but it doesn’t seem to use the meta-descriptors to give as rich of semantic meaning to, for example, class definitions. 

Perhaps that’s not enough given all of the additional tooling around that project, but I thought this one would give a nicer path forward for development. I’m sure you have a better ability to gauge that than I do.

Thanks for the review,
Greg

**Comment by joshua-golub** [comment]
@FichteFoll, this package looks good to me.

**Comment by FichteFoll** [comment]
FYI, Swift is peding addition as a default package: https://github.com/sublimehq/Packages/pull/11, however the current state of this is unclear. Maybe you are interested in picking that up and making sure everyone gets proper Swift support?

For now, unless you can explain the differences between the existing two pakages (maybe with pictures), I don't really see a need for this.

Btw, your readme link to Package Control is backwards.

**Comment by GregoryBL** [comment]
Thanks, I'll work on contributing to those other projects.

**Pull request closed without merging**
