### PR TITLE
Add NativeBase Snippets

### PR DESCRIPTION
**Pull request by SupriyaKalghatgi**
- https://github.com/GeekyAnts/native-base-sublime-package
 - https://github.com/GeekyAnts/native-base-sublime-package/tags

### CODE REVIEW

**Comment by math2001** [comment]
You need to give more info in your `readme`.

**Comment by SupriyaKalghatgi** [comment]
@math2001 Added basic details in `ReadMe`

**Comment by SupriyaKalghatgi** [comment]
@math2001 Hey, its been long time for this PR
No one to look over?

**Comment by FichteFoll** [comment]
Your package is providing "snippets" and not "auto-completions", because those would be context-aware (e.g. local variables and/or type awareness). Please remove the label.

**Comment by FichteFoll** [comment]
@SupriyaKalghatgi ping

**Comment by SupriyaKalghatgi** [comment]
@FichteFoll Done that

**Comment by FichteFoll** [comment]
Also, there isn't really any reason why this package should be platform-restricted, since it only provides snippets. I suggest you allow installation on Windows as well.

**Comment by SupriyaKalghatgi** [comment]
@FichteFoll True that
Updated

**Comment by SupriyaKalghatgi** [comment]
@FichteFoll Waiting for this PR to be merged

**Comment by FichteFoll** [comment]
Everyone is.

**Comment by SupriyaKalghatgi** [comment]
@FichteFoll Thank you

**Pull request merged**
