### PR TITLE
Add phpunit-completions; Closes gerardroche/sublime-phpunit-completions#2

### PR DESCRIPTION
**Pull request by gerardroche**
I submitted this package before but it was rejected because it was too similar to other packages. The other packages are either unmaintained or similar but not the same.

Up to you. Merge, close, pull changes into another package, it's ok with me.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Well, I can see that you have quite a few more completions for different aspects compared to https://github.com/tkowalewski/phpunit-sublime-completions, but I still don't really see something that would prevent you from adding the snippets there. Maybe @tkowalewski could take a lot at yours and say if he'd be fine with them being added to his repo, or giving you push access.

Besides, the names are way too similar.

(for future reference: https://github.com/wbond/package_control_channel/pull/3649)

**Comment by gerardroche** [comment]
ping @tkowalewski what do you think?

These completions render most of the snippets in the [PHPUnit Snippets](https://packagecontrol.io/packages/PHPUnit%20Snippets) package redundant. The snippets package will cause duplicate auto completes and unexpected behaviours. \cc @florianeckerstorfer

**Comment by tkowalewski** [comment]
@gerardroche Push access granted, feel free :)

**Comment by FichteFoll** [comment]
@gerardroche did you settle this? (and #4609)

**Comment by gerardroche** [comment]
Cool.

**Pull request closed without merging**
