### PR TITLE
added Pest Syntax

### PR DESCRIPTION
**Pull request by dten**

### CODE REVIEW

**Comment by dten** [comment]
have since added README

**Comment by dten** [comment]
@wbond I imagine you're busy but how often are these looked at? is there something else that needs asserting?

**Comment by wbond** [comment]
@dten Unfortunately due to my personal life, I have a severe deficit of free time, so I am relatively uninvolved in reviewing.

We have gracious, hardworking volunteers in @FichteFoll and @Thom1729 who do the majority of the work these days. In general requests are done in order of submission. You can get an idea of where you are in line by looking at the open pull requests.

**Comment by dten** [comment]
Thanks for the info Will

**Comment by Thom1729** [comment]
Generally, you would append `.pest` to the scopes in the syntax, e.g. `scope: support.function.override.pest`.

**Comment by dten** [comment]
Yep sure thing

**Comment by dten** [comment]
done

**Pull request merged**
