### PR TITLE
Add Torquescript highlighting package

### PR DESCRIPTION
**Pull request by ConanODoyle**
Torquescript is the scripting language of Torque Game Engine and Torque3D, and currently no highlighting package for the language exists on Package Control.

### CODE REVIEW

**Comment by braver** [comment]
Your package contains many text-mate-specific files no longer supported by ST like tmCommand. The `info.plist` file should also not be there. I would recommend cleaning it up a little and converting the syntax to the new format (there is a formatter built into ST).

**Comment by braver** [comment]
Please respond to continue the PR.

**Comment by ConanODoyle** [comment]
I am currently busy and cannot currently handle fixing the package. It is
an old package that a friend made (he does not do programming anymore), and
I made the PR to try to make this package more accessible to others that
might want to use it.

Is there a way to put this PR on hold so when I have time later I can fix
it?

**Comment by braver** [comment]
Let’s just close it for now, we can always open it again later.

**Pull request closed without merging**
