### PR TITLE
Add IrView package

### PR DESCRIPTION
**Pull request by guilhermeleobas**
A package to generate control flow graphs of LLVM Intermediate Representation directly from Sublime Text.

### CODE REVIEW

**Comment by guilhermeleobas** [comment]
Just updated the package

**Comment by Thom1729** [comment]
If a command works on a particular view, it should be a `TextCommand`, not a `WindowCommand`, so that you can use `self.view` instead of `self.window.active_window()`.

**Comment by guilhermeleobas** [comment]
Thanks for the tip. Just updated the plugin.

**Comment by Thom1729** [comment]
The hardcoded `/tmp/` doesn't look cross-platform. Can you use the builtin `tempfile` and `shutil` modules?

**Comment by guilhermeleobas** [comment]
> The hardcoded `/tmp/` doesn't look cross-platform. Can you use the builtin `tempfile` and `shutil` modules?

Thanks for the tip. I have updated the package to be less platform dependent.

**Pull request merged**
