### PR TITLE
New Snippet: Placehold.it

### PR DESCRIPTION
**Pull request by bartholomej**
Website: https://github.com/bartholomej/sublime-placeholdit
Release: https://github.com/bartholomej/sublime-placeholdit/releases/tag/v1.0.0
For Sublime Text 2 and 3

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

Please also consider not using dots in package names since they break Python plugins completely. You don't define any currently, but better be defensive here.

**Comment by bartholomej** [comment]
Thank you for your quick feedback @FichteFoll and sorry for my mistake.
I know using branches is deprecated and I was prepared to use tags. Just typing error in definition ;)

Good point with python *dot problem* in the name. It's pity that I had to give up the real name of service (placehold.it)... but I just replaced *dot* with *dash*.

I hope it's OK ;)

**Comment by FichteFoll** [comment]
Interestingly your latest commit made me aware of the existance of [the other placehold.it package](https://packagecontrol.io/packages/Placehold.it%20Image%20Tag%20Generator). Isn't that more flexible than your snippet? Or did you just not know about it because it is not marked for ST3 (and wouldn't work with it either since it contains the evil dot, but could probably be fixed very easily). Maybe you can help @SubZane a bit and update the package with missing functionality or take it over completely in case he doesn't want to maintain it anymore.

**Comment by SubZane** [comment]
If anyone wants to take over maintenance of Placehold.​it Image Tag Generator I'd be happy since I no longer have the time to support it :)

**Comment by bartholomej** [comment]
OK guys, you're right. This will be better ;)
@SubZane If you don't want to maintain it anymore, can I ask you for transfering ownership or something like that? I think you've moved over to Atom.io, right? ;) And also this will be better for future maintenace.
Firstly we want to fix it for ST3 and also we're planing some new features ;)
Thank you for your work, you did a well job ;) :+1:

**Comment by SubZane** [comment]
@bartholomej I cannot transfer ownership because you have a fork and it's conflicting. I added you as a collaborator in the meantime :)

**Comment by FichteFoll** [comment]
All right, I'm closing this issue then.

**Pull request closed without merging**
