### PR TITLE
Added LiveStamps Plugin Meta

### PR DESCRIPTION
**Pull request by TundraTech**

### CODE REVIEW

**Comment by wbond** [comment]
You had the version operator correct the first time. What you've specified right now will only allow it to be installed on ST2 and the very first build of ST3, which I don't believe was ever available to the public.

**Comment by TundraTech** [comment]
Sorry, it uses async_timeout so anything above that version is fine

**Comment by wbond** [comment]
Sorry, it looks like I missed this the first pass through. We no longer accept new packages that use branch-based releases. So you'll need to change `"branch": "master"` to `"tags": true` and create a tag in your repo every time you want to create a new version for users to download.

The tags must follow the semantic versioning (semver) specification. I.e. a three part number such as `1.0.0`.

**Comment by TundraTech** [comment]
Thanks will I created a 1.0.0 release and added tags key

**Pull request merged**
