### PR TITLE
Transparency

### PR DESCRIPTION
**Pull request by rexdf**
Make the windows transparency

### CODE REVIEW

**Comment by FichteFoll** [comment]
Generally, if possible, please try to get in contact with the original author of the package first. There is even a ticket for this, but it doesn't seem to have gotten any attention: https://github.com/vhanla/SublimeTextTrans/issues/1.
cc @vhanla

That aside, there is a package for this already at https://packagecontrol.io/packages/GlassIt, but it uses a different and less comfortable solution for the user (by depending on an external binary that needs to be downloaded), so adding this package would be fine.

Other general tip:
- When changing indentation (as in https://github.com/rexdf/SublimeTextTrans/commit/2971a5bf491b76ac7c0d85d7054a92c9f58608eb), do it in a separate commit and don't mix code changes in. Commits like this are unreviewable.

**Comment by rexdf** [comment]
I just make a fix to separate indentation and change codes. And try to get in contact with @vhanla .

**Comment by FichteFoll** [comment]
Any updates?

**Comment by rexdf** [comment]
No response  from @vhanla .

**Comment by FichteFoll** [comment]
Can't help him then, merged the PR.

**Pull request merged**
