### PR TITLE
Added CodeShark Plugin

### PR DESCRIPTION
**Pull request by JacobSamro**
Helps to bring code into the editor by searching. Users have to save the programs at https://app.codeshark.live to use it within the editor.

### CODE REVIEW

**Comment by JacobSamro** [comment]
I've made a release tag, please publish the extension

**Comment by JacobSamro** [comment]
I've made all the necessary changes. Will you please merge this pull request. thank you

**Comment by Thom1729** [comment]
- You should have a readme.
- `API_KEY` should probably be a setting rather than a global variable.
- `pickedID` should definitely be a command argument rather than a global variable.
- You don't need to pass no-op `on_change` and `on_cancel` callbacks to `show_input_panel`.
- There doesn't seem to be any error handling if an API request fails.

**Comment by JacobSamro** [comment]
Noted with thanks. Will give an update soon.

**Comment by JacobSamro** [comment]
Okay I'll work on it. Will you please help us to improve the plugin. Please fork the repo and contribute. Pull requests are always welcome!

**Comment by JacobSamro** [comment]
Changes has been made
1. Both of the opened file handlers are closed properly
2. We won't reuse the request that's why we haven't moved it to a function. We'll do it if there is a need in future
3. Now the code will be inserted on all the cursor positions
4. Yes the path is looks UNIX-specific. We have tested it on various platforms and it is working fine.
5. Exceptions are handled properly.

**Comment by JacobSamro** [comment]
@Thom1729 Will you please take a look. Thank you.

**Comment by FichteFoll** [comment]
1. Unless the `~/.codeshark` file is shared among multiple applications, it makes more sense to store the api key inside an ST settings file using
`settings = sublime.load_settings("CodeShark.sublime-settings"); settings.set("api_key", key); sublime.save_settings("CodeShark.sublime-settings")`.

1. Instead of overriding `Request.get_method`, just specify it in the constructor.

Imo catching `Exception` here is fine.

**Pull request merged**
