### PR TITLE
Add "Theme - Arzy" to t.json

### PR DESCRIPTION
**Pull request by rzProjects**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) tag (with optional leading `v`) to your repo.

**Comment by rzProjects** [comment]
Done and done!

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by rzProjects** [comment]
Got it! Done.

**Pull request merged**
