### PR TITLE
Add Competitive Programming Lite

### PR DESCRIPTION
**Pull request by JameelKaisar**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [ ] My package doesn't add context menu entries. `See Context Menu Below`
- [ ] My package doesn't add key bindings. `See Key Bindings Below`
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

About:
A simple, easy-to-use Sublime Text plugin to assist in Competitive Programming.

Repository:
https://github.com/JameelKaisar/Competitive-Programming-Lite

Context Menu:
The plugin has no entries in context menu in default mode. However in Competitive Programming mode, the plugin has two context menu entries: CP Test and CP Run. When user exits the Competitive Programming Mode, the menu entries are no longer available.

Key Bindings:
The plugin has four key bindings and these are necessary for creating and navigating through questions (files) efficiently. Competitive Programming usually has tight time constraints and having key bindings for most used functions is a reasonable thing to have. The key bindings are listed in the menu and the command palette and open in split view.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by JameelKaisar** [comment]
## Version 1.1.0 Released

### Changelogs
- Added Support for C
- Added Support for Java
- Minor Fixes

**Comment by braver** [comment]
We already have some [competitive programming packages](https://packagecontrol.io/search/competitive), how does yours compare?

**Comment by JameelKaisar** [comment]
## Existing Plugins

1. [Cpp​Fast​Olympic​Coding](https://packagecontrol.io/packages/CppFastOlympicCoding)
    - Excellent plugin for those who code in C++
    - Languages: C++ only
2. [Competitive Programming](https://packagecontrol.io/packages/Competitive%20Programming)
    - Basic plugin
    - Languages: C++ only
3. [CPP Competitive Programming Snippets](https://packagecontrol.io/packages/CPP%20Competitive%20Programming%20Snippets)
    - Snippets only
    - Languages: C++ only
4. [Get​Code](https://packagecontrol.io/packages/GetCode)
    - Problem parser
    - Platforms: Codechef, Codeforces, SPOJ, Virtual Judge

## Competitive Programming Lite
- Languages: C, C++, Java, Python
- Ability to test and compare program output with expected output with a single command.
- Ability to generate multiple template files with a single command.
- Ability to add /edit/delete custom templates to speed up coding.
- Easy to add support for more languages (see [C](https://github.com/JameelKaisar/Competitive-Programming-Lite/commit/378a6155eef666ef6b22b8b1364f23cc3fde5b6b), [Java](https://github.com/JameelKaisar/Competitive-Programming-Lite/commit/33f34f35100ce1ca8140d6700ec024678a5177cd))

**Comment by braver** [comment]
Thanks. Can you maybe tell us why .no-sublime-package is needed? Just from browsing through the repo it seems everything should be doable without.

**Comment by JameelKaisar** [comment]
There are couple of reasons why .no-sublime-package is needed:
1. [Adding Files] The user can add new templates. The templates are files stored in the plugin folder and are used as boilerplate codes to speed up coding.
2. [Renaming Files] There are two entries in the Context Menu (CP Test and CP Run) when user is in CP Mode. These options are not needed when user is not in CP mode. I couldn't find a way to get the current build system (see [Getting the current build system?](https://forum.sublimetext.com/t/getting-the-current-build-system/5886)) and decide whether Context Menu entries are relevant or not. The plugin renames the "Context.disabled-menu" file to "Context.sublime-menu" to enable the menu entries whenever user enters the CP Mode and vice versa.

**Comment by braver** [comment]
> The user can add new templates. The templates are files stored in the plugin folder 

That’s not a good idea. Updates of the package can then conflict with user files and uninstalling the package also removed the user data. Think of your package as an app: you don’t store user data in the same place as your app code. In ST user data goes in the User package. You can put a directory in there and your package can read files from it too.

> and decide whether Context Menu entries are relevant or not

Do you even really really need the context menu? It’s usually not the best place to put functionality, especially if it isn’t tied to an exact click-location. If your commands are in the command palette most users are able to find it, access it quickly, even without touching the mouse.

Maybe you need to slightly compromise on your features, but like the user templates an un-packaged package is usually a problem waiting to happen.

**Comment by JameelKaisar** [comment]
Both of your points are valid. I will make the necessary changes first then ping you back.

**Comment by rwols** [comment]
> The templates are files stored in the plugin folder and are used as boilerplate codes to speed up coding.

How is this different from clicking on Tools > Developer > New Snippet ?

**Comment by JameelKaisar** [comment]
Templates are different from Snippets because when we create a template, 4 to 5 additional files are created under `.cpl_files` folder. These include standard input/output files, the expexted output file and others files that help in comparing the output, etc. I prefer using snippets for the algorithms which I use the most while doing competitive programming. [CPP Competitive Programming Snippets](https://packagecontrol.io/packages/CPP%20Competitive%20Programming%20Snippets) plugin is based on the very same approach.

**Comment by jrappen** [comment]
Instead of adding default context menu entries and key bindings for your package and as a result for every end user, you should instead add documentation on how the end user makes use of the commands you have now added via context menus and/or key bindings while maybe adding the current defaults as suggestions to said documentation.

**Comment by jrappen** [comment]
Please do not override existing menu entries. Simply targetting by id should suffice.

**Comment by JameelKaisar** [comment]
1. Yes. I will remove Context Menu entries as suggested by @braver.
2. Also I'll add documentation instead of adding default Key Bindings.
3. I'll make changes to target menu entries by id only.
4. No, the videos don't need to be shipped to end user. Videos do not appear in the release files. I have maked videos folder as `export-ignore` in `.gitattributes` file. Would that be enough or should I remove the videos folder from the repo also? @jrappen
5. I will make the necessary changes and then test the compatibilty with previous versions of Sublime Text.

**Comment by braver** [comment]
Please report back after you make those changes and resolve the conflict of this branch with master.

**Comment by JameelKaisar** [comment]
## Version 1.2.0 Released

### Changelogs
- Change from 'No Sublime Package' to 'Sublime Package'
- Remove Context Menu Entries
- Remove Default Key Bindings
- Add Default Template for Key Bindings
- Remove Help Videos from Repository
- Target Menu Entries By ID Only

**Comment by JameelKaisar** [comment]
@braver I made the required changes and also resolved the conflict of this branch with master. You can merge this PR now.

**Pull request merged**
