### PR TITLE
Broken Window package added

### PR DESCRIPTION
**Pull request by ekalber**
Broken Window package added

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please address teh comments by @packagecontrol-bot.

Beware of hooking `on_modified_async` with operations that take a while to run in order not to block the background thread. It's not the UI thread, but it still shouldn't be taking a long-ish time for frequently occuring events either.

**Comment by FichteFoll** [comment]
@ekalber ping

**Comment by ekalber** [comment]
> @ekalber ping

Fixed, thanks for letting me know!

**Comment by FichteFoll** [comment]
My other comments above still stand, but it's not important enough to block on it.

**Pull request merged**
