### PR TITLE
add Finer Package Settings entry

### PR DESCRIPTION
**Pull request by celbig**
This package allow for a per project and/or per syntax configuration for any other package. I did not found any other package with this functionnality.

### CODE REVIEW

**Comment by celbig** [comment]
> ### Automated testing result: WARNING
...
> ```
> Processing package "Finer Packages Settings"
>   - WARNING: The package does not contain a top-level LICENSE file. A license helps users to contribute to the package.
> ```

The licence information is included in the README file

**Comment by braver** [comment]
Per syntax or project settings can already support settings per package. Here's a good example: http://www.sublimelinter.com/en/stable/settings.html#project

This isn't well documented, but ST already merges these settings in a way so that packages can handle them seamlessly. An extra package could be convenient, depending on its implementation, but it certainly isn't necessary.

**Comment by celbig** [comment]
From what I understand of your example this works only for specific packages that implement it. The point of my package is to enable this kind of configuration possibility for all installed packages without modifying the current source code of said packages.

If this is already possible from ST3 I am interested (and will of course close this pull request).

**Comment by braver** [comment]
Hm, you are correct. Most packages will only read and monitor their own settings file and not consider the state of settings per view. 

Alright, digging a bit further... From reading the README I don't have the foggiest on how I should actually use your package 😅  Where do I put the packagesSettings object?
 Also, you require a settings_file reference, but why would I need to strip the extension? Wouldn't it be clearer if it actually references the complete file name (letting your package deal with whatever post-processing you need)? 
 As I understand it your package writes to a particular file in the User space (with a lot of locking/unlocking going on?). That sounds like something worth documenting.

**Comment by braver** [comment]
Please respond to the questions to continue the review.

**Pull request closed without merging**
