### PR TITLE
Schnapsum

### PR DESCRIPTION
**Pull request by airqz**
It allows you to Insert Schnapsum like Lorem Ipsum in the editor via menu items or keyboard shortcut.

### CODE REVIEW

**Comment by airqz** [comment]
add tag

**Comment by airqz** [comment]
add tag with git

**Comment by Thom1729** [comment]
- You should add a license.
- Is `re` used anywhere?
- Why do you call `self.view.end_edit(edit)`.
- You might declare `words` a  constant outside the command.

**Comment by airqz** [comment]
thank you for your proofreading and review

**Comment by airqz** [comment]
Change invalid key

**Pull request merged**
