### PR TITLE
added SikuliTools package

### PR DESCRIPTION
**Pull request by hendrikelsner**

### CODE REVIEW

**Comment by wbond** [comment]
The `readme`, `name` and `description` fields will all automatically be pulled from your GitHub repo, so you can remove them from this PR.

**Comment by hendrikelsner** [comment]
thanks. i did that.

**Comment by FichteFoll** [comment]
The `packages.json` file is redundant. Please remove it.

The `.no-sublime-package` file is redundant as well, please remove it also.

**Comment by hendrikelsner** [comment]
thx @FichteFoll. I removed the files from repository.

**Comment by FichteFoll** [comment]
Don't forget to push a new tag with the changes.

**Comment by hendrikelsner** [comment]
thank you for the reminder. i pushed a new tag.

**Pull request merged**
