### PR TITLE
Add Wallaby.js plugin

### PR DESCRIPTION
**Pull request by ArtemGovorov**
The product - http://wallabyjs.com/
Sublime Text package - https://www.youtube.com/watch?v=xng_ymsnJks

Thank you!

### CODE REVIEW

**Comment by ArtemGovorov** [comment]
@FichteFoll Thanks! When to expect the package to appear in the list of `Install Package` command? I currently don't see it there.

**Comment by ArtemGovorov** [comment]
@FichteFoll What's interesting, I can see the package here https://packagecontrol.io/packages/Wallaby, but not in the list of `Install Package` command.

**Comment by ArtemGovorov** [comment]
@FichteFoll Sorry, the issue is resolved, I can see the package now (just had dev version of the plugin installed, so it wasn't showing up in the list).

**Comment by FichteFoll** [comment]
Yes, Package Control doesn't offer installation when the package already exists locally.

By the way, you should add a readme key to your json file.

**Comment by ArtemGovorov** [comment]
Thanks, added the readme file reference.

**Pull request merged**
