### PR TITLE
Add python 2to3 converter

### PR DESCRIPTION
**Pull request by jsn5**
Made a plugin to convert python code from version 2 to 3 on the go.

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Can you please add a single package per PR?

**Comment by jsn5** [comment]
@AlexKvazos my bad, 2nd one got added by mistake, changed it.

**Comment by FichteFoll** [comment]
You shouldn't wait for the process to finish if you don't actually need to do anything with it. It will just make the UI unresponsive.

Besides, your method of running `2to3.py` will fail, because ST stores packages in archived `.sublime-package` files, which aren't accessible by default. It also depends on `python` being installed on the system and on PATH, which is not the default for Windows.

An easier way would be to just import `lib2to3` directly and call `lib2to3.main.main` directly. It would require ST3 to be used, but basically nobody uses ST2 anyway.

**Comment by jsn5** [comment]
@FichteFoll  I tried importing `lib2to3.main` and call `main` directly, but gives the error `NotADirectoryError: [Errno 20] Not a directory: '/opt/sublime_text/python3.3.zip/lib2to3/Grammar.txt'`, I am using ST3.

**Comment by FichteFoll** [comment]
Oh, I see. That's unfortunate but not really something that we can fix.

Anyway, you can also execute 2to3 from the command line, if Python is installed on the system, using `python -m lib2to3`, so you don't need your bundled script (which has a shebang line).

**Pull request closed without merging**
