### PR TITLE
Added Mp3Player to m.json

### PR DESCRIPTION
**Pull request by RachitKansal**

### CODE REVIEW

**Comment by FichteFoll** [comment]
There does not appear to be a reason for `.no-sublime-package`. Please remove it.

**Comment by FichteFoll** [comment]
@RachitKansal ping

**Comment by RachitKansal** [comment]
@FichteFoll  I'm sorry, was busy with exams going on...
I have remove .no-sublime-package

**Comment by FichteFoll** [comment]
Don't forget to push a new tag for the release.

**Pull request merged**
