### PR TITLE
add Diagram plugin

### PR DESCRIPTION
**Pull request by jvantuyl**
This package generates diagrams from excerpts of source code. This package was removed a few years ago because it didn't make the move to tag-based releases.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please see https://github.com/wbond/package_control_channel/pull/6946.

**Comment by FichteFoll** [comment]
I assume the fallback for `DiagramEx.sublime-syntax` is `diagram.tmLanguage`. I also assume this syntax is not the primary functionality of this package and it functions reasonably fine without it, especially considering that the readme explicitly claims support for ST 2 and 3.

**Comment by bar4mi** [comment]
This package has a problem with finding its location. I installed it using Package Controller, but I can't use its example and syntax. I found that ST 3 on macOSX has wrong location definition. The Package Controller installed this package to ${packages}/Diagram, but the package defines its location to ${pacakges}/sublime_diagram_plugin in Main.sublime-menu. Please modify the location to use it correctly.

**Comment by FichteFoll** [comment]
@bar4mi you should open this as an issue directly on the package's repository.

**Pull request merged**
