### PR TITLE
Google Chrome JavaScript API Auto-complete package added

### PR DESCRIPTION
**Pull request by ismnoiet**
Offer Google Chrome JavaScript API auto-complete.

### CODE REVIEW

**Comment by FichteFoll** [comment]
This repository does not offer any file that interfaces as a Sublime Text resource.

**Comment by ismnoiet** [comment]
You are right @FichteFoll  i've tried to contact @Kronuz to give me more details about [SublimeCodeIntel](https://github.com/Kronuz/SublimeCodeIntel) plugin  because i really want to help with it, But apparently  he is not responding, i hope he is doing good.
The reason why i want to push it to [package control](packagecontrol.io) is that there is a lot of developers out there who are looking to see it added to sublime text tool box.

**Comment by FichteFoll** [comment]
I do not agree with adding something to Package Control that doesn't use its architechture at all. You'll need to think of a different way to promote your sublimecodeintel addition or add plugin code to automate the process.

**Comment by ismnoiet** [comment]
@FichteFoll  you're right i'm thinking about another way to include it, anyway thank you for your time :+1:

**Pull request closed without merging**
