### PR TITLE
Update l.json

### PR DESCRIPTION
**Pull request by JohhannasReyn**
Add Lensort package

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...
    Unique, I haven't found anything that sorts lines by length, which is why I wrote it.
    There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
[SortBy](https://packagecontrol.io/packages/SortBy) can "Sort by the length of lines". I'm not against a package that only does sorting by length though, I kind of like that focus actually. 

- You still need to tag a release (e.g. 1.0.0), that's also why the tests fail.
- Your preferences menu still has separate entries for User and Default settings... that went out of vogue ages ago ;) Use the `edit_settings` command there just like you do in sublime-commands.
- Since you ship with example key bindings, it would be a good idea to include keybindings in the preferences menu, and in the command palette.
- In my experience, users don't really like update messages unless they mention something important. If a user just installed your package, a 1.0.0 message might do a lot other than confirmed it worked (which package control also does).
- There should not be a `package-metadata.json` file in your repo. The metadata is in this entry here in package control.

**Comment by JohhannasReyn** [comment]
I've made the corrections you have listed; I believe it's ready to be reviewed again. Thank you.

**Comment by braver** [comment]
@JohhannasReyn please tag a release with your latest work.

**Comment by JohhannasReyn** [comment]
> @JohhannasReyn please tag a release with your latest work.

I believe I completed this already, no?

**Comment by braver** [comment]
Looks like!

**Pull request merged**
