### PR TITLE
Add PythonEnv to package control channel

### PR DESCRIPTION
**Pull request by kershingf**

### CODE REVIEW

**Comment by kershingf** [comment]
What I need to do now?

**Comment by FichteFoll** [comment]
If your target audience does not speak a particular language, please formulate your readme in English so that everyone can understand it, including myself for the purpose of this review.

**Comment by FichteFoll** [comment]
If you're not willing to provide an english readme, please do at least explain briefly to me what the package does and what the platform mentions mean regarding compatibility.

**Comment by FichteFoll** [comment]
@kershingf ping

**Pull request closed without merging**
