### PR TITLE
add AdonisJs

### PR DESCRIPTION
**Pull request by ctf0**
Please provide the following information:

 - Link to your code repository: https://github.com/ctf0/adonis-sublime
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/ctf0/adonis-sublime/releases

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need a `.no-sublime-package` file in your package. Please remove it.

**Comment by ctf0** [comment]
i kept is so its easier for anyone to edit/add any snippets, but sure np

**Comment by FichteFoll** [comment]
Editing and adding snippets will actually be easier if the package is archived, because otherwise all changes will get deleted on a package update.

**Comment by FichteFoll** [comment]
Please also push a new tag with the latest commit.

**Comment by ctf0** [comment]
done

**Pull request merged**
