### PR TITLE
Added url-utils package.

### PR DESCRIPTION
**Pull request by ulasozguler**
- Link to my code repository: https://github.com/ulasozguler/sublime-url-utils
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/ulasozguler/sublime-url-utils/tags

### CODE REVIEW

**Comment by math2001** [comment]
Since all your keymaps are the same, you can just create one with no platform specified: `Default.sublime-keymap`

**Comment by ulasozguler** [comment]
@math2001 I didn't realize that was possible. Updated my code. Thanks!

**Comment by vovkkk** [comment]
Generally speaking you should avoid using <kbd>super</kbd> on Windows because most certainly your choice will conflict with global shortcuts (so this is the same as not provide any default keybindings at all).

For example, <kbd>super+u</kbd> opens Utility manager (accessibility apps), <kbd>super+e</kbd> opens new Explorer window, <kbd>super+d</kbd> shows Desktop (i.e. minimises all windows).

**Comment by ulasozguler** [comment]
I've reassigned them to `ctrl+alt+e` and `ctrl+alt+d` on Windows. @vovkkk 
Thanks for the warning!

**Comment by FichteFoll** [comment]
Your `ReplaceCommand` overrides the default `replace` command. I suggest using this class as a mixin and not subclassing `sublime_plugin.TextCommand`.

Also, the control and alt modifier keys are usually equivalent to the AltGr (the right alt key) in Windows and used for special characters. `ctrl+alt+e` inserts the Euro sign (`€`) on a German keyboard, for example.

So, this package is obviously very similar to https://packagecontrol.io/packages/URLEncode (and a few others), but it also provides additional functionality that wouldn't fit either of these packages' scope.

**Comment by ulasozguler** [comment]
I've changed `ReplaceCommand` to `ReplaceCommandBase`, so it doesn't get recognized as a command now.

Shortcuts were fine on my test but I guess my keyboard layout is different.I've updated them to `["ctrl+shift+y", "ctrl+shift+e"]` and `["ctrl+shift+y", "ctrl+shift+d"]`.

**Comment by FichteFoll** [comment]
It will still get picked up as `replace_command_base`, but at least that's not overriding anything anymore. To be fair, a lot of people are using this pattern without realizing how ST picks up plugin subclasses, so I'm not going to force you to do it "the correct way". As long as it doesn't break other stuff (like previously), this should be good enough.

**Pull request merged**
