### PR TITLE
Added new plugin, HoogleSearch

### PR DESCRIPTION
**Pull request by s4wny**
[Hoogle](https://www.haskell.org/hoogle/) integrated into sublime text.

### CODE REVIEW

**Comment by wbond** [comment]
From looking at your python, I don't think this will work in ST2, so you should update the `sublime_text` selector to `>=3000`.

Also, you should add some information to your readme about how to use the package.

**Comment by FichteFoll** [comment]
You should take a look at `urllib.parse.quote_plus`.

**Comment by s4wny** [comment]
Thx for the input. I have updated the readme and added `urllib.parse.quote_plus` now.

https://github.com/s4wny/HoogleSearch

**Comment by s4wny** [comment]
Squashed commits into one.

**Comment by joneshf** [comment]
This is everything I need in life! Thanks!

**Comment by s4wny** [comment]
@joneshf Glad to hear :)

**Pull request merged**
