### PR TITLE
Add reference to Edge package

### PR DESCRIPTION
**Pull request by thetutlage**
Please provide the following information:

 - Link to your code repository: https://github.com/poppinss/edge-sublime-syntax
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/poppinss/edge-sublime-syntax/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4)) Ok!
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7)) Ok!

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for edge-sublime-syntax #####################

### Repository checks ###

No failures

No warnings

### Package checks ###

No failures

Reporting 1 warnings:
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: edge.sublime-syntax

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by thetutlage** [comment]
Referencing the greater version. Sorry new to sublime eco-system

**Comment by thetutlage** [comment]
Can anyone please look into it?

**Comment by thetutlage** [comment]
??

**Comment by thetutlage** [comment]
Can anyone really look into it, otherwise I have to close the PR and simply don't rely on sublime package manager

**Comment by wbond** [comment]
This is completely run by people volunteering their time. Please be patient!

**Comment by thetutlage** [comment]
Patently closing

**Pull request closed without merging**
