### PR TITLE
Limit AngularInject to Sublime Text 2

### PR DESCRIPTION
**Pull request by ayamflow**
I developed this package before ST3 came out, not planning to update it.

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for AngularInject ###########################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 2 failures:
- The package contains 1 Python file(s), but none of them are in the package root and no build system is specified
- '.pyc' file is redundant because its corresponding .py file exists
    File: AngularInject/AngularInject.pyc

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

So yeah, unfortunatley because you never pushed a new tag after https://github.com/ayamflow/AngularInject/commit/0a9dab163f93668ce92abb41b33d2ca4d7ad37af, nobody who installed this package could actually use it.

**Comment by FichteFoll** [comment]
@ayamflow ping

**Comment by ayamflow** [comment]
I added a [release](https://github.com/ayamflow/AngularInject/releases/tag/1.1.3), is that better?

**Comment by FichteFoll** [comment]
Yes, the package will at least work now. The pyc file is still redundant, but since the package is already on the list I'm not going to block it any further.

**Comment by ayamflow** [comment]
Thanks 👍

**Pull request merged**
