### PR TITLE
added Sprak Syntax & Completions for scripts

### PR DESCRIPTION
**Pull request by Eforen**
added Sprak Syntax & Completions for scripts from the game else Heart.Break() which has scripting in it and this gives users of Sublime the ability to handle scripts copy and pasted from or too the game.

Signed-off-by: Ariel Lothlorien <git@arielkauai.com>

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by Eforen** [comment]
Oh ok will do

**Comment by FichteFoll** [comment]
Okay, good. However, there is another problem that I just noticed: You have a dot in your package name. This will prevent any Python plugins from loading (on ST3) and even thoug you don't have any currently, we don't accept any new packages with dots.

**Comment by Eforen** [comment]
Oh I was unaware that was a problem I have yanked the dot.

**Comment by Eforen** [comment]
I made a change to my package and taged it v1.0.1 do I need to tell packagecontrol.io somehow that there is a new version? if not how long does the automated build process take?

**Comment by FichteFoll** [comment]
No, just pushing the tag is enough. It may take up to 1 hour though.

**Comment by Eforen** [comment]
Oh ok cool thx it is updated now

**Pull request merged**
