### PR TITLE
Update Maude syntax

### PR DESCRIPTION
**Pull request by ngraymon**
Small updates to the previous Maude syntax package
the primary one being that comments can now be toggled
using the default shortcut

### CODE REVIEW

**Comment by ngraymon** [comment]
My aim is to slowly flesh out the repository, borrowing from this [repo](https://github.com/adamlazz/language-maude) for atom; while following the documentation for [scope naming](https://www.sublimetext.com/docs/scope_naming.html) and [syntax](https://www.sublimetext.com/docs/syntax.html). Let me know if I need to provide any additional information, thanks!

**Comment by braver** [comment]
You seem to be taking over this package. Does the original author agree?

**Comment by ngraymon** [comment]
> 
> 
> You seem to be taking over this package. Does the original author agree?

I do not know. I was not able to find contact information otherwise I would have reached out. I've added an issue to the original repository as an attempt at contacting them.

**Comment by braver** [comment]
Yes, an issue or Pull Request on the original package’s repo would be the first thing to attempt. If that doesn’t work out, and/or @jpsikorra doesn’t want to maintain his package anymore, we can always revisit this PR.

**Comment by ngraymon** [comment]
> 
> 
> Yes, an issue or Pull Request on the original package’s repo would be the first thing to attempt. If that doesn’t work out, and/or @jpsikorra doesn’t want to maintain his package anymore, we can always revisit this PR.

Okay, thanks for the information!

**Pull request closed without merging**
