### PR TITLE
Added support for Carbon Syntax Highlighting

### PR DESCRIPTION
**Pull request by RohanVashisht1234**
@packagecontrol-bot

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a syntax highlighter for the carbon programming language

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Please check off all the items in the list, it’s there for a reason ;) 

https://github.com/wbond/package_control_channel/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by RohanVashisht1234** [comment]
Ok, I'm adding them, and also making a new repo for this.

**Comment by RohanVashisht1234** [comment]
Only adding the carbon.tmLanguage.json will be enough? or we need a package.json as well?

**Comment by RohanVashisht1234** [comment]
@packagecontrol-bot

**Comment by RohanVashisht1234** [comment]
@packagecontrol-bot please check this PR for inclusion

**Comment by RohanVashisht1234** [comment]
😂😂😂😂 I don't think package control bot works this way, How to use package control bot?

**Comment by RohanVashisht1234** [comment]
Um, can you please tell me why is this happening? and how to fix it?

**Comment by RohanVashisht1234** [comment]
Is the error fixed now?

**Comment by braver** [comment]
Yeah, uh, where to start 😅 Don't take this the wrong way, but there is some work left to do for this to work.

> I have tagged a release with a [semver](https://semver.org/) version number.

You did not, or forgot to push a [tag](https://github.com/RohanVashisht1234/sublime_text_carbon_syntax_highlighter/tags).

That's the main issue, without a tag, package control can't download your package, and not test it, resulting in the error you're seeing here.

> If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").

If your package support the [Carbon Language](https://github.com/carbon-language) (I'm guessing that's the one), please just call it "Carbon Language". A language support package in Sublime Text unlocks not just "colors" but also goto definition, symbol lists, folding, completion, etc. etc. It's not a "code colorizer". That's why we have that instruction in there: just name your package after the language and don't try to put all its features in the name.

Futhermore, don't put a package.json in your package. Your package description in this PR right here, nothing else is needed. 

Finally, your package contains various JSON files but no syntax files that Sublime Text understands. The tmLanguage json could be converted into a tmLanguage file probably. But instead of going down that (admittedly quite ancient) route, why not get with the times and write your syntax using [Sublime Text's sublime-syntax](https://www.sublimetext.com/docs/syntax.html) format?

It almost looks like you're trying to create a VS Code package here? Or maybe converting from one?

**Comment by RohanVashisht1234** [comment]
Yes, you are correct I was trying to convert a vscode package to sublime text package. My package is just a code colorizer "a syntax highligher" it doesn't provide any lsp/goes to definitions.
Yes, and I'll convert the .json to sublime-syntax

**Comment by braver** [comment]
> it doesn't provide any lsp/goes to definitions

Yes it does actually. Sublime Text uses your syntax to provide those features. Not via an LSP, but still. That’s my point, in ST “code colorizer” really is a misnomer.

**Comment by RohanVashisht1234** [comment]
yes, and also, is there a way to test this locally at my computer?
Also, can you please provide me with a demo kind of repo? for sublime-syntax?

**Comment by braver** [comment]
Sure, anything you place in the Packages directory are immediately loaded and hot-reloaded, so you can easily develop that way.

Relevant documentation, including examples:
- https://www.sublimetext.com/docs/packages.html
- https://www.sublimetext.com/docs/syntax.html
- https://www.sublimetext.com/docs/scope_naming.html

Help can be got at the [forum](https://forum.sublimetext.com) and [Discord channel](https://discord.gg/D43Pecu).

**Comment by RohanVashisht1234** [comment]
Ok brave, I have made some changes, please tell me if this needs any corrections.

**Comment by RohanVashisht1234** [comment]
@packagecontrol-bot

**Comment by RohanVashisht1234** [comment]
Idk why @packagecontrol-bot is giving these errors.

**Comment by braver** [comment]
Still this:

> You did not, or forgot to push a [tag](https://github.com/RohanVashisht1234/sublime_text_carbon_syntax_highlighter/tags).

**Comment by RohanVashisht1234** [comment]
@packagecontrol-bot

**Comment by RohanVashisht1234** [comment]
I have made a release 1.0.0

**Comment by RohanVashisht1234** [comment]
@packagecontrol-bot

**Comment by RohanVashisht1234** [comment]
Yes, it worked.

**Comment by RohanVashisht1234** [comment]
Braver, once you are done with the checks, from my side, I think all the changes have been made and this pr is ready to be merged.

**Comment by RohanVashisht1234** [comment]
And if you find any other issues, please let me know

**Comment by braver** [comment]
Good job, LGTM! 👍🏻

**Comment by RohanVashisht1234** [comment]
Thanks alot 😊

**Pull request merged**
