### PR TITLE
publishing package

### PR DESCRIPTION
**Pull request by JeisonJHA**
A new theme language for Delphi developers.

### CODE REVIEW

**Comment by luizfnunesmarques** [comment]
Thanks @JeisonJHA , very helpfull

best regards

**Comment by luizfnunesmarques** [comment]
Will be very helpfull, @alefragnani, @jcfausto

**Comment by FichteFoll** [comment]
Why restrict the package to Windows? Syntax highlighting works for all platforms.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by JeisonJHA** [comment]
Adjustments made.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by JeisonJHA** [comment]
Fixed

**Pull request merged**
