### PR TITLE
Add FlowType package.

### PR DESCRIPTION
**Pull request by Pegase745**

### CODE REVIEW

**Comment by Pegase745** [comment]
Anyone for this error please ? I changed the binding, but the error still appears cc @wbond @FichteFoll

**Comment by wbond** [comment]
`super` and `command` are the same thing. I don't think it is necessary to correct that warning, it is just telling you that in some situations your key binding won't work since the default key bindings include the same key binding, but in a more specific situation where a context is added.

Also, your PR seems to add the package twice.

**Comment by Pegase745** [comment]
@wbond thanks, it seems fixed now. can it be merged ?

**Comment by FichteFoll** [comment]
FYI, your error message in `plugin_loaded` will never be seen on ST2 because it will already fail on the imports. Not considering that `plugin_loaded` isn't called on ST2 to begin with.

Another aside, a "warning" is simply a prompt for potential action, i.e. something a human reviewer should look at.

**Comment by Pegase745** [comment]
Thanks for the info on ST2.

**Pull request merged**
