### PR TITLE
Add DoxyDoxygen to the official packages list

### PR DESCRIPTION
**Pull request by 20Tauri**
This package simplifies writing comments.

It have a good language comprehension.
May probably replace DoxyDoc package (except for the license), because even if DoxyDoxygen is not dedicated to C++ it provide a better support that it...

DoxyDoxygen have a different approch than the great DocBlockR. Due to his better knowledge of language, DoxyDoxygen may guess type without any configuration. It also provide a lot of long time requested functionaly that cannot be easily implentated to DocBlockR (like comments reparsing)

Here an example of generated documentation:
```JavaScript
/**
 * { description }
 *
 * @param      {number}  errorCode  { description }
 *
 * @return     {string}  { description_of_the_return_value }
 */
function error2msg(errorCode) {
    if (errorCode == 404) {
        return "page not found";
    }

    return "...";
}
```

Please visit the official [DoxyDoxygen page](http://20tauri.free.fr/DoxyDoxygen) for further informations

Thanks you for your time,
Thanks you for your review.

### CODE REVIEW

**Comment by FichteFoll** [comment]
1. For security reasons you must use the https protocol for hosting your own .json repository.
2. `previous_names` is redundant and could possibly confuse PC because it contains the same name as it actually has. Please remove.
3. it's better to just not include the `donate` key than setting it to `""`
4. The `details` url only supports links to github or bitbucket repos and is just there to let the crawler auto-fill the remaining keys. You can either change this to `https://github.com/20Tauri/DoxyDoxygen` and remove `readme`, `issues`, `homepage` (if you add the homepage to your package's "url", next to its description), `description` (fetched from repo description) or just remove the details key.
5. `readme` has to refer to the raw readme file.
6. `date` fomatting is invalid. It must be `YYYY-MM-DD HH:MM:SS` and should be in UTC.

Install the [ChannelRepositoryTools](https://packagecontrol.io/packages/ChannelRepositoryTools) package and run the tests on your .json file until they pass.

Because your package is not open source I would not want to replace the DoxyDoc package.

**Comment by 20Tauri** [comment]
Thanks you for this great review.

Repository file has been fixed and tests passed with your patch.

JSON Repository file is now hosted on github (https)... As github certificates seem to be checked (to prevent man in the middle attack), I will also switch packages on it... Don't seem to be blocking for Package_Control, but it's better for final users.

Regards,

**Comment by 20Tauri** [comment]
Change to secure all URLs

**Comment by FichteFoll** [comment]
Alright, this looks good.

Before I merge this however, you might want to check out [github releases](https://github.com/blog/1547-release-your-software) and the ability to upload arbitrary binary files.

**Comment by 20Tauri** [comment]
Thank you for this hint !
It's a more logical way to use GitHub (and using the Git Api is easy to maintain).

The only "issue" is that  Asset cannot have the same download name nor been hidden.
So "Sublime-Packages" have to been renamed to be used manually...

Due to this restriction, I've also slighty modified the repository ("url" field)

Thanks again for all

**Pull request merged**
