### PR TITLE
add Tpl package

### PR DESCRIPTION
**Pull request by fewspider**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please remove:

- Your change in `channel.json`
- The `packages.json` file in your repo
- The branch key
- The author key
- Optionally, the platform key

Also, please don't override default key bindings, such as `ctrl+t`.

**Comment by fewspider** [comment]
@FichteFoll Thanks for all your patience.

* I change the default key binding `ctrl+t`  to `ctrl + alt + t`.
* Remove packages.json file in my repo.
* Remove the branch,author and platform key.

Is it anything OK now?Sorry for my careless making mistake.

**Comment by FichteFoll** [comment]
All good now.

**Comment by fewspider** [comment]
@FichteFoll thankyou:)

**Pull request merged**
