### PR TITLE
Adding V (vlang) syntax highlighting package

### PR DESCRIPTION
**Pull request by elliotchance**

### CODE REVIEW

**Comment by elliotchance** [comment]
@wbond it's been 7 days now - is there any way I can get this reviewed faster?

**Comment by braver** [comment]
I'll send you a Paypal link, send me some money and we can maybe work something out 😉 

Not sure a single character is the best way to get found but 🤷🏻 
Have you tried converting your syntax to the new sublime-syntax (yaml) format? That way you can also get rid of the JSON.

**Comment by elliotchance** [comment]
@braver I'm actually pushing a fork so that it doesn't have to manually be installed. If it works, I'm planning (when I get around to it) rewriting the syntax to sublime format, but also adding more feature like building and debugging - if possible.

Do I need to put in a license now to proceed?

I know "V" is short but that that is the name of the language... https://vlang.io/

**Comment by braver** [comment]
> Do I need to put in a license now to proceed?

No, it's recommended but not required. Let's ship it!

**Pull request merged**
