### PR TITLE
Added TeamOpz plugin to list

### PR DESCRIPTION
**Pull request by mstrlaw**
Endpoint is not final for now but will update when possible.

### CODE REVIEW

**Comment by FichteFoll** [comment]
By "endpoint is not final" you mean the url 404s?

**Comment by FichteFoll** [comment]
I see. That's not really relevant to the addition of the package however.

What *is* relevant is that the url you specified in the PR, https://bitbucket.org/mstrlaw/teamopz, doesn't exist.

**Comment by mstrlaw** [comment]
Whops. My bad. Just fixed that.

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by mstrlaw** [comment]
All right added version tag and pushed it. Think it went through.

**Comment by FichteFoll** [comment]
I'm afraid it didn't. It has to be visible here: https://bitbucket.org/mstrlaw/teamopz-sublime#tags

**Comment by FichteFoll** [comment]
@mstrlaw ping

**Comment by mstrlaw** [comment]
@FitcheFoll Still have mods to implement to the package which I haven't
been able to do (lack of time).

On Wed, Sep 16, 2015 at 4:54 PM, FichteFoll <notifications@github.com>
wrote:

> @mstrlaw <https://github.com/mstrlaw> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/4681#issuecomment-140784670>
> .
>



-- 

*Law*

**Pull request closed without merging**
