### PR TITLE
Theme - GaganSoda

### PR DESCRIPTION
**Pull request by gj1118**
Hi, I am adding a new variant of Soda theme - this theme is based on the popular soda theme . has support for icons as well as support for switch panel support (introduced in the latest version of ST build 3101)

Thanks

### CODE REVIEW

**Comment by gj1118** [comment]
Hi, can you please let me know , why the travis CI is not working for this ? I am sorry for being a noob but this is my first submission . 

Thanks 
gagan

**Comment by FichteFoll** [comment]
Good question, I have no idea why Travis-CI is not triggering.

Either way, what are the differences to the original Soda? You don't seem to have updated the screenshots, or do you?

**Comment by gj1118** [comment]
Thanks.. I can see travis has now checked it. Nope, I have not updated the screenshots but I was planning to keep working on it iteratively and incrementally. One of the iterations would be to update the screenshots. right now , it has only updated icons

**Comment by FichteFoll** [comment]
So, how exactly is your theme different now?

**Comment by gj1118** [comment]
Thanks for taking time out for the reply. I have updated the screenshots. The dark theme is considerably different that the default soda dark theme , and the light theme is what I am working on now. 

Thanks

**Pull request merged**
