### PR TITLE
NgAnnotate plugin

### PR DESCRIPTION
**Pull request by kamilkp**
add or update annotation to **any** function in for AngularJS.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by kamilkp** [comment]
Done: https://github.com/kamilkp/package_control_channel/tree/v1.0.0

**Comment by FichteFoll** [comment]
The tag needs to be pushed to https://github.com/kamilkp/Sublime-Text-NgAnnotate.

**Comment by kamilkp** [comment]
Ok, sorry. Done now.

**Pull request merged**
