### PR TITLE
add ThinkPHP5 and ThinkPHP5.1

### PR DESCRIPTION
**Pull request by yangweijie**

### CODE REVIEW

**Comment by yangweijie** [comment]
please merge

**Comment by FichteFoll** [comment]
Okay, so I here is what I think this is:

Two packages for different versions of *something* that generate a bunch of snippets each, using Php. And it's all in Chinese. This is basically unreviewable, so I have no choice but to trust in your good faith of not doing more than that.

Your `dependencies.json` files are invalid because there is no `php` dependency. Package Control dependencies are a separate concept and unless you know what they are, you shouldn't be using them.

**Comment by jfcherng** [comment]
`tp5/public/index.php` requires a missing file: `tp5/thinkphp/base.php`

```
[USER@USER-NB SublimeThinkPHP5_1](master)$ php "tp5/public/index.php" "index/index/build_completion"
PHP Warning:  require(C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thinkphp/base.php): failed to open
stream: No such file or directory in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php on line 18

Warning: require(C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thinkphp/base.php): failed to open strea
m: No such file or directory in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php on line 18
PHP Warning:  require(C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thinkphp/base.php): failed to open
stream: No such file or directory in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php on line 18

Warning: require(C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thinkphp/base.php): failed to open strea
m: No such file or directory in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php on line 18
PHP Fatal error:  require(): Failed opening required 'C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thi
nkphp/base.php' (include_path='.;C:\php\pear') in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php
on line 18

Fatal error: require(): Failed opening required 'C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public/../thinkphp
/base.php' (include_path='.;C:\php\pear') in C:\Program Files\Sublime Text 3\Data\Packages\SublimeThinkPHP5_1\tp5\public\index.php on li
ne 18
```

**Comment by FichteFoll** [comment]
@yangweijie ping

**Pull request closed without merging**
