### PR TITLE
Revert "remove retina theme"

### PR DESCRIPTION
**Pull request by braver**
This reverts commit ca25f8e6b25d3c60c7c706f7ae590ca95c0baac7. Because some people can't get used to new things. 🤷‍♂️

### CODE REVIEW

**Comment by braver** [comment]
@FichteFoll the theme is still in PC but the removal does stop it from picking up updates. I'd like to push a bugfix and stop people from badgering me about it.

**Comment by FichteFoll** [comment]
Sorry for slacking on this a bit, but I prefer to avoid playing favorites unless I really have to.

Anyway, as we both know, this has been reverted in https://github.com/wbond/package_control_channel/commit/ac9854889387ce92b15f5d6f4e8e3735df55ce23 already, so I'm closing this.

**Comment by braver** [comment]
Yeah I guess Will also needed to deflect some "feedback"

**Comment by wbond** [comment]
Haha, just giving the people what the want, in the simplest way possible. "Go install Theme - Retina".

**Pull request closed without merging**
