### PR TITLE
Add AppendSemiColon package

### PR DESCRIPTION
**Pull request by MauriceZ**
This is a package that adds a semi colon at the end of the cursor's statement with a keyboard shortcut and can also automatically pass to a new line. See [here](https://github.com/MauriceZ/AppendSemiColon) for more info.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Differences to:

https://packagecontrol.io/packages/Auto%20Semi-Colon
https://packagecontrol.io/packages/Semicolon

**Comment by MauriceZ** [comment]
Differences with Auto Semi-Colon:
+ The semi colon is placed when you want it to be placed. Your cursor doesn't have to be within a parentheses to add a semicolon at the end of the line.
+ Adds the macro to automatically append a semi colon and pass to a new line

Differences with Semicolon:
+ Adds the macro to automatically append a semi colon and pass to a new line
+ Different more intuitive shortcut IMO

Check out the readme with examples [here](https://github.com/MauriceZ/AppendSemiColon)

**Comment by FichteFoll** [comment]
Alright.

How about making this a bit smarter? e.g. don't insert when there already is a semicolon, and add before comments (by utilizing `view.match_selector(p, "comment")` and `view.extract_scope(p)`).

**Comment by MauriceZ** [comment]
Agreed to not insert when there is already one.

What do you mean when you say to add a semicolon before comments? When is that necessary?

**Comment by FichteFoll** [comment]
When you have a (line) comment in a line and add code before that comment.
```
// this is a comment
code.does_stuff("maybe|") // press ctrl+semicolon
code.does_stuff("maybe|"); // press ctrl+semicolon // get this
```

**Comment by MauriceZ** [comment]
Good idea, I'll implement this within the next few days. Thanks for the ideas

**Pull request merged**
