### PR TITLE
Added Sk-ST3 Package

### PR DESCRIPTION
**Pull request by AyhamAl-Ali**
Hello,

My package is new to Sublime Text 3 package control and I have only seen one package that is related to `Skript Language` Support but it's completely different from my package, as my package has it's own `Syntax Highlighting` and `Skript Language` Support.

If you need any more info please tell me :)

Thanks.

### CODE REVIEW

**Comment by AyhamAl-Ali** [comment]
I need help by a human please :smile: 
What should I do to make my regex code formed?

Thanks.

**Comment by AyhamAl-Ali** [comment]
Finally :)

**Comment by Thom1729** [comment]
> I have only seen one package that is related to `Skript Language` Support but it's completely different from my package, as my package has it's own `Syntax Highlighting` and `Skript Language` Support.

Could you explain a bit more? Would it be possible to add new functionality to the existing package rather than creating a new one?

**Comment by AyhamAl-Ali** [comment]
Actually I remember that there was a Package related to `Skript Language` uploaded to Packge Control but it seems to be removed or something? I don't know to be honest but I just remember that there was a one. However, my package basically Supports `Skript Language (a local programming language made with Java for Minecraft users)` with a few custom Syntax Highlighting. 

So, I think there is nothing related to `Skript` on the Package Control Database right now so I think we are good to go?

Thanks.

**Comment by Thom1729** [comment]
It looks like the old [Skript](https://packagecontrol.io/packages/Skript) package is defunct. I've emailed the author to confirm.

It's generally not necessary to have “ST3” or the like in a package name, because all of these packages are Sublime packages. Depending on the response to my email, the “Skript” name might be available; or “Minecraft Skript” might work well.

**Comment by AyhamAl-Ali** [comment]
Yes the old `Skript` package was the one I remember, however my package is different because it has its own highlighting and the keywords. 

Just wondering, If you merge the Packages will I still be the author of this package?
Also, the name `Skript` and `Minecraft Skript` are okay.

**Comment by Thom1729** [comment]
The author of the original replied. He removed Skript deliberately and is not interested in maintaining it. This PR can be merged with whichever name you prefer. If you go with “Skript”, then replace the entire existing channel entry.

**Comment by AyhamAl-Ali** [comment]
Okay I will change it to `Skript`.

**Comment by AyhamAl-Ali** [comment]
Hey again, 

I'm sorry but I only changed the name in the Package Control Market to avoid changing LOTS of stuff in the links and code itself. Also, many people know this as Sk-ST3 and it has been made for this name so I would ask you gently to Accept changing only the Main name in the Market and keep the other links with the old name.

Thanks.

**Comment by AyhamAl-Ali** [comment]
Sorry to re-open this but I've released a new update v2.3 and it didn't get updated on Package Control! Any help?

Thanks.

**Pull request merged**
