### PR TITLE
Add DotENV syntax highlighter

### PR DESCRIPTION
**Pull request by zaynali53**
https://github.com/zaynali53/DotENV

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please see https://github.com/wbond/package_control_channel/pull/4787 for why such a package isn't listed yet (and for what you should do add to end that).

**Comment by zaynali53** [comment]
Yeah got it @FichteFoll :)

**Comment by zaynali53** [comment]
@FichteFoll I've updated the syntax with string interpolation, keyword and escape sequences.

**Comment by zaynali53** [comment]
test

**Comment by zaynali53** [comment]
Here is the preview. Using my Zeus color scheme
capture

**Comment by FichteFoll** [comment]
Remember that you have to push a new tag to release the latest changes.

**Comment by zaynali53** [comment]
@FichteFoll Yes sure. Thanks :)

**Pull request merged**
