### PR TITLE
add NoDialogs

### PR DESCRIPTION
**Pull request by maximsmol**

### CODE REVIEW

**Comment by wbond** [comment]
You haven't created any [semver](http://semver.org) tags yet, so no one will be able to install the package if I merge it.

**Comment by maximsmol** [comment]
@wbond All fixed now. Thank you for your time.

P.S.
I just figured I would debug the plugin while the request was pending. :P

**Comment by wbond** [comment]
You'll need to update this PR with the new URL to the repo. The GitHub API does not require repository names, so the package will be missing if I merge as-is.

**Comment by maximsmol** [comment]
Fixed that also.

**Pull request merged**
