### PR TITLE
added LiveReloadMake

### PR DESCRIPTION
**Pull request by alessandro-pezzato**
please add my package "LiveReload Make extension for Sublime Text 3 "

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can import a package's plugin code in ST3 via `from LiveReload import LiveReload` (as in `from <packagename> import <modulename>`. That doesn't require you to mess with the path (and maybe doesn't even work if LiveReload is in a .sublime-package archive (I'd need to test that)).

**Comment by alessandro-pezzato** [comment]
Thank you, I've found it in [LiveReload plugin](https://github.com/dz0ny/LiveReload-sublimetext2/blob/devel/LESSPlugin.py). A simple `import LiveReload` is working fine.

**Comment by FichteFoll** [comment]
Ugh, that's totally unnecessary. It's the equivalent of

```py
if int(sublime.version()) < 3000:
    import LiveReload
else:
    from . import LiveReload
```

cc @dz0ny

**Comment by FichteFoll** [comment]
@alessandro-pezzato As a note, your code will likely fail to execute properly if @dz0ny fixes his importing code, since the way he does it currently overrides the internal `sys.modules["LiveReload"]` that is supposed to be the entire package with just the `LiveReload.py` module. Under normal circumstances you would have to use `from LiveReload import LiveReload`. The problem is that the normal code fails here since the overritten LiveReload module does not contain a submedule or attribute named "LiveReload".

Hope this is understandable.

**Comment by alessandro-pezzato** [comment]
This is my first plugin for sublime and I've a little experience with python. So... which is the way? Your snippet isn't working for me (sublimetext 3083), only `import LiveReload` is working.

**Comment by FichteFoll** [comment]
Yes, I noticed that after you mentioned it doesn't work. The reason is that LiveReload uses this method by itself and that interferes with Sublime Text's module management.

I suggest you use 
```py
try:
    import LiveReload
except ImportError:
    from LiveReload import LiveReload
```
to 1) work right now and 2) still work when the issue I mentioned is fixed upstream. Added https://github.com/dz0ny/LiveReload-sublimetext2/pull/111.

**Comment by alessandro-pezzato** [comment]
Ok, just fixed as you suggested, thank you.

**Comment by FichteFoll** [comment]
Ah sorry, I messed up. It should be the other way around since `import LiveReload` will work in any case.

```py
try:
    from LiveReload import LiveReload
except ImportError:
    import LiveReload
```

Merging anyway since it works currently.

**Pull request merged**
