### PR TITLE
add React Templates

### PR DESCRIPTION
**Pull request by individuo7**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Before I merge this I want to mention that your release schema is flawed because it's impossible to release more than one version on a single day. You may want to consider this before I merge, because it's pretty much irreversible (since you're starting with 2015 as major number).

**Comment by individuo7** [comment]
you are right, I fix that adding a number at the end

**Comment by FichteFoll** [comment]
Unfortunately that won't do either because we require you to use semver-like versions, which have exactly three numeric identifiers. You should check it out: http://semver.org.

**Comment by individuo7** [comment]
ok I got it, then I change the version number to v1.0.0

**Pull request merged**
