### PR TITLE
submit formateverything plugin

### PR DESCRIPTION
**Pull request by lzc-alioo**

### CODE REVIEW

**Comment by lzc-alioo** [comment]
I have a dream to format everything and challenge the existing formatting plug-ins that rely on filename suffixes to intelligently resolve and format by recognizing grammar, lexicalization

**Comment by FichteFoll** [comment]
I suggest adding your package to one of the `repository/*.json` files instead of providing your own. This has several advantages. Besides, tags must be semantic versions, which consist of three numeric parts.

**Comment by FichteFoll** [comment]
You **must** note that your package sends the entire code to a remote server in order to format it. People working with sensitive data for their companies definitely would like to know whether their entire code is sent to a remote and we require this to be stated *clearly* in the readme.

Your `format` command seems redundant and colludes the global command namespace. Just do everything in `format_every_thing`.

You seem to parse JSON from the remote endpoint's response but don't list that in the accepted formats header.

**Comment by lzc-alioo** [comment]
@packagecontrol-bot   @FichteFoll thank you very much,

**Comment by lzc-alioo** [comment]
1. added tag for formateverything4sublime
2.Accept the suggestion By @FichteFoll to use repository/*.json

**Comment by FichteFoll** [comment]
Please address this comment as well:

>Your `format` command seems redundant and colludes the global command namespace. Just do everything in `format_every_thing`.

**Comment by FichteFoll** [comment]
@lzc-alioo ping

**Pull request closed without merging**
