### PR TITLE
Added Frequency Package

### PR DESCRIPTION
**Pull request by krishraghuram**
This package adds a command that allows user to count frequency of each line in the current document.

For example, running the command on,

```
foo
foo
foo
bar
bar
```

will open a new scratch file with the content,

```
{
    "bar": 2, 
    "foo": 3
}
```
I'm also planning to add more features in future (sorted output, word frequency, arbitrary separators(for csv/tsv), output format choice between csv/json etc.)

### CODE REVIEW

**Comment by Ultra-Instinct-05** [comment]
Just a heads up. This
https://github.com/krishraghuram/SublimeFrequency/blob/master/SublimeFrequency.py#L47
will work in ST3, but from ST4 onwards, the `JSON.sublime-syntax` is moved to it's own folder in the `Default` repo. It will be `JSON/JSON.sublime-syntax`.

**Comment by Ultra-Instinct-05** [comment]
> Now I haven't tested my extension for ST2. Also, I just recently got to know about the existence of ST4, and haven't tested on that either. I'm thinking of adding support for ST4 later...

Yeah, I meant you don't have to worry now, but it's something to keep in mind.

> insert does not work with newlines...

I see, now. I am not aware how to ignore to achieve that with `insert` so I guess a dummy `insert` command was needed.

**Comment by krishraghuram** [comment]
Hi, do I have to do anything else for this to be approved/merged :)

**Comment by krishraghuram** [comment]
Kind request for someone to take a look at this PR :)

**Comment by krishraghuram** [comment]
@braver would you be able to merge this PR, or let me know what needs change?

**Comment by braver** [comment]
> How can I specify that this is currently only for ST3 (and not ST2 or ST4)

You can simply ignore ST2, nobody uses that and most packages have dropped support for it without updating their package control entry. So just say < 4000 if you don't want to support ST4. I'm pretty sure there is a syntax to say "between 3000 and 400" but can't find an example right now. 

But you're overthinking it. ST4 is almost completely backwards compatible, and since it's not officially out yet you don't really need to think about your support for it. If for some reason your package doesn't work in ST4 you can always do something about it later. So for now just tag a 1.0.0 and set your entry here to "tags: true". A simple package like yours shouldn't have to worry about all this.

I'm not sure why you're including a packages.json file in your repo? It's not needed for local development, and definitely when distributing through package control.

**Comment by krishraghuram** [comment]
> So for now just tag a 1.0.0 and set your entry here to "tags: true". A simple package like yours shouldn't have to worry about all this.

Done :)

> I'm not sure why you're including a packages.json file in your repo? It's not needed for local development, and definitely when distributing through package control.

I made a mistake while reading https://packagecontrol.io/docs/submitting_a_package and added this file. Removed it now.

**Comment by braver** [comment]
Cool, let's ship this thing! ⛵

**Pull request merged**
