### PR TITLE
TamarinAssist - Support for the Tamarin Prover

### PR DESCRIPTION
**Pull request by lordqwerty**
Highlighting support in Tamarin for Keywords, Logic, Functions and your own Facts.
Compatible with all your favourite Sublime Text Colour themes.Tab autocompletion
and Snippets to get theories written quickly. Quickly check and prove your theories
within Sublime.

Tamarin Prover: https://github.com/tamarin-prover/tamarin-prover

Please provide the following information:

 - Link to your code repository: https://github.com/lordqwerty/TamarinAssist
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/lordqwerty/TamarinAssist/releases/tag/0.1.0-alpha

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by lordqwerty** [comment]
* Link to your code repository: https://github.com/lordqwerty/TamarinAssist
* Link to the tags page with at least one semver tag: https://github.com/lordqwerty/TamarinAssist/releases/tag/0.1.0

**Comment by lordqwerty** [comment]
Is there an issue with this PR as to why it might not be accepted?

**Comment by FichteFoll** [comment]
## Report for TamarinAssist ###########################

### Repository checks ###

No failures

No warnings

### Package checks ###

No failures

Reporting 1 warnings:
- '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    File: Syntaxes/spthy.sublime-syntax

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

@lordqwerty, if you were looking at the other pull requests you would have seen that they weren't being accepted etiher.

**Comment by lordqwerty** [comment]
@FichteFoll many thanks for the review.

In regards to the warning would you like to see a '.tmLanguage' file added? The package has been specified to support only Sublime Text 3, therefore I did not think this would be required. 

Please advise.

**Comment by FichteFoll** [comment]
https://github.com/packagecontrol/package_reviewer/wiki/Package-checks#sublime-syntax-support-has-been-added-in-build-3092-

**Pull request merged**
