### PR TITLE
Add Witch Hazel color scheme package

### PR DESCRIPTION
**Pull request by theacodes**
This is a simple package containing a tmTheme color scheme.

### CODE REVIEW

**Comment by Thom1729** [comment]
Why are there Python files? Is this a cross-editor thing?

**Comment by theacodes** [comment]
Yep.

**Comment by Thom1729** [comment]
Sublime will run any `.py` files in the root directory of a package. It would be preferable not to run those files if they're not needed for Sublime. What editors are they for? Do they need to be in the package root? Is there a sensible way to stop them from running outside the appropriate environment?

**Comment by theacodes** [comment]
Interesting. So, this color scheme is also made available as Sphinx/Pygments plugin so it more or less needs a `setup.py` in the root. I can shuffle the rest around if needed, but that one is hard to avoid.

**Comment by Thom1729** [comment]
@theacodes ping

**Comment by theacodes** [comment]
Sorry for the delay, I just haven't had enough time to follow-up. Thanks for your patience.

Your hunch is correct:

```
reloading plugin witchhazel.setup
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/theaflowers/Library/Application Support/Sublime Text 3/Packages/witchhazel/setup.py", line 17, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'
reloading plugin witchhazel.witchhazel
plugins loaded
```

Would it just be better for me to create a separate repo specifically for sublime so it won't choke on all the extra files?

**Comment by Thom1729** [comment]
> Would it just be better for me to create a separate repo specifically for sublime so it won't choke on all the extra files?

That would be ideal.

**Comment by theacodes** [comment]
@Thom1729 I've updated it with a separate repo just for sublime. :) Thank you for your patience and help here.

**Comment by theacodes** [comment]
Thank you!

**Pull request merged**
