### PR TITLE
Add Monkberry templates support.

### PR DESCRIPTION
**Pull request by elfet**

### CODE REVIEW

**Comment by elfet** [comment]
When you can merge it?

**Comment by elfet** [comment]
Ping.

**Comment by elfet** [comment]
Is this project alive?

**Comment by elfet** [comment]
@joneshf ping

**Comment by elfet** [comment]
ping @wbond

**Comment by wbond** [comment]
Sorry, all of the volunteers on the project have a lot of different things going on, so sometimes you'll just have to be patient. You can have users manually add your repository as a Package Control repository until then.

**Pull request merged**
