### PR TITLE
Added LaravelCollective HTML Form Snippets package

### PR DESCRIPTION
**Pull request by PHLAK**
Added LaravelCollective HTML Form Snippets package

### CODE REVIEW

**Comment by FichteFoll** [comment]
Differences to https://packagecontrol.io/packages/Laravel%20Forms%20Bootstrap%20Snippets?

**Comment by PHLAK** [comment]
@FichteFoll This is JUST the form snippets without the Bootstrap wrappings.

**Comment by FichteFoll** [comment]
Thank you for the clarification.

Unfortunately merging another PR has created a merge conflict with your package. Could you please rebase onto the current master branch and solve the conflict?

**Comment by PHLAK** [comment]
@FichteFoll I'm not sure I did that right.  It still says "This branch has conflicts that must be resolved" but I'm not sure what it's referring to.

**Comment by PHLAK** [comment]
@FichteFoll I just scrapped that and cherry picked my commit into the current upstream master.  Should be good now.

**Pull request merged**
