### PR TITLE
MarkdownAssistant , a new snippet provider which provides easy to use snippets for creating and editing markdown files.

### PR DESCRIPTION
**Pull request by code-reaper08**

### CODE REVIEW

**Comment by braver** [comment]
How would you say your package compares to, say, [Git​Hub Markdown Snippets](https://packagecontrol.io/packages/GitHub%20Markdown%20Snippets)?

**Comment by rchl** [comment]
Also one comment on the technical side - you haven't defined `scope` for those so they will trigger in any syntax, not only markdown.

**Comment by code-reaper08** [comment]
> How would you say your package compares to, say, [Git​Hub Markdown Snippets](https://packagecontrol.io/packages/GitHub%20Markdown%20Snippets)?

Hello thanks for your feedback @braver .
I checked out  [Git​Hub Markdown Snippets](https://packagecontrol.io/packages/GitHub%20Markdown%20Snippets).It does the most work tbh but , my package has some more features and snippets ,for example,

+ mailto
+ checklist items
+ mention
+ variety of tables (1X2,1X3,2X1,2X2,2X3,3X1,3X2,3X3), and i am planning to continuously *update* it with more.

And [Git​Hub Markdown Snippets](https://packagecontrol.io/packages/GitHub%20Markdown%20Snippets) is not updated for almost 5 years.

Anyways direct me to do the needed 
THANKS  😄

**Comment by code-reaper08** [comment]
> Also one comment on the technical side - you haven't defined `scope` for those so they will trigger in any syntax, not only markdown.
> 
> And also, in you readme you are advising to change the `auto_complete_selector` setting from default (which is `meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc` currently) to just `source,text` which seem like a pretty bad advice. The defaults are tweaked to not trigger completions in places they shouldn't be triggered. Just using `source` can get annoying quickly. You should probably advise to take the default and add:
> 
> `, text.html.markdown`
> 
> to it.

Hey thanks for pointing out @rchl . I am extremely sorry for that. I am a first time contributor and I missed (messed) some things badly.

i will update my snippet files with SCOPE and README with the instructions part as you said.

criticisms from people like you are really helpful 👍

**Comment by braver** [comment]
Alright, maybe we should just add this package alongside existing packages. There are already a bunch of snippet/autocomplete packages for markdown, but I can see how it might be hard to consolidate your approach with one of them.

You need to have a look at how syntax specific settings work though. I don’t think the settings you recommend in the readme are correct; setting the autocomplete selector like that would enable autocomplete _only_ in markdown. Just in general have a good close look at how your package would integrate with all the different things people do with Sublime Text.

**Comment by code-reaper08** [comment]
> Alright, maybe we should just add this package alongside existing packages. There are already a bunch of snippet/autocomplete packages for markdown, but I can see how it might be hard to consolidate your approach with one of them.
> 
> You need to have a look at how syntax specific settings work though. I don’t think the settings you recommend in the readme are correct; setting the autocomplete selector like that would enable autocomplete _only_ in markdown. Just in general have a good close look at how your package would integrate with all the different things people do with Sublime Text.

Hello @braver !
I looked into the issue , and as you said Syntax specific settings works like a charm. Wonder why I didn't use it before 😃.
I included [Markdown.sublime-settings](https://github.com/code-reaper08/MarkdownAssistant/blob/main/Markdown.sublime-settings) in my repo. Hope it'll solve the problem.

I tested this with all settings default and using Syntax specific settings for markdown files. It worked good 💯

Just go through it and let me know ,if there's anything to change !

Have a nice day 👋

**Comment by braver** [comment]
🎉

**Comment by code-reaper08** [comment]
> 🎉

Hey  @braver Thanks for merging it !
Feeling so good to contribute 🏆 .

**Comment by braver** [comment]
Thanks for contributing! 

By the way, I noticed after merging that we could’ve “optimized” the entry by removing the description. Instead you can set the description on the GitHub repo. That way you can also change it without having to create a PR here. Anyway, you can always open a new PR to make that change if you want.

**Comment by code-reaper08** [comment]
> Thanks for contributing!
> 
> By the way, I noticed after merging that we could’ve “optimized” the entry by removing the description. Instead you can set the description on the GitHub repo. That way you can also change it without having to create a PR here. Anyway, you can always open a new PR to make that change if you want.

Hey @braver 
You mean the description here [Here](https://github.com/wbond/package_control_channel/blob/master/repository/m.json) ?

**Comment by braver** [comment]
Yes, you can remove that description. Instead package control will take the one over here: 
Screenshot 2021-02-15 at 19 42 40

**Comment by code-reaper08** [comment]
Sorry if it seems silly 😅
How can I do that without creating a PR ?
If I just edit [this](https://github.com/wbond/package_control_channel/blob/master/repository/m.json#L581) , GitHub prompts me like 
```
You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork code-reaper08/package_control_channel, so you can send a pull request.
```
Please guide me in this 🙏

**Comment by braver** [comment]
Well you can’t ☺️Just make a new PR, that’s fine.

**Comment by code-reaper08** [comment]
> Well you can’t ☺️Just make a new PR, that’s fine.


hey @braver 😃
Deleted the description part [here](https://github.com/wbond/package_control_channel/blob/master/repository/m.json#L581) and created another PR [here](https://github.com/wbond/package_control_channel/pull/8193)

Merge it soon !

Have a nice day ✨✌

**Comment by braver** [comment]
Woop woop 🚀

**Pull request merged**
