### PR TITLE
Add gregschoen/sublimetext-syslog

### PR DESCRIPTION
**Pull request by sammcj**
```
  Ran 5758 tests in 0.319s
  
  OK
```

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

I'll be on vacation starting pretty much now, so I'll merge your package early before you pushed a tag; just so you don't have to wait 2 weeks for me

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by sammcj** [comment]
Ping @gregschoen - can you please tag your package so that I may update this PR to get it added to SPM?

**Comment by gregschoen** [comment]
Tagged a release of v0.0.1 in repo, should be good to go. Let me know if any other changes need to be made.

**Comment by sammcj** [comment]
Thanks Greg, I'll ipdate my PR shortly

**Comment by sammcj** [comment]
Sorry @FichteFoll I did read the docs but missed the bit about the tags!

@gregschoen has started using tags (as it's his plugin) and I've tested and updated my PR (and rebased).

Thanks,

**Pull request merged**
