### PR TITLE
Add Meson language syntax

### PR DESCRIPTION
**Pull request by Salamandar**
This is the language syntax for the Meson Build system.
It's my first ST package, so please feel free to criticize ;)

### CODE REVIEW

**Comment by FichteFoll** [comment]
You aren't actually testing anything in your syntax test file. See https://www.sublimetext.com/docs/3/syntax.html#testing for documentation and https://github.com/sublimehq/Packages for examples on syntax tests.

You'll also need to adjust the version selector to `"sublime_text": ">=3092"`.

**Comment by FichteFoll** [comment]
@Salamandar ping

**Comment by Salamandar** [comment]
Sorry had a lot on my mind lately. Gonna do that today.

**Comment by Salamandar** [comment]
Unit tests are set up, having in mind that the syntax will be a bit simplified this week.

**Pull request merged**
