### PR TITLE
Add Breadcrumbs

### PR DESCRIPTION
**Pull request by qbolec**
https://github.com/qbolec/Breadcrumbs
https://github.com/qbolec/Breadcrumbs/tags
I havent added  `"branch": "master"` as I'm using semver on master.

### CODE REVIEW

**Comment by AlexKvazos** [comment]
screen shot 2017-06-10 at 5 10 59 pm

The package is giving the following errors in Sublime Text 3134. Please address them so we can merge your package.

**Comment by qbolec** [comment]
Do I understand correctly that I have to write my plugin in a common subset of Python 2 and Python 3, to make it work on both Sublime Text 2 and Sublime Text 3?

**Comment by qbolec** [comment]
I've released bugfix, tagged 1.0.1, which seems to work on both Sublime Text 2, and Sublime Text 3 portable.

**Comment by AlexKvazos** [comment]
Works great, thanks!

**Pull request merged**
