### PR TITLE
Add the "Redo" package

### PR DESCRIPTION
**Pull request by ISSOtm**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette. (It's a build system.)
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package adds support for [the Redo build system](https://redo.rtfd.io/), adding a build system and syntax definition.

There are no packages like it in Package Control.

For bonus points, also considered how the review guidelines apply to this package:
https://github.com/wbond/package_control_channel/wiki#reviewing-a-package-addition

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Please use a consistent suffix to your scopes, even in the hidden syntax. e.g. `redo_ouput`.

I think there might be a better way to create your syntax, by simply extending the default bash syntax. Try this:


```yaml
%YAML 1.2
# https://www.sublimetext.com/docs/syntax.html
---
name: Redo
scope: source.redo
version: 2
extends: Packages/ShellScript/Bash.sublime-syntax

file_extensions:
  - do

```

**Comment by braver** [comment]
Please respond to the feedback to continue this PR.

**Comment by ISSOtm** [comment]
> Please use a consistent suffix to your scopes, even in the hidden syntax. e.g. `redo_ouput`.

I've done it that way for consistency with other syntaxes, like the built-in `Makefile`, or e.g. `Rust Enhanced`. Not sure which way should be privileged.

> I think there might be a better way to create your syntax, by simply extending the default bash syntax. Try this:
> 
> [...]
> 
> This might mean you'd have to bump your requirement to something more recent though, which should not be a problem anyway. I would suggest going with 4142 as a minimum (that's already more than a year old).

Okay, fair enough. I can't perform the modification right now, but I will. [Documentation indicates that the requirement is 4075](https://www.sublimetext.com/docs/syntax.html#inheritance), FWIW.

**Comment by braver** [comment]
> I can't perform the modification right now, but I will

Alright, just report back when you're ready and we can continue this PR. I will close it in the mean time.

**Pull request closed without merging**
