### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by idleberg**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
"Converter" is a very *general purpose* name, something that doesn't really fit what your package actually does (JSON, CSON, XML). I know this is hard because I have been there myself, but please try to find a different less general but still fitting name.

**Comment by idleberg** [comment]
With names like DataConverter and SerializedDataConverter already taken, there aren't many options left. Would you agree to something like ConvertThisToThat?

**Comment by FichteFoll** [comment]
That's true. How about "JSON_CSON_XML_Converter"? Afaik your package is the only one to support CSON and XML, so that would make it stand out.

**Comment by FichteFoll** [comment]
Actually, it's still the only one that supports CSON. Either way, this PR is conflicting with the master branch currently.

**Comment by idleberg** [comment]
I'll stick with the old name

**Pull request closed without merging**
