### PR TITLE
add MoveMore package

### PR DESCRIPTION
**Pull request by sflip**
This package makes it possible to move the cursor up or down more than one line at a time. As described in the readme file, this is a missing but wanted feature.

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/LineJumper

**Comment by sflip** [comment]
Oh,  I did not find that! 

However, I see one difference: With my plugin you can use the same key binding to extend the selection if there is one and do not create one if there isn't. This is the desired behaviour for vim (Vintage/Vintageous) users like me.

**Comment by FichteFoll** [comment]
Easy:
```js
[
    {
        "keys": ["alt+up"],
        "command": "line_jumper",
        "args": {
            "number_of_lines": 10,
            "cmd": "up_select"
        }
    },

    {
        "keys": ["alt+up"],
        "command": "line_jumper",
        "args": {
            "number_of_lines": 10,
            "cmd": "up"
        }, "context": [
            { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true }
    }
]
```

And that way it is even user-configurable.

**Comment by sflip** [comment]
All right.

**Pull request closed without merging**
