### PR TITLE
Add GoTests plugin.

### PR DESCRIPTION
**Pull request by cweill**
Add the Go test generator plugin for [gotests](https://github.com/cweill/gotests).

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need a `.no-sublime-package` file in your package. Please remove it.

**Comment by cweill** [comment]
Done.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by cweill** [comment]
Done.

**Pull request merged**
