### PR TITLE
Changed Cobalt2 Flat Theme to Theme - Cobalt2 Flat

### PR DESCRIPTION
**Pull request by r3volution11**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
The convention for the themes is that they start with `Theme -`. Do you mind changing it or it's this name format is important for you?

BTW: you have trailing commas in your `.sublime-theme`. It won't work in ST2. If you remove your multi-line comments (`/* */`), [JSONComma](https://github.com/math2001/JSONComma) can manages them for you

**Comment by r3volution11** [comment]
@math2001 I don't mind. My concern though is people have been having some issues getting the theme to work properly and I thought it may be a name issue. [See issue](https://github.com/r3volution11/Cobalt2-Flat-Theme/issues/3)

I've installed JSONComma and removed the trailing slashes. Perhaps those were the problem with the theme? Awesome work there. Will surely help me out.

Thanks for the compliment. 😄

**Comment by r3volution11** [comment]
Ok, I'm up for the name change and have done so on the repo itself. Should I kill this pull request and start over?

**Comment by math2001** [comment]
No, just edit, commit, and push. You can also edit the title of this PR.

**Comment by r3volution11** [comment]
Well apparently I failed a test. Not sure what I did wrong, looks good to me. Thanks for your help!

**Comment by math2001** [comment]
Because your new name starts with a `T`, you have to move it to `t.json`

**Comment by r3volution11** [comment]
I'm probably going to nuke this test. I was attempting to use the site's edit abilities to do these changes and it looks all screwed up to me now. Especially after editing t.json.

**Comment by r3volution11** [comment]
Alright I think I did it correctly. Haha.

**Comment by math2001** [comment]
Ok, so what is your final name? `Theme - Cobalt2 Flat` right? So, I'm pretty sure the problem you had(ve) is because people are cloning it manually, so in a folder `Theme-colbar2-flat` for example, which makes the paths in your `.sublime-theme` "wrong". So, you need to add instruction in your `readme`:

### Cloning manually

```bash
$ git clone "https://github.com/r3volution11/Theme-Cobalt2-Flat" "Theme - Cobalt2 Flat"
```

So that it download in the right folder name.

**Comment by r3volution11** [comment]
Oh ok, cool thanks. 👍 👍

**Comment by FichteFoll** [comment]
You'll want to:

1. Remove the *Cobalt-Flat-Theme" entry from `c.json`
2. Change all references like [these](https://github.com/r3volution11/Theme-Cobalt2-Flat/blob/26283ce729f2f6344f996b6ad1de1765218416f1/Theme-Cobalt2-Flat.sublime-theme#L72) to read `"layer0.texture": "Theme - Cobalt2 Flat/assets/default/fold_down.png",`.

**Comment by FichteFoll** [comment]
@r3volution11 ping

**Comment by r3volution11** [comment]
I'm alive. Working on it this evening. Sorry for the delay.

**Pull request closed without merging**
