### PR TITLE
add golang package

### PR DESCRIPTION
**Pull request by yields**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need to periodically force-push to the PR to keep it updated. We go through every PR when reviewing anyway.

**Comment by yields** [comment]
> You don't need to periodically force-push to the PR to keep it updated. We go through every PR when reviewing anyway.
> 
> (And I go by submission date.)

Apologies, I remember I read that somewhere I can close and re-open / push, IIRC I've read that here: https://packagecontrol.io/docs/submitting_a_package

Seems like there's no mention of closing/re-opening a PR, so I must've read that somewhere else.

Thanks for merging.

**Comment by FichteFoll** [comment]
Reopening is mentioned in the PR template on this repo and only useful for triggering a review from @packagecontrol-bot.

**Comment by yields** [comment]
ah gotcha, my bad, sorry about that!

**Pull request merged**
