### PR TITLE
add open_doi package

### PR DESCRIPTION
**Pull request by crazytexer**
This package provides a new command in the context menu. It opens the selected digital object identifiers (DOIs), that are formatted without `https://doi.org/` and look like `10.1103/PhysRevLett.116.061102`, as URLs in your browser.

### CODE REVIEW

**Comment by braver** [comment]
Much credits for supporting multiple cursors, people tend to forget about that. 👍🏻  

In your run command you do a check to see if the selection looks like a DOI. You should do this check in an [is_visible](https://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.TextCommand) check, so that the command doesn't display (and take up space) in the context menu. Also, it's good practice to always include all commands in the command palette, as it's accessible without using the mouse.

Finally, I'd recommend renaming the package to "Open DOI".

**Comment by braver** [comment]
Don’t forget to tag a new release with your latest changes!

**Comment by crazytexer** [comment]
Thank you very much for my pull request processing!

> Don’t forget to tag a new release with your latest changes!

Sorry but do you mean the current release (because it already has some changes as compared to the 3-days-ago version) or any future releases?

**Comment by braver** [comment]
In your repo I can only see the 1.0.0 from a few days ago.

**Comment by crazytexer** [comment]
Yes, exactly! What I am asking is whether I should add a new tag right now (because ~3 hours ago I introduced some code changes according to your review, and the 3-days-ago tag 1.0.0 is technically older than that code update) or not. This is probably a very amateurish, if not to say silly, question, and I am sorry about it.

**Comment by braver** [comment]
Package control will only pick up the releases from your GitHub repo. So anything newer than your latest release will not reach any users. So, anytime you do something new in your package you should make a new release. Then, usually an hour or two later, package control will see that release and distribute it to all users of your package.

**Pull request merged**
