### PR TITLE
Add Edje Syntax

### PR DESCRIPTION
**Pull request by sheosi**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

You still have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@sheosi ping

**Comment by sheosi** [comment]
Sorry I've neen busy lately and forgot about this, I'll try again soon (1-2
days).

**Comment by sheosi** [comment]
Well, I think I got it this time, I didn't knew I had to push the version on its own. Thanks FitchieFoll.

**Comment by sheosi** [comment]
I don't know what's happening anymore, I have made the tag, I have supposedly sent to GitHub with:
git push origin v0.2

Why isn't it  showing on the repo?

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
I cannot merge this anymore. Please open create a new request once you pushed a valid semantic version tag.

**Pull request closed without merging**
