### PR TITLE
Add Reach IDE

### PR DESCRIPTION
**Pull request by chrisnevers**

### CODE REVIEW

**Comment by braver** [comment]
@chrisnevers Thanks for submitting. Please have a look at the feedback from the bot. Let me know if you have any questions.

**Comment by chrisnevers** [comment]
@braver thanks, it looks like it's not registering the license and tmlanguage files I added?

**Comment by braver** [comment]
I'm not sure if it takes master or your latest release, but if it's the latter that would explain it. Maybe try tagging a new release and then request a new review?

**Comment by braver** [comment]
🎉

**Pull request merged**
