### PR TITLE
Added a new plugin "Django Starter"

### PR DESCRIPTION
**Pull request by geekpradd**
It's similar to the Flask Starter Plugin except longer and more complicated (plus more useful).
It enables Django Developers to create Django Projects directly from Sublime Text rather than using django_admin.py from the Terminal. It auto creates all python files and Django Folders.

Link: https://github.com/geekpradd/Sublime-Django-Starter

### CODE REVIEW

**Comment by geekpradd** [comment]
Travis Build is passing. My forked repo can be merged.

**Comment by geekpradd** [comment]
I've added support for Sublime Text 2 in this commit.

**Comment by FichteFoll** [comment]
For `djangoFileCode.py` I can recommend you to take a look at the `textwraps.dedent` function.

Furthermore, I highly suggest you to use the `os.path.join` function instead of hardcoding backslashes for file paths.

**Comment by geekpradd** [comment]
@FichteFoll .. Thanks for the feedback. I've improved the code structure and used os.path.join and textwrap.dedent in the latest version.

**Pull request merged**
