### PR TITLE
Added Hastebin Upload plugin

### PR DESCRIPTION
**Pull request by ambartsumov**

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/To%20Hastebin ?

**Comment by ambartsumov** [comment]
That plugin does not work as intended, unfortunately - with multiple regions selected, it only uploads the last one.

**Comment by FichteFoll** [comment]
Please consider proposing a pull request to the already listed package. I'm sure @nicetrysean would love to see a contribution.

**Comment by ambartsumov** [comment]
His account does not seem to be active - his last contribution was made almost a year ago, and ToHastebin repository has last been updated in 2013.

**Comment by FichteFoll** [comment]
Last activity was [5 days ago](https://github.com/nicetrysean?tab=activity).

I will wait for at least 2 weeks for a response, since I mentioned him. @nicetrysean will then be able to express his desire to merge your pull request, add you as a contributor to his repo, allow you to replace his package here on package control (in which case all of the existing functionality should be preserved and an update message about the move should be presented to users) or neither of these.

**Comment by ambartsumov** [comment]
Ok, I stand corrected. Alright, I'll try to get in touch with @nicetrysean.

**Comment by nicetrysean** [comment]
Sorry about being inactive publicly! 
I've added you as a contributor @ambartsumov, feel free to add what you want :)

**Comment by FichteFoll** [comment]
Alright, sounds good. I'm closing this then.

**Pull request closed without merging**
