### PR TITLE
add Create Init plugin

### PR DESCRIPTION
**Pull request by Boris-code**

### CODE REVIEW

**Comment by Boris-code** [comment]
fixed shortcut key conflict

**Comment by Boris-code** [comment]
Hi, I haven't seen the create init plugin in package contral. what can i do ?

**Comment by Thom1729** [comment]
The keybind is unconditional; it will run regardless of whether it would make sense to do so. That should probably be changed. In addition, you should have a `sublime-commands` file so that the command is accessible from the command palette.

It also like like the command will silently overwrite an `__init__.py` file if one already exists.

**Comment by Thom1729** [comment]
@Boris-code ping.

**Pull request closed without merging**
