### PR TITLE
Updated x86_64 assembly package info

### PR DESCRIPTION
**Pull request by 13xforever**
Seeing as it was already submitted and accepted, let's try to do it right

PS: it is not clear if a simple case adjustments in the package name should be treated as a rename

### CODE REVIEW

**Comment by wbond** [comment]
You are correct that it is not extremely clear about case changes and renames. In this case I can tell you that in order to actually change the name for existing users and have them get new releases, the old capitalization will need to be added in a `previous_names` list for the package.

**Comment by 13xforever** [comment]
Alright, I've updated the package info with the old name

**Comment by 13xforever** [comment]
Also, while we're on the topic of docs, it would be nice to have an explicit info on what tags are recognized as a package version (i.e., only "1.2.3" or "v1.2.3" works as well, etc).

**Comment by wbond** [comment]
For tag versions, see https://packagecontrol.io/docs/submitting_a_package#Step_4. Specifically, any tag that is a [semantic version number](http://semver.org/) will work.

**Comment by 13xforever** [comment]
Yes, I know follow the semver in my own projects, but I prefer to do tags with prefix instead of a bare number. Prefixes are not a part of semver specification per se.

**Comment by wbond** [comment]
https://github.com/wbond/package_control/blob/master/example-repository.json#L264-L288

**Pull request merged**
