### PR TITLE
add StackTracer package

### PR DESCRIPTION
**Pull request by zhangqibupt**
https://github.com/zhangqibupt/stacktracer
https://github.com/zhangqibupt/stacktracer/tags

### CODE REVIEW

**Comment by zhangqibupt** [comment]
It Seems that the url I offered is wrong, I have corrected it and now is 
https://github.com/zhangqibupt/stacktracer/releases
Sorry for the inconvenience.

**Comment by zhangqibupt** [comment]
It seems that the url I offered is wrong, I have corrected it and now is https://github.com/zhangqibupt/stacktracer/releases
Sorry for the inconvenience.

**Comment by wbond** [comment]
@zhangqibupt You'll need a valid [semver](http://semver.org) tag at https://github.com/zhangqibupt/stacktracer/tags. That is to say, it need to have three numeric parts.

**Comment by zhangqibupt** [comment]
@wbond 
Sorry for not having realized the point, now I have created a new tag named '1.0.0', sorry for the inconvenience.

**Pull request merged**
