### PR TITLE
Add FlowTree plugin

### PR DESCRIPTION
**Pull request by maxwelljohn**
I made a package that automatically creates a diagram of your workflow while you're programming.

### CODE REVIEW

**Comment by maxwelljohn** [comment]
I added a LICENSE file in the FlowTree repository.

**Comment by Thom1729** [comment]
Is ST2 compatibility necessary? I'm concerned about monkeypatching `sublime`.

**Comment by maxwelljohn** [comment]
Thanks for getting to this!  ST2 compatibility isn't necessary.  Let me know if there are further issues. 
 (Or make whatever changes you feel are appropriate, really.)

**Comment by Thom1729** [comment]
Without ST2 compatibility, there's no need to use `Edit.py` (which hacks into Sublime's internals in a worrisome manner).

**Comment by maxwelljohn** [comment]
Oh, I see what you're getting at.  This is my first Sublime plugin and I made use of `Edit.py` because I didn't think there was any other way to do what I was trying to do.  I took another look at the API documentation and I think I figured out the right way to do it.  `Edit.py` is no longer in the repo: https://github.com/maxwelljohn/FlowTree/commit/9878e57c86c0f55331eecd67f1b27f5178941d05

**Pull request merged**
