### PR TITLE
Add JsPrettier

### PR DESCRIPTION
**Pull request by jonlabelle**
- **Description:** A Sublime Text Plug-in for [Prettier](https://github.com/jlongster/prettier), the opinionated JavaScript formatter.
- **Code repository:** <https://github.com/jonlabelle/SublimeJsPrettier>
- **Tags page:** <https://github.com/jonlabelle/SublimeJsPrettier/tree/1.0.0>

### CODE REVIEW

**Comment by jonlabelle** [comment]
Just fyi... I did update the package to include an [animated gif demo](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/screenshots/demo.gif).

**Comment by math2001** [comment]
> I did update the package to include an animated gif demo.

:+1: But, add it in your README, otherwise, nobody's going to see it...

**Comment by FichteFoll** [comment]
Note that a local installation of `prettier` in the package's directory will get *removed* on every package upgrade of the ST package. Also, your package dir will be named "JsPrettier". You might want to fix that in the readme.

**Comment by jonlabelle** [comment]
@FichteFoll [Done](https://github.com/jonlabelle/SublimeJsPrettier/commit/1ea4f4d6ce94c6b0ae8100e96f575be750ea6bbb).

Thanks @math2001 and @FichteFoll.

**Pull request merged**
