### PR TITLE
Add Sublime Tips

### PR DESCRIPTION
**Pull request by kapitanluffy**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is **Tips**

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by kapitanluffy** [comment]
@packagecontrol-bot

**Comment by jrappen** [comment]
Please use a sane target for supported Sublime Text Builds, I suggest `>=4107`.

**Comment by jrappen** [comment]
You should also add the git helper files to `.gitattributes` with export-ignore.

**Comment by jrappen** [comment]
Not sure about the value of the tip: `Sublime Text is the second best editor!`

**Comment by jrappen** [comment]
The tips you provide seem to target Windows specifically, yet the plugin's installation isn't limited to Windows only in this PR.

What are your plans in this regard?

**Comment by kapitanluffy** [comment]
@jrappen updated the repo. It now supports osx.

**Comment by kapitanluffy** [comment]
@braver sorry. removed it 😅

**Comment by braver** [comment]
You could simplify a bit further and remove the settings file. Users can simply uninstall or disable the package if they don't want hints. 

I would think that making hints about key bindings would be a bit more involved than simply switching what key the "primary" or "super" key is? For Win/Linux chords are used more often, whereas on MacOS there are many more modifiers available and chords are usually avoided. And typically a Mac keyboard doesn't have Home or End keys (you use CMD + arrow keys instead). I'm sure you double checked your list, but this approach wil really limit what you can cover. And of course as soon as someone starts customizing the hints are no longer correct (presumably at that level you no longer need or want hints).

But it looks like a fun little, and harmless, package, so I wouldn't let its limitations stop us from adding it.

One final consideration: typically the same for such a feature would be "Tips", the dreaded "Show tips at start up" popups etc. 😉 Wouldn't that be a better name? "Hints" in software development are usually more contextual, whereas this is simply random.

**Pull request merged**
