### PR TITLE
Starting over with adding cfmldocplugin

### PR DESCRIPTION
**Pull request by MFernstrom**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo. They consist of three numeric parts.

**Comment by MFernstrom** [comment]
Done (I thought patch was optional). Sorry about all the fuss, next project will go smoother.

**Comment by FichteFoll** [comment]
It actually was ... ~1 1/2 years ago.

**Comment by MFernstrom** [comment]
Ok, will keep in mind.

**Comment by MFernstrom** [comment]
Thanks, FichteFoll.

**Pull request merged**
