### PR TITLE
Added Renpy Script syntax

### PR DESCRIPTION
**Pull request by torrentails**
Please provide the following information:
- Link to your code repository:  
  https://github.com/torrentails/RenPy-Script-Syntax-Sublime-Text-
- Link to the tags page with at least one [semver](http://semver.org) tag:  
  https://github.com/torrentails/RenPy-Script-Syntax-Sublime-Text-/tags

Also make sure you:
1. [x] Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
2. [x] Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

**Note:** Renpy Script is different from Renpy Language.

### CODE REVIEW

**Comment by joshua-golub** [comment]
Torrentails,

Since I am unfamiliar with Renpy, would you please explain to me what your package provides over and above the existing [Renpy Language](https://packagecontrol.io/packages/Renpy%20Language) package?

-Josh

**Comment by torrentails** [comment]
This package contains syntax definition and highlighting for a scripting language that generates Renpy Code. You can see the difference between the script on the left and the generated code on the right here: [rps_rpy_comparison.jpeg](https://cloud.githubusercontent.com/assets/1060901/20086119/cd13bfbe-a5bd-11e6-879d-edcd015b0745.jpeg)

Think the difference between Sass and plain CSS

**Comment by joshua-golub** [comment]
@FichteFoll, this package look good to me. If you agree, please merge it.

**Comment by FichteFoll** [comment]
`.sublime-syntax` support has been added with build 3092. Please adjust your version selector accordingly.

**Comment by torrentails** [comment]
@FichteFoll Good catch; I've corrected it.

**Pull request merged**
