### PR TITLE
Add gntp and regex dependency

### PR DESCRIPTION
**Pull request by facelessuser**
Adding gntp python library.  Tests passed.

Please provide the following information:

 - Link to your code repository:
    - https://github.com/facelessuser/sublime-gntp
    - https://github.com/facelessuser/sublime-regex
 - Link to the tags page with at least one [semver](http://semver.org) tag:
    - https://github.com/facelessuser/sublime-gntp/tags
    - https://github.com/facelessuser/sublime-regex/tags

### CODE REVIEW

**Comment by facelessuser** [comment]
Didn't think I was going to have a chance to setup the VMs and build linux support for regex anytime soon.  Luckily I actually had the time and it has taken  a bit longer for this to get committed allowing me to getting it in before it got pulled.

I am officially done with this and it is ready to be pulled whenever. Thanks.

**Comment by FichteFoll** [comment]
You're not using tags for the `regex` dependency. I don't think there is any written documentation about a requirement of this, but it makes sense to follow the same conventions as we do for packages.

**Comment by facelessuser** [comment]
Sorry, I meant to use tags.  I copied it from my test channel. I'll fix it.

**Comment by facelessuser** [comment]
Fixed.

**Comment by facelessuser** [comment]
@FichteFoll, thanks for taking time to look at this.

**Pull request merged**
