### PR TITLE
Add Projectionist package

### PR DESCRIPTION
**Pull request by timfjord**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

The package implements the logic that was originally introduced by [Tim Pope](https://github.com/tpope) in his [vim-projectionist](https://github.com/tpope/vim-projectionist) plugin. And the main idea is to provide granular project configuration using "projections".

Here are the package features:

- jump between test and implementation files
- open/jump to an alternate file from the Side Bar
- `.projections.json file` support (including JSON schema validation)
- built-in projections for Elixir, Ruby, and Sublime package development
- public API for other packages to use
- work on all platforms

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
That's very cool!

Some minor feedback:
- Your main menu is empty. It should at the very least give access to the settings.
- A sidebar context menu doesn't have mnemonics.

**Comment by braver** [comment]
By the way, you might benefit of opting into the python3.8 package runtime.

**Comment by timfjord** [comment]
@braver Thanks for taking a look.  
I've addressed your feedback.

As for Python 3.8, my plan was first to implement a reasonable amount of features and then switch to Python 3.8.
This way, Sublime Text 3 users can use the basic features of the package.
So, for now, I would keep 3.3

**Comment by braver** [comment]
There aren't that many people still using ST4 though, I wouldn't expect any active users that are also looking for new package. The 3 to 4 upgrade was free IIRC, and only changed the longevity of licenses. But suit yourself of course.

**Comment by timfjord** [comment]
I agree with you, but I don't want to switch the env without leveraging the full potential of Python 3.8
So I would probably stick to the original plan

**Comment by FichteFoll** [comment]
If your code is compatible with both Python 3.3 and 3.8, your plugins would still benefit from running on 3.8 because it's faster.

**Comment by timfjord** [comment]
Hmm, I didn't think of it from this perspective.
Will update the version then 👍🏻

**Pull request merged**
