### PR TITLE
Submitting my package to package control

### PR DESCRIPTION
**Pull request by renidantass**

### CODE REVIEW

**Comment by FichteFoll** [comment]
This looks a lot like a build system in the form of a plugin. Have you checked out build systems before? Aren't there any other packages doing this already?

**Comment by FichteFoll** [comment]
@renidantass ping

**Comment by renidantass** [comment]
Yeah, this is almost a build system... (a error checker on output to show on status bar is a difference)

**Comment by FichteFoll** [comment]
So why not use an actual build system? Or is it just the status bar text you want sepcifically here?

**Comment by renidantass** [comment]
That way is more easy on daily use. As build system, i would have 2 build system (one for embedded tvs and another to typescript).

**Comment by FichteFoll** [comment]
Note that you can add key bindings for any build system (variant) using the `build` command with the `build_system` and `variant` args, if quick switching between the two is an issue.

**Comment by FichteFoll** [comment]
I'm still not convinced this plugin has any reason for existance in its current form. Everything you do in the plugin can be done in a build system, except for printing to the status bar (which isn't even cleared, so it might as well use an output panel for the user to actually dismiss it) and running on save instead of on a separate key (e.g. ctrl+b) on-demand (which we also have https://packagecontrol.io/packages/SublimeOnSaveBuild for).

Besides, there is still the bug with paths containing spaces.

**Comment by renidantass** [comment]
Interesting! I'll fix the bug with spaces anyway, I understand the mistake in project. Thanks for advice!

**Pull request closed without merging**
