### PR TITLE
Add XdebugHelper

### PR DESCRIPTION
**Pull request by maliayas**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.

My package is [XdebugHelper](https://github.com/maliayas/SublimeText_XdebugHelper)

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Thanks for your submission. Sorry we kept it sitting there for a while, a package like this needs a bit more thinking about to review then say a color scheme :)

- There are multiple Xdebug packages in package control, none of which are called "SublimeTextXdebug". The repo might be called that way but the package is named differently. It might help users if you link to the specific one on package control you're interfacing with.
- As for the package itself the only thing I'm unsure about is the keybindings. All the F keys are popular, even with modifiers. You might end up masking some other package, or the other way around. That's why we recommend to not ship with bindings enabled and instead tell users how to set their own.
- Hopefully you also tested with some more recent builds of Sublime Text? The one in your readme is ancient.

**Comment by braver** [comment]
👋🏻

**Comment by maliayas** [comment]
Oh, I didn't notice the feedback.

1. You are right, I'll update the readme.
2. Keybindings which this plugin uses are already defined by the original Xdebug plugin. I only override them. So I think that's fair?
3. I'll do once I find time and get back to you.

Thanks for the review.

**Comment by braver** [comment]
> So I think that's fair?

Certainly 👍🏻 

Let me know!

**Comment by braver** [comment]
> get back to you.

let me know, we can re-open then

**Pull request closed without merging**
