### PR TITLE
CS-Script package

### PR DESCRIPTION
**Pull request by oleg-shilo**
Please find the new CS-Script plugin at GitHub:
- Code repository: https://github.com/oleg-shilo/cs-script-sublime
- Tags:  https://github.com/oleg-shilo/cs-script-sublime/tags

The plugin description can be found [here](https://github.com/oleg-shilo/cs-script-sublime/blob/master/README.md)

Please also note that this pull request also contains a very minor change to my other plugin CodeMap: corrected `sublime_text` value to ensure deployment on ST3 only,

Thank you,
Oleg

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Sorry for the conflict. It looks like I accidently modified the file before my pull operation was completed and `c.json` got the conflict. 

The conflict is trivial it is isolated within **my** code without affecting any other plugins' sections. And since I have no write access please just accept `"sublime_text": ">=3000",` version.

Thank you,
Oleg

**Comment by FichteFoll** [comment]
Note that you are *very likely* violating copyright by bundling the three `.exe` binaries.

**Comment by FichteFoll** [comment]
Oh, I forgot this, too:


## Report for cs-script-sublime #######################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 8 failures:
- The binding ['f6'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['f7'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['f12'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['alt+o'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['f4'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['ctrl+f4'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['f5'] unconditionally overrides a default binding
    File: Default.sublime-keymap
- The binding ['ctrl+f5'] unconditionally overrides a default binding
    File: Default.sublime-keymap

Reporting 1 warnings:
- '.no-sublime-package' is defined. Please verify that it is *really* necessary

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

Please remove the conflicting bindings.

**Comment by oleg-shilo** [comment]
Thank you.

>Note that you are very likely violating copyright by bundling the three .exe binaries.

Two of these are my other products distributed under MIT licence. The third one is MS utility under Apache licence. Just to make it more obvious I have included the licence notice for all dependency components.

> ...unconditionally overrides a default binding

Overriding was intentional as I wanted to replace the default action. I have updated the code to make key binding for *.cs files only. This is my understanding  that this is the way to do this:
```js
, "context": { "key": "selector", "operator": "equal", "operand": "source.cs"}
```

>'.no-sublime-package' is defined. Please verify that it is really necessary

Yes it is necessary since I am distributing exe files.

Thank you for looking at it.

**Comment by FichteFoll** [comment]
>Just to make it more obvious I have included the licence notice for all dependency components.

👍 

>I have updated the code to make key binding for *.cs files only. 

Also 👍

**Pull request merged**
