### PR TITLE
updated sass director

### PR DESCRIPTION
**Pull request by Stephn-R**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Any specific reason for the rename?

When renaming you have to add the old name to a `previous_names` array.

**Comment by Stephn-R** [comment]
We decided to move the project to an organizational account. Bigger plans haha

**Comment by FichteFoll** [comment]
I was mostly referring to the change of the `name` attribute. Btw, you can rename and move repositories on github itself which will preserve issues and set up http redirects.

**Comment by Stephn-R** [comment]
Ah, the name change is not too specific but we would prefer it be called "Sass-Director" and not "SassDirector"

**Pull request merged**
