### PR TITLE
Add Outline Notes Publisher

### PR DESCRIPTION
**Pull request by gnat**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

There are no packages like it in Package Control.

# [Github](https://github.com/gnat/sublime-outline-notes-publisher)

# ✒️ Sublime Outline Notes Publisher
Publish HTML pages using tab indented notes or markdown (md)! 🔥

Zero dependency publishing from the comfort of your code editor. 🔥 It's Obsidian in Sublime Text!

Perfect for:

* Note takers who love using tab indentation / whitespace for organization.
* Static site generator for personal sites, blogs, micro wiki.
* Zettelkasten
* Replacing your outliner with Sublime Text.
  * What is an [Outliner](https://en.wikipedia.org/wiki/Outliner)?

<a href="https://github.com/gnat/sublime-outline-notes-publisher/tags">
    </a>

<a href="https://www.sublimetext.com/">
    </a>

## Publish HTML Pages ...

Screenshot

## Using your hierarchy aware notes!

````
All you have to do...
    Is create an indented hierarchy.
    Of your notes.
    In a list.
    It will create a nice HTML file...
        With a hierarchy based on indent levels.
            Isn't this convenient?
            Whitespace significant outliner style notes!
            Other cool outliners:
                [Bike](https://news.ycombinator.com/item?id=31409077)
                Dynalist
                [Obsidian](https://obsidian.md)
                    [Obsidian Publish](https://obsidian.md/publish)
                Workflowy
                Roam Research
                Notion
                Standard Notes
                Evernote
                    Ever-who? 🐘
            Only for:
                Sublime Text (https://sublimetext.com)
                Super Nintendo
🔥 Great plugin for
    Note taking.
    Outlining.
    Zero dependency publishing.

🚧 Code blocks!

```javascript
document.addEventListener("click", ev => {
    alert("You selected the following element: " + ev.target)
})
```

✅ Common markdown / markup syntax.

# Header 1 line
## Header 2 line
* Emphasis line
** Bold line

### Images with img

<img src="https://avatars.githubusercontent.com/u/24665" style="max-width: 200px" />

### Global and Local Links. Plain, named and pure HTML links.

http://github.com/gnat/sublime-outliner-html
🔗 [Local named link!](/local_link) 🌐 [Global named Link!](http://google.com) https://google.com <a href="https://google.com">Pure HTML link!</a>

💬 Comments.

// I will not be in the HTML file.

🏗️ Comments to insert structural metadata.

//title I will be added to <html> ▶️ <head> ▶️ <title>
````

### CODE REVIEW

**Comment by gnat** [comment]
Added optional global configuration options to specify CSS, title, extra header, body footer content.

**Comment by gnat** [comment]
Thank you!! @TheSecEng

**Comment by braver** [comment]
Thanks for submitting your package. The only thing I'd like to see changed is to rename `__init__.py` to something like NotesPublisher.py, which is more conventional.

**Comment by braver** [comment]
Please respond to the feedback to continue the review.

**Comment by gnat** [comment]
Done @braver thanks.

**Pull request merged**
