### PR TITLE
Adding HLSL Syntax project

### PR DESCRIPTION
**Pull request by MattSutherlin**

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

**Comment by AlexKvazos** [comment]
Repository is missing a release tag, please add this so we can merge. ⚠️

**Comment by MattSutherlin** [comment]
Release tag in my HLSL repo or my fork of the Package Control repo?  I've added a release tag to the HLSL repo now.

Sorry if that's a weird question, this is my first time doing this.

**Comment by AlexKvazos** [comment]
Release tag on your repo. Thank you, now just wait for a maintainer to accept your PR, you're all set.

**Pull request merged**
