### PR TITLE
add Persistent Console

### PR DESCRIPTION
**Pull request by idleberg**

### CODE REVIEW

**Comment by Thom1729** [comment]
> This borrows heavily from the BinaryPlist package.

What is borrowed, exactly?

Would `on_new_async` work just as well as `on_new`?

> settings = sublime.load_settings("Persistent Console.sublime-settings") or True

Can the `or True` ever run?

Rather than unconditionally running `ConditionalShowConsoleCommand`, would it make more sense to conditionally run `ShowConsoleCommand`?

**Comment by idleberg** [comment]
> What is borrowed, exactly?

Whoops, it's a remainder from another package of mine which I used as boilerplate

Thanks for the input, I made all changes except for conditionally running `ShowConsoleCommand`. Will get to that a bit later, I had no idea I can pass arguments to `run_command`. So I guess it makes sense 🙂

**Comment by Thom1729** [comment]
Why not just check the setting in the listener and only run the command at all if it's enabled?

**Comment by idleberg** [comment]
How can I get `window` in the EventListener?

**Comment by Thom1729** [comment]
Something like this?

```python
class ConditionalShowConsoleListener(EventListener):
    """Adds listener events."""

    def on_new_async(self, view):
        """Listen for new windows."""
        enabled = sublime.load_settings("Persistent Console.sublime-settings").get("enable", False)
        if enabled:
            view.window().run_command("show_console")
```

**Comment by idleberg** [comment]
Thanks. I tried that before and it works, but it also prints an error for the line where it's used

> NameError: global name 'window' is not defined

**Comment by Thom1729** [comment]
Does it still do that? I don't see where the unqualified name `window` is used anywhere in the plugin.

**Comment by idleberg** [comment]
I restarted Sublime Text, now it's gone

**Comment by Thom1729** [comment]
On an unrelated note, you need to prefix tags with `v`, e.g. `v0.1.0`, due to the way that Package Control works.

**Comment by idleberg** [comment]
> On an unrelated note, you need to prefix tags with `v`, e.g. `v0.1.0`

I don't think that's true, as none of my other packages are tagged that way. I *usually* prefix all my projects with a `v`, Sublime Text being an exception. Well, but since were at 0.1, I can still <del>fix</del> change that.

**Pull request merged**
