### PR TITLE
Add UniqueWindow

### PR DESCRIPTION
**Pull request by Julow**
A plugin that allow to open folders in the same window and prevent the last window from closing

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by Julow** [comment]
Done

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by Julow** [comment]
Lol

**Comment by Julow** [comment]
Done

**Pull request merged**
