### PR TITLE
repository/g.json: add gcode syntax highlighting package

### PR DESCRIPTION
**Pull request by ElectricRCAircraftGuy**
Here is my package: https://github.com/ElectricRCAircraftGuy/sublime_gcode

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a syntax highlighter for gcode ([G-code](https://en.wikipedia.org/wiki/G-code)). 

My package is similar to https://packagecontrol.io/packages/G-code%20Syntax%20Highlighting. However, it should be added still because:
1. That package is 7 years old, not updated, and currently missing some basic things like line comment highlighting. 
2. This package is significantly different and has more-robust highlighting I find to be much more pleasing to the eye. I considered making it a fork but ended up doing a total rewrite with my own implementation instead. 

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by ElectricRCAircraftGuy** [comment]
> * If @themachinist is ok with it, I'd rather replace that package than add a new one.

I emailed @themachinist to point him to this link to see what he says. 

> * In any case language packages should just be named after the language, and not include words like "syntax" or "highlighting".

This can't be true. `grep -rni '"name":.*syntax'` shows all matches in this repo with the word "syntax" in their name. Pipe this to `wc -l` to count the matches:

There are **250** package names with the word "syntax" in them:
```bash
package_control_channel$ grep -rni '"name":.*syntax' | wc -l
250
```

...and **124** with the word "highlight" in them:
```bash
package_control_channel$ grep -rni '"name":.*highlight' | wc -l
124
```

...and **87** with the words "syntax" followed in one way, shape, or form, by "highlight":
```bash
package_control_channel$ grep -rni '"name":.*syntax.*highlight' | wc -l
87
```

Sample output:

```bash
package_control_channel$ grep -rni '"name":.*syntax'
repository/k.json:71:			"name": "Kconfig Syntax Highlight",
repository/k.json:146:			"name": "Kerbal Space Program Configuration Syntax",
repository/k.json:427:			"name": "KoLMafia ASH Syntax",
repository/k.json:459:			"name": "KRL (Kinetic Rule Language) Syntax",
repository/k.json:500:			"name": "KSQL Syntax Highlighter",
repository/k.json:553:			"name": "Kusto Syntax Highlighter",
repository/s.json:5:			"name": "S-Expressions Syntax",
repository/s.json:76:			"name": "SaltStack-related syntax highlighting and snippets",
repository/s.json:112:			"name": "San Syntax Highlight",
repository/s.json:163:			"name": "SAS Syntax and Theme",
repository/s.json:312:			"name": "Scala Syntax",
repository/s.json:546:			"name": "Scopus Syntax Highlighter",
repository/s.json:1185:			"name": "Serpent Syntax",
repository/s.json:1334:			"name": "Shader Syntax (GLSL HLSL Cg)",
repository/s.json:1518:			"name": "Shlisp Syntax",
repository/s.json:1794:			"name": "SIMPL+ Syntax Highlight",
repository/s.json:2000:			"name": "SimpleSyntax",
repository/s.json:2033:			"name": "Simutrans dat Syntax",
repository/s.json:2053:			"name": "Singularity Definition File Syntax",
repository/s.json:2085:			"name": "Siteleaf Liquid Syntax",
repository/s.json:2111:			"name": "Six - Future JavaScript Syntax",
repository/s.json:2733:			"name": "SNMP MIB Syntax",
repository/s.json:2745:			"name": "Snowball Syntax",
repository/s.json:2987:			"name": "SourcePawn Syntax Highlighting",
repository/s.json:3265:			"name": "Splunk Conf File Syntax Highlighting",
repository/s.json:3287:			"name": "Splunk Syntax",
repository/s.json:3349:			"name": "Sprak Syntax & Completions for else Heartbreak()",
repository/s.json:3648:			"name": "Stanza Syntax",
repository/s.json:3889:			"name": "Strace Syntax",
repository/s.json:5001:			"name": "SUCC Syntax Highlighting",
repository/s.json:5737:			"name": "Syntax gRally",
repository/s.json:5748:			"name": "Syntax Highlighting for PostCSS",
repository/s.json:5759:			"name": "Syntax Highlighting for Sass",
repository/s.json:5774:			"name": "Syntax Highlighting for SSS SugarSS",
repository/s.json:5785:			"name": "Syntax Highlighting Scopes Showroom",
repository/s.json:5795:			"name": "Syntax History",
repository/s.json:5806:			"name": "Syntax Matcher",
repository/s.json:5816:			"name": "Syntax Off Color Scheme",
repository/s.json:5827:			"name": "Syntax ProtoList",
repository/s.json:5837:			"name": "Syntax QBasic",
repository/s.json:5847:			"name": "Syntax Sproto",
repository/s.json:5866:			"name": "SyntaxDefinitionHelper",
repository/s.json:5876:			"name": "SyntaxFold",
repository/s.json:5886:			"name": "SyntaxHighlighter Reloaded Color Scheme",
repository/t.json:257:			"name": "Tagger Script Syntax",
repository/t.json:423:			"name": "TASM Syntax",
repository/t.json:2301:			"name": "ThriftSyntax",
repository/t.json:2528:			"name": "Tmux Syntax Highlight",
repository/t.json:2613:			"name": "TodoTxt Syntax",
repository/t.json:2935:			"name": "Topas Syntax",
repository/t.json:3404:			"name": "Turtle RDF Syntax",
repository/t.json:3542:			"name": "TXL syntax highlighting",
repository/t.json:3564:			"name": "Type Language Syntax",
repository/t.json:3598:			"name": "TypeScript Syntax",
repository/a.json:74:			"name": "ABNF-sublime-syntax",
repository/a.json:560:			"name": "ALE Syntax Highlight",
repository/a.json:826:			"name": "AMPscript Syntax Highlighter",
repository/a.json:1232:			"name": "ANTLR syntax highlight",
repository/a.json:1271:			"name": "AoE2 RMS Syntax Highlighting",
repository/a.json:1314:			"name": "APDL (ANSYS) Syntax Highlighting",
repository/a.json:1632:			"name": "ARFF Syntax Highlighting",
repository/a.json:1849:			"name": "ASL Syntax Highlight",
repository/a.json:1902:			"name": "Assembly 6809 and 6309 Syntax Highlighting",
repository/a.json:1979:			"name": "ATG(CocoR C#) Syntax",
repository/a.json:2032:			"name": "ATS Syntax Highlight",
repository/a.json:2506:			"name": "AVM2 Pcode Syntax Highlighting",
repository/w.json:91:			"name": "WDL Syntax",
repository/w.json:146:			"name": "WebAssembly Text Syntax",
repository/w.json:327:			"name": "WEOML Syntax",
repository/w.json:569:			"name": "Witcher Script Syntax",
repository/w.json:888:			"name": "World of Warcraft Macro Syntax",
repository/w.json:899:			"name": "World of Warcraft TOC file Syntax",
repository/w.json:910:			"name": "World of Warcraft XML file Syntax",
repository/d.json:371:			"name": "Debian Syntax",
repository/d.json:548:			"name": "Delphi Syntax Highlighting",
repository/d.json:800:			"name": "Dict Verification Template Syntax",
repository/d.json:1093:			"name": "Django Syntax",
repository/d.json:1208:			"name": "DLE Syntax Highlighting",
repository/d.json:1295:			"name": "Dockerfile Syntax Highlighting",
repository/d.json:1391:			"name": "DokuWiki Syntax",
repository/d.json:1478:			"name": "Dotfiles Syntax Highlighting",
repository/d.json:1489:			"name": "doTjs Template Syntax Highlighting",
repository/d.json:1522:			"name": "dotsyntax",
repository/d.json:1578:			"name": "DRAMA Syntax Highlighter",
repository/d.json:1740:			"name": "Duckyscript Syntax",
repository/n.json:38:			"name": "Nano RC Syntax",
repository/n.json:71:			"name": "naomi-syntax",
repository/n.json:207:			"name": "neko nml syntax",
repository/n.json:327:			"name": "NetLogo Syntax",
repository/n.json:377:			"name": "NetYCE syntax highlighting",
repository/n.json:409:			"name": "Neverwinter Script syntax and build",
repository/n.json:564:			"name": "NHP Syntax Highlight",
repository/n.json:706:			"name": "NitSyntaxHighliter",
repository/n.json:1219:			"name": "NuSMV Syntax",
repository/r.json:320:			"name": "RAML Syntax Highlighter",
repository/r.json:390:			"name": "RAPID Syntax Highlighting",
repository/r.json:431:			"name": "Razor C# Syntax",
repository/r.json:742:			"name": "ReaSyntax",
repository/r.json:1608:			"name": "Riot Syntax",
repository/r.json:1630:			"name": "RISC OS CMHG Syntax",
repository/r.json:1641:			"name": "RISC OS Command Syntax",
repository/r.json:1652:			"name": "RISC-V Assembly Syntax",
repository/r.json:1760:			"name": "Rockstar Syntax Highlighter",
repository/r.json:1818:			"name": "ROS msg syntax highlight",
repository/r.json:1861:			"name": "RPG Syntax for ILE on IBMi",
repository/r.json:1885:			"name": "RPM Spec Syntax",
repository/z.json:240:			"name": "ZPL Syntax",
repository/v.json:269:			"name": "VEX Syntax",
repository/v.json:772:			"name": "Vue Syntax Highlight",
repository/b.json:5:			"name": "B Syntax Highlighting",
repository/b.json:160:			"name": "BAROC syntax highlighting",
repository/b.json:257:			"name": "BazelSyntax",
repository/b.json:275:			"name": "BBC BASIC Syntax",
repository/b.json:286:			"name": "BBCode Syntax",
repository/b.json:835:			"name": "bioSyntax",
repository/b.json:860:			"name": "Bitbake Syntax",
repository/b.json:1225:			"name": "BorkFilesSyntaxHighlighting",
repository/b.json:1536:			"name": "bst syntax",
repository/j.json:481:			"name": "JavaScriptNext - ES6 Syntax",
repository/j.json:585:			"name": "Jedi Syntax",
repository/j.json:803:			"name": "JQ Syntax",
repository/j.json:1238:			"name": "jsonnet syntax",
repository/j.json:1305:			"name": "JSTL syntax",
repository/g.json:5:			"name": "G-code Syntax Highlighting",
repository/g.json:155:			"name": "gcode (syntax highlighter for G-code)",
repository/g.json:541:			"name": "Git Commit Message Syntax",
repository/g.json:892:			"name": "GitSyntaxes",
repository/g.json:1048:			"name": "GM Syntax",
repository/g.json:1091:			"name": "gmsh-syntax-and-tools",
repository/g.json:1198:			"name": "Gocc BNF Syntax",
repository/g.json:1485:			"name": "Google Stylesheets Syntax",
repository/g.json:1528:			"name": "Gopher sauce syntax and static completions",
repository/g.json:2010:			"name": "Graql Syntax",
repository/g.json:2145:			"name": "GROQ Syntax Highlighting",
repository/f.json:387:			"name": "FEI Syntax-n-Snippets",
repository/f.json:430:			"name": "ferm Syntax",
repository/f.json:933:			"name":"Firebase Rules Syntax",
repository/f.json:1113:			"name": "Flatdata Syntax Highlighting",
repository/f.json:1782:			"name": "FSP Syntax",
repository/f.json:1814:			"name": "Fugly Syntax Highlight",
repository/e.json:265:			"name": "Ecmascript Syntax",
repository/e.json:638:			"name": "ElixirSyntax",
repository/e.json:685:			"name": "Elm Syntax Highlighting",
repository/e.json:708:			"name": "Elvish Syntax",
repository/e.json:777:			"name": "Ember Single-File Component Syntax",
repository/e.json:788:			"name": "Ember Syntax",
repository/e.json:843:			"name": "Emblem.js Syntax Highlighting",
repository/e.json:867:			"name": "EML Syntax",
repository/e.json:954:			"name": "Enaml Syntax Highlighter",
repository/e.json:1222:			"name": "eScript Syntax",
repository/e.json:1897:			"name": "eZ Publish Syntax",
repository/q.json:50:			"name": "QLSyntax",
repository/q.json:147:			"name": "Quartz-Syntax",
repository/m.json:5:			"name": "M3U Syntax",
repository/m.json:37:			"name": "MAC-1 Syntax",
repository/m.json:75:			"name": "Mackerel Syntax Highlighting",
repository/m.json:116:			"name": "MagentoBacktraceMessageSyntax",
repository/m.json:411:			"name": "MapfileSyntax",
repository/m.json:431:			"name": "MapTool Syntax",
repository/m.json:1065:			"name": "Maude Syntax Highlighting",
repository/m.json:1119:			"name": "Maze Syntax",
repository/m.json:1153:			"name": "MCS_Syntax",
repository/m.json:1197:			"name": "MDX Syntax Highlighting",
repository/m.json:1255:			"name": "Mellanox Syntax Highlighter",
repository/m.json:1463:			"name": "Micro16 Syntax",
repository/m.json:1496:			"name": "Microsoft Power Query Syntax",
repository/m.json:1518:			"name": "Miking Syntax Highlighting",
repository/m.json:1714:			"name": "MIPS Syntax",
repository/m.json:1839:			"name": "MJML-syntax",
repository/m.json:2018:			"name": "Modula-2 Language Syntax",
repository/m.json:2575:			"name": "MRL syntax highlighting",
repository/i.json:124:			"name": "IDL-Syntax",
repository/i.json:145:			"name": "Idris Syntax",
repository/i.json:166:			"name": "Idyll-Syntax",
repository/i.json:178:			"name": "IFJCode2017-syntax-highlight",
repository/i.json:1008:			"name": "Ion Syntax",
repository/i.json:1084:			"name": "IPS Package Manifest Syntax",
repository/i.json:1130:			"name": "IRC Syntax",
repository/p.json:16:			"name": "P4 Syntax Highlighter",
repository/p.json:191:			"name": "Panda Syntax Sublime",
repository/p.json:419:			"name": "Parva Syntax",
repository/p.json:637:			"name": "Pawn syntax",
repository/p.json:890:			"name": "Pest Syntax",
repository/p.json:1196:			"name": "PHP Syntax Checker",
repository/p.json:1584:			"name": "PL1 PLI Syntax",
repository/p.json:1793:			"name": "PokemonTeamSyntax",
repository/p.json:1849:			"name": "Polymer Syntax",
repository/p.json:1962:			"name": "PostgreSQL Syntax Highlighting",
repository/p.json:2006:			"name": "Power System Tools Syntax",
repository/p.json:2082:			"name": "PPCL Language Syntax and Editor",
repository/p.json:2093:			"name": "Pre language syntax highlighting",
repository/p.json:2482:			"name": "Project Specific Syntax Settings",
repository/p.json:2594:			"name": "Protobuf Syntax Hightlighting",
repository/p.json:2617:			"name": "Protocol Buffer Syntax",
repository/p.json:2648:			"name": "Pue Syntax Highlight",
repository/p.json:2701:			"name": "Puppet Syntax checking",
repository/p.json:2756:			"name": "PureScript Syntax",
repository/p.json:3336:			"name": "Pyxl syntax",
repository/y.json:70:			"name": "Yang Syntax Highlighting",
repository/y.json:81:			"name": "Yara Rule Syntax",
repository/c.json:194:			"name": "Caddyfile Syntax",
repository/c.json:205:			"name": "Caffe Prototxt Syntax",
repository/c.json:301:			"name": "CAOS Syntax Highlighter",
repository/c.json:312:			"name": "Cap'n Proto Syntax",
repository/c.json:419:			"name": "CBP Syntax Highlighter",
repository/c.json:558:			"name": "CFG Configuration Syntax Highlighting",
repository/c.json:603:			"name": "cFos ml syntax",
repository/c.json:729:			"name": "ChatScript Syntax",
repository/c.json:811:			"name": "Cheetah Syntax Highlighting",
repository/c.json:1112:			"name": "ChucK Syntax",
repository/c.json:1166:			"name": "Cisco Syntax Highlighter",
repository/c.json:1221:			"name": "CJSX Syntax",
repository/c.json:1723:			"name": "Cml Syntax Highlight",
repository/c.json:1805:			"name": "COBOL Syntax",
repository/c.json:1827:			"name": "Coco R Syntax Highlighting",
repository/c.json:2367:			"name": "CoffeeAngular Syntax",
repository/c.json:2490:			"name": "ColobotSyntaxHighlighting",
repository/c.json:2884:			"name": "Columbus Syntax",
repository/c.json:3722:			"name": "Coreboot syntax",
repository/c.json:3817:			"name": "cp2k-syntax",
repository/c.json:3882:			"name": "CQ Clientlibs Syntax Highlight",
repository/c.json:4160:			"name": "CsoundSyntax",
repository/c.json:4583:			"name": "Cubescript Syntax Highlighting",
repository/c.json:4703:			"name": "Curly Syntax Definition",
repository/c.json:4723:			"name": "Curry Syntax Highlighting",
repository/c.json:4803:			"name": "CWL Syntax Highlighting",
repository/o.json:16:			"name": "OAT Syntax",
repository/o.json:347:			"name": "One Command Syntax Highlighter",
repository/o.json:679:			"name": "OpenBSD PF conf syntax highlight",
repository/o.json:894:			"name": "OPM (Orbital Parameter Message) Syntax Highlighting",
repository/o.json:1035:			"name": "Overwatch Workshop Syntax Highlight",
repository/u.json:69:			"name": "UHM Syntax",
repository/l.json:399:			"name": "Lark Grammar Syntax",
repository/l.json:550:			"name": "lay-out Syntax",
repository/l.json:646:			"name": "LC4 Assembly Syntax",
repository/l.json:657:			"name": "LDIF Syntax Highlighting",
repository/l.json:711:			"name": "Ledger syntax highlighting",
repository/l.json:731:			"name": "LeekScript Syntax",
repository/l.json:1086:			"name": "Linguist Syntax",
repository/l.json:1246:			"name": "LitElement Syntax Highlighting",
repository/l.json:1528:			"name": "Logos Syntax Highlighting",
repository/l.json:1539:			"name": "Logstash Syntax Highlighting",
repository/h.json:82:			"name": "HACS Syntax",
repository/h.json:339:			"name": "HDL Syntax Highlighting",
repository/h.json:758:			"name": "HLSL Syntax",
repository/h.json:789:			"name": "HOCON Syntax Highlighting",
repository/h.json:874:			"name": "Hoon Syntax Highlighting",
repository/h.json:1158:			"name": "HTML Syntax in Script",
repository/h.json:1203:			"name": "HTML Underscore Syntax",
repository/h.json:1385:			"name": "HTTP Spec Syntax",

```

**Comment by ElectricRCAircraftGuy** [comment]
@braver, I propose we merge my PR as-is. 

I can always add a follow-up PR to have it replace the `G-code` one by @themachinist if he wants.

Or, I could rename the name of mine like this, to be more in conformance with the existing ones shown above:

```bash
# current name
"name": "gcode (syntax highlighter for G-code)",

# rename to
"name": "gcode / G-code Syntax Highlighting",

# or, to make it stand apart more from the existing "G-code Syntax Highlighting" one:
"name": "ElectricRCAircraftGuy gcode / G-code Syntax Highlighting",
```

**Comment by braver** [comment]
> This can't be true

Sure can. Over the great many years package control has been around quality control hasn’t always been up to the same level… it’s a community project 🤷🏼‍♂️. We can always introduce guidelines that are better than before, otherwise humanity can only go backwards 😉

Let’s do it like this:

- We add your package with a new nice and short name
- We open a new PR to remove the old package and list it as “previous names” for your package
- We give @themachinist 2 weeks to object against it

That gets your package out of the door quickly and should result in eventually moving all existing installations into yours as well.

**Comment by ElectricRCAircraftGuy** [comment]
@braver , thanks for the response. Sounds good. To begin with number 1:

> We add your package with a new nice and short name

I just pushed a new commit which shortens my package name to simply `"gcode"`.

**Comment by ElectricRCAircraftGuy** [comment]
> I'm OK if the package is replaced because I no longer maintain it. @ElectricRCAircraftGuy please maintain the credit to my work in your readme file.

@themachinist, thanks for the reply here!

I have mentioned you in my readme here, under the section "Inspired by these two projects:": https://github.com/ElectricRCAircraftGuy/sublime_gcode#inspired-by-these-two-projects

Is this what you mean?

I plan on keeping that there forever, as credit to your work.

**Comment by braver** [comment]
Nice job 👍🏻

**Pull request merged**
