### PR TITLE
add HBH-Translator plugin.

### PR DESCRIPTION
**Pull request by hbh112233abc**
HBH-Translator plugin can translate the selected string to english or chinese with baidu api,it show translate result at sublime text status bar.

### CODE REVIEW

**Comment by hbh112233abc** [comment]
thanks for your comment,I add tag for https://github.com/hbh112233abc/HBH-Translator.
now the error remove.

**Comment by hbh112233abc** [comment]
> ### Automated testing result: ERROR
> Repo link: [HBH-Translator](https://github.com/hbh112233abc/HBH-Translator)
> [Results help](https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks)
> 
> ```
> Packages added:
>   - HBH-Translator
> 
> Processing package "HBH-Translator"
>   - ERROR: No valid semver tags found at https://github.com/hbh112233abc/HBH-Translator/tags for the package "HBH-Translator".
> ```
add tag v1.0.0

**Comment by hbh112233abc** [comment]
with tags,try again

**Comment by hbh112233abc** [comment]
change keymap,add LICENSE

**Comment by hbh112233abc** [comment]
remove error string

**Comment by hbh112233abc** [comment]
change keymap

**Comment by hbh112233abc** [comment]
change keymap and create new tag

**Comment by hbh112233abc** [comment]
sort by name

**Comment by Thom1729** [comment]
You should really put separate packages in separate PRs.

Are there other Baidu translation plugins?

**Comment by hbh112233abc** [comment]
only add translator plugin

**Pull request merged**
