### PR TITLE
Add ExternalTools plugin

### PR DESCRIPTION
**Pull request by FelixBoers**
Run any external tool with an keyboard shortcut and/or via the command palette.

### CODE REVIEW

**Comment by FelixBoers** [comment]
How can I restart the packagecontrol-bot? I've created the release on my GitHub page

**Comment by FichteFoll** [comment]
This is a really popular type of plugin. Does none of the existing ones do what you need? https://packagecontrol.io/search/command 
Please elaborate on notable differences.

**Comment by FelixBoers** [comment]
Hi @FichteFoll,

I've been searching for a long time for an package like mine:
https://stackoverflow.com/a/31241908/5069465

As far as I know there is no plugin available, which allows me to **easily** create **keybindings** for 
**any external applications** in my environement.
After reviewing the list of plugins in your link, the plugins I've found are either
  - designed to modify the current file
  - designed for explicit applications
  - designed for something else
   
If you can tell me that such a plugin already exists I'd love use it and/or contribute to it.

Regards, Felix

**Comment by FichteFoll** [comment]
[Commando](https://packagecontrol.io/packages/Commando) with the `commando_exec` sub-command strikes really close, imo, but since we have this many already I doubt it will matter having yet another one.

**Pull request merged**
