### PR TITLE
add WebGLCompletions package info

### PR DESCRIPTION
**Pull request by katsew**

### CODE REVIEW

**Comment by FichteFoll** [comment]
For consistency, please increase the release's contents' indentation.

**Comment by katsew** [comment]
@FichteFoll I update release note.
https://github.com/katsew/WebGLCompletions/releases/tag/v1.1.0

Is that correct what you mean to?

**Comment by FichteFoll** [comment]
I mean this:
```
"sublime_text": "*",
"tags": true
```

**Comment by katsew** [comment]
@FichteFoll 
What should I add into it?
platform section?

**Comment by katsew** [comment]
@FichteFoll 
I got what you mean.
I increase releases's indentation.
Please review it.

**Pull request merged**
