### PR TITLE
Add vuejs complete repo

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Finally working commit

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

There are already two packages for Vue.js, one with syntax highlighting (that you mention you included) and one for snippets. What is the reason for the creation of this package and why was contributing to the existing ones not done?

**Comment by BrainBuzzer** [comment]
I did not want to contribute to exusting ones because it was just named as vuejs snippets. I created a package that has syntax highlighting, snippets and **autocomplete**. And thats the reason for that. 

I will look at semantic version and git tagging that you provided. Thanks for the support @FichteFoll

**Comment by BrainBuzzer** [comment]
Hey @FichteFoll I have added the tag to my branch. Please merge.

**Comment by BrainBuzzer** [comment]
Thank you.

**Pull request merged**
