### PR TITLE
Add Solium Gutter

### PR DESCRIPTION
**Pull request by sey**
Please provide the following information:

 - Link to your code repository: https://github.com/sey/sublime-solium-gutter
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/sey/sublime-solium-gutter/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by joshua-golub** [comment]
@sey, a couple of things:

1. We really try to avoid having alpha-quality code in Package Control

2. What does "gutter" refer to? In an editor, "gutter" means something to me other than linting.

-Josh

**Comment by sey** [comment]
Thanks for your feedback. I totally understand your first point. This is now fixed.

Gutter means that the plugin uses the Sublime Text gutter next to the line numbers. I took example on the JSHint Gutter plugin that does the same for Javascript files. You can see what it does on the JSHint homepage (https://github.com/victorporof/Sublime-JSHint).
If you think it is better I can rename it (just Solium or Solidity Linter for example).

**Comment by joshua-golub** [comment]
Ok, I understand now why you used "Gutter". That's fine with me. I'll make one more pass through your package shortly.

**Comment by FichteFoll** [comment]
Can I just rant a bit about npm on why [this](https://github.com/sey/sublime-solium-gutter/blob/master/scripts/node_modules/ansi-regex/index.js) is a thing and not a part of [this](https://github.com/sey/sublime-solium-gutter/blob/master/scripts/node_modules/strip-ansi/index.js)?

**Comment by sey** [comment]
You can but no one will hear you here ;-).  
Though it may seem over engineered the ansi regex package may be used by different packages for different things. It makes sense to only write it once in my opinion.  
It's part of the Unix philosophy that each software should do only one thing and do it well.  
Thanks for the merge.

**Comment by FichteFoll** [comment]
I'm just gonna say "leftpad".

I prefer using proper (my own) judgement on whether or not a self-contained package would be better than collecting trivial parts from multiple locations, but that is subjective of course.

**Pull request merged**
