### PR TITLE
first plugin

### PR DESCRIPTION
**Pull request by ChengAnXu2014**
My first plugin

### CODE REVIEW

**Comment by ChengAnXu2014** [comment]
After so many days working, finally...

**Comment by ChengAnXu2014** [comment]
added version control

**Comment by ChengAnXu2014** [comment]
I've added license. Should I pull request again or just wait?

**Comment by braver** [comment]
Thank you for contributing a package! Some things we need to deal with here:

- Your PR now changes the entire k.json file. Probably because you changed the indentation. Please reduce the changes to just the addition of your package. 
- I don't understand, from looking at the README, what the intended use case is for this package. Maybe you could preface the README with some information about why someone would want to use this package?
- The description of your repository is "A Sublime Text 3 Plugin", which is probably correct, but also not helpful for understanding just what it does ;)
- You might want to have a look at the [scope naming guidelines](https://www.sublimetext.com/docs/3/scope_naming.html). If you adhere to these guidelines, it should not be necessary to modify a color scheme. You definitely want to support other color schemes as well, and you can probably do so without having to override them.

**Comment by ChengAnXu2014** [comment]
Thank you for reviewing my package and reminding me it's deficiencies. This is my first time to develop a ST3 package, to be honest, at the time I submitting this package, I was just giving it a try. 
My English is not good enough to make a perfect introduction for my package, and for the same reason, I can't expression how much I'm honored to receive this letter from you.
I will learn the docs and improve my package, this will take same time. Then I'll submit it again.
Again, thank you for your time.



--------------------------------
程安䋈ChengAnXu

----- 原始邮件 -----
发件人：Koen Lageveen <notifications@github.com>
收件人：wbond/package_control_channel <package_control_channel@noreply.github.com>
抄送人：程安絮 <hippyandy@sina.com>,  Author <author@noreply.github.com>
主题：Re: [wbond/package_control_channel] first plugin (#8109)
日期：2020年12月13日 02点53分


Thank you for contributing a package! Some things we need to deal with here:

Your PR now changes the entire k.json file. Probably because you changed the indentation. Please reduce the changes to just the addition of your package.
I don't understand, from looking at the README, what the intended use case is for this package. Maybe you could preface the README with some information about why someone would want to use this package?
The description of your repository is "A Sublime Text 3 Plugin", which is probably correct, but also not helpful for understanding just what it does ;)
You might want to have a look at the scope naming guidelines. If you adhere to these guidelines, it should not be necessary to modify a color scheme. You definitely want to support other color schemes as well, and you can probably do so without having to override them.

**Comment by braver** [comment]
#8130 replaces this PR.

**Pull request closed without merging**
