### PR TITLE
Add MochaBotcha package

### PR DESCRIPTION
**Pull request by tarjei**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The tests don't pass: https://packagecontrol.io/docs/submitting_a_package#Step_7

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by FichteFoll** [comment]
Also, what is the reason for this fork and why can't the changes be incorporated upstream?

**Comment by tarjei** [comment]
@FichteFoll Mocha and Jasmine are two different unit test systems with different syntax for how to handle asserts. 

Mocha uses:
`expect(foo).to.be.defined`
While Jasmine uses:
` exepect(foo).toBeDefined()`

So that's why :)

I'll get tagging. 

Tarjei

**Comment by FichteFoll** [comment]
Tests are still not passing.

https://packagecontrol.io/docs/submitting_a_package#Step_7

**Comment by FichteFoll** [comment]
@tarjei ping

**Comment by tarjei** [comment]
I'm sorry @FichteFoll I'll get on it. I just got swamped at work :(

2016-06-27 15:11 GMT+02:00 FichteFoll <notifications@github.com>:

> @tarjei <https://github.com/tarjei> ping
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/5521#issuecomment-228740843>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAM5P35OFaQfwBs-NJksgNdYWihvjgHPks5qP8vkgaJpZM4Igd-L>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by wbond** [comment]
@tarjei A reminder that this is still open 😄

**Pull request closed without merging**
