### PR TITLE
Add JunLang

### PR DESCRIPTION
**Pull request by lemonorangeapple**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is JunLang.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Any particular reason you want to ship this pre-packaged? Your syntax is missing the `.junlang` suffix on all the scopes. It's also so limited I am really curious as to what the language is actually like?

**Comment by lemonorangeapple** [comment]
It's a simple program language, like Pascal. So, how can this Pull Request be successfully merged? Add the `.junlang` suffix?

**Comment by braver** [comment]
>  Add the .junlang suffix?

Certainly, that for sure. I would also prefer simply adding the repository to the syntax as most other languages. That makes it easier for users to contribute to. I don't understand why you want a simple package like this to be shipped prepackaged. That's more typical for proprietary code, packages that need a build/compilation step, or companies wanting to manage several packages on their own.

**Comment by lemonorangeapple** [comment]
Maybe I added the suffix, I don’t know is it the suffix.

**Comment by lemonorangeapple** [comment]
Can it work successful now?

**Comment by lemonorangeapple** [comment]
@braver Can it work successful now?

**Comment by braver** [comment]
Please answer this question first:
> @braver
Collaborator
[braver](https://github.com/braver) commented [2 weeks ago](https://github.com/wbond/package_control_channel/pull/8820#issuecomment-1749527180)
Any particular reason you want to ship this pre-packaged?

**Comment by lemonorangeapple** [comment]
No. So can this package be can installed in Package Control?

**Comment by braver** [comment]
Sure it can, but preferable follow this example for how to add a syntax package:
https://github.com/wbond/package_control_channel/pull/8801/files

**Pull request closed without merging**
