### PR TITLE
added anaconda_go to the default channel

### PR DESCRIPTION
**Pull request by DamnWidget**
anaconda_go is a new full featured golang IDE like package for the anaconda plugins family

### CODE REVIEW

**Comment by DamnWidget** [comment]
I am wondering if there is any problem with this PR as it is taking really long to merge or comment anything on it.

**Comment by wbond** [comment]
No, there isn't anything wrong, it is just there are currently no volunteers helping with the review process. I usually spend 2-3 hours a week doing reviews. Unfortunately I haven't gotten to it this week yet due to the holiday yesterday.

**Comment by FichteFoll** [comment]
Your ToC in the readme appears to be very long. I suggest only indexing up to heading level 3.

I also suggest using relative imports (`from .lib import go`).

FYI, Package Control automatically makes its `package_control` module available for import to any package.

**Comment by DamnWidget** [comment]
Thanks @FichteFoll I will use the exposed `package_control` module in next release.

**Pull request merged**
