### PR TITLE
create package gototag

### PR DESCRIPTION
**Pull request by dclnet**
submit a package: gototag (quickly jump to any Tag location)

### CODE REVIEW

**Comment by dclnet** [comment]
fix the error

**Comment by FichteFoll** [comment]
Your package will be installed as "GotoTag", so [this hard-coded path](https://github.com/dclnet/gotoTag/blob/master/GotoTag.py#L8) will not work on case-sensitive filesystems. You may use the module-global `__package__` instead.

Instead of `currentLine.contains(regions[0]) or regions[0].contains(currentLine)` you can use `regions[0].intersects(currentLine)`.

Going to tag id 0 on `ctrl+alt+1` seems unintuitive.

**Comment by FichteFoll** [comment]
@dclnet ping

**Comment by dclnet** [comment]
Sorry, I was so busy that I forgot to reply to you.
I'll fix it later and submit it

**Pull request closed without merging**
