### PR TITLE
Add Kirikae

### PR DESCRIPTION
**Pull request by dvcrn**
Plugin to quickly jump between open tabs. Used to treat views as buffers similar to how vim / emacs handles them

### CODE REVIEW

**Comment by dvcrn** [comment]
Fixed the keybindings

**Comment by dvcrn** [comment]
Anything I can do to get this merged?

**Comment by FichteFoll** [comment]
How does it differ from the [fork origin](https://github.com/rajeshvaya/Sublime-Extended-Tab-Switcher)? Would it make sense to replace the old package with this one if it is actively maintained?

**Comment by dvcrn** [comment]
The main idea behind this fork is to correctly implement moving and manipulating of tabs independently of which group they are (if set) similar to how emacs/vim are handling things. For example, when the tab bar is hidden, all tabs can be treated as buffers (which is what I do). If I'm in group 2 but the tab I want to switch to is in group 1, it will get moved transparently to the current group and give focus. 

The fork also fixes the default keybindings and correctly implements previews of tabs on select in different groups (including the part/line that was in focus previously)

Since it's a fork, the core functionality is the same so I'd be ok with replacing the original but the vision I have is a bit more than just a tab switcher

**Comment by FichteFoll** [comment]
>I have is a bit more than just a tab switcher

With this and quite a bit of changed functionality, I guess it makes more sense to add it as a separate package instead of replacing the current one.

**Pull request merged**
