### PR TITLE
Adding QuickEdit

### PR DESCRIPTION
**Pull request by gamcoh**
I am creating a package that allows to edit css code directly into html code using the tag class names, like QuickEdit on the Brackets IDE.

### CODE REVIEW

**Comment by gamcoh** [comment]
i just added my first tag release, it should be good now

**Comment by gamcoh** [comment]
But i don't understand, i change the key binding, is there some kind of cache system or anything ?

**Comment by FichteFoll** [comment]
Instead of using `re.findall` and then only fetching the first element you might as well just use `re.search`.

Also, you should probably be using the first entry in `window.folders()` and combine paths with `os.path.join` instead of manually adding a platform-specific forward slash.

**Comment by gamcoh** [comment]
Thanks, i just fixed the bugs

**Pull request merged**
