### PR TITLE
Added Duotone Dark Red

### PR DESCRIPTION
**Pull request by DJgamer98**
A port of a colorscheme I once made for Atom.

### CODE REVIEW

**Comment by wbond** [comment]
You'll need a [semver](http://semver.org) tag at https://github.com/DJgamer98/Duotone-Dark-Red-Sublime/tags for this package to be installable.

Perhaps also put a screenshot in your readme?

**Comment by DJgamer98** [comment]
The semver tag is added. I'll see if I can make the screenshot later.

**Comment by FichteFoll** [comment]
Please remove the file `Duotone Dark Red.sublime-package`, it's redundant.

**Comment by DJgamer98** [comment]
Deleted the `Duotone Dark Red.sublime-package`

**Comment by FichteFoll** [comment]
And don't forget to push a new release by creating (and pushing) a new tag.

**Comment by DJgamer98** [comment]
Ah, whoops! Should be fixed now.

**Pull request merged**
