### PR TITLE
Add Brevis CSS Autocomplete

### PR DESCRIPTION
**Pull request by dlzi**

### CODE REVIEW

**Comment by Thom1729** [comment]
Does `self.data_completions` exist?

**Comment by dlzi** [comment]
It does. Plz check the line 9 of the code.

**Comment by Thom1729** [comment]
That initializes `class_completions`, not `data_completions`.

**Comment by dlzi** [comment]
Yeah.. you are right, sorry. Brevis CSS doesn't use data attributes, so I don't need data attribute completions. I just need classes.

**Comment by dlzi** [comment]
Fixed. Thank you for pointed that out.

**Pull request merged**
