### PR TITLE
B2 Jam Syntax Highlighting

### PR DESCRIPTION
**Pull request by mccann**
Add B2Jam project

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

My package is similar to ... However it should still be added because ...

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by mccann** [comment]
the .gitattributes question is unclear, should I remove the images that are included which are used by the README.md ?

**Comment by rwols** [comment]
You can omit anything that doesn’t contribute to the functioning of the sublime plugin. That probably includes images referenced in the readme.

**Comment by mccann** [comment]
> You can omit anything that doesn’t contribute to the functioning of the sublime plugin. That probably includes images referenced in the readme.

Great, done. Added .gitattributes with export-ignore for 'readme-imgs/'

**Comment by braver** [comment]
Very nice job sir 👍🏻

**Pull request merged**
