### PR TITLE
Adds the BetterJinja Package.

### PR DESCRIPTION
**Pull request by Ultra-Instinct-05**
This PR adds the [BetterJinja](https://github.com/Sublime-Instincts/BetterJinja) Package to Package Control.

This package provides syntax highlighting, snippets, completions & more for [Jinja2]() templates.

There is an existing package already which is [Jinja2](https://packagecontrol.io/packages/Jinja2), however the package hasn't been updated to keep up with latest syntax improvements via `.sublime-syntax` for ST3. So this package offers,
- An updated & tested syntax file which follows the official scope naming guidelines as closely as possible.
- Snippets for Jinja2 code blocks.
- Completions for built in tests, filters, functions & loop variables.
- Ability to have Jinja2 line & block comments.
- Certain key bindings to make life a little bit easier.

### CODE REVIEW

**Comment by braver** [comment]
Maybe @kudago isn't the one to ask about the takeover, @dy is the only member of that org. @everyonesdesign seems to be the maintainer for [Jinja​2](https://packagecontrol.io/packages/Jinja2). Guys, if no-one objects to @Ultra-Instinct-05 replacing your Jinja package with his, please do so within 2 weeks.

**Comment by everyonesdesign** [comment]
Hey, original Jinja2 package maintainer here. Sorry for not updating on the topic. I don't have resources to maintain the repo, neither have I worked with Jinja for a while. I also don't know what is the state of current Jinja extensions for Sublime Text.

If there's some organisational work I can help with, for which you need my owner's permissions, let me know. I don't have objections for adding another actively maintained package to PackageControl or, maybe, even replacing the original one with a better, newer version you have.

**Comment by braver** [comment]
Well the neatest way to deal with this is to allow @Ultra-Instinct-05 to work on the existing repository and just create new releases from there. Maybe you can invite him in as a contributor?

**Comment by everyonesdesign** [comment]
This is done, granted write access to @Ultra-Instinct-05 for the repo. 

However, also feel free to replace `Jinja2` package in Package Control to your actual repo instead, that would reflect organisation aspect of it better. Maybe, in some time package control maintainers will assist with that; it seems, though, that the process is very slow.

In the meantime, indeed, feel free to use the original repo for the updates/releases.

**Comment by braver** [comment]
Changes through package control do tend to have a bit of a delay. We do what we can.

Thanks for making the administrative changes. This makes the transition easier and will allow everyone to follow what’s happened. I’m closing this pull request. @Ultra-Instinct-05 I trust you can do what needs to be done now in the Jinja2 package repo.

Thanks everyone for cooperating here!

**Pull request closed without merging**
