### PR TITLE
Add Cup package for CoffeeScript integration

### PR DESCRIPTION
**Pull request by alin23**

### CODE REVIEW

**Comment by Thom1729** [comment]
- Why is `.no-sublime-package` set?
- The package is declared to be compatible with all versions of Sublime. You probably want to declare compatibility with 3092 and above.
- Conversely, why is the literate syntax a `tmLanguage`? If the package requires `sublime-syntax` anyway, you might as well convert it.
- What in the world is `sort.js` doing?

**Comment by alin23** [comment]
Hi @Thom1729, thank you taking the time to look into this ^_^

* I set `.no-sublime-package` because I'm executing `sort.js` using `node` and from what I understood I can't run scripts like that if the package is archived
* I fixed the compatibility declaration
* I got the literate syntax directly from the Better CoffeeScript package but I didn't make any changes to it so I forgot to convert it. I just did it.
* `sort.js` is a webpack bundled code that reads CoffeeScript code from stdin and outputs the code with the imports sorted. I uploaded the code here: [cup-import-sort](https://github.com/alin23/cup-import-sort)

**Comment by Thom1729** [comment]
Any luck with factoring out `sort.js`?

**Comment by Thom1729** [comment]
Is the `sort.js` file in the repo no longer needed?

**Comment by alin23** [comment]
Oh right, I forgot to delete it

**Comment by Thom1729** [comment]
Also, you should probably add a license.

**Comment by alin23** [comment]
Okay, I added a license. Is there anything more I should do before drafting a new release?

**Comment by Thom1729** [comment]
Looks good to me.

**Pull request merged**
