### PR TITLE
added goto folder package

### PR DESCRIPTION
**Pull request by screamingsnak3**

### CODE REVIEW

**Comment by screamingsnake** [comment]
It‘s been 10 days.. when will my package be published?

**Comment by wbond** [comment]
@screamingsnake The contributor who does almost all reviews is on vacation. My hope is to do some reviews this week, but my free time/open source time is pretty limited these days.

**Comment by FichteFoll** [comment]
You have two "Usage" sections in your readme.

The package is very similar to https://packagecontrol.io/packages/Open%20Folder. I suppose you could easily add this functionality to that package or replace it all together, if @mikepfirrmann is all right with that.

**Comment by screamingsnake** [comment]
okay.. 
take you one month to tell me that :D

**Pull request closed without merging**
