### PR TITLE
Publish the TypeScriptLang package

### PR DESCRIPTION
**Pull request by billti**

### CODE REVIEW

**Comment by wbond** [comment]
Hey @ericclemmons, it looks like Microsoft has a full fledged TypeScript package. Can we replace your current `tmLanguage` file with this package?

**Comment by wbond** [comment]
@billti You can remove the `"author"` and `"issues"` entries from the pull request since those will be automatically discovered via the `"details"` entry.

**Comment by billti** [comment]
Done.  Let me know if there are any problems with this update.  (I added the 'typescript' label also).

**Comment by wbond** [comment]
@billti Looks good to me. Let's hope we heard back an affirmative from @ericclemmons soon. I think it would be ideal to be listed as `TypeScript` instead of having that and `TypeScriptLang`, especially since this is up-to-date.

**Comment by billti** [comment]
@wbond Agreed.  Thanks!  @ericclemmons , let me know if there is anything I can help with.

**Comment by billti** [comment]
Ping...  @ericclemmons , any thoughts/decision on this?  We're getting issues about why we're not on package control yet (e.g. https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/107 ), and I'd love to get this done and published with a final name.

Seems the current `typescript` package hasn't been touched for a couple of years, and we'd love to get an up to date version be the most discoverable in Package Control.

**Comment by ericclemmons** [comment]
@billti:  I'm all for it!  Let me know what I can do to help facilitate this!

**Comment by billti** [comment]
@ericclemmons Great! Thanks so much!
@wbond Want me to update the pull request to remove my 'typescriptlang' addition and modify the current 'typescript' entry?

Thanks guys!

**Comment by ericclemmons** [comment]
What should I do with my repo?  I just put up a deprecation notice:
> https://github.com/ericclemmons/sublime-typescript

**Comment by billti** [comment]
@wbond What happens to existing users if we switch over the repo that name points to?  Do they get migrated automatically?  Or do they stay on the current package unless they uninstall/reinstall?

**Comment by billti** [comment]
I got excited when I saw this pull request gone from my GitHub landing page, but then realized its just because it's now outside the 7 day old window :disappointed: .

@wbond Any answers to the above? Anyone I need to buy a beer for? I'm happy to do what it takes to get this done.  Thanks.

**Comment by wbond** [comment]
Sorry @billti, been a little busy with things.

The correct course of action is now to adjust the PR to move your info over on top of the existing `TypeScript` entry. You should add some upgrade messaging (https://packagecontrol.io/docs/messaging)  to your repo for your initial version number that mentions replacing the previous package with the new official one. That way anyone who had the previous incarnation installed will see the message. Existing users who have left the Package Control setting `auto_upgrade` set to `true` will automatically be upgraded the next time they restart Sublime Text.

@ericclemmons, you can leave your repo up as long as you want. Once this PR is tweaked and merged, Package Control won't need it anymore.

**Comment by billti** [comment]
Thanks @wbond . No worries, I know how things get.

I've updated the pull request.  I've also updated our repo with a message.json and messages file per the link you gave, and tagged a new release.  So hopefully we're good to go!

Many thanks @wbond and @ericclemmons for your help with this.

**Pull request merged**
