### PR TITLE
add FindAndReplaceByProjectWithExclusions

### PR DESCRIPTION
**Pull request by Zlatov**
My first package.

### CODE REVIEW

**Comment by Zlatov** [comment]
I add license file to my git repo. This will automatically remove the warning or another pull request is needed?

**Comment by rwols** [comment]
You can request a new review from the packagecontrol-bot in the top right corner of this page.

I had a quick glance at your python script:

- You're using `window = sublime.active_window()`, but you can also access the window with `self.view.window()`.
- Don't load the project data with `open` and `json.load`. All the project data is already in `window.project_data()`.

**Comment by Zlatov** [comment]
@rwols, Thank you so much! I made edits!

Reading someone else's code is pretty hard, I am delighted and impressed!

**Comment by Zlatov** [comment]
Excuse me for the extra questions, but how long does it take? Or here the button "close the pull request" is unlikely.

**Comment by Zlatov** [comment]
@rwols, Good afternoon, I apologize for the unnecessary worries. How long will it take to make a decision on a request? Or maybe the system is waiting for me to act?

**Pull request merged**
