### PR TITLE
Added package LyxMath

### PR DESCRIPTION
**Pull request by rudvfaden**
A small package that add some convenient keyboard shortcuts when writing in latex

### CODE REVIEW

**Comment by FichteFoll** [comment]
What is this? Some made-up format?

https://packagecontrol.io/docs/submitting_a_package

**Comment by rudvfaden** [comment]
I tried to follow the instructions. Please let me know if I did something
wrong.

**Comment by rudvfaden** [comment]
Sorry. Figured it out.

**Comment by rudvfaden** [comment]
Sorry sorry sorry. Forgot to run the test script. Had some indentation issue. Should be fixed now.

**Comment by FichteFoll** [comment]
Yes, this looks good. However, you have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
`git tag 1.0.0` `git push --tags`

**Comment by FichteFoll** [comment]
See also the help page at https://github.com/rudvfaden/Sublime-LyxMath/tags. If you successfully pushed a tag, it should show up at said location.

**Comment by rudvfaden** [comment]
Thanks. It has been done.

On Fri, May 8, 2015 at 9:50 PM, FichteFoll <notifications@github.com> wrote:

> See also the help page at
> https://github.com/rudvfaden/Sublime-LyxMath/tags. If you successfully
> pushed a tag, it should show up at said location.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/4401#issuecomment-100339122>
> .
>



-- 
Rud

**Pull request merged**
