### PR TITLE
Add Registers package

### PR DESCRIPTION
**Pull request by BernardoAbreu**

### CODE REVIEW

**Comment by BernardoAbreu** [comment]
The keybindings for OSX were changed.

**Comment by Thom1729** [comment]
It looks like this won't work when installed. Instead of storing the “registers” in a JSON file inside the package, you should use the settings API.

**Comment by Thom1729** [comment]
@BernardoAbreu ping

**Comment by BernardoAbreu** [comment]
I updated the package to use the settings API instead.

**Pull request merged**
