### PR TITLE
Add Threejs Autocomplete package

### PR DESCRIPTION
**Pull request by wrbing728**

### CODE REVIEW

**Comment by wrbing728** [comment]
how long will it take to handle the pr on average please?

**Comment by Thom1729** [comment]
This is a fork of an existing package that's already listed in Package Control. Have you reached out to the original developer about adding features to that package?

**Comment by wrbing728** [comment]
This exist package(blackjk3/threejs-sublime) pushed the last commit 3 years ago, so i fork from it and try to upgrade some new ThreeJS properties

**Comment by Thom1729** [comment]
Have you reached out to the original developer about adding features to that package?

**Comment by wrbing728** [comment]
Actually nope.  I just created an issue to ask if he can continue to work for his package，but have not receive a reply.

**Comment by Thom1729** [comment]
You might even submit a PR with the changes you've made.

**Comment by wrbing728** [comment]
Yeah, maybe I should and I just submited a PR.   
By the way, what if there is still no reply？ How long should i keep waiting?

**Comment by wrbing728** [comment]
It seems like this package was not maintained any longer.   https://github.com/blackjk3/threejs-sublime/pull/6

**Comment by FichteFoll** [comment]
If the author is unresponsive, you may take over maintenance of the package entry on Package Control. Please submit a new PR or adjust this PR to change ownership of the existing package to yourself (and change the `details` url). While doing so, please also rename the package to not contain a period because those are known to cause issues and we'd like to make periods illegal in package names (#2524). Once you did that, we will give the current maintainer a response period of 2 weeks until which they can object to the change.

The changes in your PR are minimal, so users probably won't notice a change anyway.

**Comment by wrbing728** [comment]
I have change this PR as you said(the details url and package name),  is it all right?

**Pull request merged**
