### PR TITLE
Add Nova Color Scheme package

### PR DESCRIPTION
**Pull request by driesvints**
Please provide the following information:

 - Link to your code repository: https://github.com/driesvints/nova-sublime-text
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/driesvints/nova-sublime-text/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by driesvints** [comment]
[Nova](http://www.trevordmiller.com/nova/) is a color scheme and this package will allow ST users to install the ST theme easily. The ST package currently comes with a color scheme and will perhaps ship with a UI theme later as well.

**Comment by math2001** [comment]
You need to say how to install and activate the color scheme in your readme.

**Comment by driesvints** [comment]
@math2001 done!

**Comment by math2001** [comment]
@driesvints this is not a theme, it is a **color scheme**.

In your readme:

Activate the ~~theme~~ *color sheme* by adding the line below to your user preferences

Otherwise, your `readme` is good.

**Comment by driesvints** [comment]
@math2001 I've rephrased a bit in the readme. I'd like to keep the name of the package because I'm planning on adding a theme file as well. So the package name is ok imo but I've updated the install notes like you've suggested.

**Comment by FichteFoll** [comment]
Please don't wait too long with adding the theme.

**Comment by driesvints** [comment]
@FichteFoll thanks for merging!

**Pull request merged**
