### PR TITLE
eScript Syntax

### PR DESCRIPTION
**Pull request by sigmantium**
This package utilizes a few other existing packages and references are made to them in the readme.md file. However, this package is based around a pogramming language that was specifically written for a game server engine called POL for the game ultima online. This package includes, syntax highlighting, tooltips, autocompletes, code formatting and colours schemes consistent with others used within the community.

### CODE REVIEW

**Comment by sigmantium** [comment]
.no-sublime-package file used as tool tip system uses a database of files within the parent directory which might not be accessible if packed.

**Comment by Thom1729** [comment]
Instead of `open()`ing those files, can you use `sublime.load_resource()`?

**Comment by sigmantium** [comment]
> Instead of `open()`ing those files, can you use `sublime.load_resource()`?
Thanks @Thom1729 I've made the changes as suggested and done some testing.

**Comment by sigmantium** [comment]
Hi Guys,
Just bumping, hoping to get someone to review when they're available.
Thanks.

**Comment by FichteFoll** [comment]
Sorry for the long wait on this.

Don't use `logging.basicConfig` because it will configure the root logger and affect *all* plugins. Instead, create a logger for `logging.getLogger(__package__)`, which will be the name of your package and all loggers created from `__name__` will be under it. (Actually, you don't even seem to use the logging module since all references to it are commented.)

You seem to be using https://github.com/huot25/StyledPopup for your popups. I don't think that can handle the new `.sublime-color-scheme` format, FYI. You may find [mdpopups](https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fgithub.com%2Ffacelessuser%2Fsublime-markdown-popups) interesting, however.

**Comment by sigmantium** [comment]
Thanks @FichteFoll I've removed the debugging stuff for now and pushed a change.
I'm going to work on changing all the tooltips to being mdpopups as suggested, it does appear to be a much cleaner system. I'm wondering if the PR could be approved so that i can push it to my community without the need for people to manually maintain their repositories?

**Comment by FichteFoll** [comment]
My second note was optional, but the removal of `logging.basicConfig` was required. Since you did that, you only need to push a new tag with the latest commit and I can merge.

**Comment by sigmantium** [comment]
Thanks @FichteFoll i created the tag but forgot to create the release. This is now done.
Appreciate your assistance and pointing me in the direction of mdpopups.

**Pull request merged**
