### PR TITLE
Added ConvertKit Plugin

### PR DESCRIPTION
**Pull request by paschembri**
- [X] I'm the package's author and/or maintainer.
- [X] I have have read [the docs][1].
- [X] I have tagged a release with a [semver][2] version number.
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [X] My package doesn't add context menu entries. *
- [X] My package doesn't add key bindings. **
- [X] Any commands are available via the command palette.

My package is a plugin for managing ConvertKit tags

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by braver** [comment]
Thanks for your submission, some feedback:
- You don't provide any means of opening the settings file. You should create the command to open the settings file you mention in the readme, and create a main menu entry as well.

**Comment by paschembri** [comment]
Thanks for your feedback. I created an issue for my package (https://github.com/paschembri/convertkit_plugin/issues/1)

**Comment by braver** [comment]
Alright, let us know once you've handled it.

**Comment by braver** [comment]
I'm going to close this PR for now, we can reopen and resume when the feedback is handled.

**Pull request closed without merging**
