### PR TITLE
Submitting a Package

### PR DESCRIPTION
**Pull request by samsha1971**

### CODE REVIEW

**Comment by FichteFoll** [comment]
There is no need for your `.no-sublime-package` file, please remove it.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by samsha1971** [comment]
remove .no-sublime-package and add 1.0.0 tag.

**Comment by samsha1971** [comment]
removed .no-sublime-packag and added 1.0.0 tag.

2015-10-31 20:48 GMT+08:00 FichteFoll <notifications@github.com>:

**Comment by samsha1971** [comment]
removed .no-sublime-packag and added 1.0.0 tag.

**Pull request merged**
