### PR TITLE
Add Sequoia Studios package channel

### PR DESCRIPTION
**Pull request by alexggordon**
This adds the sequoia studios sublime package channel for DB1.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please do not use "packages_cache" and instead provide the information in "packages".

I should probably add tests for that, don't you think, @wbond?

Furthermore, if you structure the json file as intended and run the tests using the ChannelRepositoryTools package, you will notice that your "date" timestamps are badly formatted.

**Comment by alexggordon** [comment]
Heh, I actually did run the [tests](https://gist.github.com/alexggordon/49fc3ec9eddcbd6dde70), and no errors arose. In addition to that, I almost exactly followed the format [demonstrated](https://github.com/wbond/package_control/blob/master/example-channel.json) (notice the ```"packages_cache"``` json key there also) for schema version 3.0. 

However, after looking through the channels, I found [this example](https://csch1.triangulum.uberspace.de/release/packages.json) package channel that appears to be the model I should be following. I've updated my json to follow that example, which then caused the tests to fail. 

Either way though, I've corrected the date formatting!

**Comment by FichteFoll** [comment]
The problem here is that you are not providing a channel but a repository file, which does not have this key. (I know, the differentiation is counter intuitive.)

**Comment by alexggordon** [comment]
Gotchya. I understand now. The json file I'm submitting is the repository file, and I'm adding it to the channel. 

File has been updated!

**Pull request merged**
