### PR TITLE
new Color Scheme for sublime, your name is colorCode

### PR DESCRIPTION
**Pull request by vincenzopalazzo**

### CODE REVIEW

**Comment by Thom1729** [comment]
You don't need to specify `platforms`.

**Comment by vincenzopalazzo** [comment]
@Thom1729 I do remove the specific platforms?

**Comment by vincenzopalazzo** [comment]
@Thom1729 Sorry for my error, The referent os are removed

**Comment by Thom1729** [comment]
I didn't notice this before, but the package entry needs to go in `repository/c.json`, not in a new file.

**Comment by vincenzopalazzo** [comment]
@Thom1729 I not have understand the problem, what do have insert in the file 'c.json'?

I have following [this](https://packagecontrol.io/docs/submitting_a_package)

**Comment by Thom1729** [comment]
The *content* of your PR looks correct, but you need to put that into the `c.json` file (in alphabetical order, alongside the other packages).

**Comment by Thom1729** [comment]
That looks correct. I don't recall the exact internals of the PC semver implementation; you may need a third digit. A new tag “1.2.1” should do it.

**Comment by vincenzopalazzo** [comment]
@Thom1729 Sorry, how resolve a fix in my repository? [Click me](https://github.com/vincenzopalazzo/codecolor)

**Comment by Thom1729** [comment]
What is the purpose of the `.no-sublime-package` file? It seems unnecessary here.

**Comment by vincenzopalazzo** [comment]
Ok, I will remove he tomorrow

**Comment by vincenzopalazzo** [comment]
@Thom1729 I have remove file no-sublime-package, should be ok, right?

**Comment by Thom1729** [comment]
You need a new tag.

**Comment by vincenzopalazzo** [comment]
@I have fix the tag, [1.2.0](https://github.com/vincenzopalazzo/codecolor/releases/tag/1.2.0)

**Comment by FichteFoll** [comment]
The tag doesn't contain your latest commit https://github.com/vincenzopalazzo/codecolor/commit/023a2575a7d38520c9d76fdf5e81c0a05ae49f4c.

**Comment by vincenzopalazzo** [comment]
@FichteFoll fix, thanks

**Pull request merged**
