### PR TITLE
Add the Sqlx Builder plugin

### PR DESCRIPTION
**Pull request by taojy123**
sqlx is a extension for sql language (https://github.com/taojy123/sqlx)

this plugin will build sqlx script, and copy the result to clipboard

### CODE REVIEW

**Comment by FichteFoll** [comment]
I strongly suggest using ST's existing build systems, where you can use custom build commands by providing a `target` key in the `.sublime-build` file. See [the docs](https://www.sublimetext.com/docs/3/build_systems.html#advanced_example) for details.

Also, you shouldn't use assert statements for debugging because they will be stripped from plugins in a future ST build. If you want to verify input, raise errors/exceptions explictly.

**Comment by taojy123** [comment]
OK，thanks for your suggestion. 
I will improve my code and release a new version of the plugin.

**Comment by taojy123** [comment]
@FichteFoll , Hi, I have removed assert statements and released a new version.
https://github.com/taojy123/SublimeText-Sqlx/releases/tag/v1.0.2
😄

**Comment by FichteFoll** [comment]
You didn't do anything regarding the build system (and instead still have the context menu worlflow). This is quite unusual for packages and the proper solution would be integrating into ST's build system system, which is why I recommended that. Is there a particular reason why you're not doing that?

**Comment by taojy123** [comment]
Sorry，I am learning how to create a build system as a plugin. Need some time, I will update later.

**Comment by FichteFoll** [comment]
@taojy123 ping

**Comment by taojy123** [comment]
@FichteFoll 
Hi, I try to write build system, But I meet a problem. 
I don't know where `my_example_build.py` should put it ?
If put it to `Package/User/my_example_build.py` as  the docs say, it works. But I put it to plugin dir, it report `Unable to find target command: my_example_build` when `ctrl+b`

Could you help me? Thankyou

**Comment by taojy123** [comment]
Oh, I find!
Just put it to `Package/MyPluginName/my_example_build.py` 😂

**Comment by taojy123** [comment]
@FichteFoll 
I have completed the development of the build system, and release the newest version:
https://github.com/taojy123/SublimeText-Sqlx/releases/tag/v1.0.3

**Comment by FichteFoll** [comment]
Your 1.0.2 and 1.0.3 tags point to the same commit and there hasn't been a new one pushed to `master` in a month.

**Comment by taojy123** [comment]
Sorry, see `v1.0.4`
https://github.com/taojy123/SublimeText-Sqlx/releases/tag/v1.0.4

**Pull request merged**
