### PR TITLE
Added Commander package

### PR DESCRIPTION
**Pull request by TheDoctor0**

### CODE REVIEW

**Comment by FichteFoll** [comment]
How does this differ to [all the other "command" packages](https://packagecontrol.io/search/command)?

**Comment by TheDoctor0** [comment]
Most of them are not in active development for years now, additionally, some of them work only on UNIX based systems.
For now, it aims to make Composer/Laravel based web applications development in Sublime easier with the bundle of ready to use commands, still leaving an option to add any other commands you want to use.
In future, I want to add commands for npm, yarn, vuejs, django, git and more to cover the full spectrum of web development tools.

**Comment by FichteFoll** [comment]
Does "not in active development" mean they haven't been updated in a while or they are unmaintained and have open/unresponded issues?

I see that your package has a more application-specific focus and is less general, so I guess it qualifies at least as a specialization of the "external command" package type.

**Comment by TheDoctor0** [comment]
@FichteFoll, yes, there are many open issues on repositories for packages with kinda similar functionality:
1. https://github.com/markbirbeck/sublime-text-shell-command/issues
2. https://github.com/gbaptista/sublime-3-shell-exec/issues
3. https://github.com/misfo/Shell-Turtlestein/issues

Also, I assume you are right about the name.
I changed it to WebDevShell, it's now probably more appropriate.

**Comment by Thom1729** [comment]
Is the `WebdevshellCommand` constructor doing anything?

**Comment by TheDoctor0** [comment]
@Thom1729, I added it at the start because for some reason command arguments were not passed correctly - yeah, it was a dirty hack.
I checked now and it works fine without it, so I removed it permanently.

**Pull request merged**
