### PR TITLE
add perfectionist package

### PR DESCRIPTION
**Pull request by yisibl**
A Powerful Sublime Text plugin to beautify CSS!

https://github.com/yisibl/sublime-perfectionist

### CODE REVIEW

**Comment by princemaple** [comment]
did you mean https://github.com/yisibl/sublime-perfectionist ?

**Comment by yisibl** [comment]
Sorry, my mistake.

**Comment by princemaple** [comment]
I'm not an admin, just happened to see the PR and got interested by the package name.

**Comment by FichteFoll** [comment]
In the menu you use "CSS Perfectionist", which I personally would favor as a package name over just "Perfectionist" (keywords, etc.), but that's optional.

However, you'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by yisibl** [comment]
Fix.

If only `Perfectionist`, the user is not easy to enter and search.

**Comment by FichteFoll** [comment]
>If only Perfectionist, the user is not easy to enter and search.

That is a non-argument since typing "Perfectionist" will also match "CSS Perfectionist" just fine.

**Comment by yisibl** [comment]
So, now can you merge it?

**Comment by princemaple** [comment]
I'd +1 `CSS Perfectionist`. Just saying.

**Comment by FichteFoll** [comment]
>So, now can you merge it? 

I can.

**Comment by yisibl** [comment]
@FichteFoll What?

**Comment by princemaple** [comment]
@FichteFoll this guy obviously doesn't speak English as first language, hope you are not too offended. (saying that because I can tell from his email that he's from the same country as I am)

**Comment by yisibl** [comment]
@FichteFoll I'm so sorry, my English is too bad.

**Comment by FichteFoll** [comment]
>this guy obviously doesn't speak English as first language

Yes, I realize that. I'm not really offended by the comments, but reviewing packages is a pretty thankless task, so I can get a little bitter occasionally.

**Pull request merged**
