### PR TITLE
Added Rave to package control repo

### PR DESCRIPTION
**Pull request by chen36**
Package for Rave syntax and Rave evaluator.

### CODE REVIEW

**Comment by Thom1729** [comment]
Please fix the above error.

**Comment by Thom1729** [comment]
Instead of explicitly calling `read_settings`, I'd recommend loading the settings on plugin load:

```python
def plugin_loaded():
	global settings
    
    settings = sublime.load_settings(setting_file)
```

I would also recommend making `Evaluator` a `TextCommand` and then running `FetchRave` on that view, not on the view of the output panel. This avoids `active_view = self.view.window().active_view()`, which can be problematic if the user changes views.

As a totally optional suggestion, you might want to try [sublime_lib](https://github.com/SublimeText/sublime_lib)'s [OutputPanel](https://sublimetext.github.io/sublime_lib/modules/sublime_lib.output_panel.html) class:

```python
from sublime_lib import OutputPanel

panel = OutputPanel.create(window, "my_panel")
panel.show()
panel.print("Hello, World!")
```

**Comment by Thom1729** [comment]
@chen36 ping

**Comment by chen36** [comment]
Thank you so much for the recommendation, but unfortunately I will not be available for the improvement now. I will close the request first and reopen it once it is done.

**Pull request closed without merging**
