### PR TITLE
SphinxRefmate package added for consideration

### PR DESCRIPTION
**Pull request by phughes3866**
SphinxRefmate package is a reference manager/helper to aggregate and insert Sphinx Doc's project references (using restructured text).

### CODE REVIEW

**Comment by braver** [comment]
Please have a look at [our new checklist](https://raw.githubusercontent.com/wbond/package_control_channel/master/.github/PULL_REQUEST_TEMPLATE.md) and in particular the guidance around key bindings and the context menu.

**Comment by phughes3866** [comment]
Thanks @braver for the constructive suggestions. These have been acted upon and the SphinxRefmate repo updated, with a tag release, accordingly:
- Key bindings have been removed (replaced with Example.sublime-keymap file)
- Context Menu entry only appears in a restructuredText scope and can additionally be fully disabled via a settings entry
So back to you guys for reconsideration. Thanks.

**Comment by braver** [comment]
How does your package compare to https://packagecontrol.io/packages/Sphinx%20Ref%20Helper?

**Comment by phughes3866** [comment]
The SphinxRefmate package is more comprehensive and extensive than SphinxHelper in its aggregation of Sphinx project references:

- SphinxRefmate can aggregate multiple types of references (docs, section labels, glossary terms, citations), SphinxHelper focuses solely on docs.
- SphinxRefmate supports the insertion of references to other Sphinx Docs projects. SphinxHelper focuses solely on the currently active Sphinx Docs project.

SphinxRefmate's mode of operation, under the hood, is fundamentally different than SphinxHelper. SphinxRefmate compiles most of its lists of references by accessing internal Sphinx Docs project databases (objects.inv files), thus leveraging the power of Sphinx Docs own referencing system. SphinxHelper, on the other hand, compiles its list of doc-only references through the time consuming process of trawling directory trees for restructuredText files.

SphinxHelper can ably assist writers of single, small Sphinx Docs projects. It is simple to set up for this purpose.

SphinxRefmate will be useful to creators of Sphinx Docs projects who wish to reference more than just intra-project-docs. As it can perform more referencing tasks than SphinxHelper, it is more complex to set up.

If SphinxHelper is considered the penknife of Sphinx Docs reference helpers for Sublime Text, then SphinxRefmate is the Swiss Army Knife. Both are useful, dependant on your circumstances.

**Pull request merged**
