### PR TITLE
add C++YouCompleteMe plugin.

### PR DESCRIPTION
**Pull request by glymehrvrd**
I have written an plugin introducing some IDE C++ features to Sublime Text. Hopes to publish this plugin to repository channel.

### CODE REVIEW

**Comment by FichteFoll** [comment]
This looks like pure python to me and no other executables involved, which means your `.no-sublime-package` file is rather redundant. If you don't need it, please remove - or is there anything I missed?

**Comment by glymehrvrd** [comment]
@FichteFoll, it indeed needs other executables. Because the execuatables are platform-sensitive and I can't compile on each platforms, so I left this work to the users. `.no-sublime-package` is necessary, users need to put compiled component into the plugin folder before it works.

**Comment by FichteFoll** [comment]
Ah okay. This is not how you should handle this as the package directory is overwritten completely on each update (also by design). You should definitely use a different approach for users to specify the executables, e.g. by a setting variable.

**Comment by glymehrvrd** [comment]
Done. I didn't realize the folder will be completely overwritten on update. And I changed my plugin github addr to `CppYCM`.

**Pull request merged**
