### PR TITLE
re-add AlgoLang package now that is has been moved to github

### PR DESCRIPTION
**Pull request by qraynaud**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries.
- [x] My package doesn't add key bindings.
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme.
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is added to support syntax for an algorithmic language.

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by qraynaud** [comment]
I just added a LICENSE file!

**Comment by braver** [comment]
Oh, that's odd. Was the original entry removed? Is this just the same package but moved, or is there any change in content we should consider?

**Comment by braver** [comment]
Eh...

> Is this just the same package but moved, or is there any change in content we should consider?

**Comment by qraynaud** [comment]
Sorry, I missed your previous message. It’s the same content but moved.

**Pull request merged**
