### PR TITLE
Add Firebase Rules Syntax

### PR DESCRIPTION
**Pull request by jingyuexing**

### CODE REVIEW

**Comment by jingyuexing** [comment]
image

**Comment by braver** [comment]
Looks good in general but you'll want to look at the report from the bot. And maybe consider using `.gitattributes` to "export-ignore" the png from the final package to save on some storage and bandwidth.

**Comment by jingyuexing** [comment]
> Looks good in general but you'll want to look at the report from the bot. And maybe consider using `.gitattributes` to "export-ignore" the png from the final package to save on some storage and bandwidth.

already added `.gitattributes` file

**Comment by braver** [comment]
Having a LICENSE file is a recommendation, not a requirement. You can look into that in your own time. For now, let's 🚢

**Pull request merged**
