### PR TITLE
Add YardGenPlus to repository/

### PR DESCRIPTION
**Pull request by nimylian**
Yardgen, the package this is based on, isn't as customizable and the package is not represented on Github.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your keymap change has not been included in a tag yet. You also haven't updated the OSX bindings.

I suggest using a context and checking against `selector` instead of defining a global hotkey that will only do something inside a function definition.

What are the particular differences to [the original](https://packagecontrol.io/packages/yardgen)? Why can't you create a pull request against that instead of forking? cc @fappelman (hoping he sees this)

**Comment by fappelman** [comment]
I don't know about this version of Yardgen. If at some time there would be a pull request I would be happen to include the changes.

**Comment by FichteFoll** [comment]
Any update on this?

**Comment by nimylian** [comment]
I'll close this. I don't have the time to fight with the system.

**Pull request closed without merging**
