### PR TITLE
Add Coreboot Syntax package

### PR DESCRIPTION
**Pull request by ismell**
Add the coreboot syntax package. This package will contain syntax definitions that will make working on coreboot and the linux kernel more user friendly.

### CODE REVIEW

**Comment by braver** [comment]
The link in the repo description is a 404, I think it should be https://review.coreboot.org/admin/repos/sublime-text-coreboot-syntax.

You should publish a semver-numbered tag.

**Comment by ismell** [comment]
The repository description comes from out automated sync script. I've filed a bug to get that fixed. Ideally we could add Gerrit support to Package Control :)

I have pushed fixes for the README.md so it clarifies how to contribute and fixed the image. I also added a semver version tag. Let me know if there is anything else.

Thanks

**Comment by braver** [comment]
@ismell please have a look at what packagecontrol-bot has to say.

**Comment by ismell** [comment]
I had forgotten to push the new tag that had the LICENSE change. Can you run the builder again?

Thanks

**Comment by braver** [comment]
All green! Thanks!

**Comment by ismell** [comment]
Thank you!

**Pull request merged**
