### PR TITLE
added repository link for package Pointless

### PR DESCRIPTION
**Pull request by averynortonsmith**
This package provides syntax definitions and language support (commenting, auto-indentation) for the [Pointless](https://ptls.dev) scripting language.

### CODE REVIEW

**Comment by averynortonsmith** [comment]
@packagecontrol-bot

**Comment by FichteFoll** [comment]
@averynortonsmith ping

**Comment by averynortonsmith** [comment]
Sorry for the delay, I'm taking a look at the code right now. I'd like to see if I can resolve the testing error (even though the configurations seem to be working fine). Is the testing code that the bot is running available online?

**Comment by averynortonsmith** [comment]
@packagecontrol-bot

**Comment by averynortonsmith** [comment]
I've removed the redundant file extension definition to my repo and made a few tweaks. The repo is now passing the automated tests. I was being silly before and forgetting to update my package release version to make changes visible to the bot.

**Pull request merged**
