### PR TITLE
add sublime-gherkin-auto-complete

### PR DESCRIPTION
**Pull request by bubenkoff**

### CODE REVIEW

**Comment by FichteFoll** [comment]
@bubenkoff, you need to rebase onto current `master`.

@AndyHitchman, please acknowledge this addition.

**Comment by bubenkoff** [comment]
@FichteFoll done, sorry missed the origin initially

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

You will need @AndyHitchman's cooperation or fork the repo and push tags on your own.

**Comment by bubenkoff** [comment]
@FichteFoll thanks, i've changed to tags

**Comment by FichteFoll** [comment]
So I just found out that Gherkin = Cucumber, or similar, due to #2439. What happened with that?

How does this package compare to https://packagecontrol.io/packages/Cucumber and https://packagecontrol.io/packages/Cucumber%20Completion?

**Comment by bubenkoff** [comment]
cucumber-completion (the second link) is too cucumber specific
about the first link (the bundle) - i've also prepared PR there, to merge
plugin into the bundle
So if you have strong opinion it's too much for gherkin to have few
plugins, i can cancel this PR

On 12 January 2015 at 02:10, FichteFoll <notifications@github.com> wrote:

> So I just found out that Gherkin = Cucumber, or similar, due to #2439
> <https://github.com/wbond/package_control_channel/pull/2439>. What
> happened with that?
>
> How does this package compare to
> https://packagecontrol.io/packages/Cucumber and
> https://packagecontrol.io/packages/Cucumber%20Completion?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/3989#issuecomment-69521244>
> .
>



-- 
Anatoly Bubenkov

**Comment by AndyHitchman** [comment]
I like it and I've merged the PR from @bubenkoff  onto https://github.com/AndyHitchman/sublime-gherkin-auto-complete.
As noted above, this was previously rejected due to conflict/confusion with existing plugins.

**Comment by FichteFoll** [comment]
If you say that cucumber-completion is too cucumber-specific then so be it. I don't know enough about this to have an opinion of my own.

**Pull request merged**
