### PR TITLE
added haxelang (barebones haxe language support)

### PR DESCRIPTION
**Pull request by ix**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

However, it seems you are already pushing tags, so you just need to change it in the pull request.

Usually we are against duplicated functionalit in the package list, but you are right in that the original Haxe package is quite loaded compared to yours, so I guess that's okay. I suggest you to include the original package's `LICENSE` though.

**Comment by ix** [comment]
alright then, will do

**Comment by ix** [comment]
hmm, it doesn't seem like i can change the branch comparison. i'll open a new pr

**Comment by ix** [comment]
so, like this?

**Comment by FichteFoll** [comment]
Exactly.

cc @clemos btw

**Pull request merged**
