### PR TITLE
Added Copy Filename package

### PR DESCRIPTION
**Pull request by shivapoudel**
Previously there is a package Copy File Name just above of this package configs which works on Sublime Text - 2 and hasn't been updated for last 2 years and PR was not reviewed since 2014. So I have created this package. Please have a review and give it a merge.
This is my first package volunteered if something is missing and let me know xD

This works on Sublime Text - 3 ;)

@wbond Reference #4650

### CODE REVIEW

**Comment by FichteFoll** [comment]
1. Remove `package-metadata.json`, it is supposed to be created by Package Control on installation.
2. Remove `.no-sublime-package`, you don't need it and it limits override capabilities.
3. Your changelog seems ... wrong?
4. This is the same functionality as https://github.com/nwjlyons/copy-file-name, except that places the menu item at a different location and has not been flagged to support ST3, even though it does. cc @nwjlyons

**Comment by shivapoudel** [comment]
@FichteFoll above listed 1, 2 & 3 are solved:
https://github.com/shivapoudel/sublime-copy-filename/commit/6f7ef512f39f00eee447c6b23d9c9269ba059ac8
https://github.com/shivapoudel/sublime-copy-filename/commit/7068511e4c7644ab15d7708075451ab74cc7b2cf

**Comment by shivapoudel** [comment]
@FichteFoll ping :)

**Comment by FichteFoll** [comment]
What about 4.?

**Comment by shivapoudel** [comment]
@FichteFoll I got confused what you mean to say in 4. Please can you explain briefly :worried:

**Comment by FichteFoll** [comment]
I mean that there already is a package that provides the exact same functionality. You probably only missed it because it has not been flagged to support ST3 (because it is older than ST3), but it should work perfectly fine.

I would rather just flag the existing package as ST3-compatible than add another package with the same functionality.

**Comment by shivapoudel** [comment]
@nwjlyons unfortunately I am really very very sorry to remove that package. Because the `Sid Bar.sublime-menu` is annoying because its not working perfectly.

**Comment by shivapoudel** [comment]
I am sorry but since there is no any updates to that previous package I have to solve 4 by removing previous package. Can you please give this a merge. @nwjlyons if we are going to do wrong then just ping and say to stop us.

@FichteFoll can you fix this conflict and give a merge as we need this feature badly in our team members with keymap enable. Otherwise we have to copy file path and only copy basename which is time consuming.

**Comment by nwjlyons** [comment]
Is the problem here a namespace issue?

I think all I need to do is update the package_control_channel to specify my package works with ST3. I can do that in the next few days.

**Comment by shivapoudel** [comment]
@nwjlyons I will send some PR for you package tonight :)

**Comment by FichteFoll** [comment]
Exactly, @nwjlyons. I will close this PR then.

**Pull request closed without merging**
