### PR TITLE
Switch Test Double package to use tags

### PR DESCRIPTION
**Pull request by rosston**
I'd like to switch this package to using tags. The "ChannelRepositoryTools: Test Default Channel" command in Sublime Text passes.

Note that [master](https://github.com/testdouble/sublime-test-double/tree/master) is even with [0.0.1](https://github.com/testdouble/sublime-test-double/tree/0.0.1) (the [only tag](https://github.com/testdouble/sublime-test-double/tags)), so there will actually be no changes.

### CODE REVIEW

**Comment by braver** [comment]
Sure, good idea. Are you active in that project, or is someone in the testdouble team who can confirm the change?

**Comment by rosston** [comment]
@braver Good question! I just realized that my membership in the testdouble org wasn't publicly visible. I now show up on https://github.com/orgs/testdouble/people.

I'll also go ahead and ping @searls to confirm this change, as he's [the only one who has committed that repo](https://github.com/testdouble/sublime-test-double/commits/main) and he's in the testdouble org as well.

**Comment by searls** [comment]
Can confirm, @rosston is authorized to do this!

**Comment by braver** [comment]
Excellent!

**Pull request merged**
