### PR TITLE
Added React Snippets.

### PR DESCRIPTION
**Pull request by jeantimex**
The package provides modern React code snippets for writing React components, lifecycle functions and test cases faster. A lot of developers are using enzyme and chai to write React test cases, the snippets provide include them by default. Also We try to keep the commands as short as possible. Tested on ST2 and ST3. Please let me know if you see any issue, thanks a lot!

### CODE REVIEW

**Comment by FichteFoll** [comment]
What are the relevant differences to the [other packages](https://packagecontrol.io/search/react)? Also, please choose a more distinct name.

**Comment by FichteFoll** [comment]
@jeantimex ping

**Comment by jeantimex** [comment]
Hi @FichteFoll, sorry for the late reply! I guess the big difference is that my snippets include React test case snippets, Redux and Action, and they are quite essential in React development. Also my snippets all start with `r` which is much easier to list all react-related snippets. Regarding the name of this package, how about React Development Snippets? Thanks a lot mate!

**Comment by FichteFoll** [comment]
Yes, that name is better.

**Comment by jeantimex** [comment]
Thanks @FichteFoll! I've updated the project name to React Development Snippets. Please let me know if there's any issue, cheers!

**Comment by jeantimex** [comment]
Hi @FichteFoll, since this will be my first time contribute to the package control community, is there any document (for this project) I need to prepare? The reason I ask is that I see other projects have informative description on their package control page, just wondering how to write, thanks a lot!

I will continue to make this project better by providing more useful snippets. :)

**Comment by FichteFoll** [comment]
The information displayed on the packagecontrol.io website is sourced from your readme, so you don't have to do anything else.

[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by jeantimex** [comment]
Thank you so much!

**Comment by jeantimex** [comment]
Hi @FichteFoll, is there any update on this pull request? :)

**Comment by FichteFoll** [comment]
You still don't have a valid [semantic version](http://semver.org/) tag on your repo.

**Comment by jeantimex** [comment]
Sorry about that and thanks a lot for let me know! I just fixed a bug and pushed a new release v3.0.1 on my repo.

**Pull request merged**
