### PR TITLE
add jstl language syntax

### PR DESCRIPTION
**Pull request by eparisio**
added basic support for jstl syntax highlight

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by eparisio** [comment]
i've edit the file to refer a tag

**Comment by FichteFoll** [comment]
Semantic versions have three numeric parts.

**Comment by eparisio** [comment]
it should be ok now!

**Pull request merged**
