### PR TITLE
Add crollow

### PR DESCRIPTION
**Pull request by purefan**
Source at: https://github.com/purefan/crollow
[v1.0.0](https://github.com/purefan/crollow/releases/tag/1.0.0)

Checklist:
- [x] Used tags: true
- [x] Ran the tests

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for crollow #################################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 4 failures:
- '.sublime-workspace' files contain session data and should never be submitted to version control
    File: crollow.sublime-workspace
- The binding ['ctrl+shift+l'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap
- The binding ['ctrl+shift+l'] unconditionally overrides a default binding
    File: Default (Linux).sublime-keymap
- The binding ['super+shift+l'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by math2001** [comment]
Just a little GitHub's markdown tip:

```
[Y] Used tags: true
[Y] Ran the tests

- [x] lorem
- [ ] ipsum
```

does this:

[Y] Used tags: true
[Y] Ran the tests

- [x] lorem
- [ ] ipsum

**Comment by FichteFoll** [comment]
You haven't pushed a new tag with your changes yet.

**Comment by math2001** [comment]
You can remove this in your `c.json`: `"platforms": ["osx", "windows", "linux"]`

**Comment by FichteFoll** [comment]
@math2001 I stopped asking PR authors to do that since we can easily batch-remove them with all the other default values that people provide, should we ever get to do that. See also https://github.com/wbond/package_control_channel/issues/4310.

**Comment by math2001** [comment]
So, has that formater been written yet? But thanks for the info & initiative 👍

**Comment by FichteFoll** [comment]
No, otherwise that issue would have mentioned it and it would be included somewhere in this repo.

**Comment by purefan** [comment]
@FichteFoll You're right of course, I've done it now

Source at: [https://github.com/purefan/crollow](https://github.com/purefan/crollow)
[v1.0.1](https://github.com/purefan/crollow/releases/tag/1.0.1)

Checklist:

- [x] Used tags: true
- [x] Ran the tests
- [x] Fixed errors from [comments](https://github.com/wbond/package_control_channel/pull/6061#issuecomment-272759048)

**Pull request merged**
