### PR TITLE
Added a new package https://github.com/noanabeshima/sublime_codex

### PR DESCRIPTION
**Pull request by noanabeshima**

### CODE REVIEW

**Comment by noanabeshima** [comment]
Hi, I'm confused about how my PR failed a review test; does anyone know what this error means?
https://github.com/wbond/package_control_channel/pull/8354/checks?check_run_id=3584139879

I notice that this PR also has this error: https://github.com/wbond/package_control_channel/pull/8358

**Comment by finitelife** [comment]
> Hi, I'm confused about how my PR failed this review test; does anyone know what this error means? https://github.com/wbond/package_control_channel/pull/8354/checks?check_run_id=3584139879
> 
> I notice that this PR also has this error: #8358

I just checked against multiple other PRs after adding another commit on my (the aforementioned PR)... I can't see any reason why these are failing based on the contents of the PRs or the associated repos.

**Comment by rchl** [comment]
You can try requesting review again from the review bot.

**Comment by braver** [comment]
I'm sorry this has sat here for so long. 

The bot failed because there is no tag in the repository. You could have a look at our [pull request template](https://github.com/wbond/package_control_channel/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for a list of things to check when submitting a package.

Currently there already is a package to interact with Codex in package control: https://packagecontrol.io/packages/CodexAI. Although that seems to be linux-only. You might be able to contribute to that package. 

Let us know if you want to re-open this PR to re-consider your submission.

**Pull request closed without merging**
