### PR TITLE
Submitted the Git Interactive Rebase package.

### PR DESCRIPTION
**Pull request by tdd**

### CODE REVIEW

**Comment by vovkkk** [comment]
@tdd hey that’s cool how about that https://github.com/adambullmer/sublime_git_commit_syntax/pull/1
I mean keep all related syntaxes in one package, collaboration and all

cc @adambullmer

**Comment by tdd** [comment]
Hey that's actually quite cool, I'd be all for it, but this hasn't been merged for 2+ months now… Also, if we're all about aggregating stuff:

1. The main package's name isn't relevant anymore
2. We might want to merge [GitConfig](https://github.com/robballou/gitconfig-sublimetext) as well…

**Comment by vovkkk** [comment]
Here we go https://github.com/textmate/git.tmbundle speaking of all-in-one package, I didn’t know about that one. But I don’t like their rebase defenitions, too simplistic.
Speaking of my pr, I don’t remember for sure, but probably I saw @adambullmer’s pr in this repo and thought how about rebase? since I don’t commit via ST but rebase usually only via ST, so I’ve made pr into his repo, but he probably disable email notifications or something.

So I dunno what we going to do? If you @tdd want create all-in-one elaborated package with all syntaxes, I’d like to help.

**Comment by tdd** [comment]
Hey,

We could def do that at some point, for sure.

I'm quite overloaded right now, and fired this one off as a quickie. 
But we can definitely set up a package with a proper name, grab Adam's 
Git message code (with proper credits, of course), add your rebase code, 
perhaps grab Git Ignore and Git Config from their usual package(s), and 
wrap it all up in, say "Git Syntaxes" or something?

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Comment by FichteFoll** [comment]
https://github.com/kemayo/sublime-text-git has some as well.

I also propose a "Git Syntaxes" (or similar) package that includes all relevant syntax definitions for working with git. That in mind, I suggest we close this issue and you open a new pull request with the new package once it's done? Please reference this issue numbere there.

**Pull request closed without merging**
