### PR TITLE
Add New Moon Theme

### PR DESCRIPTION
**Pull request by taniarascia**
[Originally for Brackets](https://github.com/taniarascia/new-moon), now on Sublime by [popular demand](https://github.com/taniarascia/new-moon-sublime).

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by taniarascia** [comment]
Hello,

I added the tag, with version 1.0.0, to my repo.

**Comment by FichteFoll** [comment]
Also, something that I just noticed but is rather important: The package name is misleading. "Themes" are something different in Package Control, which you also seem to know since your labels only contain "color scheme". Please rename the package to read "Color Scheme".

**Comment by taniarascia** [comment]
Thanks for letting me know; that was definitely unintentional and due to ignorance. I fixed it!

**Pull request merged**
