### PR TITLE
Add 'Angular2 Snippets' package

### PR DESCRIPTION
**Pull request by evanplaice**
New snippets package.

This PR has been tested and verified via ChannelRepositoryTools

### CODE REVIEW

**Comment by FichteFoll** [comment]
As with the other two packages, https://github.com/wbond/package_control_channel/pull/5477 https://github.com/wbond/package_control_channel/pull/5480, what are the differences to the other angular packages? Is it just the angular version?

If so, I will only accept one out of the three packages. By default, we operate on first come first serve, so @pjlamb12 would get the pass. @evanplaice and @orizens, please consider contributing to that package or engaging in a discussion if you are unsatisfied with that package's direction.

**Comment by orizens** [comment]
my package follows john's papa snippets convention (triggers and actual templates).
It is to be displayed in angular.io documentation style guide page.

**Comment by FichteFoll** [comment]
@orizens, I'm not familiar with angular, so I'm afraid you need to elaborate on that.

**Comment by orizens** [comment]
@FichteFoll I'm referring to the snippets described [in angular.io style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#appendix)
It follows the standards and recommendations of the angular team.
My repository is in [PR](https://github.com/angular/angular.io/pull/1328) for this website

**Comment by evanplaice** [comment]
@FichteFoll Here's the 'skinny'. The sudden uptick in interest in submitting a snippets package is due to ngconf, which took place 2 weeks ago.

The package I submitted was developed alongside the community style guide before it was absorbed as the 'official' style guide. Ref mgechev/angular2-style-guide/issues/15

The snippets provided by @pjlamb12 and @orizens are reimplementations of [John Papa's vscode snippet](https://github.com/johnpapa/vscode-angular2-snippets) repository. Which is very useful for users who are just getting started with Angular2.

This package provides more extensive API coverage, makes fewer assumptions, and favors breaking the syntax down into smaller more granular code completions wherever possible.

I'm not keen on getting into an ego driven pissing contest. If name collision is the issue, I can resubmit my PR under the name `ng2-snippets`. Package Control already has 2 snippets packages for Angular1 (ie 'AngularJS-Snippets' and `ng2-snippets`). IMHO, a little variety doesn't hurt. If you agree that this is a reasonable compromise, I'll resubmit the PR with the change.

Thank you for your time and patience.

**Comment by orizens** [comment]
hi. 
perhaps there's a room for both. 
so, actually the package's name should note which style guide it reflects - "john papa" or "minko gechev".

**Comment by FichteFoll** [comment]
If there are two different snippet styles, one for experienced users with more control and one for beginners, that's fine. However, as you already mentioned, @evanplaice, the names are too similar currently. I like @orizens' proposal of adding the names to the packages which is more transparent and offers more information when browsing the package list.

As such, I propose the following:

1. Rename this package to `Angular2 Snippets (Minko Gechev)` (or alternatively `ng2-snippets`)
2. Reject @orizens' package since he submitted his later than @pjlamb12.
3. Rename @pjlamb12's package to `Angular2 Snippets (John Papa)`

This could also be `Angular 2` with a space. Idc about that. Could also add a "style" to the parentheses.

**Comment by pjlamb12** [comment]
While I don't see how snippets can be that different, and how one can be more along the style guide than the one that is based on the style guide author's own snippets, I have changed the name of my package to "Angular 2 Snippets (John Papa)" as suggested so that this process can move on and be added to package control. https://github.com/wbond/package_control_channel/pull/5477

**Comment by FichteFoll** [comment]
@evanplaice ping

**Pull request closed without merging**
