### PR TITLE
Update to mivascript plugin

### PR DESCRIPTION
**Pull request by zquintana**
Added support for SublimeText 3

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your fork is outdated.

**Comment by zquintana** [comment]
Not sure why build failed, but updated my fork with from the master fork.

**Comment by zquintana** [comment]
I fixed the issue, I'll close this request and submit a new request.

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

**Pull request merged**
