### PR TITLE
Add Hound Search

### PR DESCRIPTION
**Pull request by bgreenlee**
adding Hound Search plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
Specifying a branch for releases has been deprecated and is not accepted for new packages anymore.

By the way, I would not like my double click to be overridden by a plugin *that doesn't even mention this*.

**Comment by bgreenlee** [comment]
I'll document the double-click behavior, and specify how to remove it. It does not interfere with the default Sublime double-click, as that gets passed on. It is only a problem if there are other plugins that use double-click (AFAIK, there's no way around that currently)

**Comment by bgreenlee** [comment]
My solution, btw, was to make the double-click handling off by default, toggleable by a user setting: https://github.com/bgreenlee/SublimeHound/commit/c4c6acda3ac0bc241ae2e00c3f227e9ce94d9948

**Comment by FichteFoll** [comment]
If it doesn't interfere with the default implementation (didn't check if it was forwarded) it would probably be okay then, but a short mention of this would be nice.

Either way, the current way of just copying the file won't do since ST3 does not require extracted packages anymore and PC uses that. You'd need the `sublime.load_resource` API to get the virtual file's contents, but it only exists on ST3. Furthermore, you need to create the folder since it won't exist on first install. A way around this is to provide a `.no-sublime-package` file in your repo which instructs PC to manually unextract your package, but this is not desireable as the end user loses out on the overriding feature and should only used if necessary or really inconvenient otherwise.

**Comment by bgreenlee** [comment]
Arg. Thanks. Sounds like I have no good options to allow the user to be able to enable/disable double-click functionality, then.

**Comment by bgreenlee** [comment]
Ok, back to a default mousemap, but well-documented.

**Pull request merged**
