### PR TITLE
Add Bow Tintin package

### PR DESCRIPTION
**Pull request by papac**
This package brings syntax highlighting support for [Tintin](https://github.com/bowphp/tintin) https://github.com/papac/bow-tintin-sbt3.

### CODE REVIEW

**Comment by Thom1729** [comment]
It looks like this PR unintentionally changes the `Bower` channel entry.

**Comment by papac** [comment]
I do not have too much information about what produces this.

Here is what I added:

```json
{
  "name": "Bow Tintin",
  "details": "https://github.com/papac/bow-tintin-sbt3",
  "labels": ["php", "Bow", "Tintin", "language syntax", "Bow Tintin"],
  "author": "Papac Dev",
      "releases": [
	{
	   "sublime_text": "*",
	    "branch": "master"
	}
  ]
},
{
   "name": "Bower",
   "details": "https://github.com/benschwarz/sublime-bower",
   "releases": [
       {
	   "sublime_text": ">=3103",
	   "platforms": ["linux","osx","windows"],
	   "branch": "master"
	}
   ]
},
```

**Comment by papac** [comment]
I have resolve the problem.

**Comment by Thom1729** [comment]
What's the purpose of the `package.json` file?

`Comments.tmPreferences` should probably be renamed `Bow Tintin.tmPreferences` to avoid confusion.

What's the PHP file for? If it's a test to make sure the syntax it working, you might want to make it a full-fledged [syntax test](https://www.sublimetext.com/docs/3/syntax.html#testing).

**Comment by papac** [comment]
- The purpose of package.json is to help me to know the information of my package in your packages lists. But i remove it.
- I rename `Comments.tmPreferences` to `Bow Tinitin.tmPreferences`
- I have install localy the package, so i use the `test.tintin.php` file to look the syntax.

**Pull request merged**
