### PR TITLE
K_Highlighter_Teo

### PR DESCRIPTION
**Pull request by TeodorPloae**
A K Syntax highlighter for Sublime Text 3

### CODE REVIEW

**Comment by TeodorPloae** [comment]
There is no tmLanguage file because it's not needed. I'm using a sublime-syntax file with a tmTheme file to declare the needed scopes for coloring. 

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 7, 2018 at 14:43, Package Control Bot<notifications@github.com> wrote:   
@packagecontrol-bot commented on this pull request.

Automated testing result: WARNING

Repo link: K Framework Syntax Highlighter TeodorPloae
Results help
Packages added:
  - K Framework Syntax Highlighter TeodorPloae

Processing package "K Framework Syntax Highlighter TeodorPloae"
  - WARNING: '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
    - File: K_Syntax.sublime-syntax

**Comment by TeodorPloae** [comment]
There is no tmLanguage file because it's not needed. I'm using a sublime-syntax file with a tmTheme file to declare the needed scopes for coloring.

**Comment by Thom1729** [comment]
It's complaining because you're declaring support for `"sublime_text": "*"`. Change it to `"sublime_text": ">=3092"` and it will be fine.

**Comment by evandrocoan** [comment]
For reference, duplicate of: https://github.com/wbond/package_control_channel/pull/6866

**Pull request closed without merging**
