### PR TITLE
Added VEX package

### PR DESCRIPTION
**Pull request by teared**
Houdini VEX language definition, syntax highlighting and autocompletions for Sublime Text editor.

### CODE REVIEW

**Comment by FichteFoll** [comment]
How does this compare to https://packagecontrol.io/packages/VEX%20Syntax?

**Comment by teared** [comment]
This one is pretty experimental - I'm still working on it and plan to make a plugin with a small set of tools working with whole application, while some people may want only the language definition.

**Comment by FichteFoll** [comment]
Please report back once that is the case.

**Comment by teared** [comment]
I'll create a new request later.

**Pull request closed without merging**
