### PR TITLE
added MarkdownFootnotes plugin to repository

### PR DESCRIPTION
**Pull request by classicist**
I'd like to add my plugin to package control. Thanks!

### CODE REVIEW

**Comment by FichteFoll** [comment]
`alt+f` opens the file menu in the main menu. Please choose a different one.

**Comment by classicist** [comment]
Thanks for the catch. I updated it to ctrl+f instead. I looked around and this did not seem to be mapped to anything native to Sublime Text 3.

**Comment by FichteFoll** [comment]
That may be the case for OSX, but on the other two platforms this opens the find panel.

**Comment by FichteFoll** [comment]
@classicist ping

**Comment by classicist** [comment]
too true.

I just updated Windows and Linux short keys to ctrl+alt+super+f.

Thanks for the ping.

Paul

**Comment by FichteFoll** [comment]
Remember to push a new tag when making a release.

**Pull request merged**
