### PR TITLE
Added ChatGPT Package

### PR DESCRIPTION
**Pull request by eusonlito**
Related package https://github.com/eusonlito/Sublime-Text-ChatGPT

- [X] I'm the package's author and/or maintainer.
- [X] I have have read [the docs][1].
- [X] I have tagged a release with a [semver][2] version number.
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [X] Any commands are available via the command palette.
- [X] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by eusonlito** [comment]
@packagecontrol-bot Please :)

**Comment by braver** [comment]
To start with, your readme could do with some more explaining of what your package does, how to use it, maybe example use cases etc.

Also, the template for pull requests contains some points about not shipping key bindings, and about putting commands in the command palette… maybe revisit those, or expand on why you chose differently.

**Comment by eusonlito** [comment]
Ok, sorry then...

I was searching by ChatGPT and doesn't return any results...

I have tried to install the OpenAI package but...

```
Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:657))) downloading https://codeload.github.com/yaroslavyaroslav/OpenAI-sublime-text/zip/1.1.1.
error: Package Control

Unable to download OpenAI completion. Please view the console for more details.
```

It's my first package and I'm a bit confused 😅

Do you think that my package should be discarded?

Thanks!

**Comment by eusonlito** [comment]
Updates:

* Removed default Key Bindings
* Added settings comments
* Updated README
* Improved `Package Settings` > `ChatGPT` > Menu

**Comment by rchl** [comment]
To be fair, the other package is exactly the same thing (even if it doesn't include ChatGPT word in it). So I think per our policy we shouldn't accept it.

Also this package is lacking a bit in some ways. For example:
 - the requests are blocking (made on main thread) so the UI will be blocked until the request completes,
 - the menu entries for key bindings and settings use ST2-style where the default and user files are opened separately. This is inconvenient and not recommenced anymore since ST2 is long gone.
 - The other package has quite a bit of extra functionality, just by quick look at its settings and code.

**Comment by rchl** [comment]
We could add a chatgpt tag to the other package to improve discoverability.

**Comment by rchl** [comment]
> I have tried to install the OpenAI package but...

Sounds like an issue with Package Control in general in your installation and not specific to the package you were trying to install. Probably will get the same issue with most other pacakages.

**Comment by eusonlito** [comment]
Ok, thanks anyway.

I will continue to use my package by manual installation because I don't want to write in the editor to use the ChatGPT.

I have updated my code to open settings and key bindings in split view.

Also added comments on settings and some other improvements.

I will add also the request worker to avoid ui blocks.

Closing PR :)

Thanks!

**Comment by eusonlito** [comment]
Also added non-blocking requests :)

**Comment by rchl** [comment]
Is there something about the other package that makes you not wanna use it? Curious why do you prefer maintaining your own.

**Comment by eusonlito** [comment]
I have no idea as use it 😅

No Key Bindings explanation, or execute menu...

README say:

> Open the command palette and run the OpenAI Append, OpenAI Insert, or OpenAI Edit command.

I execute:

```
>>> OpenAI Append
  File "__main__", line 1
    OpenAI Append
           ^
SyntaxError: invalid syntax
```

Is the first package that I don't know how to execute 🥲

My Plugin include the `Open Command Palette` option on Package Settings Menu, also, the README link.

Maybe it's just me 🤷

Thanks for your concern.

**Comment by rchl** [comment]
The command palette is what you trigger with ctrl+shift+p (or cmd+shift+p on mac).

Key bindings are not provided by default as it's not recommended but you can easily set up any key binding you want through `Preferences: Key Bindings` in the Command Palette.

**Comment by eusonlito** [comment]
Ok, I get it.

I think the main difference with my plugin is that everything is requested from the input panel instead of writing the needs in the editor, for me it's much cleaner and clearer.

Thanks for your support :)

**Comment by rchl** [comment]
It appears to me that the other package has 3 different modes of entering queries and at least one of them uses the same method as you (`show_input_panel`). But I don't know, haven't tried it myself. Up to you but you could contribute suggestions or features to it probably if you want to save some time. :)

**Comment by yaroslavyaroslav** [comment]
I suddenly found this one, so I can answer. Yes, my package have both features: to ask question in the input view rather the sending to the server selected text and to edit selected text with a given command again in input view, though the latter gives relatively bad quality on my tasks.

And to be honest I can confirm the lack of plugin documentation that was raised by the PR author.

**Pull request closed without merging**
