### PR TITLE
Pharko Snippets

### PR DESCRIPTION
**Pull request by marczhermo**
Please provide the following information:

 - https://github.com/marczhermo/Pharko
 - https://github.com/marczhermo/Pharko/tree/v1.0.5

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please see the second section in my comment [here](https://github.com/wbond/package_control_channel/pull/6125#issuecomment-280937670).

**Comment by marczhermo** [comment]
Thanks FichteFoll for the advise. Now I have included the file .no-sublime-package in the master branch and tagged it to v1.0.2

**Comment by FichteFoll** [comment]
Well done.

Please also add a readme that properly describes what your package does and how it can be used. I only found out after reading the source code and we sure can't expect everyone to do this, can we?

**Comment by marczhermo** [comment]
Thanks again @FichteFoll 
I have updated the Readme file and hope this looks alright with you.
These changes were tagged as v1.0.3

**Comment by marczhermo** [comment]
Bump version to v1.0.5.

**New Feature**
Snippets with additional documentation shown in the output panel.
https://github.com/marczhermo/Pharko/releases/tag/v1.0.5

**Comment by marczhermo** [comment]
Thanks so much @FichteFoll. 
This is like my birthday gift last week 😀

**Pull request merged**
