### PR TITLE
add Fast Header plugin.

### PR DESCRIPTION
**Pull request by olive007**
It's my first plugin for sublime text and I hope you will enjoy it.
I writed the documation into the sublime-settings.

### CODE REVIEW

**Comment by wbond** [comment]
Branch-based releases are not accepted for new packages: https://packagecontrol.io/docs/submitting_a_package#Step_4.

You'll need to use `"tags": true` and create a semantic version tag.

**Comment by FichteFoll** [comment]
How does this differ from the [other header packages](https://packagecontrol.io/search/header)?

**Comment by olive007** [comment]
The most differ is the switching of template with your project.

**Comment by FichteFoll** [comment]
That's some pretty wishy washy reasoning, especially because there isn't even an example template nor a real description of how the package is used.

I honestly don't really see an advantage in using this package over https://packagecontrol.io/packages/FileHeader so far.

**Comment by olive007** [comment]
With FileHeader you can not have 2 or more variables in the same line of the template.
I have post a Pull request for that, and I have no answer.

And I am writing a documentation for the functionality of my plugin but I am not english, and I'll be help by a friend in september.

**Pull request merged**
