### PR TITLE
An improved Stata editor with many features integrated

### PR DESCRIPTION
**Pull request by zizhongyan**
https://github.com/zizhongyan/StataImproved

### CODE REVIEW

**Comment by zizhongyan** [comment]
Added a demo for this:
https://www.youtube.com/watch?v=4vvsk8lG6fY&t=389s

**Comment by zizhongyan** [comment]
@FichteFoll Hi, FichteFoll, Just let you know that my coauthor and I have made a big update recently of the plg and we have re-coded many parts of it. 

Thank you for the favourable review. 

We are looking forward to your kind comments. 

Many thanks!!!

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to your repo.

Because this would be your first release, the version `1.0.0` could be appropriate.

```sh
$ git tag v1.0.0
$ git push origin v1.0.0
```

Package Control will strip the optional `v` prefix.

**Comment by zizhongyan** [comment]
@FichteFoll Thank you very much for pointing out this. I have added the valid semantic version tag (v.1.0.0). Please check. Many thanks for the help!!

**Pull request merged**
