### PR TITLE
Update g.json

### PR DESCRIPTION
**Pull request by DisposaBoy**

### CODE REVIEW

**Comment by Thom1729** [comment]
What's the story here?

**Comment by Thom1729** [comment]
Branch-based releases are deprecated. Instead, you should use `"tags": "myPrefix"`. Then, PC will only find tags beginning with `myPrefix`.

**Comment by DisposaBoy** [comment]
PR updated.

**Comment by billinghamj** [comment]
> I don't want it to just vanish without users knowing what happened

It kinda seems like it just vanished? lol

How can users install the old version with PC?

**Comment by FichteFoll** [comment]
It doesn't look like there is a tag with an `unsupported-` prefix on https://github.com/DisposaBoy/GoSublime/tags. @DisposaBoy, you mentioned you want PC users to install the stale branch/release, but currently there isn't any release at all for GoSublime that PC could install.

When doing so, you might also want to include a changelog mentioning this change in your policy so that users that *do* want to receive updates can opt to do so by cloning it manually, or similar. See https://packagecontrol.io/docs/messaging for details.

**Comment by DisposaBoy** [comment]
Thanks for the tips @FichteFoll. This has fallen down the priority list but I'll keep it in mind when I get back to it.

**Comment by DisposaBoy** [comment]
@billinghamj You can't - at least not currently - but I don't know why you'd even want to do that.

If you still want to install it, you can follow the instructions https://github.com/DisposaBoy/GoSublime/tree/legacy#installation and then checkout the `legacy` branch.

**Comment by billinghamj** [comment]
I want to because I have a setup and config which works, and I have no interest in redoing it from scratch when what I have now works absolutely fine.

**Pull request merged**
