### PR TITLE
Update to new repo location organization for AutoHotKey

### PR DESCRIPTION
**Pull request by robertcollier4**

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://raw.githubusercontent.com/ahkscript/AutoHotkey/master/packages.json is still outdated.

You could as well just add the package to the default channel. Not really useful to provide your own repo file for just one package.

**Comment by robertcollier4** [comment]
I tried that before and the Package Control team rejected it - instructing that for this repo a packages.json file would be necessary to indicate that the package is for Windows only and not all platforms.

**Comment by wbond** [comment]
@robertcollier4 That was before schema_version `2.0`.

If you install https://packagecontrol.io/packages/ChannelRepositoryTools, you can run the command `Upgrade Repository Schema (Current File)` which will update your schema to the latest. It will also prompt you if you can move the repository into the main channel file.

Let me know if you have any questions, or if anything is unclear.

**Comment by FichteFoll** [comment]
Either way, `"details": "https://github.com/robertcollier4/AutoHotkey",` is still the old repo.

**Comment by robertcollier4** [comment]
Removed packages.json in favor of adding the platform tag in the default repository.

**Pull request merged**
