### PR TITLE
Added "Kivy Syntax"

### PR DESCRIPTION
**Pull request by Kulothungan16**
# Kivy Syntax
[Kivy](https://github.com/kivy/Kivy) and [KivyMD](https://github.com/kivymd/KivyMD) - Syntax Highlighting and Auto-Completion.

### CODE REVIEW

**Comment by braver** [comment]
We already have a package [Kivy Language](https://packagecontrol.io/packages/Kivy%20Language). How does your package relate to that one? Have you tried contributing to that repository? I'm not against replacing the existing package with something new, but then we first need to demonstrate that the old one is really dead. Enhancing the existing package is preferable though.

**Comment by Kulothungan16** [comment]
The Kivy Language github last commit is before 5 years. The owner of it doesn't maintain it. Please merge this PR.

**Comment by braver** [comment]
@ivlevdenis would it be possible for @Kulothungan16 to contribute to your existing [Kivy](https://packagecontrol.io/packages/Kivy%20Language) package? Alternatively, we can replace the entry with the new repository, but overall it's usually more smooth for everyone if the original package can be updated. Please let us know in the coming week or two how you'd like to deal with this.

**Comment by ivlevdenis** [comment]
Hi! I'm don't mind if someone contribute to my [repo](https://github.com/ivlevdenis/kivylng).

**Comment by braver** [comment]
Hi! Thanks for getting back to us so quickly.

@Kulothungan16 please let's first try to go via a pull request on @ivlevdenis's [package](https://github.com/ivlevdenis/kivylng). I'm going to close this one for now. It'll still be here if things don't work out and we need to try a different approach, but I'm sure you guys will figure out a way to enhance Kivy for all existing users.

**Pull request closed without merging**
