### PR TITLE
Update g.json for Gengojs

### PR DESCRIPTION
**Pull request by iwatakeshi**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please use a consistent indent/whitespace formatting.

**Comment by iwatakeshi** [comment]
Sorry about the whitespace, what kind of settings do you prefer? I'm using the original settings in ST3.

**Comment by iwatakeshi** [comment]
Never mind, I found the issue. I think you are referencing to the brackets and braces.

**Comment by FichteFoll** [comment]
Yes indeed.

**Pull request merged**
