### PR TITLE
Added the MagentoSnippets repository to the Default Channel

### PR DESCRIPTION
**Pull request by vanessametonini**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push tags to your repo.

**Comment by vanessametonini** [comment]
Hi Fichte, I just created the tag 1.0.0. Is there something else I need to fix?

**Comment by vanessametonini** [comment]
Sorry for bother, but have any chance to proceed with this PR in this week? Thanks. :)

**Comment by FichteFoll** [comment]
Sorry, I must have missed it somehow. It's merged now.

**Comment by vanessametonini** [comment]
Thank you very much! :)

**Pull request merged**
