### PR TITLE
	add UndoRedoDontMoveCursor

### PR DESCRIPTION
**Pull request by titoBouzout**
add UndoRedoDontMoveCursor package

### CODE REVIEW

**Comment by FichteFoll** [comment]
Why the weird prefix?

**Comment by titoBouzout** [comment]
I like the name for the package. There I added and pushed the tag.

**Comment by FichteFoll** [comment]
Leading zeroes are invalid for semantic versions.

**Comment by titoBouzout** [comment]
A pain in the ass :P Think is fixed.

**Comment by wbond** [comment]
I removed this package because it has a crappy name and was using version numbers bigger than 32bit integer, thus causing issues with the site and channel.

**Comment by titoBouzout** [comment]
Now what

**Comment by FichteFoll** [comment]
>version numbers bigger than 32bit integer

Well, I couldn't expect that. :joy:

**Comment by wbond** [comment]
Apparently there is some issue in constructing psycopg2 result objects with integers bigger than 32bits. I can't say I would have expected it either. However, it will have to wait until I have time to figure out exactly what is causing it. It isn't obvious to me from the exception and stack trace.

Until then, version numbers < 2 billion will have to do.

**Pull request merged**
