### PR TITLE
Added RedEye color scheme package

### PR DESCRIPTION
**Pull request by mattmag**
Created a new, custom sublime text color scheme designed to mimic jetliner cockpits at night

### CODE REVIEW

**Comment by mattmag** [comment]
> 
> ### Automated testing result: WARNING
> 
> Repo link: [RedEye](https://github.com/mattmag/RedEye)
> [Results help](https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks)
> 
> ```
> Packages added:
>   - RedEye
> 
> Processing package "RedEye"
>   - WARNING: The package does not contain a top-level LICENSE file. A license helps users to contribute to the package.
> ```

The license was linked to in the README.md - but I've added a LICENSE file with full plain text of the license and tagged as v1.0.1

**Comment by jwortmann** [comment]
Nice color scheme and it's cool to see you make use of dimmed colors for markup/tags in documentation comments. Please be aware that the scope name for `///` comments in C# was recently changed from `comment.block.documentation` to `comment.line.documentation`, so that it complies with the scoping used for doc comments in R, and because according to the [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) C# supports both single-line (`///`) and delimited block (`/** ... */`) documentation comments. Therefore to also support the C# syntax in new ST versions you ideally want to target both of these scopes.

There are also some important scopes from the recommended [minimal scope coverage](https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes) which are not highlighted by your scheme, for example `constant.language` and `keyword` (or alternatively you should at least target `keyword.declaration` in addition to the `keyword.control` and `keyword.operator` scopes that you use).

By the way, if you add `*.sublime-color-scheme linguist-language=jsonc` to your .gitattributes file, you get some basic highlighting for the color scheme file on GitHub.

**Comment by mattmag** [comment]
Thanks for the review! I'll go through and make those updates. Nice tip on the jsonc language declaration too.
I've also starred the sublimehq/Packages repository so that I can keep an eye on syntax changes in the future.

**Comment by braver** [comment]
Pretty cool color scheme!

**Pull request merged**
