### PR TITLE
LocalizedMenu: Localize Tool & Localized Menu

### PR DESCRIPTION
**Pull request by zam1024t**
Localize Tool & Localized Menu for Sublime Text 2/3 End User.

- Provide a easy way to add new languages.
- Support multiple version/platform.
- Support share common menus.
- Auto backup local menu.

### CODE REVIEW

**Comment by wbond** [comment]
This seems very similar to https://packagecontrol.io/packages/ChineseLocalizations, although I don't know many of the technical details.

Did you consider working with @rexdf to see if you could contribute features to that?

**Comment by rexdf** [comment]
Most of features have been included in ChineseLocalization, like multiple version/platform, and more, like OSX optimization, compatible with 3118. The quality of my translation is better.

I will consider to support add a backup feature and tool menu.

I have been considering to support to localize any plugins for a while.

**Comment by zam1024t** [comment]
由于这些原因，我不太想把LocalizeMenu合并到ChineseLocalization项目中：
1, 项目名字叫ChineseLocalization, 但却包含了除汉语之外的其它语言，这让我很迷糊。
2, 比如：我是一名芬兰的网站编辑，我平时就写点html代码，现在我要贡献一个芬兰语的翻译到ChineseLocalization中。
    用ChineseLocalization我什么也做不了，因为我不会git，我只是一个终端用户，我不是一个开发者。
    用LocalizedMenu，我可以在本地就把它翻译成芬兰语，然后不用提交到github也可以很好地工作，我可以自由地决定是分享或是私有。
    一个开发者提交一种语言翻译到ChineseLocalization也不是一件很件很轻松，首先我要打包好成一个zip文件，然后还要等你硬编码代码，语言包才会生效。
    https://github.com/rexdf/ChineseLocalization/blob/st3-dev/Localization.py
`LANGS = {
    "ZH_CN": {
        'zipfile': 'ZH_CN.zip',
        'syntax_md5sum': '44cd99cdd8ef6c2c60c0a89d53a40b95'
    },
    "ZH_TW": {
        "zipfile": "ZH_TW.zip",
        'syntax_md5sum': "fe7457cfd227b7db74e785321f672c4a"
    },
    "JA_JP": {
        "zipfile": "JA_JP.zip",
        'syntax_md5sum': "037128b8f8d2616c7239d8e9a7183b4c"
    },
    # "EN": { # This item is deprecated and not used in programming.
    #     "zipfile": "EN.zip",
    #     'syntax_md5sum': (
    #         "2667c3fe5c1102274051920b1f581adb",
    #         "ecd966996f5fcaff6fac2a281bec93d5",  # 3099+
    #     )
    # }
}`
3, 最关键的一点，我们的着重点不一样。你关注的是翻译的质量，我关注的是它是是不是一个好用的翻译工具，我希望任何人都可以很方便地使用它，可以很自由地添加各个版本各种语言的翻译，可以选择共享或私有。

我不太在乎语言翻译本身的质量，因为每个人都有自己的语言习惯，而且我个人懂的语言了不多，即便我再能干我懂的语种也是有限的，我希望比我在行的人可以很轻易地去添加/修正/完善各种语言的翻译。

作为一个汉语翻译的项目, ChineseLocalization是一个好项目。
作为一个翻译工具，LocalizedMenu是一个好工具。

我应该把LocalizedMenu改名为LocalizeTool再提交到插件库中吗？

----------------------------------------------------------------------------------------------------
For these reasons i do not want to merge LocalizedMenu into ChineseLocalization:
1, Project named ChineseLocalization, but included not only chinese translation, that made me confused.
2, For example, i am a finnish website editor, usually i write some html code, then i want submit an finnish translation for sublime menu.
    With ChineseLocalization, i can do nothing, becuase has no git skill, i am only a editor user, not a developer.
    With LocalizedMenu, I can translate it on local without submit, works well. It is free to me share the translation or keep it private.
    With ChineseLocalization, it is too hard to submit a transation.
    After translation i must package the languages files as a zip file, then pull request to your repo.
    When you receve the pull request, you must change your hard-code to add this language!
    https://github.com/rexdf/ChineseLocalization/blob/st3-dev/Localization.py
`LANGS = {
    "ZH_CN": {
        'zipfile': 'ZH_CN.zip',
        'syntax_md5sum': '44cd99cdd8ef6c2c60c0a89d53a40b95'
    },
    "ZH_TW": {
        "zipfile": "ZH_TW.zip",
        'syntax_md5sum': "fe7457cfd227b7db74e785321f672c4a"
    },
    "JA_JP": {
        "zipfile": "JA_JP.zip",
        'syntax_md5sum': "037128b8f8d2616c7239d8e9a7183b4c"
    },
    # "EN": { # This item is deprecated and not used in programming.
    #     "zipfile": "EN.zip",
    #     'syntax_md5sum': (
    #         "2667c3fe5c1102274051920b1f581adb",
    #         "ecd966996f5fcaff6fac2a281bec93d5",  # 3099+
    #     )
    # }
}`
3, The most important is that you care the translation quality but i care the tool itself if easy to use. 

I know a few languages, even i kown many languages, the quantity is also limited, but i hope anyone can use the tool to add/correct/improve more languages, can free to keep it public or private.

As a chinese translation project,  ChineseLocalization is better.
As a localize tool, LocalizedMenu is better.

Should i named LocalizedMenu as LocalizeTool to submit?

**Comment by rexdf** [comment]
> Project named ChineseLocalization, but included not only chinese translation, that made me confused.
Maybe I can use a different name. But now, there is just chinese and japanese.

>Hash code
In order to reduce the time complexity, I use hash O(1). The zip package is for release.

>With ChineseLocalization, it is too hard to submit a transation.
Nope, I will never accept zip pull request. Just submit a translation as code, I will make a zip release.

>The most important is that you care the translation quality but i care the tool itself if easy to use.
I don't think that the tool itself is easy to use.  Sublime Text English Menu is public, it is unnecessary to have a private local translation.

 If you have to, you can install `Zip Browser` and make easily a localization. Why do we need to use an extra plugin to edit json and update menu by event bind to consume CPU?

Some bugs:
1. Your plugin supports `English(en) English(en_US) English(en_GB)`, but actually, it does not even support sublimetext built-in English menu.
2. Your plugin can just use a plugin version of sublimetext menu, and cannot use version appropriate translation(even English).

**Comment by rexdf** [comment]
Now ChineseLocalization supports User-Defined language translation.

**Comment by zam1024t** [comment]
(In order to reduce mistake for my expression in english, I added an extra chinese comments.)
(为了避免我用英文表达出现偏差，还是每句都带上中文。汗！)

> 1. Your plugin supports English(en) English(en_US) English(en_GB), but actually, it does not even support sublimetext built-in English menu.

Not a bug. en_US/en_GB now is link to en, if you have to make translation diff for en_GB/en_US, you can remove the links then translate them.
这不是一个BUG. 现在en_US/en_GB都链接到en这个语言上，如果你硬要区分en_US/en_GB，那么你可以把链接删除掉然后去翻译一遍。

> 2. Your plugin can just use a plugin version of sublimetext menu, and cannot use version appropriate translation(even English).

I can not clearly understand what you means, you are allow to use chinese.
你说的这个问题我不是很理解，你可以用中文表达一下。

> Now ChineseLocalization supports User-Defined language translation.

Nice.
挺好的。

**Comment by rexdf** [comment]
Your plugin cannot be installed by Packagecontrol in fresh installed Sublime Text 3118. And menu item is not fit for different version of sublime text.

**Comment by zam1024t** [comment]
> Your plugin cannot be installed by Packagecontrol in fresh installed Sublime Text 3118.

Before merged, I have no idea to this.

> And menu item is not fit for different version of sublime text.

I know this.

**Comment by rexdf** [comment]
PackageControl Support github url install

**Comment by zam1024t** [comment]
Support dev version would be a later work.

**Comment by zam1024t** [comment]
@wbond I has discus with @rexdf, them are quite different for designing, i would like to add LocalizedMenu as a new plugin.

**Comment by rexdf** [comment]
I think that they are same plugins to localize sublime text, although the technical details are different.

**Pull request merged**
