### PR TITLE
Add Fuse package to the repository.

### PR DESCRIPTION
**Pull request by Tapped**

### CODE REVIEW

**Comment by FichteFoll** [comment]
I suggest using relative imports instead of absolute (and not basing on "Fuse").

You should really take a look at PEP8 and the naming conventions it suggests.

**Comment by Tapped** [comment]
We have tried to be consistent in our style, but if it matters that the style is not "proper" python style, we can fix that.

**Comment by FichteFoll** [comment]
It does not matter, but naming functions in TitleCase is quite concerning, for me at least, since that is normally reserved for classes. I also couldn't actually find a style since you were using lowercase and camelCase, as well as TitleCase for method names (in the `BuildResults` class for example)

**Comment by Tapped** [comment]
Yeah, build_results, fuse_parseutils and fuse_util has not yet been refactored for its function names. 

However it is okey, with camelCase and__camelCase for method names?

**Comment by FichteFoll** [comment]
__ actually has a special meaning that is not limited to simply naming (and I hope you are aware of that). If not, you should look it up. It should also be mentioned in PEP8.

I'm more concerned about relative imports.

**Comment by Tapped** [comment]
@FichteFoll 
Hey, I have done some cleanups. Thank you for your time.

**Pull request merged**
