### PR TITLE
Add type language syntax highlighting

### PR DESCRIPTION
**Pull request by goodmind**

### CODE REVIEW

**Comment by goodmind** [comment]
Anyone here?

**Comment by jrappen** [comment]
@goodmind If you're targeting ST3, maybe you could bump the requirements to ST3092+ (and update the requested changes here) and provide a `*.sublime-syntax` file? I see you already have a YAML file for PackageDev you're working with. Compare <https://www.sublimetext.com/docs/3/syntax.html>. I also recommend adding test files, see the "testing" section on that page for more.

**Comment by goodmind** [comment]
@jrappen can i convert TextMate to `*.sublime-syntax` automatically?

**Comment by jrappen** [comment]
@goodmind Try opening the syntax file, then choose `Tools > Developer > New .... syntax` from the menu or whatever it was called. Can't check right now, but should be there. Alternatively, you can open a file and set that syntax, then the same from the menu.

**Comment by FichteFoll** [comment]
Unintuitively, you need to be *using* the syntax file you want to convert instead of having it open with that command.

I'll wait for you to switch to the new format and update ST build requirements before merging.

**Comment by goodmind** [comment]
@FichteFoll updated package

**Pull request merged**
