### PR TITLE
Add Assembly for pic16f84 Syntax package

### PR DESCRIPTION
**Pull request by Alejok0**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is Assembly syntax for PIC16F84A

My package is similar to [this] (https://github.com/vyivanov/AVR-ASM-Sublime) However, it still needs to be added because the mnemonics and syntax change quite a bit.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Please tag a semver-numbered release, remove the package metadata file and then try to run the review bot again.

**Comment by Alejok0** [comment]
Trigger package review

**Comment by Alejok0** [comment]
Trigger package review

**Comment by braver** [comment]
Your readme still reads

> ... syntax definition for [Sublime Text 2](http://www.sublimetext.com/)

Nobody still uses ST2.

You might also want to look into converting your tmLanguage into the new sublime-syntax: it's more performant and easier to maintain. A convertor is available inside ST.

**Comment by braver** [comment]
Closing this for now. Let us know if you want to re-start the review.

**Pull request closed without merging**
