### PR TITLE
Add SpectreMan

### PR DESCRIPTION
**Pull request by code-reaper08**
## Hello 😄

This is my new snippet package called **SpectreMan**, it provides highly useful snippets and almost contain all the features, which SpectreCSS contains as of now. I am planning to include the few missed ones as update too in near future. I think this is the first package for SpectreCSS framework, and i think it's awesome too. Hoping for a postive reply.

Have a nice day 😄✔

### CODE REVIEW

**Comment by braver** [comment]
Looks pretty useful 👍🏻 Some things:

- the snippet descriptions don't read well for me, `Spectre-Disabled Button` without the spaces around the `-`... Maybe `Spectre: Disabled Button`?
- The name SpectreMan and the repo description don't immediately signal that this is about Spectre.css to me. SpectreMan is a cool name, but why not simply call the package SpectreCSS? That will really help people find it.

**Comment by code-reaper08** [comment]
> Looks pretty useful 👍🏻 Some things:
> 
> * the snippet descriptions don't read well for me, `Spectre-Disabled Button` without the spaces around the `-`... Maybe `Spectre: Disabled Button`?
> * The name SpectreMan and the repo description don't immediately signal that this is about Spectre.css to me. SpectreMan is a cool name, but why not simply call the package SpectreCSS? That will really help people find it.

## Hey @braver 😀

Thanks for the feedback. That's true I didn't thought about descriptions, I'll change it today.

Regarding package name,
will change that package name too.

Thanks 💯✨

**Comment by code-reaper08** [comment]
Hello @braver 👋
Done with the name and descriptions.

Also changed some descriptions to be short and understandable.

Thanks for your feedback 😀

**Comment by braver** [comment]
Excellent! Don't forget to tag a new release with your latest changes.

**Pull request merged**
