### PR TITLE
Add hacklang typechecker

### PR DESCRIPTION
**Pull request by SiebelsTim**
Ref https://github.com/SiebelsTim/hack-sublime/issues/5

### CODE REVIEW

**Comment by FichteFoll** [comment]
You should remove the `.sublime-package` from your repo since it's unnecessary data and instead have all its contents in the initial repo (which might as well just be that .py file).

Also you need to push a versioned tag.

**Comment by SiebelsTim** [comment]
@FichteFoll thanks, do I *have* to remove the .sublime-package file? I like having it in there in case someone wants to install it without the package manager.

**Comment by FichteFoll** [comment]
I suggest you host it in a separate branch instead or use the github releases feature that allows you to upload binary "builds". You'd have to update the download url for every release though.

**Comment by SiebelsTim** [comment]
All right. Ping.

**Comment by FichteFoll** [comment]
I actually meant it the other way around. Especially since using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by SiebelsTim** [comment]
So I can't specify a specific branch where the packagecontrol is searching for the correct tag? Does it have to be in master?

**Comment by FichteFoll** [comment]
Tags are completely independant of branches. You can even create and push a tag that is not on a branch (anymore) because you reset the branch or didn't push it.

**Comment by SiebelsTim** [comment]
Oh! It's never too late to learn :)

changed again, sorry for the inconvenience

**Comment by FichteFoll** [comment]
Alright, but one last thing: It has to be a semantic version in the form `v1.0.0`.

**Comment by SiebelsTim** [comment]
aaah, right. Sorry.

**Pull request merged**
