### PR TITLE
Add RegexMatch package

### PR DESCRIPTION
**Pull request by mercurykd**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] Any commands are available via the command palette.
- [x] If my package is a syntax it doesn't also add a color scheme. ***

My package is Testing regular expressions

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by braver** [comment]
Very interesting package idea! Some questions:
 
- Do you really need the keybinding?
- The feedback UI seems a bit limiting for larger regexes with more capture groups. Maybe you could utilize the output panel for more details about the matches?
- Are you fully highlighting the regex, like with escape sequences etc?

**Comment by mercurykd** [comment]
> * Do you really need the keybinding?

no

> * The feedback UI seems a bit limiting for larger regexes with more capture groups. Maybe you could utilize the output panel for more details about the matches?

good idea

> * Are you fully highlighting the regex, like with escape sequences etc?

didn't really understand the question

**Comment by mercurykd** [comment]
add license and delete keybinding

**Comment by mercurykd** [comment]
add:
- explain in panel
- display groups like ~()~

**Comment by mercurykd** [comment]
removed global variables
color scheme patch
redundant events removed

**Comment by braver** [comment]
> > Are you fully highlighting the regex, like with escape sequences etc?

> didn't really understand the question

If you look at a regex in say Python, sequences, certain characters and escapes are highlighted with different colors. In your package it's just a string. Would be nice to have syntax highlighting for the regex. Since you probably only support Python regexes anyway (which is something you might want to clarify in your readme, the underlying regex engine can be quite relevant), you might be able to apply the same syntax in this context?

**Comment by mercurykd** [comment]
> If you look at a regex in say Python, sequences, certain characters and escapes are highlighted with different colors

do you mean highlight the regex pattern itself?
image

**Comment by braver** [comment]
yes!

**Comment by braver** [comment]
Well, consider those improvements in your own time. I think we should just ship it now as is.

**Pull request merged**
