### PR TITLE
Add package -- ShellScriptImproved

### PR DESCRIPTION
**Pull request by jfcherng**
Repo: https://github.com/jfcherng/Sublime-ShellScriptImproved

I guess people would have a hard time reviewing [this pull request](https://github.com/sublimehq/Packages/pull/47) in the official ST package repo so I make it a non-official one.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need a `.no-sublime-package` file in your package. Please remove it.

**Comment by jfcherng** [comment]
@FichteFoll  Done.

**Comment by FichteFoll** [comment]
Don't forget to push a new tag with the changes.

**Comment by jfcherng** [comment]
@FichteFoll Done.

**Pull request merged**
