### PR TITLE
Replaced Wrapper with WrapIt

### PR DESCRIPTION
**Pull request by pyking2**
Original author @lattespirit offered to remove Wrapper from the channel in favor of a new strongly enhanced version.
_See here: https://github.com/lattespirit/SublimeWrapper/issues/7_

**WrapIt** shares the core function of Wrapper but is a _complete rewrite_. It adds important features which makes it much more powerful than its predecessor:
- the support for custom wrappers
- a new more  maintainable JSON structure
- very easy templating of custom code blocks
- custom key bindings.

### CODE REVIEW

**Comment by FichteFoll** [comment]
@lattespirit it would be nice if you could explicitly acknowledge this move. You offered to delete the pacakge but didn't necessarily agree on replacing it (although this is the preferred action).

@bfelder you should prepare an update message informing about the changes for the users that have this pacakge installed already.
Besides, `readme` should point to a raw file, which your URL does not. You can just remove the line as PC will pick up the readme from your repo's master branch by default.
Finally, you need to escape some characters from the selection if you use it with the `insert_snippet` command. To be precise, replace `$` with `\$`.

**Comment by bfelder** [comment]
@FichteFoll Great point escaping in `$` in the selections. It escaped my attention.

Where should I place this UpdateMessage? In the readme?

**Comment by FichteFoll** [comment]
See https://packagecontrol.io/docs/messaging.

**Comment by bfelder** [comment]
@FichteFoll @lattespirit 
I have just released a new version of WrapIt.
From its release note:
- added install message to inform about WrapIt to take over from SublimeWrapper
- added menu entry for settings and key bindings
- added escaping mechanism for text selection to prevent interference from '$' containing selections

**Comment by FichteFoll** [comment]
@lattespirit any words from you on this?

@pyking2 you need to adjust the package URL to your rename.

**Comment by pyking2** [comment]
@FichteFoll I'll do in an instant together with the other recent merges.

**Comment by FichteFoll** [comment]
Don't worry about the others, I just spotted that and fixed it myself in fd4c070645a779bc726e3c2c044a397e4083a14d.

**Comment by pyking2** [comment]
Should be done by now.

**Comment by lattespirit** [comment]
@FichteFoll @pyking2 Sorry for the late reply, I agree with transfering this package and i hope more people  
 enjoy the benifit from this new package.

**Comment by FichteFoll** [comment]
@pyking2 I just checked your "update message" and noticed you show it on installation. That won't do since this is *only* shown on installation and any user already using Wrapper will not see the message, while it is instead shown to any new users installing "WrapIt". You need to add a message for your current latest release tag with a message you want previous users to see.

**Comment by pyking2** [comment]
@lattespirit Thank you for your trust. This is very honorable. As you may have noted I have included your alias under contributors, as a special mention. If you like to have your full name state just tell me.

@FichteFoll I have made a new release. The install message should now be shown to any users installing the latest release.

**Pull request merged**
