### PR TITLE
added DocPy-a docstring python autocomplete tool

### PR DESCRIPTION
**Pull request by RicherMans**
DocPy is a simple python function autocomplete tool, which helps writing function documentation.

### CODE REVIEW

**Comment by geekpradd** [comment]
Great Plugin.. I recently started writing docstrings in Python and it looks helpful. ST2 support would be awesome (I think i can help, but I'll have to grasp your code first)

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

I didn't spot anything that would be incompatible with ST2 (but no guarantees). However, @geekpradd, you should really consider upgrading to ST3 since it's a lot better.

**Comment by geekpradd** [comment]
Already on ST3 @FichteFoll .. But I always like backporting stuff (especially Python 3 to Python 2). And I have ST2 installed that I use sometimes. 

And many people who bought ST2 haven't purchased ST3 (like me) because it's a beta and so ST2 still lurks in our machines.

**Comment by RicherMans** [comment]
Well actually there is something not working with ST2, which is in line 121 of the plugin
```python
functionname, *args = funcdefargs
```
I have never worked with python3, but I just liked that feature so I simply implemented it. Havent even thought of using the whole plugin for ST2, but will do then.

**Comment by FichteFoll** [comment]
Okay, but you need to edit this PR so that it points to your releases.

**Comment by RicherMans** [comment]
Is it enough to commit the release into the current pull request or do I only need to push one commit which points at the release?

**Comment by FichteFoll** [comment]
I don't exactly understand, but what you did is fine.

**Pull request merged**
