### PR TITLE
Add Bootstrap4 package

### PR DESCRIPTION
**Pull request by mdegoo**
Simply add Bootstrap4 snippet in ST ;)

### CODE REVIEW

**Comment by FichteFoll** [comment]
This package only contains one snippet several dozen times?

**Comment by mdegoo** [comment]
they're placed as template..

**Comment by mdegoo** [comment]
The rest of the snippets will be added this week following https://github.com/mdegoo/atom-bootstrap4

**Comment by FichteFoll** [comment]
Okay.

- You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.
- `0-1-0` is not a valid version number (from `messages.json`).

**Comment by mdegoo** [comment]
Ok thnks

**Comment by FichteFoll** [comment]
@mdegoo ping

**Comment by mdegoo** [comment]
Fixed!

**Comment by FichteFoll** [comment]
I don't see a tag here: https://github.com/mdegoo/sublime-bootstrap4/tags

**Comment by mdegoo** [comment]
oh, my bad. forgot to push.

now it's fixed : https://github.com/mdegoo/sublime-bootstrap4/tree/v0.1.0

**Pull request merged**
