### PR TITLE
Add addons for the Boxy Theme

### PR DESCRIPTION
**Pull request by oivva**
Adds SublimeLinter theme and addons for changing font size of the inputs and the console panel text.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Are you sure you need `.no-sublime-plackage` files for these? I don't think so.

**Comment by oivva** [comment]
Agree, I'll delete `.no-sublime-package` files for the all addons, except **Boxy Theme Addon - Font Face**, because user should customize font family manually.

**Comment by FichteFoll** [comment]
Just remember that any update of the package will erase all user changes when the package is extracted.

**Comment by oivva** [comment]
After some experiments, I can say that `.no-sublime-package` should be removed only from **Boxy Theme Addon - Linter Theme**, because font size and face isn't overriding when the packages aren't extracted.

**Pull request merged**
