### PR TITLE
Add SnipTeX package

### PR DESCRIPTION
**Pull request by CharbelAD**
This is a collection of (currently) 95 snippets for a LaTeX workflow. It contains a lot more snippets than the other existing packages and it is more varied, hence why I made it into a separate package.

### CODE REVIEW

**Comment by CharbelAD** [comment]
Added proper semantic versioning number

**Comment by CharbelAD** [comment]
Okay, should be fixed now again

**Comment by CharbelAD** [comment]
I fixed the semantic versioning, but I don't understand why the automated check is failing, could someone please help?

**Comment by FichteFoll** [comment]
Could you please resolve the conflict? I'll merge afterwards.

**Comment by CharbelAD** [comment]
The conflict should be resolved now (I hope)

**Comment by FichteFoll** [comment]
No, something went terribly wrong here. If you can't easily fix it, I suggest making a new PR fresh from `master` and closing this one.

**Comment by CharbelAD** [comment]
I think the problem was with another package, but you're right. I'm making a new one

**Comment by FichteFoll** [comment]
The problem was introduced by [your merge commit](https://github.com/wbond/package_control_channel/pull/8015/commits/15d1d0b90e4c4749bbc4b718e177258a7c4069d0), but it dosn't matter.

**Comment by CharbelAD** [comment]
Ohh... Okay. I apologize, I'm still kind of new.

**Pull request closed without merging**
