### PR TITLE
Add Meteor Awesome Snippets

### PR DESCRIPTION
**Pull request by lnmunhoz**

### CODE REVIEW

**Comment by FichteFoll** [comment]
What are the differences to [this other package](https://packagecontrol.io/packages/Meteor%20Snippets)?

**Comment by lnmunhoz** [comment]
@FichteFoll Its not being updated anymore.

**Comment by FichteFoll** [comment]
Did you try to reach out to @mrtnbroder? Maybe he would be willing to add you as a contributer?

**Comment by lnmunhoz** [comment]
I will shot him an email!

**Comment by mrtnbroder** [comment]
Do it!

**Comment by FichteFoll** [comment]
Awesome, sounds like you resolved it.

As a heads up, don't forget to push a new tag to publish a new release. And finally, you don't actually need a `.no-sublime-package` file in your package. Please remove it.

**Comment by lnmunhoz** [comment]
Thanks @FichteFoll

**Pull request closed without merging**
