### PR TITLE
Add Sexy Snippets

### PR DESCRIPTION
**Pull request by felquis**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can remove your `repository.json` file and move the tags from there to this pull request as it won't be looked at.

**Comment by felquis** [comment]
I'm not sure if I understand what did you mean, but I removed the `repository.json` file, and I put these information in the `s.json` file. Is it right now? Thanks.

**Comment by FichteFoll** [comment]
Yes. Well, the most important things were the labels as the others are the calculated defaults anyway, but this works.

**Comment by felquis** [comment]
Thank you FichteFoll :)

2015-01-04 13:57 GMT-02:00 FichteFoll <notifications@github.com>:

> Merged #3969 <https://github.com/wbond/package_control_channel/pull/3969>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/3969#event-213795694>
> .
>



-- 
Felquis Gimenes - Front-end
felquis.com +55 011 95980 2233

**Pull request merged**
