### PR TITLE
Added package PEPEasm

### PR DESCRIPTION
**Pull request by Jonyleo**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] If my package is a syntax it doesn't also add a color scheme. ***

My package is syntax highlighting for the PEPE assembly programming language, used in a introduction to computer architecture class in IST at university of Lisbon.

My package is very similar to [PEPE Assembly](https://github.com/patriq/Sublime-PEPE-Assembly), however it should still be added because the original package has fallen behind of the new features of the language.

I've tried getting in contact with the maintainer, via github issues and e-mail, but I have not gotten a response.

I would try to get the original package replaced with mine, however I can't find a way to request that.

For this reason I decided to make my own package that addresses this issue. 

I would also like to add that I work on the official compiler for this language, if that adds any weight to my application!

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Thanks for your submission. I have seen your issue in the original repo. In such cases we typically give the original author, @patriq in this case, some time to object (say 2 weeks). Then we can proceed to replace the existing package with the new one.

Two things to do in preparation for the replacement to work:
- Ensure the latest tag in your repo is a higher version than the last one in the old repo.
- Change your submission in this PR to simply replace the repo url of the existing entry to point to your repo.

You can ignore those warnings from the bot. The version compatibility issue is not really relevant anymore and a license is optional (though recommended).

Your syntax should be slightly tweaked though. To enable package authors and color scheme designers to specifically target your syntax, all your scopes should end with something like “.pepeasm”.

**Comment by Jonyleo** [comment]
Thank you for the feedback, I will push the new version shortly. I do have a question, I want to have simple completion for words that already exist in the file, the documentation says that sublime does that as default but it does not seem to happen.

**Comment by Jonyleo** [comment]
I think I've done all you asked correctly, thank for the feedback.

I'm not great with github but I believe my latest tag in the PEPEAsm repo points to the latest commit!

**Comment by patriq** [comment]
Hello! Sorry this issue was somehow filtered by my inbox.  Also sorry @Jonyleo in-case I have ignored any of your communication attempts (I have only now seen the issue created in my repo).

I am not sure about the similarity of our projects. The language I added syntax and snippets for was this very niche assembly for this very niche microprocessor made to teach the [Introduction to Computer Architecture course](https://fenix.tecnico.ulisboa.pt/disciplinas/IAC317/2015-2016/1-semestre) at the Instituto Superior Técnico University in Lisbon.

As stated in the README of my project:
```
This is a syntax definition for assembly that works on a processor called PEPE which was designed by my Introduction to Computer Architecture teacher. Thus you should only use it if you are actually developing for it.
```

So unless you are a student from this specific course I would rather keep ownership and name of the package.

**Comment by Jonyleo** [comment]
Hello @patriq, thanks for the response.
I am indeed a student of that class(took it a few years ago) and I've been working with the teacher to develop new language features for the processor that are missing from your package.

I believe that puts me in a good position to own this package.

I will say however, that when I took the class, your package was a great tool to aid our work. Thank you for your contribution.

I would love to add a note to my repo thanking your previous work, let me know if you would like that!

**Comment by patriq** [comment]
@Jonyleo sounds good!! Then what I would suggest is that I just transfer ownership of the original package to you, keeping the name PEPE Assembly and the original git commit history.

What do you think?

**Comment by Jonyleo** [comment]
I would be overriding all the files. My grammar is not based on yours, it's redone from scratch.
With that being said I'm not 100% sure on the pros of your suggestion

**Comment by patriq** [comment]
So users wouldn't have to download a whole new package, getting the updated version right away.

Also keeping download history is a nice feature.

**Comment by braver** [comment]
Indeed, that would be the best course of action as it keeps everything in one place and all references to this package will continue to point to the latest version.

**Pull request closed without merging**
