### PR TITLE
add AutoSaveBuildLatex

### PR DESCRIPTION
**Pull request by jgonzalezr**
Requires latextools package

### CODE REVIEW

**Comment by wbond** [comment]
Your readme and install messages state that ctrl+shift+s should be used to enable auto build, however you also say to use that key combo for auto save. From reading further on, I think you intended to have users bind auto build to ctrl+shift+b.

**Comment by jamesfzhang** [comment]
This is a fork of my plugin [auto-save](https://github.com/jamesfzhang/auto-save) with some modified code. Can you explain what you're trying to do @jgonzalezr?

**Comment by jgonzalezr** [comment]
I tried to define an auto-save and auto-build plugin only for .tex files, using ctrl+s and ctrl+b respectively. I've updated the README file. 
Use auto-build helps to review the output file while you are typing with Latex.

**Comment by FichteFoll** [comment]
You can just combine auto-save and https://packagecontrol.io/packages/SublimeOnSaveBuild instead, which is also more flexible.

**Pull request closed without merging**
