### PR TITLE
Add package MagentoBacktraceMessageSyntaxAndOpenRestySyntax

### PR DESCRIPTION
**Pull request by alex-magebinary**
Please provide the following information:

 - Link to your code repository: https://github.com/Magebinary/MagentoBacktraceMessageSyntax
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/Magebinary/MagentoBacktraceMessageSyntax/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by alex-magebinary** [comment]
Please provide the following information:

 - Link to your code repository: https://github.com/Magebinary/OpenRestySyntax
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/Magebinary/OpenRestySyntax/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

**Comment by gerardroche** [comment]
You added one of your packages incorrectly: you have replaced "OpenResty lua snippets" with https://github.com/Magebinary/OpenRestySyntax.

You need to close this PR and send separate PR's for your packages. Be sure to read the docs: https://packagecontrol.io/docs/submitting_a_package.

I'm recommending to close this.

**Comment by alex-magebinary** [comment]
Thanks for the review. I have omitted the second commit.
Could you please check the first commit only.

**Comment by gerardroche** [comment]
You should rebase and squash the 6 commits into 1. Reword the PR too.

**Comment by FichteFoll** [comment]
It's fine, I can squash myself.

**Pull request merged**
