### PR TITLE
Add Lucky Link Plugin

### PR DESCRIPTION
**Pull request by ishu3101**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your package code is not compatible with ST3 because Python 3 rearranged the urllib packages.

**Comment by ishu3101** [comment]
Yeah I know, what do I need to do to release it for Sublime Text version 2 only?

**Comment by FichteFoll** [comment]
Change `"sublime_text": "*"` to `"sublime_text": "<3000"`.

**Comment by ishu3101** [comment]
Made the changes required.

**Comment by ishu3101** [comment]
Why does the description not show up? It says "No description provided"

**Pull request merged**
