### PR TITLE
Add `Jedi Syntax`

### PR DESCRIPTION
**Pull request by CyanSalt**
Please provide the following information:

 - Code Repository: https://github.com/CyanSalt/Sublime-Jedi/
 - Tag v1.0.0: https://github.com/CyanSalt/Sublime-Jedi/tree/1.0.0

Also make sure you:

 - [x] Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 - [x] Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
you're package looks good. Maybe add a demo in your readme: some code when your syntax is activated.

**Comment by CyanSalt** [comment]
@math2001 The readme file has been updated as well as the latest tag. Thanks a lot!

**Comment by math2001** [comment]
nice! 2 screenshot at a time. 👍 Maybe you could mention the font, color scheme bellow the image.

> A Jedi syntax highlight plugin for Sublime Text/TextMate.

I'm not sure TextMate supports `.sublime-syntax`

**Comment by CyanSalt** [comment]
@math2001 it's a typo :( . Updated again with names of the color schemes.

**Pull request merged**
