### PR TITLE
added mod-monokai-javascript theme

### PR DESCRIPTION
**Pull request by MauricioAndrades**
added new .sublime-theme based on the Monokai theme for JavaScript.

### CODE REVIEW

**Comment by FichteFoll** [comment]
The tests don't pass: https://packagecontrol.io/docs/submitting_a_package#Step_7

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by wbond** [comment]
@MauricioAndrades Ping

**Comment by MauricioAndrades** [comment]
Hey sorry will. I missed the original ticket... let me take a look. I thought I passed all test locally but obviously not. First time publishing on pkgcontrol :D

**Comment by wbond** [comment]
Feel free to open a new PR if you are still interested in having this added.

**Pull request closed without merging**
