### PR TITLE
Add package -- ASS

### PR DESCRIPTION
**Pull request by jfcherng**
https://github.com/jfcherng/Sublime-ASS

Specs: http://www.matroska.org/technical/specs/subtitles/ssa.html

# Sublime-ASS
ASS/SSA subtitles syntax highlight for Sublime Text >= 3092

screenshot

### CODE REVIEW

**Comment by FichteFoll** [comment]
Nice, I've wanted to write one for ASS for years but never got around to it because it was really low priority for me. I just skimmed over it a bit and don't exactly agree with some of your scope choices, but I will file a pull request when I end up using it probably.

For searchability, you might want to consider the name "Advanced Substation Alpha" because "ass" is part of "assembler".

**Comment by jfcherng** [comment]
> I just skimmed over it a bit and don't exactly agree with some of your scope choices, but I will file a pull request when I end up using it probably.
I chose the scope just because of the color on my own theme, in fact.
PRs are welcome.

> For searchability, you might want to consider the name "Advanced Substation Alpha" because "ass" is part of "assembler".
Good suggestion.

**Comment by jfcherng** [comment]
But to search 'Advanced Substation Alpha', it may type 'ASA'.
Is 'Advanced Substation Alpha (ASS)' acceptable?

**Comment by FichteFoll** [comment]
Yes, that's also fine

**Pull request merged**
