### PR TITLE
Add Materialize-Appbar

### PR DESCRIPTION
**Pull request by saadq**

### CODE REVIEW

**Comment by saadq** [comment]
In case there is any confusion, Materialize-Appbar is a fork of equinusocio's Material-Appbar, but this new one is compatible with all of the themes in [Materialize](https://github.com/saadq/Materialize).

**Comment by FichteFoll** [comment]
Why does this package have a `.no-sublime-package` file?

cc @equinusocio

**Comment by saadq** [comment]
I pretty much just followed the way that equinusocio did it, and I'm not too sure but I think it's because this add-on to the themes is just used to overwrite a few of the settings on the theme files and would need to go into the `Packages` folder to do so (this is my guess).

**Comment by equinusocio** [comment]
It's right. Like Material Theme White Panels the package overwrite some of the original theme rules.

**Comment by FichteFoll** [comment]
Hm, okay. Themes are the one thing I never touched, so I have to rely on your information here.

**Pull request merged**
