### PR TITLE
Add OpenDSS Script Syntax

### PR DESCRIPTION
**Pull request by dparrini**

### CODE REVIEW

**Comment by Thom1729** [comment]
Please fix the above.

**Comment by Thom1729** [comment]
@dparrini ping.

**Comment by dparrini** [comment]
Sorry for taking so long. Just added the .tmLanguage fallback file.

**Comment by FichteFoll** [comment]
The other option would have been to just limit installation to a non-ancient ST3 build, i.e. anything >=3092.

Either way, you need to push a new tag with your changes.

**Comment by Thom1729** [comment]
@dparrini Please push a new tag.

**Comment by FichteFoll** [comment]
And please resolve the conflict as well.

**Pull request merged**
