### PR TITLE
Add enum34, ipython_genutils, jupyter_client, six, and traitlets dependencies

### PR DESCRIPTION
**Pull request by eivind88**
Repos and tags pages:

https://github.com/eivind88/sublime-enum34
https://github.com/eivind88/sublime-enum34/tags

https://github.com/eivind88/sublime-ipython_genutils
https://github.com/eivind88/sublime-ipython_genutils/tags

https://github.com/eivind88/sublime-jupyter_client
https://github.com/eivind88/sublime-jupyter_client/tags

https://github.com/eivind88/sublime-six
https://github.com/eivind88/sublime-six/tags

https://github.com/eivind88/sublime-traitlets
https://github.com/eivind88/sublime-traitlets/tags

### CODE REVIEW

**Comment by FichteFoll** [comment]
In your repositories you always use the `all/` folder, yet you list ST3 as being required for all of these in this PR.

For `enum34` I know that it is compatible with 2.6 (ST2) as well, but I don't know about the others.

**Comment by FichteFoll** [comment]
@eivind88 ping

**Comment by eivind88** [comment]
@FichteFoll Sorry - been crazy busy lately.
I know the dependencies are compatible with ST3, but I'll have to look into compatibility with earlier versions.

**Comment by FichteFoll** [comment]
All right, your acknowledge was all I needed.

**Comment by FichteFoll** [comment]
Just tell me when you get around to adjusting the version restrictions or the folder names.

**Pull request closed without merging**
