### PR TITLE
Update WoW Development package

### PR DESCRIPTION
**Pull request by Resike**

### CODE REVIEW

**Comment by evandrocoan** [comment]
@Resike, branch based packages are not supported anymore. You can you push a git tag like 1.0.0 and set `"tags": true`, instead of `"branch": "master"`?

@frodzet, had you given up the package maintaining to @Resike?

Can you guys considering adding some OSS license?

**Comment by evandrocoan** [comment]
@FichteFoll, I see no tags on https://github.com/Resike/WoWDevelopment/releases and no error from the @packagecontrol-bot, perhaps the @packagecontrol-bot is on vacation?

**Comment by Resike** [comment]
Should i make a tag?

**Comment by evandrocoan** [comment]
Yes, without it does not work. 

See this link for more information on how to create git tags:
* https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

**Comment by FichteFoll** [comment]
@evandrocoan, the package checks are only run on new packages, not on modified packages. That's mostly because we don't force older packages to adapt to our new standards, although we encourage them to do so.

**Comment by Resike** [comment]
Any way i can mark the package not to get packaged into a sublime-package? Since it has multiple exe files that needs to be accessed somehow.

**Comment by FichteFoll** [comment]
If you need to launch bundled .exe files from within the package, add a `.no-sublime-package` file (content doesn't matter) to your repo and create a new tag.

**Comment by Resike** [comment]
Okay one more question is there any way to make the project's folder to be WoWDevelopment instead of WoW Development?

**Comment by FichteFoll** [comment]
The folder name is determined from the package's name, indeed. You can rename your package by changing the name key and adding a `previous_names` array to reference the old name.

**Comment by Resike** [comment]
Can i change that with another PR? Or do i need to create a new package?

**Comment by evandrocoan** [comment]
Do another pull request changing the package name like this:
```json
		{
			"name": "WoWDevelopment",
			"details": "https://github.com/frodzet/SublimeWoWDevelopment",
			"details": "https://github.com/Resike/WoWDevelopment",
			"previous_names": ["WoW Development"]
			"releases": [
				{
					"sublime_text": "*",
					"branch": "master"
					"tags": true
				}
			]
		},
```

**Pull request merged**
