### PR TITLE
Added JsonL18nResourcesEditor package

### PR DESCRIPTION
**Pull request by alex18881**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your code/package does not appear to require a `.no-sublime-package` file, please remove it.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by alex18881** [comment]
Done.  Verify please.
Thanks. Alex.

ср, 25 Ноя 2015, 0:53, FichteFoll <notifications@github.com>:

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
Also, please note that people won't be able to find your package in Sublime Text unless they specifically enabled downloading pre-releases for it.

**Comment by alex18881** [comment]
Do I have to recreate pull requests each time I release new version?

**Comment by FichteFoll** [comment]
No, Package Control automatically detects when you push a higher-versioned tag to your repo. It can take up to one hour however.

**Pull request merged**
