### PR TITLE
Add package Angular Material Snippets

### PR DESCRIPTION
**Pull request by devotis**

### CODE REVIEW

**Comment by FichteFoll** [comment]
There is only one snippet in this package?

You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by devotis** [comment]
More snippets are coming soon.

There are 3 parts to your instruction. I know how to implement only the first.
> You'll need to change "branch": "master" to "tags": true.

That's clear. Changed that locally for now in the definition of my package in  /package_control_channel/repository/a.json
> and use tags to create releases

In what file do I add tags?
> and push valid semantic version tags to your repo.

You mean in a `package.json` file in my repository? Your docs say: *"If you chose manual package hosting, you will need to use semantic versioning in your packages.json file."* Where is defined what a manual package is? In lots of other repositories for ST packages I don't see a `package.json` file, but a `messages.json` file like [this one](https://github.com/rs459/bootstrap3-jade-sublime-plugin/blob/master/messages.json). Is that how to add semantic version tags?

**Comment by FichteFoll** [comment]
Git has a feature called "tagging": http://git-scm.com/book/en/v2/Git-Basics-Tagging

When you see your tags on https://github.com/devotis/sublime-angular-material-snippets/tags, you know you've been successful.

**Comment by devotis** [comment]
All done. Working on more snippets....

So when I'm done creating more snippets, I commit that, push that to master on Github and add a new tag (version) and it gets available to ST users?

**Comment by FichteFoll** [comment]
Correct.

**Pull request merged**
