### PR TITLE
Added Metaphor Snippets

### PR DESCRIPTION
**Pull request by a13xemz**
Please provide the following information:

 - Link to your code repository:
https://github.com/csun-metalab/metaphor-snippets
 - Link to the tags page with at least one [semver](http://semver.org) tag: 
https://github.com/csun-metalab/metaphor-snippets/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
'.sublime-package' files have no business being inside a package. Please remove it.

Package Control will download a snapshot of the repo and use that as base for creating a '.sublime-package' archive on the user's machine.

**Comment by FichteFoll** [comment]
@a13xemz ping

**Comment by a13xemz** [comment]
Changes where made

**Comment by FichteFoll** [comment]
You need to add a new tag with that change.

**Comment by FichteFoll** [comment]
@a13xemz ping

**Pull request closed without merging**
