### PR TITLE
Added Matlab completions

### PR DESCRIPTION
**Pull request by tushortz**
* Updated M.json

### CODE REVIEW

**Comment by FichteFoll** [comment]
I don't think https://github.com/tushortz/Java-Methods-Completion should be in this, or should it? Because i 404s.

**Comment by tushortz** [comment]
It shouldnt be there. I've removed it or does it still appear there

**Comment by tushortz** [comment]
Coz I closed the pull request and added the methods completion as an extra
file to JavaIME

**Comment by FichteFoll** [comment]
From the commit history, it seems that you just merged wbond/master into your branch, which still contained the addition of the Java package.

You should create new branches when working on pull requests.

**Comment by tushortz** [comment]
Should I remove it and recreate a pull request

**Comment by FichteFoll** [comment]
Yes

**Pull request closed without merging**
