### PR TITLE
Add LeekScript Syntax

### PR DESCRIPTION
**Pull request by GuimDev**
Hi !

information:  
 - Link to your code repository: https://github.com/GuimDev/LeekScript-Sublime
 - Link to the tags page with at least one [semver](http://semver.org) tag: 
    - https://github.com/GuimDev/LeekScript-Sublime/tags
    - https://github.com/GuimDev/LeekScript-Sublime/tree/1.0

Thanks.

### CODE REVIEW

**Comment by GuimDev** [comment]
Sorry I forgot to add tag.

**Comment by rwols** [comment]
You may also want to restrict to windows and Linux, because it looks like [this](https://github.com/GuimDev/LeekScript-Sublime/blob/master/LeekScript.py#L7) won't work on OSX as it doesn't have a `start` command (that only works on windows).

Consider also using `sublime.platform()` to check for `"linux"`, `"osx"`, or `"windows"`.

**Comment by GuimDev** [comment]
Thanks. I update my code.

The mainly goal is to syntax highlight.

**Comment by wbond** [comment]
The tags need to be valid [semver](http://semver.org). In other words, they need three numeric parts.

**Comment by GuimDev** [comment]
I edited the tags.

**Comment by wbond** [comment]
@GuimDev You'll need to delete the file `package-metadata.json` from your repository.

**Comment by GuimDev** [comment]
I remove it

**Comment by wbond** [comment]
You'll need a new tag, then I can re-trigger the test bot for you

**Comment by GuimDev** [comment]
I make a new tag.

Sorry for this, thank you for your time.

**Pull request merged**
