### PR TITLE
Add 'Programatic Key Binding' plugin

### PR DESCRIPTION
**Pull request by VonHeikemen**
This plugin allows the user the ability to declare their keybindings using Python

### CODE REVIEW

**Comment by braver** [comment]
Hi, thanks for your submission. Sorry if I'm slow, but just so I understand what you're providing here, why would someone use your package to edit keybindings instead of editing them manually? Ie. your README does a pretty good job of explaining how everything works, but maybe an example use case would help "visualise" it :)

**Comment by VonHeikemen** [comment]
For me the main benefit comes from the ability to use variables. I have a lengthy configuration which became a bit of a pain to manage in a json format. I wanted a way to store "context objects" to do something like this:

```python
def keybinding(bind):
  # Navigate the sidebar vim-style 
  bind(["h"], "move", sidebar_focused, by="characters", forward=False)
  bind(["l"], "move", sidebar_focused, by="characters", forward=True)
  bind(["k"], "move", sidebar_focused, by="lines", forward=False)
  bind(["j"], "move", sidebar_focused, by="lines", forward=True)

# Context objects
sidebar_focused = {
  "key": "control",
  "operand": "sidebar_tree"
}

#  more code ...
```

In this short example it may not look like a big deal but if you have 15 context objects (and many bindings), having them in variables with meaningful names it's really useful.

A nice side effect of this approach is that we can use functions, for loops, conditionals... so if you wanted to take it one step further, you could do it.

```python
def keybinding(bind):
  # use `ctrl+k` and `ctrl+j` to move up and down everywhere
  move(bind, up=["ctrl+k"], down=["ctrl+j"])

  # more bindings ....

def move(bind, up=[], down=[]):
  contexts = [
    sidebar_focused,
    overlay_focus,
    auto_complete
  ]

  for ctx in contexts:
    bind(up, "move", ctx, by="lines", forward=False)
    bind(down, "move", ctx, by="lines", forward=True)


# Context objects
sidebar_focused = {
  # ...
}

overlay_focus = {
  # ...
}

auto_complete = {
  # ...
}
```

**Comment by braver** [comment]
Nice, sounds useful 👍🏻

**Comment by braver** [comment]
Shouldn’t it be “programmatic”, double m?

**Comment by VonHeikemen** [comment]
you're right, it should be double m. I'll fix that.

**Comment by braver** [comment]
🤔 final consideration, because you can’t easily change it later: maybe the storage dir for the keybindings should be named after the package name (instead of the repo name)?

**Comment by VonHeikemen** [comment]
ok. It has been updated.

**Pull request merged**
