### PR TITLE
Specify the readme description

### PR DESCRIPTION
**Pull request by harryngh**
for WordCount & WordHighlight package

### CODE REVIEW

**Comment by FichteFoll** [comment]
WordHighlight has its readme displayed on the site just fine: https://packagecontrol.io/packages/WordHighlight

Regarding the other change, cc @titoBouzout.

**Comment by harryngh** [comment]
Hi Tito please accept my proposal of displaying the readme for WordCount package on packagecontrol. Thank you very much!

**Comment by FichteFoll** [comment]
@harryngh please remove the addition of the readme key for the WordHighlight package.

**Comment by harryngh** [comment]
The update is made.
Thank you @FichteFoll

**Comment by titoBouzout** [comment]
Hi there  thank you both =) 

kind regards

**Pull request merged**
