### PR TITLE
Add Pawn Kit package

### PR DESCRIPTION
**Pull request by punkochel**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***

My package is a fork of the Pawn syntax package, which is adapted for OpenMP-server development.

It should be added because it contains many updated completions and snippets.
The Pawn syntax package contains development tools for SA:MP, so it can't be updated in the interests pawn-developers for SA:MP.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by punkochel** [comment]
@packagecontrol-bot

**Comment by braver** [comment]
Thanks for your submission. Please re-read the recommendations regarding [key bindings and the command palette](https://github.com/wbond/package_control_channel/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by punkochel** [comment]
@packagecontrol-bot

**Comment by braver** [comment]
Thanks. Can you add the pawn_build_path command to the command palette?

**Comment by punkochel** [comment]
@braver, Thanks for your support. If I understood you correctly, then everything is done.

**Comment by braver** [comment]
Please tag a new release now that you've removed that metadata file, then we're ready to ship.

**Comment by punkochel** [comment]
@braver, Thanks you for the help.
All is ready.

@packagecontrol-bot

**Comment by braver** [comment]
🎉

**Pull request merged**
