### PR TITLE
Add Hermes extension to the sublime package manager

### PR DESCRIPTION
**Pull request by callicles**
This is an extension to be able to use project-hermes from sublime.
http://project-hermes.io/

Code: https://github.com/gitlinks/hermes-4-sublime
tags: https://github.com/gitlinks/hermes-4-sublime/tags

Thank you !

### CODE REVIEW

**Comment by joshua-golub** [comment]
Callicles-

I am reviewing your package. Would you please update the README.md file in your repository to provide a more detailed explanation of what your package does? It's not obvious to me and unless I understand what it does, I can't reasonably review it.

Thanks.

-Josh

**Comment by FichteFoll** [comment]
ctrl+super+d is a default binding. Please remove it.

```
    { "keys": ["ctrl+super+g"], "command": "find_all_under" },
```

**Comment by callicles** [comment]
will get onto those, thx

**Comment by FichteFoll** [comment]
@callicles ping

**Comment by callicles** [comment]
I am not going to have time to improve that anytime soon and the plugin is out of date with our API now, I will make another pull request with an updated version later.

Thanks for looking at it.

**Pull request closed without merging**
