### PR TITLE
Add bourbon-completions

### PR DESCRIPTION
**Pull request by tysongach**
[bourbon-completions](https://github.com/tysongach/bourbon-completions) enables autocompletion for the [Bourbon Sass library](http://www.bourbon.io).

### CODE REVIEW

**Comment by wbond** [comment]
I'm planning on cleaning up some labels to help standardize. Could you remove `completions` (leaving `auto-complete`)?

**Comment by FichteFoll** [comment]
These are *just* completions, not auto-completions, though.

**Comment by wbond** [comment]
There is a difference? Looking through the labels, it seems pretty much everything is tagged auto-complete: https://packagecontrol.io/browse/labels/auto-complete.

Either way, it shouldn't be `auto-complete` and `completions`.

**Comment by FichteFoll** [comment]
I probably did not pay attention as closely as I do now regarding this, but to me, auto-completions are context-aware and provided by plugins, whereas normal completions are provided by `.sublime-completions` file.s

**Comment by wbond** [comment]
That sounds reasonable.

**Comment by tysongach** [comment]
@wbond @FichteFoll Updated! Thanks for the review.

**Comment by tysongach** [comment]
@wbond @FichteFoll Anything else I can do to get this merged?

**Pull request merged**
