### PR TITLE
re: request add css intellisense

### PR DESCRIPTION
**Pull request by id-sakurata**
Add CSS Intellisense

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [ ] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is CSS Intellisense

My package is similar to "IntelliSense for CSS class names in HTML" from vscode plugin. However it should still be added because it can make it easier to develop html without remembering the complete css class. you can use autocomplete from Css Intellisense.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
There are various important points in that checklist still open. Please ensure you covered all of that and then report back.

**Comment by braver** [comment]
I see you addressed most feedback from the [previous PR](https://github.com/wbond/package_control_channel/pull/8939). It's looking pretty good now, let's just see how it does out in the wild 😉

**Comment by id-sakurata** [comment]
> I see you addressed most feedback from the [previous PR](https://github.com/wbond/package_control_channel/pull/8939). It's looking pretty good now, let's just see how it does out in the wild 😉

I really thank you for accepting my request. I can now recommend this plugin to my work friends 😆.

and now how do i update my plugin, i just found a problem when updating the settings, and now i have fixed the problem in the new update.

**Comment by braver** [comment]
> how do i update my plugin

Any time you create a tag (with a higher version number), that will get pushed to users (typically when they start ST, or when they manually check for updates).

**Pull request merged**
