### PR TITLE
OpenedFiles package added

### PR DESCRIPTION
**Pull request by qiray**
## OpenedFiles plugin:

Plugin for Sublime Text to show opened files as a treeview or a listview.

### CODE REVIEW

**Comment by qiray** [comment]
Hm. The project had some errors, I fixed them and restarted request. @packagecontrol-bot now shows only warnings but I still have "All checks have failed" message. Is that correct?

**Comment by qiray** [comment]
Restarted again, now it's all right.

**Comment by FichteFoll** [comment]
So, what are the improvements over FileBrowser?

**Comment by qiray** [comment]
@FichteFoll, FileBrowser shows full tree for opened directory or project - all files and subdirs:

FileBrowser image

But OpenedFiles shows only opened files:

OpenedFiles image

In some large projects (or when you work at multiple projects simultaneously) it's very comfortable to see only few currently opened files instead of large directory with multiple subdirs and files. I found this feature in [Kate editor](https://kate-editor.org/) and [Geany](https://www.geany.org/) and I think it's useful.

**Pull request merged**
