### PR TITLE
Update MKB Package Information

### PR DESCRIPTION
**Pull request by KeeMeng**
Sorry for new pull request :/
Hopefully this is ok for merging

### CODE REVIEW

**Comment by braver** [comment]
Why do you require 2 different (but mostly the same) README's?

**Comment by KeeMeng** [comment]
The readme for the github page includes other information which package control does not need, such as manual installation, and also the table feature of markdown doesn't seem to work on package control. 
Hope this is understandable 😀

**Comment by braver** [comment]
Oh, usually it's understood that the manual installation part doesn't apply to package control. It's still good information if someone finds the package via package control. It doesn't hurt to have it and it simplifies a lot to have just one file with that info.

Simple tables tend to work just fine. For example: https://github.com/SublimeLinter/SublimeLinter#key-bindings vs. https://packagecontrol.io/packages/SublimeLinter

**Comment by braver** [comment]
⛵

**Pull request merged**
