### PR TITLE
Add TabNine package.

### PR DESCRIPTION
**Pull request by zxqfl**
Link to code (for the Sublime Text frontend, the backend is closed source): https://github.com/zxqfl/tabnine-sublime/
Link to main website: https://tabnine.com

### CODE REVIEW

**Comment by zxqfl** [comment]
Added a tag 0.1.0 to https://github.com/zxqfl/tabnine-sublime/tags.

**Comment by Thom1729** [comment]
It's not clear to me that Package Control can/should redistribute the binaries without an explicit license. @FichteFoll?

**Comment by zxqfl** [comment]
@Thom1729 I tried to address your concerns by adding a note saying that the binaries are covered by https://tabnine.com/eula, which explicitly permits redistribution of unmodified copies.

As the copyright holder I would not want to file any kind of claim against Package Control in any case, since I want my software to be distributed as widely as possible. But I understand why you would want an explicit guarantee.

**Comment by zxqfl** [comment]
Added a new release 0.2.0 with bug fixes and usability improvements.

**Pull request merged**
