### PR TITLE
Adding Broceanic

### PR DESCRIPTION
**Pull request by kenwheeler**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Well, you kind of updated the fork but I figured you would notice the difference between your addition and every package around it. Just replace `"details": "https://github.com/kenwheeler/broceanic-theme/tree/master"` with `"tags": true`

**Comment by kenwheeler** [comment]
@FichteFoll Sorry about that, fixed

**Comment by FichteFoll** [comment]
Now you only need to fix order: https://travis-ci.org/wbond/package_control_channel/builds/67548418#L158

**Comment by kenwheeler** [comment]
@FichteFoll done

**Comment by kenwheeler** [comment]
@FichteFoll sorry about all that

**Pull request merged**
