### PR TITLE
add meld compare plugin

### PR DESCRIPTION
**Pull request by scott1028**

### CODE REVIEW

**Comment by scott1028** [comment]
add tag 1.0.0

**Comment by scott1028** [comment]
update message.json

**Comment by FichteFoll** [comment]
You could replace the https://packagecontrol.io/packages/Meld%20diff package, which seemingly has been deleted a while ago. Remove the corresponding entry from `channel.json` where this was referenced and then either take the name of that package or alternatively add a `previous_names` array to get users of that package to switch over to yours, if there are any still.

In your `plugin_loaded`, you should check for `os.path.exists(settings().get('meld_compare_path'))` in the first branch as you don't want to override user configuration on every restart. Actually, you could just use the manual search for the executable as a backup when no valid exeutable has been specified instead of saving the setting on disk. That way users don't need to have the settings file when they use the default location anyway. Also, I believe that you should prioritize the 64 bit version.

`is_windows` computes a static value that never changes, so you could just assign that to a variable directly instead of wrapping it inside a function.

**Comment by FichteFoll** [comment]
@scott1028 ping

**Pull request closed without merging**
