### PR TITLE
Adding InstaGoogling Plugin

### PR DESCRIPTION
**Pull request by Ivanca**
https://github.com/Ivanca/InstaGoogling

### CODE REVIEW

**Comment by math2001** [comment]
If you want your package to be accepted, you're going to have to add a `README.md`.

**Comment by Ivanca** [comment]
@math2001 Done.

**Comment by math2001** [comment]
Great! Super readme!

**Comment by math2001** [comment]
Try to find an other shortcut to close the popup: `ctrl+w` is a default shortcut that closes the current tab, and I use it all the time. Maybe `alt+w`.

**Comment by Ivanca** [comment]
@math2001 That's the magic, It only uses the `ctrl+w` shortcut when the Chrome pop-up is open, otherwise it does the default thing (close the current tab or whatever the user configigured to)

This also helps because if the browser is the one focuses then it gets closed (cause `ctrl+w` is how you close tabs in chrome as well)

**Comment by Ivanca** [comment]
BTW I just fixed the travis build issue (`.git` was erroneously there)

**Comment by Ivanca** [comment]
@math2001 ?

**Comment by math2001** [comment]
Sorry, I'm busy. Yep you're shortcut is, now that you say that, way better. You should add this explanation in your readme, something like this:

```
# why `ctrl+w`, it's already used by sublime text!?
...
```

**Comment by Ivanca** [comment]
@math2001 Explication added. 

BTW please accept the PR soon, thanks!

**Comment by Ivanca** [comment]
@math2001

**Comment by math2001** [comment]
I can't really do anything... @FichteFoll is (or was since he wants to cool down on this) the one of those that can accept your PR.

**Comment by FichteFoll** [comment]
Pywin32 is available as a [dependency for Package Control](https://github.com/randy3k/sublime-pywin32). I highly suggest using that instead of bundling your own (and modifying `sys.path`), unless there is a certain reason why you can't use that.
For SimpleWebSocketServer you can just use a relative import like `from .libs.SimpleWebSocketServer import SimpleWebSocketServer, WebSocket` and remove the `sys.path` modifications.

**Comment by Ivanca** [comment]
@FichteFoll I understand. 
Changes done (https://github.com/Ivanca/InstaGoogling/commit/3e1bc30afc6d92de300abf3c99ba84250c09fd4a)

**Comment by FichteFoll** [comment]
Don't forget to push a new tag with the changes.

**Comment by Ivanca** [comment]
ok, done

**Comment by Ivanca** [comment]
https://github.com/Ivanca/InstaGoogling/releases

**Comment by Ivanca** [comment]
@FichteFoll

**Pull request merged**
