### PR TITLE
Add gerardroche/sublime-phpunit

### PR DESCRIPTION
**Pull request by gerardroche**
This is similar to stuartherbert/sublime-phpunit which may at some point incorporate the features in this package, it has already added some features but it supports ST2 which means its codebase is much very complicated. It was easier to write a plugin from scratch only supporting ST3 with the features I wanted.

Originally the package name was phpunit but that conflicts with the other package so I renamed it to "php_phpunit" because honestly I didn't know what else to name it.

### CODE REVIEW

**Comment by FichteFoll** [comment]
"phpunit" and "php_phpunit" are too similar for my taste. There is also "SimplePHPUnit" already.

Maybe something like "phpunitizer" or similar a variation.

**Comment by gerardroche** [comment]
How about phpunit_tools?

**Comment by FichteFoll** [comment]
Either would work.

**Comment by gerardroche** [comment]
Thanks. I went with `phpunitkit`.

**Comment by gerardroche** [comment]
ping @FichteFoll This ready to merge. Thanks.

**Pull request merged**
