### PR TITLE
Add GobuildEx plugin package json

### PR DESCRIPTION
**Pull request by jerrytaffy**
This is a Sublime Text plugin with Golang develop. He difference is that, before it will be killed your process. He is a very very very simple plugin.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Tests are failing: https://travis-ci.org/wbond/package_control_channel/builds/96558693

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

Why do you not add this to an existing package instead?

**Comment by FichteFoll** [comment]
@jerrytaffy ping

**Comment by jerrytaffy** [comment]
ping??? How ping??? Terminal ping command???

**Comment by FichteFoll** [comment]
@jerrytaffy I was simply asking you to address the issues I raised in my earlier comment. "pinging" is usually done to check whether your communication partner is still available, which is normally common for software but also occasionally used for person-to-person communication.

**Pull request closed without merging**
