### PR TITLE
"Preap" dark theme and syntax

### PR DESCRIPTION
**Pull request by equinusocio**
Added "Preap" theme package

### CODE REVIEW

**Comment by equinusocio** [comment]
New awesome dark theme added!

**Comment by equinusocio** [comment]
@FichteFoll Hi, there's a reason why my package does not appear in the list of available packages? I done something wrong?

**Comment by FichteFoll** [comment]
Ah, yes. I didn't notice it in my initial scan, but your tags currently have the format `v.major.minor.patch` whereas PC by default only finds `vmajor.minor.patch` and `major.minor.patch`. You eather need to fix the tags (I've never seen that naming scheme before) or adjust the release here to specify `"tags": "v."` so that PC will find the prefix you used.

**Comment by equinusocio** [comment]
Ok! Thanks. I will simple update the release prefix. Thanks!

**Pull request merged**
