### PR TITLE
MyC Build

### PR DESCRIPTION
**Pull request by Haiquan-27**
This sublime plug-in is for C language debugging and compilation
Deleted the conflicting shortcut [F9]

developer: Haiquan(3570670889@qq.com)

### CODE REVIEW

**Comment by Haiquan-27** [comment]
LICENSE file added

**Comment by braver** [comment]
Thanks!

I believe you have a typo here (builE instead of builD):
https://github.com/Haiquan-27/Sublime-MyC/blob/main/Main.sublime-menu#L16

You seem to do some wrangling of the Context.sublime-menu file [here](https://github.com/Haiquan-27/Sublime-MyC/blob/main/My%20C.py#L44). I'm not sure what that's for, but I'm not sure that works when your package is delivered in a archived format. E.g. you can't write to the package. You _can_ find and read resources (see: https://www.sublimetext.com/docs/3/api_reference.html#sublime). However, I'm not sure what your code tries to accomplish and therefore can't really point you in the right direction.

**Comment by Haiquan-27** [comment]
Thank you for your tips. 
It's really a mistake. I've corrected it and reissued 0.3.0tag and added comments to some major files

**Comment by Haiquan-27** [comment]
Thank you for your tips.
 It's really a mistake. I've corrected it and reissued 0.3.0tag and added comments to some major files



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Koen Lageveen"<notifications@github.com&gt;; 
发送时间: 2021年1月8日(星期五) 凌晨1:11
收件人: "wbond/package_control_channel"<package_control_channel@noreply.github.com&gt;; 
抄送: "猴哥"<3570670889@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wbond/package_control_channel] MyC Build (#8152)






谢啦！

我相信你这里打错字了（buildE而不是buildD）：
https://github.com/Haiquan-27/Sublime-MyC/blob/main/Main.sublime-menu#L16

您似乎对Context.sublime-menu文件做了一些争论在这里.我不知道那是什么，但我不确定当您的包是以存档格式交付时是否有效。你不能给包裹写信。你可以查找并阅读资源（请参阅：https://www.sublimetext.com/docs/3/api_reference.html#sublime).然而，我不确定您的代码试图实现什么，因此不能真正为您指出正确的方向。

—
你收到这个是因为你编写了这个线程。
直接回复此邮件，在GitHub上查看，或取消订阅.

**Comment by Haiquan-27** [comment]
> 
> 
> Thanks!
> 
> I believe you have a typo here (builE instead of builD):
> https://github.com/Haiquan-27/Sublime-MyC/blob/main/Main.sublime-menu#L16
> 
> You seem to do some wrangling of the Context.sublime-menu file [here](https://github.com/Haiquan-27/Sublime-MyC/blob/main/My%20C.py#L44). I'm not sure what that's for, but I'm not sure that works when your package is delivered in a archived format. E.g. you can't write to the package. You _can_ find and read resources (see: https://www.sublimetext.com/docs/3/api_reference.html#sublime). However, I'm not sure what your code tries to accomplish and therefore can't really point you in the right direction.

Thank you for your tips.
It's really a mistake. I've corrected it and reissued 0.3.0tag and added comments to some major files

**Comment by braver** [comment]
Oh, I forgot. The non-functional files in your repo, like MyC.mp4, should be removed from the package via [.gitattributes](https://www.git-scm.com/docs/gitattributes). This saves disk space and download times. 

I'm still a bit concerned about [MyCsContextMenuTopToggleCommand](https://github.com/Haiquan-27/Sublime-MyC/blob/0.3.0/My%20C.py#L28). Packages are shipped in an archived format, meaning that you can't read or write files like you can if you would just put your repo in Packages (like you would do for development). I'm not sure what "My C: context menu top toggle" does?

**Comment by Haiquan-27** [comment]
@braver 

This function is very simple, that is, By changing“ Context.sublime -Menu file: ["Id": "end"] or ["Id": "] to control the [my C] item in the right-click menu to display at the top or bottom of the menu
Like:
If "Id": "end": My C menu will be displayed at the bottom of the right-click menu
If "Id": ": My C menu will be displayed above the right-click menu

You can try it with the right mouse button, but my menu is in Chinese
(right click >My C  > 顶置/底置右键菜单)
(right click > My C > Top / bottom right click menu)

This is a more "rough" method, but this function is really useful. For example, some people like to click the mouse to execute commands

**Comment by Haiquan-27** [comment]
If the plug-in is installed through package control, it is installed into installed packages and packaged as "myc" Build.sublime -package"

In this way, the plug-in cannot be modified“ Context.sublime -Menu "to achieve" my_ Cs_ context_ menu_ top_ "Toggle" function, right

**Comment by Haiquan-27** [comment]
If the plug-in is installed through package control, it is installed into installed packages and packaged as "MyC Build.sublime -package"
In this way, the plug-in cannot be modified“ Context.sublime-menu"to achieve" my_ cs_ context_ menu_ top_ toggle" function, right

**Comment by rwols** [comment]
> In this way, the plug-in cannot be modified“ Context.sublime -Menu "to achieve" my_ Cs_ context_ menu_ top_ "Toggle" function, right

That is correct. You need to use `sublime.load_resource` to load resource files. That said, it's probably not a good idea to modify `Context.sublime-menu`. It's just a static resource and should not be modified dynamically.

**Comment by braver** [comment]
Ah, that clears things up. As @rwols said, these files should be considered a static resource. Put your menu entry somewhere smart and humble (ie. probably don’t take the top spot). If possible hide the entry if it isn’t applicable to a specific context. But changing its position via a command is neat but doesn’t sound like it’s worth the trouble.

**Comment by Haiquan-27** [comment]
@rwols 
@braver 

Thank you for your correction. I will redesign this function and other similar problems

**Comment by Haiquan-27** [comment]
I need to re Pull, right?
This time the request seems to have been closed

**Comment by braver** [comment]
No, this PR is fine. I closed the other one you created. Just let me know when you’ve made the changes to your package.

**Comment by Haiquan-27** [comment]
All right, thanks  👍

**Comment by braver** [comment]
@Haiquan-27 please confirm you made the requested changes.

**Pull request closed without merging**
