### PR TITLE
Add LSP-leo package.

### PR DESCRIPTION
**Pull request by dev-sptg**
Hello.
Leo is a functional, statically-typed programming language built for writing private applications.
https://leo-lang.org/
https://developer.aleo.org/developer/getting_started/overview

This package provides LSP features (diagnostics, completions, hovers, go-to definitions, semantic highlights) and also a theme for syntax token coloring.

### CODE REVIEW

**Comment by rwols** [comment]
Thanks for adding a helper package for LSP.

To understand why you would need a separate channel, I took a look at what's inside https://leo-lsp-packages.sfo2.digitaloceanspaces.com/sublime-package/0.7.7/LSP-leo.sublime-package. From what I understand you seem to be bundling the server inside the package. There is therefore no need to use a `releases` array. So I would suggest you simply add an entry to https://github.com/sublimelsp/repository/

What's more, the LSP package should at some point use the newer plugin_host-3.8 host. This requires all helper packages to be updated in one fell swoop as well. I would therefore request your package to be part of this organization: https://github.com/sublimelsp. Let me know when you're ready to receive an invite.

**Comment by dev-sptg** [comment]
I have a few questions:
1 - If I delete an array of releases from the file https://leo-lsp-packages.sfo2.digitaloceanspaces.com/sublime-package/latest/LSP-leo.json how will the package update work? Please explain because I do not understand how package updates work.

2 - Should I close this PR and open a new one in the repository https://github.com/sublimelsp/repository/? Can I also add an entry from MANUAL HOSTING in this repository, because I only see queries from GitHub there?

3 - I have my own private repository. Should I make it public?

4 - Do I need to create an LSP-leo repository at https://github.com/sublimelsp and push releases there?

**Comment by rwols** [comment]
> 1 - If I delete an array of releases from the file https://leo-lsp-packages.sfo2.digitaloceanspaces.com/sublime-package/latest/LSP-leo.json how will the package update work? Please explain because I do not understand how package updates work.

It works based on git tags. Each git tag should be in the form of a semantic version: $major.$minor.$path, e.g. 1.0.2. When Package Control detects a newer version, it takes the .zip source in the release assets and renames it to .sublime-package.

> 2 - Should I close this PR and open a new one in the repository https://github.com/sublimelsp/repository/?

Yes.

> Can I also add an entry from MANUAL HOSTING in this repository, because I only see queries from GitHub there?

You can, but like I mentioned it's not actually necessary to do that.

> 3 - I have my own private repository. Should I make it public?

If it's going in github.com/sublimelsp then it's going to be public.

> 4 - Do I need to create an LSP-leo repository at https://github.com/sublimelsp and push releases there?

Yes please. I'll create one and invite you as admin.

**Comment by dev-sptg** [comment]
I would like to keep the sources in a private repository and deploy the release to Digital Ocean. So I will close this PR and create a new one at https://github.com/sublimelsp/repository/.

**Comment by rwols** [comment]
Alright, sounds good to me. Be prepared to make a new git tag and release once LSP switches to the py38 runtime.

**Comment by dev-sptg** [comment]
Before closing this PR and opening a new one at https://github.com/sublimelsp/repository, I want to clarify how the release will take place.
I have a condition that the LSP-leo repository must be private. That's why I'm releasing the package into Digital Ocean as an archive.
I researched https://github.com/sublimelsp/repository and didn't see channels.json there. So I came to the conclusion that my only option is to add an entry to repository.json. Therefore, I plan to place the contents of the file https://leo-lsp-packages.sfo2.digitaloceanspaces.com/sublime-package/latest/LSP-leo.json in https://github.com/sublimelsp/repository/repository.json.
With this approach, I will need to do a new PR for each release and add a new object to the release array.
Do I understand correctly that the only way to not do a new PR for each release is to push sources into https://github.com/sublimelsp/LSP-leo and make a release with a tag there?

**Comment by rwols** [comment]
> I researched https://github.com/sublimelsp/repository and didn't see channels.json there. So I came to the conclusion that my only option is to add an entry to repository.json. Therefore, I plan to place the contents of the file https://leo-lsp-packages.sfo2.digitaloceanspaces.com/sublime-package/latest/LSP-leo.json in https://github.com/sublimelsp/repository/repository.json.

Yeah, unfortunately if you want the repo to stay private then you'd have to create a PR for each new .sublime-package.

> Do I understand correctly that the only way to not do a new PR for each release is to push sources into https://github.com/sublimelsp/LSP-leo and make a release with a tag there?

That's correct.

I don't understand why the package must be private. Anyone can unzip the .sublime-package and inspect the contents for instance. The bundled server files are WebAssembly, so those files remain "private" even if they're pushed to a public repository.

If the package is public, we can provide suggestions for improvement. One such suggestion is to not use `view.assign_syntax` in your event listener for reasons I won't go into here.

**Pull request closed without merging**
