### PR TITLE
Added the Auro Theme

### PR DESCRIPTION
**Pull request by Ryan-da-ghost**
This is a beautiful Sublime text 3 theme :) Its blue/dark and supports most languages

- PHP
- HTML
- CSS
- JSON
- TXT
- .Htaccess
- And more

### CODE REVIEW

**Comment by Ryan-da-ghost** [comment]
semver tags?

**Comment by braver** [comment]
Yes, [semver](https://semver.org) tags. So in GitHub create a release and if it's your first 0.1.0 is usually a good version number.

What you've made here is what's called a "color scheme" in Sublime Text. A "theme" is for the main application UI, a color scheme controls the colours of the code.

You probably want to add the "color scheme" labels to make your package easier to find.

You're also still using a tmTheme file. If you're only targeting Sublime Text, you'll want to convert that to a sublime-color-scheme file. That format supports variables and is a 1000x easier to maintain. You can do a conversion within Sublime Text via the Tools>Developer menu.

We already have an Aurora package, so you need to look for a different name I'm afraid.
https://packagecontrol.io/packages/Aurora%20Color%20Scheme

If you want people to try your color scheme, it's a good idea to put a screenshot in your readme.

**Comment by Ryan-da-ghost** [comment]
> Yes, [semver](https://semver.org) tags. So in GitHub create a release and if it's your first 0.1.0 is usually a good version number.
> 
> What you've made here is what's called a "color scheme" in Sublime Text. A "theme" is for the main application UI, a color scheme controls the colours of the code.
> 
> You probably want to add the "color scheme" labels to make your package easier to find.
> 
> You're also still using a tmTheme file. If you're only targeting Sublime Text, you'll want to convert that to a sublime-color-scheme file. That format supports variables and is a 1000x easier to maintain. You can do a conversion within Sublime Text via the Tools>Developer menu.
> 
> We already have an Aurora package, so you need to look for a different name I'm afraid.
> https://packagecontrol.io/packages/Aurora%20Color%20Scheme
> 
> If you want people to try your color scheme, it's a good idea to put a screenshot in your readme.

Its not Aurora its Auro

**Comment by braver** [comment]
> Its not Aurora its Auro

oh, damn, that's why it showed up in the search results. my bad, sorry.

**Comment by Ryan-da-ghost** [comment]
I added a new release

**Comment by Ryan-da-ghost** [comment]
@brave Tysm!

**Pull request merged**
