### PR TITLE
add mariSublime

### PR DESCRIPTION
**Pull request by cg-cnu**
Provides integration with the 3D animation software [Mari](http://foundry.com/products/mari) for sending code using command port.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please specify a name override that does not include "Sublime" as per our naming guidelines. "Mari" is still free. Following is a manual run of your reviewer, since the endpoint fails for some reason:


## Report for mariSublime #############################

### Repository checks ###

No failures

No warnings


### Package checks ###

Reporting 3 failures:
- The binding ['ctrl+m'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap
- The binding ['ctrl+m'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap
- The binding ['ctrl+m'] unconditionally overrides a default binding
    File: Default (Linux).sublime-keymap

Reporting 2 warnings:
- The package does not contain a top-level LICENSE file. A license helps users to contribute to the package.
- The command 'send_to_mariCommand' is not PascalCase
    File: mari_sublime.py
    Line: 53, Column: 1


For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/py_package_reviewer/wiki

**Comment by cg-cnu** [comment]
Hi @FichteFoll Thanks for looking into this. I fixed the Pascal case and the name override. The key bindings are still messing with the defaults. Will that be alright or need to be fixed ? If nothing works out I might just remove the default bindings and let the user set them up.

**Comment by FichteFoll** [comment]
Overriding default bindings in general is not acceptable, unless your package specifically replaces the previous behavior for that binding. Since your package does not do that, I suggest not providing a binding and instead explaining what command the user can bind by themselves. You already have a context menu and command palette entry, so maybe that will be enough for most users.

**Comment by FichteFoll** [comment]
@cg-cnu pin

**Pull request closed without merging**
