### PR TITLE
Add RubocopDaemon

### PR DESCRIPTION
**Pull request by georf**

### CODE REVIEW

**Comment by Thom1729** [comment]
Why create a new package? Could your improvements be integrated into the original?

**Comment by georf** [comment]
Sorry, I had a few days off.

The original plugin offers a completely different approach. You can't use both at the same time. Either you use the normal Rubocop process call or you use the daemon call.

**Comment by Thom1729** [comment]
- What is the purpose of `RubocopDaemonEventListener.listener_instance`?
- To test whether a file is a Ruby file, it's probably best to run `view. match_selector(0, 'source.ruby')` instead of checking syntax file names.

**Comment by Thom1729** [comment]
@georf ping.

**Comment by georf** [comment]
Ohh.. I will take a look.

**Comment by georf** [comment]
>     * What is the purpose of `RubocopDaemonEventListener.listener_instance`?

I removed this part of the code.

>     * To test whether a file is a Ruby file, it's probably best to run `view. match_selector(0, 'source.ruby')` instead of checking syntax file names.

Thank you for your hint. Now I use this method to detect the file is a ruby file.

I created a new version `v1.0.1`. Did I do this on the correct way?

**Comment by Thom1729** [comment]
In `daemon_file()`, you never close the file. It would be easiest to use a `with` block here:

```py
try:
    with open(file, "r") as stream:
        return stream.read()
except OSError:
    # whatever
```

**Comment by georf** [comment]
Thanks for your advise. I updated the repo to version 1.0.2

**Pull request merged**
