### PR TITLE
add `Chinese Words Cutter`

### PR DESCRIPTION
**Pull request by absop**
This package is a plugin to do Chinese words segmentation for Sublime Text 3.
It supply these functions
- selecting words
- removing words
- clicking to select words

### CODE REVIEW

**Comment by absop** [comment]
> ### Automated testing result: ERROR
> Repo link: [Chinese Words Cutter](https://github.com/absop/ChineseTokenizer)
> [Results help](https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks)
> 
> ```
> Packages added:
>   - Chinese Words Cutter
> 
> Processing package "Chinese Words Cutter"
>   - ERROR: The binding ['alt+left'] unconditionally overrides a default binding
>     - File: Default.sublime-keymap
>   - ERROR: The binding ['alt+right'] unconditionally overrides a default binding
>     - File: Default.sublime-keymap
>   - ERROR: The binding ['alt+shift+left'] unconditionally overrides a default binding
>     - File: Default.sublime-keymap
>   - ERROR: The binding ['alt+shift+right'] unconditionally overrides a default binding
>     - File: Default.sublime-keymap
> ```

These bindings unconditionally overrides a default binding, it is the result that this package **wanted**: **Replacing** the default `words-select/cursor-move` actions with new actions for **Chinese** specifically.

**Comment by braver** [comment]
Thank you for your submission. I don't really know enough about Chinese characters to fully understand what your package does. But a video looks really useful. Maybe you can look into cutting down that mp4 a little bit and converting to a gif you can put it in the readme?

I can understand the wish to override the keybindings, here that's probably acceptable. I always recommend putting your command in the command palette, as that is the primary place people look for such things and that way they don't have to remember the keybindings. In this package it would also make sense to repeat those commands in the main menu in a group under Edit.

The name of your package in package control and in Sublime Text will be "Chinese Words Cutter", but your README still calls it ChineseTokenizer. Be sure to also check that name if you add entries to the menu's etc.

**Comment by absop** [comment]
Hello, friend. I have modified the README, and the following screen video shows what the plugin can do.

cwc

**Comment by jfcherng** [comment]
> Thank you for your submission. I don't really know enough about Chinese characters to fully understand what your package does. But a video looks really useful. Maybe you can look into cutting down that mp4 a little bit and converting to a gif you can put it in the readme?

Basically, ST doesn't tokenize CJK (or probably any non-latin?) sentences so these default commands are useless in CJK sentences.

```js
	{ "keys": ["alt+left"], "command": "move", "args": {"by": "subwords", "forward": false} },
	{ "keys": ["alt+right"], "command": "move", "args": {"by": "subword_ends", "forward": true} },
	{ "keys": ["alt+shift+left"], "command": "move", "args": {"by": "subwords", "forward": false, "extend": true} },
	{ "keys": ["alt+shift+right"], "command": "move", "args": {"by": "subword_ends", "forward": true, "extend": true} },
```

His plugin tries to tokenize Chinese sentences and make `move` commands work.

**Pull request merged**
