### PR TITLE
Title updated to improve the way to search the package

### PR DESCRIPTION
**Pull request by gepd**
Just minor changes in the title and labels

### CODE REVIEW

**Comment by FichteFoll** [comment]
Why do you remove the labels?

**Comment by gepd** [comment]
I don't know if they are necessaries, I've looked into the labels sections in the website, and they aren't listed. Do you think I should keep them?

**Comment by FichteFoll** [comment]
I think labels are only listed if they occur three or more times. It seems like no other package besides yours defines the labels.

I'm okay with removing the labels since it's your package, but I was curious regardless. Tags should probably have a higher impact on search results (or rather have an impact in the first place) so that package descriptions in parentheses aren't needed to improve search accuracy.

Adding the term "Arduino" to your repo's description would also include it in search results for "Arduino" though.

**Comment by gepd** [comment]
Do you mean add it into the Readme file?

My confusion started because, at the beggining, I though in labels like tags, I mean they will be considered in the search results, but if I search the term `Arduino` in the web or in ST, my plugin isn't listed. The same happens with `iot` and `platformio` this last one is in the readme more than one time, so I guess it isn't working as I expected

**Comment by FichteFoll** [comment]
No, I mean this description:
img

The description is fetched from the repository and is searchable on the packagecontrol.io site.

**Comment by gepd** [comment]
Thanks!, I've just updated the description to test it, I'll wait at least a day to see  if there is any change in packagecontrol

**Comment by FichteFoll** [comment]
Changes *should* be discovered within an hour.

**Comment by gepd** [comment]
Ok, I'll close this PR because make the changes you suggested, did what I was looking for.

Thanks!

**Comment by gepd** [comment]
I'll reopen this PR, because I keep having a doubt, I just check that when I search for "arduino" or "platformio" from ST it does not show any result related with my plugin. However if I search `deviot` I can see new the description, is this a bug or is the way that PC works in ST?

**Pull request merged**
