### PR TITLE
Add SubGrep plugin

### PR DESCRIPTION
**Pull request by houcheng**

### CODE REVIEW

**Comment by jrappen** [comment]
You might want to add a `.gitattributes` file to **NOT** ship the included GIF via Package Control.

Random example:

<https://github.com/sublimelsp/LSP/blob/main/.gitattributes>

**Comment by houcheng** [comment]
> You might want to add a `.gitattributes` file to **NOT** ship the included GIF via Package Control.
> 
> Random example:
> 
> https://github.com/sublimelsp/LSP/blob/main/.gitattributes

Hi,
I've added the file. Thank you.

**Comment by braver** [comment]
We don't recommend shipping with keybindings, especially for packages that don't completely need them. They tend to conflict with those of other packages, or even existing defaults. Just make sure your commands are in the command palette, that's enough for most users. Then maybe document how to make the bindings in the README, so users can choose their own bindings.

**Comment by braver** [comment]
Please respond to the feedback to continue this PR.

**Pull request closed without merging**
