### PR TITLE
Added JavascriptLogSnippets package

### PR DESCRIPTION
**Pull request by Vall3y**
Javascript Log Snippets

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/Logger%20Snippets seems very similar. Maybe you want to add some snippets there instead?

**Comment by Vall3y** [comment]
@FichteFoll It's been 2 weeks since I've submitted a PR. I also mailed the author. It doesn't seem like it would be merged any time soon

**Comment by FichteFoll** [comment]
All right, if the author is not responsive there's nothing we can do about it.

**Comment by Vall3y** [comment]
Woops, all done

**Pull request merged**
