### PR TITLE
Adds Copy To SharePoint Root

### PR DESCRIPTION
**Pull request by eakron**
Adds a simple helper for working with SharePoint development in Sublime Text which lets you quickly copy files to the "hive" using a Sublime build system and a Powershell script.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your package name here and the name you hardcoded in your build system don't match. You have to use the same for both.

**Comment by eakron** [comment]
Removed the spaces in the package name

**Comment by FichteFoll** [comment]
Now you need to update the package's position in the file ;)

**Comment by eakron** [comment]
Done!

**Pull request merged**
