### PR TITLE
Added FortifyThemes package

### PR DESCRIPTION
**Pull request by pwntester**
FortifyThemes provides themes for Fortify RulePacks and NST files

### CODE REVIEW

**Comment by FichteFoll** [comment]
???

What does it do?

**Comment by pwntester** [comment]
I updated the original description. Its just a bunch of tmLanguage files to color Fortify rulepacks and NST files. Fortify is a static source code analyzer and rulepacks and NSTs are file formats used to write custom rules and to represent source code files

**Comment by FichteFoll** [comment]
Hm. I recommend you add some info to your repository, possibly even with a screenshots (because images speak more that thousand words).

Also, "Themes" are something different in Sublime Text. Themes are `.sublime-theme` files that change the look of the editor itself, like https://packagecontrol.io/packages/Theme%20-%20Soda, the most popular one. `.tmLanguage` files are usually referred to as syntax or language definitions. I'd like you to reconsider the name of the package.

**Comment by pwntester** [comment]
Thanks for the usefule feedback! I have changed the package name, and added a verbose README.md  to the repo.

**Comment by FichteFoll** [comment]
Looks alright.

**Pull request merged**
