### PR TITLE
Added JaiLang Package

### PR DESCRIPTION
**Pull request by gingerBill**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Differences to https://packagecontrol.io/packages/Jai?

**Comment by gingerBill** [comment]
Contains better syntax highlighting in general and does not contain the same code.

**Comment by FichteFoll** [comment]
>does not contain the same code

This reads the same as "it's just different".

Please consider filing a pull request against the existing Jai package instead of branching off small enhancements.

cc @GreenLightning

**Comment by GreenLightning** [comment]
I would be happy to accept pull requests!

**Comment by FichteFoll** [comment]
Any update?

**Pull request closed without merging**
