### PR TITLE
Added XO-Formatter

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
@wbond I'm not sure why it's reporting `h` is being used:

```sh
λ ~/Projects/XO-Formatter/ master rg "ctrl"
Default (Linux).sublime-keymap
2:  "keys": ["ctrl+shift+x"],

Default (Windows).sublime-keymap
2:  "keys": ["ctrl+shift+x"],
```

**Comment by niftylettuce** [comment]
Can anyone tell me why it's reporting the hotkey h?

**Comment by FichteFoll** [comment]
You force-pushed your repo, so I can't see what it might have seen before.

Either way, you need to push a semver tag.

**Comment by FichteFoll** [comment]
@niftylettuce ping

**Pull request closed without merging**
