### PR TITLE
Added earthly earthfile syntax

### PR DESCRIPTION
**Pull request by vishnugt**
This is a syntax definition for Earthly - https://github.com/earthly/earthly

Earthly is a build automation tool that allows us to execute all our builds in containers. Earthly can be used to create Docker images and artifacts (eg binaries, packages, arbitrary files).

There are no other existing packages for providing syntax highlighting to Earthly

### CODE REVIEW

**Comment by braver** [comment]
- Since ST2 is essentially dead and there are only like 5 people still out there using it, you may want to provide your syntax as a [.sublime-syntax](https://www.sublimetext.com/docs/3/syntax.html#overview) file. It's much easier to maintain and read, it has more features, and it has enhanced performance. There is a converter built into ST3 (IIRC via Tools > Developer and/or in the command palette).
- You don't need to specify the README location if it's simply in the root of the main branch of your repository and has a "normal" filename.

**Comment by braver** [comment]
@vishnugt please remove the README key. 

Additionally, please consider removing "syntax" from the name. Usually packages that supply syntax and related features simply have the name of the language they support. That it's (also) the syntax is implied.

**Comment by vishnugt** [comment]
Removed readme key and removed "syntax" from the name @braver

**Comment by braver** [comment]
🎉

**Pull request merged**
