### PR TITLE
Add Nim-lang package

### PR DESCRIPTION
**Pull request by vanyle**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is similar to Nimlime.
However it should still be added because NimLime is abandoned and does not support Sublime Text 4 (It's targeted towards Sublime Text 2). A lot of features like autocompletion, documentation generation and tooltips are missing or broken. Contributing to NimLime is non-trivial and making a new package is simpler.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Is NimLime truly abandoned? There seems to be a pretty big PR going to update it. Have you tried contributing to that effort?

**Comment by vanyle** [comment]
The scope of this package is a bit different from what NimLime does. NimLime aims to provide basic editing support for Nim: syntax highlighting, and integration with the build system. While this plugin also has these features, the aim is a bit different.
The current pull request on NimLime aims to update the syntax to the current new features of Nim without adding features to the plugin.
The Nim compiler provides by default some tools (namely Nimsuggest and the `nim check` command) that allow for static analysis and fancy suggestions without needing an LSP.
Most sublime plugins (I think?) that support a language are designed to be simple and give this basic support as Sublime Text is not an IDE but a text editor.
This plugin gives the user the option to have these "IDE" like features if they need (all the features can be toggled in a config file).
There are some redundancy between this plugin and NimLime because I think it's easier for a user to only install a single package for a language that gives what they need (depending on if they want something closer to an editor or an IDE) then first installing a plugin for basic support and another plugin for "advanced" features.

**Comment by AmjadHD** [comment]
@vanyle, Other than that PR, I was planning to rename and simplify the package. And make it work alongside nimlsp.
So I would prefer if you can help with this.

**Comment by vanyle** [comment]
@AmjadHD I can do both!
I just like to work on my own package so that I can quickly add features and distribute them based on problem I encounter when writing Nim (currently, that probably means figuring out a way to add auto-imports even if it will probably we quite hard!), and without having to worry about handling contribution, reviews, etc...
I have plans to simplify the syntax to use snbf and if I do, I will probably add also submit PR to NimLime. I need to check how far you are on the simplification. I'm not really writing a lot of syntax highlighting as I find automatic documentation/error highlighting/suggestion more exciting but I noticed a few highlighting bugs that will need fixing at some point (even though they are not very bothering)

Also, I will probably change the name to Nimplus to avoid confusion. What name would you change NimLime to ? Just "Nim" ?

**Comment by AmjadHD** [comment]
Just "Nim" since it's the official package, But I didn't discuss this with the owners yet.

**Comment by braver** [comment]
So… management summary, we’re going with two packages, one official one that’s maybe going to be renamed, and another one with more features and higher velocity, and you’re looking to contribute back to the official package whenever that seems like a good idea? Works for me, just let me know when to push “merge”.

**Comment by vanyle** [comment]
Yup, this is fine with me! I'm ready for the merge!

**Comment by braver** [comment]
Alright! Almost there. You may want to update your readme, settings file and maybe some other places that have the name of the package in it: they currently don’t match the NimPlus name and that might confuse users.

**Comment by vanyle** [comment]
Updated !

**Comment by braver** [comment]
> changing the url will become more and more impractical

GitHub is pretty good at redirecting usually, but it's definitely nice to have these things aligned. If the bot is happy too I'll hit merge.

**Pull request merged**
