### PR TITLE
Add new theme "Atom Theme"

### PR DESCRIPTION
**Pull request by christopherfouquier**
I've added a new Atom design theme to package control.

Please provide the following information:

 - Link to your code repository: [https://github.com/christopherfouquier/atom-theme](https://github.com/christopherfouquier/atom-theme)
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/christopherfouquier/atom-theme/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
This theme already exists: https://packagecontrol.io/packages/Theme%20-%20One%20Dark

**Comment by wbond** [comment]
You forgot required information, and forgot to run the tests.

**Comment by christopherfouquier** [comment]
@math2001 : 
* My color scheme is different of "One Dark Theme", he is more near of "Atom Editor". The color scheme of "One Dark Theme" is no longer maintained by IceTimux her creator.
* My theme is full retina
* My theme is customizable with options

I think that my theme has its place in the "Package Control".

@wbond : I added required informations and run the tests with success.

**Comment by FichteFoll** [comment]
@christopherfouquier, don't you think it would make sense to add retina support and more options to the existing package? They look *really* similar to me and one being inferior to the other for some obscure reason that is not obvious to users is confusing. Furthermore, your enhancements to the existing theme  would benefit almost 3k users who already installed that package.

Your install instuctions in `messages/install.txt` are wrong, btw.

**Comment by FichteFoll** [comment]
@christopherfouquier please respond to the comment I made earlier.

**Comment by christopherfouquier** [comment]
@FichteFoll : You are right. Apart from what you mentioned and a better syntactic support, the idea of the theme is the same.

**Pull request closed without merging**
