### PR TITLE
added new package "Vray"

### PR DESCRIPTION
**Pull request by Aloiseau**
This package is used to edit files " .vrscene " created by the rendering engine Vray , more easily.
Thanks !

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/docs/submitting_a_package#Step_2

**Comment by Aloiseau** [comment]
Sorry I took example on wren-sublime and MayaSublime. I'll change that. Thanks !

**Comment by Aloiseau** [comment]
The name of my package is finaly clean, thank !

**Comment by FichteFoll** [comment]
I didn't notice at first, but it seems that [this commit](https://github.com/wbond/package_control_channel/commit/5abb8504686f01bb73340d998305e5d77c35ecee) has messsed up the  git history completely.

Am considering scraping that commit and force-pushing for the sake of git blame and similar.

@wbond?

**Pull request merged**
