### PR TITLE
Add LC-2K Assembly Syntax Plugin to l.json

### PR DESCRIPTION
**Pull request by BGR360**
Syntax Highlighting and auto-completion for the LC-2K assembly ISA.

Please provide the following information:
- Link to your code repository:

https://github.com/BGR360/lc2k-sublime-plugin
- Link to the tags page with at least one [semver](http://semver.org) tag: 

https://github.com/BGR360/lc2k-sublime-plugin/releases/tag/0.0.0

### CODE REVIEW

**Comment by joshua-golub** [comment]
BGR360, please provide a more appropriate semver tag than `0.0.0`. I think that either `1.0.0` or `0.1.0` would be better.

**Comment by BGR360** [comment]
Done.

**Comment by joshua-golub** [comment]
@FichteFoll, this package looks good to me. I recommend that it be merged.

**Comment by FichteFoll** [comment]
@BGR360, please remove `LC-2K Assembly.sublime-package` from the repo. It serves no purpose (you don't even use it for your manual download instructions) and just increases the repo size. Don't forget to push a new tag for that.

A recommendation: Use `'` single quotes for strings in YAML when specifying regular expressions. Single-quoted strings don't support any escape sequences besides `''` and are much better for something as backslash-heavy as regular expressions.

Also, using a `0.0.0` semver tag is perfectly valid and some argue for it to be the initial version, although it is uncommon. The interested reader might want to take a look into https://github.com/mojombo/semver/issues/221.

**Comment by BGR360** [comment]
Will do. Why do you recommend using single quotes? To avoid having to do \\ for every escape sequence?

**Comment by BGR360** [comment]
Almost all of the documentation I've seen for sublime-syntax files uses the double-quotes-and-double-backslashes style. I will make note of this for future packages I make though :)

**Comment by FichteFoll** [comment]
>Why do you recommend using single quotes? To avoid having to do \ for every escape sequence?

Exactly. Actually, in most cases you don't need quotation marks at all.

> Almost all of the documentation I've seen for sublime-syntax files uses the double-quotes-and-double-backslashes style. 

Probably lack of knowledge by the author(s).

**Comment by BGR360** [comment]
Removed the sublime-package file. Here is the new semver tag: https://github.com/BGR360/lc2k-sublime-plugin/releases/tag/v1.0.0

**Comment by BGR360** [comment]
Thank you! :))

**Comment by BGR360** [comment]
How can I be notified when this becomes publicly available through Package Control's "Install Package" command?

**Comment by FichteFoll** [comment]
You can't, but it usually happens within an hour. Okay, there is https://twitter.com/SublimePackages, but that's pretty late. Might as well just refresh https://packagecontrol.io/browse/new if it's important for you.

**Comment by vovkkk** [comment]
There is rss http://wbond.net/sublime_packages/community/rss

**Comment by FichteFoll** [comment]
I was looking  for an rss meta tag on the packagecontrol.io site but couldn't find one. Might be worth adding an issue over it at the corresponding repo.

**Pull request merged**
