### PR TITLE
Add Starlark syntax

### PR DESCRIPTION
**Pull request by Vasfed**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is syntax highlighting for Starlark language.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by Vasfed** [comment]
@packagecontrol-bot please review

**Comment by braver** [comment]
Well done 👍🏻

**Comment by deathaxe** [comment]
What's the main difference between Starlark and the syntax provided by https://github.com/niosus/BazelSyntax?

**Comment by braver** [comment]
Oh, nice find… one thing this new one has going for it is that it has the correct name 😁. Starlark is not limited to the Bazel project, it’s a language all on its own. .. Although I guess we did duplicate a bit now, the new one is probably much more findable (the old one doesn’t even mention Starlark).

**Pull request merged**
