### PR TITLE
added theme - classic

### PR DESCRIPTION
**Pull request by IceTimux**
Added the classic theme

### CODE REVIEW

**Comment by wbond** [comment]
You didn't actually test installing this, did you?

**Comment by wbond** [comment]
Also, how is this different than https://packagecontrol.io/packages/Theme%20-%20Retina?

**Comment by IceTimux** [comment]
@wbond Not sure what you mean, but its tested. If you take a loot at the Retina theme you can see that it's broken in the latest build, there are missing assets

**Comment by FichteFoll** [comment]
There was an issue with the retina theme being temporarily removed from the package control channel. Updates weren't picked up anymore but the package was still cached and installable.

This has since been fixed and the theme was moved to the SublimeText org: https://github.com/SublimeText/LegacyTheme. Because the theme isn't maintained anymore, issues have been disabled but pull requests can still be submitted. Is this more to your liking, @IceTimux?

**Comment by IceTimux** [comment]
@FichteFoll Yeah that's really good!

**Pull request closed without merging**
