### PR TITLE
Add csv-record-view

### PR DESCRIPTION
**Pull request by mrp130**
Plugin to transform csv row to record view

### CODE REVIEW

**Comment by Thom1729** [comment]
Do any existing packages provide this functionality? (I don't know what “record view” is, so I'm not clear on this.)

**Comment by mrp130** [comment]
@Thom1729 I searched and cannot find existing packages provide this functionality. To make clear, this is example for record view https://github.com/dbeaver/dbeaver/wiki/Data-View-and-Format#table-vs-record-views

**Comment by Thom1729** [comment]
Instead of `sublime.active_window()`, you should use `self.view.window()`.

**Comment by mrp130** [comment]
done @Thom1729

**Pull request merged**
