### PR TITLE
add Total.js View Engine

### PR DESCRIPTION
**Pull request by petersirka**

### CODE REVIEW

**Comment by wbond** [comment]
You appear to have forgotten to run the tests: https://packagecontrol.io/docs/submitting_a_package#Step_7

**Comment by FichteFoll** [comment]
@petersirka ping

**Comment by petersirka** [comment]
@FichteFoll I'll look into it this week. Sorry for delay :-1:

**Comment by petersirka** [comment]
I have fixed it in `t.json`. But the Travis creates a new problem :8ball: 
Can you help me?

**Comment by FichteFoll** [comment]
The test failure message is pretty clear to me. Please also run the tests locally, following the instructions above.

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Pull request closed without merging**
