### PR TITLE
Add LuaFormat

### PR DESCRIPTION
**Pull request by FloydaGithub**
Please provide the following information:

 - Link to your code repository: https://github.com/FloydaGithub/LuaFormat
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/FloydaGithub/LuaFormat/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FloydaGithub** [comment]
#6214 duplicate [`FormatLua`](https://github.com/denglf/FormatLua)
1. package [`FormatLua`](https://github.com/denglf/FormatLua) can't work properly unless installed Lua development tools library.
2. my package used Python

**Comment by FichteFoll** [comment]
You don't need to add your package path to `sys.path`. It will work regardless.

**Comment by wbond** [comment]
@FloydaGithub Did you address the issue that @FichteFoll found regarding `sys.path`?

**Comment by FloydaGithub** [comment]
https://github.com/FloydaGithub/LuaFormat/releases/tag/0.0.2

I did below and created new tag:
1. do not add package to sys.path
2. delete message.json

**Pull request merged**
