### PR TITLE
add GoDebug package

### PR DESCRIPTION
**Pull request by dishmaev**

### CODE REVIEW

**Comment by dishmaev** [comment]
Hi
Can i use a 'context' in the Default.sublime-mousemap similar to the Default.sublime-keymap?
How do I get rid of warnings?

**Comment by FichteFoll** [comment]
No, you cannot specify a context for mousemaps unfortunately. I suggest adding instructions for the user in the readme. (Or using `edit_settings` to open your defaults with a different extension next to the User file.)

You should use relative imports because those are independent of the package's installed name.

**Comment by FichteFoll** [comment]
@dishmaev ping

**Comment by dishmaev** [comment]
Hi
I will make the necessary changes to GoDebug tomorrow

**Pull request merged**
