### PR TITLE
angular2-snippets added

### PR DESCRIPTION
**Pull request by ozcanzaferayan**
Created Angular2 Typescript snippets for developing components, services etc.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please read through https://github.com/wbond/package_control_channel/pull/5482 and conclude which style your snippets follow. If they are of the same style as https://packagecontrol.io/packages/Angular%202%20Snippets%20(John%20Papa), please consider contributing to that instead.

**Comment by FichteFoll** [comment]
Actually, it seems your snippets are more specific and include entire blocks as boiler plate. Please use a more specific name for your package.

**Comment by wbond** [comment]
@ozcanzaferayan Do you have any thoughts regarding the comments from FichteFoll?

**Comment by ozcanzaferayan** [comment]
I will change package name as angular2-boilerplate

**Comment by FichteFoll** [comment]
@ozcanzaferayan please do so

**Pull request closed without merging**
