### PR TITLE
Add 'Ion Syntax' package

### PR DESCRIPTION
**Pull request by SevenO2**
I couldn't find any existing packages for this (which is why I made it in the first place).

Running the test triggered some failures, but they look like problems with other packages? I would appreciate some help there. I'll post the failures in a comment.

### CODE REVIEW

**Comment by SevenO2** [comment]
FAIL: test_error('Downloading https://raw.githubusercontent.com/jvantuyl/sublime_diagram_plugin/master/packages.json failed', HTTPError()) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 582, in _test_error
      self.fail("%s: %s" % (msg, e))
  AssertionError: Downloading https://raw.githubusercontent.com/jvantuyl/sublime_diagram_plugin/master/packages.json failed: HTTP Error 404: Not Found
  
  ======================================================================
  FAIL: test_package('https://eoa-cdn.s3.amazonaws.com/extensions/packages.json', {'name': 'Email on Acid', 'labels': ['email', 'email testing'], 'homepage': 'https://www.emailonacid.com/', 'releases': [{'date': '2017-10-20 10:00:00', 'sublime_text': '*', 'url': 'https://eoa-cdn.s3.amazonaws.com/extensions/email-on-acid.sublime-package', 'version': '1.0.0'}], 'readme': 'https://eoa-cdn.s3.amazonaws.com/extensions/readme.md', 'description': 'Test your emails with the Email on Acid plugin for Sublime Text.'}) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 369, in _test_package
      'provided' % key)
  AssertionError: 'author' not found in {'name': 'Email on Acid', 'labels': ['email', 'email testing'], 'homepage': 'https://www.emailonacid.com/', 'releases': [{'date': '2017-10-20 10:00:00', 'sublime_text': '*', 'url': 'https://eoa-cdn.s3.amazonaws.com/extensions/email-on-acid.sublime-package', 'version': '1.0.0'}], 'readme': 'https://eoa-cdn.s3.amazonaws.com/extensions/readme.md', 'description': 'Test your emails with the Email on Acid plugin for Sublime Text.'} : 'author' is required if no "details" URL provided
  
  ======================================================================
  FAIL: test_release('Laravel Blade Highlighter (https://raw.githubusercontent.com/Medalink/laravel-blade/master/packages.json)', {'date': '2015-05-13 11:09:00', 'sublime_text': '<=3083', 'version': '1.5.3', 'url': 'https://nodeload.github.com/Medalink/laravel-blade/zip/1.5.3', 'platforms': ['windows', 'osx', 'linux']}, False, False) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 480, in _test_release
      self.check_release_key_values(data, dependency)
    File "./tests\test.py", line 527, in check_release_key_values
      '"osx, windows, linux" are similar to (and should be replaced by) "*"')
  AssertionError: True is not false : "osx, windows, linux" are similar to (and should be replaced by) "*"
  
  ======================================================================
  FAIL: test_release('Laravel Blade Highlighter (https://raw.githubusercontent.com/Medalink/laravel-blade/master/packages.json)', {'date': '2015-10-08 12:57:00', 'sublime_text': '3084', 'version': '1.5.6', 'url': 'https://nodeload.github.com/Medalink/laravel-blade/zip/1.5.6', 'platforms': ['windows', 'osx', 'linux']}, False, False) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 480, in _test_release
      self.check_release_key_values(data, dependency)
    File "./tests\test.py", line 505, in check_release_key_values
      'sublime_text must be `*`, of the form '
  AssertionError: sublime_text must be `*`, of the form `<relation><version>` where <relation> is one of {<, <=, >, >=} and <version> is a 4 digit number, or of the form `<version> - <version>`: '^(\\*|<=?\\d{4}|>=?\\d{4}|\\d{4} - \\d{4})$' not found in '3084'
  
  ======================================================================
  FAIL: test_release('Laravel Blade Highlighter (https://raw.githubusercontent.com/Medalink/laravel-blade/master/packages.json)', {'date': '2020-05-28 13:50:00', 'sublime_text': '>3084', 'version': '1.6.18', 'url': 'https://nodeload.github.com/Medalink/laravel-blade/zip/1.6.18', 'platforms': ['windows', 'osx', 'linux']}, False, False) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 480, in _test_release
      self.check_release_key_values(data, dependency)
    File "./tests\test.py", line 527, in check_release_key_values
      '"osx, windows, linux" are similar to (and should be replaced by) "*"')
  AssertionError: True is not false : "osx, windows, linux" are similar to (and should be replaced by) "*"
  
  ======================================================================
  FAIL: test_release('Ribosome Syntax (https://raw.githubusercontent.com/JesseTG/ribosome-sublime/master/packages.json)', {'sublime_text': '>=3092', 'url': 'https://github.com/JesseTG/ribosome-sublime/archive/v0.1.5.zip', 'version': '0.1.5'}, False, False) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 462, in _test_release
      'A release must provide "url", "version" and '
  AssertionError: 'date' not found in {'sublime_text': '>=3092', 'url': 'https://github.com/JesseTG/ribosome-sublime/archive/v0.1.5.zip', 'version': '0.1.5'} : A release must provide "url", "version" and "date" keys if it does not specify "tags" or"branch"
  
  ======================================================================
  FAIL: test_release('Theme - Monokai Pro (https://packages.monokai.pro/packages.json)', {'date': '2020-06-09 9:00:00', 'version': '1.1.17', 'url': 'https://packages.monokai.pro/Theme - Monokai Pro/1.1.17/Theme - Monokai Pro.sublime-package', 'sublime_text': '>=3000'}, False, False) (package_control_channel.tests.test.DefaultChannelTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "./tests\test.py", line 100, in wrapper
      return method(self, *params)
    File "./tests\test.py", line 480, in _test_release
      self.check_release_key_values(data, dependency)
    File "./tests\test.py", line 530, in check_release_key_values
      self.assertRegex(v, r"^\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d$")
  AssertionError: Regex didn't match: '^\\d\\d\\d\\d-\\d\\d-\\d\\d \\d\\d:\\d\\d:\\d\\d$' not found in '2020-06-09 9:00:00'
  
  ----------------------------------------------------------------------
  Ran 9798 tests in 0.798s
  
  FAILED (failures=7)

**Comment by SevenO2** [comment]
I reran the Default Channel Tests and it was super quick this time, which seems suspicious but it passed:
>  Ran 9157 tests in 0.756s
>  
>  OK

**Comment by braver** [comment]
Thanks for submitting!

The only thing missing here is the "language syntax" label.

You could also have a look at adding a .gitattributes to exclude some non-functional things like test files from your package, to save a little network and disk space usage.

**Comment by SevenO2** [comment]
> The only thing missing here is the "language syntax" label.

Ah, will do. You might consider adding "labels" to the docs: https://packagecontrol.io/docs/submitting_a_package

> You could also have a look at adding a .gitattributes to exclude some non-functional things like test files from your package, to save a little network and disk space usage.

Are you suggesting removing it from the git repo altogether? Or is there a way to tell packagecontrol to ignore folders? It looks like 'export-ignore' in .gitattributes would work if packagecontrol uses git-archive. Do you know if it does?

**Comment by braver** [comment]
> Do you know if it does?

Sorry, yes, that’s exactly how it works. We should have these things documented somewhere, I’ll look into it!

**Pull request merged**
