### PR TITLE
Add CoderPad-Color-Scheme

### PR DESCRIPTION
**Pull request by marwan37**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **

My package is a color scheme that mimics the CoderPad environment. There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by marwan37** [comment]
All requested changes have been made:
1. Converted `CoderPad.tmTheme` to `CoderPad.sublime-color-scheme`
2. Added `.gitattributes` with export ignores

Yes, those scopes must have been autogenerated. I'm not sure how or where they came from. Hope all's well now, and thank you.

**Comment by braver** [comment]
Please tag a release using semver numbering, we can't ship your package without tags.

**Comment by braver** [comment]
Please respond to the feedback to continue the review.

**Comment by marwan37** [comment]
I have just tagged and published a release (v1.0.0). Thanks!

**Pull request merged**
