### PR TITLE
Add Ribosome syntax definition URL to channel.json

### PR DESCRIPTION
**Pull request by JesseTG**
I added [a syntax definition](https://github.com/JesseTG/ribosome-sublime) for this neat little thing called [Ribosome](https://github.com/sustrik/ribosome).  Because of how I implemented it, I compile and release a `.sublime-package` myself with Travis.  However, I'm not sure what to do about `package.json` (note: singular) or that metadata file.

### CODE REVIEW

**Comment by JesseTG** [comment]
Okay, I don't know what I'm doing wrong.  I *do* have semver tags in my repo, but they're not being recognized.  Please help.

**Comment by evandrocoan** [comment]
> I do have semver tags in my repo, but they're not being recognized. Please help.

The tests are failing because you are using a external `.json` file and there the tags are prefixed with `v` or are not complete on the format `x.x.x`, for example `1.0.0`

Also, your tags are prefixed with `v`, but on the package control channel settings you set the tag as `st3-`, you should set them as `v`:
```json
      "releases": [
        {
          "sublime_text": ">=3092",
          "version": "0.1.4",
          "url": "https://github.com/JesseTG/ribosome-sublime/archive/0.1.4.zip",
          "tags": "v"
        }
```

To make the tests pass now, you can create the entry on the repository. Use this package as example:

1. https://github.com/wbond/package_control_channel/pull/6819/files

Your would be like:
```json
		{
			"name": "Ribosome Syntax",
			"details": "https://github.com/sustrik/ribosome",
			"releases": [
				{
					"sublime_text": ">=3000",
					"tags": "v"
				}
			]
		},
```

**Comment by JesseTG** [comment]
Yes!  Okay, I'm good now, thank you!

**Comment by FichteFoll** [comment]
When you pre-package the package, you need a custom `repository.json`. The `tags` and `branch` features only fetch zipballs, i.e. a snapshot from your actual repository, and not any artifacts you add as custom downloads using Github's releases.

As such, your [`repository.json`](https://raw.githubusercontent.com/JesseTG/ribosome-sublime/master/packages.json) file was almost fine, but you need to remove the `"tags": "v"` line since the different release channel discovery options are exclusive.

**Comment by FichteFoll** [comment]
@JesseTG ping

**Comment by JesseTG** [comment]
@FichteFoll Christ, I'd forgotten all about this.  Fixed.

**Comment by FichteFoll** [comment]
`version` shouldn't have the leading "v" and just be the version string.

**Comment by JesseTG** [comment]
Ok, try it now.

**Pull request merged**
