### PR TITLE
add SnippetMakerNext

### PR DESCRIPTION
**Pull request by braver**
SublimeSnippetMaker is dead as a doorknob: no commits for years and no reaction on issues or pull requests. This adds much needed features and a promise of maintenance going forward.

### CODE REVIEW

**Comment by FichteFoll** [comment]
If the authoer of the original package, @jugyo, is AWOL, it might make more sense to take over the existing package entry and update it for everyone who uses it in the meantime.

@jugyo, I see that you are still active on Github, although in private repositories. If you object to @braver replacing your package here, please speak up.

**Comment by jugyo** [comment]
@braver You can take over the "SnippetMaker". Thanks!

**Comment by braver** [comment]
@jugyo you want to add me as a collaborator to your repo, or transfer it or something?

**Comment by jugyo** [comment]
@braver I'll add you as a collaborator to my repo. Does that work?

**Comment by braver** [comment]
@jugyo as long as I can create tags it should work. Thanks!

**Comment by braver** [comment]
@FichteF

**Comment by jugyo** [comment]
@braver cool!

**Comment by braver** [comment]
@jugyo one final request: could you update the repo's description (I don't seem to have that access) from

> Sublime Text 2 plugin that provides you to make snippets easily.

to:

> Makes managing snippets easy in Sublime Text

Mostly to remove the suggestion of being ST2 compatible only.

**Comment by jugyo** [comment]
@braver I've done!

**Pull request closed without merging**
