### PR TITLE
Added "Riot Syntax" package

### PR DESCRIPTION
**Pull request by ilearnio**

### CODE REVIEW

**Comment by FichteFoll** [comment]
`.sublime-syntax` support was added (and considered usable) starting build 3092. Please adjust the version selector accordingly.

I can not merge the PR due to a merge conflict it seems. Please rebase onto current `master`.

**Comment by FichteFoll** [comment]
@ilearnio ping

**Comment by ilearnio** [comment]
I increased the min. version of Sublime, please have a look. Thanks

**Comment by FichteFoll** [comment]
It's still conflicting with the master branch however.

**Pull request closed without merging**
