### PR TITLE
Add Copy Relative Command

### PR DESCRIPTION
**Pull request by patoui**
https://github.com/patoui/CopyRelativeCommand

- [X] I'm the package's author and/or maintainer.
- [X] I have have read [the docs][1].
- [X] I have tagged a release with a [semver][2] version number.
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [X] My package doesn't add context menu entries. *
- [X] My package doesn't add key bindings. **
- [X] Any commands are available via the command palette.
- [X] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [X] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is similar to [CopyRelativePath](https://github.com/bpicolo/CopyRelativePath) however it should still be added as it provides different functionality by given the user the ability to define rules by language (source) and glob patterns. It also allows them to inject scope relevant symbols such as function, class, or function falling back to class.

As an example; if the cursor is within a [PHPUnit](https://phpunit.de/) method and the user can [define rules](https://github.com/patoui/CopyRelativeCommand/tree/main#quick-start-%EF%B8%8F) to copy a command to their clipboard to run the test in terminal.

From the [example configuration]((https://github.com/patoui/CopyRelativeCommand/tree/main#quick-start-%EF%B8%8F)) in the repo, the output would look like:
```
vendor/bin/phpunit tests/Unit/ExampleTest.php --filter=test_that_true_is_true
```

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Woah, that’s hyper niche, cool 👍🏻

I think you should decide, in the command palette or elsewhere, if your package is called “Copy Relative Command” with or without the spaces.

If you want to support project specific settings you don’t need to parse the project data yourself. Instead you can access the settings for the current view, which will have the project settings applied to it.

**Comment by braver** [comment]
You might also want to document how your users can set up key bindings for this.

**Comment by patoui** [comment]
@braver thanks for the feedback! Sorry for the delayed response, I'll have a look at the changes you suggested within the next week or so (hopefully 🤞)

**Comment by patoui** [comment]
@braver I've made the changes you suggested, let me know if there's anything else I can do to improve the package :)

**Comment by braver** [comment]
🎉

**Pull request merged**
