### PR TITLE
New Apex (Salesforce) snippets: Trigger + Trigger Handler

### PR DESCRIPTION
**Pull request by adashko**

### CODE REVIEW

**Comment by FichteFoll** [comment]
What are the differences to https://packagecontrol.io/packages/Apex%20Snippets?

**Comment by adashko** [comment]
Hi.
These Trigger + Trigger Handler are more correct in terms the "correct" implementation triggers in Apex. This code includes insert/update/delete/undelete events within one method - good performance improvement
+ Out team will add new snippets (sample): knockoutjs + Apex controller (using @Remote action), new reRender using only jQuery + Apex controller (using @Remote action). These snippets are in development

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by adashko** [comment]
Hello.

I added the tag v0.2 to my repository

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by adashko** [comment]
Hi.

I added the tag v0.2.0 to my repository

**Pull request merged**
