### PR TITLE
Remove support for PSR1/PSR2 and update issues link for phpfmt

### PR DESCRIPTION
**Pull request by ccirello**

### CODE REVIEW

**Comment by ccirello** [comment]
ping @FichteFoll

**Comment by FichteFoll** [comment]
Please only ping me if I accidentally missed your PR and have reviewed other pull request newer than yours. Thank you.

**Comment by ccirello** [comment]
> I accidentally missed your PR

From my point of view you missed it due to fact you took so many days to merge.

**Comment by FichteFoll** [comment]
5 days are not many. I could have easily been on vacation for this period. I will, in fact, be starting tomorrow.

**Pull request merged**
