### PR TITLE
Added ServiceNow Sync package

### PR DESCRIPTION
**Pull request by salcosta**

### CODE REVIEW

**Comment by Thom1729** [comment]
- You shouldn't modify `sys.path`, because that is shared between all packages.
- You have an empty `__init__.py`.
- Your readme doesn't describe what the package does or who would use it.

**Comment by salcosta** [comment]
@Thom1729 Appending the current path to the `sys.path` seems to be the standard across other packages.  Is there an alternative you are wanting to use now?

Regarding the other 2 changes I will resolve those.

**Comment by Thom1729** [comment]
Instead of modifying `sys.path`, use relative imports: `from .Commands.create_connection import *`.

**Comment by Thom1729** [comment]
@salcosta ping.

**Pull request closed without merging**
