### PR TITLE
Add Git blame plugin

### PR DESCRIPTION
**Pull request by psykzz**
Please provide the following information:

 - Link to your code repository: https://github.com/psykzz/st3-gitblame
 - Link to the tags page with at least one [semver](http://semver.org) tag:  https://github.com/psykzz/st3-gitblame/tree/1.0.0

----
Example Screen
image

### CODE REVIEW

**Comment by FichteFoll** [comment]
-- Report for st3-gitblame ----------------------------

= Repository checks =

No failures

No warnings

= Package checks =

Reporting 2 failures:
- The binding ['ctrl+shift+q'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap
- The binding ['ctrl+shift+q'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

You should add that screenshot to your readme, because currently that might as well not exist at all.

**Comment by FichteFoll** [comment]
@psykzz ping

**Comment by psykzz** [comment]
Sorry for the delay, i've updated the keybinding and im just updating the readme me, (I've already attached the screenshot).

**Comment by psykzz** [comment]
@FichteFoll updated.

**Comment by FichteFoll** [comment]
Because your package uses phantoms a lot, you should restrict users to download it only for builds where they aer supported, which is somewhere in the 3100 range (I don't know it by heart).

**Comment by psykzz** [comment]
Thanks @math2001 for the link. 

@FichteFoll I've updated the requirements to restrict the build.

**Comment by FichteFoll** [comment]
@math2001, you normally want to go by the dev build they first appeared in, which https://www.sublimetext.com/3dev indicates as being 3118, but it doesn't really matter in this case because of how long ago these releases were.

**Pull request merged**
