### PR TITLE
Added FileDelete plugin

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Hang on... I broke some formatting.

**Comment by jbrooksuk** [comment]
Fixed :)

**Comment by FichteFoll** [comment]
Line 8 will throw an exception if run on an unsaved view. Also, I'm not sure that I'd make the answer recognition case sensitive.

**Comment by jbrooksuk** [comment]
I didn't know about Delete Current File :)

**Pull request closed without merging**
