### PR TITLE
Added the package amxmodx to repository/a.json

### PR DESCRIPTION
**Pull request by evandrocoan**
Please provide the following information:

 - Link to your code repository: https://github.com/evandrocoan/SublimeAMXX_Editor
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/evandrocoan/SublimeAMXX_Editor/releases

Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7)):
```
Running Default Channel Tests

  ..................................................
  ----------------------------------------------------------------------
  Ran 7634 tests in 2.217s
  
  OK
```

### CODE REVIEW

**Comment by wbond** [comment]
Sorry, that last message should have said there are a few problems that were identified

**Comment by evandrocoan** [comment]
Thanks. I think I fixed it on eaf8a8d 

But how to run these tests you did? The one I ran did not catch those invalid plists.

**Comment by rwols** [comment]
It's a python program called [st_package_reviewer](https://pypi.python.org/pypi/st-package-reviewer), it's fairly new.

**Comment by wbond** [comment]
If you rebase on master, these tests will be run by Travis CI.

**Comment by FichteFoll** [comment]
@evandrocoan you need to push a new tag with the changes.

**Comment by evandrocoan** [comment]
Thanks! I had forgot to.

**Pull request merged**
