### PR TITLE
Added my updated Tortoise package to repository/t.json

### PR DESCRIPTION
**Pull request by westy**

### CODE REVIEW

**Comment by FichteFoll** [comment]
@wbond, since this is your package and added outside of the this repo in a separate `repository.json`, I ask you to take care of this.

**Comment by FichteFoll** [comment]
@wbond ping

**Comment by braver** [comment]
@westy, the license violation mentioned above hasn't been responded to. This PR cannot move forward without a change to the license info.

Besides, there have been previous attempts to update or contribute to the existing package, but they have stranded apparently because no-one seemed up to actually doing anything with it. Your activity doesn't inspire confidence that you're going to keep the original package going. Prove me wrong within the next 2 weeks and I'll try to take it up with the original maintainer to add you as a contributor. For this period I'll keep the PR open as a reminder.

**Comment by westy** [comment]
@braver No need to take that tone to be honest. Yes, I'm not very active on GitHub because I happen to work all week and no longer fancy coding in my spare time thank you very much. You've obviously had a bad week. Why don't you treat people with more respect you arse.

Look at my commit. I just got it working again, I am not a maintainer of the plugin.
I don't know anything about the license violation that has been mentioned. It's certainly not in the commit I made.

**Comment by braver** [comment]
Well sorry if that landed the wrong way, it wasn't meant to be angry in any way. I just forgot that tongue-in-cheek doesn't translate online. Again, sorry about that. 

The license violation I meant was this:

> By the way, this is not how licenses work. You can't just remove the original copyright holder from the license copyright section, but you may add your own name.

But in the end that's moot. If the original author wants to grab your fixes he can do so. It looks like replacing the existing package with yours isn't a long term solution, so we'll just let it sit for now.

**Pull request closed without merging**
