### PR TITLE
Update b.json

### PR DESCRIPTION
**Pull request by diegoinacio**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need a `.no-sublime-package` file in your package. Please remove it.

You should also add `*.cache` to your `.gitignore`.

**Comment by diegoinacio** [comment]
done! :)

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@diegoinacio ping

**Pull request closed without merging**
