### PR TITLE
"Better typescript" is deprecated.

### PR DESCRIPTION
**Pull request by lavrton**
https://github.com/lavrton/sublime-better-typescript/blob/master/README.md#overview

### CODE REVIEW

**Comment by FichteFoll** [comment]
You should prepare an update message for the people still using this package, otherwise they might never notice.

See https://packagecontrol.io/docs/messaging for details. This requires you to push a versioned tag to the repo and switch release strategy from commit-based to tag-based and you should wait for a while after the update was pushed (maybe 1 month) to finally remove it.

**Comment by FichteFoll** [comment]
@lavrton ping

**Comment by FichteFoll** [comment]
@lavrton ping²

**Comment by lavrton** [comment]
Too many steps. I am not sure I have time for this.

**Comment by FichteFoll** [comment]
It's literally

1. change `"branch": "master"` to `"tags": true`
2. create a file with the message in the repo
3. create `messages.json` with an entry for `1.0.0` that points to the above file
4. push a tag named `1.0.0` to the repo

**Comment by FichteFoll** [comment]
Since #4693 caused a merge conflict with this PR, I'm closing it. Please open a new PR when you want to actually remove the package.

**Pull request closed without merging**
