### PR TITLE
Remove nathos/sass-textmate-bundle package

### PR DESCRIPTION
**Pull request by nathos**
Hey friends 👋 

I'd like to remove my (long abandoned 😢) Sass package from the directory, as I haven't maintained it in years, and it's probably doing more harm than good at this point. There are newer/better/actually supported [packages for Sass](https://packagecontrol.io/packages/Syntax%20Highlighting%20for%20Sass) and Sublime Text 3 today.

### CODE REVIEW

**Comment by FichteFoll** [comment]
@P233 would you be interested in taking over the "Sass" package name from @nathos? The package is among the top 25 most installed packages according to packagecontrol.io stats and the name speaks for itself. If @nathos believes your package to be substantially better than his, I see no problem with replacing that package with yours.

In this case, you should most likely prepare an update messages for users currently using the original Sass package and inform them about the take over. Then we'd replace his package entry with yours and add a previous_names entry for your old package names to get all current users of your package moved over, too. Feel free to ask any questions regarding this procedure.

I'll leave this PR open until we have decided on the following actions.

**Comment by P233** [comment]
Thanks @FichteFoll, I'd like to take over the "Sass" package name and keep maintaining.  Also thanks to @nathos, honestly I am inspired a lot by your work!

I will prepare an update message in a couple of days and let you guys review.

**Comment by P233** [comment]
I have prepared the update message: https://github.com/P233/Syntax-highlighting-for-Sass/blob/master/messages/1.2.2.txt Please see if it is appropriate and feel free to correct me.

I guess I could release a new tag and wait for you to replace the package entry?

Cheers

**Comment by FichteFoll** [comment]
I just pushed 9186277b2bc77b5ec037cf81e36131f07741d067. Please push the `v1.2.2` as soon as possible.

**Comment by P233** [comment]
Thank you, I have released the `v1.2.2` tag.

**Pull request closed without merging**
