### PR TITLE
add: project snippets

### PR DESCRIPTION
**Pull request by hemersonvianna**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

The name "Project Snippets" is very vague and does in no way hint the actual scope of the package. Maybe you can iterate on the name or explain to me why the name makes sense?

**Comment by hemersonvianna** [comment]
The idea is to have " Snippets Project " with HTML , CSS, JavaScript, Schema.org and resources to help in web development. I changed the name to " Front-end Project Snippets " , which brings more meaning.

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by hemersonvianna** [comment]
Done

**Comment by FichteFoll** [comment]
Just added a test for your temporary label "mis-used": https://github.com/wbond/package_control_channel/commit/03ba71c0036bcf651c915d45cb44f1e04a558f55

**Pull request merged**
