### PR TITLE
gherkin_auto_complete_plus

### PR DESCRIPTION
**Pull request by austincrft**
Added [gherkin_auto_complete_plus](https://github.com/austincrft/sublime-gherkin-auto-complete-plus) package

### CODE REVIEW

**Comment by FichteFoll** [comment]
The usual naming convention is to use PascalCase with optional whitespaces between words. Is there a specific reason why you chose to not follow that?

**Comment by austincrft** [comment]
In the [Submitting a Package](https://packagecontrol.io/docs/submitting_a_package) doc, it says "Use CamelCase or underscore_notation", so I assumed it was okay to use it. Also, it makes it easier to use [import statement in gherkin_event_listener.py](https://github.com/austincrft/sublime-gherkin-auto-complete-plus/blob/master/gherkin_event_listener.py#L4). Is there an easier way to do this? I'm okay with changing the name.

**Comment by FichteFoll** [comment]
>In the Submitting a Package doc, it says "Use CamelCase or underscore_notation", so I assumed it was okay to use it.

I see, I never noticed.

>Is there an easier way to do this?

Yes, just use a relative import.
These kind of imports only work on ST3 btw (on ST2 they need to be absolute but without the package name, oddly). Either you need to fix the imports or change the ST compatability.

**Comment by austincrft** [comment]
Ah, I didn't realize those imports would only work in ST3. I'll fix the import and then rename, because it seems underscore notation is an unpopular choice. Thanks!

**Comment by austincrft** [comment]
Okay, @FichteFoll. I think this should be satisfactory.

**Comment by FichteFoll** [comment]
You specify `"tags": "st3-"`, but there are actually no tags with this prefix on your repo. You want to set this to `"tags": true`.

**Comment by austincrft** [comment]
Okay, apparently I misunderstood their use in the docs. Got that fixed.

**Comment by FichteFoll** [comment]
Here's what you can do with them: https://raw.githubusercontent.com/FichteFoll/sublime_packages/master/package_control.json

**Pull request merged**
