### PR TITLE
Adding Merge Windows to m.json

### PR DESCRIPTION
**Pull request by chinchin96**
Adding a new package, Merge Windows to m.json.

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

**Comment by chinchin96** [comment]
Thanks Alex. 

Any idea when this might make it onto packagecontrol.io?

**Comment by AlexKvazos** [comment]
Hello @chinchin96, I am doing my best to talk with will and other maintainers to help out merging all this PRs.

**Comment by chinchin96** [comment]
Thanks for the quick reply, @AlexKvazos! Let me know if I can help at all. Y'all are great!

**Comment by chinchin96** [comment]
Hey wbond,

Sorry for the trouble. I've fixed the issue by adding a tag for v1.0.0.
[image: Inline image 1]


--------------------------------
Chinedu Ezeamuzie
(404) 514-7910

**Comment by chinchin96** [comment]
Thanks so much, wbond!

**Pull request merged**
