### PR TITLE
my first sublime plugin

### PR DESCRIPTION
**Pull request by CourageSuo**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by CourageSuo** [comment]
this plugin help developer write json faster

**Comment by math2001** [comment]
First, you need to add a `readme.md`

**Comment by FichteFoll** [comment]
Als, @math2001 said, please provide a readme that describes what the package does. I'm not trying to figure this out from reading the source, and neither are other potential users going to.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to your repo.

Because this would be your first release, the version `1.0.0` could be appropriate.

```sh
$ git tag v1.0.0
$ git push origin v1.0.0
```

Package Control will strip the optional `v` prefix.

**Comment by FichteFoll** [comment]
@CourageSuo ping

**Pull request closed without merging**
