### PR TITLE
Added PyQt and  Qt autocomplete ...

### PR DESCRIPTION
**Pull request by tushortz**
* Added PyQt autocomplete
* Added Qt autocomplete
* Renamed Wildlife 
* Added label for JavaIME

### CODE REVIEW

**Comment by tushortz** [comment]
I realised that a pull request of mine was marked as duplicate even after I had closed it earlier before opening a new one that includes two new packages

**Comment by FichteFoll** [comment]
You should definitely take a look at completions files instead of providing more than 10000 snippets in a package, each in their own file: http://docs.sublimetext.info/en/latest/reference/completions.html

**Comment by tushortz** [comment]
Thanks, I didn't know something like this existed. I'll definately have a
look

**Comment by FichteFoll** [comment]
@tushortz, since you replied by mail, I edited my above comment shortly after submission to include the following:

>Furthermore, in the conventional sense "autocomplete" refers to the static or dynamic analysis of source code and only suggestion completions for the available variables and their available attributes according to their type. Your packages are about the traditional "completion" instead.

**Comment by tushortz** [comment]
Thanks again. And from what you mentioned now, is it possible to do that on
sublime text as well.

**Comment by tushortz** [comment]
I'll close this pull request and create a new one for the updated packages

**Pull request closed without merging**
