### PR TITLE
Update t.json

### PR DESCRIPTION
**Pull request by stuartelimu**
Add Toggle Sidebar and Reveal Current File package

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is Toggle Sidebar and Reveal Current File

There are no packages like it in Package Control.

My package is similar to FocusFileOnSidebar. However it should still be added because they work differently

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
> I have tagged a release with a [semver](https://semver.org/) version number.

No, you [didn't](https://github.com/stuartelimu/toggle-sidebar-and-reveal-file/tags) 😉

**Comment by stuartelimu** [comment]
> > I have tagged a release with a [semver](https://semver.org/) version number.
> 
> No, you [didn't](https://github.com/stuartelimu/toggle-sidebar-and-reveal-file/tags) 😉

Sorted!🙈 
https://github.com/stuartelimu/toggle-sidebar-and-reveal-file/releases/tag/v1.0.0

**Comment by braver** [comment]
The normal “toggle sidebar” command is also available via the command palette. It would also make sense for your command, I think.

**Comment by stuartelimu** [comment]
Makes sense, I'll add it in the next release. Thank you

**Pull request merged**
