### PR TITLE
Add 'P4Explorer' repo to the default channel

### PR DESCRIPTION
**Pull request by ymengesha**

### CODE REVIEW

**Comment by ymengesha** [comment]
Corrected versioning.

**Comment by ymengesha** [comment]
Closing and reopening the PR to to trigger the packagecontrol-bot.

**Comment by FichteFoll** [comment]
Does [this line](https://github.com/ymengesha/P4Explorer/blob/4f90e14876b0ab8c1c3e8718239dd33e7e656703/P4Explorer.py#L55) also work on Windows systems and with Windows paths?

**Comment by ymengesha** [comment]
The [line](https://github.com/ymengesha/P4Explorer/blob/4f90e14876b0ab8c1c3e8718239dd33e7e656703/P4Explorer.py#L55) you're referring to is actually dealing with a perforce depot path. So I think it should be fine.

**Pull request merged**
