### PR TITLE
Add Caddyfile syntax

### PR DESCRIPTION
**Pull request by mholt**
Take three on #6580 and #6584...

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please add a proper version restriction to the package's release. And don't open a new PR. Package checks are re-run for new commits.

**Comment by mholt** [comment]
> Please add a proper version restriction to the package's release.

Done!

> And don't open a new PR. Package checks are re-run for new commits.

Of course, but in the previous PRs, there were no new commits to be made. 🤔 So I'm not sure what one would do in that case.

**Comment by FichteFoll** [comment]
If you don't have a commit to make, you can also trigger reviews by re-opening a pull request. You can also insert the JSON on this page: https://packagecontrol.io/test_repo.

In any case, I can manually trigger a review when I think I need one.

**Comment by mholt** [comment]
Ah, that's cool. Thanks! (My first submission, obviously. Thanks for the tutelage.)

**Pull request merged**
