### PR TITLE
Add the UnicodeCharacterInsert package

### PR DESCRIPTION
**Pull request by Sorbing**
**Sublime Text 3 Plugin for insert Unicode Character**

Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U-I</kbd> to open popup panel with Unicode Characters table.

Example screen:
The Unicode Characters popup window

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

The package won't work on ST3. Because packages are installed in an archived state there by default and you need to access package file contents using the `sublime.load_resource` API, which is only available to ST3.

**Comment by Sorbing** [comment]
Thanks for the tip. I fix inclusion the html resource through `sublime.load_resource`. Tell me please how to properly create a tag? At first I create a lightweight tag `v0.0.1`. And just now (after fix `load_resource`) I create a new tag `v0.0.2` ([see releases](https://github.com/Sorbing/sublime-unicode-character-insert/releases)). What did I do wrong? Thanks)

**Comment by FichteFoll** [comment]
Looks all right to me.

**Comment by princemaple** [comment]
interesting

**Pull request merged**
