### PR TITLE
A reincarnation of GPG plugin, as original repo was deleted

### PR DESCRIPTION
**Pull request by dmitrievav**
Please provide the following information:

 - Link to your code repository: https://github.com/dmitrievav/sublime_gpg
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/dmitrievav/sublime_gpg/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for sublime_gpg #############################

### Repository checks ###

No failures

No warnings

### Package checks ###

No failures

Reporting 1 warnings:
- '.no-sublime-package' is defined. Please verify that it is *really* necessary

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

From looking at the code, it doesn't look like you need it.

**Comment by dmitrievav** [comment]
Hi!
Usually GPG is used for sensitive information.
I put this file for security reason, to make people able to see the code they use.
Shall I delete it ?

**Comment by jrappen** [comment]
@dmitrievav Delete it. Whoever is interested in looking at the code, could do so by unpacking the `*.sublime-package` file as it actually is a `*.zip` provided you didn't compile your python code.

**Comment by dmitrievav** [comment]
'.no-sublime-package' removed

**Pull request merged**
