### PR TITLE
Add "Theme - Spaceblack"

### PR DESCRIPTION
**Pull request by saadq**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by FichteFoll** [comment]
Pull requests are automatically updated when you push commits to the branch you opened them from.

You need to push a tag to your repo.

**Comment by saadq** [comment]
Sorry, I'm a bit new to this as you can see. What kind of tag am I supposed to be pushing and how exactly would I go about doing it?

**Comment by FichteFoll** [comment]
`git tag v0.1.0`
`git push --tags`

**Comment by saadq** [comment]
Thanks for the suggestion, I'll definitely look into it! I've also added a tag to my repo, please let me know if it didn't work.

**Pull request merged**
