### PR TITLE
Added new Sublime-Blade package

### PR DESCRIPTION
**Pull request by jbrooksuk**
This is a better package.

### CODE REVIEW

**Comment by ahmadawais** [comment]
@jbrooksuk Your tests are failing probably because you have used the word `Sublime` in the package name, which I think is not allowed. Talking about the name parameter `Sublime Laravel Blade`

**Try not to use the word Sublime in your package name. Every package available via Package Control is for Sublime Text. Using the word Sublime just adds noise to the list when trying to find packages. You can use the word Sublime in your marketing material, but omit it the package list, e.g. Sublime SFTP.**

REF: https://packagecontrol.io/docs/submitting_a_package

**Comment by ahmadawais** [comment]
The tests for your package didn't pass: https://packagecontrol.io/docs/submitting_a_package#Step_7

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org/) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by FichteFoll** [comment]
^ what @ahmadawais said, except that the tests are failing because of [incorrect package ordering](https://travis-ci.org/wbond/package_control_channel/builds/132545971) and not the "Sublime" prefix, since we can not test for this. Nevertheless, you must choose a different name. 

Besides, how is this different from https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter and why can't you contibute to that instead?

**Comment by jbrooksuk** [comment]
Sorry, I've got to fix these up.

> Besides, how is this different from https://packagecontrol.io/packages/Laravel%20Blade%20Highlighter and why can't you contibute to that instead?

Originally Medialink wasn't responsive with things and took ages to get it up to date. He's since asked me to contribute with him (I'm yet to reply). But I'd be happy to, if I'm given repo access.

**Comment by FichteFoll** [comment]
@jbrooksuk ping

**Comment by Medalink** [comment]
I have added @jbrooksuk to my project. He has not yet contributed anything so I am unsure if he plans to help or still continue this side project.

**Comment by FichteFoll** [comment]
Since he stated his willingness for contribution, I'm closing this PR.

You can always open a new one when you change you mind.

**Pull request closed without merging**
