### PR TITLE
Kronuz Theme added

### PR DESCRIPTION
**Pull request by Kronuz**
This theme is the one I use. It's a clean, simple and easy on the eye dark theme

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Also, no screenshots?

**Comment by Kronuz** [comment]
Tes, workung on that :)

**Comment by Kronuz** [comment]
@FichteFoll I've added a couple screenshots, added the tag and cleaned some things in the theme. Current version is v1.1. I hope it's now ready for Package Control.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by Kronuz** [comment]
@FichteFoll, done! It's v1.0.0 now ...I hope this is it :)

**Comment by FichteFoll** [comment]
Yes, all good now.

**Pull request merged**
