### PR TITLE
Adding a new package (SublimeTextLanguagePortuguese) to PackageControl 

### PR DESCRIPTION
**Pull request by gusbemacbe**
Add Brazilian or European Portuguese spelling languages to your Sublime Text editor.

### CODE REVIEW

**Comment by gusbemacbe** [comment]
I didn't understand. I am still confused with this error.

**Comment by FichteFoll** [comment]
Your package name must not start with (or include) "SublimeText".

I'm not sure why the reviewer isn't working anymore, but the package itself looks okay.

**Comment by gusbemacbe** [comment]
@FichteFoll, I have just updated. I removed 'SublimeText' and renamed it to 'LanguagePortuguese', and I moved from s.json to l.json.

**Comment by gusbemacbe** [comment]
@FichteFoll, it worked now.

**Pull request merged**
