### PR TITLE
Add VueFormat package

### PR DESCRIPTION
**Pull request by lanbin**
It's a plugin for Vue file format.

### CODE REVIEW

**Comment by wbond** [comment]
You'll need to create a [semver](http://semver.org) tag at https://github.com/lanbin/vueformat/tags so users may install the package.

**Comment by lanbin** [comment]
@wbond thanks for your prompting

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
Furthermore, your code indicates support for all platforms but here you restrict the package to only be installable by OSX users. Further-furthermore, you should use `os.path.join` (and similar) when working with path strings.

**Comment by FichteFoll** [comment]
@lanbin ping

**Pull request closed without merging**
