### PR TITLE
Midnight theme for ST3

### PR DESCRIPTION
**Pull request by devottam**
A dark gray theme for Sublime text. Noticeably highlights selected item during auto-complete, command palette etc

### CODE REVIEW

**Comment by wbond** [comment]
So, you need to change `"branch": "master"` to `"tags": true` and then create at least one tag (https://github.com/devottam/midnight/tags) that is a three-part version number, e.g. `1.0.0`.

You don't need a new PR, just add a new commit with the changes.

**Comment by devottam** [comment]
Updated. Thanks!

**Comment by FichteFoll** [comment]
You still need to push a tag though.

**Comment by devottam** [comment]
__Sorry__ I thought, I pushed all the tags but somehow it didn't.

Done.
Thanks.

**Pull request merged**
