### PR TITLE
City Lights Theme

### PR DESCRIPTION
**Pull request by noudadrichem**
edits to fix errors

### CODE REVIEW

**Comment by FichteFoll** [comment]
You should add some content to your readme, like a screenshot.

**Comment by noudadrichem** [comment]
Hi @FichteFoll 

We're waiting for the merge to release all the other branding, website & readme included. 😊

**Comment by noudadrichem** [comment]
I've added a README.md file to the repository. See: https://github.com/Yummygum/city-lights-sublime

**Comment by noudadrichem** [comment]
@FichteFoll @wbond

**Comment by Yummygum** [comment]
We released a new update with tag 1.0.2 that fixes the UI assets issue.

**Comment by jrappen** [comment]
@noudadrichem just a heads-up: you can now use [PackageDev](https://github.com/sublimetext/PackageDev) to convert the color scheme(s) to the **new** [color scheme format for ST3149+](https://www.sublimetext.com/docs/3/color_schemes.html)

**Comment by noudadrichem** [comment]
Hi @jrappen , 

Thanks for the heads up! I'll take a look at it!

**Pull request merged**
