### PR TITLE
Bootstrap 4 latest snippet

### PR DESCRIPTION
**Pull request by hs950559**
- Latest bootstrap 4 snippet added inspired by https://github.com/JasonMortonNZ/bs3-sublime-plugin
- It will greatly improve developer productivity

### CODE REVIEW

**Comment by hs950559** [comment]
"cards/cards-title-subtitle-link.sublime-snippet" &->and issue fixed

**Comment by hs950559** [comment]
border, breakpoints, flex, headings, images, media, and typography snippet added

**Comment by FichteFoll** [comment]
You need to push a new tag with the recent fixes, so that PC can pick up the changes as a new release.

What are the differences of this package to this other bootstrap 4 snippets package? https://packagecontrol.io/packages/Bootstrap%204%20Snippets

**Comment by FichteFoll** [comment]
@hs950559 ping

**Pull request closed without merging**
