### PR TITLE
Register RailsGoToSass package

### PR DESCRIPTION
**Pull request by xijo**
A package to switch between views and sass files in a rails project

### CODE REVIEW

**Comment by xijo** [comment]
A package to switch between views and sass files in a rails project.

**Comment by FichteFoll** [comment]
This is a bit similar to https://packagecontrol.io/packages/Rails%20Related%20Files but for a more specific use case.

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by xijo** [comment]
Hello @FichteFoll,

thanks for your response. Indeed, the Rails Related Files is similar, but I really wanted a plugin that focusses on those specific sass files, within large rails codebases having seeing all related files can be quite chaotic.

What do you mean with change `"branch": "master"` to `"tags": true`? I created a 0.1.0 tag but can't yet change or create a new PR "for" this tag. The documentation for `Step 8` is not very specific regarding the creation of the PR.

Thanks for your help and your work on the package control!

**Comment by xijo** [comment]
@FichteFoll nevermind, I found the `tags: true` flag and added it. `v0.1.0` tag is created as well.

**Comment by FichteFoll** [comment]
@xijo it appears you didn't push your changes to the PR.

**Pull request merged**
