### PR TITLE
add Theme - Minimist

### PR DESCRIPTION
**Pull request by worg**
Add Minimist theme

 - Link to your code repository: https://github.com/worg/Minimist-SublimeTheme
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/worg/Minimist-SublimeTheme/tags

### CODE REVIEW

**Comment by math2001** [comment]
You need to add README, and a picture of sublime with your theme in it.

**Comment by worg** [comment]
Hi, there's a readme now, sorry.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
@worg ping

**Comment by worg** [comment]
`ack`
sorry I've been a bit busy, fixed the semver missing part

**Pull request merged**
