### PR TITLE
Adding Mithrilizer to package control

### PR DESCRIPTION
**Pull request by Bondifrench**
Auto completions for the [Mithril](http://lhorie.github.io/mithril/index.html) javascript framework

### CODE REVIEW

**Comment by FichteFoll** [comment]
>`"branch": "true"`

Unfortunately, this is not how it works. You need to change that to `"tags": true` and push a versioned tag to your repo.

**Comment by Bondifrench** [comment]
Sorry, it is my first time, should have corrected both issues now

**Comment by FichteFoll** [comment]
It has to be a plain boolean though, not a string.

**Comment by Bondifrench** [comment]
@FichteFoll 
What is missing now?

**Comment by FichteFoll** [comment]
Just a notification (comment) that something was changed.

**Pull request merged**
