### PR TITLE
Moved sublime-oz repo from rkoeninger to mozart

### PR DESCRIPTION
**Pull request by rkoeninger**
* Moved `Oz` package from `rkoeninger/sublime-oz` to `mozart/sublime-oz`.
* Added `snippets`, `build-system` tags to `Oz` package.

### CODE REVIEW

**Comment by Thom1729** [comment]
You should move the repo first. I think there's a way to redirect one repo to another.

**Comment by rkoeninger** [comment]
@Thom1729 Do you know when this can be merged? [Repos do indeed redirect from the old url](https://blog.github.com/2013-05-16-repository-redirects-are-here/), but I wanted to keep that window to a minimum to avoid confusion.

**Comment by Thom1729** [comment]
I can merge it right now if you put in a redirect.

**Comment by rkoeninger** [comment]
@Thom1729 Repo transferred: https://github.com/mozart/sublime-oz

**Comment by rkoeninger** [comment]
@Thom1729 thanks!

**Pull request merged**
