### PR TITLE
Added Lucene Query Formatter plugin

### PR DESCRIPTION
**Pull request by nishant-ns19**
Added a plugin to formatter lucene query objects for better readability.

### CODE REVIEW

**Comment by nishant-ns19** [comment]
How much time will it take to reflect changes in Sublime Text?

**Comment by FichteFoll** [comment]
> How much time will it take to reflect changes in Sublime Text?

Please read the pull request template that should be filled in when you open a pull request. That should have also told you how to request a new review from the bot instead of opening a new PR every time.

Anyway, the answer is: after I have reviewed, accepted and merged your changes.

**Comment by nishant-ns19** [comment]
Greetings, 
I would like to thank you for merging my  PR. Also I apologise for so many PR , actually it was my first time when I tried to make a plugin. May I know when can someone download my plugin from sublime package controller ?

**Comment by nishant-ns19** [comment]
Thank You !! I will keep the same in mind next time.

**Pull request merged**
