### PR TITLE
Add HISE Script

### PR DESCRIPTION
**Pull request by Levitanus**
is a little project trying to integrate HISE (hise.audio, https://github.com/christophhart/HISE) JS API into the Sublime Text
Features: new JS-based syntax, autogenerated API completions

### CODE REVIEW

**Comment by Thom1729** [comment]
There are several extraneous changes in the channel file.

You're modifying `sys.path` in HISEScript.py. This is strongly discouraged, because `sys.path` is a shared resource. Instead, use relative imports: `import .snippets`.

You don't need to watch for the `supress_completions` setting to change. When the setting changes, the `Settings` object will be updated internally, so the next time you get `settings['supress_completions']` it will return the correct value. If you do need to watch the settings object for some reason, you should make sure that the listener is eventually removed.

Rather than doing path manipulation with strings, you should use `os.path` (or the very handy [`pathlib` dependency](https://github.com/packagecontrol/pathlib).

**Comment by Levitanus** [comment]
Thanks for the review!
updated repository and version tag

**Comment by Thom1729** [comment]
There are extra changes in the channel file. It looks like you may be using some sort of auto-formatter.

**Comment by Levitanus** [comment]
reset to initial branch commit and updated repo one more time

**Comment by Levitanus** [comment]
Can't understand, what is wrong with the tag...

**Comment by Levitanus** [comment]
license added

**Pull request merged**
