### PR TITLE
New package added: CodeforcesUtil

### PR DESCRIPTION
**Pull request by shankhs**
- Link to code repository: https://github.com/shankhs/CodeforcesUtil
- Link to the tags page: https://github.com/shankhs/CodeforcesUtil/tags
- Link to the release page: https://github.com/shankhs/CodeforcesUtil/releases

### CODE REVIEW

**Comment by math2001** [comment]
You need to update your `readme`. 

@FichteFoll can you update the PR template saying: like this: `Fill your readme up!`

**Comment by shankhs** [comment]
@math2001 Thanks. I have updated the readme.

**Comment by math2001** [comment]
Hum, I still don't understand what it does... Could you be more descriptive? Maybe add a demo...

**Comment by shankhs** [comment]
Working on adding a demo

**Comment by shankhs** [comment]
ping

Can I help in anyways to expedite the merging of this PR? Thanks

**Comment by FichteFoll** [comment]
Please use the [`bs4`](https://github.com/jlegewie/sublime-beautifulsoup4) [dependency](https://packagecontrol.io/docs/dependencies) instead of bundling your own. This way many packages can share the same version without overriding one another (since a python interpreter realistically only every loads one version of a module).

**Comment by FichteFoll** [comment]
@shankhs ping

**Comment by shankhs** [comment]
Working on it

**Pull request closed without merging**
