### PR TITLE
Update branch for Toggle Words

### PR DESCRIPTION
**Pull request by timfjord**
Update the `branch` for `ToggleWords` package from `master` to `main`
image

### CODE REVIEW

**Comment by braver** [comment]
Branch based releases are not supported anymore actually, so please change to tag based releases.

**Comment by timfjord** [comment]
@braver Even for existing packages?
I am not an author of the package so I will try to reach out to the author

@gordio Is there a chance to change to the tag-based releases strategy for this package?

**Comment by braver** [comment]
Yes, we do not accept pull requests that use or change branch based releases. We also only accept pull request from package authors/maintainers.

**Comment by timfjord** [comment]
Ok, thanks the clarification

**Comment by gordio** [comment]
@timfjord ops… sorry. I check it right now

**Comment by braver** [comment]
Please also resolve the conflict.

**Comment by braver** [comment]
🤷🏻

**Comment by timfjord** [comment]
Addressed switching to `tags` in another PR https://github.com/wbond/package_control_channel/pull/8465

**Pull request closed without merging**
