### PR TITLE
adding ChapelLang

### PR DESCRIPTION
**Pull request by acrosby**
Please let me know if this wasn't done properly or if I need to fix something. Cheers!

### CODE REVIEW

**Comment by FichteFoll** [comment]
The tests don't pass: https://packagecontrol.io/docs/submitting_a_package#Step_7

**Comment by acrosby** [comment]
Perhaps you can explain why. The documentation isn't particularly helpful. Testing the local channel passes, but I have no idea how that might relate to the default channel. Thanks!

**Comment by FichteFoll** [comment]
The package is not in lexicographical order. It should be here: https://travis-ci.org/wbond/package_control_channel/builds/87895411#L154

Test failures explain why they failed. If you run them properly, they should also fail for you locally since it's the same code being run.

**Comment by acrosby** [comment]
Oh I see I pushed a change before i sorted , sorry for my confusion

**Comment by FichteFoll** [comment]
Oh yeah, and uncommited/unpushed changes is also a possibility.

**Pull request closed without merging**
