### PR TITLE
jQuery mobile demos

### PR DESCRIPTION
**Pull request by coderyang**

### CODE REVIEW

**Comment by FichteFoll** [comment]
I think you are using `gen_commands.py` locally to generate `Default.sublime-commands` since it currently would be automatically loaded by ST and not work.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by coderyang** [comment]
Oh, This is my first time to write plug-ins for sublime-text, and I am not familiar with the workflow of publishing a package. I think I have fixed the problem. Thanks for your reminder.

**Comment by FichteFoll** [comment]
Don't forget to push a new tag after the changes.

**Comment by coderyang** [comment]
Ok!

**Pull request merged**
