### PR TITLE
added repository rcraggs/feedwack

### PR DESCRIPTION
**Pull request by rcraggs**
Added new repo for my little plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
Seems to be very specific indeed, but whatever.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@rcraggs ping

**Comment by rcraggs** [comment]
Sorry - done now.

**Comment by FichteFoll** [comment]
By the way, instead of looking for feedback with plugin code you could use http://docs.sublimetext.info/en/latest/reference/symbols.html.

**Pull request merged**
