### PR TITLE
Adds ruby-idiomatic-snippets channel.

### PR DESCRIPTION
**Pull request by mark-d-holmberg**
This package overrides the default ruby snippet for "begin .. rescue .. end" to not rescue Exception but rather StandardError, as rescuing from "Exception" is frowned upon and not the idiomatic way.

### CODE REVIEW

**Comment by FichteFoll** [comment]
If it's a general improvement to the default snippets and the current version strictly inferior, I'm sure a PR at https://github.com/sublimehq/Packages would be accepted. Other than that, it appears Sublime Hq is generally looking to remove snippets from the default packages in the future, so new snippets wouldn't be accepted. However, fixing or changing existing ones is fine.

**Comment by mark-d-holmberg** [comment]
I will definitely do that.

**Comment by mark-d-holmberg** [comment]
https://github.com/sublimehq/Packages/pull/2183

**Comment by FichteFoll** [comment]
Thanks. I'm closing, then.

**Pull request closed without merging**
