### PR TITLE
Add gerardroche/sublime-php-snippets; Closes gerardroche/sublime-php-snippets#2

### PR DESCRIPTION
**Pull request by gerardroche**

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://travis-ci.org/wbond/package_control_channel/builds/70090093#L176

**Comment by gerardroche** [comment]
Must be because I force pushed a fix.

**Comment by gerardroche** [comment]
:+1: needed to be sorted properly.

**Comment by FichteFoll** [comment]
It should have linked you to the exact line where the package needed to be.

**Comment by gerardroche** [comment]
It did, I didn't read the error message properly ;)

**Pull request merged**
