### PR TITLE
New Rocks Plugin

### PR DESCRIPTION
**Pull request by jonesambrosi**
- Link to your code repository: [https://github.com/jonesambrosi/rocks](url)
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/jonesambrosi/rocks/tags

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for rocks ###################################

### Repository checks ###

No failures

Reporting 1 warnings:
- Only found pre-release tags.

### Package checks ###

Reporting 2 failures:
- '.sublime-workspace' files contain session data and should never be submitted to version control
    File: rocks.sublime-workspace
- `messages` folder exists, but `messages.json` does not

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

You should remove the `dependencies` line from this PR since you also have a `dependencies.json` file in your repository (which is the preferred way).

**Comment by jonesambrosi** [comment]
It is correct now. I'm create release v0.0.1.

**Comment by FichteFoll** [comment]
>You should remove the `dependencies` line from this PR since you also have a `dependencies.json` file in your repository (which is the preferred way).

**Comment by jonesambrosi** [comment]
Ok ... Done!

**Comment by jonesambrosi** [comment]
Changes made

**Comment by FichteFoll** [comment]
You still have your `.sublime-workspace` file in the repository, but I'm not gonna block the PR just for that. I still recommend you to remove it.

**Pull request merged**
