### PR TITLE
add a mobile ui framework for sublime

### PR DESCRIPTION
**Pull request by tangbindu**

### CODE REVIEW

**Comment by tangbindu** [comment]
add a mobile ui framework for sublime

**Comment by tangbindu** [comment]
add a mobile ui framework for sublime      fixed a bug

**Comment by tangbindu** [comment]
add a mobile ui framework for sublime fixed a bug    help me

**Comment by saadq** [comment]
The tests are failing because you need to keep the packages in alphabetical order. Your package which is named **CUI** should go after the **CUE Sheet** package and before the **Curly Syntax Definition** package. 

Also, you'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid semantic version tags to your repo. As mentioned in the docs, branch-based releases are no longer accepted for new packages.

**Comment by FichteFoll** [comment]
What @saadq said.

Additionally, instead of providing completions via plugin code you could as well define a `.sublime-completions` file, since your plugin doesn't do anything dynamic at all. Read more here: http://docs.sublimetext.info/en/latest/reference/completions.html

**Comment by wbond** [comment]
@tangbindu This is just a reminder that your PR needs work before we can accept it. :smile:

**Pull request closed without merging**
