### PR TITLE
glslViewer

### PR DESCRIPTION
**Pull request by patriciogonzalezvivo**
Require a 3rd party application ( https://github.com/patriciogonzalezvivo/glslViewer )

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

I suggest providing a setting for the path for the user's `glslViewer` executable.

**Comment by patriciogonzalezvivo** [comment]
Done! Thanks you

**Comment by FichteFoll** [comment]
Looks good.

However, your update message `"0.1.0": "messages/0.1.0.txt"` should be `"install": "messages/install.txt"` (and the file renamed accordingly).

**Comment by patriciogonzalezvivo** [comment]
Roger that! I just change it. Thanks @FichteFoll

**Pull request merged**
