### PR TITLE
take over VintageLines

### PR DESCRIPTION
**Pull request by co-dh**
The tmanderson/VintageLines seemed abandoned.
I have a pull request sit for 40 days.
I've implemented new features and would like to take over.

### CODE REVIEW

**Comment by FichteFoll** [comment]
@tmanderson, I know you marked declared your package as being unmaintained, but maybe you have a certain plan in mind for handing it over, such as adding a collaborator or just moving the repo entirely. That way issues and would be transferred and urls redirected.
If you don't reply within two weeks, I will just replace the reference to your package with one to @co-dh's fork.

@co-dh, please consider adding your package directly to one of the `repository/*.json` files. It's easier to maintain if the package references are centralized (e.g. you are still using schema 2.0).

**Comment by co-dh** [comment]
@FichteFoll  ok. will do in 1 week.

**Comment by co-dh** [comment]
Done. let me know if anything wrong.

**Comment by FichteFoll** [comment]
You need to change `"branch": "master"` to `"tags": true` and remove the reference to the original https://raw.githubusercontent.com/tmanderson/VintageLines/master/packages.json in `channel.json`.

**Comment by co-dh** [comment]
Done. thanks.

**Comment by tmanderson** [comment]
@co-dh @FichteFoll, sorry for the slow responses and  glad to see that you've taken control of everything! Thanks a lot! I'll update my repo to reference yours as the new source.

**Comment by FichteFoll** [comment]
@co-dh, another thing I just noticed: Your package has a space between "Vintage" and "Lines", causing it to be recognized as a different package. You either have to properly rename it by adding a `previous_names` array or change the name to the original.

You also have to push a new tag in order to create a release. I has to be higher-versioned than `0.5.7`.

**Comment by co-dh** [comment]
all done. removed the space, and a new tag v0.5.8 released.
Thanks :)

**Comment by co-dh** [comment]
Thanks a lot @FichteFoll 
When will this be released? I'd like to test.

**Comment by FichteFoll** [comment]
Changes may take up to one hour to be detected.

**Comment by co-dh** [comment]
It already works . Thanks.
If I update the github and create a new tag, will it automatically take
effect?

**Comment by FichteFoll** [comment]
Yes, same story.

**Pull request merged**
