### PR TITLE
Add Hadar Theme to h.json

### PR DESCRIPTION
**Pull request by CristianVasquez13**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] Any commands are available via the command palette.
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").

There are no packages like it in Package Control.

[1]:https://packagecontrol.io/docs/submitting_a_package
[2]:https://semver.org/

### CODE REVIEW

**Comment by braver** [comment]
Your theme seems to have some settings. Shouldn't they be exposed to the end user?

**Comment by braver** [comment]
The bot feedback is fine, you don't need a license file. Please address my earlier feedback about the settings.

**Comment by braver** [comment]
> Your theme seems to have some settings. Shouldn't they be exposed to the end user?

☝🏻

**Comment by CristianVasquez13** [comment]
Y como hago eso de la configuración? 🤔

**Comment by braver** [comment]
You would usually have a menu entry (and a command palette entry) that allows a user to open and edit the settings.

**Comment by braver** [comment]
I'm going to close this as stale, please respond (hopefully in English, sorry about that) if you want to continue.

**Comment by jwortmann** [comment]
> You would usually have a menu entry (and a command palette entry) that allows a user to open and edit the settings.

Those menu and command palette entries are already included in Sublime Text; the menu entry is under *Preferences > Settings* (might be different on macOS (?)) and the command palette entry is *Preferences: Settings*.

Note that unlike plugins, themes cannot define their own settings files, instead settings are always read from the genereal *Preferences.sublime-settings* file.

In theory, a theme could add another entry to open a predefined *Preferences.sublime-settings* file on the lefthand side, and the users setting on the righthand side, but then the [built-in settings](https://www.sublimetext.com/docs/themes.html#settings) which are expected to be implemented by themes, wouldn't be visible. And I doubt that there are many themes which do it this way. Instead, I would just describe the settings in the Readme page.

**Pull request closed without merging**
