### PR TITLE
CollaBroText

### PR DESCRIPTION
**Pull request by aaronfernandes45**
This plugin is used to enhance collaboration between software developers working on same project remotely in Sublime Text. Main functionality is commenting on a file in a similar way to how Google Docs does it. We are using git to keep the comments synced via Github or any other site you may wish to use for your project

Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please remove `repository/c.json~` from the PR.


## Report for CollaBroText ############################

### Repository checks ###

Reporting 1 failures:
- No semantic version tags found (no tags found at all)

No warnings

### Package checks ###

No failures

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

You might also find the `View.show_popup` and `EventListener.on_hover` APIs interesting for showing comments.

**Comment by math2001** [comment]
Why is it only available on Linux? I'm not sure you need the `__init__.py` at the root of your package

**Comment by FichteFoll** [comment]
@aaronfernandes45 ping

**Comment by aaronfernandes45** [comment]
The plugin is only available for Linux, currently, because we are a team of
6 people who built this plugin as a project for our Final Year of
Engineering (Undergrad). We do have plans to add support for Windows and
Mac but we will do so in future versions of the plugin.

Semantic versioning tag has been added.
Also removed repository/c.json~

**Comment by FichteFoll** [comment]
Unfortuntely it seems you forgot to push the removal of `repository/c.json~`.

**Pull request closed without merging**
