### PR TITLE
Add CoberturaCoverage to respository

### PR DESCRIPTION
**Pull request by jeffrand**
Signed-off-by: Jeff Rand <jeff.rand@artivest.co>

### CODE REVIEW

**Comment by FichteFoll** [comment]
`ctrl+shift+n` is a default binding. Please choose a different one or don't define one at all and let users set their own.

**Comment by FichteFoll** [comment]
Remember that you need to push a  new tag in order to publish a release.

**Comment by jeffrand** [comment]
@FichteFoll done! Let me know if there's anything else I need to do.

**Comment by FichteFoll** [comment]
Your `messages.json` file contains a trailing comma, which is invalid JSON.
It won't matter currently since nobody will see the update messages (they only start seeing these once they installed the package and it's not yet installable).

**Pull request merged**
