### PR TITLE
Added ng-snippets package

### PR DESCRIPTION
**Pull request by alsfurlan**
How we speak earlier on...
https://github.com/wbond/package_control_channel/pull/4188#event-329582379
follow my pull request.

### CODE REVIEW

**Comment by alsfurlan** [comment]
@FichteFoll How I know when will avaiable the package? I don't use much Github.

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/ng-snippets

**Comment by alsfurlan** [comment]
Ok! But packages list in my sublime text don't show the package, that's normal?

**Comment by alsfurlan** [comment]
Thanks @FichteFoll!

**Pull request merged**
