### PR TITLE
Adding Newline Separated to List

### PR DESCRIPTION
**Pull request by jeechu**
Please provide the following information:

 - Link to your code repository: https://github.com/Jeechu/NewlineSeparatedToList
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/Jeechu/NewlineSeparatedToList/releases/tag/0.1.0

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by joshua-golub** [comment]
@Jeechu, would you please add an example to your `README` file? I don't quite follow what this package will do.

-Josh

**Comment by Jeechu** [comment]
@joshua-golub Added a few examples. I hope it explains what this package does.

**Comment by FichteFoll** [comment]
Your package name contains a typo. It should be "separated"

**Comment by jeechu** [comment]
@FichteFoll Thanks for pointing it out. The repo name was correct, I misspelt it in 3 instances(2 in README + 1 in a commented line) and while creating the pull request. Fixed them.

**Pull request merged**
