### PR TITLE
add ThinkphpBjy pachage

### PR DESCRIPTION
**Pull request by baijunyao**
add ThinkphpBjy pachage

### CODE REVIEW

**Comment by FichteFoll** [comment]
How does this package compare to https://packagecontrol.io/packages/Thinkphp?

**Comment by FichteFoll** [comment]
@baijunyao ping

**Comment by baijunyao** [comment]
1：Add some code fragments;
2：Delete some menus;
3：Easy to edit;

**Comment by FichteFoll** [comment]
If the differences are so small, please consider adding these to @yangweijie's instead.

**Comment by baijunyao** [comment]
thanks you;

**Pull request closed without merging**
