### PR TITLE
Add MIT Alloy highlighting.

### PR DESCRIPTION
**Pull request by corbanmailloux**

### CODE REVIEW

**Comment by FichteFoll** [comment]
FYI, you don't need to escape forward slashes or hypens outside of sets in regular expressions.

**Comment by corbanmailloux** [comment]
Thanks. Just to clarify, you mean:
```
- comment: Line comment
  name: comment.double-slash
  match: \/\/.*$
```

could be replaced with:
```
- comment: Line comment
  name: comment.double-slash
  match: //.*$
```

Correct?

**Comment by FichteFoll** [comment]
Yes.

And `match: \-\-.*$` with `match: --.*$`.

**Comment by corbanmailloux** [comment]
Okay. Thanks for the heads up. I'll change it over.

**Pull request merged**
