### PR TITLE
Added ExpressComplete

### PR DESCRIPTION
**Pull request by Heedster**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

Also, it should be [here](https://travis-ci.org/wbond/package_control_channel/builds/53763425#L184).

**Comment by Heedster** [comment]
Changed version number. 
Changed to alphabetical order.

**Comment by FichteFoll** [comment]
You still need to push a tag.

**Comment by Heedster** [comment]
I dont understand. I updated the version tags in my repo as you suggested. 
https://github.com/Heedster/ExpressComplete/blob/master/package.json

This is not what you want?

**Comment by FichteFoll** [comment]
No, you need to push a tag to the github repo by creating it normally `git tag v1.0.1` and then pushing it `git push --tags`.

**Comment by Heedster** [comment]
Ok. Thanks for that. Done!

**Pull request merged**
