### PR TITLE
add Theme - DC

### PR DESCRIPTION
**Pull request by dubeg**
Add theme for Sublime Text 3

### CODE REVIEW

**Comment by FichteFoll** [comment]
Since theming hasn't really changed between ST2 and ST3 you should be able to allow this package for ST2 as well.

**Comment by dubeg** [comment]
Ok, the theme should work with ST2 now.

**Comment by dubeg** [comment]
Just a question because i don't know where to discuss this. Should I remove the file icons from the theme package and put them in a new one? Most icons are from the Seti UX/UI package, but I changed and added a few. Hmm.

**Comment by FichteFoll** [comment]
Why would you want to do that? You need those icons in the theme, don't you?

**Comment by dubeg** [comment]
Yeah, well, you can have custom file icons without a custom theme. And maybe some ppl prefer the original Seti icons to some of my versions. 

Also, I just tested this: some pref. files seem to conflict with Cobalt2. I guess because their names are slightly different and they don't get overriden. You can disable the unused theme, but meh.

I thought it would be cool to have icon packages like we have for color schemes and UI themes. Anyway, I probably won't do it.

**Comment by FichteFoll** [comment]
The problem with icon packages is that they need a file with the same name as the current theme in the package root so that the icons are considered. This could be achievable with some plugin code however.

Anyway, your decision.

**Pull request merged**
