### PR TITLE
Add "Git Commit Message Auto Save"

### PR DESCRIPTION
**Pull request by aristidesfl**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You need to test whether `view.file_name()` is `None` because otherwise the following attribute access raises an exception.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by aristidesfl** [comment]
@FichteFoll thanks, fixed! 👍

**Comment by aristidesfl** [comment]
How long does it take until it is available through package control?

**Comment by FichteFoll** [comment]
Up to an hour.

**Pull request merged**
