### PR TITLE
Added GitHubFileFetcher Package.

### PR DESCRIPTION
**Pull request by dennykorsukewitz**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is [GitHubFileFetcher](https://github.com/dennykorsukewitz/Sublime-GitHubFileFetcher).
This package searches and fetches files from GitHub.

githubfilefetcher

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Is the list of possible repositories a "white list", ie. only repos in that list can be searched?

**Comment by dennykorsukewitz** [comment]
> In the main menu file, for any existing entries like "Preferences", "Package Settings", etc. please only provide the id. Otherwise you're effectively overriding the menu entry name/caption and mnemonic.
> 
> The Default.sublime-keymap file doesn't seem to exist in your repo?

Ah good to know.
I fixed that all with https://github.com/dennykorsukewitz/Sublime-GitHubFileFetcher/commit/622d267ff995aedd6e8dee7fa03aa091e618cc2b

**Comment by dennykorsukewitz** [comment]
> Is the list of possible repositories a "white list", ie. only repos in that list can be searched?

It is rather a list of already saved repos (from already searched repos). 

You are looking for a repo. Either by the owner or directly by name.

Then you can get the desired file in the desired branch.

Finally, you are asked whether you want to save this repo. 
This list of saved repos is then displayed each time.

This allows you to use your frequently used repos quickly.

**Comment by braver** [comment]
Alright, let's ship this, but don't forget to tag a new release with your latest changes. Package Control only sees the tags on your repo, general commits won't deploy to end users.

**Pull request merged**
