### PR TITLE
added color scheme package

### PR DESCRIPTION
**Pull request by b0xw00d**
Added my color scheme package.

### CODE REVIEW

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

A readme with a screenshot is also much appreciated.

**Comment by b0xw00d** [comment]
Done.  Let me know if you need anything else on my end.  Thanks!

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by wbond** [comment]
You should delete the tags `v1.0`, `v1.1` and `v1.2` since they are confusing with `v1.0.0` also present.

Could you add a screenshot to the readme?

**Comment by b0xw00d** [comment]
good to go?

**Pull request merged**
