### PR TITLE
added DumperWrap

### PR DESCRIPTION
**Pull request by barkonar**
- Link to your code repository: https://github.com/barkonar/dumperwrap
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/barkonar/dumperwrap/tags

### CODE REVIEW

**Comment by wbond** [comment]
@barkonar Can you update the key bindings to not override one of the defaults?

**Comment by barkonar** [comment]
OK. Key bindings changed. 

BTW. How is that possible that "Console Wrap" package uses "ctrl+shift+q" which overrides:
` { "keys": ["ctrl+shift+q"], "command": "run_macro" }` (on Windows) and everything is fine?

**Comment by AlexKvazos** [comment]
@barkonar Can you please create a release tag on your package?

**Comment by FichteFoll** [comment]
> How is that possible that "Console Wrap" package uses "ctrl+shift+q" which overrides:
{ "keys": ["ctrl+shift+q"], "command": "run_macro" } (on Windows) and everything is fine?

Because the package is three years old and we didn't have this guideline in place back then (or, maybe we did, but a human (myself) missed this, because we didn't have automated reviews).

**Comment by barkonar** [comment]
Release tag added: https://github.com/barkonar/dumperwrap/releases

**Pull request merged**
