### PR TITLE
Add Bootstrap autocomplete

### PR DESCRIPTION
**Pull request by kennith**
This pull request adds Bootstrap Autocomplete package. 

I already review existing packages, but the developers of the package are not responsive to the merge request. 

[Done] Reviewing Existing Packages

Request to [bootstrap-4-autocomplete](https://github.com/webchun/bootstrap-4-sublime-autocomplete/pull/5)

Request to [sublime-text-bs4-autocomplete](https://github.com/proficientdesigners/sublime-text-bs4-autocomplete/pull/2)

[Done] Tests locally 

[Done] Add README to package

This package autocompletes Bootstrap classes. A similar package exists, but the authors were not responsive to update requests.

### CODE REVIEW

**Comment by kennith** [comment]
Fixed.

**Comment by FichteFoll** [comment]
How does this differ from these other packages? https://packagecontrol.io/search/bootstrap%204

Autocompletion suggests a context awareness, however you only provide static completions. Please remove the "auto" part from the package's name.

**Comment by kennith** [comment]
@FichteFoll I made PR to both package to add missing classes, but it's non-responsive. I created this one with the updated class lists.

**Comment by FichteFoll** [comment]
It appears [your PR](https://github.com/proficientdesigners/sublime-text-bs4-autocomplete/pull/2) to "Bootstrap 4x Autocomplete" has been applied manually (via https://github.com/proficientdesigners/sublime-text-bs4-autocomplete/commit/ef9227b5ef920bf6bbc92d46e29270177d5fa22d). Is this package still needed?

**Comment by kennith** [comment]
@FichteFoll Thanks! It looks like @proficientdesigners close the PR and apply update w/o merge. A bit confusing on my end. Thanks for looking it up. 

This package is no longer needed if @proficientdesigners continue to update the package.

**Pull request closed without merging**
