### PR TITLE
New Ansible syntax for Sublime Text 4

### PR DESCRIPTION
**Pull request by killua99**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is an updated Ansible syntax, the other package is abandoned.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by killua99** [comment]
what else does it need to advance ?

**Comment by braver** [comment]
> what else does it need to advance

Patience padawan 🤗

**Comment by braver** [comment]
@clifford-github your Ansible package for Sublime is really old. If you don't intend to update it, can you maybe

- give @killua99 access to your repo so he can continue your work and create new versions of the package
- or allow us to replace your package with his neo package

If we don't get a reaction within some time (typically 2 weeks, or whenever after that period we have time to revisit this PR) we'll opt for the second option.

**Comment by clifford-github** [comment]
@braver I added @killua99 as contributor to the project.
The second option is OK from my side. Do I have to do something?

**Comment by braver** [comment]
Oh, that's excellent. The ideal situation IMO is if the original work is continued in that a repo. That way everyone knows where to find it. Also, in that case we don't have to do anything here. Thanks all!

**Pull request closed without merging**
