### PR TITLE
Add Materializecss Snippets

### PR DESCRIPTION
**Pull request by leninalbertolp**
Collection of snippets for materializecss, complete and understandable, updated.

Is that there is already an equal to this plugin, but the existing 3 versions outdated regarding materializecss updates, I will make every effort to maintain my plugin updated and abreast with updates from materializecss.Add my plugin, materializecss snippets.

Sorry for my horrible English, is not my native language.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your package's name is too similar to "Materialized CSS Snippets".

Perhaps you can contribute to @ayinloya's package instead of adding your own and keep it up to date? It seems like he has been very open to PRs so far: https://github.com/ayinloya/materialized-css-snippets/pulls?q=is%3Apr+is%3Aclosed

**Comment by leninalbertolp** [comment]
ok thanks, I'll put in contact to see how we can solve, I intend to keep my plugin updated and provide a good user experience.

The plugin built by **[@ayinloya](https://github.com/ayinloya)** this somewhat outdated regarding Materializecss Framework versions and many things have changed since then.

**Comment by FichteFoll** [comment]
@leninalbertolp any update?

**Comment by leninalbertolp** [comment]
@FichteFoll  excuse me for my bad English, it is not my native language.

I do not understand your question

**Comment by FichteFoll** [comment]
Were you able to get in contact with @ayinloya and did you work something out?

**Comment by leninalbertolp** [comment]
@FichteFoll 
If you talk to, respect the work of @ayinloya, I don't know, what other things have occupied their time, but there are three people working in its repository and at this point there are several outdated snippets of your project.

So I think, that they are not 100% committed to the project and I do not work that way.

Therefore, if you believe that my plugin can not enter Pakage control, because already there is the @ayinloya, you can close this pull.

**Comment by FichteFoll** [comment]
I do not intend to solve every conflict and I won't force people to collaborate when they don't want to (although I encourage them to do so), but your packacge names are still too simiar.

**Comment by ayinloya** [comment]
@FichteFoll , I'm always open to contributions. The [materialized css snippits](https://github.com/ayinloya/materialized-css-snippets) project is dependent on [materializecss](http://materializecss.com/) and has not been updated recently because there hasn't been much change. I believe @leninalbertolp's plugin can still be accepted under a different name if it's that different from the already existing one or @leninalbertolp you can let us merge the snippets that are up to date, I'm really ok with any of those options.

**Comment by leninalbertolp** [comment]
@FichteFoll @ayinloya, I want to clarify some things, my intention is not to discredit the work of no one, and much less to say that my work is better. Only that, if I'm going to work with people, I like that they are committed to the project.

@ayinloya your repository has such outdated CDN snippets, the current version of materializecss is 0.97.6 and yours is still in version 0.97.3. Change a simple number does not take 1 minute. This is what I am referring to the commitment to the project. materializecss has also added a new card option.

I'm willing to work and contribute with you, my intention is provide to the community without search prominence.

@ayinloya I apologize if we begin with the left feet :) I will put in contact with you

**Comment by ayinloya** [comment]
@leninalbertolp , thanks for your consideration :) :+1:

**Comment by wbond** [comment]
So is collaboration happening on another package now? Should this PR be closed?

**Comment by leninalbertolp** [comment]
if you can close this petition

**Pull request closed without merging**
