### PR TITLE
Added Jenkinsfile plugin

### PR DESCRIPTION
**Pull request by june07**

### CODE REVIEW

**Comment by june07** [comment]
Added version tag.  0.1.0

**Comment by june07** [comment]
LICENSE is there?!

**Comment by june07** [comment]
@wbond Do I need to perform some magic here?

**Comment by Thom1729** [comment]
You probably need to release a new tag.

**Comment by Thom1729** [comment]
A few comments:

- Instead of `'win32' in str(sys.platform).lower()`, use `sublime.platform() == 'windows'`.
- In a `TextCommand`, instead of `view = sublime.Window.active_view(sublime.active_window())`, use `view = self.view`.

**Comment by june07** [comment]
@Thom1729 Updated.

**Pull request merged**
