### PR TITLE
Add ChromiumTodoView-sublime to available packages

### PR DESCRIPTION
**Pull request by dougt**
Please provide the following information:

 - Link to your code repository:

https://github.com/dougt/ChromiumTodoView-sublime

 - Link to the tags page with at least one [semver](http://semver.org) tag: 

https://github.com/dougt/ChromiumTodoView-sublime/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))

Done.

 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

Done.

### CODE REVIEW

**Comment by math2001** [comment]
You need a `readme.md` file

**Comment by dougt** [comment]
> You need a readme.md file

Done.

> why don't you just import your script get_chromium_issue_data.py instead of running it as a subprocess?

The python version that used in Sublime Text is different and incompatible with the version required for depot_tools.  See the comment here: https://github.com/dougt/ChromiumTodoView-sublime/blob/master/ChromiumTodoView.py#L53

**Comment by math2001** [comment]
But, a user that doesn't have python installed (the right version, btw) on its system *cannot* use this plugin?

**Comment by dougt** [comment]
> But, a user that doesn't have python installed (the right version, btw) on its system cannot use this plugin?

Yes, that is correct.  To use this plugin, you need to have depot installed and configure the settings to point to it.  Note, that in order to build chromium, people use a set of tools called depot.  (You can read about them here: https://dev.chromium.org/developers/how-tos/install-depot-tools).  These tools require Python 2.7+.  So, a user may have newer versions of Python installed on their system, but they typically will use 2.7 for chromium development.

> BTW, this doesn't work on my machine. Do we need to install them?

Please make sure you have set up a chromium build, verified the settings for this plugin are correct.  If it still doesn't work, please send me a console log.  Happy to see what's going on.

> What is incompatible?

A ton! Someone probably could go update all of the chromium tooling, but I don't think anyone has had time/desire.  For example, the depot tooling still uses 2.7-isms like "print a" instead of "print(a)".

**Comment by FichteFoll** [comment]
Since I just mentioned this in a different PR, I'll just reference that here: https://github.com/wbond/package_control_channel/pull/6125#issuecomment-280937670
It's the second part that is relevant.

**Comment by FichteFoll** [comment]
@dougt ping

**Comment by dougt** [comment]
merge conflict resolved.

As for protecting windows developers from path woes, I sympathize.  I will add better logging to console if I can't find any of the paths in settings.  That's a good suggestion.

**Comment by FichteFoll** [comment]
It seems you misunderstood. What I was going at was the need for a `.no-sublime-package` file.

**Comment by dougt** [comment]
Ah. Got it.  Fixed.

**Pull request merged**
