### PR TITLE
add new package : iconfont snippets Amos

### PR DESCRIPTION
**Pull request by badprint**
this package is bootstrap & font awesome icon font snippet, use Chinese keyword. Convenient Chinese user. you can see animation demo, Thank you
http://csscoke.com/ST-iconfont/ST-iconfont-demo.html

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by badprint** [comment]
Hi FichteFoll  i add version tag done! Please you look, thank you.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by badprint** [comment]
OK, I've added to v0.2.0

**Pull request merged**
