### PR TITLE
Update spec finder repo url

### PR DESCRIPTION
**Pull request by rogeriochaves**
The sublime plugin is no longer available on the original repository and I used it a lot, so I forked and improved the plugin (to find the specs faster and with more precision).

### CODE REVIEW

**Comment by FichteFoll** [comment]
@resellercore, what happened there?

@rogeriochaves, for the same reason we don't allow new packages with branch based releases, we don't allow switching back to it either: they have been deprecated.

**Comment by rogeriochaves** [comment]
@FichteFoll okay then, done!

I searched but I couldn't find any other ways to contact @resellercore, neither any explanation why they deleted the repo.

**Comment by FichteFoll** [comment]
We'll wait a few days for an answer. Until then, you can push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by rogeriochaves** [comment]
@FichteFoll sorry, I forgot to push the tags, is everything ok now?

**Comment by FichteFoll** [comment]
Yes, all okay. We'll wait for another few days however, imo 2 weeks are a minimum for these issues.

**Comment by bfocht** [comment]
the repo on the resellers group was deleted.  I am not able to approve pull requests for @wbond

**Comment by FichteFoll** [comment]
@bfocht, I am unsure what you mean with that. If the package was deleted and there is no replacement for it, I will just replace the record on Package Control with the fork by @rogeriochaves (in 1-2 days).

**Pull request merged**
