### PR TITLE
added swift completion

### PR DESCRIPTION
**Pull request by tushortz**
Please provide the following information:

 - Link to your code repository: https://github.com/tushortz/Swift-Completion
 - Link to the tags page with at least one [0.0.1](https://github.com/tushortz/Swift-Completion/tree/0.0.1) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
Fill in the message, please.

**Comment by tushortz** [comment]
- Link to your code repository: https://github.com/tushortz/Swift-Completion
 - Link to the tags page with at least one [0.0.1](https://github.com/tushortz/Swift-Completion/tree/0.0.1) tag:

**Comment by math2001** [comment]
You see that you're adding `Beautiful Soup Completion` at the same time?

**Comment by tushortz** [comment]
@math2001 yes, I don't know why. It shouldn't be there because it is already on package control

**Pull request closed without merging**
