### PR TITLE
RPN - Reverse Polish Notation Calculator

### PR DESCRIPTION
**Pull request by bphunter1972**
Supersedes pull request #4292. Let's hope this one's better.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Okay, so far so good, but [semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by bphunter1972** [comment]
Done. That’s the last time I listen to GitHub’s tagging recommendations.

**Comment by FichteFoll** [comment]
It's not that github's recommendation is wrong. There are many different versioning schemes.

Also, it is better if you know what semver actually is (I suggest reading the spec it if you didn't already) before unconsciously using versions that conform its standard. It won't really matter for package control since packages can not be used as dependencies and semver is mainly targeted towards libraries that can be depended on, but I now use it for everything and try to find the best fit for each project.

**Comment by bphunter1972** [comment]
Merely being facetious. Thanks for you help.

**Pull request merged**
