### PR TITLE
Update i.json

### PR DESCRIPTION
**Pull request by james2develop**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by james2develop** [comment]
1. Used "branch": "master"

2. Ran the tests ...success

**Comment by math2001** [comment]
> Used "branch": "master"

Well, you have to use `"tags": true`...

**Comment by james2develop** [comment]
setting "tags": true ....OK!  thanks..^

**Comment by james2develop** [comment]
Do you have any other questions??

Why can not find the package in the package control??

**Comment by math2001** [comment]
This pr needs to be merged to be available in Package Control

**Comment by james2develop** [comment]
How to do it??

I do not have permission to merge.

**Comment by james2develop** [comment]
How to do it??

I do not have permission to merge.

**Comment by FichteFoll** [comment]
## Report for Ionic1-Snippets #########################

### Repository checks ###

Reporting 1 failures:
- No semantic version tags found (no tags found at all)

No warnings

### Package checks ###

No failures

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

How does this differ from the other ionic snippets packages? https://packagecontrol.io/search/ionic

**Comment by james2develop** [comment]
Repository checks

Reporting 1 failures:

No semantic version tags found (no tags found at all)


--->   Has increased  semantic version tags .

**Comment by FichteFoll** [comment]
>How does this differ from the other ionic snippets packages? https://packagecontrol.io/search/ionic

**Comment by FichteFoll** [comment]
@james2develop ping

**Pull request closed without merging**
