### PR TITLE
Add Business Catalyst Liquid Snippets

### PR DESCRIPTION
**Pull request by PhilMarcuson**
I've added my package to the b.json repository file. Let me know if there is anything else I need to do please. 

Thank you,

Phil Marcuson

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) tag (with optional leading `v`) to your repo.

**Comment by PhilMarcuson** [comment]
I’m sorry about that.  Took me a little bit to figure this out, but I’m pretty sure I have it now.

Could you include a link to this along with the semantic versioning link for your documentation page:  https://help.github.com/articles/creating-releases/

Regards.

Phil Marcuson

**Comment by FichteFoll** [comment]
I'll link to http://git-scm.com/book/en/v2/Git-Basics-Tagging in the future.

**Comment by PhilMarcuson** [comment]
Maybe both?  I found that article too, but since I’m not using the shell environment to push commits that doesn’t apply.  I commit with the Github Desktop UI and then I created the release on github.com under the releases area.  Just two different approaches with the same result.  ☺

**Comment by PhilMarcuson** [comment]
So cool!  Thank you!

**Pull request merged**
