### PR TITLE
Added codeigniter 4 snippets support

### PR DESCRIPTION
**Pull request by mpmont**

### CODE REVIEW

**Comment by mpmont** [comment]
Hi there, from what I understand this gave an error because of my package name. But I can't find a package with the same name. Can this be from a old pull request I had with the same name?

**Comment by FichteFoll** [comment]
> Hi there, from what I understand this gave an error because of my package name. 

No, there was and still is an error because you didn't insert your package in the right location. [It should be here](https://travis-ci.org/wbond/package_control_channel/builds/657966445#L400). Please don't create a new PR when addressing this and instead push new commits to your master branch (which you inconveniently opened this PR from).

**Comment by mpmont** [comment]
Hi there, thank you for you feedback. Sorry for that second pull request. I think everything is good now.

**Comment by FichteFoll** [comment]
Note that you'll have to push a new tag with a higher version in order to make a new release. PC won't check your `master` branch.

**Comment by mpmont** [comment]
@FichteFoll So every time there's a new version I need to create the new tag and create a new pull request with the respective tag right?

**Comment by mpmont** [comment]
Oh got it I just need to make the new tag in my repo and the package will get the latest one. ok.

**Comment by FichteFoll** [comment]
Correct, you create a new tag for your repo and PC will detect the new version within a an hour Usually.

**Pull request merged**
