### PR TITLE
add: sublime-open-require

### PR DESCRIPTION
**Pull request by nswbmw**
repository: [sublime-open-require](https://github.com/nswbmw/sublime-open-require)
tag: [v1.0.0](https://github.com/nswbmw/sublime-open-require/releases/tag/v1.0.0)

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/Open%20URL does this already.

**Comment by nswbmw** [comment]
sublime-open-require is different with open-url, sublime-open-require can open a package's main file that open-url cannot.

**Comment by FichteFoll** [comment]
Can you provide an example please?

**Comment by nswbmw** [comment]
In my app.js:

```
var koa = require('koa');
```

when use sublime-open-require, alt + double-click will open `node_module/koa/lib/application.js` that `node_module/koa/package.json` specified `main` field. But open-url will open google then search `koa`.

**Comment by FichteFoll** [comment]
## Report for sublime-open-require ####################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 1 failures:
- The binding ['ctrl+u'] unconditionally overrides a default binding
    File: Default.sublime-keymap

Reporting 1 warnings:
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default.sublime-mousemap

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by FichteFoll** [comment]
@nswbmw ping

**Pull request closed without merging**
