### PR TITLE
Add Compass Navigator

### PR DESCRIPTION
**Pull request by kapitanluffy**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is [Compass Navigator](https://github.com/kapitanluffy/sublime-compass)

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by jwortmann** [comment]
The kind icons for the different sheet types in the quick panel should not be defined as "function", "variable", "keyword", etc., because sheets are semantically completely unrelated to those predefined kinds.

Take a look how e.g. LSP does it to use the desired colors:
https://github.com/sublimelsp/LSP/blob/b7e32635ac9fefe985b9a76a6d2991153a42c54a/plugin/core/views.py#L106-L113

Or the CommandsBrowser package:
https://github.com/Sublime-Instincts/CommandsBrowser/blob/16ef299085854d1f4b61aaf8280c23c3f98a43a5/src/utils/miscellaneous_utils.py#L18-L28

**Comment by kapitanluffy** [comment]
> The kind icons for the different sheet types in the quick panel should not be defined as "function", "variable", "keyword", etc., because sheets are semantically completely unrelated to those predefined kinds.
> 
> Take a look how e.g. LSP does it to use the desired colors: https://github.com/sublimelsp/LSP/blob/b7e32635ac9fefe985b9a76a6d2991153a42c54a/plugin/core/views.py#L106-L113
> 
> Or the CommandsBrowser package: https://github.com/Sublime-Instincts/CommandsBrowser/blob/16ef299085854d1f4b61aaf8280c23c3f98a43a5/src/utils/miscellaneous_utils.py#L18-L28

Thank you! Updated it. 

Curious though, where are the last two values of the tuple used? I see that you can also make them empty.

**Comment by jwortmann** [comment]
> Curious though, where are the last two values of the tuple used? I see that you can also make them empty.

https://www.sublimetext.com/docs/completions.html#kind-info

The letter is shown as the icon and the third value of the tuple is shown in the tooltip when you hover with the mouse over the icon. And I think in case of autocompletion it's also shown in the details pane at the bottom of the popup when that is visible.

Btw, the reason of my suggestion from above is that the predefined (non-color) IDs like KIND_ID_FUNCTION will result in special attributes being set on the theme class rule. For example I use a little "trick" in my own theme to make the kind letter transparent for the predefined kinds, and instead show a special icon in that case.

kind_icons

But of course the icons wouldn't make sense anymore if the kind IDs are used by plugins for unrelated things, like in this example for the different sheet types. (But for the "colorish" kind IDs it will be rendered with the letter still visible, like in the default themes.)

**Comment by kapitanluffy** [comment]
> I use a little "trick" in my own theme to make the kind letter transparent for the predefined kinds, and instead show a special icon in that case.

Whoa! So, I can show icons instead of letters? Can you share that? I think icons would be a more suitable visual guide.

**Comment by braver** [comment]
Pretty awesome package, made even more awesome by the interaction here. 

Your keymap still has two entries for debugging purposes. I doubt a general user of the package would be able to memorize the bindings for those, might as well disable those two and instead add them to the command palette.

You're still missing main menu entries for your settings and key bindings. You might add those debugging commands there as well. 

Personally I would suggest reducing the install message a bit. You already "sold" it to the user: they installed it. If that message has lots of info, people won't read it (as far as users ever read anything...). I would suggest focussing on the fact that the package really is better with keybindings and help users set that up. Also, the version history there is not super relevant for first-time installation. 

Other than those details though, very nicely done 👌🏻

**Comment by kapitanluffy** [comment]
> Pretty awesome package, made even more awesome by the interaction here.
> 
> Your keymap still has two entries for debugging purposes. I doubt a general user of the package would be able to memorize the bindings for those, might as well disable those two and instead add them to the command palette.
> 
> You're still missing main menu entries for your settings and key bindings. You might add those debugging commands there as well.
> 
> Personally I would suggest reducing the install message a bit. You already "sold" it to the user: they installed it. If that message has lots of info, people won't read it (as far as users ever read anything...). I would suggest focussing on the fact that the package really is better with keybindings and help users set that up. Also, the version history there is not super relevant for first-time installation.
> 
> Other than those details though, very nicely done 👌🏻

Thank you. I'll work on it later and let you know.

**Comment by kapitanluffy** [comment]
@braver created a [new release](https://github.com/kapitanluffy/sublime-compass/releases/tag/2.1.1)

**Comment by braver** [comment]
Thanks! 

Final remark: for existing menu entries please only provide the id ("package_settings") not the mnemonic or the label: you're otherwise effectively overriding those.

**Comment by kapitanluffy** [comment]
> Thanks!
> 
> Final remark: for existing menu entries please only provide the id ("package_settings") not the mnemonic or the label: you're otherwise effectively overriding those.

Ah, PackageDev added that. I did not notice. Made a re-release 😅

**Pull request merged**
