### PR TITLE
Add BetterFindNext Package

### PR DESCRIPTION
**Pull request by notbaab**
[Repo](https://github.com/notbaab/BetterFindNext)
[Tag](https://github.com/notbaab/BetterFindNext/releases/tag/1.0.0)

Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by notbaab** [comment]
Rebound to unused binding with [this](https://github.com/notbaab/BetterFindNext/releases/tag/v1.0.1) release.

Actually ran it against st_package_reviewer this time.

**Comment by notbaab** [comment]
Does it need to pass with no warnings? 

Also, I'm trying to provide similar functionality to the find_next (ctrl+d) command, so having escape clear the added regions makes sense, like so. 

add_next

**Comment by AlexKvazos** [comment]
Yeah, you can't override default keybindings as people don't find that cool. Try with a third modifier key or two-step (prefix) key.

**Comment by AlexKvazos** [comment]
Actually, now that I see it is "escape", I think it is no problem, let me pass this to someone else though.

cc @wbond @keith-hall

**Comment by keith-hall** [comment]
I suspect it is fine, as it has a specific context - user feedback will dictate whether closing autocomplete popups etc. should take precedence over the clearing find regions or not :)

**Comment by AlexKvazos** [comment]
Alright then!

**Comment by r-stein** [comment]
Maybe worth to say, that you can just give it a lower precedence by taking the context in the default keybindings and inverting them:

```js
    {
        "keys": ["escape"], "command": "clear_better_find_selection", "context":
        [
            { "key": "has_next_field", "operator": "not_equal", "operand": true },
            { "key": "has_prev_field", "operator": "not_equal", "operand": true },
            { "key": "panel_visible", "operator": "not_equal", "operand": true },
            { "key": "overlay_visible", "operator": "not_equal", "operand": true },
            { "key": "popup_visible", "operator": "not_equal", "operand": true },
            { "key": "auto_complete_visible", "operator": "not_equal", "operand": true },
            { "key": "has_region", "operand": "find_region" }
        ]
    },
```

**Comment by notbaab** [comment]
That is a great suggestion, done! 

This might be covered in the documentation in which case I apologize but does the auto tester test every release? Or intermittently to make sure developers haven't violated the rules?

**Comment by r-stein** [comment]
The auto reviewer is only to help the reviewers before merging the package to package control and won't be executed afterwards.
However you can manually download and execute it: https://pypi.python.org/pypi/st-package-reviewer

**Comment by notbaab** [comment]
Awesome, thanks!

**Pull request merged**
