### PR TITLE
added tomorrow night italics color scheme

### PR DESCRIPTION
**Pull request by kennethreitz**
:sparkles: :cake: :sparkles:

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by wbond** [comment]
@kennethreitz We use a standard versioning scheme so that we can derive some meaning from versions and thus allow users to opt-in to pre-release versions, and hopefully in the future prompt users for major breaking changes in a package.

Since we use git tags, hopefully it shouldn't really be too much work to just create a new tag whenever changes are ready for users to consume.

**Comment by FichteFoll** [comment]
@kennethreitz ping

**Pull request closed without merging**
