### PR TITLE
feat: lsp-vtsls

### PR DESCRIPTION
**Pull request by gxanshu**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

My package is similar to [LSP-typescript](https://github.com/sublimelsp/LSP-typescript) However it should still be added because it uses [vtsls](https://github.com/yioneko/vtsls) as its internal language server. which is extracted from VSCode and provide same performance and features.

Main goal of this package is to enhance language server support of  TypeScript for Sublime Text users  

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by rchl** [comment]
- The convention is to add LSP packages in https://github.com/sublimelsp/repository.
- The package should be called `LSP-vtsls` for consistency
- The package should ideally live in the sublimelsp org (https://github.com/sublimelsp/). I can help arranging the transfer and proper review

**Comment by gxanshu** [comment]
@rchl sure please

**Comment by braver** [comment]
yeah, @gxanshu please create a PR over here: https://github.com/sublimelsp/repository/pulls

**Comment by rchl** [comment]
I've created https://github.com/sublimelsp/LSP-vtsls. Can you create a PR there with your changes?

**Comment by gxanshu** [comment]
thanks a lot @rchl & @braver 

will create PR soon

**Comment by gxanshu** [comment]
@rchl please add something in https://github.com/sublimelsp/LSP-vtsls i'm unable to fork & create PR

**Comment by rchl** [comment]
Done

**Pull request closed without merging**
