### PR TITLE
Add Halcyon Theme

### PR DESCRIPTION
**Pull request by bchiang7**
This is a theme & color scheme based on the popular Ayu Mirage theme, but with more contrast and
more attention to detail. A [VS Code Version](https://marketplace.visualstudio.com/items?itemName=brittanychiang.halcyon-vscode) of this is theme is also published on VS Code Marketplace. Thank you for taking the time to review this!

### CODE REVIEW

**Comment by jrappen** [comment]
Why not use the new `sublime-color-scheme` format based on JSON?

---

For examples, do the following in `Build 3149` or later:

* Tools > Command palette > `View package file` > `sublime-color-scheme`

**Comment by bchiang7** [comment]
I'm currently am only on `Build 3143` since I don't have a license. Once the features from build 3149 go into production, I'll definitely check out the new JSON theme format. Is it necessary for this PR?

**Comment by FichteFoll** [comment]
No, this was just a hint from @jrappen about the new format. In order to support older builds (including the latest stable release), you still need to provide a `.tmTheme` file.

**Comment by jrappen** [comment]
@bchiang7 just a heads-up: You can now use [PackageDev](https://github.com/sublimetext/PackageDev) to convert the color scheme(s) to the **new** [color scheme format for ST3149+](https://www.sublimetext.com/docs/3/color_schemes.html)

**Pull request merged**
