### PR TITLE
Add JEB Script Development Helper

### PR DESCRIPTION
**Pull request by nfalliere**

### CODE REVIEW

**Comment by Thom1729** [comment]
```py
verbose = False  # set to True when developing/debugging
```
This should probably be a setting.

```py
os.path.dirname(os.path.realpath(__file__))
```

This won't work if the package is installed. Instead, use `sublime.load_resource('JEB Script Development Helper/jeb-api.txt')`. To allow the user to override this file, you can first check `User/JEB Script Development Helper/jeb-api.txt`, and when you update the API docs, you can save the new file at that location (i.e. `os.path.join(sublime.packages_path(), 'User', 'JEB Script Development Helper', 'jeb-api.txt')`).

**Comment by nfalliere** [comment]
Thank you for your feedback @Thom1729. Both comments were addressed, I pushed the changes to the main repository and tagged the branch 1.0.1 (https://github.com/pnfsoftware/jeb_scriptdev_helper/tree/1.0.1)

**Comment by Thom1729** [comment]
> verbose = os.environ.get('JEB_SUBLIME_VERBOSE') == '1'

I meant a Sublime setting. You can create package-specific settings by adding a package file called (e.g.) `JEB Script Development Helper.sublime-settings` with the following contents:

```json
{
    "verbose": true
}
```

Then, you can access the setting with `sublime.load_settings('JEB Script Development Helper.sublime-settings').get('verbose')`. The user can override this setting by creating their own settings file in the User directory.

**Comment by nfalliere** [comment]
> I meant a Sublime setting. You can create package-specific settings by adding a package file called (e.g.) `JEB Script Development Helper.sublime-settings`

Thanks - fixed. Also, I left the sublime-settings file under source control. Is that the general recommendation or should those files be .gitignore'd?

On master/ branch, will wait for your final approval before tagging 1.0.2.

**Comment by Thom1729** [comment]
That's correct — the .sublime-settings file in the package will serve as the defaults.

**Comment by Thom1729** [comment]
Can merge as soon as 1.0.2 is out.

**Comment by nfalliere** [comment]
Tagged: https://github.com/pnfsoftware/jeb_scriptdev_helper/tree/1.0.2 - Thanks.

**Pull request merged**
