### PR TITLE
add ImageCMS.tpl

### PR DESCRIPTION
**Pull request by ROBsoer**
add ImageCMS.tpl syntax plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
You must not use dots in package names (older packages may still have this however). Just use "ImageCMS".

[Semantic versions](http://semver.org) consist of exactly three numeric parts and there must not be a dot after the `v`.

**Comment by ROBsoer** [comment]
changed plugin name

**Comment by FichteFoll** [comment]
Please also address the last section of my earlier comment.

**Comment by ROBsoer** [comment]
have updated relise version

**Comment by FichteFoll** [comment]
I don't see anything having changed here: https://github.com/ROBsoer/sublime-imagecms.tpl/tags

**Comment by FichteFoll** [comment]
@ROBsoer ping

**Pull request closed without merging**
