### PR TITLE
A new color Scheme

### PR DESCRIPTION
**Pull request by mramzn**
Please provide the following information:

 - Link to your code repository: https://github.com/ramazan360/new-monokai
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/ramazan360/new-monokai/releases/tag/v1.0

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by ramazan360** [comment]
Why the build is not passing on Travis CI?

**Comment by math2001** [comment]
Might because you added a non-needed line (look at the difference).

**Comment by ramazan360** [comment]
Thanks. There was an accidental newline that was causing the error.

**Comment by FichteFoll** [comment]
## Report for new-monokai #############################

### Repository checks ###

Reporting 1 failures:
- No semantic version tags found (semantic versions consist of exactly three numeric parts)

No warnings

### Package checks ###

No failures

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

This color scheme doesn't seem to relate to Monokai a lot (it looks very different, as far as I can tell). Don't you think it would be better to use your own name rather than competing with [these other packages](https://packagecontrol.io/search/monokai)?

**Comment by FichteFoll** [comment]
Closing in favor of https://github.com/wbond/package_control_channel/pull/6228.

**Pull request closed without merging**
