### PR TITLE
Add Cucumber Snippets e Highlight em Inglês

### PR DESCRIPTION
**Pull request by RobertoPegoraro**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

_Please follow PR template next time_

**Comment by wbond** [comment]
@RobertoPegoraro Can you remove the cache file that was highlighted in the review above?

**Comment by RobertoPegoraro** [comment]
File removed

**Comment by wbond** [comment]
I think you forgot to create a new tag after removing the file

**Comment by FichteFoll** [comment]
Are you sure about this package having a non-English name despite explicitly using the english language?

**Comment by FichteFoll** [comment]
@RobertoPegoraro ping; you haven't pushed to this repo since April.

**Comment by RobertoPegoraro** [comment]
Created new tag, sorry for my mistake.

**Comment by FichteFoll** [comment]
Please restrict installation to versions 3092 and above.

**Pull request merged**
