### PR TITLE
Add AutoIt Plys

### PR DESCRIPTION
**Pull request by NSUSpray**
**[AutoIt Plys](https://github.com/NSUSpray/AutoItPlysSublime)** it‘s fork of https://github.com/AutoIt/SublimeAutoItScript (https://github.com/Codehimn/AutoItScript) – package for support [AutoIt language](https://www.autoitscript.com/site/autoit/) which is not supported for a long time. My package fixes a lot of bad decisions of the original package. In massive addition, my package adds support for a third-party *Plys dialect* of the AutoIt language, which will definitely not be supported by the developers of the original package.

### CODE REVIEW

**Comment by braver** [comment]
Shouldn't this replace the old package then?
Please reread the [docs](https://raw.githubusercontent.com/wbond/package_control/master/example-repository.json), you probably don't need all that information in the JSON.

**Comment by NSUSpray** [comment]
Thank you for feedback!

> ### Automated testing result: ERROR
> ```
>   - ERROR: Invalid JSON (with comments)
>     - File: Completions/DirectivesAndOptions.sublime-completions
>     - Exception: Invalid control character at: line 51 column 86 (char 3269)
> ```

As I understand it, the message is referring to the *tab character*. There are no such moments in the new version anymore. The repository has been updated.

> ```
>   - WARNING: '.no-sublime-package' is defined. Please verify that it is *really* necessary
>   - WARNING: '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
>     - File: AutoIt Plys.sublime-syntax
> ```

*.no-sublime-package* is needed for working of the *Include_Helper.au3* script. Perhaps I will add '.tmLanguage' fallback file to the new version of the package. So far, I've specified version 3092.

> Shouldn't this replace the old package then?

This is a good question. First, this is my first Sublime Text package. It is a big responsibility to become a replacement for the official AutoIt package, although official package is very primitive and has not been supported for a long time. But now I have probably understood the intricacies enough and am ready to make such a decision. Secondly, my package have a massive add-on which not all AutoIt users need. Do I need to make this decision before accepting my pull request, or can I do it after?

> Please reread the [docs](https://raw.githubusercontent.com/wbond/package_control/master/example-repository.json), you probably don't need all that information in the JSON.

You’re right. I have read this document more carefully. I have removed unnecessary information from JSON.

**Comment by NSUSpray** [comment]
Thank you for feedback!

> ### Automated testing result: ERROR
> ```
>   - ERROR: Invalid JSON (with comments)
>     - File: Completions/DirectivesAndOptions.sublime-completions
>     - Exception: Invalid control character at: line 51 column 86 (char 3269)
> ```

As I understand it, the message is referring to the *tab character*. There are no such moments in the new version anymore. The repository has been updated.

> ```
>   - WARNING: '.no-sublime-package' is defined. Please verify that it is *really* necessary
>   - WARNING: '.sublime-syntax' support has been added in build 3092 and there is no '.tmLanguage' fallback file
>     - File: AutoIt Plys.sublime-syntax
> ```

*.no-sublime-package* is needed for working of the *Include_Helper.au3* script. Perhaps I will add '.tmLanguage' fallback file to the new version of the package. So far, I've specified version 3092.

> Shouldn't this replace the old package then?

This is a good question. First, this is my first Sublime Text package. It is a big responsibility to become a replacement for the official AutoIt package, although official package is very primitive and has not been supported for a long time. But now I have probably understood the intricacies enough and am ready to make such a decision. Secondly, my package have a massive add-on that not all AutoIt users need. Do I need to make this decision before accepting my pull request, or can I do it after?

> Please reread the [docs](https://raw.githubusercontent.com/wbond/package_control/master/example-repository.json), you probably don't need all that information in the JSON.

You’re right. I have read this document more carefully. I have removed unnecessary information from JSON.

**Comment by braver** [comment]
>.no-sublime-package is needed for working of the Include_Helper.au3 script.  

👍🏻 

> Perhaps I will add '.tmLanguage' fallback file to the new version of the package. So far, I've specified version 3092.

Also fine, we don't really care about support for < 3092.

One last thing I noticed you ship keybindings only for Windows. Do you really really need a keybinding at all?

**Comment by NSUSpray** [comment]
> One last thing I noticed you ship keybindings only for Windows. Do you really really need a keybinding at all?

Hello, **[braver](https://github.com/braver)**! Thanks for this remark. I have rethought the purpose of “Key Bindings” section in the README, it is now titled “Features”, and the key bindings are now additional information. I also indicated which bindings work only on Windows and which on all platforms (⌘ instead of Ctrl on macOS).

**Comment by braver** [comment]
> Do I need to make this decision before accepting my pull request, or can I do it after?

Sure, we always replace the old package later. Or not.

**Pull request merged**
