### PR TITLE
Add Explain PostgreSQL

### PR DESCRIPTION
**Pull request by MGorkov**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is **Explain PostgreSQL** https://github.com/MGorkov/explain-postgresql-sublime

There are no packages like it in Package Control.

It adds context menu entries, but only in sql context and their visibility is conditional.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by MGorkov** [comment]
@braver Thanks for you comments!
Could you tell how the context menu items can be switched off ?
Plugin commands have the is_visible() so they show in context menu only if syntax is sql.

**Comment by braver** [comment]
Sure! In the class that defines your command, you can implement an is_visible method. In that method you can check a setting, or the current scope, etc. If you want to apply a setting only to the context menu entry, you need that to be a separate command (a different class), so you can implement the is_visible method specifically for this case. But you can of course call the same command implementation.

Hope that answers your question!

**Comment by MGorkov** [comment]
@braver Thanks for you answer
This already has been implemented - all commands in the plugin have is_visible method that checks current scope.
So, the PR can be merged?

**Comment by braver** [comment]
All set 👍🏻

**Pull request merged**
