### PR TITLE
Update t.json

### PR DESCRIPTION
**Pull request by russianidiot**
+touch

### CODE REVIEW

**Comment by FichteFoll** [comment]
Since `os.utime` does not work on directories on Windows, this package won't have any use on Windows. Please restrict installation to the other platforms.

**Comment by FichteFoll** [comment]
You still need to change `"branch": "master"` to `"tags": true`.

**Comment by FichteFoll** [comment]
@russianidiot ping

**Comment by russianidiot** [comment]
ready. check https://github.com/russianidiot/Sublime-touch

**Comment by russianidiot** [comment]
https://github.com/wbond/package_control_channel/pull/5597

**Pull request closed without merging**
