### PR TITLE
A collection of dark Color Schemes by a professional senior Graphic and Web Designer

### PR DESCRIPTION
**Pull request by draganmilenkovic**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.

My package is a collection of color schemes.

There are no packages like it in Package Control. If we remove the obvious similarity which ALL dark themes have (being dark), my collection of color schemes has original colors picked by my 15 years of experience in Graphic Design and Coding. This was done after testing a very large amount of dark themes from Package Control and none are similar.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Please tag a release using semver numbering, we can't ship your package without tags.

Also, if you're targeting Sublime Text, you'd do well to convert your tmTheme files to the newer sublime-color-scheme format. They're much easier to maintain and edit. A convertor is built into Sublime Text.

**Comment by draganmilenkovic** [comment]
@braver Hi. I tagged it and converted tmTheme files to sublime-color-scheme format.

**Comment by braver** [comment]
Thanks!

**Comment by draganmilenkovic** [comment]
@braver Awesome! Thanks.

**Comment by draganmilenkovic** [comment]
@braver Do you know why the images from the readme are not loading on packagecontrol.io ? Thanks.

**Comment by braver** [comment]
Nope, sorry, not familiar with the inner workings of that.

**Pull request merged**
