### PR TITLE
Added Theme - Numix Light

### PR DESCRIPTION
**Pull request by ikenfin**

### CODE REVIEW

**Comment by FichteFoll** [comment]
In your readme you mention the package name `Theme - Numix Light` but in this pull request it is `Numix Light Theme`. I suggest you stick with the former since that is the generally accepted conevention of naming themes (and similarly color schemes).

You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by ikenfin** [comment]
Fixed it @FichteFoll

**Comment by FichteFoll** [comment]
FYI, your currently highest tag (1.0.0) does not point to the latest commit and still contains the color scheme.

**Comment by ikenfin** [comment]
Yes, i have updated tag just now. Thanks!

**Pull request merged**
