### PR TITLE
Update s.json

### PR DESCRIPTION
**Pull request by ggstec**

### CODE REVIEW

**Review by ggstec — COMMENTED** [review]
Created LICENSE

**Comment by rchl** [comment]
- You can re-request review from the bot yourself
- The readme says "A web browser page reloading plugin for the Sublime Text 3 editor." which is not really the case.

**Comment by ggstec** [comment]
Modified Readme.md

**Comment by braver** [comment]
Can you explain what your package does and how it provides something that doesn't already exist by default or in other packages? I really don't get from the readme what it does (maybe it needs a gif...) and that might also mean that it makes it hard for others to find your package and see how it solves a problem they might be having.

**Comment by braver** [comment]
Please respond to the feedback to continue the review.

**Pull request closed without merging**
