### PR TITLE
Add "TestCafe Test Runner" plugin

### PR DESCRIPTION
**Pull request by churkin**
Please provide the following information:

 - Link to your code repository: https://github.com/churkin/testcafe-sublimetext
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by math2001** [comment]
- The tests didn't pass. Please make sure that they do. (it might be because you need to alphabetically sort the list of package)
- You need to create at least one tag

**Comment by churkin** [comment]
@math2001 I've added 0.1.0 tag for my repo

**Comment by FichteFoll** [comment]
Your package will not work properly in ST3 because you are trying to write to a folder that does not exist. Package Control installs packages as `.sublime-package` zip archives, which means `__file__` will likely point to something you don't expect, and more specifically the package folder isn't created on installation.

You can either explicitly tell PC to unextract your package by adding a `.no-sublime-package` file (and prevent users from being able to override files of your package) or try to add workarounds that work even when the package is archived (the package name is in `__package__`; you can create the Packages folder if it does not exist).

Also, you should use `os.path.join` instead of hardcoding back- or forwardslashes for joining paths.

**Comment by churkin** [comment]
@FichteFoll Thanks a lot!
I've fixed your remarks: https://github.com/churkin/testcafe-sublimetext/commit/1ceab8cfbc05cd116866f1e3feb4b01585bccf9f

**Pull request merged**
