### PR TITLE
add LiveReload

### PR DESCRIPTION
**Pull request by alepez**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

You can remove `package.json`, that file won't be looked at.

It appears that the repo you forked this from has two commits that completely destroy features like git blame and are generally unreviewable in the current state, because one removes all files and the other adds them again - with changes. It's in your judgement whether you want to fix that however (squash/cherry-pick and force-push).

**Comment by FichteFoll** [comment]
@alepez ping

**Comment by alepez** [comment]
Sorry for the long delay, I've applied your requests, but I don't know why github is now saying "alepez  wants to merge 16 commits into wbond:master".

**Comment by FichteFoll** [comment]
Yeah, I can't merge that. It's most likely due to your merge commit.

With pull requests it's usually best to rebase insetad of merge and fix possible conflicts on-the-go.

**Comment by alepez** [comment]
Ok, so I just close this pull request, delete my `package_control_channel` fork and create a new fork.

**Pull request closed without merging**
