### PR TITLE
Added Rust44 to 0-9.json

### PR DESCRIPTION
**Pull request by qwertyonepilots**

### CODE REVIEW

**Comment by saadq** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid semantic version tags to your repo. As mentioned in the docs, branch-based releases are no longer accepted for new packages.

**Comment by qwertyonepilots** [comment]
Done :)

**Comment by qwertyonepilots** [comment]
Is this never going to be merged? Is package control dead? @saadq @wbond

**Comment by FichteFoll** [comment]
Due to lack of time I mostly review packages on mondays. That means you may have to wait up to seven days until a package is reviewed, and then possibly more until feedback has been addressed and reviewed.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by kylebebak** [comment]
@qwertyonepilots 

If you look at <https://github.com/qwertyonepilots/44Rust/releases>, you'll see the repo for your plugin doesn't have any releases.

To create a release, you need to push a tag to your repo. Because this is your first release, the tag `1.0.0` could be appropriate.

```sh
git tag 1.0.0 -m "First release"
git push --tags origin master
```

**Comment by wbond** [comment]
There are still no tags in the repo, so merging this won't do anything @qwertyonepilots.

**Pull request closed without merging**
