### PR TITLE
added One Dark Color Scheme

### PR DESCRIPTION
**Pull request by IceTimux**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You need to push a [semantic version](http://semver.org) tag.

**Comment by IceTimux** [comment]
semantic version tag added.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts. (I don't know how you can not see this when you follow the link.)

**Comment by IceTimux** [comment]
whoa my mistake, sorry. I've fixed it now.

**Pull request merged**
