### PR TITLE
Added iron router snippets to repository/i.json

### PR DESCRIPTION
**Pull request by Ogamedia**
This a meteor snippet

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
Also, how about adding this snippet to https://packagecontrol.io/packages/Meteor%20Snippets ?

**Comment by Ogamedia** [comment]
Added the version number to be file

**Comment by Ogamedia** [comment]
@FichteFoll What file should I put the version information in ?

**Comment by FichteFoll** [comment]
You need to use git to create and push a tag to your repo, so that it shows up at https://github.com/Ogamedia/Router/tags

**Comment by Ogamedia** [comment]
@FichteFoll Done.
Thanks very much.  I have learnt a lot today. :+1:

**Comment by FichteFoll** [comment]
Almost. Semantic versions have exactly three numeric parts.

**Comment by Ogamedia** [comment]
Added last numeric part. 
And  I appreciate version better now after going through the [semver](http://semver.org/) doc
Thanks for the time @FichteFoll

**Pull request merged**
