### PR TITLE
CodeTerminal

### PR DESCRIPTION
**Pull request by victoreduardobarreto**

### CODE REVIEW

**Comment by math2001** [comment]
This label isn't really good (you're the first to use it)

```
"labels": ["Terminal Console Command"],
```

Maybe:
```
"labels": ["terminal", "console", "command line"]

**Comment by math2001** [comment]
why did you close this issue?

**Comment by victoreduardobarreto** [comment]
Sorry, I don't know use the github very well.

I changed the tags how you explained, but I did this wrong, then not passed in the test. 
after close the pullrequest, I saw  that I was code the tags wrong.

**Comment by math2001** [comment]
Don't worry, I'm like you. Reopen this pull request, we'll continue on this one.

The pass don't pass because the json is invalid. You need to put a comma between the labels:

```diff
-"labels": ["terminal" "console" "command line"],
+"labels": ["terminal", "console", "command line"],
```

you see the difference? Note that you can do these tests locally. Have a look [here](https://packagecontrol.io/docs/submitting_a_package#Step_7)

All the tests must pass. Once this is done, just push your changes, GitHub's clever, it'll detect them and check them (do the same tests that you did locally).

**Pull request closed without merging**
