### PR TITLE
Update d.json

### PR DESCRIPTION
**Pull request by mikasuon**
A Sublime Text 3.X Plugin to handle Microsoft Dynamics 365 Web Resources.

### CODE REVIEW

**Comment by dvhh** [comment]
@mikasuon  change your release tag from `v1.0.2` to `1.0.2`

**Comment by mikasuon** [comment]
Hello,

 

Done!

 

/ Mika S

**Comment by Thom1729** [comment]
Is the `adal` module built-in on Windows?

**Comment by mikasuon** [comment]
Hello,

 

No, it’s not.

 

The files in  <https://github.com/AzureAD/azure-activedirectory-library-for-python/tree/dev/adal> https://github.com/AzureAD/azure-activedirectory-library-for-python/tree/dev/adal should be copied to [Sublime Text]\Lib\pythonX\adal\ folder.

 

That’s a little impractical, could be better to include them in the project, but I’m not sure if I’m allowed to include those in my project.

 

Br,

Mika Suonvieri

**Comment by Thom1729** [comment]
It looks like the code is MIT-licensed, which means that you're allowed to redistribute them as long as you include the license. The simplest way to do this would be to have an `adal` directory in the package and use relative imports. You could also create a [dependency](https://packagecontrol.io/docs/dependencies), which would allow other packages to use `adal`.

**Comment by Thom1729** [comment]
@mikasuon ping

**Pull request closed without merging**
