### PR TITLE
add CodeComplice

### PR DESCRIPTION
**Pull request by spectacles**
CodeComplice is targeted at (and has already) heating up development of better CodeIntel for SublimeText

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can make use of the new 3.0.0 feature of providing a string to the `"tags"` key with a prefix which will then only match semantic version tags with that prefix. Refer to https://github.com/wbond/package_control/blob/master/example-repository.json

Anyway, how exactly is this different from the original CodeIntel package?

**Comment by wizza-smile** [comment]
It differs in ambition and support.
It has provided a lot of Enhancements and new features and people who tried it were very pleased by it.
I would very much like to provide the users with a convenient way of updating!

**Comment by FichteFoll** [comment]
>It differs in ambition and support.

This is too vague for me.

Why is working on the initial CodeIntel package not an option? Do you think you will make to many updates to bother @Kronuz? Have you considered a pull request at all?

I'm just curious here as I see wasted potential with developing a fork of something still maintained, unless the goals are too different.

**Comment by wizza-smile** [comment]
I did do all of that. I am not pleases with the outcome of contributing to the project. SublimeCodeIntel has been dead since October 2013, seeing no progress. That is the consequence of no competition in my view. Kronuz wrote a wrapper file for an open source project (Komodo) and he stopped working on it as it met his personal needs. 
After not reacting to issues, questions or pull requests for at least 18 months, Kronuz immediately reappeared, when I adverted my project on various issues, as it offered what people had been asking for.
I shoveled my code (the work of months) into his codebase somehow in less then 5 hours and instantly released a new version. That was all fine with me. He took an open-source project and worked on that basis, so did I, its open-source, anybody is free to do what he desires. But he didn't bother to read and understand my code. He broke the application for many of his users and is unable to fix it. 
My code on the other hand is working and I understand it also.

My project is the single source of progress for SublimeCodeIntel since 2013.
I feel that I deserve a chance to offer my work to people directly, without somebody messing with the code and not mentioning the source of progress.

**Comment by Kronuz** [comment]
"Not mentioning the source of progress"? Credit where credit is due: git commit logs and messages since first version, and https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/messages/2.1.0.txt

Long story short, I **merely** wrote a "wrapper file" and then ripped-off wizza-smile's *work of months* worth of *Enhancements* and new features and then shoved it all into "my" codebase to release a "broken version", which of course couldn't possibly ever happen to wizza-smile because he does **understand** every bit of the code. Did I get that right?

@wizza-smile, you have some major rage going on! Chill out dude!! Enough of your offensive comments all over! I'm not here to make your life a living hell, and nor SublimeCodeIntel is "my" code or "my" project to fit "my" personal needs; it's the community's project. I just happen to have started it for Sublime Text and shared to the world with two hopes: I hoped it'd be useful to others, and I hoped more could have helped me in the endeavor of maintaining it and enhancing it... but of the two things I hoped, I still just haven't gotten as much help, as I got with SublimeLinter.

I have no further comment to make about this.

**Comment by wizza-smile** [comment]
actually, my opinion is, that a little competition is what the project needs.
We have all seen what happens without it. People get lazy. I don't mean to offend anyone!

I know @Kronuz did a great job in 2011 porting Komodo and again in 2013 when he made the basics work on a lot of systems, but it's a port of an existing plugin, so *please* don't behave like a legend. 
If you really want to stop resting on old achievements and help the community once again, get back in the game and teach the people how to compile the binaries. Make it simpler and give support! 
That could spark the community. I believe we can really get independent of Komodo in the future. 

Don't worry I'm completly chilled, we are just playing around here in our free time, take my apology?! ;)

@FichteFoll I would still very much like you to include my package. There is a solid chance that the two projects will reunite in the future!

**Comment by FichteFoll** [comment]
>I feel that I deserve a chance to offer my work to people directly, without somebody messing with the code and not mentioning the source of progress. 

This statement was all I wanted to hear. While I can encourage people to work together on similar or even the same project(s) I can not force them if they don't want to, nor will I hold back a package addition for that reason. It appears you know about the positive and negative aspects enough to come to your own conclusion, which I wil respect. Although it is not desireable, multiple packages for the same solutions *may* exist on the default channel.

**Comment by wizza-smile** [comment]
@FichteFoll Thanx a lot!

**Pull request merged**
