### PR TITLE
Add Adaptify theme

### PR DESCRIPTION
**Pull request by lodev09**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a theme that comes with 2 color schemes. It extends the default _Adaptive_ theme.
There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by deathaxe** [comment]
This theme overrides default Adaptive.sublime-theme with obvious/significant changes. This shouldn't have been merged.

see: https://github.com/lodev09/Adaptify/issues/1

**Comment by braver** [comment]
I thought it was pretty obvious that that’s what it does. Of course any breaking change to Adaptive might break it, but how realistic is that to ever happen, and how much of a problem is that?

**Comment by deathaxe** [comment]
It just disables the use of unmodified original Adaptive theme, once this package is installed. 

It's not obvious it is doing that, probably resulting in bug reports about broken or changed visuals of Adaptive theme at sublimehq tracker. It looked like a color scheme package on the first glance.

The shipped theme adds some broken/duplicate paddings to quick panel items, for instance.

Originial themes/color schemes should just not be augmented that way.

If a package provides a modified theme, it should express it by a dedicated name, which was easily possible via `"extends": "Adaptive.sublime-theme",` key.

**Comment by braver** [comment]
Oh, right, totally. Got it. I was assuming that it did exactly as you describe, by making a new theme available under a new name but under the hood extending the default theme. Didn't look closely enough I guess.

I see that a bug report is already open on the Adaptify repo and I assume the issue can be resolved there. If I can be of any assistance let me know.

**Comment by lodev09** [comment]
I tried the `extends` key and works. However, the default icons are no longer working. It looks like a bug under the hood.. or am I missing something?

**Pull request merged**
