### PR TITLE
added nx sublime coverage plugin

### PR DESCRIPTION
**Pull request by lordnox**

### CODE REVIEW

**Comment by lordnox** [comment]
Sorry, I forgot to add the tag
How do I re-run the packagecontrol-bots automatic test?

**Comment by FichteFoll** [comment]
The remote reviewer fails on this PR for some reason, so I ran it locally:


## Report for NXSublimeCoverage #######################

### Repository checks ###

No failures

No warnings


### Package checks ###

Reporting 3 failures:
- Invalid modifier key 'c'
    File: keymaps/Default (OSX).sublime-keymap
    Binding: {"command": "clear_nx_coverage", "keys": ["super+shift+c+x"]}
- Invalid modifier key 'c'
    File: keymaps/Default (Windows).sublime-keymap
    Binding: {"command": "clear_nx_coverage", "keys": ["super+shift+c+x"]}
- Invalid modifier key 'c'
    File: keymaps/Default (Linux).sublime-keymap
    Binding: {"command": "clear_nx_coverage", "keys": ["super+shift+c+x"]}

Reporting 1 warnings:
- Found multiple command prefixes: Clear, Show. Consider using one single prefix so as to not clutter the command namespace.


For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/py_package_reviewer/wiki

---

The prefix warning is fine because you suffixed your commands.

You are using UNIX-specific paths in a few locations. You should watch out for Windows compatibility (or alternatively declare your package as incompatible for Windows).

**Comment by FichteFoll** [comment]
@lordnox ping

**Comment by lordnox** [comment]
Thank you for coming back to me (and pinging me again)...
I was not sure what to do as I was in a hurry at the time and the wiki link did not work, you might want to take a look at that.

I'll submit an update shortly

**Pull request merged**
