### PR TITLE
add plugin: GoTools EX - GoTools with EXtension

### PR DESCRIPTION
**Pull request by liuhewei**
Integrate Golang tools such as gofmt, goimports, golint, govet, oracle, gorename. Support auto-format, auto-lint, auto-completion, goto definition and other IDE-like features for Golang development.

BTW: It's a fork and extension version of [GoTools](https://github.com/ironcladlou/GoTools) which's no longer maintained.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I suggest taking over the place of the currently unmaintained GoTools package instead of adding it alongside.

cc @ironcladlou

**Comment by liuhewei** [comment]
My original purpose is just making it easier to share with my team members and between my different workspaces (although I can make it through "git clone "). I have omitted several features from GoTools, so I wonder @ironcladlou could accept it :)

I've just noticed that @nuance also had done similar work like mine, and asked for taking over the project: https://github.com/ironcladlou/GoTools/pull/131

For myself, I hope the GoTools project could keep going. It help me a lot :)

**Comment by FichteFoll** [comment]
What are the features you omitted, if you would be so kind? Are they suited to live alongside in the same environment or is this really supposed to be an "alternative"? Just so I can form an opinion on my own.

**Comment by liuhewei** [comment]
As mentioned in my repository: https://github.com/liuhewei/gotools-sublime#features-removed-from-gotools
And also in the discussions: 
https://github.com/ironcladlou/GoTools/issues/121
https://github.com/ironcladlou/GoTools/issues/128

Basically, I use the sublime's original syntax, Golang official sublime-build plugin to replace GoTools' original.

**Comment by FichteFoll** [comment]
All right, I'm adding this to the channel. The differences are big enough to warrant a new package.

**Comment by ironcladlou** [comment]
@liuhewei I really would have preferred you fork with a more distinct name (since I am not yet willing to relinquish ownership of the repo/original project). Thoughts?

**Comment by ironcladlou** [comment]
To be clear, it's not a huge deal to me, just something I wish I had been able to bring up sooner.

**Comment by liuhewei** [comment]
@ironcladlou Of course. Sorry for making you unconfortable with the name, I didn't mean that:) Is "Golang Tools Integrate" OK for you?

@FichteFoll I'm not sure how to change the name of a plugin. Is it possible that I just submit a PR to change it? Sorry for the bothering :)

**Comment by ironcladlou** [comment]
I was thinking something that didn't use the word "GoTools", but like I said, if renaming is too much of a pain at this point then I say leave what's already been done.

**Comment by FichteFoll** [comment]
@liuhewei yes, just change the name of the package and add a `previous_names` array with the old name in it. Remember to update the package's position in the JSON.

**Pull request merged**
