### PR TITLE
Add package: SublimeLinter-contrib-yaml-lint

### PR DESCRIPTION
**Pull request by witsec**
I created a YAML linter which uses the yaml-lint Ruby gem.

### CODE REVIEW

**Comment by witsec** [comment]
Added a 0.1 tag.

**Comment by witsec** [comment]
Messing up here. Some issue on my end. Will open a new PR later on.

**Comment by wbond** [comment]
Just an FYI, new packages aren't allowed to use branch-based releases.

**Comment by witsec** [comment]
Ah, okay, thanks. I'll fix that.

**Pull request closed without merging**
