### PR TITLE
Add SVG to JSX converter to s repo

### PR DESCRIPTION
**Pull request by tylergould**
https://github.com/tylergould/sublime-svg-to-jsx
https://github.com/tylergould/sublime-svg-to-jsx/tags

### CODE REVIEW

**Comment by joshua-golub** [comment]
@tylergould, I am reviewing this package and I think it would be useful to include an example of what your converter will do. For example, what the before (SVG) and after (JSX) will look like. Would you please add this to your README?

**Comment by FichteFoll** [comment]
Please use a less generic command name than `convert`. Remember that all plugins share the same command namespace.

**Comment by tylergould** [comment]
Thanks for the feedback. I will make the updates in the next couple of days.

**Comment by tylergould** [comment]
@FichteFoll and @joshua-golub -- in the latest version, I've updated the README with example input & output, and I've changed the name of the command to avoid collisions.

Thanks again for the feedback.

**Pull request merged**
