### PR TITLE
add python-black

### PR DESCRIPTION
**Pull request by thep0y**

### CODE REVIEW

**Comment by braver** [comment]
We already have some of those: https://packagecontrol.io/search/pep8, https://packagecontrol.io/packages/sublack. What does yours add?
Also please don't change or format any files beyond your additions.

**Comment by thep0y** [comment]
> https://packagecontrol.io/search/pep8

1. `pep8` and `black` are different styles.
2. The design logic of `python-black` is different from that of [`sublack`](https://github.com/jgirardet/sublack). When all plugins are loaded after starting SublimeText, `sublack` will start, and `python-black` will only run when needed, and exit immediately after formatting, without occupying operating system resources. In addition, the implementation of functions in `sublack` is complicated, which is not practical for me personally.
3. I seem to format the `p.json` file in the `repository` directory, because after editing a file, I will format it habitually.

For the above reasons, I wrote this package.

**Comment by rchl** [comment]
In the readme it says "Supports ST3 only.". That should be updated.

**Comment by thep0y** [comment]
> In the readme it says "Supports ST3 only.". That should be updated.

Sorry, I did not find the content about "Supports ST3 only." in the README, can you tell me where it is?

**Comment by braver** [comment]
I mention pep8 because you're trying to add AutoPEP8 2020 as well here. Please clean up the json files and only make the changes necessary for the package you want to submit.

As for sublack (disclaimer: I am not wholly familiar with how it works), doesn't it only run in the background as a daemon if you want it to? Ie. it does seem to support a mode where it only does on-demand formatting.

**Comment by rchl** [comment]
> > In the readme it says "Supports ST3 only.". That should be updated.
> 
> Sorry, I did not find the content about "Supports ST3 only." in the README, can you tell me where it is?

Screenshot 2021-06-02 at 15 22 47

**Comment by thep0y** [comment]
> I mention pep8 because you're trying to add AutoPEP8 2020 as well here. Please clean up the json files and only make the changes necessary for the package you want to submit.
> 
> As for sublack (disclaimer: I am not wholly familiar with how it works), doesn't it only run in the background as a daemon if you want it to? Ie. it does seem to support a mode where it only does on-demand formatting.

I have no experience in developing `sublime text` plugins. I have seen that `plugin_loaded` will be automatically called when sublime text starts. I think there are some meaningless codes in this function.
But if it is not a daemon, please reject this pull request https://github.com/wbond/package_control_channel/pull/8287/commits/5e2df2987385c8fa68f1bcce07c2c55b6a33ac31.

**Comment by thep0y** [comment]
> > > In the readme it says "Supports ST3 only.". That should be updated.
> > 
> > 
> > Sorry, I did not find the content about "Supports ST3 only." in the README, can you tell me where it is?
> 
> Screenshot 2021-06-02 at 15 22 47

My fault, because I modified autopep8 a long time ago, deleted the fork before, and forgot to delete the request for autopep8 when I re-fork and submit a new pull request today.

**Pull request closed without merging**
