### PR TITLE
FIX: retitle Chrome REPL > ChromeREPL to fix imports

### PR DESCRIPTION
**Pull request by acarabott**
Renamed the Package from "Chrome REPL" to "ChromeREPL" as the name determines the installed `.sublime-package` file, and thus imports such as `ChromeREPL.helpers` are broken.

---

Please ensure the automated reviews pass. 
Follow the instructions provided, if necessary.
You can speed up the process
by [running some tests locally](https://packagecontrol.io/docs/submitting_a_package#Step_7).

You can trigger @packagecontrol-bot to re-evaluate your pull request
by pushing a commit or closing and reopening your pull request.
Do **NOT** open a new pull request!

In general, make sure you:

 1. Used `"tags": true` and not `"branch": "master"` 
    (versioning docs: <https://packagecontrol.io/docs/submitting_a_package#Step_4>)
 2. Added a README to your repository so that users (and reviewers) 
    can understand what your package provides.
 
You should proceed with a short description of what the package does
and, in case one or multiple similar package already exists, 
why you believe it is different and needed
below this line. -->

### CODE REVIEW

**Comment by Thom1729** [comment]
You need to realphabetize the entry.

**Comment by acarabott** [comment]
Alphabetize done!

**Comment by acarabott** [comment]
Thanks for the merge!

I've noticed that the repo exists under both names at the moment, is this a caching issue?

**Comment by acarabott** [comment]
Would it be possible to have the old cached version removed? It creates confusion upon installing...

To be removed: https://packagecontrol.io/packages/Chrome%20REPL

**Pull request merged**
