### PR TITLE
Add Refraction

### PR DESCRIPTION
**Pull request by haydenbleasel**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read the docs.
- [x] I have tagged a release with a semver version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries.
- [x] My package doesn't add key bindings.
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme.
- [x] I use .gitattributes to exclude files from the package: images, test files, sublime-project/workspace.

My package is a Sublime extension for [Refraction](www.refraction.dev), a code generation tool for developers. It uses AI to generate code for you. You can use it to generate unit tests, documentation, refactor code and more.

There are no packages like it in Package Control.

### CODE REVIEW

**Comment by braver** [comment]
Please just add your package to [r.json](https://github.com/wbond/package_control_channel/blob/master/repository/r.json).

**Comment by haydenbleasel** [comment]
Sorry @braver I didn't notice the existing file structure. Fixed my PR.

**Comment by braver** [comment]
Almost! Entries are sorted alphabetically.

**Comment by braver** [comment]
The existing, and recently added, [AssistantAI](https://packagecontrol.io/packages/AssistantAI) package might also be able to work with Refraction. If that's true, it might be more efficient to work together on that package. 

In any case, please have a look at my feedback for that package, it might apply to yours as well: https://github.com/wbond/package_control_channel/pull/8712#issuecomment-1490753516

**Comment by haydenbleasel** [comment]
Thanks @braver, fixed the alphabetical sorting. Checked out AssistantAI but it wouldn't work for this particular use case — this extension that works with a paid Refraction subscription. However I'll keep an eye on it in case this changes.

**Comment by braver** [comment]
Ok! Please clearly state in your readme if how and when code will be uploaded to third party services, as outlined in the comment I linked to earlier. And have a look at the feedback from the bot.

**Comment by haydenbleasel** [comment]
Hi @braver, thanks for the review. I've added a top-level LICENSE file and added note to the README about external processing.

**Comment by haydenbleasel** [comment]
@braver I've just deleted package-metadata.json as per the results above

**Comment by braver** [comment]
Ah, you need to tag a new release before the bot actually sees that you did that.

**Comment by haydenbleasel** [comment]
@braver Gotcha, ok just made a new tag / release

**Comment by braver** [comment]
Alright, that's better :) 

One final thing I noticed from reviewing your code. You let users set credentials via a command (nice job there 👍🏻), and then store them in the user's `Refraction.sublime-settings` file. I think users might appreciate it if you allow them to find and view that file directly, as is typically done with sublime settings files, via the packages settings menu.

**Comment by haydenbleasel** [comment]
Hey @braver, great idea! I'm not the active developer on this repo, so it is possible I could open this as an enhancement task and implement it for the next version?

**Comment by braver** [comment]
Well it's trivial, can't even call it code really. I'll make a PR. One of the big reasons for the review process here is that we kinda validate your willingness and ability to respond to user feedback, so let's make a good show of that ;)

**Comment by haydenbleasel** [comment]
Thanks @braver I appreciate that. I should brush up on my Python / Sublime Extension syntax so I can take care of these myself going forward.

**Comment by braver** [comment]
Well you can handle that in your own time and tag a release when ready. Let's wrap it up here in the mean time.

**Pull request merged**
