### PR TITLE
Add ERB Formatter

### PR DESCRIPTION
**Pull request by gobijan**
- [X] I'm the package's author and/or maintainer.
- [X] I have have read [the docs][1].
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [X] My package doesn't add context menu entries. *
- [X] My package doesn't add key bindings. **
- [X] Any commands are available via the command palette.
- [X] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.

My package is a formatter for ERB files often used in Ruby on Rails applications.
There are no packages like it in Package Control.

### CODE REVIEW

**Comment by gobijan** [comment]
@packagecontrol-bot can you review?

**Comment by gobijan** [comment]
Not sure what is failing... Can anybody help?

**Comment by FichteFoll** [comment]
I took a quick look at it since it was posted on discord.

1. Per convention, your menu entry to open the settings should open the User key bindings (platform-specific).
2. I generally recommend to always create command palette entries for everything that a package can do and that you would define menu entries for, since the command palette is much easier to access using a keyboard.
3. This functionality is also generically provided by the [Fmt package](https://packagecontrol.io/packages/Fmt), which aims to replace 100 packages for different formatters with a unified package design based on configuration. Imo it makes more sense to add multiple known formatter configuration to that package's readme or wiki instead of yet another package to the list, but YMMV. For searchability, a generic package might be harder to find than a specific one.

**Comment by gobijan** [comment]
Hey, I agree with you @FichteFoll.
I'll add to the wiki for the FMT package. Any idea how to promote the FMT package? I didn't know about it before you told me via Discord.

**Pull request closed without merging**
