### PR TITLE
add complete scss-snippets

### PR DESCRIPTION
**Pull request by onhernandes**
[Repository](https://github.com/mhernandes/sublime-scss-snippets)
[Last release](https://github.com/mhernandes/sublime-scss-snippets/releases/tag/v0.0.3)

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for sublime-scss-snippets ###################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 1 failures:
- Invalid XML
    File: selector-parse.sublime-snippet
    Exception: not well-formed (invalid token): line 7, column 78

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by onhernandes** [comment]
Fixed.
[Repository](https://github.com/mhernandes/sublime-scss-snippets)
[Last release](https://github.com/onhernandes/sublime-scss-snippets/releases/tag/v1.0.4)

**Comment by FichteFoll** [comment]
You might also want to take a look at completions files, which are better suited for the function call completions, but that's just a suggestion.

**Comment by onhernandes** [comment]
I'll read about that, thank you!

**Pull request merged**
