### PR TITLE
Add Viper plugin

### PR DESCRIPTION
**Pull request by WirelessWizard**
A new Sublime Text 3 plugin for the ETH Zürich [Viper project](http://www.pm.inf.ethz.ch/research/viper.html). The plugin allows to automatically verify annotated programs in Silver language through a mechanism based on Sublime's build systems.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your repo url 404s.

**Comment by FichteFoll** [comment]
@WirelessWizard ping

**Comment by WirelessWizard** [comment]
@FichteFoll  Sorry for the delay—the repo is ready.

**Comment by FichteFoll** [comment]
You state that ST3 is required but as it stands, installation will be possible for ST2 as well. Please update the version requirement. I also noticed that in your readme you tell users to clone to a package named "Silver", while the package will be installed as "Viper" (from your package name). In https://bitbucket.org/viperproject/viper-sublime-ide/src/330ff22841dea3d249b5aee7a946a3d2117b0c4a/BuildSilver.py?fileviewer=file-view-default#BuildSilver.py-19 you then hard-reference a package name of "Viper-IDE".

**Pull request closed without merging**
