### PR TITLE
polyglot snippets

### PR DESCRIPTION
**Pull request by thespacedoctor**
Please provide the following information:
- Link to your code repository:
- Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:
1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please  only add one package per Pull Request.

I will revisit this PR at a later time.

**Comment by thespacedoctor** [comment]
apologies. Would you prefer that I reissued pull requests for each package?

**Comment by FichteFoll** [comment]
No, you can leave it like this now. Just consider it for the future.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts (applies to both packages).

**Comment by thespacedoctor** [comment]
ok, all package updated and tagged with semantic versions

**Pull request merged**
