### PR TITLE
add APICloudSnippets plugin

### PR DESCRIPTION
**Pull request by taxusyew**

### CODE REVIEW

**Comment by FichteFoll** [comment]
If you can you should add `<scope>` restritctors to your snippets because currently they are active for all languages.

**Comment by taxusyew** [comment]
Thanks for your advice, I have changed the `<scope>` restritctors in my snippets.
And the tag has benn added.

**Comment by FichteFoll** [comment]
There is no tag on https://github.com/taxusyew/apicloud-sublime-snippet/tags however.

**Comment by taxusyew** [comment]
Sorry about that, my mistake, is that all right now?

**Pull request merged**
