### PR TITLE
Add DisableArrowKeys plugin

### PR DESCRIPTION
**Pull request by daytonn**
Plugin to make arrow key bindings toggleable

### CODE REVIEW

**Comment by wbond** [comment]
You need to push a tag in order for users to install this

**Comment by daytonn** [comment]
I do have a 1.0.0 tag. I don't see it in the package list.

**Comment by wbond** [comment]
Not seeing anything at https://github.com/daytonn/DisableArrowKeys/tags

**Comment by daytonn** [comment]
Nevermind, I thought this was on another repo

**Comment by daytonn** [comment]
Done

**Pull request merged**
