### PR TITLE
add my BowerInjector plugin

### PR DESCRIPTION
**Pull request by ismnoiet**
i added BowerInjector plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by ismnoiet** [comment]
@FichteFoll You are talking about adding the supported version of sublime to the title of the plugin for example BowerInjectorSublime3 that is what you want me to add?  or am i getting it wrong ?

**Comment by ismnoiet** [comment]
@FichteFoll i've created a release, i think this is what you are talking about

**Comment by FichteFoll** [comment]
Yes, exactly.

**Comment by ismnoiet** [comment]
Thank you for accepting my pull request

**Pull request merged**
