### PR TITLE
Add Just package

### PR DESCRIPTION
**Pull request by nk9**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a syntax definition for the [Just task runner](https://just.systems). It has comments and a simple build system too.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
- Why do you have both uppercase and lowercase syntax files?
- The formatter functionality might be better (more flexible etc) supported by the [Fmt package](https://packagecontrol.io/packages/Fmt) (although I use similar build systems for this all the time myself). But you might be interested in documenting a setup for Fmt.
- I believe the package assumes just already being set up on the user's system. Users just starting out with just and ST might need a little help setting it up. Ie. you might want to clarify that the package doesn't ship with just and it needs to be in the user's path.

**Comment by nk9** [comment]
Thanks for the review!

- I've added the `LICENSE` file back to the package. I was excluding it in the `.gitattributes` file.
- Good catch on the doubled syntax files, I've fixed that.
- I wasn't aware of Fmt, it looks useful! As it stands, though, the formatter is still unstable. There is actually [a bug at present](https://github.com/casey/just/issues/1449) which will cause it to generate code which won't parse correctly. (Fixed, but not yet released.) So I think I will wait to mention this anywhere.
-  Note that the Build System included with this package doesn't actually change the file. Rather, it produces a reformatted version in memory and compares that to the version on disk. It also parses the file and does a bit of static analysis to make sure that there are no syntax errors.
- The Build System does assume that just is installed and in the PATH, although of course the syntax works regardless. I've incldued a bit about this in the install message.

**Comment by braver** [comment]
🎉

**Comment by nk9** [comment]
Thanks for your help!

**Pull request merged**
