### PR TITLE
first release

### PR DESCRIPTION
**Pull request by tushortz**

### CODE REVIEW

**Comment by FichteFoll** [comment]
I admit I haven't actually checked your repo before, but your package only contains a "color scheme", not a "theme" (in sublime text terminology). Please adjust name and labels accordingly. You do not need to start a new pull request for this.

**Comment by tushortz** [comment]
I was wondering. Is there anything else I need to include in my forked version

**Comment by FichteFoll** [comment]
Sorry, but I don't get notifications for commits on pull requests, unlike comments.

Yes, you have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by tushortz** [comment]
I have just done the versioning on GitHub in the release section. Is there anything I may be missing?

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by tushortz** [comment]
I've changed it to v1.0.0

**Comment by tushortz** [comment]
Thanks for the useful information. I at least know the steps to follow next time

**Comment by tushortz** [comment]
When will the package be available on the packagecontrol.io website

**Comment by FichteFoll** [comment]
I suspect the issue is the upper-case `V` in your tag. Try changing that to lower-case or removing it completel.y

**Comment by tushortz** [comment]
thanks.it worked now

**Pull request merged**
