### PR TITLE
colorToVal.json

### PR DESCRIPTION
**Pull request by yh418807968**
Please provide the following information:

 - Link to your code repository:
 - Link to the tags page with at least one [semver](http://semver.org) tag: 

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Can you please add a valid release tag?

**Comment by FichteFoll** [comment]
@yh418807968 please follow the procedure outlined at https://packagecontrol.io/docs/submitting_a_package. Specifically, remove the file you created and add the data to `repository/c.json`.

**Comment by yh418807968** [comment]
I am so  sorry，my English understanding is not very good,so I did some wrong operations.
I have resolved the problem mentioned，hope my operation is correct this time.Thank you !



418807968@qq.com
 
From: FichteFoll
Date: 2017-06-28 00:11
To: wbond/package_control_channel
CC: hong; Mention
Subject: Re: [wbond/package_control_channel] colorToVal.json (#6384)
@yh418807968 please follow the procedure outlined at https://packagecontrol.io/docs/submitting_a_package. Specifically, remove the file you created and add the data to repository/c.json.

**Comment by FichteFoll** [comment]
Callbacks added via `add_on_change` are not cleared when the plugin is unloaded. To ensure your package will be properly unloaded when disabled, you need to implement `plugin_unloaded` and call `clear_on_change`.

This is a minor error though, so I'll merge already.

**Comment by FichteFoll** [comment]
Actually, no, the package is not in order.

Please sort the package alphabetically, as indicated by Travis CI: https://travis-ci.org/wbond/package_control_channel/builds/248383915#L417

**Comment by FichteFoll** [comment]
The tests are still failing. https://travis-ci.org/wbond/package_control_channel/builds/248605694#L170

**Comment by yh418807968** [comment]
Thank you so much for pointing out my mistakes repeatedly!
The error is a format error:"Indent must be tabs in line 2507", so in order to ensure correctness , I copied the others, and then changed the information with my plugin.



418807968@qq.com
 
From: FichteFoll
Date: 2017-07-01 00:21
To: wbond/package_control_channel
CC: hong; Mention
Subject: Re: [wbond/package_control_channel] colorToVal.json (#6384)
The tests are still failing. https://travis-ci.org/wbond/package_control_channel/builds/248605694#L170

**Pull request merged**
