### PR TITLE
Added SumoSwissKnife package

### PR DESCRIPTION
**Pull request by scrummastermind**
This is to add **SumoSwissKnife** a collection of tools to work with [Sumo Logic](https://www.sumologic.com/what-is-log-management/) Log Management [APIs](https://api.sumologic.com/docs/)

### CODE REVIEW

**Comment by scrummastermind** [comment]
fixed errors

**Comment by scrummastermind** [comment]
Fixed errors

**Comment by FichteFoll** [comment]
Are you sure this needs to be limited to macOS? This mostly seems to be general support for a language with a syntax definition and completions, which are perfectly cross-platform. The Python code is a bit too much for me to review in detail, but even if that was platform-specific you could just disable it when it's not supported.

Keys in messages.json must be actual versions, i.e. not have the `v` prefix.

**Comment by FichteFoll** [comment]
@scrummastermind ping

**Comment by scrummastermind** [comment]
OS Restriction removed

**Comment by scrummastermind** [comment]
OS Restriction removed

**Comment by scrummastermind** [comment]
@FichteFoll

**Comment by FichteFoll** [comment]
Please remove the `v` from the key at

https://github.com/scrummastermind/SumoSwissKnife/blob/82008156fea643b17d1349db2d4d1f0c22e1b5c3/messages.json#L3

**Comment by scrummastermind** [comment]
> Please remove the `v` from the key [here](https://github.com/scrummastermind/SumoSwissKnife/blob/82008156fea643b17d1349db2d4d1f0c22e1b5c3/messages.json#L3).

Done!

**Pull request merged**
