### PR TITLE
add escape plugin to package.json

### PR DESCRIPTION
**Pull request by iahu**
add escape plugin to package.json

### CODE REVIEW

**Comment by FichteFoll** [comment]
I suggest adding this functionality to https://packagecontrol.io/packages/Stringify.

**Comment by iahu** [comment]
As it can say `escape` is a upgrade version of `Stiringify`, I think `escape` is better release as a new version of `Stringify`. @BurnerPat
```
escape(`中文`); //  => \u4e2d\u6587
escape('\u4e2d\u6587'); // => \\u4e2d\\u6587  same as stringify('\u4e2d\u6587)

unescape('\\u4e2d\\u6587'); // => \u4e2d\u6587 same as deStringify(''\\u4e2d\\u6587')
unescape('\u4e2d\u6587'); // => 中文
```

**Comment by FichteFoll** [comment]
Actually, I now think that Stringify serves a different purpose.

Anyway, you'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by iahu** [comment]
ok, I have changed the repository file. @FichteFoll

**Pull request merged**
