### PR TITLE
Everblush color scheme

### PR DESCRIPTION
**Pull request by Qwickdom**
- [x] I'm the package's author and/or maintainer.
- [x] I have read the docs.
- [x] I have tagged a release with a semver. version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries.
- [x] My package doesn't add key bindings.

My package is... **A Dark, Vibrant and Beatiful color scheme for Sublime Text**

### CODE REVIEW

**Comment by braver** [comment]
Please tag a release using semver numbering, we can't ship your package without tags.

**Comment by braver** [comment]
Please respond to the feedback to continue the review.

**Comment by Qwickdom** [comment]
> Please respond to the feedback to continue the review.

Hi, in a few days I'll tag a release using semver

**Comment by braver** [comment]
Tagging a release takes about 2 seconds. Please let us know when you've done so, we can re-open the PR then. For now I'm closing it so we don't have to actively monitor it.

**Pull request closed without merging**
