### PR TITLE
Add Direct Copy plugin

### PR DESCRIPTION
**Pull request by UniFreak**

### CODE REVIEW

**Comment by Thom1729** [comment]
Please add a license.

**Comment by UniFreak** [comment]
Added MIT license.

**Comment by Thom1729** [comment]
What's the purpose of the odd settings behavior?

**Comment by UniFreak** [comment]
To load the default setting if no user setting is found. 
I don't know whether there is a better way to do this.

**Comment by Thom1729** [comment]
You can put a `DirectCopy.sublime-settings` file in your package with whatever defaults you need. If the user has their own `DirectCopy.sublime-settings` under `User` then it will supersede the defaults key-by-key.

It looks like you should simply rename your `Default.sublime-settings` to `DirectCopy.sublime-settings`. Then, `sublime.load_settings('DirectCopy.sublime-settings').get('entry')` will default to your initial value unless the user's `DirectCopy.sublime-settings` file has an `entry` key. When you save the settings object, it will create/update the user's `DirectCopy.sublime-settings` file, leaving the original intact.

**Comment by UniFreak** [comment]
Thanks for your suggestion. I tried it and it works as expected. Also I need to edit the `Main.sublime-menu` to point the default setting file to `DirectCopy.sublime-settings`.

I've made a new commit.

**Pull request merged**
