### PR TITLE
Add SPARQL Runner package

### PR DESCRIPTION
**Pull request by hevp**
Add SPARQL Runner Improved package

### CODE REVIEW

**Comment by Thom1729** [comment]
Why fork the existing package?

**Comment by Thom1729** [comment]
If the original author isn't interested in maintaining it, then it's possible to transfer the package name to a new repository. Have you reached out to the author, e.g. on the issue tracker?

**Comment by FichteFoll** [comment]
The author appears to be unresponsive (https://github.com/cezarsa/sublime-sparql-runner/issues/6), so we can go forward with transfering package ownership.

Please adjust the internal references to the package's name and do the necessary updates in this PR so we can go ahead with it.

**Comment by FichteFoll** [comment]
@hevp the tags you push are not valid semantic versions. [Semantic versions](https://semver.org) consist of three numeric parts.

**Comment by hevp** [comment]
Indeed, I have updated the tags.

**Comment by FichteFoll** [comment]
Doesn't look like it. https://github.com/hevp/sublime-sparql-runner/tags

**Comment by hevp** [comment]
One more try

**Pull request merged**
