### PR TITLE
Add sublimelsp repository

### PR DESCRIPTION
**Pull request by rwols**
- Remove LSP package
- Remove LSP-* packages
- Remove lsp_utils dependency

### CODE REVIEW

**Comment by rchl** [comment]
I believe you can close and re-open PR to re-trigger the bot.

**Comment by rchl** [comment]
Forgot that changes need to be released first (I've released `LSP-json` now).

**Comment by rwols** [comment]
I guess the bot needs an update.

**Comment by rwols** [comment]
Thanks!

**Pull request merged**
