### PR TITLE
Cipher Package

### PR DESCRIPTION
**Pull request by depaolism**
A package that includes common functions used when deobfuscating various texts.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Except for string concatenation, most of these utils are already available in at least one other package.
Maybe you could add that functionality to https://packagecontrol.io/packages/StringUtilities?

cc @akalongman

**Comment by akalongman** [comment]
Pull requests hightly welcomed

**Comment by depaolism** [comment]
Thanks, I found various packages that performed base64 encoding/decoding when I searched through the available packages, but I didn't come across StringUtilities (bad search skills). I plan on continuing to add different string transformations as I come across them. StringUtilities may be the place for them.

**Comment by FichteFoll** [comment]
Since this seems resolved, I'm closing.

**Pull request closed without merging**
