### PR TITLE
added DumperWrap

### PR DESCRIPTION
**Pull request by barkonar**
Link to code repository: https://github.com/barkonar/dumperwrap
Link to the page with tag 0.0.1: https://github.com/barkonar/dumperwrap/tree/0.0.1

### CODE REVIEW

**Comment by joshua-golub** [comment]
@barkonar, two things:

1. You've got a typo ("pronting") in your .sublime-menu file

2. Have you verified that your key binding doesn't override a default on any platform?

-Josh

**Comment by FichteFoll** [comment]
The highes version tag on your repo is `0.0.8`, which is not what the current master branch represents at all. This is an artifact from you forking the package.

**Comment by FichteFoll** [comment]
@barkonar ping

**Comment by barkonar** [comment]
Hi,

I'll fix it. probably next week. I just don't have time for this now.



2017-01-19 13:45 GMT+01:00 FichteFoll <notifications@github.com>:

**Pull request closed without merging**
