### PR TITLE
Rebasing Flask Starter

### PR DESCRIPTION
**Pull request by Joepriesto**
After repeated requests to the package maintainer with no response I believe this package is no longer maintained. I would like to re base it to my fork and take over support.

### CODE REVIEW

**Comment by Joepriesto** [comment]
Hi is there any reason why this isn't moving forward?

**Comment by FichteFoll** [comment]
I've been on vacation last week and am currently dealing with exams, which is why I haven't been able to set aside time for reviewing. Don.t worry, your package will eventually be looked at.

**Comment by Joepriesto** [comment]
Apologies, I thought there was a bit of a bigger team reviewing and merging!

Obviously, take your time, there's really no rush. I just thought I might have made an error.

**Comment by FichteFoll** [comment]
In theory there are up to three people reviewing, but in practice it's just me.

**Comment by FichteFoll** [comment]
@geekpradd, if you are still alive and object to this change of ownership, please respond here within the next two weeks. If you don't, I will merge after that.

**Pull request merged**
