### PR TITLE
Added labels to Conda plugin

### PR DESCRIPTION
**Pull request by mandeep**
I added labels to the Conda plugin. It's an existing plugin already on Package Control. Thanks!

### CODE REVIEW

**Comment by AlexKvazos** [comment]
@mandeep Do you authorize this?

**Comment by mandeep** [comment]
@AlexKvazos what do you mean?

**Comment by AlexKvazos** [comment]
@mandeep Omg so sorry, I don't know why I thought you modified someone else's package, fail.

**Comment by mandeep** [comment]
@AlexKvazos Haha, no worries!

**Pull request merged**
