### PR TITLE
Add Cucumber Snippets e Highlight em Português

### PR DESCRIPTION
**Pull request by RobertoPegoraro**
Cucumber Snippets e Highlight em Português

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

@wbond was there anything regarding non-ASCII characters in package names?

**Comment by RobertoPegoraro** [comment]
I created a new release in my repository with version 1.0.0, I think that's what you asked for, right?

**Comment by FichteFoll** [comment]
Yes. I'd like to wait for @wbond's reply however.

**Comment by wbond** [comment]
The only issue I know of with non-ascii characters is that the command palette does not strip diacritics when searching, so if you have a package named `Résumé`, you would have to type `é` and not just `e` to match it.

**Comment by RobertoPegoraro** [comment]
This is a problem I need to change?

**Comment by FichteFoll** [comment]
Not really. It just means that you can't find this package by searching for `Portugues`.

**Pull request merged**
