### PR TITLE
Add RustAutoImport

### PR DESCRIPTION
**Pull request by trishume**
My package provides a command to automatically add `use` statement imports in Rust. Basically a single fancy text macro with some smarts.

<https://github.com/trishume/SublimeRustAutoImport>

### CODE REVIEW

**Comment by Thom1729** [comment]
What's the deal with `Default.history_list`?

**Comment by trishume** [comment]
@Thom1729 I wanted the built in “jump back” (CTRL+minus on Mac) command to work to jump back to where you were before adding the import. The function to add locations to the jump history is only available importing like that.

**Comment by Thom1729** [comment]
Why doesn't `import Default.history_list` work?

**Comment by trishume** [comment]
@Thom1729 it doesn't import it as the path I thought it would. I changed it to use `from Default import history_list` instead and that works. I pushed `1.0.1` with that change.

**Pull request merged**
