### PR TITLE
RPN Calculator

### PR DESCRIPTION
**Pull request by bphunter1972**
An RPN Calculator with programmer, scientific, and statistical modes.

### CODE REVIEW

**Comment by bphunter1972** [comment]
I'm not sure if there's anything left. Can this pull req be integrated?

**Comment by FichteFoll** [comment]
Could you perhaps squash the commits? Also, please perform tests locally next time using [ChannelRepositoryTools](https://packagecontrol.io/packages/ChannelRepositoryTools).

I think a screenshot it your readme would be nice.

**Comment by bphunter1972** [comment]
Sorry about that. Last week, ChannelRepositoryTools was dying on me, but the recent ST3 build must have fixed the issue because now it’s working.

Added images and rebased.

Brian

**Comment by FichteFoll** [comment]
It's okay, as long as you squash (because 11 commits for a change this small are really unwarranted). You didn't rebase though, you merged.

**Comment by bphunter1972** [comment]
Closing this one in favor of 4313.

**Pull request closed without merging**
