### PR TITLE
Add NeoVintageousHighlightLine

### PR DESCRIPTION
**Pull request by gerardroche**
https://github.com/gerardroche/NeoVintageousHighlightLine

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is NeoVintageousHighlightLine

https://github.com/gerardroche/NeoVintageousHighlightLine

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
If you're going to publish a lot of plugins, at some point it maybe starts making sense having your own channel?

**Comment by gerardroche** [comment]
I don't expect to have a crazy amount of NeoVintageous packages. Most NeoVintageous plugins are bundled with NeoVintageous. It's really only the one's that have side effects or one's that are   unique to a subset of users like keyboard layout plugins e.g. [Colemak](https://github.com/gerardroche/NeoVintageousColemak) and [Dvorak](https://github.com/gerardroche/NeoVintageousDvorak) (those are experimental in development so we'll see how it goes).

Plugins like this one are not everbody's cup of tea. But I've been using them in my own custom Subime Text plugins for a while and figured others might find them useful.

**Comment by gerardroche** [comment]
@braver When you said it make sense having my own channel, did you mean
 specifically for NeoVintageous or in general for all my packages? Because if
 you meant the latter, I didn't know you could do that. I thought SublimeLinter
 and the few others were special cases.

**Comment by braver** [comment]
You could do a personal channel indeed. Some do have one. I don't like doing it that way though, because the packages are out of reach of maintainers of the channel and it's a hassle if a developer stops supporting a package that we still want to keep available (or fork or replace etc). Although it's not "policy", I would say we're quietly moving away from that idea for individual developers. Even the Sublime Text org simply lists their packages in the main channel. 

I brought it up mostly indeed because of the use cases like SublimeLinter and LSP, where it's easier to manage several plugins in one place. And maintainers of those "frameworks" are better positioned to manage and review those plugins anyway. If you don't need that and don't expect a large number of plugins, let's just keep them here in the main channel. 

Especially for known active members of the community and those who already maintain multiple packages, I hope the review process isn't too much of a blocker. I do keep an eye out for the known quantities, as yourself, and move them along quickly.

**Comment by gerardroche** [comment]
I don't mind the review process. It's helpful to catch some oversights. 

Plus, it's not that often you add a package. And rarely update them. I don't know why some people get upset that it could maybe take up to a few weeks for a package to be processed.

**Comment by braver** [comment]
Just some folks feel they're entitled to stuff. 🤷🏻

**Pull request merged**
