### PR TITLE
Update Vue Syntax Highlight release tags

### PR DESCRIPTION
**Pull request by yyx990803**
We are now releasing a rewritten version for build > 3153.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Because the highest `newsyntax-` tag is `1.0.1` and the last normal tag is `3.2.3`, people would be upgraded to it. You'll have to push something higher than `3.2.3`.

**Comment by yyx990803** [comment]
@FichteFoll thanks, /cc @skyronic

**Comment by skyronic** [comment]
Will take care of it today

**Comment by skyronic** [comment]
The tags are created and the latest version is being picked up now.

image

**Comment by yyx990803** [comment]
👍

**Pull request merged**
