### PR TITLE
New Package : Remove Workspace

### PR DESCRIPTION
**Pull request by SmartManoj**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is  Remove Workspace

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by SmartManoj** [comment]
Solves https://stackoverflow.com/questions/11744365/removing-projects-in-sublime-text-2-and-3

**Comment by rwols** [comment]
I believe this is builtin in ST4

**Comment by Ultra-Instinct-05** [comment]
Yes. For ST4, you can just use `Project -> Open Recent -> Remove Deleted` to get rid of deleted projects or workspaces (FWIW SM also has the same ability to clear dead repositories using (`File -> Open Recent -> Clear Missing`).

For ST3, there was this earlier https://github.com/STealthy-and-haSTy/SublimeScraps/tree/master/session_cleaner. So the plugin could be useful for ST3, but given that a decent number of stable ST4 releases are present, I wouldn't use ST3 and there is no need of this plugin in ST4.

**Comment by SmartManoj** [comment]
Just a note, the difference from that package is it automatically closes the app and the workspaces can be selected.

**Pull request closed without merging**
