### PR TITLE
Add "Increment Decrement" package

### PR DESCRIPTION
**Pull request by cgjosephlee**
This package is inspired by vim script [nextval](
https://www.vim.org/scripts/script.php?script_id=4536), implementing increment or decrement of integers, decimals, roman and boolean values.

### CODE REVIEW

**Comment by Thom1729** [comment]
It would be a good idea to declare `__all__ = [IncrementCommand, DecrementCommand]` so you're not declaring a new command called `number`.

**Comment by cgjosephlee** [comment]
> It would be a good idea to declare `__all__ = [IncrementCommand, DecrementCommand]` so you're not declaring a new command called `number`.

Good point! Thank you for the suggestion.

**Comment by Thom1729** [comment]
You have a typo in the command name: `IncrementDecreamentCommand`.

**Comment by cgjosephlee** [comment]
> You have a typo in the command name: `IncrementDecreamentCommand`.

@Thom1729 This is fixed, thank you.

**Pull request merged**
