### PR TITLE
Add Nuke-Tools-St

### PR DESCRIPTION
**Pull request by sisoe24**
A Sublime Text package that allows to send python or blinkscript code to be executed inside Nuke.

### CODE REVIEW

**Comment by braver** [comment]
Tip: you can use `.gitattributes` to "export-ignore" some files (test, documentation, ideas config) so they don't end up in your package, saving space and bandwidth. 
We recommend against shipping keybindings because they tend to conflict with other packages. Instead document in your readme how users can set up their own bindings. Also, your command probably doesn't need to be in every menu, especially not unconditionally in the context menu. Space is limited!

**Comment by sisoe24** [comment]
Thank you for your time!

I've implemented all of your suggestions. Should I create a new release tag or create back the initial one?

**Comment by braver** [comment]
Just create a new tag 👍🏻

**Comment by sisoe24** [comment]
ok. let me know if there is something else. 

thanks

**Comment by braver** [comment]
Nope, looks good 👍🏻

**Pull request merged**
