### PR TITLE
Add dependency Beautiful Soup 4.4.1

### PR DESCRIPTION
**Pull request by jlegewie**
Add Beautiful Soup 4.4.1 to dependencies. https://www.crummy.com/software/BeautifulSoup/

### CODE REVIEW

**Comment by divinites** [comment]
Great!  I want beautiful soup as a dependencies for months!

**Comment by jlegewie** [comment]
Good to hear that! I realized that I am not entirely sure whether this actually works. Can anyone test it? Otherwise, I will post in the forum and ask for advice.

**Comment by divinites** [comment]
I want to use BS4 to enhance my quickmail plugin, but it is unlikely to be done recently.  Posting in the forum seems to be a good idea anyway.

**Comment by jlegewie** [comment]
Ok, everything should work now. I have tested it with a private repository and Beautiful Soup seems to be running perfectly!

**Comment by wbond** [comment]
Your tag is going to need to be [semver](https://semver.org)-compatiable. `1.0` won't work, but `1.0.0` will.

**Comment by jlegewie** [comment]
Sorry for that. Just changed it...

**Pull request merged**
