### PR TITLE
Add FacilityApi support

### PR DESCRIPTION
**Pull request by jzbrooks**
This package provides syntax highlighting for Facility Service Definition files used by the [Facility API Framework](https://facilityapi.github.io/). No package currently exists for this purpose.

### CODE REVIEW

**Comment by jzbrooks** [comment]
A tag (1.0.0) has been pushed to the repo.

**Comment by jzbrooks** [comment]
Added a license file

**Comment by jzbrooks** [comment]
I'm not sure why the bot is still triggering the license file warning. I've added one [here](https://github.com/FacilityApi/FacilitySublime/blob/master/LICENSE)

**Comment by wbond** [comment]
You release (1.0.0) points to the commit before you added the license.

**Comment by jzbrooks** [comment]
Got it. I'll sort the tag. Thanks.

**Pull request merged**
