### PR TITLE
Remove MavensMate

### PR DESCRIPTION
**Pull request by joeferraro**
MavensMate has reached end of life and is no longer being actively developed or supported.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You should update the installation instructions so people don't start wondering why they can't install via PC anymore. Just tell them to add the repo with the "Add Repository" command instead or to clone the repo, if they really want it.

**Comment by harshgosar** [comment]
@joeferraro Why did you do that, I loved MavensMate. I couldn't even fork this project 😞

**Comment by FichteFoll** [comment]
What do you mean, you can still fork it.

**Comment by dmnBrest** [comment]
The best IDE for classic SF development. I still use it and will use until it is possible. Many thanks for author!!!!

**Comment by dmnBrest** [comment]
WTF!!!!
https://i.snag.gy/S8sn2t.jpg
If you don't want to develop and support your app why you kill it in our side? I didn't update anything but today found this f..ing screen!
Thank you so much!

**Comment by yoni-g** [comment]
@joeferraro 
Why did you kill the app?? It was sooooo useful and great to use!!
Please let us know how we can maybe fork it and still use it..

**Pull request merged**
