### PR TITLE
Add Elevator

### PR DESCRIPTION
**Pull request by kapitanluffy**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is Elevator

There are no packages like it in Package Control.

My package is similar to ... However it should still be added because ...

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Looks like you're basically providing what [LineJumper](https://packagecontrol.io/packages/LineJumper) already does. That's a pretty stale package though. Please find out if you can contribute to that package instead of adding a new package. Maybe you can even take over that repo. Otherwise, if that does not work out, we can consider removing that existing package with yours, and bring the updated and improved functionality to more users.

**Comment by braver** [comment]
Please let us know if things worked out with LineJumper.

**Comment by kapitanluffy** [comment]
> Please let us know if things worked out with LineJumper.

Will do. I contacted the author 👍

**Comment by braver** [comment]
Looks like the answer to [your question](https://github.com/hypebeast/LineJumper/issues/1) is "no" 😄. Feel free to proceed with a replacement of the existing entry with yours.

**Comment by kapitanluffy** [comment]
> Looks like the answer to [your question](https://github.com/hypebeast/LineJumper/issues/1) is "no" 😄. Feel free to proceed with a replacement of the existing entry with yours.

Oh, this has been out of my radar. Yeah, tried reaching out but he did not reply. What should I do to proceed?

**Comment by braver** [comment]
The cleanest thing to do is remove the existing entry for LineJumper, and add "LineJumper" to the previous_names of your package (example: https://github.com/wbond/package_control_channel/pull/8875/files#diff-2b7dc45bc94d46ab4847d3281d04dac17d5f228e762a8491333857d6ca7cc6d2R455). Also ensure your package has a version higher than the last one for LineJumper (1.0.0). This effectively replaces that with yours and will upgrade existing users to the latest version of your package. Bonus points for adding an upgrade message ([docs](https://packagecontrol.io/docs/messaging)) telling those users what happened.

**Comment by kapitanluffy** [comment]
Ok. Got it. I will close this for now. I will add the highlighting feature from linejumper and reopen this PR.

**Pull request closed without merging**
