### PR TITLE
[Add] CriticMarkup package

### PR DESCRIPTION
**Pull request by Kristinita**
1. link to repository: **<https://github.com/Kristinita/CriticMarkup>**,
2. link to tag page: **<https://github.com/Kristinita/CriticMarkup/releases>**,
3. tests: `Ran 7488 tests in 0.362s` — `OK`.

Thanks.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Dependencies and packages are separate concepts. You can only depend on dependencies, not on packages. Refer to the docs.

It woud be nice if your readme explained what this package actually provides.

**Comment by Kristinita** [comment]
@FichteFoll, are there methods automatically install «package» as a «dependency»?

I know [**Local Packages**](https://packagecontrol.io/packages/Local%20Packages) package, users can automatically add Package Control packages, if they have `.sublime-local-dependency` file. See [**example**](https://github.com/Kristinita/CriticMarkup/blob/master/CriticMarkup.sublime-local-dependency) for a CriticMarkup. But users must install Local Packages for this effect.

Is it possible install Local Packages as a dependency? Other methods?

Thanks.

**Comment by FichteFoll** [comment]
You *can* directly invoke Package Control's interal API or the `advanced_install_package` command, although I would normally not suggest doing that and instead prompting the user to install these packages from within your plugin code when they are not available.

**Comment by Kristinita** [comment]
> You can directly invoke Package Control's interal API or the advanced_install_package command

@FichteFoll , where I can to see, how is implemented contributors of Sublime Text packages? I don't find real examples( .

Thanks.

**Comment by Kristinita** [comment]
@spywhere, is it possible to realize that behavior?

1. Package contributor may [**add Local Packages as dependency**](https://github.com/wbond/package_control_channel/pull/6116/files#diff-d7f2b64139092c24db0f8253007c33cbR3234).
2. If package contributor add to package repository file [**sublime-local-dependency**](https://github.com/Kristinita/CriticMarkup/blob/master/CriticMarkup.sublime-local-dependency), all packages, are added in `sublime-local-dependency` file, will be installed automatically for users.

Thanks.

**Comment by spywhere** [comment]
@Kristinita Sadly no. Local Packages only look for `.sublime-local-dependency` file in the top-most folders opened. It will not even look into subfolder of any top-most folder. So, Local Packages does not even find the files outside what user opened.

Feel free to ask me again if the answer is vague or not relevant.

**Comment by FichteFoll** [comment]
@Kristinita refer to the Package Control source code.

**Comment by FichteFoll** [comment]
@Kristinita ping

**Pull request closed without merging**
