### PR TITLE
Add Writer Color Scheme

### PR DESCRIPTION
**Pull request by tonsky**

### CODE REVIEW

**Comment by tonsky** [comment]
BTW is there a way to exclude screenshots/specimens/tests from the Github repo when package is packaged? Something like `.gitignore`, but for sublime packages hosted on Github?

**Comment by rwols** [comment]
Yes. Use a `.gitattributes` to define what you want to ignore while running `git archive` (which is what Package Control runs). Example: https://github.com/jisaacks/GitGutter/blob/master/.gitattributes

**Comment by braver** [comment]
Pretty cool! FYI, you can also change color scheme in syntax specific settings, e.g. if you want to use this color scheme just for Markdown.

**Comment by tonsky** [comment]
Thanks @braver! I realised it a little too late, but yes, it works too

**Pull request merged**
