### PR TITLE
Add Caddyfile Syntax package

### PR DESCRIPTION
**Pull request by mholt**
This adds [Caddyfile syntax](https://caddyserver.com/docs/caddyfile) highlighting to Sublime. This is my first Package Control submission. Thanks for your review!

### CODE REVIEW

**Comment by mholt** [comment]
Hmm, there's a v1.0 tag. How do we get it to re-run the checks?

**Comment by jakebathman** [comment]
To re-run, you can either push another commit to your forked `master` branch, or close this PR and re-issue it.

**Comment by FichteFoll** [comment]
@jakebathman please do not recomment to re-submit pull requests, since this is redundant. The checks run automatically when an issue is re-opened or a commit is pushed.

Additionally, the JSON can also be checked when pasted on this page: https://packagecontrol.io/test_repo.

**Comment by jakebathman** [comment]
Well the issue I and others seem to have (or at least the question on how to proceed) is when the only warning is about a tag, and wouldn't require a code change and commit to the branch. 

So I guess official guidance is to just close & re-open the PR? 

I completely agree, reducing redundant PRs is optimal.

**Comment by FichteFoll** [comment]
To my knowledge, no checks on the actual package are run if a properly formatted tag can't be found.

We'll see if we can do something about making it more obvious for submitters to have the checks re-run without DoS'ing the server in the meantime.

**Comment by jakebathman** [comment]
Cool, sorry for the trouble! I'd recommend either adding some instruction to the packagecontrol-bot response, or on the [wiki page](https://github.com/packagecontrol/st_package_reviewer/wiki/Package-checks), on how to proceed.

**Pull request closed without merging**
