### PR TITLE
Add Hover Image Preview package.

### PR DESCRIPTION
**Pull request by alvesjtiago**
Link to code repo: https://github.com/alvesjtiago/hover-preview
Link to tags page: https://github.com/alvesjtiago/hover-preview/tags

### CODE REVIEW

**Comment by joshua-golub** [comment]
@alvesjtiago, what assumptions do you make in order to determine that the item being hovered is a viewable image?

-Josh

**Comment by alvesjtiago** [comment]
@joshua-golub, for now the assumptions to determine if it is an image are as follows:

- checking between single quotes, double quotes or parentheses
- images must be of type ```.jpg```, ```.gif``` or ```.png```
- the search is performed taking into account files inside the project folder
- the image returned is the first that matches the filename

**Comment by FichteFoll** [comment]
Great idea to use the "new" APIs like this.

**Comment by alvesjtiago** [comment]
Thank you @FichteFoll 🙂

**Pull request merged**
