### PR TITLE
Add pegasus data language (PDL) syntax package.

### PR DESCRIPTION
**Pull request by jpbetz**
- https://github.com/jpbetz/PegasusDataLanguage
- https://github.com/jpbetz/PegasusDataLanguage/releases/tag/v1.0.0

- Uses `"tags": true`
- Tests run?  Yes:

```
...
  ----------------------------------------------------------------------
 Ran 7614 tests in 0.383s
  
  OK
```

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

**Comment by wbond** [comment]
@jpbetz Could you update the PR to limit this to version >= 3092 since it is using .sublime-syntax?

**Comment by deltaidea** [comment]
FYI, the repo [jpbetz/PegasusDataLanguage](https://github.com/jpbetz/PegasusDataLanguage) no longer exists.

**Comment by wbond** [comment]
@jpbetz Can you confirm if you want this closed?

**Pull request closed without merging**
