### PR TITLE
Add StoryToJasmine package

### PR DESCRIPTION
**Pull request by gallegogt**
SublimeText plugin for BDD that retrieves a Story from Pivotaltracker
and inserts it to the current document as a jasmine spec.

### CODE REVIEW

**Comment by wbond** [comment]
You'll probably want to rename `plugin.py` in your root folder. The reason for this is that it is a generic name, and in Sublime Text 2, packages are loaded in such a way that this plugin will be added to `sys.modules` as just `plugin`. `story_to_jasmine.py` would be far less likely to conflict.

**Comment by FichteFoll** [comment]
You didn't push a new tag for the latest changes yet, so they won't be installed.

Please also use a consistent indentation style.

**Comment by FichteFoll** [comment]
@gallegogt ping

**Comment by gallegogt** [comment]
@FichteFoll Hi, this plugin have some problem?

**Comment by FichteFoll** [comment]
@gallegogt, no, not the package itself. Please address the inconsistent indentation style in this pull request.

**Pull request closed without merging**
