### PR TITLE
Plugin VN IME - VNI

### PR DESCRIPTION
**Pull request by 88d52bdba0366127fffca9dfa93895**
Gõ tiếng Việt trên Sublime Text 3 - kiểu gõ VNI

### CODE REVIEW

**Comment by FichteFoll** [comment]
Since I don't know what this package actually does, how does it compare to the original one? Does it provide different functionality entirely or is it just an addition?

**Comment by yehnkay** [comment]
ya, it's contain some function to help user when type vietnamese language
in sublime text 3

2015-01-15 4:09 GMT+07:00 FichteFoll <notifications@github.com>:

> Since I don't know what this package actually does, how does it compare to
> the original one? Does it provide different functionality entirely or is it
> just an addition?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/3954#issuecomment-69992369>
> .
>



-- 
______________________________________________________

*Vũ Mạnh Tú *
*Sdt* : 01634861670
*Email* : glmanhtu@gmail.com

**Comment by FichteFoll** [comment]
That doesn't really answer my question.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Welcome back, yehnkay. Should we work together and improve your plugin?

**Comment by yehnkay** [comment]
ofcourse :)

2015-01-15 14:11 GMT+07:00 tuanta <notifications@github.com>:

> Welcome back, yehnkay. Should we work together and improve your plugin?
>
> On 01/15/2015 06:55 AM, yehnkay wrote:
> > ya, it's contain some function to help user when type vietnamese language
> > in sublime text 3
> >
> > 2015-01-15 4:09 GMT+07:00 FichteFoll <notifications@github.com>:
> >
> > > Since I don't know what this package actually does, how does it
> > compare to
> > > the original one? Does it provide different functionality entirely
> > or is it
> > > just an addition?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/wbond/package_control_channel/pull/3954#issuecomment-69992369
> >
> > > .
> > >
> >
> >
> >
> > --
> > ______________________________________________________
> >
> > *Vũ Mạnh Tú *
> > *Sdt* : 01634861670
> > *Email* : glmanhtu@gmail.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/wbond/package_control_channel/pull/3954#issuecomment-70016775
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/3954#issuecomment-70048053>
> .
>



-- 
______________________________________________________

*Vũ Mạnh Tú *
*Sdt* : 01634861670
*Email* : glmanhtu@gmail.com

**Comment by FichteFoll** [comment]
Did you manage to solve this?

**Comment by yehnkay** [comment]
Sr. It's long time I don't change anything in this plugin and someone has
name's tuana was forked and improved this plugin. I think it's better than
me

2015-02-13 21:56 GMT+07:00 FichteFoll <notifications@github.com>:

> Did you manage to solve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/3954#issuecomment-74265462>
> .
>



-- 
______________________________________________________

*Vũ Mạnh Tú *
*Sdt* : 01634861670
*Email* : glmanhtu@gmail.com

**Pull request closed without merging**
