### PR TITLE
Add Theme - Aurora

### PR DESCRIPTION
**Pull request by expalmer**

### CODE REVIEW

**Comment by FichteFoll** [comment]
This is a Color Scheme, not a theme. Please update name and labels.

**Comment by expalmer** [comment]
Done! Thanks.

**Comment by FichteFoll** [comment]
Your instructions for activating the scheme are wrong by the way.
The real menu item is `Preferences -> Color Scheme -> Aurora Color Scheme -> Aurora`.

**Comment by expalmer** [comment]
Ah OK, I will update now! Thanks

**Pull request merged**
