### PR TITLE
Update o.json

### PR DESCRIPTION
**Pull request by oytunistrator**
Olang Support added to github.com.
Other documents: http://o-lang.tk/

### CODE REVIEW

**Comment by evandrocoan** [comment]
@oytunistrator, you need to create a tag as `1.0.0` on your repository. See this link for more information:

1. https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

**Comment by oytunistrator** [comment]
Recheck please. Added 1.0.0 tag.

**Comment by FichteFoll** [comment]
Your base scope should begin with either `text` or `scope` and then have syntax-specific suffix, i.e. `source.olang.plain`. All other scope names should then probably end in `olang`, i.e. `onstant.comments.olang`.

**Comment by FichteFoll** [comment]
@oytunistrator ping

**Pull request closed without merging**
