### PR TITLE
Adding ProjectCompletions plugin

### PR DESCRIPTION
**Pull request by bordaigorl**
Simple plugin to add completions from a `completions` key in the current project file.

### CODE REVIEW

**Comment by bordaigorl** [comment]
(apologies for the failed PRs)

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

**Comment by bordaigorl** [comment]
Yes I knew that but I thought you would have liked a cleaner history :wink: thanks for merging!

**Comment by FichteFoll** [comment]
You can also squash and force-push ;)

**Pull request merged**
