### PR TITLE
Add Chrome Syntax package

### PR DESCRIPTION
**Pull request by mapsiter**
Syntax theme mimicking Chrome Developer Tools

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please name your package "Chrome Color Scheme", which matches ST terminology.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by math2001** [comment]
Could you add a demo to your `readme`?

**Comment by mapsiter** [comment]
Please review!

**Comment by FichteFoll** [comment]
You still need to update this pull request with the new name (and url).

[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
Now you need to fix package order ;)

**Comment by FichteFoll** [comment]
@mapsiter ping

**Pull request merged**
