### PR TITLE
Grocery Crud Snippets

### PR DESCRIPTION
**Pull request by asrul10**
Snippets auto crud http://www.grocerycrud.com

### CODE REVIEW

**Comment by FichteFoll** [comment]
`package-metadata.json` is supposed to be created by Package Control on instalation and not provided by you. Please remove it.

**Comment by asrul10** [comment]
Ok, i'am done :+1:

**Comment by FichteFoll** [comment]
You didn't push a tag though. It has to appear here: https://github.com/asrul10/grocery_crud_snippets/tags

**Comment by asrul10** [comment]
finished

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by asrul10** [comment]
ops my bad, ok done it

**Pull request merged**
