### PR TITLE
Added DevSkim to repository metadata.

### PR DESCRIPTION
**Pull request by scovetta**
Please provide the following information:

 - Link to your code repository:
[https://github.com/Microsoft/DevSkim-Sublime-Plugin](https://github.com/Microsoft/DevSkim-Sublime-Plugin)
 - Link to the tags page with at least one [semver](http://semver.org) tag:
[https://github.com/Microsoft/DevSkim-Sublime-Plugin/tags](https://github.com/Microsoft/DevSkim-Sublime-Plugin/tags)

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
-- Report for DevSkim-Sublime-Plugin ------------------

= Repository checks =

No failures

No warnings

= Package checks =

Reporting 3 failures:
- The binding ['ctrl+shift+d'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap
- The binding ['super+shift+d'] unconditionally overrides a default binding
    File: Default (OSX).sublime-keymap
- The binding ['ctrl+shift+d'] unconditionally overrides a default binding
    File: Default (Linux).sublime-keymap

Reporting 1 warnings:
- '.no-sublime-package' is defined. Please verify that it is *really* necessary

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by FichteFoll** [comment]
Furthermore, I suggest basing synax mappings on base scope names instead of the path to a syntax definition, i.e. `view.match_selector(0, "source.js")` for JavaScript. Alternatively, you can base this on the position of some text in the view and even match inline JavaScript in HTML (replacing the `0`).
From a quick audit, I'm not exactly sure what you use `applies_to_ext_mapping` for, though. If it's for linting files that are in the project but not open, then relying on scopes obviously won't help.

**Comment by scovetta** [comment]
Thanks for the feedback, @FichteFoll -- the package has been updated based on the items above:

- The `.no-sublime-package` file has been removed.
- The key bindings were changed to `ctrl-shift-g`.
- I paired down the `applies_to_ext_mapping` to the minimal set needed -- it's still needed to help with linting code that syntax highlighting isn't installed for (e.g. PowerShell), but the change make things a bit cleaner and more flexible.

Thanks again!!

**Comment by FichteFoll** [comment]
## Report for DevSkim-Sublime-Plugin ##################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 1 failures:
- unable to load `messages.json`
    File: messages.json
    Exception: Expecting property name enclosed in double quotes: line 5 column 1 (char 111)

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

Hint: `messages.json` must not have trailing commas.

**Comment by scovetta** [comment]
Thanks again, @FichteFoll -- package has been fixed.

**Comment by FichteFoll** [comment]
Unfortunately, your latest commit (https://github.com/Microsoft/DevSkim-Sublime-Plugin/commit/a4ae4c6bc74e65c0f1ddddea97c9f5a862a2d65a) is not contained in any tag, which means Package Control will not install the fixed version. Once you pushed a new tag with that commit, we are ready to go.

**Comment by scovetta** [comment]
@FichteFoll Thanks again -- tagged as [0.2.1](https://github.com/Microsoft/DevSkim-Sublime-Plugin/releases/tag/0.2.1).

**Pull request merged**
