### PR TITLE
added All Files Autocomplete

### PR DESCRIPTION
**Pull request by PSeitz**
AllFilesAutocomplete Plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/All%20Autocomplete ?

**Comment by PSeitz** [comment]
The plugin is dead - e.g. unmerged, uncommented pullrequest from 29 Dec 2013.

**Comment by FichteFoll** [comment]
I see that @alienhard hasn't made any contributions in the past year, but he commented only two months ago. Hopefully he will see this.

@alienhard, I suggest you to look for a maintainer for your ST package, such as @PSeitz or any other you find trustworthy. Your package apparently is one of the top 25 installed packages and it would be a waste to not have all these users be able to receive updates from some entity. If you don't care about it, we can just make the package entry point to a different repository.

I will wait for a responds for approximately 2 weeks and see what I will do then.

**Comment by alienhard** [comment]
It's true that I haven't put much work into this project for a while. I have also become more careful merging people's merge requests as there have been some that negatively affected lots of people. Since this plugin is used daily by so many people it's important to be cautious.

I'll go through the list of open issues this week to check out recent submissions and bug reports.

@PSeitz is there a particular change you vote to get integrated?

**Comment by PSeitz** [comment]
Yes, the pull request which adds the filename to the list
https://github.com/alienhard/SublimeAllAutocomplete/pull/29

**Comment by alienhard** [comment]
BTW, @PSeitz, the change you suggested to merge is in now.

**Comment by FichteFoll** [comment]
So, I take it this has been solved?

**Comment by PSeitz** [comment]
Yes

**Pull request closed without merging**
