### PR TITLE
Update s.json

### PR DESCRIPTION
**Pull request by Enteleform**
Added SublimeSlides:

Easily create slide presentations in Sublime Text with SublimeSlides
Also includes a file launcher to quickly open media files during your presentation

This is my first plugin release, please let me know if you have any feedback on the plugin or the way I set it up in the repository!

### CODE REVIEW

**Comment by FichteFoll** [comment]
Interesting idea.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Your name does not qualify: https://packagecontrol.io/docs/submitting_a_package#Step_2

**Comment by Enteleform** [comment]
@FichteFoll 

Thanks : )
I added a remote via UnifiedRemote since you commented, check it out @ README.md!

I don't quite understand what I actually have to do to implement semantic versioning.  I'm new to GitHub & this is the first thing I'm releasing.

The link you posted seems to outline usage guidelines, but I didn't see anything actionable.

I'd probably set this @ 0.0.1, as I still have to do some testing on other ST versions & OS's.

**Comment by FichteFoll** [comment]
@Enteleform unfortunately, tests are failing now. Please take a look.

It doesn't really matter if you are complying to the versioning restrictions of SemVer with regards to API (which would mostly be settings and commands for ST packages), but it is recommended. What is required is the format however, so that PC can reliably extract the correct tags from your repository.

Glad you found what you were searching for. :smile: Thank you for the kind words.

**Comment by Enteleform** [comment]
@FichteFoll 

I updated `s.json` & it appears that the tests are passing now ( I was 1 entry out of order )

I think I've added a tag (maybe?)
Is this what you meant by pushing a tag?:
[GitHub - Creating Releases](https://help.github.com/articles/creating-releases/)

**Comment by Enteleform** [comment]
@FichteFoll 

Is everything good to go with this as far as PackageControl requirements go?

**Comment by FichteFoll** [comment]
Yes, all good. I have just been really busy.

**Comment by Enteleform** [comment]
@FichteFoll 

Awesome, thanks!

**Pull request merged**
