### PR TITLE
Rename Otto to Boxy

### PR DESCRIPTION
**Pull request by oivva**
Due to unrelated meaning of `Otto` in some languages I've been forced to change the theme name. Starting from now it is `Boxy`! It's short, memorable and inspired by gift boxes.

### CODE REVIEW

**Comment by oivva** [comment]
Also I already informed users about renaming and breaking changes caused by it.

**Comment by michaelblyons** [comment]
To the best of my understanding, this passes all the relevant tests of the [Review Guidelines][rg] for a package change:

- [x] [Old url][old] redirects to the [new one.][new]
- [x] Has "Previous Names" in the new package definition.
- Additionally, there is information about the change in the ReadMe and in the release notes of the existing package.

[rg]: https://github.com/wbond/package_control_channel/wiki/Pull-Request-Review-Guidelines#reviewing-a-package-change
[old]: https://github.com/oivva/otto
[new]: https://github.com/oivva/boxy

**Comment by oivva** [comment]
@FichteFoll, sorry for the ping, but I think you skipped this pr, because #5499 & #5501 were closed. Many users are waiting for it, especially newcomers from [Best Sublime Text 3 Themes of 2015 and 2016](https://scotch.io/bar-talk/best-sublime-text-3-themes-of-2015-and-2016). I'll push 2.0.0 tag, right after closing this pr.

**Comment by FichteFoll** [comment]
Yes, I skipped this package indeed because your comment 7 days ago disrupted my workflow, which is based on github.com/notifications and crawling that from latest update to newest. It appears that you made the comment shortly before I reviewed a larger batch of packages, thus causing the PR to be moved to the beginning of the queue rather than the end where it should have been.

Sorry for that.

**Pull request merged**
