### PR TITLE
add Prettierd Format

### PR DESCRIPTION
**Pull request by smastrom**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

There are no packages like it in Package Control.

Repo: https://github.com/smastrom/sublime-prettierd-format

### CODE REVIEW

**Comment by braver** [comment]
Thanks!

Would the existing [Fmt](https://packagecontrol.io/packages/Fmt) package also be able to support prettierd? That might be beneficial to users because it already supports a lot of configuration and has implemented the behaviors and tested them across many use cases. It would also make maintenance a bit easier in the long run.

In any case, your settings should be accessible via the main menu.

**Comment by smastrom** [comment]
Hi @braver, yes prettierd works with Fmt. This is how it can be configured:

```json
{
   "rules": [
      {
         "selector": "source.ts",
         "cmd": [
            "prettierd",
            "--stdin-filepath",
            "$file"
         ],
         "format_on_save": true,
      }
   ]
}
```

The only gotcha seems to be that rules must be entered manually for each scope.

When I recently started using Sublime, I struggled to find a way to format files faster using prettier. I had no luck searching the forum, googling or browsing issues that I ended up discovering prettierd and building this plugin.

For this reason, I doubt any novice user can discover Fmt and the above integration easily.

I think it would be great to have a straightforward solution directly in Package Control by just typing `prettier`. 

I've added the menu settings and an installation message that informs that `prettierd` should be installed on the machine in order to use this plugin.

**Comment by smastrom** [comment]
Hi @braver, thank you for your feeback.

Yes prettierd works with Fmt. This is how it can be configured:

```json
{
   "rules": [
      {
         "selector": "source.ts",
         "cmd": [
            "prettierd",
            "--stdin-filepath",
            "$file"
         ],
         "format_on_save": true,
      }
   ]
}
```

The only gotcha seems to be that rules must be entered manually for each scope.

When I recently started using Sublime, I struggled to find a way to format files faster using prettier. I had no luck searching the forum, googling or browsing issues that I ended up discovering prettierd and building this plugin.

For this reason, I doubt any novice user can discover Fmt and the above integration easily.

I think it would be great to have a straightforward solution directly in Package Control by just typing `prettier`. 

I've added the menu settings and an installation message that informs that `prettierd` should be installed on the machine in order to use this plugin.

**Comment by braver** [comment]
> The only gotcha seems to be that rules must be entered manually for each scope.

I guess that's how it works, but of course you can combine scopes in the selector (e.g. "source.ts, source.js" should work). 

It might be worth to add your example here to the documentation of Fmt, so that users who need multiple formatters, or are savvy with packages like that can use that. In the end it's better for users (because of overall quality of the package, consistency across multiple similar formatters, etc) if functionality is combined in to a higher level package like Fmt. Similar to SublimeLinter for instance.

That said, I'm not 100% against a specific package like yours, just trying to advocate collaborating on these things rather than creating more and more of the same (as is usually typical of open source development). 

> I've added the menu settings and an installation message that informs that prettierd should be installed on the machine in order to use this plugin.

👍🏻

**Pull request merged**
