### PR TITLE
add ilorem snippet

### PR DESCRIPTION
**Pull request by imasood**
Simple snippet for insert lorem ipsum in sublime text.
this snippet written for english/persian language

### CODE REVIEW

**Comment by imasood** [comment]
please check my snippet.

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by imasood** [comment]
i change "branch": "master" to "tags": true and use tags for my repo.
please check it.
thanks

**Comment by imasood** [comment]
when ilorem package will add to packagecontrol?

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by imasood** [comment]
finally, i add semantic version tag. you can now check it(v1.0).
thanks

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by imasood** [comment]
semantic version add to repo(v1.0.0)

**Comment by imasood** [comment]
thanks for accept my snippet.
i have a question.
for any update of my snippet i must send pull request?
it is yes your answer please recheck my repository and review version 1.0.1

**Comment by FichteFoll** [comment]
No, you only need to push a new tag with a higher precedence (for example 1.0.1, as you mentioned) to the repository. Package Control will then automatically find the update within an hour.

**Comment by imasood** [comment]
i'll update labels plz check my fork.
thanks

**Comment by FichteFoll** [comment]
Please file a new pull request when changing labels.

**Pull request merged**
