### PR TITLE
Add dateutil dependecy for PlainTasks

### PR DESCRIPTION
**Pull request by vovkkk**
https://github.com/vovkkk/sublime-dateutil
https://github.com/vovkkk/sublime-dateutil/releases

cc @aziz

### CODE REVIEW

**Comment by joshua-golub** [comment]
@vovkkk, I am reviewing this package but don't quite understand the value that it provides to the Sublime Text user. Would you please elaborate in your README file?

**Comment by vovkkk** [comment]
I believe my readme contains all needed information; it is for developers who want to use dateutil module in their package(s)

I guess you are not familiar with dependencies in PC, my readme contains link to docs https://packagecontrol.io/docs/dependencies

**Comment by FichteFoll** [comment]
I agree that the readme is more than enough.

However, I suggest to use an in-repo `dependencies.json` file for specifying dependencies since that will allow updating the dependencies along with new releases instead of having to update the channel.

**Comment by vovkkk** [comment]
> use an in-repo dependencies.json file for specifying dependencies since that will allow updating the dependencies along with new releases instead of having to update the channel.

I do not understand.
I have experience of adding dependencies #5658 and I do know how version update works; there is no need to update channel. Dependency will be updated in case it has new version _and_ package that depends on it has new version.

Surely, once this pr will be merged I will add dependencies.json file to repo for manual installation.

I hope that setting dependency in channel will allow to avoid restart ST after installation (if it is not this way then it could be in future), i.e. when user install PlainTasks then PC can see dependency right away install it, load it, and then install and load PT.

**Comment by FichteFoll** [comment]
>Dependency will be updated in case it has new version and package that depends on it has new version.

I meant that the *package* update can change the dependencies it uses along when its code is updated as well.

>Surely, once this pr will be merged I will add dependencies.json file to repo for manual installation.

When specifying a package's dependencies in the channel, its `dependencies.json` file will be ignored.

>I hope that setting dependency in channel will allow to avoid restart ST after installation (if it is not this way then it could be in future), i.e. when user install PlainTasks then PC can see dependency right away install it, load it, and then install and load PT.

Dependencies are always installed before the package (I myself made sure of that).

**Comment by vovkkk** [comment]
I’ve made change you suggested.

> When specifying a package's dependencies in the channel, its dependencies.json file will be ignored.

That’s disappointing and non-intuitive, TBH.

**Pull request merged**
