### PR TITLE
ADD RPG Maker MV Snippets set

### PR DESCRIPTION
**Pull request by jomarcenter-mjm**
this package is a ported version that was requested by a rpg maker community member from a visual studio version https://marketplace.visualstudio.com/items?itemName=MJMCreativeWorksAndIdea.rmmvpluginsnippet

my apologies with the spam, new here!

### CODE REVIEW

**Comment by FichteFoll** [comment]
Tab triggers can't contain spaces and shouldn't contain punctuation (like `@`) either because ST doesn't handle them well. Please make the tab triggers ASCII letters only.

**Comment by FichteFoll** [comment]
@jomarcenter-mjm ping

**Comment by FichteFoll** [comment]
There is no 1.1.0 tag on https://github.com/jomarcenter-mjm/RMMVSublimeSnippet/tags.

**Comment by jomarcenter-mjm** [comment]
@FichteFoll 1.1.0 Have been tested and finalized, a 1.1.0 tag have been put up.

**Pull request merged**
