### PR TITLE
Add Interactivity package

### PR DESCRIPTION
**Pull request by ichichikin**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is Interactivity.
This plugin allows you to run shell commands and scripts directly within the editor, providing their output right alongside your written content, making your workflow more dynamic and interactive.

### CODE REVIEW

**Comment by kaste** [comment]
Not gonna lie, that looks good (lgtm).   I think the configuration is a bit awkward. E.g. you have
```
"text_shortcuts": "@ -> ##param##\n@@ -> chat4(r\"\"\"##param##\"\"\")",
```
and I wonder why that isn't just a mapping `prefix: command`.  E.g. `{"@": "##param##"}`.  I'm also not  sure how I would define a command that runs Node instead of python.  Or how I could add my own function, e.g. instead of `chat4`.  Also `##param##` looks unfamiliar (instead of, e.g., `$param` or `${param}`) but that maybe makes sense in your context.

**Comment by kaste** [comment]
Ah, the entry here, add it sorted case-insensitive.

**Comment by ichichikin** [comment]
@kaste I'm glad that you liked the package. I made changes to settings management as you suggested. 

Regarding `##param##`, I intentionally picked this unusual syntax to reduce the chance of interference with any possible REPLs.

For interacting with Node, please try these settings:

```json
{
    "append_output": "",
    "environment_variables": {},
    "lines_to_suppress": 2,
    "output_filter": "^>\\s(?:\\.\\.\\.\\s)*",
    "prepend_output": " ",
    "shell": "node",
    "shell_params": [
        "-i"
    ],
    "shutdown_commands": ".exit",
    "startup_commands": "",
    "text_shortcuts": {
        "@": "##param##"
    }
}
```

If you want to add custom functions in Python, please follow these [steps](https://github.com/ichichikin/sublime-plugin-interactivity/?tab=readme-ov-file#custom-functions).

I'd be glad if you commit any useful modules for Node as well.

**Comment by ichichikin** [comment]
@kaste thank you for sharing your ideas!

I didn't want to overload the plugin too much, but I like your idea of accessing different shells simultaneously. I will consider this functionality for future releases.

I've added all the necessary files to my repository.

**Comment by kaste** [comment]
Check the sorting https://github.com/wbond/package_control_channel/pull/8922#issuecomment-2174334550

**Comment by ichichikin** [comment]
@kaste, it looks like I'm missing something here. Could you please tell me more about what exactly should be sorted case-insensitively?

**Comment by kaste** [comment]
Then entries in `i.json` should be sorted by name.

**Comment by ichichikin** [comment]
@kaste, got it, thanks! Done.

**Comment by kaste** [comment]
@braver I think that LGTM.

**Comment by braver** [comment]
@kaste , thanks, your help here is really appreciated 👍🏻

**Pull request merged**
