### PR TITLE
Add ScalaScript package

### PR DESCRIPTION
**Pull request by KimBurgess**
- Link to your code repository:
https://github.com/ciasia/sublime-scalascript

 - Link to the tags page with at least one [semver](http://semver.org) tag: 
https://github.com/ciasia/sublime-scalascript/releases

### CODE REVIEW

**Comment by joshua-golub** [comment]
@KimBurgess, there are a bunch of other Scala packages (for example, [this one](https://packagecontrol.io/packages/Scala%20Syntax)). What does your package offer over and above those others?

-Josh

**Comment by KimBurgess** [comment]
@joshua-golub thanks for checking!

This ones a syntax for [ScalaScript](https://docs.scala.com/display/D1102/The+ScalaScript+Language), the declarative language used by the [Scala digital signage platform](http://scala.com/). If you think the name clash is confusing here, try jumping on their forums...

**Comment by FichteFoll** [comment]
`.sublime-syntax` support has been added with build 3092. Please adjust your version selector accordingly.

**Comment by KimBurgess** [comment]
@FichteFoll nice catch! Updated.

**Pull request merged**
