### PR TITLE
Add PHPMe package

### PR DESCRIPTION
**Pull request by eghojansu**
This plugin is developed based on PHP Companion. 
This plugin add some functionality which does not exists on PHP Companion.
- Generate getter and setter
- More flexible when generate constructor
- Support multiple cursor.
- Support class/interface parent tree

### CODE REVIEW

**Comment by Thom1729** [comment]
Is this a superset of PHP Companion? Is this functionality that could reasonably be added to PHP Companion without creating a new package?

**Comment by FichteFoll** [comment]
Yes, please consider submitting a pull request to PHP Companion first so that all users of that package can profit from the new features.

If @erichard doesn't have enough time to maintain the package anymore, maybe they'd add you as a contributor or would have the package transferred to you (on Github or just here on the channel)?

If you consider it to be too different of a package, I can live with that, but I'd like you to consider this first.

cc @erichard

**Comment by erichard** [comment]
New features are welcomed in PHP Companion :+1:

**Comment by eghojansu** [comment]
Hey, have you try PHPMe yet? The code and functionality is very different than PHP Companion, but if you like that, i can try to merge fit my project with PHP Companion.

**Comment by FichteFoll** [comment]
@erichard please comment on @eghojansu's question.

**Comment by erichard** [comment]
@eghojansu You say PHPMe is based on PHP Companion and code and features are different, but I think the goal is the same. Both package try to ease our daily work and they share many features.

I think PHP developers should have only one package to install and PHP Companion already have a strong userbase.

We just have to agreed on an implementation and a set of feature. I have no problem to consider a big refactoring of PHP Companion if needed, we just have to avoid BC break. I even can promote you as a maintener of PHP Companion, there is some challenging features requests waiting :smile: 

Feel free to contact me to discuss this further.

**Comment by eghojansu** [comment]
@erichard let's work together on this, I'll open issue on php companion repo.

@FichteFoll thanks for noticing, you can remove this PR , thank you

**Pull request closed without merging**
