### PR TITLE
Added Python pexpect dependency

### PR DESCRIPTION
**Pull request by varp**

### CODE REVIEW

**Comment by varp** [comment]
@wbond @FichteFoll hey guys. Are there some problems with merging this?

**Comment by varp** [comment]
@wbond please review this

**Comment by FichteFoll** [comment]
https://pypi.python.org/pypi/pexpect doesn't mention support for Python 2.6, which is used by ST2. Did you check whether it works on ST2? If not, just restrict the dependency to ST3 only (and rename the `all` folder to `st3`).

**Comment by varp** [comment]
You were right. The pexpect could not work with ST2. I've made required change in both repos.

**Pull request merged**
