### PR TITLE
add PyCrypto dependency

### PR DESCRIPTION
**Pull request by jlegewie**
Currently only compiled for osx.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You only have `st3_osx_x64/Crypto` so I suppose this should be for `"platforms": ["osx-64"]`.

**Comment by jlegewie** [comment]
Done.

**Comment by FichteFoll** [comment]
My bad, `osx-x64` it is.

**Comment by jlegewie** [comment]
Okay, back to "osx" and I squashed the commits to keep this clean...

**Comment by FichteFoll** [comment]
Why back to "osx"? It's clearly not available for osx-x86.

I mean it's not too big of a deal since the worst thing to happen is that, if specified, Package Control just installs the dependency for osx-x86 and it just does nothing, but an actual error would certainly be better.

**Comment by jlegewie** [comment]
I guess I got confused. I thought Travis chocked on `osx-64` and didn't see the `x`. Now it should be fine.

**Comment by wbond** [comment]
Just for the record, there is no ST3 OS X x86. There is a just a single OS X version, and it is 64bit: http://www.sublimetext.com/3.

**Comment by FichteFoll** [comment]
Well ... TIL I guess.

**Pull request merged**
