### PR TITLE
Add new package "Git Blame Status Bar"

### PR DESCRIPTION
**Pull request by rodrigobdz**
Shows Git blame author for the currently selected line.

### CODE REVIEW

**Comment by Thom1729** [comment]
I see that this is partly derived from the [Git blame](https://github.com/psykzz/st3-gitblame) package. Would it make sense to add this feature to that package rather than creating a new package?

**Comment by rodrigobdz** [comment]
@Thom1729 I thought about it but decided to publish a new package instead to offer a minimalistic solution to a common problem.
[Git Blame](https://github.com/psykzz/st3-gitblame) sure offers more functionality but IMO it has a different goal than [Git Blame Status Bar](https://github.com/rodrigobdz/subl-gitblame-statusbar).

**Comment by rodrigobdz** [comment]
[Git Blame Status Bar](https://github.com/rodrigobdz/subl-gitblame-statusbar) has an approach comparable to the one of the VSCode Extension [Active File In Status Bar](https://github.com/RoscoP/ActiveFileInStatusBar).
Minimal solution to a simple problem.

**Comment by Thom1729** [comment]
- You should explicitly handle the case where the file is not in a git repo.
- Generally, ignoring errors is not ideal.
- You should throttle multiple activations to avoid performance problems.

What I would do myself is separate the code into a `TextCommand` that does all of the real work and a `ViewEventListener` that invokes that command. I'd also add some sort of timeout to prevent the listener from activating the command too frequently.

**Comment by Thom1729** [comment]
@rodrigobdz ping.

**Comment by rodrigobdz** [comment]
@Thom1729 I haven't forgotten this open PR. I haven't got around to it yet.

**Pull request closed without merging**
