### PR TITLE
Added Craft Development Snippets

### PR DESCRIPTION
**Pull request by alecritson**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push version tags to your repo, otherwise Package Control won't find a release.

**Comment by alecritson** [comment]
Thanks for the heads up! I've added a version tag

**Comment by FichteFoll** [comment]
Okay, but it has to be a semantic version (or at least be in the format of that) which requires three number parts.

**Comment by alecritson** [comment]
okay sure, i've updated the tag :)

**Pull request merged**
