### PR TITLE
Added SublimeGerrit

### PR DESCRIPTION
**Pull request by borysf**
Added back SublimeGerrit, now as open source on GitHub.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Related issue: #3887

Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

Furthermore, since your last released version was `1.0.11` from when you were hosting this on your own, you should push a higher one.

**Comment by borysf** [comment]
Ready to merge

**Comment by wbond** [comment]
You can delete the `readme` key since Package Control will automatically find that file from the `details` key.

**Comment by borysf** [comment]
@wbond done!

**Pull request merged**
