### PR TITLE
add package named by SublimeHydra

### PR DESCRIPTION
**Pull request by iamfredng**
this is a Sublime plugin of Lua

### CODE REVIEW

**Comment by FichteFoll** [comment]
I don't particularly see a reason for this to not be available for Linux. I assume you just didn't test it there? It shouldn't be a problem to allow linux users to install this as well.

**Comment by iamfredng** [comment]
I don't have Linux. So I not sure it work for Linux.

**Comment by FichteFoll** [comment]
I can assure you that this will work just fine on Linuxs. I don't have access to all the different OSes either, but since Python is cross-platform you will be fine, as long as you are't doing platform specific stuff which this does not seem to do.

**Comment by iamfredng** [comment]
Ok. I will add Linux platform to My setting.  Thanks a Lot.

**Comment by FichteFoll** [comment]
I just noticed it, but your package violates our [naming policies](https://packagecontrol.io/docs/submitting_a_package#Step_2).

**Comment by FichteFoll** [comment]
@iamfredng ping

**Comment by iamfredng** [comment]
Can I just change my package name and repush?
I want the new package named LuaSimpleComplete, Is OK?

**Comment by iamfredng** [comment]
@FichteFoll I rename the old plugin to LuaSimpleComplete

**Comment by FichteFoll** [comment]
Technically that is all that was necessary, but practically your latest commit seems to have caused a merge conflict with current `master`. Please fix the conflict by squashing and rebasing.

**Comment by iamfredng** [comment]
@FichteFoll Thanks for removed the stale label. The conflict is fixed.

**Comment by FichteFoll** [comment]
"merged" separately

**Pull request closed without merging**
