### PR TITLE
Add TSL package

### PR DESCRIPTION
**Pull request by polygoat**
This package adds syntax highlighting and a build system for TSL, a text scraping language for intuitive processing of text files, offering basic data cleanup and normalization tasks to non-programmers.

### CODE REVIEW

**Comment by polygoat** [comment]
The package _does_ contain a LICENSE file though

**Comment by Thom1729** [comment]
It looks like you need to release a new tag.

**Comment by Thom1729** [comment]
`sys.path` is shared between the entire plugin runtime, so you shouldn't modify it. Instead, use relative imports (`from .TSLCore import TaskRunnerCore`).

**Comment by polygoat** [comment]
Thanks, @Thom1729 !

**Comment by Thom1729** [comment]
What's the purpose of this bit at the bottom of TSL.py?

```py
if len(sys.argv) > 1:
	taskFileName = sys.argv[1]

	TSL = TaskRunner(taskFileName)

	TSLPlugins = glob('tsl-plugins/*.py')

	if len(TSLPlugins):
		for TSLPlugin in TSLPlugins:
			exec(open(TSLPlugin, 'r', encoding='utf8').read())
	
	if TSL.task:
		print('Running "%s"...\n' % taskFileName)
		TSL.run()

else:
	print()
```

**Comment by polygoat** [comment]
@Thom1729 I haven't had the chance to document this yet, but this just opens up the ability for auto-discovery & running of TSL plugins in the future

**Comment by Thom1729** [comment]
Sublime will execute that code when the module is loaded, but it doesn't look like it would make sense within the plugin runtime. For instance, `sys.argv` won't generally exist, and `glob` isn't likely to find anything under Sublime's working directory. In addition, `exec`-ing unknown modules in the plugin runtime seems dangerous.

**Comment by polygoat** [comment]
Hi @Thom1729. Please note that so far the script was run through Python externally, so sys.argv would've been populated by Sublime calling the shell command `python TSL.py $filename`. The working directory would be the file from which the build is called. But I have refactored this to be a proper plugin and use Sublime's internal Python engine instead. Please see version `1.2.0`. I have also removed the code that just execs, as it isn't needed at this point and I agree with your concerns.

**Pull request merged**
