### PR TITLE
Added Tagger Script Syntax

### PR DESCRIPTION
**Pull request by phw**
See also http://forums.musicbrainz.org/viewtopic.php?id=5652

### CODE REVIEW

**Comment by FichteFoll** [comment]
Out of curiousity, is this the same syntax that is also used in foobar2000 and http://www.mp3tag.de/en/index.html?

I've wanted to create a proper syntax for that for a while (3 years to be exact) but eventally lost sight of it.

**Comment by phw** [comment]
I'll update the tag.

The foobar2000 syntax was the basis for Picard's scripting, so this should work in general. However I don't know foobar 2000 well enough to be sure there is no difference. Give it a try ;)

**Comment by phw** [comment]
I've updated the tag

**Comment by FichteFoll** [comment]
Well, the current syntax is pretty minimalistic so I'm sure it will work just fine. I had a more advanced one with deprecation warnings even and different highlighting for generally known tags (e.g. `%artist%`). I know that foobar supports `%album artist%` however, which your definition doesn't match currently.

**Comment by phw** [comment]
> I know that foobar supports %album artist% however, which your definition doesn't match currently.

No, than this is one of the minor differences between Picard and foobar. If I find the time I would like to extend this syntax, maybe it could even offer variations for foobar and MP3tag.

Thanks for the quick merging :)

**Pull request merged**
