### PR TITLE
Add October Twig Highlighter package

### PR DESCRIPTION
**Pull request by daftspunk**
This package is structurally identical to the Laravel Blade Highlighter package.

Hope I did everything correctly.

<3

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your `packages.json` file doesn't do anything more than what directly specifying the package in one of the `repository/*.json` files with a `"tags": true` key in the release would do. Please re-consider listing the package information along with the other packages so that we can potentially mass-update it in the future.

**Comment by FichteFoll** [comment]
Your `messages.json` contains a trailing comma and is invalid.

You might also want to check out the testing section at http://www.sublimetext.com/docs/3/syntax.html

**Comment by daftspunk** [comment]
Fixed `messages.json`. Unsure how to follow the other instructions. This package has been refitted directly from [another package](https://github.com/Medalink/laravel-blade/). Is it because this is a legacy package that it uses redundant options?

**Comment by FichteFoll** [comment]
Providing your own `packages.json` file has informally been deprected since instructing PC to check your repository's tags does almost everything you would have wanted to do manually before automatically. Refer to https://github.com/wbond/package_control/blob/master/example-repository.json for details (also explains redundant keys).

**Comment by FichteFoll** [comment]
@daftspunk ping

**Comment by daftspunk** [comment]
Hey, could you point me to a similar and more modern package that I can copy instead?

**Comment by FichteFoll** [comment]
Uhm, any package listed in any of the files in https://github.com/wbond/package_control_channel/tree/master/repository that specifies `"tags": true`?

**Comment by daftspunk** [comment]
Going with [Abaqus](https://github.com/SenhorLucas/AbaqusSublimePackage) as the basis moving forward. Cheers.

**Comment by daftspunk** [comment]
All done, revised this PR and [ditched the legacy approach](https://github.com/daftspunk/october-twig/commit/fcc507dcd50d26828faed87077f6265f8875beab). How are we looking?

**Comment by FichteFoll** [comment]
All right, looking much better. However, because `.sublime-syntax` has only been made available with build 3092, you should specify that as the minimum version (via `"sublime_text": ">=3092").

**Comment by FichteFoll** [comment]
@daftspunk ping

**Comment by daftspunk** [comment]
This has been fixed. Thanks

**Comment by FichteFoll** [comment]
Okay, now you just need to push a new tags with all your recent changes and we're finally good to go.

**Comment by daftspunk** [comment]
Done in v1.0.1

**Pull request merged**
