### PR TITLE
Added Hybris Impex Syntax to repository/h.json

### PR DESCRIPTION
**Pull request by Blumed**
Thank you.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by Blumed** [comment]
Thanks @FichteFoll. I have made the necessary changes. Anything I need to change? I have never done this before. What happens next?

**Comment by FichteFoll** [comment]
Yes, you have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by Blumed** [comment]
I believe I did what you wanted me to do. Just to be clear only needed to
add the release data to my repo and didn't need to add any versioning to my
h.json file correct?

**Comment by FichteFoll** [comment]
I'm quite sure there was no tag on the repo when I checked last time, but there is now.

However, [semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by Blumed** [comment]
I changed it to 1.0.0 for the initial launch. Sorry for the miss.

**Comment by Blumed** [comment]
Thank you for your help :)

**Comment by Blumed** [comment]
When might I be able to use the plugin from package control? I would like to be able to announce this to my team.

**Comment by Blumed** [comment]
never mind I see it in there. Thanks again for your help!

**Pull request merged**
