### PR TITLE
Terminal in packages

### PR DESCRIPTION
**Pull request by Proyecto513**
Package addition

### CODE REVIEW

**Comment by FichteFoll** [comment]
1. Won't work in ST2 because `print` is a statement there and does not have a value.
2. I'm also a bit confused about `"{}".format(self.command)`, it makes no sense.
3. Instead of running the change directory command inside the terminal it's better to give a working_dir parameter to Popen.
4. It's better to access settings when they are used, not for example when a command is instantiated (as I don't actually know when that happens) because this will assure that the current setting is read live and is not outdated.

**Comment by Proyecto513** [comment]
I'm really amazed by the thought that you read all the code in the packages, but it's nice to know that somebody cares about the quality of them.

I just pushed a commit :smiley:

**Comment by FichteFoll** [comment]
Alright, looks good.

**Comment by FichteFoll** [comment]
... almost.

Your tags must be valid [semantic versions](http://semver.org) (with optional leading `v`). And you also didn't push one for the latest changes.

**Comment by geekpradd** [comment]
You are using global variables in your code. Can't you just pass TERMINAL as a parameter to CommandThread?

**Comment by Proyecto513** [comment]
Just pushed another one

**Pull request merged**
