### PR TITLE
Cmder for Sublime Text

### PR DESCRIPTION
**Pull request by exiahuang**
Cmder for Sublime Text run customer command, `Cmder for Sublime Text` run any command. You can use it to run any os command, such as python, java, ruby, go, c, c++, github, docker, heroku, etc.

### CODE REVIEW

**Comment by exiahuang** [comment]
add MIT LICENSE.

**Comment by exiahuang** [comment]
I have update a new version of my plugin. I have made new [tag](https://github.com/exiahuang/Cmder/releases/tag/v1.0.1).

**Comment by Thom1729** [comment]
Does this differ substantially from other command-running packages?

**Comment by exiahuang** [comment]
@Thom1729 There are many different with others command-running packages.
This Plugin can custom `input` textare and `select` menu, custom context menu and side bar many.
Use this plugin , you can integrated with any program language, such as python, java, ruby, go, c, c++, etc. Also , you can integrated with platform, such as github, docker, heroku , ect.

I am updating the document of this plugin. [Document](http://salesforcexytools.com/Cmder/)
Integrated with [Hexo Blog](http://salesforcexytools.com/Cmder/cmder-hexo/)
Integrated with [Express and heroku](http://salesforcexytools.com/Cmder/cmder-express/)
Integrated with [Docker](http://salesforcexytools.com/Cmder/cmder-docker/)

I have build a [salesforce plugin for sublime](https://packagecontrol.io/packages/SalesforceXyTools) before, I want to give up the old one and use this new plugin to develop the salesforce develop and share to everyone who is developing salesforce.

Look forward to your favourable reply, Thank you.

**Comment by exiahuang** [comment]
@Thom1729 I will look forward to your response.

**Comment by FichteFoll** [comment]
I guess this is different enough to the existing packages, should one ever feel they need it. I lost track of them long ago anyway.

Why do you set the Java syntax for your "console", though?

**Pull request merged**
