### PR TITLE
add fewest moves plugin

### PR DESCRIPTION
**Pull request by oyyq99999**
This is a plugin for Rubik's Cube Fewest Moves practising using an editor, more powerful functions are upcoming.

### CODE REVIEW

**Comment by Thom1729** [comment]
The 'notation.fm' scope is not standard. What about `constant.other.fm`? And is there really a need for an accompanying color scheme?

If you're not supporting Sublime Text 2, there's not much point in supporting builds before 3092, because the 3.0 final release was build 3143. Rather than adding the `.tmLanguage`, I'd just declare support for `"sublime_text": ">=3092"`.

**Comment by Thom1729** [comment]
It looks like `FewestMovesEventListener` is running the `count_moves` command every single time any view is modified. This should only apply to views using the Fewest Moves syntax.

**Comment by oyyq99999** [comment]
I have set it to run only when the syntax is fewest moves, see [here](https://github.com/oyyq99999/sublime_fewest_moves/blob/0.2.3/fewest_moves.py#L102-L103)

**Comment by Thom1729** [comment]
Fair enough. It might be clearer to explicitly check for that in the listener, although I'm not aware of concrete advantages to doing so.

Another thing I noticed: the keymap doesn't check the scope either. Even if the command is not enabled, I think that the keymap will eat the keystroke, possibly interfering with other syntax-specific bindings.

**Comment by oyyq99999** [comment]
Added syntax checks for keymap and eventlistener

**Pull request merged**
