### PR TITLE
Remove Grunt package

### PR DESCRIPTION
**Pull request by tvooo**
This PR removes the Grunt package (https://github.com/tvooo/sublime-grunt), which is no longer maintained. If someone is willing to pick up maintenance, I'm happy to hand it over; it can then be re-added to Package Control.

### CODE REVIEW

**Comment by Thom1729** [comment]
Is it necessary to actually remove the package?

**Comment by tvooo** [comment]
It seems to be working for some people still, but I get a bug report every once in a while that I'm not intending to address... along with comments from people complaining about that very fact.

**Comment by Thom1729** [comment]
If you really want to remove it, I'll do that. But I don't think it's doing any harm just sitting there. I'd recommend opening an issue declaring that the package is no longer maintained and asking if anyone wants to take it over.

**Comment by Thom1729** [comment]
@tvooo Do you still want to remove this package?

**Comment by tvooo** [comment]
Thanks, let's leave it in for now.

**Comment by FichteFoll** [comment]
When the amount of issues (for some reason) becomes unbearable, you can set your repository to read-only. That should be clear enough to everyone.

**Pull request closed without merging**
