### PR TITLE
added Black Rain color scheme

### PR DESCRIPTION
**Pull request by ginfuru**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by ginfuru** [comment]
@FichteFoll - thanks reverted the previous PR and resubmitted with the changes you wanted to see. Let me know if there is anything else that needs to happen.

**Comment by ginfuru** [comment]
@FichteFoll Thanks for the merge -- when does one see it inside of package control?

**Comment by FichteFoll** [comment]
Probably due to https://github.com/wbond/package_control_channel/issues/5283.

**Comment by ginfuru** [comment]
@FichteFoll :+1: Thanks!

**Pull request merged**
