### PR TITLE
update u.json

### PR DESCRIPTION
**Pull request by maxleungcode**
Dear 
To compare Unity3D Shader Highlighter and Snippets ,We are increase VF model function  compeletes and parameter tips,like this "ShadeVertexLights(float4_vertex,float3_normal)  "

### CODE REVIEW

**Comment by FichteFoll** [comment]
How is this different from https://packagecontrol.io/packages/Unity3D%20Shader%20Highlighter%20and%20Snippets?

**Comment by maxleungcode** [comment]
to compare  https://packagecontrol.io/packages/Unity3D%20Shader%20Highlighter%20and%20Snippets
We are increase VF model function compeletes and parameter tips,like this "ShadeVertexLights(float4_vertex,float3_normal) "

**Comment by maxleungcode** [comment]
https://packagecontrol.io/packages/Unity3D%20Shader%20Highlighter%20and%20Snippets this plugin a lot of function is not complete

**Comment by FichteFoll** [comment]
What about proposing pull request to @petereichinger's package to improve it further and not split development into two branches?

**Comment by petereichinger** [comment]
Hey I agree with @FichteFoll two packages for Syntax Highlighting of Unity Shaders seems redundant :). How about we incorporate your features into my package?

**Pull request closed without merging**
