### PR TITLE
Add Exalt

### PR DESCRIPTION
**Pull request by eerohele**
A plugin for wrangling XML.

### CODE REVIEW

**Comment by FichteFoll** [comment]
The name "Markup" seems a bit too general to me since you are "only" validating and formating the XML (and SGML) family, which is quite a limited subset of all the markup languages. I suggest finding a different name that is more specific.

**Comment by eerohele** [comment]
That's fair enough.

I suppose the name doesn't have to be too "literal". Would you accept "Exalt"? For, uh... "**X**ML v**al**idation and forma**t**ing".

**Comment by FichteFoll** [comment]
Sounds good to me. Just make sure to include all those keywords in the description so that they are searchable on packagecontrol.io.

**Comment by eerohele** [comment]
Renaming done.

**Pull request merged**
