### PR TITLE
move to SublimeText repo

### PR DESCRIPTION
**Pull request by randy3k**
two things.

1. specified UnitTesint information here rather than https://github.com/randy3k/sublime_packages/blob/master/packages.json#L190-L204

2. moved `sublime-pyzmq` and `sublime-pywin32` to ~SublimeText~ packagecontrol as discussed below

### CODE REVIEW

**Comment by randy3k** [comment]
once it is merged, I will remove the reference in https://github.com/randy3k/sublime_packages/blob/master/packages.json#L190-L204

**Comment by FichteFoll** [comment]
You could also move your dependencies to https://github.com/packagecontrol/ if they don't really need maintenance. I can add you to that. That's certainly not a requirement, just an idea to group PC-specific dependencies in a separate repo.

**Comment by randy3k** [comment]
@FichteFoll I moved [pyzmq](https://github.com/SublimeText/sublime-pyzmq) a
and [pywin32](https://github.com/SublimeText/sublime-pyzmq) to SublimText. Could you move them to packagecontrol too? (I have lost the admin rights of them)

**Comment by FichteFoll** [comment]
Right, I forgot to add them to you when I received the "new repo" notification (I have to grant the rights manually). Will do.

**Comment by FichteFoll** [comment]
Okay, deps are moved and you have admin access on them again.

However, you cannot switch from explicit versioning to branch-based. You must use tag prefixes for your st2 release channel.

**Comment by randy3k** [comment]
Do I need to tag a different prefix for st3? How PC determine the latest release?

**Comment by FichteFoll** [comment]
>Do I need to tag a different prefix for st3? 

No, if you set it to `true`, PC will look for no prefix or a `v` prefix, which is then stripped automatically.

**Pull request merged**
