### PR TITLE
Adding yii2 auto-complete

### PR DESCRIPTION
**Pull request by udokmeci**
Added yii2 auto-complete

### CODE REVIEW

**Comment by udokmeci** [comment]
Adding yii2 auto-complete

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@udokmeci ping

**Comment by udokmeci** [comment]
@FichteFoll sorry for late return.

**Pull request merged**
