### PR TITLE
new status bar file path package

### PR DESCRIPTION
**Pull request by kushalhalder**

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://github.com/unphased/SublimeStatusbarPath provides a *very* similar feature, but the package is only marked to support ST2 (which it does not since the code is definitely compatible).

I suggest adding features to @unphased's package and adjusting the version restriction in the channel here.

**Comment by FichteFoll** [comment]
@kushalhalder ping

**Comment by kushalhalder** [comment]
I'll do that.

**Comment by FichteFoll** [comment]
@kushalhalder any update?

**Pull request closed without merging**
