### PR TITLE
Added Architect language syntax

### PR DESCRIPTION
**Pull request by ryanblock**
### Checklist 

- [x] Local tests passed
- [x] Used `tags: true`
- [x] Have a `readme.md`
- [x] No other similar packages exist

### About

Hey there! I'm one of the maintainers of [OpenJS Architect](https://arc.codes) ([GitHub @architect](https://github.com/architect), [npm @architect](https://www.npmjs.com/package/@architect/architect)), a framework for building powerful full-stack serverless web apps on AWS.

In addition JSON and YAML manifests, Architect also features its own lightweight, minimal syntax for declaratively deploying infrastructure-as-code. [A little bit more about the format here.](https://arc.codes/docs/en/guides/get-started/project-layout)

I wish I'd written this Sublime Text syntax definition a long time ago! Unfortunately it wasn't until the last couple of weeks that I was able to abstract all that regex and make everything reasonably maintainable for the rest of the Architect community.

Anyway, thanks!

### CODE REVIEW

**Comment by ryanblock** [comment]
FYI: I usually specify the license in `package.json` instead of adding duplicative filesystem cruft, but since it appears to be a consideration here, I've added a license file for good measure: https://github.com/architect/sublime-package/blob/main/LICENSE

**Comment by braver** [comment]
If you're concerned about maintainability you'll also want to convert your files to the new yaml "sublime-syntax" type. There is a convertor built into Sublime Text. Besides being more readable and flexible syntaxes using the new system are also more performant.

**Comment by ryanblock** [comment]
Thanks! I'll open an issue, not sure when I'll have a chance to get to it but that sounds like a good idea.

**Comment by braver** [comment]
Unless you have a wildly exotic syntax the conversion tool does all the work and it shouldn’t take more than a minute or two.

**Comment by ryanblock** [comment]
Is this a blocker for approval? If so, why?

**Comment by ryanblock** [comment]
Now that I'm back at my desk, to add a bit more context: anything that requires a human (e.g. me) to do something manually on their local machine and publish is not desirable. There are multiple maintainers and anything we ship to customers should be able to be published via CI. Maybe that's possible with the Sublime conversion tool, idk, but as I mentioned before, not sure when I'll have a chance to get to research that, and as things stand everything works to the best of my knowledge.

**Comment by braver** [comment]
> Is this a blocker for approval?

Not directly but we do look at your willingness and ability to maintain the package you submit. This is a really small effort, so if that’s a problem for you then that’s a problem.

As soon as your package is admitted into package control all tags will be picked up and published automatically.

**Comment by ryanblock** [comment]
Alright, and your thoughts on the potentially negative impacts of ostensibly forcing manual, local steps into what should otherwise be an automated, deterministic package publishing process?

**Comment by braver** [comment]
I really have no idea what you’re talking about. Just convert the syntax files and tag a new release, what’s the big deal?

**Comment by ryanblock** [comment]
> I really have no idea what you’re talking about.

I'm talking about publishing releases via CI, as opposed to a person taking manual steps on their local machine to produce a build artifact for each release (which is what it sounds to me like you're asking that we do). What am I misunderstanding?

**Comment by braver** [comment]
No the conversion is a one step thing you do only once. The result file with the sublime-syntax extension you “git add”, the old tmLanguage file you “git rm”, Bob’s your uncle. Just try it.

**Comment by ryanblock** [comment]
Right! And the next time (and every future time) we publish a bug fix to our language syntax, we have to (manually) run that conversion again, yes?

**Comment by braver** [comment]
No you threw away the old file and can now continue to edit the new sublime-syntax file and be more productive.
Maybe you should just try it and report back afterwards.

**Comment by ryanblock** [comment]
Today, Architect generates and publishes our TextMate grammar from here: https://github.com/architect/syntaxes/blob/main/src/textmate.js It works, is actively maintained, and [fully-tested](https://github.com/architect/syntaxes/blob/main/test/example.arc.snap) with semver [releases](https://github.com/architect/syntaxes/runs/3594429388?check_suite_focus=true).

This TextMate grammar is then able to be automatically be published as plugins/extensions for VS Code, Atom, Sublime Text, TextMate, and Shiki (which we use for syntax highlighting on our site https://arc.codes), among others.

It sounds a lot like y'all are asking us to now create and maintain a separate, Sublime-only syntax definition apart from our main syntax definition, and to manually publish it (whereas all our other extensions / plugins can be deterministically published via CI).

This feels like make-work. We are happy and excited to maintain our Sublime Text extension via the TextMate Grammar, as hundreds of other authors currently do.

**Comment by braver** [comment]
Well you didn’t tell me that and it’s not in the readme, so I didn’t know. Of course if that’s your workflow the tmLanguage format is a good compromise. Could’ve told me earlier and saved us both a lot of time, but at least we’re talking about the same thing now. You can always improve that pipeline later and future proof your Sublime Text support by also outputting towards the yaml format. For now though, let’s ship this thing.

**Comment by ryanblock** [comment]
Wonderful, thanks!

How we publish this package would not have been in the readme, as the readme is used by Package Control for end-user consumption. This project depending on a grammar file built and published by another repo was clearly visible in the project's [package.json](https://github.com/architect/sublime-package/blob/main/package.json).

Additionally, you never asked why we did anything the way we did; you took up a position on how you seem to prefer to see syntax definitions be published, despite multiple comments where I explained that we publish our software via CI/CD. I'm really not sure how the onus was on me here.

Re. the yaml format, if at any point y'all can point us at a conversion utility that can be run from a command line / via CI, I'd be happy to incorporate that into our build process and output it automatically instead of the current tmLanguage format. Thanks again.

**Pull request merged**
