### PR TITLE
Insert package ng-snippets

### PR DESCRIPTION
**Pull request by alsfurlan**
Package referenced a AngularJS Snippets

### CODE REVIEW

**Comment by FichteFoll** [comment]
Since your package does not seem to have a specific target audience, it would be preferrable to have an English readme.

Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

Finally, how exactly are your snippets different to:
https://packagecontrol.io/packages/AngularJS%20Snippets
https://packagecontrol.io/packages/AngularJS
and why can't you add them to one of these packages?

**Comment by alsfurlan** [comment]
Hello,
I do read me in English as you said and change the branches of nomenclature.

So the difference between my snippet and these two packages is the syntax, as they follow a pattern of code, my follow the Angular Style Guide developed by John Pope, which is quite different.

A example of the Factory Functions:

AngularJS Snippets: 
factory('name', [function () {
	return {
	};
}])

My snippet:
(function() {
	'use strict';

	angular
	  .module('module')
	  .factory('NameFactory', NameFactory);

	NameFactory.$inject = ['dependencies'];

	function NameFactory(dependencies) {
		//content
	}
})();

**Comment by FichteFoll** [comment]
Okay. You still need to push a tag and change the release strategy to tags though.

**Comment by FichteFoll** [comment]
@alsfurlan ping

**Comment by alsfurlan** [comment]
@FichteFoll I followed the procedure. I hope to be okay now.

**Comment by FichteFoll** [comment]
You need to update package order: https://travis-ci.org/wbond/package_control_channel/builds/60273649#L138

**Comment by alsfurlan** [comment]
How i update my project? I check the order e it's ok.

**Comment by FichteFoll** [comment]
The remote repository probably changed and your change can't be merged correctly anymore. I suggest to retry on a new branch that you branch off upstream/master.

**Pull request closed without merging**
