### PR TITLE
adds fight-color-scheme package

### PR DESCRIPTION
**Pull request by ghyatzo**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **

My package is ...

There are no packages like it in Package Control.

My package is similar to ... However it should still be added because ...

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
You should add a README to explain your package to users. And for a color scheme it's really helpful to put a screenshot in there: what it looks like is basically the only thing that matters ;)

**Comment by ghyatzo** [comment]
Oh duh. I forgot to push it, will do. Thanks.

**Comment by braver** [comment]
@ghyatzo please ping me when you've done so, so that we can merge this.

**Comment by ghyatzo** [comment]
Yes I am sorry. Got sidetracked with a million things. Tomorrow I will have some free time.

**Comment by ghyatzo** [comment]
@braver it's up. Thank you for your patience

**Comment by braver** [comment]
Remember that package control only looks at your tags, so create a new tag whenever you’ve made some changes.

**Pull request merged**
