### PR TITLE
add HBH-KeySearch

### PR DESCRIPTION
**Pull request by hbh112233abc**

### CODE REVIEW

**Comment by hbh112233abc** [comment]
add tag v1.0.0

**Comment by Thom1729** [comment]
Are there other packages that do the same thing?

**Comment by hbh112233abc** [comment]
delete another plugin

**Comment by Thom1729** [comment]
@hbh112233abc I'm fairly sure that there are existing packages that perform a similar function. Is this package substantially different?

**Comment by hbh112233abc** [comment]
> @hbh112233abc I'm fairly sure that there are existing packages that perform a similar function. Is this package substantially different?

this plugin will call default browser and load your selected search engine web to search the keyword of your selected at sublime text; you could add more search engine web url at setting config

**Comment by FichteFoll** [comment]
I really don't think we need this.

* [WebSearch - Packages - Package Control](https://packagecontrol.io/packages/WebSearch "WebSearch - Packages - Package Control")
* [OnlineSearch - Packages - Package Control](https://packagecontrol.io/packages/OnlineSearch "OnlineSearch - Packages - Package Control")
* [Search Anywhere - Packages - Package Control](https://packagecontrol.io/packages/Search%20Anywhere "Search Anywhere - Packages - Package Control")
* [Internet Search - Packages - Package Control](https://packagecontrol.io/packages/Internet%20Search "Internet Search - Packages - Package Control")

You also have lots of debug prints still in your code

**Comment by hbh112233abc** [comment]
> I really don't think we need this.
> 
> * [WebSearch - Packages - Package Control](https://packagecontrol.io/packages/WebSearch)
> * [OnlineSearch - Packages - Package Control](https://packagecontrol.io/packages/OnlineSearch)
> * [Search Anywhere - Packages - Package Control](https://packagecontrol.io/packages/Search%20Anywhere)
> * [Internet Search - Packages - Package Control](https://packagecontrol.io/packages/Internet%20Search)
> 
> You also have lots of debug prints still in your code

Thank you for your audit. the best plugin of your recommendation is WebSearch

ecommendation |  
-- | --

**Pull request closed without merging**
