### PR TITLE
Dop/map preview

### PR DESCRIPTION
**Pull request by doneill**
This package provides ability to preview spatial map data files in your default web browser on a map. Current supported map formats are GeoJSON & TopoJSON. Open a valid GeoJSON or TopoJSON file and run the Map Preview command from the command pallete, valid files will be parsed and displayed inside users default web browser overlayed a world map.

### CODE REVIEW

**Comment by doneill** [comment]
😕 package has a readme but continue to get warnings, what fix is required?

**Comment by doneill** [comment]
Package has a readme, what can I do to get past the warning and merged?

**Comment by FichteFoll** [comment]
> Package has a readme, what can I do to get past the warning and merged?

The bot downloads your tagged release and only checks that. However, your latest tag contains the readme, so I don't know what's going on there.

**Comment by doneill** [comment]
Interesting as the readme doesn't show up in [package control](https://packagecontrol.io/packages/MapPreview) 🤔

**Comment by wbond** [comment]
It’s because we have the branch name master hardcoded in some code and yours is main.

**Pull request merged**
