### PR TITLE
split phpfmt into two separated packages

### PR DESCRIPTION
**Pull request by ccirello**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Do you know that you can also have this in one package, even though the code is split upon multiple repositories? https://github.com/wbond/package_control/blob/5643f4fa9a335a4591482a8ecdf6e0d7413fbaa1/example-repository.json#L322-L338

**Comment by ccirello** [comment]
Thanks for the suggestion. Gonna do it.

**Comment by ccirello** [comment]
@FichteFoll done - ready to merge

**Comment by ccirello** [comment]
@FichteFoll ping

**Pull request merged**
