### PR TITLE
Added mIRC Scripting Language

### PR DESCRIPTION
**Pull request by eneerge**
This is the first package that provides support for mIRC scripting language syntax highlighting and command autocompletion.

### CODE REVIEW

**Comment by Thom1729** [comment]
It looks like you're not consistently using the `.msl` suffix for scopes.

**Comment by eneerge** [comment]
I have added the missing .msl to the scopes.

**Comment by Thom1729** [comment]
After reviewing the syntax more thoroughly:

- You have a lot of complex, repeated snippets, like giant lists of words. Putting these in variables would make the syntax much, much easier to read.
- You're scoping a lot of whitespace. I'm not sure that's correct.
- You're doing most of the work in giant regexp captures. This is likely to make the syntax difficult to extend, and it often leads to subtle bugs.
- You have several lookbehinds. These are very bad for performance, because they trigger the older, slower regexp engine.
- You're using capture groups in a lot of places where you're not using the result. This is likely to lead to bugs, especially in variables, and it's not great for performance, either.

**Comment by FichteFoll** [comment]
You should definitely try to avoid lookbehinds as they will be detrimental in performance (relative to the other points pointed out by @Thom1729). You *may* get the package merged in its current state since it's pretty much just performance that's lacking, but I want you to acknowledge this and decide on whether you want to improve on it first.

**Comment by eneerge** [comment]
Hello.  At this time, I'm not sure  how I would implement the regex without the lookbehinds.  While testing, I didn't experience any slow downs on my 2600k system.  I will review other highlighters to see if there's an alternative solution.  Since this is the only mIRC syntax highlighter available for Sublime, can we go ahead and merge?

**Pull request merged**
