### PR TITLE
add rx for python

### PR DESCRIPTION
**Pull request by guillermooo**
This adds the rxpy module so that it can be depended on by plugins. All tests for the changed file passed.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your entire repo needs to be wrapped in the folder `st3/rx` so that it becomes importable as `import rx`. See also the documentation: https://packagecontrol.io/docs/dependencies

**Comment by guillermooo** [comment]
Changes made. Hope I got it right this time!

**Comment by FichteFoll** [comment]
Remember to push a new release. :smile:

**Comment by guillermooo** [comment]
Duh... Done now.

**Pull request merged**
