### PR TITLE
Add ExpandSelectionToComments package

### PR DESCRIPTION
**Pull request by timfjord**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

The package expands the current selection to fully enclose the intersecting comment block

- works with multiple cursors
- supports soft undo
- supports comments divided with empty lines
- works with any language that has syntax highlighting

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by rchl** [comment]
As I potential user of this package I would wonder what "Expands the current selection to the nearest comment block" exactly means. The screencast in the repo makes it clear but by just reading the text I would think that it has to do with having cursor outside of the comment block and expanding selecting to touch the comment block from the outside? Not sure.

Would it be more precise to say "Expands the current selection to contain the nearest comment block"?

Also I wonder what happens when cursor is outside of the comment block? Nothing? If so then maybe it can be even more precise: "Expands the current selection to fully enclose the intersecting comment block"?

**Comment by timfjord** [comment]
@rchl I like your suggestion. Thanks.

I've updated the description all over the places

**Comment by braver** [comment]
Looks good and useful. Only thing I'd like to change is the position of your command in the Selection menu... it's a bit lost now. Nothing you can do much about I believe. So, let's ship it.

**Comment by timfjord** [comment]
Woohoo 🎉 
Thanks @braver

**Pull request merged**
