### PR TITLE
Add SmarterLineMoves package

### PR DESCRIPTION
**Pull request by trych**
A Sublime Text package that overrides Sublime's default line swapping to work in a more predictable way and adds additional commands for moving lines of text.

https://github.com/trych/SmarterLineMoves

### CODE REVIEW

**Comment by braver** [comment]
Alright, doesn't always work as smoothly as the default but I can see the value proposition here.

**Comment by trych** [comment]
> Alright, doesn't always work as smoothly as the default but I can see the value proposition here.

Do you mean smoothly in terms of performance? Or in terms of usability? Open for improvement suggestions!

Thanks for merging!

**Comment by braver** [comment]
I especially noticed some stuttering when moving a selection up against the top of the viewport. Although of course in the default implementation most of a multi-line selection moves out of view, it does scroll smoothly. No idea if the API provides any way for you to improve on that though.

**Comment by trych** [comment]
Thanks. Hadn't noticed something like that in my tests, but will keep an eye on it.

**Pull request merged**
