### PR TITLE
Added Devicetree highlighter.

### PR DESCRIPTION
**Pull request by fallrisk**
Here is a link to my code repository: https://github.com/fallrisk/devicetree-highlighter
Here is a link to my tags page: https://github.com/fallrisk/devicetree-highlighter/tags

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

**Comment by fallrisk** [comment]
Does this mean it's going to be merged?

**Comment by fallrisk** [comment]
Is there a reason why "Devicetree DTS..." is not showing up in the package list in Sublime Text?

**Comment by wbond** [comment]
It appears the only release you've made is a pre-release (there is a `-` after the three numeric segments. For someone to install that, they'd have to opt-in to prerelease versions for that packages. My recommendation is to create a `1.0.0` tag and go from there. :smile:

**Comment by fallrisk** [comment]
Ah, thank you @wbond. I apologize. That didn't occur to me. I will make a 1.0 release.

**Pull request merged**
