### PR TITLE
new color scheme

### PR DESCRIPTION
**Pull request by watergear**
Coffee
Desert

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

I highly recommend adding screenshots to your readmes.

**Comment by watergear** [comment]
Tags is finish.
Screenshots is going to be added later.

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by watergear** [comment]
ok, I have updated tags again.

**Pull request merged**
