### PR TITLE
Add: Mongolian Dictionary package

### PR DESCRIPTION
**Pull request by bataak**

### CODE REVIEW

**Comment by bataak** [comment]
Actually it's just spelling dictionary package. But bot is getting an error.

**Comment by braver** [comment]
You seem to have removed the repo. If you want to restart this PR, please let me know.

As for the package file, packaging the plugin is handled by Package control, you should not submit a `.sublime-package` file.

**Comment by FichteFoll** [comment]
It seems the repository exists again. @bataak if you're still interestedm please comment in here, so that we can re-open, or submit a new PR.

**Comment by braver** [comment]
@FichteFoll it has already been managed in a newer PR

**Comment by FichteFoll** [comment]
Sorry about that, don't mind me. 
(And I even went to the PR list to confirm that before commenting and missed it anyway.)

**Comment by braver** [comment]
😂

**Pull request closed without merging**
