### PR TITLE
Add Koto package

### PR DESCRIPTION
**Pull request by irh**
This PR adds the Koto package, providing syntax highlighting support for the [Koto language](https://github.com/koto-lang/koto).

### CODE REVIEW

**Comment by jrappen** [comment]
Current docs:

<https://www.sublimetext.com/docs/syntax.html#ver-dev>

Also you probably want to add tests and use GitHub actions as is done for the default packages shipping with SublimeHQ products:

- <https://www.sublimetext.com/docs/syntax.html#testing:ver-dev>
- <https://github.com/sublimehq/Packages>
- <https://github.com/sublimehq/Packages/tree/master/.github/workflows>
    - target URL will change, but you knew that

**Comment by irh** [comment]
Hi @jrappen, thanks for taking a look but it's not clear to me if there's a problem? You gave me a docs link without describing an issue, then started the next point with 'Also', which makes me think a sentence is missing from your reply.

**Comment by jrappen** [comment]
* Docs link was meant as a replacement for the link you provide in the syntax file at the top.
* No sentence missing, add optional tests if you like. Whatever works for you.

**Comment by irh** [comment]
OK thanks, I've updated the docs link, and I'll consider adding tests next time I need to update the package.

**Pull request merged**
