### PR TITLE
Fixed broken repository url for Base Encoder

### PR DESCRIPTION
**Pull request by rwieckowski**
Configuration is pointing to non existing repository

### CODE REVIEW

**Comment by FichteFoll** [comment]
cc @socsieng

**Comment by FichteFoll** [comment]
Also cc @euphwes, what happened?

**Comment by socsieng** [comment]
@euphwes, did you delete the repository?

**Comment by euphwes** [comment]
Hey all, I goofed. Sorry about that. I was shuffling repos around between accounts which I've set up for different purposes, and my Base Encoder one got lost in the mix.

@socsieng, I'd be happy for yours to be the main one for this project. I saw that you added some additional functionality onto mine (thanks!).

I'll put mine back up today, and link it here when I do. @socsieng, would you like to open a merge request to my repo (can we do that after I accidentally deleted and re-added it?), or would you like to keep your copy as the main one for the project?

Totally up to you, since you have the most up-to-date code, and also you didn't drop the ball...

Thanks,

**Comment by socsieng** [comment]
@rwieckowski, are you okay to close this PR once @euphwes restores the repo to its former location?

@euphwes, you should own the repo. If you no longer have a copy of the source, just grab it from my fork. I can re-fork if the linkage doesn't automatically get applied.

**Comment by euphwes** [comment]
@rwieckowski, @FichteFoll, @socsieng,

I restored my original repo here: https://github.com/euphwes/base-encoder

This is the original URL for this repo, so this should fix the broken link within Package Control.

@socsieng, it looks like you already made a pull request which I merged some time ago. My memory isn't so great... Thanks again for the contribution.

I think we should be good to go now, and can close this without merging.

Thanks again, everybody.

**Comment by FichteFoll** [comment]
Good to hear :+1:

**Comment by poke** [comment]
Hey @euphwes and @socsieng,
sorry to ping you on here but it seems that the repo is gone again and it was removed from the package list in #8844 (though it still [appears on the website](https://packagecontrol.io/packages/Base%20Encoder)).
I see that [Soc’s repository](https://github.com/socsieng/base-encoder) is still available though, so do we want to switch it over to that URL now, or do you want to restore the repo again Wes? 😅

Otherwise, if both of you are not interested in keeping this alive, I would be willing to put up a copy myself and resubmit it as a package.

**Comment by socsieng** [comment]
Feel free to point to my repository.

**Comment by euphwes** [comment]
Hi all,

Thanks for the ping, and sorry for the late reply! I'm not sure what
happened to my original repo, I don't remember closing/archiving it, but
I'm totally fine with you pointing to @socsieng's fork. Thanks for
volunteering! I'm not sure I have enough time these days to actually keep
an eye on the package and maintain it. Let me know if there's anything else
I need to do to properly transition the package to point to @socsieng's
fork.

-Wes

**Pull request closed without merging**
