### PR TITLE
add react-native-snippets

### PR DESCRIPTION
**Pull request by Shrugs**
Adds `react-native-snippets`, a collection of snippets for react native.

https://github.com/Shrugs/react-native-snippets

### CODE REVIEW

**Comment by wbond** [comment]
As mentioned at https://packagecontrol.io/docs/submitting_a_package#Step_4, you can't use "branch": "master" for new packages.

Instead you should use "tags": true and create a tag for each release.

**Comment by Shrugs** [comment]
Whoops, sorry about that. I've fixed the issue and created the v0.1 release [here](https://github.com/Shrugs/react-native-snippets/releases).

Cheers!

**Comment by wbond** [comment]
Tags must be semantic versions, e.g. `0.1.0`

**Comment by Shrugs** [comment]
Ah, sorry about that; first time publishing a package. How's this setup?

https://github.com/Shrugs/react-native-snippets/releases

**Pull request merged**
