### PR TITLE
Added Toggle .only package

### PR DESCRIPTION
**Pull request by CurtisHumphrey**
Toggles ".only" on and off of describe and it for test files in javascript

### CODE REVIEW

**Comment by FichteFoll** [comment]
You cannot use dots in the package's name due to how Python importing works.

**Comment by CurtisHumphrey** [comment]
Are you sure @FichteFoll as I have this installed via add github source and everything has been working fine.  I think the name field was just a pretty print thing.

**Comment by FichteFoll** [comment]
Yes, I am sure. #2524 covers this.

Package Control installs the package under the name specified, i.e. it either calls your package `Toggle .only.sublime-package` or extracts it to a folder named `Toggle .only` (if `.no-sublime-package` is provided, which isn't necessary here). You can try this yourself, as importing the Python plugin will fail.

**Comment by CurtisHumphrey** [comment]
hmm, I see what you are getting at now.  They way I installed it, it use the repo name. Fixing it in just a moment.

**Comment by FichteFoll** [comment]
You'll have to fix the package order after the name change: https://travis-ci.org/wbond/package_control_channel/builds/308559511#L675

**Comment by Thom1729** [comment]
I read through the documentation and I still can't quite tell what this package is for. Some specific unit-testing framework? What framework? Is there an existing package for that framework that may provide similar functionality, or to which this functionality could be added?

You're creating a global keybinding that applies in every scope. If possible, you should add `context` conditions to the binding so that it's only available when you're using the relevant testing framework.

You're only performing the modification on the first selection. You should probably do it on every selection. (This would also handle the case where there is no selection.)

**Comment by FichteFoll** [comment]
I agree with these.

>You're creating a global keybinding that applies in every scope. If possible, you should add context conditions to the binding so that it's only available when you're using the relevant testing framework.

>You're only performing the modification on the first selection. You should probably do it on every selection. (This would also handle the case where there is no selection.)

Please address this feedback before we proceed with the merge.
I don't care which testing framework this is for, but I don't recall having seen a package like this before.

**Comment by CurtisHumphrey** [comment]
So If I understand correctly you would like:
- [ ] Better readme file that says what framework this is for
- [ ] Somehow add context conditions to restrict it to only certain type of files?
- [ ] Allow modification on more than one sections

I did quite a bit of looking but the other packages (ones related to Mocha or Jasmine - both JS testing) seem to all be related to either running the tests or generating templates.  This one doesn't really fit with either as it more a helper for toggle tests on and off that are auto-running in the background somewhere on a file watcher.  I'm not sure how to do the context but I can look it up.

**Comment by FichteFoll** [comment]
>- Somehow add context conditions to restrict it to only certain type of files?
>- Allow modification on more than one sections

These are the important parts here. If you need any help with that, I can guide you towards documentation or an implementation.

**Comment by FichteFoll** [comment]
@CurtisHumphrey ping

**Pull request closed without merging**
