### PR TITLE
Update EditorConfig to use tagged releases

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by braver** [comment]
Branch based releases are deprecated. Now would be a good time to switch to tagged releases.

**Comment by sindresorhus** [comment]
I prefer to keep using branch releases. I don't foresee many updates for any of these.

**Comment by braver** [comment]
Well deprecated here means you will not be able to do branch based releases at some point in the future. We’re not going to accept changes to different branches. If you don’t expect many updates, certainly creating a single tag is also not that big of a problem.

**Comment by sindresorhus** [comment]
Done

**Comment by braver** [comment]
🙏🏻

**Pull request merged**
