### PR TITLE
Added HttpUnit

### PR DESCRIPTION
**Pull request by gaohuia**
Added SimpleHttpRequester

### CODE REVIEW

**Comment by Thom1729** [comment]
Are there other packages that perform a similar task?

**Comment by gaohuia** [comment]
> Are there other packages that perform a similar task?

The answer is YES, but I think SimpleHttpRequester can do better.

https://packagecontrol.io/packages/Http%20Requester

**Comment by Thom1729** [comment]
Would it make sense to improve that package rather than creating a new one?

**Comment by gaohuia** [comment]
> Would it make sense to improve that package rather than creating a new one?

Maybe keep both would be better.  

When people wanna send simple requests, `HttpRequester` would be easy to use, with which even no need to save the request to disk.  If more control is needed or people wanna make something like a document, `SimpleHttpRequester` would be better.

**Comment by gaohuia** [comment]
Hi, just let me know if anything need to add. Looking forward to see it in sublime.

**Comment by FichteFoll** [comment]
>When people wanna send simple requests, HttpRequester would be easy to use, with which even no need to save the request to disk. If more control is needed or people wanna make something like a document, SimpleHttpRequester would be better.

Following this decription, are you sure your package name is appropriate?

Requiring PHP seems like a pretty big downside compared to the other package. Also, because the spawned `php` process needs to access your bundled `.php` file, you must provide a `.no-sublime-package` file to tell PC to unpack your package.

Your `install.py` will get loaded by ST when it most certainly shouldn't. Move it to a subfolder, change its extension, or remove it. (It also uses `sublime` without importing it.)

**Comment by gaohuia** [comment]
Than you, will improve.

**Comment by gaohuia** [comment]
Thank you for your advisement, have done the following changes.

Renamed to HttpUnit. 
Added .no-sublime-package

But I'm not able to get rid of php for now.

**Pull request merged**
