### PR TITLE
add lebab plugin for sublime

### PR DESCRIPTION
**Pull request by inkless**
This is a plugin to use lebab (http://lebab.io/) to convert ES5 code to ES6 code

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

The file name for messages is supposed to be `messages.json`, with an s.

Your code is not comaptible with Python 2 (and thus ST2) because you define "exec" as a function. Please rename the function or adjust the version requirements.

A general Python tip: You should be using modules for namespacing, not classes and staticmethods.

**Comment by wbond** [comment]
- We no longer accept branch-based releases. You'll have to switch to use semver tags.
 - Your keybinding overrides the key binding for splitting a multi-line selection into multiple cursors. Probably best not to provide a key binding and just a command palette entry.

**Comment by FichteFoll** [comment]
@inkless ping

**Comment by inkless** [comment]
@FichteFoll  Thanks for reminding, didn't notice this for a while. 
Just updated as request, please let me know if there's still something not right. :)

**Pull request merged**
