### PR TITLE
added Night Owl color scheme

### PR DESCRIPTION
**Pull request by VonHeikemen**
Adding Night Owl color scheme

### CODE REVIEW

**Comment by VonHeikemen** [comment]
Done. I have created the license file

**Comment by Thom1729** [comment]
The PR has become conflicted (not your fault). If you can fix the conflict, I can merge right away.

**Comment by Thom1729** [comment]
There's one brace out of place (line 502).

**Comment by Thom1729** [comment]
Also, you need to create a new tag.

**Comment by VonHeikemen** [comment]
> There's one brace out of place (line 502).

Sorry. It's fixed.

> Also, you need to create a new tag.

Done.

**Pull request merged**
