### PR TITLE
Add RTL-Mirror

### PR DESCRIPTION
**Pull request by doobleweb**
[https://github.com/doobleweb/RTL-Mirror](RTL-Mirror)

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for RTL-Mirror ##############################

### Repository checks ###

No failures

No warnings

### Package checks ###

Reporting 1 failures:
- The binding ['alt+a'] unconditionally overrides a default binding
    File: Default (Windows).sublime-keymap

No warnings

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

**Comment by doobleweb** [comment]
Changed Binding to Ctrl + F1

**Comment by FichteFoll** [comment]
Don't forget to push a new tag with the recent changes.

**Comment by doobleweb** [comment]
do you mean to release it again with a new tag number? that's what i did.

**Comment by doobleweb** [comment]
Is there anything else i need to do so the plugin will be published?

**Comment by gerardroche** [comment]
I'd recommend squashing and rebasing.

**Comment by kylebebak** [comment]
@doobleweb 
I think what gerardroche is suggesting is that they might be reluctant to merge your pull request because it has 16 commits but it only has changes to 1 file.

You should squash those 16 commits into only 1 commit. Here's how you can do this:

From your repo, run `git remote`, and find the name of the original repo you forked, which is probably __upstream__.

Run `git fetch upstream`, to make sure you have the latest changes to the upstream repo. Then run `git reset --soft upstream/master`. This will make your local master branch point to the latest commit in the upstream repo, but will not delete your changes. Now all you have to do is stage and commit your changes, and run `git push --force`.

Now your remote master branch will only be 1 commit ahead of the upstream master branch. You don't even have to submit a new pull request.

**Comment by doobleweb** [comment]
@kylebebak thanks, you're awesome.

**Comment by FichteFoll** [comment]
Fortunately Github now allows me to squash pull requests when merging, which is what I've been doing basically since it was implemented, so you don't have to squash yourself.

**Pull request merged**
