### PR TITLE
Add Rome Formatter package

### PR DESCRIPTION
**Pull request by marekpiechut**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.

My package is adding support for Rome code formatter for Javascript and Typescript.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Are you familiar with the Fmt package, and would this formatter work with that?

**Comment by marekpiechut** [comment]
> Are you familiar with the Fmt package, and would this formatter work with that?

Hmm, it looks like basic functionality would work. But I think it would not support formatter config and binary auto discovery. Binary can and usually will be in project `.node_modules/.bin` folder and config file has to be exactly under `cwd` for it to be used by binary.

**Comment by braver** [comment]
Yes, I can see how a specific package can have more features like that.

One thing I’d like to change is the key bindings. Because packages can override each other, it’s better if packages don’t ship with their bindings enabled. A common approach is to comment out the bindings, and provide menu and command palette entries that allow users to edit their bindings in split view. It’s then very easy to copy over the binding for your package, and maybe tweak the key combination. That also has the benefit of making the binding easier to remember.

**Comment by marekpiechut** [comment]
You’re right. I think I’ll remove the key biding and just add it to Readme. Most users will probably want to remap it anyway. Give me 15 minutes to create a new release.

**Comment by rchl** [comment]
Maybe also try to clarify the `Dependencies` section which says:

> Plugin needs nothing. If you don't have Rome yet installed: [install instructions]

This seems to contradict itself. Your plugin might not require *ST dependencies* but for casual user this doesn't mean anything and, had it been required, it would be handled automatically anyway.

If we are talking high-level it seems to me like the rome dependency is required.

**Comment by rchl** [comment]
I also see that Rome implements LSP server so this could also be handled as a LSP plugin but we should probably not hold that against this package.

**Comment by marekpiechut** [comment]
> Maybe also try to clarify the `Dependencies` section which says:
> 
> > Plugin needs nothing. If you don't have Rome yet installed: [install instructions]
> 
> This seems to contradict itself. Your plugin might not require _ST dependencies_ but for casual user this doesn't mean anything and, had it been required, it would be handled automatically anyway.
> 
> If we are talking high-level it seems to me like the rome dependency is required.

Yeah, haven't thought about it this way. But you're right, someone might think that Rome itself is included in the plugin. I've updated the readme.

**Comment by rchl** [comment]
It still says "Dependencies: None, Plugin itself has no dependencies,..."

I think this still talks about ST dependencies but, as I said, this wouldn't be relevant to the user even if there would be dependencies because the user wouldn't have to do anything about that anyway -- it would be handled automatically.

I would suggest just treating "rome" as a dependency and make it explicit. Or instead you could name the section "requirements" if you think that "dependencies" is too ambiguous.

**Comment by marekpiechut** [comment]
> It still says "Dependencies: None, Plugin itself has no dependencies,..."
> 
> I think this still talks about ST dependencies but, as I said, this wouldn't be relevant to the user even if there would be dependencies because the user wouldn't have to do anything about that anyway -- it would be handled automatically.
> 
> I would suggest just treating "rome" as a dependency and make it explicit. Or instead you could name the section "requirements" if you think that "dependencies" is too ambiguous.

Updated the readme, hope it makes it more obvious what has to be done. Please check it out.

**Comment by braver** [comment]
Looks good to me!

**Pull request merged**
