### PR TITLE
update sublime text version from >=3000 to >=4000 in Project And workspace Management Plugin

### PR DESCRIPTION
**Pull request by tshrpl**

### CODE REVIEW

**Comment by jrappen** [comment]
There is no public Build 4000.

**Comment by tshrpl** [comment]
so what is the lowest ST4 version?

**Comment by jrappen** [comment]
* `stable` channel: <https://www.sublimetext.com/download>
* `dev` channel: <https://www.sublimetext.com/dev>

**Comment by FichteFoll** [comment]
There may not have been a build 4000, but this selector is still fine.

**Pull request merged**
