### PR TITLE
A Cobalt2 Flat Theme For Use With The Cobalt2 Color Scheme

### PR DESCRIPTION
**Pull request by r3volution11**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please don't change the indentation of `package_control_channel.sublime-project`. You should be using `"detect_indentation": true` in your configuration.

**Comment by r3volution11** [comment]
My fault. Sorry about that. I thought I did have that on.

**Comment by FichteFoll** [comment]
You can just revert the changes, I will squash your commits anyway.

**Comment by r3volution11** [comment]
Ok, thanks for your help. Please let me know if I messed things up again. 5+ years using version control and I've never submitted a pull request before.

**Pull request closed without merging**
