### PR TITLE
Add Ring syntax highlighting package

### PR DESCRIPTION
**Pull request by ysdragon**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **

My package is for supporting Ring syntax highlighting

### CODE REVIEW

**Comment by braver** [comment]
Please handle the bot's feedback:

> 'Ring'] : Packages must be sorted alphabetically (by name)

**Comment by ysdragon** [comment]
Hi @braver, fixed now.

**Comment by braver** [comment]
I’ve only got one final point of feedback: if you add a [scope or file regex](https://www.sublimetext.com/docs/build_systems.html#basic-example) to your build system, you help Sublime automatically select your build system (ie you can run it just by hitting CMD+B), if the current file matches. Users can always select the build system manually as well.

**Comment by ysdragon** [comment]
Fixed in this commit [deb3d6d](https://github.com/ysdragon/ring-sublime/commit/deb3d6d261486730d08f7302e63173ffca4da8f6)

**Comment by ysdragon** [comment]
Hello @braver ,

Why our package marked as `Needs Review`.

**Comment by braver** [comment]
The old [Package Control site](https://packagecontrol.io/packages/Ring) sometimes needs manual verification of packages. We've built a new architecture and [website](https://packages.sublimetext.com/packages/Ring) that doesn't have that problem. I would say don't worry about it, it will get resolved soon.

**Comment by ysdragon** [comment]
> The old [Package Control site](https://packagecontrol.io/packages/Ring) sometimes needs manual verification of packages. We've built a new architecture and [website](https://packages.sublimetext.com/packages/Ring) that doesn't have that problem. I would say don't worry about it, it will get resolved soon.

Thank you! So, does this mean the package will appear in Package Control in Sublime Text again?

**Comment by braver** [comment]
Yes, either the package get's reviewed on the old architecture, or Package Control will switch to the new architecture, whichever happens first.

**Pull request merged**
