### PR TITLE
add Parinfer plugin

### PR DESCRIPTION
**Pull request by oakmac**
[Parinfer](https://shaunlebron.github.io/parinfer/) for Sublime Text :)

### CODE REVIEW

**Comment by FichteFoll** [comment]
You mention that ST3 is not supported, yet this package will be available for installation to ST3 users due to your specified version selector. You might want to clarify this.

**Comment by JoakimLofgren** [comment]
@FichteFoll Support for ST3 should be in place now :P

**Comment by FichteFoll** [comment]
@JoakimLofgren what changed?

**Comment by JoakimLofgren** [comment]
Well basically the compatibility fixes was the following:
* Fix imports in Python 2.x and 3.x
* Change config file to a .sublime-settings file
* Move edits into a TextCommand for ST3

That made it work for me in ST2 and ST3 for Windows.

**Comment by FichteFoll** [comment]
Oh I see now, I was looking at the wrong timestamps.

**Pull request merged**
