### PR TITLE
Added 'Toothpaste' Package

### PR DESCRIPTION
**Pull request by imcatnoone**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

For discovery purposes, I suggest either adding "Color Scheme" to the package name or as a label.

**Comment by imcatnoone** [comment]
@FichteFoll Will do and then create a new PR. Thanks!

**Comment by FichteFoll** [comment]
Please don't. You can append commits to existing pull requests by pushing onto the branch you opened it from.

**Comment by imcatnoone** [comment]
@FichteFoll that's what I meant. Sorry about that.

**Comment by imcatnoone** [comment]
Hey @FichteFoll I've created a release and tagged my repo with versioning (1.0.0) and added `color scheme`to the *t.json* file for better clarity. Please let me know if anything else needs to be done to get it accepted. Thank you!

**Comment by imcatnoone** [comment]
Hey @FichteFoll - Is there anything else that needs doing in order for the commit to be accepted and the theme to be put in package control? Thanks!

**Comment by FichteFoll** [comment]
It seems you have accidentally pushed your custom sublime project file. Please remove the file and squash it into the last commit.

I'm sorry for the delay but I have been really busy lately.

**Comment by FichteFoll** [comment]
@imcatnoone ping

**Comment by imcatnoone** [comment]
Hey I apologize for the delay. I was actually on vacation. Going to tackle this today.

**Comment by FichteFoll** [comment]
@imcatnoone ping

It appears a recent change on the repo caused a merge conflict with this pull request. Please rebase onto current `master`.

**Pull request closed without merging**
