### PR TITLE
Add Pkl (Pickle) syntax highlight

### PR DESCRIPTION
**Pull request by serjan-nasredin**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [ ] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

Documentation: https://pkl-lang.org/

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Hi 👋 

You need to tag a release for this to work.

**Comment by serjan-nasredin** [comment]
Hello @braver 😄! I created a version on my repository: <https://github.com/serjan-nasredin/pkl.tmbundle/releases/tag/v0.0.1>.

**Comment by serjan-nasredin** [comment]
how? I use yaml

**Comment by braver** [comment]
Looks like `pkl.sublime-completions` is an empty file.

**Comment by braver** [comment]
> I don't know yet how to create syntax highlighting like: [JavaScript](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax) (It is very difficult to understand).

Well you picked a really complicated example :) If you want to learn more, the Sublime Text Discord is a great place to ask questions.

**Comment by serjan-nasredin** [comment]
> Looks like `pkl.sublime-completions` is an empty file.

https://github.com/serjan-nasredin/pkl.tmbundle/releases/tag/v0.0.2

**Comment by serjan-nasredin** [comment]
> the Sublime Text Discord is a great place to ask questions.

Can you give me a link? I want to be a member of this server :)

**Comment by braver** [comment]
This should be it: https://discord.com/invite/D43Pecu

**Comment by braver** [comment]
This bit about testing will also be of use, it really helped me build more complicated syntaxes: http://www.sublimetext.com/docs/syntax.html#testing

**Comment by serjan-nasredin** [comment]
@braver thanks you! ❤️

**Pull request merged**
