### PR TITLE
add HTML2CSS

### PR DESCRIPTION
**Pull request by jaxgeller**
add https://github.com/jaxgeller/sublime-html-to-css

Select html with cursor, run from command palette and css class + id selectors get parsed from the html and pasted into your clipboard.

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/packages/CSS%20Primer
https://packagecontrol.io/packages/eCSStractor
?

**Comment by jaxgeller** [comment]
These are good, but I like having it save straight to the clipboard, instead of overwriting files. Also, this works by selecting the content you need, not just the whole file.  But thanks for bringing this up, i appreciate it.

**Comment by FichteFoll** [comment]
Do you think it would make sense to add that kind of functionality to an existing plugin like @hudochenkov's?

**Comment by hudochenkov** [comment]
@jaxgeller, in eCSStractor you can select part you need and only selection will be processed.

Your plugin doesn't work with multiple classes.

I can add “copy to clipboard” option to eCSStractor if you [open issue](https://github.com/hudochenkov/ecsstractor/issues).

**Comment by jaxgeller** [comment]
Going to close this with https://github.com/hudochenkov/ecsstractor/issues/6 . Thanks everyone.

**Pull request closed without merging**
