### PR TITLE
Inspr

### PR DESCRIPTION
**Pull request by wzhix**
Link to the code repository: https://github.com/wzhix/inspr
Link to the tags page: https://github.com/wzhix/inspr/releases

### CODE REVIEW

**Comment by wzhix** [comment]
Is there something wrong with my pull request?

**Comment by math2001** [comment]
Could you write your `readme` in English please?

You have trailing commas in you `.sublime-keymap` files. I've done a plugin [JSONComma](https://github.com/math2001/JSONComma) that deals with them for you

**Comment by wzhix** [comment]
I have edit README.md in English and removed trailing commas in `.sublime-keymap` files.

**Comment by FichteFoll** [comment]
You don't have the "tab" binding in your Linux keybindings file. Furthermore, it seems that your tab key bindings might be too general because it will be active in all widgets that are overlays and not panels (i.e. quick panels and goto anything). Since you usually don't need a tab character in these, it will *probably* be fine, but I want to mention it just in case since it will prevent other plugins from trying to captue the tab character in these.

For FileHistory, we implemented our [own context key](https://github.com/FichteFoll/FileHistory/blob/069ea3d3a20c20ca96b380e4a26f63d8496d2efb/Default%20(Windows).sublime-keymap#L8) for this purpose.

**Comment by wzhix** [comment]
Sorry about that. I fixed the "tab" binding in Linux and added my own context key `inspr_result_overlay_visible` to prevent other plugin capturing the tab key.

**Comment by FichteFoll** [comment]
Unfortunately, your context key is useless because it always returns `True`. You only want it to be true while your quick panel is open. (For that, you set a global variable to true before opening it and set it to false when it has been closed, i.e. your `on_done` callback was called.)

**Comment by wzhix** [comment]
Thanks for pointing out. Is this OK?
[set a global variable](https://github.com/wzhix/inspr/blob/master/Inspr.py#L148)
[set true if quick panel is opened](https://github.com/wzhix/inspr/blob/master/Inspr.py#L239-L240)
[set false if on_done is called](https://github.com/wzhix/inspr/blob/master/Inspr.py#L296-L297)

**Comment by FichteFoll** [comment]
Yes, this should do.

**Pull request merged**
