### PR TITLE
Add "Motoko" syntax

### PR DESCRIPTION
**Pull request by jingyuexing**

### CODE REVIEW

**Comment by braver** [comment]
Can you perhaps explain in the readme and/or the repo's "about" what language your syntax package is for?

**Comment by jingyuexing** [comment]
> Can you perhaps explain in the readme and/or the repo's "about" what language your syntax package is for?

this project [motoko](https://github.com/dfinity/motoko)

**Comment by braver** [comment]
Your package repo has neither a description nor a README. Please add at least one of those, otherwise nobody will understand what your package is for.

**Comment by braver** [comment]
Please respond to the feedback to continue this PR.

**Pull request closed without merging**
