### PR TITLE
Remove AutoFoldCode

### PR DESCRIPTION
**Pull request by callodacity**
I have stopped development on AutoFoldCode and have deleted the repository. It should therefore also be removed from Package Control.

### CODE REVIEW

**Comment by callodacity** [comment]
@RIDE-2DAY unfortunately there have been some changes in my life recently, and I won't be able to further any development on such things.

If you'd like the source, I can send it to you and you can feel free to maintain it.

**Comment by RIDE-2DAY** [comment]
@callodacity oh, that would be great actually! I'm really interested on it. I was going to install it some days ago in a new computer and I noticed it wasn't available anymore.

Do you need my e-mail or you're able to upload it somewhere?

Thank you, best regards.

**Comment by callodacity** [comment]
@RIDE-2DAY I can upload it to GitHub and transfer the repository to you, or I can sent it to you via email, the choice is yours.

**Comment by RIDE-2DAY** [comment]
@callodacity the GitHub way would be great, thank you again.

**Comment by RIDE-2DAY** [comment]
@callodacity it has been transferred correctly, thanks.

**Comment by callodacity** [comment]
@RIDE-2DAY No worries, if you would like you can open a PR here and update the repository details on package control, rather than having it removed in this PR.

**Comment by RIDE-2DAY** [comment]
PR #6825 - updated the URL of this package, as the original author transferred it to me. Thanks a lot @callodacity.

I think this PR might be closed.

**Pull request closed without merging**
