### PR TITLE
add Find Exclude Patterns

### PR DESCRIPTION
**Pull request by titoBouzout**
Thanks!

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

Travis-CI is doing weird things at the moment. I am unsure if the build actually failed or if the integration is broken.

**Comment by titoBouzout** [comment]
Thanks for the info, that sad decision, I don't want to maintain versions :o

**Comment by FichteFoll** [comment]
It's a no-exceptions rule.

We settled the travis interaction issues. The build did in fact fail and your package is not in order: https://travis-ci.org/wbond/package_control_channel/builds/103195645#L167

**Comment by titoBouzout** [comment]
okei thanks

**Pull request closed without merging**
