### PR TITLE
Add iCalendar package

### PR DESCRIPTION
**Pull request by kimsey0**
Very simple [iCalendar](https://en.wikipedia.org/wiki/ICalendar) syntax highlighting.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your details url should point to https://github.com/kimsey0/iCalendar-sublime.

[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by kimsey0** [comment]
Oops about the details URL. I've fixed that now.

Shall I omit the 'v' in front of the version number, which is traditionally used on GitHub?

**Comment by FichteFoll** [comment]
The 'v' is optional, Package Control will detect and filter it.

**Comment by kimsey0** [comment]
Great. Thanks!

**Pull request merged**
