### PR TITLE
Added Code Story package

### PR DESCRIPTION
**Pull request by dperetti**

### CODE REVIEW

**Comment by wbond** [comment]
@dperetti Can you create a tag on the repo so the rest of the tests can be run?

**Comment by dperetti** [comment]
Done !

**Comment by dperetti** [comment]
Maybe because the tag was 1.0 and not 1.0.0 ? Added 1.0.0

**Comment by dperetti** [comment]
Removed codestory-sublime.sublime-workspace in 1.0.1 !

**Comment by FichteFoll** [comment]
Also, please update the min version requirement to a build that includes the popup API.

**Pull request merged**
