### PR TITLE
Add Theme - Seti Monokai

### PR DESCRIPTION
**Pull request by poucotm**

### CODE REVIEW

**Comment by wbond** [comment]
Did you test the package without a `.no-sublime-package` file? Ideally packages should be created as a `.sublime-package` since it allows users to override things.

**Comment by poucotm** [comment]
In my local computer, it works. And many old packages use like that. I don't know differences. Is there any difference of reading speed between them (compressed files vs. non-compressed files) ? Anyway, I've removed .no-sublime-package and committed again.

**Comment by wbond** [comment]
A `.no-sublime-package` will always work, but it makes it impossible for end-users to override or tweak parts of a package. This functionality was added in Sublime Text 3.

The only reason you really need a `.no-sublime-package` file is if you have `.dll`, `.so`, `.exe`, `.sh` or other executable files in the package that need to be executed.

**Comment by poucotm** [comment]
Thank you for the information ~

**Pull request merged**
