### PR TITLE
Stylelint Auto fix with global stylelint command

### PR DESCRIPTION
**Pull request by paleite**

### CODE REVIEW

**Comment by paleite** [comment]
The package runs a script included in the package using `node`.

**Comment by Thom1729** [comment]
Why fork the existing package rather than improving it?

Also, I don't see any node scripts in the repo.

**Comment by paleite** [comment]
Hi, and thanks for the feedback!

The existing package was for running eslint (linter for js), but this package is for running stylelint (linter for css, scss, less, etc), which I don’t reckon have the same use cases, hence why I forked it, rather than improving the existing package. What are your thoughts on this?

The package doesn’t run a node-script. I think I may have misunderstood in that case; it runs a script included in the package, which in turn uses a global node script. (I.e. the same procedure as the existing eslintAutoFix-package). Can I remove the .no-sublime-package file?

Thanks!

**Comment by Thom1729** [comment]
> The existing package was for running eslint (linter for js), but this package is for running stylelint (linter for css, scss, less, etc), which I don’t reckon have the same use cases, hence why I forked it, rather than improving the existing package. What are your thoughts on this?

That makes sense. You should clarify in the readme that it does something substantially different from the source; it's not just an improved or modified version.

> The package doesn’t run a node-script. I think I may have misunderstood in that case; it runs a script included in the package, which in turn uses a global node script. (I.e. the same procedure as the existing eslintAutoFix-package). Can I remove the .no-sublime-package file?

Yes, you can (and should).

Other thoughts:

- You should add a license.
- It's probably better to include a default sublime-settings file than to use hardcoded defaults in the script.
- It looks like `Stylelint_auto_fixCommand` should be a `TextCommand` rather than a `WindowCommand`. That way, you can invoke it on a particular view rather than getting the active view.
- Instead of `platform.system()`, you can use `sublime.platform()`.
- I don't really see the point of the `Preferences` class, but YMMV.

**Comment by FichteFoll** [comment]
The auto-fixer operates on the saved file, so perhaps you should verify that the file being edited is indeed unchanged compared to the saved version `view.is_dirty()`. Besides, `view.file_name()` may be `None` in case the file is unsaved.

You can just pre

**Comment by Thom1729** [comment]
@paleite ping

**Pull request closed without merging**
