### PR TITLE
Add "Paste Plus" package

### PR DESCRIPTION
**Pull request by ggets**

### CODE REVIEW

**Comment by braver** [comment]
Thanks for submitting. Could you perhaps elaborate what this package adds and how that is something that's not already covered by existing packages? 
It looks like it does one thing (which is good!) but I didn't get _what_ that is from the name of the package (it sounds like a multi-featured thing around pasting stuff). Or is your intention to add more?

**Comment by ggets** [comment]
I plan to add more functionality. Right now it's sole purpose is to provide paste-able URIs from copied files in Windows Explorer.

**Comment by ggets** [comment]
The keyboard shortcuts are not replaced unless this behavior is allowed by configuration option.

**Comment by braver** [comment]
Cool, thanks!

**Pull request merged**
