### PR TITLE
Adding the Retro Theme Colorscheme

### PR DESCRIPTION
**Pull request by rafaelfragosom**
Please provide the following information:

 - Link to your code repository: https://github.com/retro-theme/sublime
 - Link to the tags page with at least one [semver](http://semver.org) tag:  https://github.com/retro-theme/sublime/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Tested on Sublime 3131 macOS 10.12 ✅

**Comment by wbond** [comment]
Since this is a color scheme, it feels wrong to have "theme" in the name.

**Comment by FichteFoll** [comment]
@rafaelfragosom please also resolve the merge conflict.

**Comment by FichteFoll** [comment]
@rafaelfragosom ping

**Comment by rafaelfragosom** [comment]
@FichteFoll sorry the delay, I will solve this tomorrow. Busy week.

**Pull request closed without merging**
