### PR TITLE
Angular 2 Snippets

### PR DESCRIPTION
**Pull request by pjlamb12**
Added Angular 2 Snippets which will provide commonly used snippets when developing Angular 2. Located at https://github.com/pjlamb12/st3-ng2-snippets

### CODE REVIEW

**Comment by FichteFoll** [comment]
What are differences to [other angular packages](https://packagecontrol.io/search/angular)?

**Comment by pjlamb12** [comment]
I don't know that there are any differences, but when I submitted the pull request there were no other Angular 2 snippets packages. You can see that from the pull request number and date stamp.

**Comment by pjlamb12** [comment]
Any ETA on when this will be merged?

**Comment by FichteFoll** [comment]
Please follow the discussion in #5482.

**Comment by pjlamb12** [comment]
As suggested in #5482 I have changed the name of my snippets package to "Angular 2 Snippets (John Papa)".

**Pull request merged**
