### PR TITLE
Added Weave Package - Salesforce Code Snippets

### PR DESCRIPTION
**Pull request by mailtoharshit**
This package contains snippet to generate visualforce pags templates for Salesforce.com Platform, it also contains templates to generate Material Design Code with Salesforce and ready to publish pages and snippet containing design patterns in Apex

### CODE REVIEW

**Comment by FichteFoll** [comment]
How does this compare to [other salesforce packages](https://packagecontrol.io/search/salesforce)?

**Comment by mailtoharshit** [comment]
Other packages, do not have snippet to generate template code for Visualforce pages, this generates visualforce layout using material design, salesforce lightning design system and also generates scaffold code for Factory and other design patterns. We saw fairly limited version in Mavensmate and other snippets provided by folks around here. No other package generates boilerplate layouts on visualforce pages

**Comment by mailtoharshit** [comment]
http://mailtoharshit.github.io/Weave/  <- site under construction, but we generate a complete code using cutting edge pattern and best practices provided by Salesforce not just auto-complete as seen in the links provided above.

**Comment by mailtoharshit** [comment]
@FichteFoll  - Something unique about package is which 'none' of package provides they are just auto-complete for Apex

1. Visualforce Markup Generator using Google MDL, Materialize and More 
2. Bootstrap multiple layout
3. Mobile Ready Templates
4. Apex Trigger Scaffold Generator
5. Apex Trigger Handler Generortor
6. Javascript Remoting Boilerplate Code generator

I believe none of the of the list plugin is close to this, leveraging best practices of Salesforce and generates boilerplate code
http://mailtoharshit.github.io/Weave/  (Site under construction, but a quick glimpse can be seen, what our vision is)

**Comment by mailtoharshit** [comment]
@FichteFoll  - Just wondering what I cannot search 'Weave' Package on https://packagecontrol.io/ and sublime though it is listed ?

**Comment by ravichandra1** [comment]
True. I liked the instant templates for triggers, vf pages with material design . Easy to use and it helps in maintaining  a standard coding practice through out the organization.Saves time and improves the readability of the code as its done following best coding practices.

**Pull request merged**
