### PR TITLE
Add CSScomb-Updated

### PR DESCRIPTION
**Pull request by loringdodge**
The previous CSScomb Sublime package is no longer maintained and CSScomb has seen several versions since. This PR adds a package that brings the updated version of CSScomb and some usage changes.

Old Sublime CSScomb repo - https://github.com/csscomb/sublime-csscomb

### CODE REVIEW

**Comment by loringdodge** [comment]
I think the build is using a cached version of the repo that has .no-sublime-package defined. I removed it but it's still throwing a warning. See the Repo Link (it's been removed)

**Comment by FichteFoll** [comment]
Maybe someone at @csscomb could add you as a collaborator so you can update the existing repo to a recent version? That way, all the people who installed that package would receive this update instead of having to find and install this package manually. 

cc @tonyganch

---

You need to push a new semver tag to the repo to make a new release. This is what Package Control will look for and download.

**Comment by tonyganch** [comment]
@loringdodge, i'll be happy to add you as a collaborator to csscomb/sublime-csscomb repo if you're willing to update it

**Comment by FichteFoll** [comment]
@loringdodge, @tonyganch have you managed to get in touch?

**Comment by loringdodge** [comment]
@FichteFoll Let me reach out to @tonyganch

**Comment by tonyganch** [comment]
@FichteFoll, we did get in touch 🐙

**Comment by FichteFoll** [comment]
All right, I'm closing this then. Should any issues arise, feel free to comment here.

**Pull request closed without merging**
