### PR TITLE
Add 'Copy Paste Killer' package

### PR DESCRIPTION
**Pull request by kyamaguchi**
Sublime text 3 plugin to help to refactor duplicated code.

See screenshots on https://github.com/kyamaguchi/CopyPasteKiller/blob/master/README.md for more detail.

### CODE REVIEW

**Comment by kyamaguchi** [comment]
triggering bot

**Comment by Thom1729** [comment]
Rather than grabbing `sublime.active_window()` and `sublime.active_window()`, you should make the command a `TextCommand` and get `self.view` and `self.view.window()`.

What is the `slurp_find_string` command?

**Comment by kyamaguchi** [comment]
> What is the `slurp_find_string` command?

It fires "Use Selection for Find ⌘E" in "Find" menu.
`slurp_replace_string` fires "Use Selection for Replace ⇧⌘E" in "Find" menu.

I couldn't copy text into "Find" and "Replace" boxes in other ways.

**Comment by kyamaguchi** [comment]
Fixed with `TextCommand`

**Pull request merged**
