### PR TITLE
Add Night Soft Color Scheme

### PR DESCRIPTION
**Pull request by notiv-nt**

### CODE REVIEW

**Comment by Acecool** [comment]
'Ngx HTML',
+  'Night Soft Color Scheme',
   'NightCycle',
   'Nightwalker Color Scheme',
-  'Night Soft Color Scheme',
   'Niji',
   'NimLime',


---

Packages need to be sorted alphabetically.. The - shows where it is in the list and the + shows where it needs to go.

**Comment by Thom1729** [comment]
You should add a license.

**Comment by notiv-nt** [comment]
@Thom1729 done

**Comment by notiv-nt** [comment]
@Thom1729 can you accept ?

**Pull request merged**
