### PR TITLE
Add Profile Switcher

### PR DESCRIPTION
**Pull request by tonsky**

### CODE REVIEW

**Comment by braver** [comment]
I kinda wonder how this compare with [Switch Settings](https://packagecontrol.io/packages/Switch%20Settings) (besides being a lot newer).

Besides that an older similar package already exists and might be replaced, I don't object merging this per se. However...

I also kinda wonder how much of this wouldn't be better handled using syntax specific setting. Assuming of course that most other modes are like "writing" and that writing mostly being in one syntax. In any case, personally, I'd be looking for an automatic switch like "use this profile for these languages" instead of manually switching modes every time. Which is essentially what syntax specific settings already does, except that it doesn't bundle settings for multiple profiles.

**Comment by tonsky** [comment]
@braver You are right, my case could be handled by syntax-specific settings. I realized that after writing the whole thing, though :) So the question is: could this be potentially useful to someone besides that? I think yes, but can’t think of an use-case.

Re: Switch Settings, I just tried it. It’s exactly the same idea, yes. But I’d say mine is much smoother. E.g. Switch Settings has modal alerts and restarts ST every time you change profile. Mine is silent and invisible.

**Comment by braver** [comment]
Well let’s see if we can update the existing package. Not a whole lot of users, but it would be nice to have a smooth new implementation of the same idea.

@t8m8 would you mind if we replace your Switch Settings package with this new package from @tonsky ?

**Comment by tonsky** [comment]
One of the side effects of using syntax-specific settings for Markdown: in SM markdown diffs are in different font now. Not sure good or bar, certainly not what I’d expected

Screenshot 2021-03-02 at 01 53 27

**Comment by braver** [comment]
Oh, that’s interesting. SM seems to take quite a lot of settings from ST, I’m always a bit surprised by how deep that seems to go.

**Comment by tonsky** [comment]
> @t8m8 would you mind if we replace your Switch Settings package with this new package from @tonsky ?

It’s been a week since you reached out to @t8m8. Is it possible that we publish my package now and wait for the reply (if it ever comes) in the background?

**Comment by braver** [comment]
Not really. The policy requires 2 weeks and its a whole lot of hassle to correct afterwards.

**Comment by tonsky** [comment]
Ok, it’s now been two weeks. For the record, I don’t propose to remove @t8m8 package, I propose to add mine and keep his/hers too for now. And open a separate issue in which you can wait for the reply to remove it later

**Comment by braver** [comment]
Nah, I’d rather just straight out replace the thing. We want to prevent users from having to weed through and perhaps try out different packages that do the same thing. @t8m8 has been active on GitHub these past few weeks, and not responded here. So there really is no reason to keep that package around.

**Comment by t8m8** [comment]
Sorry for the late reply. Switch Settings I developed in the past is now completely out of development, so I am in favor of replacing it with @tonsky package. Thanks for contacting me, I appreciate it.

**Comment by braver** [comment]
@tonsky can you update this PR so that it replaces the existing package with yours?

**Comment by tonsky** [comment]
@braver done

**Comment by rwols** [comment]
braver meant using the `previous_names` key.

**Comment by tonsky** [comment]
@rwols done

**Comment by tonsky** [comment]
@braver done

**Pull request merged**
