### PR TITLE
Added own package: UnusedCssFinder

### PR DESCRIPTION
**Pull request by Harderer**

### CODE REVIEW

**Comment by FichteFoll** [comment]
This PR is unreviewable. Please check if you changed indentation, and if you did, also check your editor config to auto-detect it, so this won't happen again.

**Comment by Harderer** [comment]
Thanks for the information. I retried commiting it and it seems to have worked. Please notice that I changed the name from 'FindUnusedCss' to 'UnusedCssFinder'.

**Comment by FichteFoll** [comment]
Unfortunately the file `f.json` still contains over a thousand lines changed, but at least I can review `u.json` now.


You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

You can not pass `edit` objects around in an asynchronous manner since they get effectively "destroyed" as soon as the `run` method returns. See also: https://forum.sublimetext.com/t/solved-issue-using-edit-objects-recursively/18400

**Comment by FichteFoll** [comment]
@Harderer ping

**Comment by Harderer** [comment]
Updated the u.json file and created a release tag. Also removed the `edit` object from the async functions as it was only a relict of developing.

Can the f.json be ignored in this pull request? As the package is now contained in the u.json. Or do I have to clear the indentation problem.

**Comment by FichteFoll** [comment]
Only if I merge manually, which I'd like not to since it is additional work. Please rebase/reset/squash/whatever the pull request and re-apply the necessary changes yourself. You can learn a bit about git's features during that process.

**Comment by Harderer** [comment]
Okay, I've performed the other changes and have done my best to restore the f.json file. I hope it works now.

**Pull request merged**
