### PR TITLE
VPC Script Syntax Highlighting

### PR DESCRIPTION
**Pull request by GitSparTV**
Syntax Highligthing for Valve Project Creator scripts.
image

### CODE REVIEW

**Comment by braver** [comment]
Syntaxes do much more in Sublime Text than just highlighting. And packages for specific languages usually provide more than just the syntax. Therefore, simply name your package after the language it supports and leave out words like “syntax” or “highlighting”.

Please have a look at the tests, you need at least a README, a license is also recommended.

**Comment by braver** [comment]
You probably also want to add a tmPreferences file to enable comments via keyboard shortcuts.

**Comment by GitSparTV** [comment]
Done

**Comment by braver** [comment]
You can ignore the version 3092 warning, but I would like to rename the package to "VPC Script" for the aforementioned reasons.

**Pull request merged**
