### PR TITLE
Add Beau to Repository

### PR DESCRIPTION
**Pull request by Seich**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You don't need a `.no-sublime-package` file. Please remove it.

**Comment by Seich** [comment]
@fichtefoll done.

**Comment by Seich** [comment]
Is there anything missing @FitcheFoll?

**Comment by FichteFoll** [comment]
Yes, please push a new tag with the latest changes.

**Comment by Seich** [comment]
@FichteFoll done.

**Comment by FichteFoll** [comment]
Unfortunately, your created tag uses an upper-case `V` which PC doesn't recognize.

**Comment by Seich** [comment]
@FichteFoll oh, didn’t notice. It’s been renamed.

**Pull request merged**
