### PR TITLE
Added Flat Chameleon UI Theme

### PR DESCRIPTION
**Pull request by r3a1ay**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo.. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by r3a1ay** [comment]
`"tags": true` added.
Should I fix something else?

**Comment by r3a1ay** [comment]
Thanks.
I have fixed some bugs in my theme and added new tags (v1.2.2 - the latest/added 2 hours ago).
[Package control](https://packagecontrol.io/packages/Flat%20Chameleon) page updated readme section twice, but has not updated the version of the package.
Is something wrong in my tags?

**Comment by FichteFoll** [comment]
All the tags you pushed have dots after the `v`. You can make Package Control understand that (by setting `"tags": "v."`, but I suggest just removing the dots instead.

**Comment by r3a1ay** [comment]
Thanks.

**Pull request merged**
