### PR TITLE
Added Simple FTP Deploy to packages

### PR DESCRIPTION
**Pull request by HexRx**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You didn't push any tag.

I highly recommend putting some information in the readme. You can't expect everyone to be able to read the source code in order to understand what it does.

**Comment by FichteFoll** [comment]
@HexRx ping

**Comment by HexRx** [comment]
Hi, @FichteFoll. I added information in the readme and created tag.

**Comment by FichteFoll** [comment]
Your tag doesn't contain the prefix you specified here. I suggest you just change it to `"tags": true`, which means no prefix.

**Comment by HexRx** [comment]
@FichteFoll, I changed tags.

**Pull request merged**
