### PR TITLE
DFormat plugin

### PR DESCRIPTION
**Pull request by dmi7ry**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The package name is not meant to contain a description of the package, that's what the description is for (fetched from your repo's description).

You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by dmi7ry** [comment]
Done

**Comment by FichteFoll** [comment]
Also, [semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by dmi7ry** [comment]
Ok, changed.

**Comment by dmi7ry** [comment]
Now changed.

**Pull request merged**
