### PR TITLE
Add ChineseTranslator plugin

### PR DESCRIPTION
**Pull request by toaol**
This is translate plugin for Chinese.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

`ctrl+q` is already bound by default to the `toggle_record_macro` command. Please do not override default key bindings and either choose a free binding or suggest your users to set this binding on their own.

**Comment by toaol** [comment]
@FichteFoll Thanks, I have already updated them.

**Comment by FichteFoll** [comment]
Well, `ctrl+shift+q` is also a default binding - for `run_macro`.

**Comment by toaol** [comment]
@FichteFoll I am sorry about it because in my system the key binding of `run_macro`  is `ctrl+alt+shift+q`, and now, this might be OK.

**Pull request merged**
