### PR TITLE
Add yara package

### PR DESCRIPTION
**Pull request by nyx0**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by nyx0** [comment]
My bad, I fixed the release problem.

**Comment by FichteFoll** [comment]
Good, but you still need to adjust the pull requets.

**Comment by nyx0** [comment]
I think it's good

**Pull request merged**
