### PR TITLE
Add IRC log Syntax package

### PR DESCRIPTION
**Pull request by barnumbirr**
IRC log file syntax highlighting.

### CODE REVIEW

**Comment by braver** [comment]
Are you sure you want to register for the txt extension?

**Comment by barnumbirr** [comment]
It's not ideal but most IRC client export their log files to plain text.

**Comment by braver** [comment]
I don’t know exactly how it behaves, but as long as it doesn’t automatically becomes the default for txt files that’s fine. That would be annoying. And that might be a good reason to not set the extension, or something irc-specific.

**Comment by barnumbirr** [comment]
I've now released [v1.0.1](https://github.com/barnumbirr/sublime-irc/releases/tag/1.0.1) which removes file extension.

**Comment by braver** [comment]
Excellent 👌🏻

**Pull request merged**
