### PR TITLE
added ERB helpers package (rayhanw)

### PR DESCRIPTION
**Pull request by rayhanw**
# Sublime ERB Helpers

Other ERB snippet packages have not been updated for years and I propose a couple of new snippets to help shorten the amount of keystrokes you need to type these snippets (I am a lazy person😅).
`<%= cl_image_tag %>`, `<%= simple_form_for %>`, `<%= time_ago_in_words() %>`, etc.

### NOTE
Using proper indentation somehow fails the test, so I know that it looks skewed, but it's a way that i figured to pass the test.

### CODE REVIEW

**Comment by rayhanw** [comment]
Added LICENSE file to fix the warning, will close and re-open PR

**Comment by FichteFoll** [comment]
Please indent your additions properly. You must use tabs, not spaces.

You should also add a description to your Github repo for better search results on packagecontrol.io.

**Comment by FichteFoll** [comment]
@rayhanw ping

**Comment by rayhanw** [comment]
Hi @FichteFoll sorry for the late reply. I used spaces because using tabs somehow fails the tests.

As for the description part, will do!

**Comment by FichteFoll** [comment]
All JSON files in this repo use tabs. If tests are failing, it's because of something you did with your file, which may or may not be related to your ST configuration.

**Comment by FichteFoll** [comment]
@rayhanw final ping

I can't merge when the tests are failing. Please fix the indentation.

**Pull request closed without merging**
