### PR TITLE
Added Advanced PLSQL

### PR DESCRIPTION
**Pull request by TheEggi**
There exists a similar package, which is very inactive (last commit in 2016). The main reason why this package was now created is that there exists quite a few ideas (better build system, included SQL tools, better highlights, ...) on how to improve / get this package at least to the same level as the VS Code package. In order to achieve this the possibility of regular updates is mandatory and therefore a new package has been created.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I assume you're talking about https://packagecontrol.io/packages/Oracle%20PL%20SQL? That really only has a syntax definition and if you include that to at least the same feature level, since yours looks to be based on it, I would condone replacing it entirely to give users less choice and only present them the better version. What do you say?

**Comment by TheEggi** [comment]
That sounds perfect to me. Should I just edit this PR in a way that it replaces the original plugin or how should we continue here?

Regarding the syntax: The syntax is based on the existing plugin with some improvements (and it still needs a few more minor fixes for it to be perfect).

**Comment by FichteFoll** [comment]
Yes, just replace the package URL and optionally rename it (by supplying `previous_names`).

Per convention, we grant maintainers a 2 week period to object to their package being replaced. @mulander, if you would like to object or condone this change, please comment.

**Comment by mulander** [comment]
No objections - go ahead. I stopped using Sublime after moving to OpenBSD (no builds for the platform :().

**Pull request merged**
