### PR TITLE
Add Bootstrap 5x Autocomplete

### PR DESCRIPTION
**Pull request by ahmetcadirci25**

### CODE REVIEW

**Comment by ahmetcadirci25** [comment]
@packagecontrol-bot

**Comment by ahmetcadirci25** [comment]
*really*

**Comment by ahmetcadirci25** [comment]
really

**Comment by rchl** [comment]
There is no reason to have `.no-sublime-package` or `.sublime-package` file in your package. Do you understand what it does in the first place?

**Pull request closed without merging**
