### PR TITLE
add Term package

### PR DESCRIPTION
**Pull request by percevalw**
Plugin for emulating a terminal inside a tab

 - Link to your code repository: https://github.com/percevalw/SublimeTerm
 - Link to the tags page: https://github.com/percevalw/SublimeTerm/tags

Used "tags": true => Done
Ran the tests => Done

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Your package is not referencing the theme properly
Look at, https://github.com/percevalw/SublimeTerm/blob/master/Term.sublime-settings#L2
screen shot 2017-05-11 at 12 12 25 pm

**Comment by percevalw** [comment]
The property “name” in the repository json file would rename the package to “Term”
so it would comply with the name policy (no Sublime in it) and reference the theme properly.
I added a `packages.json` file to the repo so you can install it more easily, using the "Add repository" menu command on ST.
[https://raw.githubusercontent.com/percevalw/SublimeTerm/master/packages.json](https://raw.githubusercontent.com/percevalw/SublimeTerm/master/packages.json)

I also changed the referencement of the package, adding the `packages.json` link to the `channel.json` instead of writing it directly in the `repositories` folder for more control over it in the future.

**Comment by wbond** [comment]
@percevalw Can you update the PR to set `sublime_text` to `>=3092` since you are using .sublime-syntax?

**Comment by FichteFoll** [comment]
The platform key "osx" includes "osx-x64".

**Comment by FichteFoll** [comment]
Closing in favor of https://github.com/wbond/package_control_channel/pull/6359.

**Pull request closed without merging**
