### PR TITLE
Adds MotionBuilderSublime package.

### PR DESCRIPTION
**Pull request by matthewkapfhammer**
- Repository: https://github.com/matthewkapfhammer/MotionBuilderSublime
- Tags: https://github.com/matthewkapfhammer/MotionBuilderSublime/releases

### CODE REVIEW

**Comment by FichteFoll** [comment]
You should add more context conditions to your key binding so you don't end up overriding the default one for `replace_all`:
```js
	{ "keys": ["ctrl+alt+enter"], "command": "replace_all", "args": {"close_panel": true},
		 "context": [{"key": "panel", "operand": "replace"}, {"key": "panel_has_focus"}]
	},
```

**Comment by matthewkapfhammer** [comment]
Thanks, @FichteFoll. I'll have a go at that and push an update.

**Comment by matthewkapfhammer** [comment]
@FichteFoll, I couldn't come up with any better context conditions, so I changed the key bindings instead. 

See this commit: https://github.com/matthewkapfhammer/MotionBuilderSublime/commit/2c713d10aafa2a0966b66b0855e909d101c37851

Let me know if anything else pops out to you. 

Thanks!
MK

**Comment by matthewkapfhammer** [comment]
@FichteFoll, Should I being seeing the package in https://packagecontrol.io/ yet? 

Thanks!
MK

**Comment by FichteFoll** [comment]
It seems you added a wrong URL in your pull request that differs from the one you posted in the issue and I didn't notice.

I fixed that in https://github.com/wbond/package_control_channel/commit/109eb252875e6a31777f5210acf03c2e748e3b68 and also named the package "MotionBuilder", since the "Sublime" part is really redundant and also against our package name policies. Yet another thing I missed.

**Comment by matthewkapfhammer** [comment]
Apologies for the mixup.

Regarding the package name, I was following the name pattern used by MayaSublime to be consistent since they both are designed to send code snippets to their respective Autodesk application. I didn't realize it was against a name policy.

Thanks for fixing the URL!

**Pull request merged**
