### PR TITLE
Adding `F2J - FCore to Java`

### PR DESCRIPTION
**Pull request by zonyitoo**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push valid [semantic version](http://semver.org) tags (with optional leading `v`) to your repo.

**Comment by zonyitoo** [comment]
@FichteFoll Already done ;)

**Comment by FichteFoll** [comment]
Semantic versions consist of three numeric parts.

**Comment by zonyitoo** [comment]
@FichteFoll Ah, sorry about that... I have updated.

**Pull request merged**
