### PR TITLE
Add Multicommand package

### PR DESCRIPTION
**Pull request by dvcrn**
Plugin for executing multiple commands per keybinding

### CODE REVIEW

**Comment by deathaxe** [comment]
How does this package differ from the existing [Chain Of Command](https://packagecontrol.io/packages/Chain%20of%20Command)?

**Comment by dvcrn** [comment]
Looks similar, yeah but Chain Of Command is also abandoned (couple open issues, PR and no license). I don't think another option hurts

**Comment by dvcrn** [comment]
Anything I can do to get this merged?

**Comment by FichteFoll** [comment]
Since you removed the `context` functionality, as ST automatically resolves it for your when you use `Window.run_command`, you should also remove mentions of it in the readme and comments (and mentions of evernote, which is entirely unrelated now).

**Comment by dvcrn** [comment]
Thanks will do!

**Comment by FichteFoll** [comment]
Regarding Chain of Command, the only issue worth resolving seems to be https://github.com/jisaacks/ChainOfCommand/issues/10 (and probably https://github.com/jisaacks/ChainOfCommand/pull/7), which your version *does* address. It not being maintained isn't really an issue since the functionality fundamentally won't change in the foreseeable future.

Because the existing package a) is really basic, b) has probably been referenced a lot in various places over time as a solution for a common problem, and c) both "chain of command" and "multi command" are names you can find when searching this problem, I am okay with having another package fulfill the same job. I could also see replacing Chain of Command, as long as it remains backwards-comaptibl.

**Comment by dvcrn** [comment]
Cleaned up the README and examples to remove context and not needed references

**Pull request merged**
