### PR TITLE
add Carmesim color scheme

### PR DESCRIPTION
**Pull request by sergiokopplin**

### CODE REVIEW

**Comment by FichteFoll** [comment]
So, what exactly are the differences to the original spacegray theme? They look *very* similar to me, besides a small shift in hue.

I also don't see a reason to include the Dracula scheme since it's [available on package control](https://packagecontrol.io/packages/Dracula%20Color%20Scheme).

**Comment by sergiokopplin** [comment]
It's the same idea of the amCoder Package. Optimized for the Dracula color Scheme.
I can split the dracula from the package, what you think? The user can install separate from the Carmesim.

My intention is to create a theme with the Dracula theme colors. What is a fork from the spacegray, like the amcoder is.

**Comment by sergiokopplin** [comment]
I put the dracula out of the package.

**Comment by FichteFoll** [comment]
>Go to `Preferences -> Color Scheme -> User` and select the `Dracula Color Scheme`.

"User" is wrong here, as indicated by the JSON that follows.

Also, you need to push a new tag with the latest commit in order to mark a new release.

**Comment by sergiokopplin** [comment]
I will fix that! Thank you

**Comment by sergiokopplin** [comment]
Fixed!

**Pull request merged**
