### PR TITLE
ChineseOpenConvert

### PR DESCRIPTION
**Pull request by rexdf**
Orginal author has been not online for years.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I'd prefer if you could take over the original package (name) or replace it by optional renaming in the process.

@erinata, are you still alive? If so, do you have any objections if @rexdf takes over your "Tradsim" package slot? I will wait for ~2 weeks.

**Comment by FichteFoll** [comment]
It appears that you, @erinata, were active on said repository in the past two weeks. Please comment on this issue.

**Comment by erinata** [comment]
I am active. I just didn't notice the pull request before.

Erinata

**Comment by rexdf** [comment]
Now I release a completely different and much more powerfull plugin with opencc.

**Comment by FichteFoll** [comment]
I have the feeling that your readme is outdated and that a different package name is more suitable, especially because "Tradism" exists already.

`view.end_edit` does not exist on ST3.

**Comment by rexdf** [comment]
Maybe ChineseOpenConvert is better.

**Comment by erinata** [comment]
I dun exactly know what happen... but if there is a more powerful (and more
maintained) package  showing up I dun want my package to stand in its way

**Comment by rexdf** [comment]
It is really different package. Maybe I should use my upstream package name open chinese convert just as you use ruby Tradsim.
ChineseOpenConvert should be better.

**Comment by rexdf** [comment]
No, your package is still usefull for sublime 2 at least. And different implement for same function is allowed.

**Comment by erinata** [comment]
I am glad to hear that.

**Comment by rexdf** [comment]
ChineseOpenConvert can distinguish Taiwanese idiom and Hong Kong Standard etc. It is usefull for country names and proper nouns.

**Pull request merged**
