### PR TITLE
Add new package "Mellanox Syntax Highlighter"

### PR DESCRIPTION
**Pull request by KeyboardInterrupt**
This Package adds Syntax highlighting for Mellanox router/switch/firewall configuration files.

Also Thank you very much for package control, I could not imagine Sublime Text without it!

### CODE REVIEW

**Comment by KeyboardInterrupt** [comment]
I added a Tag now, Missed that step somehow.

**Comment by Thom1729** [comment]
You should add a license.

**Comment by KeyboardInterrupt** [comment]
I added a LICENSE.md

**Comment by Thom1729** [comment]
The channel entry appears to be sorted incorrectly.

**Pull request merged**
