### PR TITLE
[Colored Comments] - Package Update

### PR DESCRIPTION
**Pull request by TheSecEng**
Added `bracex` to PackageControl dependencies
Added tags to Colored Comments

### CODE REVIEW

**Comment by facelessuser** [comment]
We'll need a specific Sublime compare repo for this. We can't use the main repo directly. If you need me to, I can create one and the main is also mine.

**Comment by TheSecEng** [comment]
> We'll need a specific Sublime compare repo for this. We can't use the main repo directly. If you need me to, I can create one and the main is also mine.

Oh yes, go for it please

**Comment by facelessuser** [comment]
I'll post back when I have one.

**Comment by FichteFoll** [comment]
Please remove the bracex change from this PR so I can merge.

**Comment by facelessuser** [comment]
@TheSecEng when you are ready, bracex can be specified using this repo: https://github.com/facelessuser/sublime-bracex

From the ST4 console:

```
Python 3.3>>> bracex.expand('a{a,b}')
['aa', 'ab']
Python 3.3>>> bracex.expand(b'a{a,b}')
[b'aa', b'ab']
```

**Comment by TheSecEng** [comment]
@FichteFoll Removed
@facelessuser will create a new PR for this.

**Pull request merged**
