### PR TITLE
Adding CalculateRelativePath to package control channel

### PR DESCRIPTION
**Pull request by TonyHYK**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by TonyHYK** [comment]
Done!

**Comment by FichteFoll** [comment]
There is nothing [here](https://github.com/TonyHYK/CalculateRelativePath/tags).

**Comment by TonyHYK** [comment]
My bad... should be there now.

**Pull request merged**
