### PR TITLE
added Python2UnicodeFixer

### PR DESCRIPTION
**Pull request by allieus**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The general convention for Python encoding notation seems to be `# -*- coding: utf-8 -*-`, so you might want to consider that in your code.

**Comment by allieus** [comment]
@FichteFoll : Thanks. I've done. :)
 * added encoding notation : https://github.com/allieus/Python2UnicodeFixer/commit/d458edbe2d4f7aa2a3529d9d32a5dce9959c76ef
 * 1.0 tag : https://github.com/allieus/Python2UnicodeFixer/tree/1.0

**Comment by FichteFoll** [comment]
I was actually talking about [this line](https://github.com/allieus/Python2UnicodeFixer/blob/d458edbe2d4f7aa2a3529d9d32a5dce9959c76ef/Python2UnicodeFixer.py#L12). Also, semantic versions consist of three numeric parts.

**Comment by allieus** [comment]
I got mixed up. Thanks. :)

https://github.com/allieus/Python2UnicodeFixer/commit/df29ff4ed42975187fb9c4dcd91d343d817c2179

and, current version is 1.1.0.

**Pull request merged**
