### PR TITLE
Added AWS Helper plugin

### PR DESCRIPTION
**Pull request by cibinmathew**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is **AWS Helper**: https://github.com/cibinmathew/sublime-aws-helper

This plugin helps to validate IAM policy json from editor. It uses aws access analyser api. Error findings are listed in details in a separate tab. The plugin makes use of `accessanalyzer` from `boto3` library.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Thanks for your submission and sorry for taking a while to review it.

You didn't list boto3 in your dependencies, so it looks like your package won't work?

**Comment by cibinmathew** [comment]
> Thanks for your submission and sorry for taking a while to review it.
> 
> You didn't list boto3 in your dependencies, so it looks like your package won't work?

Thanks. Updated now

**Comment by braver** [comment]
Alright, please tag a new release with those latest changes.

**Comment by cibinmathew** [comment]
> Alright, please tag a new release with those latest changes.

Done

**Pull request merged**
