### PR TITLE
Add Executor

### PR DESCRIPTION
**Pull request by tonsky**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package lets you choose and run any executable from your working dirs inside Sublime Text.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by tonsky** [comment]
Video of package at work https://twitter.com/nikitonsky/status/1557889757212016641

**Comment by tonsky** [comment]
Anything I can do to speed it up? It’s not a large package by any means, and the most complicated parts are copied from `Default/exec.py`. Basically it just extends what `exec.py` does with dropdown which offers you every executable it can find

**Comment by braver** [comment]
Looks good, I've got nothing to add. There are several packages that "execute something", but this is its own thing 👍🏻

**Comment by tonsky** [comment]
Thank you 🙏

**Pull request merged**
