### PR TITLE
Adding a computercraft channel updated by me

### PR DESCRIPTION
**Pull request by Cyb3rWarri0r8**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please remove your `package-metadata.json` file. It will be generated by Package Control on installation.

Furthermore, [semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by FichteFoll** [comment]
Also, what's with @GravityScore's original https://packagecontrol.io/packages/ComputerCraft%20Package?

**Comment by Cyb3rWarri0r8** [comment]
I fixed the version number and removed the file. He hasn't been updating his package and I've made a few changes to it.

**Comment by FichteFoll** [comment]
I suggest you to be a bit more patient. You opened your pull request 17 hours ago, that's not a long time.

@GravityScore, just in case you don't want to maintain your package anymore I'm sure you could add @Cyb3rWarri0r8 as a contributor or transfer ownership.

**Comment by Cyb3rWarri0r8** [comment]
Okay. It was because I saw other activity on his Github.

-- 
Noah Kovacs
Sent with Airmail

On April 21, 2015 at 3:40:31 PM, FichteFoll (notifications@github.com) wrote:

I suggest you to be a bit more patient. You opened your pull request 17 hours ago, that's not a long time.

@GravityScore, just in case you don't want to maintain your package anymore I'm sure you could add @Cyb3rWarri0r8 as a contributor or transfer ownership.

**Comment by GravityScore** [comment]
@Cyb3rWarri0r8 Other GitHub activity doesn't indicate that I've looked at my notifications or had time to respond to them. A bit more patience would be much appreciated.

My preference would be to maintain the package under my account and simply merge pull requests from other collaborators. I am happy to merge @Cyb3rWarri0r8's pull request (after a few requested changes) and generate a new release.

**Comment by FichteFoll** [comment]
All right, I'm closing this then.

**Pull request closed without merging**
