### PR TITLE
add JustNotes package

### PR DESCRIPTION
**Pull request by sanykey**

### CODE REVIEW

**Comment by FichteFoll** [comment]
This is obviously a fork of https://github.com/aziz/PlainTasks.

Why? What are the differences?

**Comment by sanykey** [comment]
This is forks of two plugins:
https://github.com/aziz/PlainTasks
https://github.com/aziz/PlainNotes
At the moment the difference is small, but it is there in the syntax.

I want to add more functionality and remodel some existing functions and
themes.

Sorry,  I do not speak English well.

2015-12-20 18:20 GMT+03:00 FichteFoll <notifications@github.com>:

**Comment by FichteFoll** [comment]
I still don't get why this package is needed. Why can you not add missing functionality to one of these as a pull request?

**Comment by sanykey** [comment]
Because I not only want to add functionality, but also to remake some of
the features.
Surely the author will not approve of all my changes.
Why do people do the forks if not for this?

Ok, let us postpone this problem for later.
I will continue to work on the package, make some changes, and then we
decide whether it.
But if you are against it, I do not insist.

2015-12-20 19:43 GMT+03:00 FichteFoll <notifications@github.com>:

**Pull request closed without merging**
