### PR TITLE
Add Inline Fold plugin

### PR DESCRIPTION
**Pull request by predragnikolic**
- [X] I'm the package's author and/or maintainer.
- [X] I have have read [the docs][1].
- [X] I have tagged a release with a [semver][2] version number.
- [X] My package repo has a description and a README describing what it's for and how to use it.
- [X] My package doesn't add context menu entries. *
- [X] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...
meant to fold regions. This plugin can be useful when working with TailwindCSS to hide the long strings.

### CODE REVIEW

**Comment by braver** [comment]
Ha, don’t get me started on Tailwind and those classes 😂

Looks pretty neat and easy to use. 👍🏻 

From browsing the code, I’m not sure how well you’re guarding against views disappearing in the middle of an operation or after a debounce. In my experience anything even slightly async needs to do regular checks if views are still there (ie. the user didn’t cmd+w closed it, or maybe it was a transient view).

**Comment by braver** [comment]
You might need to think about your SEO a bit here. I didn’t understand what the package does until I read the full readme. It sounds like something especially useful to developers working with css, and perhaps it could also work with doc blocks? Anyway, maybe put some choice keywords in “labels” and hint at use cases in your repo description.

**Comment by predragnikolic** [comment]
Thanks!

> I’m not sure how well you’re guarding against views disappearing in the middle of an operation or after a debounce.

I pushed a [commit](https://github.com/predragnikolic/InlineFold/commit/96ba83273dcb782ec8eaaa49a4d3f004722e9ab9) for that.

Also I updated the README(with some examples) and added some labels on the Github repo.
Hopefully it is more clearer now.

**Comment by braver** [comment]
Looks good 👍🏻

**Comment by predragnikolic** [comment]
Thanks again :+1:

**Pull request merged**
