### PR TITLE
add Hearts of Iron 4 Syntax Definitions

### PR DESCRIPTION
**Pull request by docbuchanan**
Add listing of package as directed.

### CODE REVIEW

**Comment by vovkkk** [comment]
There is such package already: [Paradox](https://packagecontrol.io/packages/Paradox).

Not mention, that you should not keep package file in repo, but its content (i.e tmLanguage, PC will create package file automatically for users upon install)

**Comment by docbuchanan** [comment]
Yeah I'm not really sure how to do any of it.

On Monday, June 20, 2016, Vova Kolobok <notifications@github.com> wrote:

> There is such package already: Paradox
> <https://packagecontrol.io/packages/Paradox>.
>
> Not mention, that you should not keep package file in repo, but its
> content (i.e tmLanguage, PC will create package file automatically for
> users upon install)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/5613#issuecomment-227339333>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATINpGLmFOdLcKOa6iHX0f0Q66f70DJ-ks5qN2xPgaJpZM4I6VFK>
> .
>


-- 
*Matthew C. Buchanan*
210-240-8242
DocBuchanan@gmail.com

**Comment by FichteFoll** [comment]
@vovkkk so, does https://packagecontrol.io/packages/Paradox cover everything that this package *would add*?

@docbuchanan the repository is incompatible with Package Control. You must add the files directly to it, not the archive. Furthermore, you need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by vovkkk** [comment]
> so, does https://packagecontrol.io/packages/Paradox cover everything that this package would add?

Yes, I looked at the code it is basically the same essential definition for [Clauswitz](https://en.wikipedia.org/wiki/Paradox_Development_Studio#Clausewitz_Engine) syntax used in many games by Paradox Development Studio, including HoI4.

**Comment by wbond** [comment]
@docbuchanan What are you having trouble with? Do you still want to merge this, even though the Paradox package provides the same functionality?

**Comment by docbuchanan** [comment]
No sir I'll withdraw request sry

Matt Buchanan
925-549-5633

**Comment by wbond** [comment]
No problem.

**Pull request closed without merging**
