### PR TITLE
Rename NimLime to Nim

### PR DESCRIPTION
**Pull request by AmjadHD**
Pending approval https://github.com/nim-lang/NimLime/issues/181.

### CODE REVIEW

**Comment by braver** [comment]
By itself this change is fine. However, it looks like you're about to push a breaking change to users. Please consider using the [messages system](https://packagecontrol.io/docs/messaging) to tell users about what happened and how to deal with it.

**Comment by braver** [comment]
Please let us know when the approval came through, we can re-open the PR then.

**Comment by AmjadHD** [comment]
I'll go ahead and assume [this](https://github.com/nim-lang/NimLime/issues/181#issuecomment-2049388600) is an approval.

**Comment by braver** [comment]
I don't disagree :)

**Pull request merged**
