### PR TITLE
Added BetterAutoIndent package

### PR DESCRIPTION
**Pull request by BadStreff**
Please provide the following information:

 - Link to your code repository: https://github.com/BadStreff/IndentToAllBrackets
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/BadStreff/IndentToAllBrackets/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

Still new to making pull requests so please let me know if there is anything wrong.

### CODE REVIEW

**Comment by FichteFoll** [comment]
The current package name, to me, implies the packag could do more than it actually does. I suggest something along the lines of "IntentToAllBrackets", leaning on the `indent_to_bracket` setting it references.

**Comment by BadStreff** [comment]
I went ahead and changed the repo name per your recommendation. I agree BetterAutoIndent can be a bit misleading :)

Let me know if there is anything else you would like changed!

**Comment by FichteFoll** [comment]
## Report for IndentToAllBrackets #####################

### Repository checks ###

Reporting 1 failures:
- No semantic version tags found (semantic versions consist of exactly three numeric parts)

No warnings

### Package checks ###

No failures

Reporting 1 warnings:
- The binding ['enter'] is also defined in default bindings but is masked with a 'context'
    File: Default.sublime-keymap

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

The warning can be ignored, but the a tag is required.

**Comment by wbond** [comment]
@BadStreff Can you fix the issue identified by @FichteFoll?

**Comment by BadStreff** [comment]
Hey! Sorry it has been an extremely busy last few week at work. I guess I fixed it and forgot to send you guys a heads up. Sorry about that!

**Pull request merged**
