### PR TITLE
String Generator Plugin

### PR DESCRIPTION
**Pull request by 0rez91**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by 0rez91** [comment]
I created the tag to the project

**Comment by FichteFoll** [comment]
Please refrain from creating merge commits and rebase your branch instead - and only do it if the PR can't be merged without conflicts.

[Semantic versions](http://semver.org) consist of exactly three numeric parts.

You still have to change `"branch": "master"` to `"tags": true`.

**Comment by FichteFoll** [comment]
@0rez91 ping

**Pull request closed without merging**
