### PR TITLE
sublime-sql-snippets added

### PR DESCRIPTION
**Pull request by ancor-dev**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

Btw, the last table in your readme is broken.

**Comment by ancor-dev** [comment]
I am fixed version tag and readme file :)

**Comment by ancor-dev** [comment]
Should I create package.json?

**Comment by FichteFoll** [comment]
>Should I create package.json?

What for? Its only legitimate usage nowaday  is if you want to commercialize your package and choose to not host it on github or bitbucket.

**Pull request merged**
