### PR TITLE
Competitive Programming Plugin

### PR DESCRIPTION
**Pull request by egtoneyUK**
I wrote a plugin to be used to test competitive programming problems quickly against many test cases. Support for other languages like Java and Python is intended but not implemented yet.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please do not create new files.

Since you are running external executables (scripts), you need a `.no-sublime-package` file in your repository to tell Package Control to unpack the package.

**Comment by egtoneyUK** [comment]
Thank you so much for your help! What do you mean by your first comment of, "Please do not create new files."? I added in the .no-sublime-package to the master branch of my repo, is that all I needed to do?

**Comment by FichteFoll** [comment]
Your package should be added to `repository/c.json` because that is the package's first letter.

You'll also need to push a new tag with the most recent commit to make Package Control pick up the update.

**Comment by egtoneyUK** [comment]
Okay, it should be good now. Thanks for the help!

**Comment by FichteFoll** [comment]
Please remove `repository/package-info.json`.

**Comment by egtoneyUK** [comment]
It has been removed.

**Pull request merged**
