### PR TITLE
add sublime FileZilla

### PR DESCRIPTION
**Pull request by thecotne**

### CODE REVIEW

**Comment by FichteFoll** [comment]
https://packagecontrol.io/docs/submitting_a_package#Step_2

You can remove your `package.json`, it won't be looked at.

**Comment by thecotne** [comment]
after merging this i will remove `package.json`

will name `FileZilla` be better then `sublime FileZilla`?

i can't come up with better name

**Comment by FichteFoll** [comment]
Yes

**Comment by thecotne** [comment]
@FichteFoll merge please

**Pull request merged**
