### PR TITLE
Added new plugin - Command Runner

### PR DESCRIPTION
**Pull request by narent**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

How about all these?
https://packagecontrol.io/search/command
https://packagecontrol.io/search/run

**Comment by narent** [comment]
Nice to know about the pull append. 
I wanted something that will take text from the view rather than bringing up a new view to paste into. Those don't do what I want. 




On Wed, Jun 24, 2015 at 9:36 AM -0700, "FichteFoll" <notifications@github.com> wrote:












You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.



How about all these?

https://packagecontrol.io/search/command

https://packagecontrol.io/search/run

**Comment by FichteFoll** [comment]
Did you consider adding such functionality to one of the existing packages? It sounds useful to me having this and other features in the same package.

**Comment by FichteFoll** [comment]
@narent pin

**Pull request closed without merging**
