### PR TITLE
Add "Theme - Rainbow"

### PR DESCRIPTION
**Pull request by pradyunsg**

### CODE REVIEW

**Comment by pradyunsg** [comment]
Requesting review and merge.

**Comment by wbond** [comment]
The following code from Package Control is no longer relevant as of build 3112:

 - https://github.com/pradyunsg/Sublime-Rainbow-Theme/blob/master/1_reloader.py#L29-L46
 - https://github.com/pradyunsg/Sublime-Rainbow-Theme/blob/master/1_reloader.py#L86-L94
 - https://github.com/pradyunsg/Sublime-Rainbow-Theme/blob/master/1_reloader.py#L108-L125

I'm planning on removing them from Package Control in the near future also, although it is more important that PC get this 100% correct, since a failure results in Package Control getting stuck on a version forever.

**Comment by wbond** [comment]
You need to follow this license since you are using work from Soda: https://github.com/buymeasoda/soda-theme#license

**Comment by pradyunsg** [comment]
Thanks!

I have relicensed the package as CC BY-SA and added the appropriate attribution.

**Comment by pradyunsg** [comment]
I'll remove the said code once PC removes it. 

:smiley:

**Comment by wbond** [comment]
Package Control has it behind version guards:

 - https://github.com/wbond/package_control/blob/master/1_reloader.py#L29
 - https://github.com/wbond/package_control/blob/master/1_reloader.py#L239

**Comment by pradyunsg** [comment]
Ooh, :sweat_smile:. Fixed in https://github.com/pradyunsg/Sublime-Rainbow-Theme/commit/2154c51d7de2c811b770c3d56d34cb5550487607 .

Thanks a ton! Any other flaws you could point me to?

**Pull request merged**
