### PR TITLE
Added my packages to channel.json with others

### PR DESCRIPTION
**Pull request by evandrocoan**
Initially I was adding all my packages to the across the files, then I realized is easier just add them into one place, so I can easy know and manage what I have added to package control.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You only removed ~3 packages directly, so I assume this adds a lot of packages to the default channel that I need to review, correct?

**Comment by evandrocoan** [comment]
Yes, I put everything into one file, so I can easily find them all at one place. 

I tried to fix the parsing error with https://github.com/evandrocoan/SublimeStudioChannel/commit/35166546d94781163e23b46203bcf10f2e9c09f1, how to trigger the bot to recheck it if it is correct now?

**Comment by FichteFoll** [comment]
I tried re-triggering the review but only get 500 replies from the server currently.

I'm gonna hold off reviewing all these for a while because it will be *a lot* of work and I'd rather finish reviewing all the other PRs from different people first. I hope you understand.

**Comment by FichteFoll** [comment]
Sorry I didn't get around to reviewing these earlier btw, but it was just too much to handle back then and even now. I haven't checked out your other PR because I might miss it during the next review pass then.

**Comment by evandrocoan** [comment]
I cancelled this because it seems too much work for reviewing at once, then I will create pull requests one by one over time, so it is more simple to review. 

By now I send the one which is troubling me most:

1. https://github.com/wbond/package_control_channel/pull/6814 Fixes latest version breaks syntax highlighting

```
			"releases": [
				{
					"sublime_text": ">3144",
					"tags": true
				},
				{
					"sublime_text": "<=3144",
					"tags": "build3144support-"
				}
			]
``` 

Without merging this pull request, I cannot push the next version tag 2.0.0 without breaking the syntax for the stable version 3143. Also, anyone which installs it using build 3145 or superior will get everything messy.

**Pull request closed without merging**
