### PR TITLE
added GLE syntax highlighting to g.json

### PR DESCRIPTION
**Pull request by vlabella**
- [x ] I'm the package's author and/or maintainer.
- [ x] I have have read [the docs][1].
- [x ] I have tagged a release with a [semver][2] version number.
- [x ] My package repo has a description and a README describing what it's for and how to use it.
- [ x] My package doesn't add context menu entries. *
- [ x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x ] If my package is a syntax it doesn't also add a color scheme. ***
- [ x] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
You can ignore the warning from the bot.

Mostly looks good otherwise. However, your scopes should all end in .gle to make them easier to target specifically.

**Comment by braver** [comment]
👋🏻

**Comment by vlabella** [comment]
I just added .gle to the end of each scope and pushed the change.  Thanks for the reminder.

**Comment by braver** [comment]
Alright! Please tag a new release, if you don't make a tag package control won't see it and roll it out to users.

**Comment by vlabella** [comment]
Done

**Pull request merged**
