### PR TITLE
Update QML repository URL

### PR DESCRIPTION
**Pull request by ratijas**
New syntax, new repo, new maintainer

- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [ ] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Review by jfcherng — APPROVED** [review]

**Comment by FichteFoll** [comment]
Don't you want to prepare the entry for the new syntax currently in https://github.com/SublimeText/QML/pull/10 ? I.e. either restrict the supported ST version to ST3 or 4 (dependingg on the usage of branching) or add a legacy channel for the previous version that people on older ST versions can install.

**Comment by ratijas** [comment]
> Don't you want to prepare the entry for the new syntax currently in https://github.com/SublimeText/QML/pull/10 ? […]

I… dunno?  Do I?  I barely know what are you talking about. What is the market share of old ST installations, and what are possible reasons against upgrading?

Not to mention that this plugin's target audience are ST users who build KDE from git master (i.e. me, let's be realistic here xD)

**Comment by FichteFoll** [comment]
There isn't really a reason not to upgrade other than legacy OS support, or laziness, or in general being unable to update software. That said, none of this is a reason for us to break their existing, working installation by updating one of their packages to a version they cannot use anymore. For that reason, PC has a mechanism of declaring which ST builds are supported by a package and only allows installation (or updates) for supported builds.

Thus, you may either provide a legacy version for older ST builds pre-ST4 by adding a [separate release channel](https://github.com/wbond/package_control/blob/cfaaeb57612023e3679ecb7f8cd7ceac9f57990d/example-repository.json#L260-L288) or update the version selector to only allow ST4 versions (which currently says "all builds").

**Comment by ratijas** [comment]
tbh I don't think an old version is worth keeping. It didn't do much expect highlighting JavaScript keywords and operators, and _sometimes_ uppercase identifiers as classes.

However, specifying lower bound is a good idea. So, which predicate that would be? `"sublime_text": ">=4000"` ?

**Comment by FichteFoll** [comment]
I suggest limiting it to the first stable ST4 build or higher
.

**Comment by ratijas** [comment]
> the first stable ST4 build or higher

And that would be [`Build 4107`](https://www.sublimetext.com/download)?

**Comment by ratijas** [comment]
I checked the source code of this repo locally, grepped, and found a lot of plugins using 4107 as their lower bound. Makes sense to me.

**Pull request merged**
