### PR TITLE
Adding aw-watcher-sublime

### PR DESCRIPTION
**Pull request by kostasdizas**
aw-watcher-sublime reports the files and projects you're working on to the open source time tracker [ActivityWatch](https://activitywatch.net)

### CODE REVIEW

**Comment by FichteFoll** [comment]
The "sublime" part in "aw-watcher-sublime" is redundant for a package index for Sublime Text (and ST only). Please remove it.

**Comment by kostasdizas** [comment]
Fair enough, updated.

**Comment by FichteFoll** [comment]
You need to fix the package order now.

Like @packagecontrol-bot mentions, you have a `.no-sublime-package` file but I don't see any need for it as you don't bundle an executable or do other stuff that would require it. Please remove it.

**Comment by kostasdizas** [comment]
I think I misunderstood the purpose of that file. Removed.

**Pull request merged**
