### PR TITLE
Add Rainglow color themes.

### PR DESCRIPTION
**Pull request by daylerees**
This package provides 100+ of my Color themes for Sublime (also available on vscode and jetbrains repos).

Thanks for maintaining Package Control! :)

### CODE REVIEW

**Comment by daylerees** [comment]
Fixed the location. Didn't account for single letter package names. :)

**Comment by jrappen** [comment]
Why not use the new `sublime-color-scheme` format based on JSON?

---

For examples, do the following in `Build 3149` or later:

* Tools > Command palette > `View package file` > `sublime-color-scheme`

**Comment by FichteFoll** [comment]
An easy answer would be that it's only available for dev builds.

**Comment by daylerees** [comment]
@jrappen @FichteFoll thanks for the replies and the merge! I didn't know about the new format. Maybe I'll convert them when it's more widely available. :)

**Comment by jrappen** [comment]
@daylerees just a heads-up: you can now use [PackageDev](https://github.com/sublimetext/PackageDev) to convert the color scheme(s) to the **new** [color scheme format for ST3149+](https://www.sublimetext.com/docs/3/color_schemes.html)

**Pull request merged**
