### PR TITLE
CollaBroText plugin: Writing Collaborative code with commenting feature.

### PR DESCRIPTION
**Pull request by shantanu3637**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Platform-specific settings (`collabro (Linux).sublime-settings`) only work inside the default package. This must be named `collabro.sublime-settings`. (Or does it work for you?)

There's a hard-coded path [here](https://github.com/shantanu3637/CollaBroText/blob/e930f7b38d62fa37dd72efa83c659e726a09cc85/CollaBroText.py#L36)

You should store comment data in `sublime.cach_path()` instead of inside your package's directory.

**Comment by shantanu3637** [comment]
Regarding point 1, the settings only configure theme of the comments file, and it works for us as tested on Linux Ubuntu machines, hence not changing.

Regarding point 2 and 3 we have followed what you recommended and made changes accordingly in the latest commits. Would we need to create new version number so as to reflect the changes?

**Comment by FichteFoll** [comment]
You need to create the `sublime.cache_path() + '/CollaBroText'` folder before you try writing to a file within it.

Yes, you'll have to make a new release by pushing a tag for Package Control to pick up the changes.

**Comment by shantanu3637** [comment]
we've fixed the folder creation part in the latest commit. If there are no more issues from your side then we'll create a new tag.

**Comment by FichteFoll** [comment]
Looks good. You only need to push a new tags with the latest changes now.

**Comment by shantanu3637** [comment]
We've pushed a new tag v0.1.1 and incorporated the new changes in it. 👍

**Pull request merged**
