### PR TITLE
added sublime phinx package.

### PR DESCRIPTION
**Pull request by OwenMelbz**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by FichteFoll** [comment]
@OwenMelbz ping

**Comment by OwenMelbz** [comment]
Pong?

On Friday, 12 June 2015, FichteFoll <notifications@github.com> wrote:

> @OwenMelbz <https://github.com/OwenMelbz> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/package_control_channel/pull/4369#issuecomment-111500951>
> .
>


-- 
*Owen Melbourne*

www.owenmelbourne.com
www.the-dot.co.uk

**Comment by FichteFoll** [comment]
@OwenMelbz please address my notes from April 27th.

**Pull request closed without merging**
