### PR TITLE
Publish Panda to Package Control

### PR DESCRIPTION
**Pull request by siamak**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by siamak** [comment]
@FichteFoll I had pushed a valid version tag. Please check it ;)

**Comment by FichteFoll** [comment]
It doesn't show up on this page though: https://github.com/siamak/panda-syntax-sublime/tags

**Comment by siamak** [comment]
@FichteFoll You can check it now: https://github.com/siamak/panda-syntax-sublime/tags

**Comment by FichteFoll** [comment]
[Semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by siamak** [comment]
@FichteFoll Check this version: https://github.com/siamak/panda-syntax-sublime/releases/tag/v0.0.1

**Pull request merged**
