### PR TITLE
New boto3 version

### PR DESCRIPTION
**Pull request by revmischa**
https://github.com/revmischa/sublime-boto3/releases

### CODE REVIEW

**Comment by wbond** [comment]
The `"tags": true` part automatically scans the repo for tags. Adding a `version` won't do anything good here.

**Comment by revmischa** [comment]
What do I do if I depend on a newer version? Does everything get magically updated all the time?

**Comment by wbond** [comment]
Package Control *should* update any dependencies that a package has when the package is updated.

I have had a report that is not working properly. It is one of the few bugs to fix before I release the next version.

**Comment by revmischa** [comment]
I'm trying to use a feature in a newer version of boto3 in my plugin. I don't really get how to upgrade the dependency locally to make sure it fetches the latest-tagged sublime-boto3 version

**Comment by revmischa** [comment]
I pushed a new tag (v2.0.0) to https://github.com/revmischa/sublime-boto3/releases but when I run "satisfy dependencies" it says 
```
Package Control: Caching https://packagecontrol.io/channel_v3.json in /Users/bobo/Library/Application Support/Sublime Text 3/Packages/User/Package Control.cache/01524fae79697630d0454ba3fabd9414
Package Control: The dependency 'boto3' is installed and up to date (1.4.1); leaving alone
```
Making it hard to test this locally, unless I'm missing something?

**Comment by FichteFoll** [comment]
@revmischa did you try to update the dependency immediately after pushing the tags? Tag information is cached on Package Control's server side so that the github API rate limit is not hit. It can take up to one hour for new tags to be found by the crawler.

**Comment by revmischa** [comment]
I do not remember, probably. Any way to force that?

**Comment by FichteFoll** [comment]
Force what exactly?

**Comment by FichteFoll** [comment]
Force what exactly? The crawler to hit your repository?

No, you have no control over that.

**Pull request closed without merging**
