### PR TITLE
Change the name of the package

### PR DESCRIPTION
**Pull request by jfromaniello**
I think there is a problem with Sublime 3 when the name of the package contains a dot.

And I've always wanted to change from Node.js to CommonJS because that what really is.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Indeed, dots are not good in package names. I thought it didn't work on ST2 too, though.

May I encourage you to use tags as releasing strategy? https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by jfromaniello** [comment]
Sure, thanks

**Comment by jfromaniello** [comment]
done, I created the tag 1.0.0

Sorry for the delay

**Comment by FichteFoll** [comment]
No problem. You need to update the release here to include `"tags": true` instead of the branch line though.

**Comment by jfromaniello** [comment]
@FichteFoll thanks for your all help. 

It is done and I merged all the commits into one.

thanks again

**Comment by FichteFoll** [comment]
Oh, there is unfortunately another thing that I either forgot or you changed in the force-push, but when renaming you have to add the old name to a `previous_names` array.

**Comment by jfromaniello** [comment]
@FichteFoll done

**Pull request merged**
