### PR TITLE
Added EasyFileHider plugin

### PR DESCRIPTION
**Pull request by AustinTruex68**
I was not able to find a similar package. It essentially just gives quick access to modifying the file_exclude_patterns node in user settings.

### CODE REVIEW

**Comment by AustinTruex68** [comment]
I added the top level LICENSE file

**Comment by Thom1729** [comment]
What is the purpose of the placeholder file? I'm nearly sure that there must be a simpler way to do it.

**Comment by AustinTruex68** [comment]
@Thom1729 I put it there primarily to separate the settings, as to not overwrite anything already in my settings while I was developing, and liked the idea of having them separated.. It was something I threw together quickly to help out me and a couple co-workers on sublime. I am also not very familiar with the Sublime API and was not sure there was an easy way to fetch a specific setting.

**Comment by Thom1729** [comment]
You can create a package-specific settings file: just name it (e.g.) `EasyFileHider.sublime-settings`. Users can override the defaults with a `EasyFileHider.sublime-settings` file in their `User` package.

You can load the settings via `sublime.load_settings('EasyFileHider.sublime-settings')`. Then, you can persist any changes with `sublime.save_settings('EasyFileHider.sublime-settings')`.

The problem with modifying a file inside the package is that it won't work if the package is installed. It's possible to work around this, but it's much easier to use settings for this sort of thing.

**Comment by AustinTruex68** [comment]
Thanks for the quick response. I was not aware of that (like I said, slapped together a quick plugin for what I was currently doing, and it seemed to work fine on my machine)

I will go ahead and make those changes sometime this week (more likely this weekend) and post a new release to my repo.

Will I need to submit a new pull request, or would a comment on this thread suffice?

**Comment by Thom1729** [comment]
A comment is fine.

**Comment by AustinTruex68** [comment]
@Thom1729 Modified the package to use sublime settings rather than a json placeholder file. Ready for merge to package control.

**Comment by AustinTruex68** [comment]
Just wondering on this @Thom1729

**Comment by AustinTruex68** [comment]
Can anyone approve this... lol

**Pull request merged**
