### PR TITLE
Added new Demandware plugin

### PR DESCRIPTION
**Pull request by SGD1953**
This plugin provides upload capabilities to Demandware Commerce servers for Sublime Text

### CODE REVIEW

**Comment by FichteFoll** [comment]
I think this is similar to https://packagecontrol.io/packages/Entropy. What are the differences?

**Comment by SGD1953** [comment]
The authors and that this one is already used by a bunch of people, it was just not open source until now.

Am 02.07.2015 um 23:25 schrieb FichteFoll <notifications@github.com<mailto:notifications@github.com>>:


I think this is similar to https://packagecontrol.io/packages/Entropy. What are the differences?

-
Reply to this email directly or view it on GitHub<https://github.com/wbond/package_control_channel/pull/4580#issuecomment-118172349>.

This e-mail message and all attachments transmitted with it may contain privileged and/or confidential information intended solely for the use of the addressee(s). If the reader of this message is not the intended recipient, you are hereby notified that any reading, dissemination, distribution, copying, forwarding or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message, all attachments and all copies and backups thereof.

**Comment by FichteFoll** [comment]
So, what are the differences in functionality? If there aren't any or many, I suggest combining forces and working on a single package instead.

**Comment by SGD1953** [comment]
This is no longer relevant as @danechitoaie pointed out on https://github.com/wbond/package_control_channel/pull/4602#event-350923288

**Pull request closed without merging**
