### PR TITLE
Chinese-Localization

### PR DESCRIPTION
**Pull request by rexdf**
Chinese Translation for Sublime Text. Support MainMenu TabMenu ContextMenu,etc

### CODE REVIEW

**Comment by FichteFoll** [comment]
You may not use package names of default packages because it may cause inintended side effects. You need to think of another way of overriding the menus.

**Comment by rexdf** [comment]
Can you explain me how to hook the `plugin-finish-load` event? I find **emmet** and **package Control** have this hook. But I do not real understand.

**Comment by FichteFoll** [comment]
I suppose you mean `plugin_loaded`? That is needed because the APIs provided by the `sublime` module are not always available when plugins are loaded.

**Comment by rexdf** [comment]
I have tried in a different package name.  It will add the same id twice an english one and one chinese one.

Default is package namespace, if sublime find a differnet caption in different package, it create double items.

I try to load the `Main.sublime-menu` when all other package finished load just like **Package Control** checking network for updating.

Some package has an items like following. It will override my `Main.sublime-menu`. So I hope to load last. And the `Default/Main.sublime-menu` is the fit one.

```json
"caption": "Preferences",
"mnemonic": "n",
```

I have no other way to override the exist **Main.sublime-menu** by dynamic way. Maybe I should check about how **Package Control** disbale package Menu and enable it.

**Comment by rexdf** [comment]
I just rename `Default` --> `Default2`.  Double items.
sublime_trans2

**Comment by FichteFoll** [comment]
No, this is not what I meant. You are right, you need to override the default menu files by placing files somewhere in the "Default" package, but you need to do it in a different way than adding the package as "Default" to package control. Not only does that restrict any other localizations (since there can only be one package for each name), it also interferes with the user potentially overriding the default package on his own already. And this is all talking about ST3 only, because in ST2 this would go horribly wrong due to bad interactions with Package Control.

> e.g. a plugin that copies the menu files to the desired location.

**Comment by rexdf** [comment]
Ok. I got it.

**Comment by rexdf** [comment]
Add a python script to load the Main.menu

**Comment by FichteFoll** [comment]
That looks better :+1: 

You can access files in ST archives like this: `sublime.load_binary_resource("Packages/ChineseLocalization/EN.zip")`. If you do that you don't even need the `.no-sublime-package` file anymore, but I will accept this beforehand.

**Pull request merged**
