### PR TITLE
Add a isorted package

### PR DESCRIPTION
**Pull request by rimvaliulin**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [ ] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is [isorted](https://github.com/rimvaliulin/isorted)

My package is similar to [isort](https://github.com/thijsdezoete/sublime-text-isort-plugin). However it should still be added because it's seems like abandoned and use [fixed and old isort library v3.9.6](https://github.com/thijsdezoete/sublime-text-isort-plugin/blob/master/isort/__init__.py) (current isort version 5.10.1), which you can't easily update. My package works much more like [sublack](https://github.com/jgirardet/sublack) and use external [isort](https://github.com/PyCQA/isort) library. 

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
I can agree on adding this because it's a different (and cleaner) approach. However, make sure your command is listed in the command palette so people can find and use it easily.

**Comment by rimvaliulin** [comment]
I renamed package, and added missing files due global .gitignore.

**Comment by braver** [comment]
Alright, that’s better. I would like to propose removing the keybinding though. It’s a very generic combination that users or other packages might already be using for something else. At the very least it should be made conditional for python. But typically it’s a better idea to remove the binding itself and help users set up a binding if they want to. Your main menu entry should also have an entry for editing the keymap, and you could for instance comment out your binding. That way it’s presented as a suggestion and it makes it really easy for users to add it if they want to, or tweak the combination to their liking.

**Comment by rimvaliulin** [comment]
I maked keybindings optional.

**Comment by braver** [comment]
You need to tag a new release when you make changes. Only tags are picked up and distributed by package control.

**Comment by rimvaliulin** [comment]
I tagged a new release, is there anything wrong?

**Pull request merged**
