### PR TITLE
Magpie Script syntax highlighting for Sublime Text

### PR DESCRIPTION
**Pull request by bfraiche**
Automated reviews passed.

This package provides syntax highlighting for the domain specific language of Mapgie, a data lake tool created by [Silectis](http://silect.is "Silectis").

### CODE REVIEW

**Comment by bfraiche** [comment]
Hi @wbond,
Does the warning message from the automated test indicate that my pull request will not be approved?

Brendan

**Comment by jwortmann** [comment]
You can just replace `"sublime_text": "*",` with `"sublime_text": ">=3092",` to remove the warning, because `.sublime-syntax` files will only work in build 3092 or newer. Also close and reopen the PR to prompt the bot to repeat the test.

**Comment by bfraiche** [comment]
Updated "sublime_text": ">=3092"

**Comment by FichteFoll** [comment]
You should include the trailing `\n` character in your comment pop pattern so it gets the comment scope and prevents the auto completion popup from opening when typing at the end of a line.

**Comment by FichteFoll** [comment]
Since it's not really problematic, I'll merge the package as-is, but please consider my feedback.

**Pull request merged**
