### PR TITLE
Added Laravel Lang package

### PR DESCRIPTION
**Pull request by mariovalney**

### CODE REVIEW

**Comment by braver** [comment]
I'm not 100% what the utility is here, but I don't know Laravel very well.

In any case, usually you _don't_ want to ship keybindings. They tend to conflict with keybindings in other packages, or ones users configured for themselves. If you provide commands, they should show up in the command palette via a `.sublime-commands` file. That makes them discoverable, and in most cases is just as easy to use as a keybinding. You can then explain in the readme how users can set up keybindings if they want them.

Oh, and please add a license file.

**Comment by braver** [comment]
@mariovalney please respond to the feedback here if you still want to add your package to package control.

**Comment by mariovalney** [comment]
> I'm not 100% what the utility is here, but I don't know Laravel very well.

Hi. It's a simple package to help add translation functions during code writting.

> In any case, usually you _don't_ want to ship keybindings. They tend to conflict with keybindings in other packages, or ones users configured for themselves. 

Hi. Removed the default keybindings,

> Oh, and please add a license file.

Added.

--

Thanks for your comments and revision.

**Comment by braver** [comment]
Thanks for responding! So, for users to be able to find your commands, please add a Default.sublime-commands file (have a look here [for an example](https://github.com/SublimeLinter/SublimeLinter/blob/master/Default.sublime-commands)).

**Comment by mariovalney** [comment]
Done, sir!

**Comment by braver** [comment]
🍻

**Pull request merged**
