### PR TITLE
Added SEPath package. 

### PR DESCRIPTION
**Pull request by eudorokhov**
This script allows you to quickly open file paths from the sublime text 3 in the same place or in the file manager.

### CODE REVIEW

**Comment by Thom1729** [comment]
There is a built-in window command that opens a directory in the OS file browser: `open_dir`, with `dir` and optional `file` arguments. You should probably use this command rather than a custom `open_in_file_manager`. (This also removes the need for platform-specific code.)

**Comment by eudorokhov** [comment]
I used open_dir command. Thanks for help!)

**Comment by Thom1729** [comment]
It looks like you still need to `import os.path`.

**Comment by eudorokhov** [comment]
Of course! Fixed it :)

**Pull request merged**
