### PR TITLE
add ConvertChineseCharactersFor2 and ConvertChineseCharactersFor3

### PR DESCRIPTION
**Pull request by stormtea123**
Plugin for Sublime text 2 for convert chinese characters.
Plugin for Sublime text 3 for convert chinese characters.

### CODE REVIEW

**Comment by FichteFoll** [comment]
You can append commits to existing pull requests by pushing onto the branch you opened it from. Just FYI.

Please merge these two repos into one. If you want to maintain two different code bases, you should use different branches and tag prefixes to differentiate between releases.

**Comment by stormtea123** [comment]
@FichteFoll I have finished

**Comment by FichteFoll** [comment]
@stormtea123 what did you do? You're still hosting two repositories for the same package with slightly different code.

Please either merge the code bases into one branch on one repo or two branches on one repo. You can take a look at other packages that do this with tag-prefixes.

**Comment by stormtea123** [comment]
@FichteFoll It's two plugins, one for sublime text 2, another for sublime text 3.
Just started,  one package fore sublime text2 and sublime text 3, but `re.sub(ur"([\u4e00-\u9fa5]+)",toUnicode,s.decode('utf8'))` is not supported for sublime text 3.  So hosting two repositories.

My English is poor, some places may be expressed not so clear.

**Comment by stormtea123** [comment]
@FichteFoll Just now,  I have delete a repositories

**Pull request merged**
