### PR TITLE
Add Plugin Logger

### PR DESCRIPTION
**Pull request by kapitanluffy**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is Plugin Logger

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Ok, that’s maybe a bit niche, but cool. I’d prefer it not to print anything unless in a debug mode though (on load/unload).

**Comment by kapitanluffy** [comment]
Do you mean a `debug` setting? I made it so that it would use the default `_LogWriter` when the plugin is disabled in package control though.

**Comment by braver** [comment]
I meant for instance [print("Plugin Logger plugin loaded")](https://github.com/kapitanluffy/sublime-plugin-logger/blob/master/plugin_logger.py#L61), that line should be removed, or put behind a debug setting. Preferably packages don’t log anything during normal operation, and ST already has its own reporting about the loading/unloading of packages.

**Comment by kapitanluffy** [comment]
I see. I just removed it since it was unnecessary actually.

**Pull request merged**
