### PR TITLE
Add Wrap

### PR DESCRIPTION
**Pull request by futureprogrammer360**
Wrap allows users to wrap the text under cursor or selected with brackets (type is customizable). A placeholder will be inserted before the starting bracket. This is useful when passing a variable into a function/method call as argument or as an index into a list/array.

Example:
Original code: `x` (`x` is selected or under cursor)
After `Wrap`: `abc(x)` (`abc` is selected)

### CODE REVIEW

**Comment by futureprogrammer360** [comment]
I might be understanding things wrong, but aren't comments allowed in the configuration files?

The `sublime-keymap` files are there for users to use as reference when adding their own keybindings. I didn't ship the plugin with default keybindings since that was discouraged in previous packages. At the same time, I didn't want to delete the files altogether since that'd cause problems with the `Preferences: Wrap Key Bindings` command.

**Comment by futureprogrammer360** [comment]
Ah that makes sense, thank you @jwortmann!

**Comment by jwortmann** [comment]
You need another tag for packagecontrol-bot to see the changes.

**Comment by futureprogrammer360** [comment]
Right, forgot about that 😅

**Pull request merged**
