### PR TITLE
added ProjectNotes

### PR DESCRIPTION
**Pull request by budRich**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Please tell us a little about your package, and have a look at the bot test results.

**Comment by budRich** [comment]
i think the CI checks went through at first, but after i made the last commit (changed `"sublime_text": ">=3000",` to `"sublime_text": ">=4000",`) i got the red cross.

---

This package provides two commands:  
`project_notes_open` and `project_notes_list`  

---

## default settings

```JSON
{
  "notes_dir_path": "...",
  "note_file_name": "todo",
  "add_note_dir_to_project": true,
  "note_dir_name": "notes"
}
```
---

## project_notes_list

This will display a quickpanel listing the names
of projects which have a note named **$note_file_name**.
And open that file upon selection.

## project_notes_open

When the command is executed it will open the file:  
`$notes_dir_path/$PROJECT_NAME/$note_file_name`  

If there is no project associated with the active
window the command will not do anything.

If **notes_dir_path** is not a path to an existing
directory (example: `~/Documents/notes`), it will
default to: SUBLIME_PACKAGE_PATH/User/notes
(`~/sublime-text/Packages/User/notes`).

If **add_note_dir_to_project** is set to true the directory
containing the note will get added to the current project
with the display name defined for **note_dir_name**.

## Why?

I often find myself wanting to keep notes, lists
of links and other files related to a project, in its
own directory, *outside* the project, so i don't accidentally
commit those files to **git**.

This simple package makes that workflow seamless.

## keybinding

There is no keybindings enabled by default, I personally use
<key>Alt</key>+<key>n</key>:  
```JSON
{ "keys": ["alt+n"], "command": "project_notes_open" }
{ "keys": ["alt+shift+n"], "command": "project_notes_list" }
```

**Comment by braver** [comment]
Thanks for the information, I'll need to get back to that at a later time. For now though, your tags need to adhere to the [semver](https://semver.org) specification (ie. 1.0.0, 1.0.1 etc)

**Comment by budRich** [comment]
ok, i created a new release (no change in source) with a valid semver
https://github.com/budlime/ProjectNotes/releases/tag/2022.07.04

**Comment by braver** [comment]
Lol semver sucks indeed. y.m.d probably passes the regex, but that's not semver. The concept is that you (e.g.) update the first number only for new versions that break compatibility in some way, not just because it's a new year. This isn't a discussion about the merits of semver, users of Sublime Text and Package Control will have expectations about what those version numbers mean. If you don't want to play along, just number them 0.1.0, 0.2.0, 0.3.0 etc or something.

**Comment by budRich** [comment]
mfw releasing the 2022th version and is not believed.
also version 0.3.0 released.

**Comment by budRich** [comment]
ok now there are not tags.....

**Pull request merged**
