### PR TITLE
Add Behave

### PR DESCRIPTION
**Pull request by pkucmus**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with your chosen prefix `st3-`) to your repo.

**Comment by FichteFoll** [comment]
@pkucmus ping

**Comment by pkucmus** [comment]
Yes, forgive me - tough times. Please decline if it bothers you to much. I
should have time to fix over the weekend.

--
*PAWEŁ KUCMUS*
Team Leader / Senior Python Developer

pawel.kucmus@stxnext.pl
+48 531 090 500
--
*STX Next Sp. z o. o.*
Al. Piastów 3
64-920 Piła, Polska
www.stxnext.pl

**Comment by FichteFoll** [comment]
I will just close the pull request if you don't update in in the next 2 weeks.

**Pull request closed without merging**
