### PR TITLE
Add "Boxy Thmem" to "b.json" and delete "Vine Theme" from "v.json".

### PR DESCRIPTION
**Pull request by xufanchn**
- Add "Boxy Thmem" to "b.json" and delete "Vine Theme" from "v.json".
- After I learned about it again, I found that the original "Boxy Theme" has been deleted from the repository, so I deleted the "Add Vine Theme" request that I applied for the merge last time, and re-added "Boxy Theme" to "b.json" . Thanks again.

### CODE REVIEW

**Comment by braver** [comment]
It would be nice to have this one back. But I think the author should at least mention the original author.

**Comment by xufanchn** [comment]
> It would be nice to have this one back. But I think the author should at least mention the original author.

yep, I don't know if author tag supports multiple, so I changed author to original author.

**Comment by braver** [comment]
>  I don't know if author tag supports multiple

It will take an array of strings if you want.

**Comment by xufanchn** [comment]
> > I don't know if author tag supports multiple
> 
> It will take an array of strings if you want.

**Comment by jrappen** [comment]
⚠️ I highly doubt that theme supports all versions of Sublime Text.

---

Also, please respond to **braver**'s feedback from above.

**Comment by xufanchn** [comment]
> > I don't know if author tag supports multiple
> 
> It will take an array of strings if you want.

**Comment by xufanchn** [comment]
> ⚠️ I highly doubt that theme supports all versions of Sublime Text.
> 
> Also, please respond to **braver**'s feedback from above.

sorry, I don't want to submit this anymore.

**Comment by xufanchn** [comment]
> > I don't know if author tag supports multiple
> 
> It will take an array of strings if you want.

thank u. i will use if i want.

**Pull request closed without merging**
