### PR TITLE
change toml repo to Jayflux repo

### PR DESCRIPTION
**Pull request by Jayflux**

### CODE REVIEW

**Comment by Jayflux** [comment]
Gakai's repo seems to have gone a bit inactive

**Comment by FichteFoll** [comment]
We're not just handing over packages randomly. Their authors need to be inactive and not respond to our mentions for at last two weeks.

@Gakai please respond here (and in the pr at https://github.com/Gakai/sublime_toml_highlighting/pull/6).

**Comment by Jayflux** [comment]
@FichteFoll Thats fine

**Comment by Jayflux** [comment]
@FichteFoll  its been over 2 weeks now

**Comment by FichteFoll** [comment]
All right.

You need to push a new tag to the repository in order to trigger an update for users of the package and ship your changes.

**Comment by Jayflux** [comment]
Done

**Pull request merged**
