### PR TITLE
Added SublimeInChains - modified:   repository/s.json

### PR DESCRIPTION
**Pull request by hc-12**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your package name violates our naming guidelines: https://packagecontrol.io/docs/submitting_a_package#Step_2

**Comment by hc-12** [comment]
Oh that's a shame. I really like that name! Somehow just  __"In chains"__ doesn't have the same ring to it.

Anyway to make this as exception? I'm also open for ideas.

**Comment by FichteFoll** [comment]
I do not think the term "Sublime" provides anything significant to this package's name, so no exception here.

I though of "DontBreakTheChain" or maybe just "Chain".

**Comment by hc-12** [comment]
Will rename to chains

**Pull request closed without merging**
