### PR TITLE
Added simple-black

### PR DESCRIPTION
**Pull request by phil-bell**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x]  If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a plugin for the Python formatting library [Black](https://github.com/psf/black).

My package is similar to `python-black` however, it should still be added because it is a simpler implementation that relies on the user's installation of black rather than its own. The main benifits of this is it will reliably work the same as the black cli tool when it comes to config and users can easily pick which version of black they would like to use.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by jrappen** [comment]
Have you considered sending a pull request to `python-black` with your changes, instead? Asking because this is the third `black` package for Sublime. The first one died already. Not sure whether adding a third is the best way forward.

**Comment by jrappen** [comment]
Your README has a lot of typos. Maybe you could fix those?

**Comment by phil-bell** [comment]
Heya, `python-black` goes about their plugin in such a different way I would expect a PR to move it towards black cli would be too large to be accepted. I also think it would be difficult to make their implementation as consistent and adaptable as this approach. 

Sorry for the typos, I think I've fixed them all now.

**Comment by deathaxe** [comment]
Explicitly running `black` on a file can easily be achieved via build system.

The point of python-black is to provide a package without external dependencies.

**Comment by braver** [comment]
In fact, [Fmt](https://packagecontrol.io/packages/Fmt) probably already supports this. IMO, there is no need for specific formatter packages if they don't offer anything beyond simply running a file through the command line utility. Because Fmt does it better (more flexibility in settings, more continued support) and as @deathaxe says a package is entirely unnecessary anyway because build systems can already do the same.

**Pull request closed without merging**
