### PR TITLE
Add build system for Kotlin

### PR DESCRIPTION
**Pull request by shubhamaggarwal**
Added **build system** for **Kotlin** language. Uses Kotlin compiler installed locally on the system. I could not find any build system for Kotlin in package control, so I built this.

### CODE REVIEW

**Comment by shubhamaggarwal** [comment]
@wbond @FichteFoll How long before someone reviews this package? This is my first PR, so I apologize for the anxiousness.

**Comment by FichteFoll** [comment]
Time until a pull request is reviewed may vary.

Why not just add the build system to https://github.com/vkostyukov/kotlin-sublime-package?

Also, you should use `shell_cmd` (requires ST3) over `cmd` and `shell`.
FYI, since build 3127 you don't need to override `path` either, because since then ST inherits the environment from your login shell. The latest beta build is 3126 though, so you shouldn't remove it just yet.

**Comment by shubhamaggarwal** [comment]
@FichteFoll In order to make the build system usable with both ST2 and ST3, I used `cmd` and `shell`.  Should I close this request and then make another to https://github.com/vkostyukov/kotlin-sublime-package or leave this one as it is?

**Comment by FichteFoll** [comment]
Yes, imo it is best to add the build system to https://github.com/vkostyukov/kotlin-sublime-package. Just open a PR and see if the author is interested. If they are not, we can still go back to having it in a separate package.

If you want to support ST2, then not using `shell_cmd` is fine (required, actually).

**Comment by vkostyukov** [comment]
I'd be totally happy to see this embedded into kotlin-sublime-package. @shubhamaggarwal please, feel free to open a PR.

**Comment by shubhamaggarwal** [comment]
@vkostyukov I have opened a PR in your repo. Please review it.

**Comment by FichteFoll** [comment]
Thanks for your cooperation. I'm closing this, then.

**Pull request closed without merging**
