### PR TITLE
Add Sophia package

### PR DESCRIPTION
**Pull request by dincho**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [ ] Any commands are available via the command palette.
- [ ] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is for [Sophia](https://github.com/aeternity/aesophia) contract programming language for aeternity blockchain.

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
You should end all your scopes with something specific to your syntax, e.g. `.Sophia`, so that other packages and syntaxes can make adjustments for your particular syntax.

**Comment by ElectricRCAircraftGuy** [comment]
@dincho, in case you don't know what @braver is talking about, all he means is this, I think:

In this file: https://github.com/aeternity/sublime-sophia/blob/master/Sophia.sublime-syntax

Add `.sophia` to *every* single `scope` entry. Ex:

Change FROM this:

```yaml
  brackets:
    - match: \]
      scope: punctuation.section.brackets.end
      pop: true
    - include: main

  braces:
    - match: \}
      scope: punctuation.section.braces.end
      pop: true
    - include: main
```

TO this:

```yaml
  brackets:
    - match: \]
      scope: punctuation.section.brackets.end.sophia
      pop: true
    - include: main

  braces:
    - match: \}
      scope: punctuation.section.braces.end.sophia
      pop: true
    - include: main
```

This doesn't break anything for various Color Schemes, because the first matching color scheme name will be used, meaning that if a particular color scheme doesn't have an entry for `punctuation.section.brackets.end.sophia`, the formatting one level up at `punctuation.section.brackets.end` will be used instead, so long as it exists. If it doesn't exist in the color scheme, it goes up another level, and so-on, until a matching name is found, and that formatting will be used.

Adding `.sophia` to the end of all `scope`s allows color scheme maintainers and users to add customisations for your particular package by simply adding entries for your `*.sophia` scopes.

**Comment by ElectricRCAircraftGuy** [comment]
Good luck getting your package approved. I'll be submitting my own shortly.

**Comment by dincho** [comment]
The request seem clear and fair, I just forgot adding it in a rush, also I'm delaying a bit to service it as I'm working on other stuff right now.

**Comment by dincho** [comment]
@braver fixed, thank you

**Pull request merged**
