### PR TITLE
Add .vrscene syntax highlighting

### PR DESCRIPTION
**Pull request by poseidon4o**
Please provide the following information:

 - Link to your code repository: https://github.com/poseidon4o/VRayScene
 - Link to the tags page with at least one [semver](http://semver.org) tag:  https://github.com/poseidon4o/VRayScene/tags

### CODE REVIEW

**Comment by FichteFoll** [comment]
If the author of a  package does not reply to pull requests (via https://github.com/Aloiseau/VraySublime/pull/1), it is preferred if you take over the existing package instead of submitting the fork as an additional package. We have a 2 week grace period for package authors to object against their packages being replaced on package control for any reason. This very rarely happens, however.

Thus, @Aloiseau, if you would like to keep your package being listed, please comment here (and cooperate with @poseidon4o), otherwise we'll point the "Vray" package to @poseidon4o's fork.

**Comment by FichteFoll** [comment]
@poseidon4o would you take the necessary steps in this pull request to replace @Aloiseau's package?

**Comment by FichteFoll** [comment]
Actually, I see that @Aloiseau has merged the referenced pull request. Can I assume this matter is resolved?

**Comment by poseidon4o** [comment]
@FichteFoll the pull request is merged and everything is okay, sorry for not writing here when it was done.

**Pull request closed without merging**
