### PR TITLE
Added the FixedToggleFindPanel package

### PR DESCRIPTION
**Pull request by evandrocoan**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Ctrl+q is a default binding to close the application. Please use something else for your key chords.

**Comment by evandrocoan** [comment]
That keybind is pure evil at at the same time, a very handy/easy to access keybind to make combos. I prefer close it instead of changing it.

**Comment by FichteFoll** [comment]
> That keybind is pure evil at at the same time

I use it very frequently to maintain my ST session on restarts that consists of at least 2 windows. Regardless, it is not in the scope of packages to decide which key bindings a user needs or not.

**Comment by evandrocoan** [comment]
I kept hitting it by accident, closing my Sublime Text and losing my undo history of things, so evil for my tricky fingers.

To close Sublime Text (without losing my windows), I always hit `Alt + F -> Up -> Enter`:
bug2

There is not way I hit/type that by accident like `Ctrl+Q`, which is quite close to `Ctrl+W`.

**Pull request closed without merging**
