### PR TITLE
A simple plugin that interfaces with dpaste.org pastebin

### PR DESCRIPTION
**Pull request by adder46**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You must use tags and `"tags": true` for releases instead of your master branch.

What about these other packages? https://packagecontrol.io/search/dpaste

In your dependencies file you specify requests for versions 3119 and upwards, but here you also allow installation on ST2.

Users don't need to manually satisfy dependencies when installing via PC.

**Comment by adder46** [comment]
This package uses dpaste.org, some of other packages don't work at all (dpaste.de is shut down) or use dpaste.com.

**Comment by TheSecEng** [comment]
> This package uses dpaste.org, some of other packages don't work at all (dpaste.de is shut down) or use dpaste.com.

In addition to the question, when using `"tags": true` you'll need to generate a Release. That is what PC looks for when using `"tags": true`

**Comment by adder46** [comment]
I generated the release. What are the next steps?

**Comment by TheSecEng** [comment]
Thanks, now you just sit back and wait for it’s approval. Usually pretty quick.

**Comment by FichteFoll** [comment]
`0.1` is not a valid semantic version.

You need to remove the "sublime" part from your package name according to our guidelines, because it is obvious that the package is for sublime text on a sublime text package listing. The other packages I referenced predate this guideline.

**Comment by FichteFoll** [comment]
Since the dpaste API seems to pretty much be the same for all of these sites, you might also want to make the domain configurable. And the expiration time. And add more syntax mappings from the other packages.

Anyway, I will merge the package for now. These are just ideas for improvement.

**Pull request merged**
