### PR TITLE
Add laravel-blade-autocomplete package

### PR DESCRIPTION
**Pull request by ahmedash95**
Laravel Blade autocomplete is a simple package to autocomplete blade files when using laravel blade engine

### CODE REVIEW

**Comment by ahmedash95** [comment]
Tag added .. check again

**Comment by FichteFoll** [comment]
Note that you hardcode forward slashes in your code. You should look into using `os.path.join` and replace `os.path.sep` with `"."`.

**Comment by ahmedash95** [comment]
Hi @FichteFoll thanks for advice .. I did some enhancements and I think PR is ready to merge now 

Thanks

**Comment by FichteFoll** [comment]
You don't need to close files that you open in a context manager (i.e. with `with`), but it doesn't hurt in this case.

Remember that you have to push a new tag with your changes to make a new release.

**Comment by ahmedash95** [comment]
I drafted a new release, Thanks a lot

**Pull request merged**
