### PR TITLE
Add Tinkerwell plugin

### PR DESCRIPTION
**Pull request by mpociot**
The product can be found at https://tinkerwell.app

This is how the plugin looks like:

sublime

Thank you :)

### CODE REVIEW

**Comment by niladam** [comment]
For the ones that are looking to get this sorted faster, in Package Control you can add a repository.

Screenshot 2019-11-19 17 32 46

You are then able to install using your regular install procedure :)

**Comment by niladam** [comment]
hey @mpociot maybe take a look at this ?:) - Manually installing this package doesn't work. And as @wbond said on Twitter, this could be related to the obfuscation of the code..

**Comment by mpociot** [comment]
I updated the package, so it should work now

**Comment by wbond** [comment]
Yesterday when replying on twitter, I tried installing the package. You should not need a .no-sublime-package file from what I could tell. That is only used when you have a shared library or executable you need unpacked. Any `.sublime-*` files work fine in a `.sublime-package` and so do `.py` files.

**Comment by mpociot** [comment]
Yeah I also got rid of that file :)
Thank you!

**Comment by niladam** [comment]
@mpociot Manually installing it using the procedure above, i'm getting this:

Screenshot 2019-11-20 22 13 14

So, this appears to still not be working ?:(

**Comment by niladam** [comment]
@wbond, @mpociot  - this works now!:)

**Comment by erikverbeek** [comment]
Any update if/when we can get this added to Package Control?

**Comment by FichteFoll** [comment]
You should indeed specify a `readme` key for your package with a url to a raw markdown (or other markup? not sure which we support) file that will be rendered on the package's packagecontrol.io entry.

Other than this, I don't see a reason for the package not to work when installed in its current state.

**Pull request merged**
