### PR TITLE
Add CaretPositionNavigation package

### PR DESCRIPTION
**Pull request by rohanrhu**
Navigate prev-next over cursor position history in Sublime Text!

- Github: https://github.com/rohanrhu/CaretPositionNavigation/
- Tags: true
- Test: ok

### CODE REVIEW

**Comment by math2001** [comment]
Your package shouldn't include a 'package-metadata.json' file. Package Control will automatically create it for you

**Comment by rohanrhu** [comment]
I forgot git rm I did now :D

**Comment by FichteFoll** [comment]
## Report for CaretPositionNavigation #################

### Repository checks ###

Reporting 1 failures:
- No semantic version tags found (no tags found at all)

No warnings

### Package checks ###

Reporting 2 failures:
- Invalid modifier key 'cmd'
    File: Default (OSX).sublime-keymap
    Binding: {"args": {"nav": "prev"}, "command": "caret_pos_nav", "keys": ["cmd+shift+left"]}
- Invalid modifier key 'cmd'
    File: Default (OSX).sublime-keymap
    Binding: {"args": {"nav": "next"}, "command": "caret_pos_nav", "keys": ["cmd+shift+right"]}

Reporting 1 warnings:
- '.no-sublime-package' is defined. Please verify that it is *really* necessary

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

You may use `command` or `super` instead of `cmd` (latter is preferred).

How is this different from soft_undo and soft_redo?

**Comment by rohanrhu** [comment]
I fixed them. This plugin provide navigation over caret position history according to `threshold`.

**Comment by FichteFoll** [comment]
So, I just went over the source code and am still not much smarter. Please describe the differences between your plugin and what the `soft_undo` and `soft_redo` commands (built-in) provide. You can find these in the *Edit → Undo Selection* menu.

**Comment by rohanrhu** [comment]
It is different. It does not do "undo/redo". Only goes to prev-next cursor position according to specified `threshold`, not modifying file.

**Comment by FichteFoll** [comment]
Okay, so it does what `jump_back` and `jump_forward` do? (*Goto* menu)

**Comment by rohanrhu** [comment]
I did not know it. I tried now, it is nice but methinks there is not a threshold option. The plugin works more different. You can try and decide for merge or close pull request.

**Comment by FichteFoll** [comment]
Since having a threshold doesn't exactly strike as a "feature" to me, I'll close this PR. Furthermore, your plugin code is very naive about multiple selections from what I can tell from reading the code and the built-in commands handle these way better.

**Pull request closed without merging**
