### PR TITLE
Material Monokai Color Scheme

### PR DESCRIPTION
**Pull request by hlrossato**
Please provide the following information:

 - Link to your code repository: https://github.com/hlrossato/material-monokai
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/hlrossato/material-monokai/releases/tag/v1.0.0

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by wbond** [comment]
In some places you call this a color scheme (which is correct, for Sublime Text) and in other places, such as the name, you call it a theme. You should update them all to "color scheme", as a theme controls the tabs, buttons, icons, etc. of the Sublime Text interface.

**Comment by hlrossato** [comment]
Thanks for the tips @wbond . I've already updated the naming.

**Comment by wbond** [comment]
@hlrossato You need to change the `name` entry in the JSON of the PR

**Comment by hlrossato** [comment]
@wbond Now I think it's ok. Thanks a lot!

**Comment by hlrossato** [comment]
@wbond If I change something on the theme, do I need to create another tag and submit another PR? Sorry about the silly question but it's my first contribution to open source projects :)

**Comment by wbond** [comment]
No, once the package is in the channel, you just make a new release by pushing a tag up to your github repo. In other words: once the addition has been initially reviewed, you are set to make whatever changes you want to the package and release them.

**Comment by hlrossato** [comment]
Ok. So, basically it'll always use my latest tag version, right?! Many thanks!

**Pull request merged**
