### PR TITLE
Added Run In InDesign Plugin

### PR DESCRIPTION
**Pull request by vamitul**

### CODE REVIEW

**Comment by wbond** [comment]
A few things:

 1. You don't have any tags at https://github.com/vamitul/RunInIndesign/tags
 2. The readme indicates this is for ST3, but your pull request here indicates it will work with ST2
 3. The readme should be improved to help users figure out how to use the package

**Comment by vamitul** [comment]
1. I added the v1.0 tag
2. I thought "sublime_text": ">=3000", means is for ST3. 
3. Readme is in the works.

**Comment by wbond** [comment]
Yes, sorry, I must have mixed up your `sublime_text` operator with another PR. It is currently correct!

However, the tag you created will not work. Package Control uses semantic versioning, which means there need to be three parts to the version number. In other words, you need a tag like `1.0.0` not `1.0`.

**Comment by vamitul** [comment]
ok, sorry, i am a complete noob to github and open source projects (this was my first foray into it and also python). I have changed the tag, i hope it is ok. 
Thank you, and also thank you for all the work you did with the package manager, it is the best thing for sublime.

**Pull request merged**
