### PR TITLE
Added syncrow package info

### PR DESCRIPTION
**Pull request by Afzal7**
I created this plugin to ease the process of creating snippets and syncing them into my various machines. Details are in the repo readme file. Thanks.

### CODE REVIEW

**Comment by Afzal7** [comment]
I have made the necessary changes, how do i rerun the bot?

**Comment by FichteFoll** [comment]
1. It's kind of obvious, but you should mention in your readme that the snippet's contents are synced using a third-party remote (i.e. your server) and the contents can be read there.

2. You should use `os.path.join` when combining paths instead of hardcoding forward slashes.

3. I strongly suggest storing your snippets inside a subfolder of the User package instead of directly in the Packages folder. That one is supposed to contain whole packages (read: folders) and not individual resource files. A subfolder in `sublime.cache_path()` might work as well, but that needs to be tested.

4. `sublime.status_message` has been deprecated. Use `Window.status_message` instead.

5. You can infer a view's window object through its `.window()` method instead of using `sublime.active_window()`.

6. The `sublime.platform` print in your `plugin_loaded` can be removed.

7. I also suggest supplying a `.sublime-commands` file instead of a weird key binding (ctrl+shift+x seems quite arbitrary) because those are basically conflict-free.

8. Two menu items in the same menu and the same file should never have the same id.

9. I suggest splitting your command into two separate commands because they do fundamentally different things depending on a single argument.

**Comment by FichteFoll** [comment]
@Afzal7 ping

**Comment by Afzal7** [comment]
Hi @FichteFoll 

1. Readme updated.
2. `os.path.join` added.
3. Created a new folder _Syncrow Snippets_ for storing the snippets.
4. Using window.status_message
5. Still using `sublime.active_window()`, will update over time.
6. Cleaned `plugin_loaded` function
7. Left the shortcuts as `ctrl+shift+x `. I will update these in some time.
8. Given separate ids for both the menu options.

I will keep on updating the plugin over time. I hope, for now, everything is good to go. 

Thanks.

**Comment by FichteFoll** [comment]
Now you just need to push a new tag with the latest changes.

**Comment by Afzal7** [comment]
@FichteFoll  Done!

**Comment by Afzal7** [comment]
@FichteFoll Thanks for merging. Appreciate it.

**Pull request merged**
