### PR TITLE
added lodash modules snippets package

### PR DESCRIPTION
**Pull request by oriSomething**
it adds [lodash-modules-sublime](https://github.com/oriSomething/lodash-modules-sublime) to package control list of package.
this package contains snippets to make it easy to import only the functions you need.

### CODE REVIEW

**Comment by oriSomething** [comment]
someone can help. i read the travis CI results, and i don't understand why it failed. thanks!

**Comment by oriSomething** [comment]
nevermind

**Comment by FichteFoll** [comment]
Using branches for releases is deprecated and won't be accepted for new packages anymore: https://packagecontrol.io/docs/submitting_a_package#Step_4

**Comment by oriSomething** [comment]
hey, i'm using versioning by tags in github. i just don't think i get the things right maybe because english is not my native language. so can you please explain me, because, i've read this section, and i didn't got what i did wrong.
should i change something in the commit?
should i remove `package.json`? i already use tags for versioning

thanks

**Comment by FichteFoll** [comment]
You indeed have a tag pushed, but in this pull request you point to the master branch (see `"branch": "master"`). It should point to the tags (`"tags": true`).

**Pull request merged**
