### PR TITLE
Add AutoLISP package

### PR DESCRIPTION
**Pull request by divtiply**
AutoCAD AutoLISP programming language package for Sublime Text.
repo: https://github.com/divtiply/autolisp-sublime
tags:  https://github.com/divtiply/autolisp-sublime/tags

### CODE REVIEW

**Comment by math2001** [comment]
Why did you added the `AutoLISP.sublime-settings` with the `extension` option? The `fileTypes` key in the syntax definition doesn't work?

Could you also add a screenshot in your `README`?

**Comment by divtiply** [comment]
Fixed. Please review again.

**Comment by math2001** [comment]
👍 

I've look at the build system: why is it only available on windows? (sorry for not asking you this earlier)

I'm not able to tell if a syntax definition is good or not, but for the rest, it looks good! 😄

**Comment by FichteFoll** [comment]
Where does `autolisp.bat` come from? It's not in your repo and not mentioned as requirement in the readme.

**Comment by divtiply** [comment]
Added [autolisp-console](https://github.com/divtiply/autolisp-console) repository. Updated readme.

**Pull request merged**
