### PR TITLE
Add ModxElements package

### PR DESCRIPTION
**Pull request by Deum1teuli**

### CODE REVIEW

**Comment by FichteFoll** [comment]
ctrl+k, ctrl+c and ctrl+k, ctrl+k are default bindings for Windows and Linux. Please choose different bindings. Also, please check if you have colliding bindings with OSX.

**Comment by FichteFoll** [comment]
@Deum1teuli ping

**Comment by Deum1teuli** [comment]
Made a quick fix

**Comment by FichteFoll** [comment]
You only corrected the Linux bindings, and not the Linux and OSX bindings. Please address those as well.

(By the way, things like these are the reason why reviewing packages takes so long.)

**Comment by Deum1teuli** [comment]
I feel so wrong...sorry

**Pull request merged**
