### PR TITLE
Add Theme Switcher

### PR DESCRIPTION
**Pull request by chmln**
Counterpart abandoned and unmaintained, author inactive.

### CODE REVIEW

**Comment by FichteFoll** [comment]
I suggest taking over the [existing package](https://packagecontrol.io/packages/Themes%20Menu%20Switcher) reference instead of adding it alongside the abandoned package.
@geekpradd, if you don't reply to this within two weeks, we will assume that we are free to change the reference to @chmln's continuation of your project.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

You should also totally check out the results of `sublime.find_resources("*.sublime-theme")`.

**Comment by chmln** [comment]
Thank you @FichteFoll

See https://github.com/geekpradd/Theme-Switcher/issues/3#issuecomment-206241152
>@chmln, nice work with this new plugin. I'll put out a notice on this repo recommending users to use your plugin. 
I would have maintained this project but school and studies leave me with almost no time to pursue open source plugin development (I'm in high school with lots of other things that I am learning in Computer Science). 
It looks like you have used some of my code in your plugin (or atleast the structure). Not a problem with me, just give me proper credit (I did spend some time 1 and a half year back on this plugin).

I have updated the reference and pushed a release onto my repo.

**Comment by FichteFoll** [comment]
All right, that is enough for me.

You'll need to push a tag higher than `1.0.1` however (the current version) and [semantic versions](http://semver.org) consist of exactly three numeric parts.

**Comment by chmln** [comment]
> You'll need to push a tag higher than 1.0.1 however (the current version) and semantic versions consist of exactly three numeric parts.

Released [v1.0.2](https://github.com/chmln/sublime-text-theme-switcher-menu/releases/tag/v1.0.2) :zap:

**Pull request merged**
