### PR TITLE
Add SuperSettings

### PR DESCRIPTION
**Pull request by TechHawk**
Please provide the following information:

 - Link to your code repository: https://github.com/TechHawk/SublimeFolderSettings
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/TechHawk/SublimeFolderSettings/tags

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your package name is not okay. Please follow the submission guidlines.

**Comment by TechHawk** [comment]
Hi @FichteFoll 

Thank you very much for getting back to me!

Naming seems to be an interesting topic around here. The submission guidelines simply state that we should _try_ to avoid `Sublime` in the package name. I have also seen a lot of approved packages which start with`Sublime`. I therefore assumed, that it is okey to use `Sublime` in the name.

The reason why I chose to use the name `SublimeFolderSettings`: if I market the plugin with the name `FolderSettings` it is not clear on first sight that this is a plugin for Sublime Text. If I market it as `SublimeFolderSettings` but publish it as `FolderSettings` in Package Manager, people won't be able to find the plugin if they search for `SublimeFolderSettings`. I would obviously mention that in the documentation, but people sometimes don't read the documentation fully.

Do you have a suggestion to address my concern or can you simply approve it with the current name?

**Comment by FichteFoll** [comment]
>I have also seen a lot of approved packages which start withSublime.

Most of these packages date back to the very early days of Package Control many years ago. This guideline was established afterwards (still years ago) and is not applied retrospectively.

Market it as "FolderSettings for Sublime Text".

**Comment by FichteFoll** [comment]
@TechHawk ping

**Comment by TechHawk** [comment]
Hi @FichteFoll

Thank you for your patience!

I have renamed the package. You can find it here:
https://github.com/TechHawk/SuperSettings

I did not know if you needed a new pull request, so I have just committed the changes to the current request.

**Comment by FichteFoll** [comment]
Updating the PR is best.

**Comment by TechHawk** [comment]
Thank you!

**Pull request merged**
