### PR TITLE
add Jester package

### PR DESCRIPTION
**Pull request by absszero**
A runner for Jest testing framework.

### CODE REVIEW

**Comment by braver** [comment]
Eh, this PR now adds two packages, is that intentional?

**Comment by absszero** [comment]
> Eh, this PR now adds two packages, is that intentional?

My fault. I have fixed it.

**Comment by braver** [comment]
Note that you can exclude some files from the resulting package using `.gitattributes` with "export-ignore", e.g. your test files and png's, saving on space and bandwidth.
Please check the readme or examples on how to set up your Settings menu entries so they open in split view.
You might want to introduce a setting for debugging instead of the env var, so that users can also debug easily.
Props for putting the keybinding stuff in the README 👍🏻 
It's not 100% clear to me what testing framework your package is for, but it looks like it could be a replacement for the existing [Jest package](https://packagecontrol.io/packages/Jest)?

**Comment by absszero** [comment]
> Note that you can exclude some files from the resulting package using `.gitattributes` with "export-ignore", e.g. your test files and png's, saving on space and bandwidth. Please check the readme or examples on how to set up your Settings menu entries so they open in split view. You might want to introduce a setting for debugging instead of the env var, so that users can also debug easily. Props for putting the keybinding stuff in the README 👍🏻 It's not 100% clear to me what testing framework your package is for, but it looks like it could be a replacement for the existing [Jest package](https://packagecontrol.io/packages/Jest)?

Thank you, I have modified it by your feedback.
the Jest is a snippet package. and the Jester package is a runner package to run js test files.

**Comment by braver** [comment]
Sorry for letting this sit here for so long, we've been struggling with capacity a bit. My last remaining worry is that your package ships with keybindings that seem like very common/popular bindings to me, and no Mac-specific bindings. You have a high risk of overruling bindings of other packages. Our [current guideline](https://raw.githubusercontent.com/wbond/package_control_channel/master/.github/PULL_REQUEST_TEMPLATE.md) is this:

> There aren't enough keys for all packages,
     you'd risk overriding those of other packages.
     You can put commented out suggestions in a keymap file, 
     and/or explain how to create bindings in your README.

**Comment by absszero** [comment]
> Sorry for letting this sit here for so long, we've been struggling with capacity a bit. My last remaining worry is that your package ships with keybindings that seem like very common/popular bindings to me, and no Mac-specific bindings. You have a high risk of overruling bindings of other packages. Our [current guideline](https://raw.githubusercontent.com/wbond/package_control_channel/master/.github/PULL_REQUEST_TEMPLATE.md) is this:
> 
> > There aren't enough keys for all packages,
> > you'd risk overriding those of other packages.
> > You can put commented out suggestions in a keymap file,
> > and/or explain how to create bindings in your README.

I understood your concern and removed the default keymap file.
Also I explained how to binding these in the README file.

**Comment by braver** [comment]
🎉

**Pull request merged**
