### PR TITLE
adding moon-light theme

### PR DESCRIPTION
**Pull request by developedby-sam**

### CODE REVIEW

**Comment by developedby-sam** [comment]
This is a sublime theme and comes with its own color scheme, which is dark yet with vibrant colors. The colors are a lot easy on eyes than the themes already out there..!

**Comment by braver** [comment]
Please don't change any entries other than the one you want to add!

**Comment by developedby-sam** [comment]
> Please don't change any entries other than the one you want to add!

yeah, I guess it got auto formated..
should i do another commit or start a new pull request.?

**Comment by braver** [comment]
Another commit is fine. In the end we’ll just squash everything anyway.

**Comment by developedby-sam** [comment]
I guess, it is fixed now.

**Comment by braver** [comment]
Yes, all that remains is to tag your first release!

**Comment by jwortmann** [comment]
A few hints:
* The resource path of the package will be determined by the "name" property in this PR, i.e. it will be `Packages/Mooon Light Theme/`. There are a few invalid paths in your package, for example in "Widget - mooon-light.sublime-settings": `"color_scheme": "Packages/mooon-light/widgets/Widget - mooon-light.stTheme",`.
* The textures in the theme refer to `ayu/assets/`, which means that the theme only works if "ayu" is installed as well. I guess you would either want to describe that in the Readme, or use only assets from inside your package.
* A `dependencies.json` file without any dependencies in it has no real use
* The names of the theme and color scheme in the command palette are taken from the file names. You might want to adjust the filenames unless you want them to be lowercase and with the dash
* I would say the "popup_css" in the color scheme can be a bit of a "danger zone", because it can have unintended side effects if used. Here is how the phantoms for build errors from Default/exec.py on ST3 currently look with your color scheme:
screenshot

**Comment by developedby-sam** [comment]
> Yes, all that remains is to tag your first release!

yeah! Done.

**Comment by developedby-sam** [comment]
> A few hints:
> 
>     * The resource path of the package will be determined by the "name" property in this PR, i.e. it will be `Packages/Mooon Light Theme/`. There are a few invalid paths in your package, for example in "Widget - mooon-light.sublime-settings": `"color_scheme": "Packages/mooon-light/widgets/Widget - mooon-light.stTheme",`.
> 
>     * The textures in the theme refer to `ayu/assets/`, which means that the theme only works if "ayu" is installed as well. I guess you would either want to describe that in the Readme, or use only assets from inside your package.
> 
>     * A `dependencies.json` file without any dependencies in it has no real use
> 
>     * The names of the theme and color scheme in the command palette are taken from the file names. You might want to adjust the filenames unless you want them to be lowercase and with the dash
> 
>     * I would say the "popup_css" in the color scheme can be a bit of a "danger zone", because it can have unintended side effects if used. Here is how the phantoms for build errors from Default/exec.py on ST3 currently look with your color scheme:
>       screenshot
> 
>     * The files in the "images" folders are several MB large. You should use a .gitattributes file with `export-ignore` to not distribute them when the package is installed from Package Control

Thanks for the hints 😃, fixed most of them
Please review once again.

**Comment by jwortmann** [comment]
You should not "export-ignore" the LICENSE file, it needs to be distributed with the package.

Besides that, the package looks good to me. The final approval is required from braver, of course.

**Comment by developedby-sam** [comment]
yup!! thanks!! 😄

**Comment by braver** [comment]
I’m about to hit “merge” just to get it out of the way, but be sure to actually those final changes. Package control will only pick up on your tags, so those file path fixes won’t reach your users unless you tag a release.

**Comment by developedby-sam** [comment]
> I’m about to hit “merge” just to get it out of the way, but be sure to actually those final changes. Package control will only pick up on your tags, so those file path fixes won’t reach your users unless you tag a release.

I created new tag with all those changes, when those file path fixes will be able to reach to the users?

**Pull request merged**
