### PR TITLE
added Arturo Programming Language package

### PR DESCRIPTION
**Pull request by drkameleon**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Don't provide an `extensions` setting with your Package. That is supposed to be configured by the user for local overrides of the default file type associations.

You should include `\n` in your pop match of the comment scope in order to prevent the completion popup from opening when at the end of a line.

**Comment by drkameleon** [comment]
> Don't provide an `extensions` setting with your Package. That is supposed to be configured by the user for local overrides of the default file type associations.
> 
> You should include `\n` in your pop match of the comment scope in order to prevent the completion popup from opening when at the end of a line.

Just fixed it.

**Comment by FichteFoll** [comment]
See my comment at https://github.com/arturo-lang/art-sublimetext-package/commit/7bd0284f18c10d6b246058ad015d43778d4ba1cb#diff-27fc91ad0e45d535e68bc9167c6feda4R87.

Please push a new tags with the changes.

**Comment by FichteFoll** [comment]
@drkameleon ping

**Comment by drkameleon** [comment]
> @drkameleon ping

(I think) I've just fixed it! Please let me know.

P.S. Happy new year!

**Comment by FichteFoll** [comment]
The new tag should be listed on https://github.com/arturo-lang/art-sublimetext-package/tags and point to your latest commit.

**Comment by drkameleon** [comment]
> The new tag should be listed on https://github.com/arturo-lang/art-sublimetext-package/tags and point to your latest commit.

I've just added a new 0.1.2 release, as you said.

**Pull request merged**
