### PR TITLE
Org agenda

### PR DESCRIPTION
**Pull request by robinchenyu**
add org agenda for orgmode.

### CODE REVIEW

**Comment by FichteFoll** [comment]
The url you point to 404s.

**Comment by robinchenyu** [comment]
have fixed it. Thanks

**Comment by FichteFoll** [comment]
`.sublime-syntax` files are only available starting build 3092. Please update the ST requirements to that.

I also don't see a particular need for your package to only be available to Windows, so you might want to change that too.

**Comment by robinchenyu** [comment]
fixed

**Pull request merged**
