### PR TITLE
Colourful bright on dark themes inspired by RainbowDrops

### PR DESCRIPTION
**Pull request by AhanM**

### CODE REVIEW

**Comment by wbond** [comment]
You need to remove `packages.json` from your repository. 

You also need to create a tag that is a valid [semver](http://semver.org), otherwise no one will be able to install it.

**Comment by AhanM** [comment]
I just made the changes.

I apologise for the inconvenience; I'm new to submitting packages to package control.

**Comment by AhanM** [comment]
I can't see it yet. 
Does it take time for the package to register?

**Comment by wbond** [comment]
Yes, up to an hour.

**Pull request merged**
