### PR TITLE
Add BrightScript Booster package

### PR DESCRIPTION
**Pull request by lukewang1024**
To provide a complete BrightScript language support with common snippets.

### CODE REVIEW

**Comment by FichteFoll** [comment]
How is this different from the https://packagecontrol.io/packages/BrightScript package?

**Comment by lukewang1024** [comment]
This package adopts the language definition from [VBScript](https://github.com/SublimeText/VBScript), which provides better language support than the existing `BrightScript` package. Also it has many snippets that could make coding faster.

**Comment by FichteFoll** [comment]
@hastinbe what do you think of incorporating these improvements into your packages or instead have @lukewang1024's package replace yours in the list?

**Comment by hastinbe** [comment]
@FichteFoll this is a copy of the VBScript package with the file type coverage changed. While BrightScript and VBScript are similar they are also very different. For example, this package uses the keywords for VBScript, most of which don't exist in BrightScript, and consequentially also doesn't have keywords that are unique to BrightScript. In addition it contains highlighting mismatches because of nuances in syntax. While I welcome others to improve upon BrightScript, this package does not really provide it. Instead I would encourage @lukewang1024 to fork and incorporate what he/she considers improvements from the VBScript package and re-implement them to work properly for BrightScript and create a PR.

**Comment by FichteFoll** [comment]
@hastinbe thanks for your insights. Your proposal sounds very good to me. @lukewang1024, what do you think about this?

**Comment by lukewang1024** [comment]
Thanks for the insights, @hastinbe. I have not used VBScript myself and was not aware of the difference between them. I think I can start by creating a PR with the snippets. As for the language definition, I am not familiar with how it works and how BrightScript and VBScript differs at the moment so may not tough that in near future.
Closing this one. Thanks @FichteFoll.

**Pull request closed without merging**
