### PR TITLE
Add "Bigine" for Sublime Text 3

### PR DESCRIPTION
**Pull request by snakevil**

### CODE REVIEW

**Comment by FichteFoll** [comment]
What does this do? Please provide a readme for your package (or at least explain it to me).

**Comment by snakevil** [comment]
Sorry for that, I'll add a readme in the next release.

This package is aimed to provide a whole work flow for writing our Bigine (an chinese AVG engine) scripts.

**Comment by FichteFoll** [comment]
Tip for opening the changelog from the menu: You could just run `open_file` with `"file": "${packages}/Bigine/Resources/CHANGELOG.md"`.

**Comment by snakevil** [comment]
Got it! Thanks~

**Pull request merged**
