### PR TITLE
Add Chromium X-Refs Plugin

### PR DESCRIPTION
**Pull request by karlinjf**
Please provide the following information:

 - Link to your code repository: https://github.com/karlinjf/ChromiumXRefs
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/karlinjf/ChromiumXRefs/releases

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by FichteFoll** [comment]
## Report for ChromiumXRefs ###########################

### Repository checks ###

No failures

Reporting 1 warnings:
- Only found pre-release tags.

### Package checks ###

No failures

Reporting 1 warnings:
- It is not advised to specify mousemaps because of how limited the configuration options are. Instead, suggest the user to add specific bindings to their User package.
    File: Default.sublime-mousemap

For more details on the report messages (for example how to resolve them), go to:
https://github.com/packagecontrol/package_reviewer/wiki

---

`readme` must point to a raw file. Just remove it since PC will pick your README.md by default.

**Comment by karlinjf** [comment]
Addressed all warnings and comments, thanks!

**Comment by FichteFoll** [comment]
You didn't push a new (non-pre-release) tag, though. Currently your package won't be installable by default.

**Comment by karlinjf** [comment]
I pushed 1.0.0. Is that not pre-release?

https://github.com/karlinjf/ChromiumXRefs/releases/tag/1.0.0

**Comment by FichteFoll** [comment]
That's not a pre-release, but exactly what we want here.

**Comment by karlinjf** [comment]
Thanks!

**Pull request merged**
