### PR TITLE
add LikeGit / remove Smart Repeat

### PR DESCRIPTION
**Pull request by poucotm**

### CODE REVIEW

**Comment by Thom1729** [comment]
@poucotm You should add a license.

**Comment by Thom1729** [comment]
Why remove Smart Repeat?

Why manually reload modules in LikeGit?

**Comment by poucotm** [comment]
I added the License. 

Why remove Smart Repeat? >> no body uses it. 
Why manually reload modules in LikeGit? >> to ensure updates

**Comment by Thom1729** [comment]
What's the use case for the reloading logic? If it's to make it easier to work on , then [AutomaticPackageReloader](https://github.com/randy3k/AutomaticPackageReloader) would do the trick. Hot-reloading Python is really fiddly and error-prone, so if it's possible to offload the reloading logic to a “standard” implementation, that would be greatly preferable.

**Comment by FichteFoll** [comment]
Unfortunately, because you intend to run `osx/terminal.sh`, it needs to be available as a file and requires the package to be unpacked. Add a `.no-sublime-package` file to tell PC this. Alas, I'm unsure if writing a temporary theme file at `LikeGit/theme/LikeGit.tmTheme` is a good idea, because it will be removed on each update, but it might just work out here. You can try using the cache folder instead (`sublime.cache_path()`).

**Comment by FichteFoll** [comment]
@poucotm ping

**Comment by poucotm** [comment]
I added .no-sublime-package. 
As I know, it cannot apply color_scheme setting for a theme file in cache_path().
I changed to use Packages/User folder instead. Thanks for comment !

**Comment by FichteFoll** [comment]
`os.makedirs` is recursive and with the `exist_ok` parameter you don't need to check whether it exists already.

**Pull request merged**
