### PR TITLE
Adding a new custom color scheme called 10-percent-too-dull

### PR DESCRIPTION
**Pull request by whatnickcodes**

### CODE REVIEW

**Comment by whatnickcodes** [comment]
Woohoo... passed.

How long does it usually take to merge in? Was trying to publish this post tomorrow but obviously whenever you can get to it. Thanks for everything

**Comment by whatnickcodes** [comment]
Hey - Is this not allowed or something?

**Comment by whatnickcodes** [comment]
Is there a reason this won't get put in?

**Comment by rubensfernandes** [comment]
Is there a reason this won't get put in?
21 days.... Omg

**Pull request merged**
