### PR TITLE
Added Docs plugin

### PR DESCRIPTION
**Pull request by joaopjt**

### CODE REVIEW

**Comment by Thom1729** [comment]
Are there other packages that perform a similar function?

The name “Docs” isn't very descriptive. You should probably use something a little more specific.

Instead of using a custom `.docsconfig` file, why not use project settings?

Building paths with string concatenation is unlikely to work cross-platform.

**Comment by joaopjt** [comment]
I've got changed the plugin name from 'Docs' to 'npmDocs'.

I`m following the exemple of 'waka-time-dashboard'.
Some people just open the folder, instead of creating a project

**Comment by FichteFoll** [comment]
>Building paths with string concatenation is unlikely to work cross-platform.

Fortunately it will in this particular case, as all usages of `/` here are covered by Windows-internal API.

However:

- You should look into using instance variables instead of the `PACKAGES` global.
- You should check for `index == -1` before anything else in `on_done`.
- Remove your `.no-sublime-package` file.

Also, what do you think of "node_modules Readme" as the package name?

**Comment by Thom1729** [comment]
@joaopjt ping

**Pull request closed without merging**
