### PR TITLE
add donation links for Sass and LESS

### PR DESCRIPTION
**Pull request by braver**
adds Paypal donation links for Sass and LESS packages.

### CODE REVIEW

**Comment by Thom1729** [comment]
Did you mean to change the LESS version compatibility?

**Comment by braver** [comment]
@Thom1729 Yes, it should have been done earlier because it changed to the new sublime-syntax format. Sorry, should have added a comment here as well.

**Comment by FichteFoll** [comment]
FYI you still have https://sublime.wbond.net/packages/LESS in the repo's url.

**Comment by braver** [comment]
Yeah, I've got enough access to manage the codebase and releases, but that part of the repo setup is outside my jurisdiction. Also don't care enough to do something about it, it's like a neat little indicator that this package has been around for that long.

**Pull request merged**
