### PR TITLE
Add Umajin package

### PR DESCRIPTION
**Pull request by AdamHarte**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You have to push a valid [semantic version](http://semver.org) tag (with optional leading `v`) to your repo.

**Comment by AdamHarte** [comment]
@FichteFoll Sorry about that. I have never had to push a tag before, and though it would just happen with a normal git push. But the tag is there now.

**Comment by FichteFoll** [comment]
Note that, by default, pre-release versions are not installed by Package Control. This has to be enabled in its settings before attemption to install your package. I suggest releasing an non-prerelease version.

**Comment by AdamHarte** [comment]
@FichteFoll I have created a new 1.0.0 tag for my repo. Do I need to do anything else for Package Control to see this new version?

**Comment by FichteFoll** [comment]
No, Package Control will automatically find the new version up to one hour after you pushed it.

**Pull request merged**
