### PR TITLE
Add CopyFilenameWithLineNumbers plugin

### PR DESCRIPTION
**Pull request by maxx27**

### CODE REVIEW

**Comment by maxx27** [comment]
I have added the tag v1.0.0

**Comment by FichteFoll** [comment]
You mention quite a few similar packages in your readme, out of which two are already installable via Package Control. Could you outline the motivation behind this package and how it is different to these other packages?

**Comment by FichteFoll** [comment]
@maxx27 ping

**Comment by maxx27** [comment]
> You mention quite a few similar packages in your readme, out of which two are already installable via Package Control. Could you outline the motivation behind this package and how it is different to these other packages?

@FichteFoll : Yes, I will update README with differences with them.
Sorry for delay.

**Pull request closed without merging**
