### PR TITLE
added STexercism

### PR DESCRIPTION
**Pull request by thosgood**

### CODE REVIEW

**Comment by Thom1729** [comment]
You should pick more specific names for the commands than "submit" and "open".

**Comment by thosgood** [comment]
ok, I've changed them

**Comment by FichteFoll** [comment]
I suggest prefixing your commands with `exercism_` to prevent any chances of name collisions.
You also need to push a new tag with the latest changes.

**Comment by FichteFoll** [comment]
It just eluded my mind for some reason that this package uses "ST" as the prefix, which not technically but  violates our naming guidelines (by including a name reference to Sublime Text). You don't need that on a package repository for Sublime Text.

Please re-add the package as just "exercism" and add a `previous_names` entry to that while removing the one I just merged. Otherwise I will do it in a few days most likely.

**Pull request merged**
