### PR TITLE
update sublime3unityshader

### PR DESCRIPTION
**Pull request by maxleungcode**

### CODE REVIEW

**Comment by maxleungcode** [comment]
add name

**Comment by maxleungcode** [comment]
add name

**Comment by FichteFoll** [comment]
How does this compare to https://packagecontrol.io/packages/Unity3D%20Shader%20Highlighter%20and%20Snippets?

Your name is inappropriate https://packagecontrol.io/docs/submitting_a_package#Step_2.

You'll need to change `"branch": "master"` to `"tags": true` and use [tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging) to create releases and push valid [**semantic version**](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by FichteFoll** [comment]
@maxleungcode ping

**Pull request closed without merging**
