### PR TITLE
Adding sublime plugin for https://cheat.sh/ service.

### PR DESCRIPTION
**Pull request by gauravk-in**
## Cheat.sh
This is a sublime plugin for http://cht.sh/ service from https://github.com/chubin/cheat.sh. Using Cheat.sh programmers can find answers to their questions easily and efficiently, directly in the editor or the terminal, without having to open the browser. This helps in improving productivity, by reducing distractions. 

## Sublime Plugin
With this plugin, Sublime users will be able to take advantage of this service. The users can use this plugin in 3 ways. 
* Show top 3 answers for a query in a new tab. [Cmd + c + s]
* Insert the top answer for a query directly in the editor. [Cmd + c + i]
* Replace the query in the editor with the top answer. [Cmd + c + r]

The user can get the answers with or without helpful comments. To get answers without comments, users must press the "Alt" key instead of the "Cmd" key.

Going ahead, new features and improvements will be added to this plugin.

### CODE REVIEW

**Comment by gauravk-in** [comment]
I have now added the semver tag. Can someone please let me know how to restart the test?

**Comment by tillt** [comment]
@gauravk-in you pull-request template tells you how to do it - did you read the preset text?

> You can trigger @packagecontrol-bot to re-evaluate your pull request
> by pushing a commit or closing and reopening your pull request.

**Comment by gauravk-in** [comment]
Hi, I have removed the key bindings as suggested. I request you to review this pull request.

**Comment by FichteFoll** [comment]
You'll want to update your readme to mention using the Command Palette instead of key bindings.

**Comment by mgaitan** [comment]
Hi, I'm wondering why this package is not available to install.

**Comment by FichteFoll** [comment]
It is again now https://packagecontrol.io/packages/cheat_sh. Package Control's crawler seems to be hitting github's API rate limit more often lately and probably needs to become a bit more robust.

**Pull request merged**
