### PR TITLE
Add QNav package

### PR DESCRIPTION
**Pull request by ta-tikoma**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Your code uses a weird mixture of foward and backward slashes for paths in various places. You should unify them at some point to the platform's default (preferrably directly after user input) and then use `os.path` methods to join and split them.

**Comment by ta-tikoma** [comment]
Thanks, I unify slash. See:
https://github.com/ta-tikoma/QNav/blob/8f35092df0ed77d360e5d4229296eabae228b920/QNav.py#L9
and
https://github.com/ta-tikoma/QNav/blob/8f35092df0ed77d360e5d4229296eabae228b920/QNav.py#L53

**Comment by FichteFoll** [comment]
This is not at all what I said.

You can retrieve the platform's pathsep via `os.path.sep`, though you'll rarely need it. Instead, use other methods of the `os.path` module like `os.path.join` or `os.path.split`.

**Comment by ta-tikoma** [comment]
Oh, Thanks again.
I updated my code.
This is really better.

**Pull request merged**
