### PR TITLE
added lestle theme

### PR DESCRIPTION
**Pull request by lewislepton**

### CODE REVIEW

**Comment by FichteFoll** [comment]
You'll need to change `"branch": "master"` to `"tags": true` and use tags to create releases and push valid [semantic version](http://semver.org) tags to your repo. As mentioned [in the docs](https://packagecontrol.io/docs/submitting_a_package#Step_4), we no longer accepts branch-based releases for new packages.

**Comment by FichteFoll** [comment]
You didn't push a tag.

**Comment by lewislepton** [comment]
oooh sorry. just been busy and completely forgot. how do you do tags?

**Comment by FichteFoll** [comment]
Check out https://github.com/lewislepton/lestle.tmTheme/tags

**Comment by lewislepton** [comment]
cool spot. thanks you .done ;)

**Pull request merged**
