### PR TITLE
added metro colour scheme package

### PR DESCRIPTION
**Pull request by iJohnPaul**

### CODE REVIEW

**Comment by braver** [comment]
You probably want to add the "color scheme" labels to make your package easier to find.

You're also still using a tmTheme file. If you're only targeting Sublime Text, you'll want to convert that to a sublime-color-scheme file. That format supports variables and is a 1000x easier to maintain. You can do a conversion within Sublime Text via the Tools>Developer menu.

**Comment by iJohnPaul** [comment]
Yeah, that makes sense. I have converted it now.

**Comment by jrappen** [comment]
You probably want to complete the list of globals. The current docs give you a list:

<https://www.sublimetext.com/docs/color_schemes.html#global_settings:ver-dev>

**Comment by braver** [comment]
Also, please add the "color scheme" labels to make your package easier to find.

**Comment by braver** [comment]
Let me know what you think of that last bit of feedback and we'll re-open.

**Pull request closed without merging**
