### PR TITLE
Add new HaoGist plugin

### PR DESCRIPTION
**Pull request by xjsender**
Add new HaoGist plugin

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please make use of the new dependencies feature and require `requests` instead of bundling it in your package: https://github.com/packagecontrol/requests

@codemil, can you comment on the state of your Gist package? Would you be interested in adding @xjsender as a contributor so that we don't have two packages doing very similar things?

**Comment by xjsender** [comment]
@FichteFoll , thanks for your tip about dependency part, I have already used this feature in my plugin.

I remember, I requested a ```refresh gist``` feature from that plugin but no response since half a year ago.

Honestly, gist was blocked in china half a year ago, I can only use gist Api to manage my gists, however, there is no thread process and cache in that gist plugin, so I can only develop my own plugin to manage my gists.

Thanks.

**Comment by FichteFoll** [comment]
I will wait a few days for @condemil to read and reply before merging.

**Comment by condemil** [comment]
@FichteFoll, thanks for summoning me here. I think it will be better to keep on the collaborated development of one feature-rich plugin.

@xjsender, if your ready to merge everything together and support only one package I'm fine to add you as a contributor.

**Comment by xjsender** [comment]
@FichteFoll , I am not intended to merge something to ```gist``` plugin, can you please just merge this plugin?

**Comment by FichteFoll** [comment]
Well, it's sad that you are unwilling to collaborate, but I won't force you to. You should be aware of advantages and disadvantages by now.

**Pull request merged**
