### PR TITLE
add my plugin difinitions.

### PR DESCRIPTION
**Pull request by ekazyam**
It'll add a separator file to open file list .

### CODE REVIEW

**Comment by wbond** [comment]
I think a snippet would be more appropriate for this instead of a whole python-based package.

**Comment by ekazyam** [comment]
Thanks. I'm going to try it.

**Comment by ekazyam** [comment]
Which part should i cut for snippet ?

**Comment by ekazyam** [comment]
Thanks. I'm going to try it.
Which part should i cut for snippet ?

**Comment by ekazyam** [comment]
Thanks. I'm going to try it.
In Python rather , do you think that there is a good plug -ins using a snippet?

**Comment by ekazyam** [comment]
If you use a snippet , you can not use a temporary file using the scratch buffer . I thought you do not want to save when you close the source code .

**Comment by FichteFoll** [comment]
I do not understand the purpose of this package. It creates a new file, makes it a scratch view and then adds some separator line to it. What for?

**Comment by ekazyam** [comment]
I will open a lot of files while working . Therefore , in the case of the tab display , management is troublesome . Therefore , I have to hide the tab . List of files I'm sure in the OPEN FILES of sidebar . At that time , since the request had colleagues that want a separator to identify the files for each application , it has been created . However, in management by the tab display , this plug -in is meaningless .

**Comment by FichteFoll** [comment]
Ah, I understand. In that case I would rather use a name like "SeparateOpenFiles" or "SidebarSeparator" and use `view.set_name` directly instead of adding a new line. Also, I would advise to additionally set `view.set_read_only(True)`.

**Comment by FichteFoll** [comment]
Oh, and you must not provide `package-metadata.json` in your repository. Please remove it.

**Comment by ekazyam** [comment]
Thanks.
I will do the modification .

**Comment by ekazyam** [comment]
Modification has been completed . Because you have changed the package name , my repository also has been changed . Whether it is better that sent again pull request ?

**Comment by ekazyam** [comment]
Modification has been completed . Because you have changed the package name , my repository also has been changed . Whether it is better that sent again pull request ?

**Comment by ekazyam** [comment]
Modification has been completed . Because you have changed the package name , my repository also has been changed .

**Pull request merged**
