### PR TITLE
Transferring ownership of the Element Finder package to thinkv

### PR DESCRIPTION
**Pull request by keeganstreet**
@thinkv has updated the package for Sublime Text 3.

### CODE REVIEW

**Comment by thinkv** [comment]
Might need to move it up in the order @keeganstreet 
`Repositories must be sorted alphabetically`

**Comment by keeganstreet** [comment]
Thanks @thinkv, fixed alphabetisation now.

**Comment by thinkv** [comment]
Hi @wbond,

My packages.json has a hybrid of URL releases and then the main channel with tagged releases, is that not possible?

If not, I have made the change to point to the version number instead.

**Comment by wbond** [comment]
The current run of the tests is:

```
2 Warnings
 - Creating a readme for your package will help users understand what it does and how to use it
 - '.no-sublime-package' is defined. Please verify that it is *really* necessary
```

You should probably add a `"readme"` entry, or use `"details"` instead of `"homepage"`, in which case it will pick up the existing readme and issues from the GitHub repo.

**Comment by thinkv** [comment]
Thanks @wbond, have made the changes now.

**Pull request merged**
