### PR TITLE
Update with Sass Compiler

### PR DESCRIPTION
**Pull request by enagic**

### CODE REVIEW

**Comment by FichteFoll** [comment]
`sublime.load_settings` will not necessarily be available when it is reached in the code (due to the API lazy-loading). It is guaranteed to succeed if called when or after a `plugin_loaded` callback has been run however.

You have to push a valid [semantic version](http://semver.org) [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) (with optional leading `v`) to your repo.

**Comment by FichteFoll** [comment]
@enagic ping

**Comment by enagic** [comment]
Thanks for the reminder. Let me check in my changes tonight.

**Comment by enagic** [comment]
Done.

**Comment by FichteFoll** [comment]
I forgot to list that you also need to change `"branch": "master"` to `"tags": true`.

**Comment by enagic** [comment]
Yep.

**Comment by enagic** [comment]
Sorry, that means "done" in some part of the world... I just don't know
which yet.

**Comment by FichteFoll** [comment]
Did you perhaps forget to push?

**Comment by enagic** [comment]
I thought it was something that can be done through the UI.  I'm finding it
hard to find an answer from Google on how its done.  What's the command for
it?  I'm using CLI.

**Comment by FichteFoll** [comment]
http://stackoverflow.com/questions/5195859/push-a-tag-to-a-remote-repository-using-git

`git push --tags` or `git push origin <tagname>`

**Comment by FichteFoll** [comment]
@enagic ping

**Comment by enagic** [comment]
I appreciate your persistence. However, I think I might have to retract my
request for this project because my bandwidth is getting thinner for now.

**Pull request closed without merging**
