### PR TITLE
Laravel Blade Snippets

### PR DESCRIPTION
**Pull request by laravelish**

### CODE REVIEW

**Comment by FichteFoll** [comment]
How does this compare to [the others](https://packagecontrol.io/search/laravel%20snippets)?

**Comment by DeeJaVu** [comment]
Hi @FichteFoll i will add my own snippets, i tried others on st3 wich did not work

**Comment by laravelish** [comment]
Hi @FichteFoll i will add my own snippets, i tried others on st3 wich did not work

**Comment by FichteFoll** [comment]
This is not a comparison. In an attempt to maintain a diverse package list with few to no duplicates, please try to explain to me why you believe a separate package is necessary.

**Comment by laravelish** [comment]
whatever i will do it manually

**Pull request closed without merging**
