### PR TITLE
Add GetCode

### PR DESCRIPTION
**Pull request by Salil03**
This adds https://github.com/Salil03/GetCode to the default channel.
This is a ST3 plugin which:

Gets the program name in the form of the url from Codeforces/Codechef
Parses the problem page
Generates a program file (default: .cpp file) with ready made code (snippet)
Opens the file in current window

### CODE REVIEW

**Comment by Salil03** [comment]
This adds https://github.com/Salil03/GetCode to the default channel.
This is a ST3 plugin which:

- Gets the program name in the form of the url from Codeforces/Codechef
- Parses the problem page
- Generates a program file (default: .cpp file) with ready made code (snippet)
- Opens the file in current window

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Thom1729** [comment]
I don't understand what this package does. What is "Codeforces/Codechef"?

**Comment by Thom1729** [comment]
Could you resolve the merge conflict?

You should add a license.

```python
    if not os.path.exists(dir_path):
        os.makedirs(dir_path, mode=0o777)
        os.chmod(dir_path, 0o777)
```

This contains a race condition. Instead, call `os.makedirs(dir_path, mode=0o777, exist_ok=True)`.

```python
    try:
        open(filename, "a").close()
        return filename
    except Exception as e:
        print ("Exception: ", e)
        sublime.error_message(
            "Unable to create file: 'Permission denied'," +
            " please specify another folder in Codeforces.sublime-settings" +
            " or change the permissions of the folder")
        return None
```

How do you know that the error was due to permissions?

```python
        snippets_file = open(snippets_file_name)
        try:
            snippets_content = snippets_file.readlines()
            snippets_file.close()
        except Exception as e:
            sublime.error_message("File not found " + snippets_file)
            print (e)
            snippets_file.close()
            return
```

Same here. In addition, you should use `with open(snippets_file_name) as snippets_file:` rather than trying to close it manually.

```python
open(file, 'w').writelines(snippets_content)
```
You never close this handle. Use `with` here.

```python
sublime.active_window().open_file(file)
```

You probably want to return `file` from `fetch` and move this line out to the `CodeforcesProblemCommand` as `self.view.window().open_file(file)`.

**Comment by Salil03** [comment]
@Thom1729 What is a merge conflict?

**Comment by Salil03** [comment]
@Thom1729  Please see my latest release on [Getcode](https://github.com/Salil03/GetCode/releases)

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Salil03** [comment]
@Thom1729 I have done all the changes you have suggested. Is there anything else?

**Comment by Salil03** [comment]
@Thom1729 @FichteFoll Please reply

**Comment by Salil03** [comment]
@Thom1729 @FichteFoll @wbond I have made all necessary changes and resolved the merge conflict. Can this package be accepted, please? I have been waiting for over a week.

**Comment by Salil03** [comment]
@packagecontrol-bot

**Comment by Thom1729** [comment]
```python
if not os.path.exists(dir_path):
        os.makedirs(dir_path, mode=0o777, exist_ok=True)
```
You don't need `if not os.path.exists(dir_path):`; that's the point of `exist_ok=True`.

```python
sublime.error_message("File not found " + snippets_file)
```
You're catching `Exception`, not `FileNotFoundError`.

**Comment by Salil03** [comment]
@Thom1729 I have made the required changes

**Comment by Salil03** [comment]
@Thom1729 I have also added [Virtual Judge Functionality](https://vjudge.net/) in the latest [release](https://github.com/Salil03/GetCode/releases/tag/0.3.0)

**Comment by FichteFoll** [comment]
Please rebase onto current master. Due to a previous merge, you're removing the `Gettext` package in your PR.

Normally, just providing Command Palette entries (and maybe menu items) is enough. Ideally, the user should add key bindings by themselves as there are only so many bindings available, but the number of packages (with bindings) keeps growing.

You don't need to close file handles when creating them in a `with` block. (Optional fix.)

I don't think describing all settings as "mandatory" but then falling back to the working dir when creating files is a good idea UX-wise. I suggest to check whether the  settings are set and then abort with an error message when they are not. The working directory of a Sublime Text process is generally **unpredictable** and should *not* be used in plugin code.

**Comment by Salil03** [comment]
@FichteFoll Can't you just upload the package as it is?

**Comment by FichteFoll** [comment]
Yes, I can. I still highly suggest you check out my last remark regarding the working directory, however. Key binding conflicts are annoying but not as important, imo.

**Comment by Salil03** [comment]
@FichteFoll Why can't I see my package in sublime text package control?

**Comment by FichteFoll** [comment]
It takes up to one hour to update.

**Comment by Salil03** [comment]
@FichteFoll I still can't see my package on package control.

**Pull request merged**
