### PR TITLE
Created the DiffMatchPatch dependency

### PR DESCRIPTION
**Pull request by evandrocoan**
https://github.com/evandroforks/DiffMatchPatch

### CODE REVIEW

**Comment by Thom1729** [comment]
I don't think the `.no-sublime-package` file does anything for dependencies.

Is all of the code necessary? If only the python3 code is used, perhaps the rest should be removed.

**Comment by evandrocoan** [comment]
The .no-sublime-package file does nothing. 

The other code is there because I just forked the repository and added the loader code for Sublime Text. I just removed it.

**Comment by Thom1729** [comment]
Could you remove the `.no-sublime-package` file too, if it doesn't do anything?

**Comment by evandrocoan** [comment]
DOne

**Pull request merged**
