### PR TITLE
Added the SpotifyWeb plugin.

### PR DESCRIPTION
**Pull request by agilesteel**

### CODE REVIEW

**Comment by agilesteel** [comment]
Hi,

I'm using an external library that reads and writes from/to files. Therefore I cannot use the sublime.load_resource API. I hope this pull request will be accepted. It's the first time I'm submitting a package into packagecontrol.

Cheers
Vlad

**Comment by FichteFoll** [comment]
spotipy uses relative imports internally, so you can just import it relatively as well instead of modifying `sys.path`. 

Just move `lib/spotipy-2.4.4/spotipy` to `lib/spotipy` (and delete everything else except for the license) and then write `from ...lib import spotipy`. The number of dots depends on how deeply nested you are within `src` of course.

**Comment by agilesteel** [comment]
Cool, good to know!

I just did it here https://github.com/DevInsideYou/SpotifyWeb/commit/2bf3743d0a4a0581268c4e251744b9053c43b610

I'm relatively new to python. Does this mean that I don't need the .no-sublime-package file anymore?

Let me know and I'll remove it!

Thx for the help!

**Comment by FichteFoll** [comment]
>Does this mean that I don't need the .no-sublime-package file anymore?

Yes, exactly.

**Comment by agilesteel** [comment]
Awesome!

Done https://github.com/DevInsideYou/SpotifyWeb/releases/tag/v0.0.6

**Comment by agilesteel** [comment]
Hi again,

thanks for accepting my package!

The removal of the .no-sublime-package file seems to prevent me from opening the settings file for my plugin. Would you be so kind to look at line 38 of https://github.com/DevInsideYou/SpotifyWeb/blob/master/src/sublime/SettingsManager.py#L38 and tell me if there is some packagecontrol API that would help me out with that? As of right now I'm trying to open the Packages/SpotifyWeb/SpotifyWeb.sublime-settings file but the SpotifyWeb folder doesn't exist since the plugin is packaged by packagecontrol.

Sorry to bother...

**Comment by FichteFoll** [comment]
You can use the `edit_settings` command, which has been added in a dev build around 3100. It provides the same functionality, basically. Examples are in the default menu (and commands) file. 

Other than that, you can tell ST to load files from the packages using the open_file command and specifying the path as $packages/SpotifyWeb/... This is, to my knowledge, the only way to make st open virtualized resource files.

**Pull request merged**
