### PR TITLE
Add Zukan Icon Theme

### PR DESCRIPTION
**Pull request by 53v3n3d4**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [ ] My package doesn't add context menu entries. *
- [x] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [ ] If my package is a syntax it is named after the language it supports (without suffixes like "syntax" or "highlighting").
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is ...

There are no packages like it in Package Control.

My package is similar to A File Icon and FileIcons. It is different if we consider it uses mostly original icons. And, also there are file icons that do not have on other packages, as of today.

It is part of my original theme, which I split in 3 parts: theme, color-scheme and file icons.

Sorry for reposting, I deleted my fork thinking that it would not affect here. I was wrong.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
I'm getting an error, even after restarting ST a few times:
```
No such file or directory: '/Users/.../Sublime Text/Packages/Zukan Icon Theme/icons_preferences'
```

**Comment by braver** [comment]
Otherwise, looks like a nice addition :)

**Comment by 53v3n3d4** [comment]
Hi Braver,

> I'm getting an error, even after restarting ST a few times:
> 
> ```
> No such file or directory: '/Users/.../Sublime Text/Packages/Zukan Icon Theme/icons_preferences'
> ```

I will check this. I think you test the main repo.

But I will double check and confirm when fix it.

I changed data file because of some settings options that I am still doing, and this folder now needs to be created. Sorry.

Thanks.

**Comment by braver** [comment]
> I think you test the main repo.

Oh, yeah, I just checked out your repo (to the correct directory though). Let me know what you find out, it might have just been my mistake!

**Comment by 53v3n3d4** [comment]
Hi Braver,

I checked and fixed the error, so main repo should work. I released a new version with this change.

Thanks.

**Pull request merged**
