### PR TITLE
Add the Hotspots package

### PR DESCRIPTION
**Pull request by x0th**
- [x] I'm the package's author and/or maintainer.
- [x] I have have read [the docs][1].
- [x] I have tagged a release with a [semver][2] version number.
- [x] My package repo has a description and a README describing what it's for and how to use it.
- [x] My package doesn't add context menu entries. *
- [ ] My package doesn't add key bindings. **
- [x] Any commands are available via the command palette.
- [x] Preferences and keybindings (if any) are listed in the menu and the command palette, and open in split view.
- [x] If my package is a syntax it doesn't also add a color scheme. ***
- [x] I use [.gitattributes][3] to exclude files from the package: images, test files, sublime-project/workspace.

My package is a Rust profiler inside Sublime Text

There are no packages like it in Package Control.

[1]: https://packagecontrol.io/docs/submitting_a_package
[2]: https://semver.org
[3]: https://www.git-scm.com/docs/gitattributes#_export_ignore

### CODE REVIEW

**Comment by braver** [comment]
Does your package really need the keybindings?

**Comment by braver** [comment]
Please respond to the feedback to continue the PR.

**Comment by x0th** [comment]
I understand that since the number of keyboard shortcuts is limited, it is better to release a plugin without them.
For Hotspots, keybindings were more of a convenience thing. I have removed them in patch 1.0.1.
Let me know if I need to edit the PR.

**Comment by braver** [comment]
Excellent, thanks. One final thing to look at would be to open the settings in split view, instead of having to separate menu entries. Have a look around for examples, most modern packages use that feature.

**Comment by x0th** [comment]
I introduced split-view settings in 1.0.2.

**Pull request merged**
