### PR TITLE
Add One Command Syntax package

### PR DESCRIPTION
**Pull request by yrsegal**

### CODE REVIEW

**Comment by FichteFoll** [comment]
The lack of a readme for the actual "OneCommand" repo is kind of a bummer.

**Comment by FichteFoll** [comment]
Oh, I actually forgot to mention this, but you can use relative imports in Sublime Text, via `from .OneCommand import oneCommand` (ST3) and `from OneCommand import oneCommand` (ST2). That way you don't need to mess with sys.path.

**Comment by yrsegal** [comment]
Yeah, agreed (but it's technically @destruc7i0n's project so I don't want to touch it)

**Comment by yrsegal** [comment]
Fitchte, it wasn't working for some reason so I used sys.path.

**Pull request merged**
