### PR TITLE
add webloc

### PR DESCRIPTION
**Pull request by looking-for-a-job**

### CODE REVIEW

**Comment by Thom1729** [comment]
What's the story here? What happened to the old repository?

**Comment by looking-for-a-job** [comment]
Thom1729, probably it was  one of my firsts pr on github, I was tired of waiting, deleted the repository and unsubscribed, and it was merged but not available all this time :)

**Comment by Thom1729** [comment]
Instead of `sys.platform`, you should use `sublime.platform`.

You should also add `"previous_names": "Webloc-open"` to the channel entry.

**Comment by looking-for-a-job** [comment]
fixed

**Pull request merged**
