### PR TITLE
Add SublimeLinter-contrib-verilator

### PR DESCRIPTION
**Pull request by poucotm**
Please provide the following information:

 - Link to your code repository: https://github.com/poucotm/SublimeLinter-contrib-verilator
 - Link to the tags page with at least one [semver](http://semver.org) tag: https://github.com/poucotm/SublimeLinter-contrib-verilator/tree/1.0.0

Also make sure you:

 1. Used `"tags": true` and not `"branch": "master"` ([versioning docs](https://packagecontrol.io/docs/submitting_a_package#Step_4))
 2. Ran the tests ([tests docs](https://packagecontrol.io/docs/submitting_a_package#Step_7))

### CODE REVIEW

**Comment by AlexKvazos** [comment]
Can you please run tests locally and fix them?

**Comment by beaugunderson** [comment]
I think SublimeLinter plugins should be added to https://github.com/SublimeLinter/package_control_channel and not here, no?

**Comment by FichteFoll** [comment]
@beaugunderson yes, and there's also a PR for this already: https://github.com/SublimeLinter/package_control_channel/pull/39

@groteworld, is there anything specific holding this back or just a lack of time?
A long time ago, @aparajita asked us to not accept plugins for SublimeLinter and instead redirect them to the repo referenced by @beaugunderson. If you'd like this to change, please comment on it here, though I personally like it the way it is currently (grouping SublimeLinter plugins in a more or less SublimerLinter-managed repo).

**Comment by groteworld** [comment]
Sorry for the slow reply, @poucotm. https://github.com/SublimeLinter/package_control_channel/pull/39 didn't see any comment because it was not under proper review, layed out in the [preparing for publication documentation](http://www.sublimelinter.com/en/latest/creating_a_linter.html#preparing-for-publication) (probably something i need to start stating. Please accept my apology). I see now that then you posted https://github.com/SublimeLinter/SublimeLinter3/issues/585 and i must have just missed that issue. I will review during my lunch break in 20 minutes.

Please feel free to close this issue.

**Comment by poucotm** [comment]
Thank you all!

**Pull request closed without merging**
